### ISSUE TITLE
filter_reset does not  work if multiple tables use the same DOM

### ISSUE THREAD

**Issue by simongcc** [Mottie/tablesorter#1001]
I have several tables and of each using column filter widgets, the filter_reset work fine if each table assign different DOM to control but it doesn't work if all point to the same.
For instance, I have a button to reset all views, it is not appropriate to make 3 different buttons.
Is the design feasible or not contradict to the spirit of the design to make it multiple tables binding to same filter_reset button?

Thanks.

**Comment by Mottie** [comment]
Hi @simongcc!

Thanks for reporting this issue. It will be fixed within the master branch shortly.
