### ISSUE TITLE
How to change background on the filtered columns?

### ISSUE THREAD

**Issue by crazyserb** [Mottie/tablesorter#1006]
I couldn't find this anywhere - what do I need to do to bind some sort of a class to all the columns (or td's and th's in specific columns) that were filtered in one way or another (whether that's select, text input, search, etc), so that I can visually see which columns were filtered (it's a pain in the ass to scroll left and right with around 40-50 columns in place and try to figure out which ones you used a filter on)?

Any ideas?

Thanks!

**Comment by Mottie** [comment]
Hi @crazyserb!

[Here is a demo](http://jsfiddle.net/Mottie/856bzzeL/637/)

Start with this css. It's defined this way to give it greater specificity than the definition from the theme:

```css
.tablesorter .tablesorter-filter-row .hasFilter {
    background: #0080ff; /* choose any color */
}
```

Then use the [`filterEnd` event](http://mottie.github.io/tablesorter/docs/#filterend) to add classes to filter cells that have a value:

```js
$(function () {
    $('table').tablesorter({
        theme: 'blue',
        widgets: ['zebra', 'filter']
    }).on('filterEnd', function (event, config) {
		var lastSearch = config.$table.data('lastSearch'),
        	$f = config.$filters;
        $f
        	.removeClass('hasFilter')
        	.each(function( index ) {
        		if ( lastSearch[ index ] !== '' ) {
                    $f.eq( index ).addClass( 'hasFilter' );
                }
        	});
    });
});
```

To get the last search, you can use the [`getFilters` function](http://mottie.github.io/tablesorter/docs/#function-getfilters) or just grab it from the table data (`config.$table.data('lastSearch')`); which is what the `getFilters` function does anyway.

**Comment by crazyserb** [comment]
Beautiful!

Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
