### ISSUE TITLE
How to refresh Ajax pager widget after modify the rows data ?

### ISSUE THREAD

**Issue by don750421** [Mottie/tablesorter#1008]
I want to let user modify the table data.
When user click the button top of the table.and the button will call the function.

![image](https://cloud.githubusercontent.com/assets/13444821/9654477/a470266a-525d-11e5-89cc-da1bf53ff7ae.png)

my code is...
````
function ChangeRTStatus(ChangeStr)
        {
            var arrSelItem = [];
            $('#tJobAssign').find('input[type="checkbox"]:checked').each(function (idx,row) {
                arrSelItem.push($(this).val().trim());
            });

            if (arrSelItem.length < 1)
            {
                alert("Please select one RT before change.");
            } else {
                $("#divChangeRTStatus").dialog({
                    resizable: false,
                    modal: true,
                    title: "RT Change Confirm",
                    height: 230,
                    width: 370,
                    buttons: {
                        "Yes": function () {
                            $.ajax({
                                url: "/Handler/Handler.ashx?WorkType=CHANGERTSTATUS",
                                type: "POST",
                                async: false,
                                data: {
                                    DataType: ChangeStr,
                                    DataKey: arrSelItem.join(",")
                                },
                                dataType: "json",
                                success: function (data, textStatus, jqXHR) {
                                    if (data.Result) {
                                        $("#tJobAssign").trigger('updateAll');
                                        //gv_JobAssignTable.trigger('update');
                                        $("#divChangeRTStatus").dialog().dialog('close');
                                    }
                                    else {
                                        alert("Some RT update status error.RT:" + data.RtnMsg);
                                    }
                                },
                                error: function (jqXHR, textStatus, errorThrown) {
                                    alert("Error '" + jqXhr.status + "' (textStatus: '" + textStatus + "', errorThrown: '" + errorThrown + "')");
                                }
                            });                         
                        },
                        "No": function () {
                            $(this).dialog('close');
                        }
                    }
                });
                $("#divChangeRTStatus").dialog("open");
            }
````
if the update ajax return success ,the table column 6 and column 9 (red square) data will be change(like first row.)
but I used the update or updateall,the update is not work.
````
                                        $("#tJobAssign").trigger('updateAll');
                                        //gv_JobAssignTable.trigger('update');
````
How to correctly refresh my table after update data.
Thanks.

**Comment by Mottie** [comment]
Hi @don750421!

Don't use "updateAll" unless the header changes.

I'm sorry I can't read the language in the screenshot. If the user is changing the value of the table directly inside the table, then all you would need is to trigger an update. If the user is changing the value in that dropdown, then you'll need to add the changes into the table, then trigger an "update":

```js
// target the cell and add the new data
$('td.toUpdate1').html( newData1 );
// ...
$('td.toUpdateN').html( newDataN );

// trigger update after all cells have been updated
$('table').trigger('update');
```

**Comment by don750421** [comment]
Hmm,OK,maybe you don't know my problem. (Sorry,my English is very basic)
When user check the row (the checkbox by row) that user want to modify.
then user will click the dropdown list item which they want to change.
and the dropdown item will call ajax function to modify the row data in the database.
so...my change data in the database with the ajax function. (in my last post)

so,when I change the data success with ajax.I want to refresh the data in the tablesorter.
let user look the newest data.
so, i want to trigger an update to get the newest data from database with ajax.
but when i use the trigger an 'update',the tablesorter is not refresh.
(include the checkbox is not unclear )
````
  $("#tJobAssign").trigger('update');
````

**Comment by Mottie** [comment]
Ok, try these changes...

Save the `$row` being changed:

```js
var arrSelItem = [],
	$row = $('#tJobAssign').find('input[type="checkbox"]:checked').each(function (idx,row) {
	arrSelItem.push($(this).val().trim());
});
```

Then update the row if the ajax was successful:

```js
if (data.Result) {
	$row.each(function( index ){
		$(this).html( arrSelItem[ index ] );
	});
	$("#tJobAssign").trigger('update');
	$("#divChangeRTStatus").dialog().dialog('close');
}
```

**Comment by don750421** [comment]
Thanks @Mottie 
If used the your method.
Is these only change the row that user selected?
all of the setup (contain sort , filter?)will be update ?
because the user change data inside the tablesorter is on the sixth column,
if the change only update the row ,and the table is filter by desc will fail..

so . may i have any method to tirgger update all of the table with ajax ?
or i have any method to update the row data?(contain sort.filter)?

**Comment by Mottie** [comment]
Maybe use [`addRows`](http://mottie.github.io/tablesorter/docs/#addrows)?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
