### ISSUE TITLE
Populate select filter column with Ajax

### ISSUE THREAD

**Issue by likedo** [Mottie/tablesorter#1010]
Hi, thanks for the support.
I get the test JSON with Ajax and return it:

```js
filter_selectSource : {
    2:function(table, column, onlyAvail){
        return $.getJSON("../admin/callbacks/getSelectFilterSearch.php",function(data){
            return data.hasOwnProperty('options') ? data.options : false;
        });
    }
}
```

The JSON is: `{"options":["a","b","c"]}`

How do you fill the select with the json?

Thanks!

**Comment by Mottie** [comment]
Hi @likedo!

It appears that the `filter_selectSource` is being used correctly and should fill the select with that array returned by JSON.

If it isn't working:

* Are you seeing any errors in the console?
* Is `2` the correct zero-based column index?
* Does that column have `filter-select` class name added? Or set the [`filter_functions` option](http://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html#default_select) for that column to `true`.
* Is the filter widget working in other columns? If not, is it being loaded correctly?
* Is tablesorter v2.16+ being using with the filter widget? Ideally, use the most up-to-date version of both tablesorter and the filter widget.

Sorry for all the questions; but a little more information is needed to help troubleshoot the problem. And that is all the questions I can think of for right now.

**Comment by likedo** [comment]
Hi, thanks for your answer.
You are right, i was quick to respond :).

I did more tests and will answer your questions. 

The first example works (without ajax):

filter_selectSource : {
        		// Alphanumeric match (prefix only)
        		// added as select2 options (you could also use select2 data option)
        		2 : function(table, column) {
          			return ['1', '2', 'bla bla'];          			
        		}
      		}	

The second example does not work (with ajax):

filter_selectSource : {
        		// Alphanumeric match (prefix only)
        		// added as select2 options (you could also use select2 data option)
        		2 : function(table, column) {          			
          			return $.getJSON("../admin/callbacks/getSelectFilterSearch.php",function(data){													
			            return data.hasOwnProperty('options') ? data.options : false;			            			            			            
					});
        		}
      		}


The file php called is:

<?php
$arr = array('1','2','bla bla');
echo json_encode(array('options'=>$arr));
?>

My answers to your questions should be ok. Maybe it's a problem of JSON.

Thank you very much!

**Comment by Mottie** [comment]
Hmm, I just did some testing and I think the problem might actually be in the filter widget... let me investigate further.

**Comment by likedo** [comment]
Ok! Thanks for the support :)

**Comment by Mottie** [comment]
Well, the method I have in the docs doesn't work, change the `filter_selectSouce` to something like this:

```js
filter_selectSource : {
    // Alphanumeric match (prefix only)
    // added as select2 options (you could also use select2 data option)
    2 : function(table, column) {
        // call ajax after tablesorter has initialized; this prevents
        // multiple ajax calls during initialization
        if (table.hasInitialized) {
            $.getJSON("../admin/callbacks/getSelectFilterSearch.php", function(data){
                var result = data.hasOwnProperty('options') ? data.options : false;
                $.tablesorter.filter.buildSelect( table, column, result, true );
            });
        }
    }
}
```

I'll update the docs to reflect this change.

**Comment by likedo** [comment]
Thanks!
With this code now appears an error in console:
"Uncaught TypeError: Cannot read property 'length' of undefined" ----- jquery 2.1.1 line 2.

Do you agree?

**Comment by Mottie** [comment]
Yeah, I forgot to include a `return false` when I first posted the solution... it's in the code now.

**Comment by likedo** [comment]
Oh it is true ! Thanks!

**Comment by Mottie** [comment]
I just split out some code & made it into a new function:

```js
var array = $.tablesorter.filter.processOptions( table, column, array );
```

This function basically sorts & removes duplicates from the array. I did this because in [this demo](http://jsfiddle.net/Mottie/uwZc2/52/), filltext.com is used to provide random ajax data, but the content is provided unsorted, and the filter doesn't work - filltext doesn't provided this server-side functionality.

**Comment by likedo** [comment]
Great works!
Last question...I can separate the values ​​of the select between "value " and "text "?

<select>
    <option value="1"> Test 1 </option>
    <option value="2"> Test 2 </option> 
</select>

...because the value is a fk table and the "text" is description field of table. Can be done changing the JSON returned?

as well:

<?php
$arr = array('1','2','bla');
echo json_encode(array('options'=>$arr));
?>

<select>
<option value="1"> 1 </option>
<option value="2"> 2 </option>
<option value="bla"> bla </option>
</select>

in so (..for example):

<?php
$arr = array('a'=>'1' , 'b'=>'2', 'c'=>'bla');
echo json_encode(array('options'=>$arr));
?>

<select>
<option value="a"> 1 </option>
<option value="b"> 2 </option>
<option value="c"> bla </option>
</select>

Thanks!

**Comment by Mottie** [comment]
I'm not so good with php, but you could just return JSON that looks like this:

```js
{
    "data": [{
            "value": "a",
            "text": 1
        }, {
            "value": "b",
            "text": 2
        }, {
            "value": "c",
            "text": "bla"
        }]
}
```

or, you could simplify the JSON by letting the [`filter_selectSourceSeparator` option](http://mottie.github.io/tablesorter/docs/#widget-filter-selectsource-separator) do the work and return data like this:

```js
{ "data": [ "a|1", "b|2", "c|bla" ] }
```

**Comment by likedo** [comment]
Perfect! 
This method { "data": [ "a|1", "b|2", "c|bla" ] } works correctly! 
Thanks for now!

**Comment by azjol** [comment]
Hello Mottie,
is it possible to build more filters than just one via JSON? I mean filters for more headers. Can you eventually send some example?
Thank you.

**Comment by Mottie** [comment]
Hi @azjol!

Please explain further. What do you mean by more filters for more headers? Where are the headers?

Maybe what you're looking for is the [`$.tablesorter.filter.bindSearch` function](https://mottie.github.io/tablesorter/docs/#function-bindsearch). Duplicate the filter row anywhere, then use this function to tie it to the table.

**Comment by azjol** [comment]
Ok, I will try:
JSON returns data for three filters to the three columns. By headers I mean columns, sorry.

JSON Example:
```
{ 
"1": [ "a|1", "b|2", "c|bla" ],"2": [ "a|1", "b|2", "c|bla" ],"3": [ "a|1", "b|2", "c|bla" ] 
}
```
so final script will look like:
```
      filter_selectSource : {
        1: [ "a|1", "b|2", "c|bla" ],
        2: [ "a|1", "b|2", "c|bla" ],
        3: [ "a|1", "b|2", "c|bla" ],
      },
```

**Comment by Mottie** [comment]
You can already do that. If you look at the [`filter_selectSourceSeparator` docs](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource-separator), you'll see an example similar to that. Although, if all columns have the same options, you can set it with a class name instead:

```js
filter_selectSource : {
  ".select-options": [ "a|1", "b|2", "c|bla" ]
},
```

**Comment by azjol** [comment]
Okay, this is cool and what about ajax, which returns data for 3 filter-selects, is it possible to parse it? Because I do not want to call ajax three times for each filter-select.

**Comment by Mottie** [comment]
If you look at the [`filter_selectSource` option docs](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource), you'll find the last example which obtains the filter select data via ajax.
