### ISSUE TITLE
Remembering Filtered data containing spaces

### ISSUE THREAD

**Issue by rancor1223** [Mottie/tablesorter#1012]
Hi,
I'm having trouble with remembering filters containing spaces. 

If for example I have a column with full names (e.g. Jon Doe), it won't save the filter. I'm using the code you posted in issue #146.

Is that a problem on my side or does the script not support such thing?

**Comment by Mottie** [comment]
Hi @rancor1223!

In v2.14, a [`filter_saveFilters` option](http://mottie.github.io/tablesorter/docs/#widget-filter-savefilters) was added which saves the filters for you automatically when set to `true` (default is `false`).

You can test [this demo](http://mottie.github.io/tablesorter/docs/example-widget-filter-any-match.html) by entering `n c` in the "First Name" column, or `y j` in the "Last Name" column, then reloading the page. The same row should show in both cases.

**Comment by rancor1223** [comment]
Ah, that works nice. 

However, I forgot to mention I'm trying to save 'select2' filters. And now that I think about it, that probably means there is not much you can do about it since it's an external plugin, right?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
