### ISSUE TITLE
Add ZenHub to readme?

### ISSUE THREAD

**Issue by feluraschi** [Mottie/tablesorter#1013]
Hey, I'm on the ZenHub.io team. I noticed this repo uses ZenHub task boards to organize issues.

To help contributors know to check the task boards for current priorities, what do you think about adding the ZenHub badge to your ReadMe (or contributor guidelines)? I'm happy to create a PR. A lot of people don't know ZenHub is free for open-source users :smile:

Thoughts?

**Comment by Mottie** [comment]
Hi @feluraschi!

Sure, I can add a badge, or you can submit a PR. Either way it'll get done.

**Comment by feluraschi** [comment]
Thanks @Mottie! I'll submit a PR :)

**Comment by feluraschi** [comment]
Thanks @Mottie :) Whatever is easiest for you! I'd be happy to submit a PR, where is a good place to include the badge?

**Comment by Mottie** [comment]
I got it, no worries ;)

**Comment by feluraschi** [comment]
Sounds good @Mottie :)

**Comment by Mottie** [comment]
Done
