### ISSUE TITLE
tablesorter instantiate more than one time

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1014]
I am having an issue with the instatiation of the tablesorter, 

since i have 2 tabs in my page, and i just implemented the group-date-day,

the problem is that this only is applied in the first tab, on the second one is not having effect, how can i make it work

**Comment by Mottie** [comment]
Hi @fcferreira29!

Please provide more details and share the code being used.

There is a demo showing [how to use tablesorter with jQuery UI tabs](http://jsfiddle.net/Mottie/abkNM/786/) on the [Home wiki page](https://github.com/Mottie/tablesorter/wiki). That page contains numerous demos and might help provide guidance for any future questions.

**Comment by fcferreira29** [comment]
the problem is when we load the page the 1st Tab has the group working, but when we change to the second tab the group is not in effect,

we are making instances to more than 1 tablesorter, because we may have more than 1 tab, 

is there a possibility that is having conflict with one another tab?

Thanks,

Fabio Ferreira

**Comment by Mottie** [comment]
The group widget only works on visible rows, so if all rows are hidden inside a tab, then once that tab is active, you'll need to trigger an 'applyWidgets' event on the table to re-apply the group setting. The code from the demo I shared above will take care of that problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
