### ISSUE TITLE
group-date-day issue

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1015]
can i group the date by day and day of the week? (it would be very helpfull to have this option) like (Out 18 Friday) something like this.

**Comment by Mottie** [comment]
Hi @fcferreira29!

If you look at the [group widget demo](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html#slider1), there is a date slider. Set it to "group-day-week" and you'll see that it sorts by day of the week.

Note that if you want to actually group the days of the week together, then you'll need to use the weekday parser (see [parser-date-weekday.js](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date-weekday.js)).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
