### ISSUE TITLE
IE9 console bug

### ISSUE THREAD

**Issue by LPology** [Mottie/tablesorter#1019]
The presence of `console.log` instead of `window.console.log` is triggering a known IE9 bug that can kill all Javascript execution on the page. 

More info in this Stackoverflow thread: http://stackoverflow.com/questions/7742781/why-javascript-only-works-after-opening-developer-tools-in-ie-once

The fix is very simple. Just replace all instances of console functionality, including `console.log`, `console.warn`, `console.group`, `console.groupEnd`, with `window.console.log`, `window.console.warn`, etc.

I've fixed it in my fork and have confirmed the fix works (VM tested). I can submit a pull request, but I don't have time to include unit tests along with it. Let me know if you would like me to submit it anyway without the unit tests.

Thanks

**Comment by thezoggy** [comment]
or just use a proper console wrapper?

**Comment by LPology** [comment]
I suppose that depends on what you mean by "proper console wrapper."

**Comment by thezoggy** [comment]
many legacy browsers dont have a console or dont have one loaded all the time. i guess we could just force the use of one by including one, but its simple enough to just add/most people already have one they use.

**Comment by Mottie** [comment]
I do define `console` in tablesorter ([ref](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L2091-L2099)):

```js
// set up debug logs
if ( !( console && console.log ) ) {
	ts.logs = [];
	/*jshint -W020 */
	console = {};
	console.log = console.warn = console.error = console.table = function() {
		ts.logs.push( [ Date.now(), arguments ] );
	};
}
```

What do I need to change to fix it?

**Comment by LPology** [comment]
Working on it right now. It may be simpler than I initially thought. This <em>may</em> do it:

```javascript
	// set up debug logs
	if ( !( window.console && window.console.log ) ) {
		ts.logs = [];
		/*jshint -W020 */
		console = {};
		console.log = console.warn = console.error = console.table = function() {
			ts.logs.push( [ Date.now(), arguments ] );
		};
	}
```

So far just adding `window` in front of `console` on line 2092 seems to be fixing it.

**Comment by thezoggy** [comment]
@Mottie I would suspect you could just change:
`console = {};`
to:
`console = (window.console = window.console || {});`

**Comment by LPology** [comment]
@thezoggy That won't work because there's a call to `console` on 2092 that comes first. When that gets executed it's throwing the error.

**Comment by Mottie** [comment]
Yeah, I just saw that in the Stackoverflow comments... IE needs `window.console` to not throw an error... sheez!

Ok, I'll have an update pushed to the master in a sec.

**Comment by thezoggy** [comment]
@LPology why i said that you could just drop that check and just use the line i noted first

**Comment by Mottie** [comment]
No, I need that check... it puts a different log system into place since there isn't a console...

`$.tablesorter.logs` will contain all logs instead of things being displayed in the console.
