### ISSUE TITLE
Search results return child rows that do not match search criteria

### ISSUE THREAD

**Issue by Bratzilla** [Mottie/tablesorter#1020]
Hello, and apologies in advance if this was already documented. I have spent days looking through the official and unofficial documentation but didn't see what I was looking for.

I have integrated Tablesorter into my Joomla app, and am using it for custom category management for that component. Everything has gone very smoothly. However, when testing the search, there is one maddening quirk. Basically, the results include the correct row AND all its sibling rows. **Ideally, a search will only return the row(s) that actually match the search criteria.** In the case of child rows however I could live with the parent also being listed if I must.

Here are the files I'm using in the order called (latest versions as a few days ago):
* tablesorter.min.js
* tablesorter.pager.min.js
* widget-uitheme.min.js
* widget-filter.min.js
* widget-grouping.min.js
* widget-storage.min.js

Below is the jQuery code I am using:

    var $caTable = $( "#categoryList" )
					.tablesorter({
						theme : "metro-dark",
						sortLocaleCompare: true, // needed for accented characters in the data
						cssChildRow : "tablesorter-childRow",
						widgets: ["group","filter"],
						 widgetOptions: {
							filter_cssFilter   	: "tablesorter-filter",
							filter_reset : ".reset",
							filter_external : ".search",
							filter_columnFilters: false,
							filter_ignoreCase  : true,
							filter_startsWith  : false,
							filter_liveSearch: false,
							group_collapsible : true,
							group_collapsed   : false,
							group_count       : false,
							filter_childRows  : true
						}

				}).tablesorterPager(pagerOptions);

And here is a screenshot that summarizes the situation (note: the only column being searched here is **Title** ):
![screenshot](https://cloud.githubusercontent.com/assets/2223465/10038167/0fe13e94-6176-11e5-8a10-fcd9fb453417.png)

Given this, how do I get Tablesorter to only return rows that match the search criteria when there are sibling rows involved? 

Thanks!

**Comment by Mottie** [comment]
Hi @Bratzilla!

I added a new option `filter_childWithSibs` option with a demo and everything... but I'm not quite done with all the documentation. I'll have it available in the master soon - I have to run right now :crying_cat_face:

**Comment by Mottie** [comment]
Ok, all done!

New version available & [here is a demo](http://mottie.github.io/tablesorter/docs/example-widget-filter-childrows.html) that lets you toggle the [`filter_childWithSibs` option](http://mottie.github.io/tablesorter/docs/index.html#widget-filter-child-with-sibs).

**Comment by Bratzilla** [comment]
Hey, thanks so much! I will test it this evening and report back.

**Comment by Bratzilla** [comment]
Hello again. I've just finished testing the revision. The good news is that the correct child rows now appear in searches. The problem now is that **parent** categories are completely excluded in search results.

If you test the demo page, and do a search for France or UK (both of which exist), you'll see that neither of these terms now appear if you search for them. For obvious reasons, because parent categories are still indeed categories (and you don't know what page a category will fall on), you'd want them to appear in a search. :)

**Comment by Mottie** [comment]
Hmm, ok try the update I am about to push to the master branch.

**Comment by Bratzilla** [comment]
Will do in just a bit... putting out a fire. :)

**Comment by Bratzilla** [comment]
I managed to squeeze in some basic testing. The code does seem to work, but documentation is really going to be critical to get this working right. Using the settings in the demo yields the right results, but care has to be taken when setting any of the "filterchild"-type settings. When I started playing with those, things got... interesting.

Of course, as you can tell by my data, this is just test samples. I will continue to monitor Tablesorter as the app gets more complex and let you know if I find anything else that's noteworthy. Thanks again for your help. :+1:

**Comment by Mottie** [comment]
Yeah, you need all three setting to make that demo work properly.

### `filter_childRows`
* `false` (default) - ignore all child row content
* `true` -  Appends all child row content to each column while searching

### `filter_childByColumn`
* `false` (default) - all child row content added to each column
* `true` - search child row content by column

### `filter_childWithSibs`
* `true` (default) - include all child rows with parent when one child, or parent matches the search criteria
* `false` - only show the matching parent, or child with parent that matches the search criteria.

If you set `filter_childRows` to `false` the other two options are ignored.

Hmm, if `filter_childByColumn` is `false` and `filter_childWithSibs` is `true` all child rows will be hidden... I think I'll have to fix that.

**Comment by Bratzilla** [comment]
Hello again. I haven't had a chance yet to pull your latest updates. I think I may have found another glitch but I'm not sure if it's related to this current  issue.

I am using the following code for the table and for the pagination toggle:

    var $caTable = $( "#categoryList" )
					.tablesorter({
						theme : "metro-dark",
						sortLocaleCompare: true, // needed for accented characters in the data
						cssChildRow : "tablesorter-childRow",
						widgets: ["group","filter"],
						 widgetOptions: {
							filter_cssFilter   	: "tablesorter-filter",
							filter_reset : ".reset",
							filter_external : ".search",
							filter_columnFilters: false,
							filter_ignoreCase  : true,
							filter_startsWith  : false,
							filter_liveSearch: false,
							filter_childRows     : true,
							filter_childByColumn : true,
							filter_childWithSibs : false,
							group_collapsible    : true,
							group_collapsed      : false,
							group_count          : false
						}

				}).tablesorterPager(pagerOptions);
				
    				// toggle pagination
				$(".cat_pager").click(function(){
					 var $this = $(this);
					$this.toggleClass("cat_pager");
					if($this.hasClass("cat_pager")){
						$this.html(\'<span class="icon-grid-2"></span>&nbsp;Show All\');
						$caTable.tablesorterPager(pagerOptions);
					} else {
						$this.html(\'<span class="icon-loop"></span>&nbsp;Reset\');
							$caTable.trigger("destroyPager");
					}
					return false;
				});      

It occurs when I use destroyPager when there is only one parent category and all other categories are its children. **When destroyPager is engaged, only the parent is shown. All of the children are hidden.

I've attached some screen shots to give you a visual.

![screenshot - one parent pager enabled](https://cloud.githubusercontent.com/assets/2223465/10093519/8165dc30-6308-11e5-85fb-4a610deaddc0.png)
*(table before pagination toggle)*

![screenshot - pagedestroy children hidden](https://cloud.githubusercontent.com/assets/2223465/10093523/963943f4-6308-11e5-8d9d-4ab166f7da2b.png)
*(table after pager destroy)*

However, when I restart the pager, everything goes back like it should (i.e., like in the first image).

Could this be related to the whole child rows issue?

**Comment by Mottie** [comment]
It works for me - ([demo](http://jsfiddle.net/Mottie/1a5yu8yq/78/))... anyway, I would recommend using the methods to enable & disable the pager.

**Comment by Bratzilla** [comment]
Good morning. I am downloading your latest files and about to retest. I checked the demo and have the same settings, so at this point I'm stymied. It's probably something really silly on my part. Anyway I'll report back soon.

**Comment by Bratzilla** [comment]
Actually, the problem DOES exist. Take a look now:

http://jsfiddle.net/1a5yu8yq/79/

I just updated your demo by removing all other parent/child groupings so that the table now looks in structure just like my own (that is, only one parent with children). As you can see, regardless of pager method, when you toggle, only the parent shows.

**Comment by Mottie** [comment]
Ok, try this latest update.

**Comment by Bratzilla** [comment]
Has it been updated in the demo?

**Comment by aayush26** [comment]
I small correction in your demo website.   
Link: [https://mottie.github.io/tablesorter/docs/example-widget-filter-childrows.html](https://mottie.github.io/tablesorter/docs/example-widget-filter-childrows.html)  
The line:
**Search the "Stock" ( 11% )**  
Shouldn't it be:
**Search the "Stock" ( >11% )**

**Comment by Mottie** [comment]
Hi @aayush26!

Actually no, the search for `11%` finds and shows the child row with it's parent, which is the cell that shows the values greater than 11%. If  you click the button to change the `filter_childWithSibs` to `true`, then you'll see all the other sibling rows appear.

There is currently a bug in the grouping widget - see #1325 - if you use the `widget-group.js` file in the master branch, it will work as expected.
