### ISSUE TITLE
Print Function - how to trigger?

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1022]
I have an existing tablesorter working great. I am trying to add the print function. I copied the widget options from the documentation as well as the div for the print button.

However I do not understand how the code from the documentation below triggers anything?
   << div class="print button">>Print<</div>>

I dont have a "print button" class and dont see that in the docs. I am guessing I needed to do something different to make a button to trigger the print function? How exactly do I do that?

**Comment by Mottie** [comment]
Hi @southmeadows!

If you look at the [print widget demo](http://mottie.github.io/tablesorter/docs/example-widget-print.html#method) under "method" you'll see this:

> To make the print widget work programmatically, trigger a "printTable" event.
```js
$('.print').click(function(){
  $('.tablesorter').trigger('printTable');
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
