### ISSUE TITLE
resizing doesnt work if table fills screen

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1023]
If I have too many columns such that horizontal scrolling is enabled in the browser then the column resizing doesnt work. If I change the table so it less columns then resizing seems to work ok.

**Comment by Mottie** [comment]
Hi @southmeadows!

If the table wrapper has a css `overflow` set to `auto` or `scroll`, then it should work. If your table doesn't have a wrapper, then you need to explicitly set the body to have an overflow ([demo](http://jsfiddle.net/Mottie/856bzzeL/654/)):

```css
body {
  overflow: scroll;
}
```

Script

```js
$(function () {
    $('table').tablesorter({
        theme: 'blue',
        widgets: ['resizable']
    });
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
