### ISSUE TITLE
Filter Storage does not work if using cookies and storing a '=' character

### ISSUE THREAD

**Issue by toesus** [Mottie/tablesorter#1026]
I am using IE9 with a local file. The storage defaults to cookies. If i use a '=' in the filter widget, I get the error message "SCRIPT1015: Unterminated string constant".

I suppose this is due to the way the cookie data is loaded:
```javascript
cookies = document.cookie.split(/[;\s|=]/); 
``` 
The cookie is split at '=' characters, and thereby breaks the json-data.

Most other examples of cookie-loading seem to split the data only on ';' and then look for the string  'key=' to find the beginning of the data.

**Comment by Mottie** [comment]
Hi @toesus!

Thanks for reporting this problem. I'll try to look at fixing this later tonight.

**Comment by Mottie** [comment]
Sorry for taking so long... please try the updated filter widget in the master branch (not yet released). Instead of looking for a "key=" string, I opted to use `encodeURIComponent` on the filters. Please tell me if you run into any issues with this method.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
