### ISSUE TITLE
Problem using applyWidgets to apply grouping

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1030]
Hello, 

i am struggling with appluWidgets, i am trying to add the group widget when the page loads (because i want to have the group applyied to only some tablesorters)

here is the code i am using,

```js
$('.tablesorter1').tablesorter(); 
                  
  $('.tablesorter1').trigger('applyWidgets', true);
  $('.tablesorter1')[0].config.widgets = ['group'];

});   
```

and here is the error i am having,

wo.group_forceColumn is undefined

```js
 column = typeof wo.group_forceColumn[0] !== 'undefined' ?
					( wo.group_enforceSort && !hasSort ? -1 : wo.group_forceColumn[0] ) :
					( hasSort ? c.sortList[0][0] : -1 );
```
widget-grouping.js

i havent touched the widget so the line of the error is 63

Thanks,

Fábio Ferreira

**Comment by Mottie** [comment]
Hi @fcferreira29!

Instead, add a `widget-group` class name only to the tables where you want the group widget added. See the docs for the [`widgetClass` option](http://mottie.github.io/tablesorter/docs/#widgetclass) which would allow you to change the class name in case there are conflicts.

**Comment by fcferreira29** [comment]
i did what you told me and added the "widget-group" to the table,

but the error is the same:

wo.group_forceColumn is undefined

column = typeof wo.group_forceColumn[0] !== 'undefined' ?
 ( wo.group_enforceSort && !hasSort ? -1 : wo.group_forceColumn[0] ) :
 ( hasSort ? c.sortList[0][0] : -1 );

widget-grouping.js

i havent touched the widget so the line of the error is 63

**Comment by Mottie** [comment]
Please make sure that the most recent version of the tablesorter core & group widget are being used.

If it is still broken, please try adding a `group_forceColumn: []` to the widget options (empty array). Either way, I'll make some changes in the code to prevent that error.

**Comment by Mottie** [comment]
Actually, try the group widget update in the master branch and see if that prevents the error. If the error is still there, please share the tablesorter initialization code you are using.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
