### ISSUE TITLE
How to used the header from AJAX with json format

### ISSUE THREAD

**Issue by don750421** [Mottie/tablesorter#1031]
Sorry,I am pending some test since Aug.
I have a question in https://github.com/Mottie/tablesorter/issues/985
and I want to fix my code with your update version now.
but I don't know how to dynamic used the header from AJAX

Because I want to used a page let user key in the SQL Command.and the tablesorter will show query result.but user SQL command and query column is non-fixed.
so I has not fix theader name.

My HTML is 
````
<div style="overflow: auto; height: 150px;">
       <table id="QueryDBTable" style="float: left; padding-top: 10px" class="tablesorter">
             <thead>
                 <tr>
                 </tr>
             </thead>
             <tbody>
             </tbody>
         </table>
</div>
````
and my JS
````
var gv_QueryDBTable ;
gv_QueryDBTable = $("#QueryDBTable").tablesorter({
                    theme: 'blue',
                    sortList: [[0, 0]],
                    widthFixed: true,
                    widgets: ['zebra', 'columnSelector', 'stickyHeaders'],
                    widgetOptions: {
                        columnSelector_container: '#QueryDBColSel',
                        columnSelector_columns: {
                        },
                        columnSelector_mediaquery: true,
                        columnSelector_mediaqueryState: false
                    }
                })
                .tablesorterPager({
                    // target the pager markup - see the HTML block below
                    container: $("#QueryDBpager"),
                    ajaxUrl: "/Handler/SrcHandler.ashx?TableName=QueryDBTable",
                    size: 9999,
                    savePages: false,
                    customAjaxUrl: function (table, url) {
                        // need to dynamically update page size
                        // since adding 'rows : size' in ajaxObject.data doesn't
                        // dynamically update the size
                        table.config.pager.ajaxObject.data.rows = table.config.pager.size;
                        return url;
                    },
                    ajaxObject: {
                        dataType: 'json',
                        type: 'POST',
                        data: {
                            SevName: $("#QueryName").val().trim(),
                            SQLComm: $("#QuerySQLComm").val().trim()
                        },
                    },
                    ajaxProcessing: function (data) {
                        if (data) {
                            if (data && data.hasOwnProperty('rows')) {

                                var indx, r, row, c, d = data.rows,
                                // total number of rows (required)
                                total = data.total_rows,
                                // array of header names (optional)
                                headers = data.headers,
                                // cross-reference to match JSON key within data (no spaces)
                                headerXref = headers.join(',').replace(/\s+/g, '').split(','),
                                // all rows: array of arrays; each internal array has the table cell data for that row
                                rows = [],
                                // len should match pager set size (c.size)
                                len = d.length;
                                // this will depend on how the json is set up - see City0.json
                                // rows
                                for (r = 0; r < len; r++) {
                                    row = []; // new row array
                                    // cells
                                    for (c in d[r]) {
                                        if (typeof (c) === "string") {
                                            // match the key with the header to get the proper column index
                                            indx = $.inArray(c, headerXref);
                                            // add each table cell data to row array
                                            if (indx >= 0) {
                                                row[indx] = d[r][c];
                                            }
                                        }
                                    }
                                    rows.push(row); // add new row array to rows array
                                }
                                // in version 2.10, you can optionally return $(rows) a set of table rows within a jQuery object
                                return [total, rows, headers];
                                //return [data.total_rows, $(data.rows), data.headers];
                            }
                        }
                    },
                    output: 'Showing: {startRow} to {endRow} (Total:{total})'
                });

                gv_QueryDBTable.on('pagerComplete', function () {
                      $(this).trigger('refreshColumnSelector', 'selectors');
                });
````
and my AJAX return is 
````
{"total_rows":1,"headers":["PACKAGE_ID","ID_NUMBER","PACKAGE_TYPE","CREATION_DATE","LAST_UPDATE_DATE","TEST_PACKAGE","STATUS"],"rows":[{"PACKAGE_ID":5193200.0,"ID_NUMBER":2456919.0,"PACKAGE_TYPE":"S","CREATION_DATE":"2015-06-16T13:41:51","LAST_UPDATE_DATE":"2015-06-16T13:41:51","MES_TICKET":"998D510DD","STATUS":"CRT"}]}
````

**Comment by Mottie** [comment]
Hi @don750421!

The code looks very similar to the code in [this demo](http://mottie.github.io/tablesorter/docs/example-pager-ajax.html#javascript), and if you look at the HTML, you'll see that the header text get replaced. So I know it works.

It still looks like the code within the `ajaxProcessing` function will replace the header text. I'm not sure why it wouldn't be working for you.

Are you seeing any errors in the console (press F10 in the browser, then go to "Console")?

Maybe you could add a log in your code to verify the data is all there:

```js
console.log( headers );
return [total, rows, headers];
```

Other than that, I guess I'd need to see the page where the code isn't working to provide better help.

**Comment by don750421** [comment]
Sorry,I forget post my screenshot.
![image](https://cloud.githubusercontent.com/assets/13444821/10296817/f7333d6e-6bfe-11e5-859a-f4569a1975b4.png)

and I has no error in the console.and the header is correct.(I use the chrome to debug)
![image](https://cloud.githubusercontent.com/assets/13444821/10296876/85fcb2d2-6bff-11e5-88b7-1716e3e593e5.png)

**Comment by Mottie** [comment]
Hmm, ok is there a hidden column? The `headers` variable is ignored if the length of the array returned from `ajaxProcessing` isn't the same as the number of headers in the table. Also, it will only apply to `th` cells (not `td` cells) in the `thead`, because there are cases where the pager controls are added to the `thead` within a `td`.

**Comment by don750421** [comment]
Hi @Mottie 
There is no hidden column.
The length of the array is 7..
![image](https://cloud.githubusercontent.com/assets/13444821/10298253/73aa4008-6c0f-11e5-8ba5-d6524c485ac0.png)

**Comment by Mottie** [comment]
And no `td`s? Can you share the HTML?

**Comment by don750421** [comment]
Sorry ! My HTML is...
![image](https://cloud.githubusercontent.com/assets/13444821/10326970/65f00c5c-6cd4-11e5-8e54-dbe1084020f2.png)

Thank you.

**Comment by Mottie** [comment]
So there are no `<th>`'s in the `<thead>`? Please add some. The pager is set up to update the `<th>` cell content, not add news one.

**Comment by don750421** [comment]
Yes.but i test two situation.
case 1: the DB column count meets the HTML Table th
It's work for me.
![image](https://cloud.githubusercontent.com/assets/13444821/10328550/aafcbc8c-6ce8-11e5-843f-7ca359cbb308.png)

case 2: the DB column count NOT meets the HTML Table th
![image](https://cloud.githubusercontent.com/assets/13444821/10328560/c86c7f1e-6ce8-11e5-853a-c62c8af74a99.png)

And I need non-fixed column count. non-fixed. https://github.com/Mottie/tablesorter/issues/985
because 
I want to used a page let user key in the SQL Command.and the tablesorter will show query result.
but user SQL command and query column is non-fixed.
so... I want to set the tablesorter column by query result header.
![image](https://cloud.githubusercontent.com/assets/13444821/10296817/f7333d6e-6bfe-11e5-859a-f4569a1975b4.png)

**Comment by thezoggy** [comment]
so looks like you return different amount of columns? just analyze your return data and re-setup the proper header with it? or you just have malformed html.

**Comment by don750421** [comment]
Thanks @thezoggy 
The return column always is 7.
if I setup thead th "before" AJAX Query,it is work for me.

But I need design a page let user key in the SQL Command.and show the query result with tablesorter.
then user SQL command and query column is non-fixed.(EX.Select * from xxxxxx)
so...How to re-setup the tablesorter column count (thead th) after query.

**Comment by thezoggy** [comment]
accepting user input blindly to pass to sql command is just setting yourself up for failure (xss/hacks). you shouldnt have to re-setup the column count if the count is the same, your data is what changes.. not the headers. if you did.. you'd lose the sorting info applied to said headers.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
