### ISSUE TITLE
Filter issue (maybe only with ajax)

### ISSUE THREAD

**Issue by DaveGahan** [Mottie/tablesorter#1032]
Hi Mottie, by using ajax server side tablesorter v2.22.1 I've got this (correct) behaviour when using filters (empty result, no date contains "99" value) : 

![0](https://cloud.githubusercontent.com/assets/12768499/10280344/ce1992e4-6b6c-11e5-8333-272f5bc6266b.jpg)

Upgrading to v2.23.5 I get that (wrong) behaviour (seems like there is no update when request returns nothing) : 

![1](https://cloud.githubusercontent.com/assets/12768499/10280404/442af1f8-6b6d-11e5-846c-a28df47161f2.jpg)

As you can see pager's counter works well but tablesorter should be empty as it is on the first screen (same code, same datas).

Have you any idea to solve this please ?

PS: I use "dist" folder.

**Comment by Mottie** [comment]
I wonder if it might be related to [this change](https://github.com/Mottie/tablesorter/commit/d36184a1d432087c4f5ba24a31e81d4a98645421). Can you test to see if this problem occurs in v2.22.2?

Thanks!

**Comment by DaveGahan** [comment]
It does not occurs using v2.22.2.

Thanks.

**Comment by Mottie** [comment]
Ok, I'll see what I can do to fix it.

**Comment by Mottie** [comment]
Please try out the pager code in the master branch and see if it fixes the problem. Thanks!

**Comment by DaveGahan** [comment]
It's ok now, thank you again !
