### ISSUE TITLE
Problem using group_months

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1036]
i am having a problem using the "group_months" array, 

since you are using the array as 0 => Jan, 1 => Feb.....

our dates are not in sync because we want october that is the month 10 and we get November instead, 

the months go from 1 - 12 why is this array from 0 - 11?

is there a specific reason for this?

**Comment by Mottie** [comment]
Hi @fcferreira29!

I provided an explanation and even some code on how to get around this issue to you [previously](https://github.com/Mottie/tablesorter/issues/1016#issuecomment-142923426).

Again, if you shared the code on how the array is being used, I could help.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
