### ISSUE TITLE
Sorting problems with latin characters, like "á" or "ã"

### ISSUE THREAD

**Issue by feperrella** [Mottie/tablesorter#1039]
First, thanks for the incredible plugin!

Could you fix this issue, any latin character with some sort of accentuation doesn't work, they all goes to bottom of the list.

Thanks in advance.

**Comment by thezoggy** [comment]
works fine..
http://mottie.github.io/tablesorter/docs/example-locale-sort.html

**Comment by feperrella** [comment]
Thanks, haven't found that before, now it works, thanks.
