### ISSUE TITLE
Style the table before it renders?

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1042]
I have a problem in that the default styling of the table appears on the screen, before .tablesorter is applied. So, there is a delay and then the table is styled and takes on the formatting and functionality after a second or two. How can I keep the table from loading until tablesorter has done its magic?

**Comment by Mottie** [comment]
Hi @aetna-wsa!

If you are using one of the included themes, add "tablesorter-" plus the name of that theme. For example, if using the blue theme, add this class to the table:

```html
<table class="tablesorter-blue">
...
</table>
```

This is essentially the same as adding a `theme` option. The sort arrows won't be applied, and will show up only after tablesorter has finished initializing.

If you aren't using an included theme, then make sure the css that styles the table is loaded in the `<head>` of the document.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
