### ISSUE TITLE
static-row widget fails

### ISSUE THREAD

**Issue by ysarkain** [Mottie/tablesorter#1044]
I have a table which uses the static-row widget to keep a "group header" in place, but if I click a column  to sort twice, it sends the static row to the bottom of the table.

**Comment by Mottie** [comment]
Hi @ysarkain!

Are you using the grouping widget in conjunction with the static row widget? The grouping widget is not meant to have its group headers made static.

If you don't mean the grouping widget, then please modify [this demo](http://jsfiddle.net/Mottie/3s60epzt/) to help me troubleshoot the problem.

**Comment by ysarkain** [comment]
Thanks for the reply

I put the code I am using for the javascript, css, and the source html, and it works fine in the demo page.

but on my actual page it doesn't keep the static row at the top under the header row.

**Comment by Mottie** [comment]
Are you loading the `widget-staticRow.js` file?

**Comment by ysarkain** [comment]
ok, I thought it was part of jquery.tablesorter.widgets.js

I added widget-staticRow.js and now it works great!

Thanks!
