### ISSUE TITLE
ServerSide- update ajaxUrl for external filter values

### ISSUE THREAD

**Issue by AlexDag** [Mottie/tablesorter#1045]
Using tablesorter I have server side filter by ajaxUrl. All work well, now I need do add some external filter by columns that does not present on tablesorter. So, I need to update formal filter on ajaxUrl, extending/adding by some additional parameters. This additional parameters are the input values of other html component. Are there some appropriate solutions for this case? As I understand I need to fire ajaxUrl event and update filters parameters. Thanks on advance.

**Comment by Mottie** [comment]
Hi @AlexDag!

Are you not using the `{filter:fcol}` placeholder in the [`ajaxUrl` option](http://mottie.github.io/tablesorter/docs/#pager-ajaxurl)? It should automatically update when the user enters a new query. It should also work if you have the filter set up with [external inputs](http://mottie.github.io/tablesorter/docs/#widget-filter-external).

I might be able to better help if you provide some code and more details.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
