### ISSUE TITLE
Error in widget.js file

### ISSUE THREAD

**Issue by BitStinker** [Mottie/tablesorter#1050]
jquery.tablesorter.widgets.js - v2.23.5
LINE 2340:

ts.filter.hideFilters($stickyTable, c);

SHOULD BE

ts.filter.hideFilters(c);

REF (LINE 1208):

hideFilters: function( c ) {...

Something went awry in the dynamic generation. It obviously caries over to the widget.min.js file.

**Comment by Mottie** [comment]
Hi @BitStinker!

Thanks for reporting this issue, I'll have it fixed here shortly.
