### ISSUE TITLE
setFilter for range

### ISSUE THREAD

**Issue by BitStinker** [Mottie/tablesorter#1051]
I have a column (first column) using filter-formatter with a date range (from, to) and two other filter-select columns. I tried this:

$.tablesorter.setFilters( tbicnc.table, [ '', '{no one}', '{nothing}' ], true );

but it failed to set the proper filters. If I disable filtering on the first column it works as expected.

Perhaps there is a special way to specify the date range in setFilter?

Thx

**Comment by Mottie** [comment]
Hi @BitStinker!

Have you tried using the [`filterReset` method](http://mottie.github.io/tablesorter/docs/#filterreset)?

```js
$('table').trigger('filterReset');
```

I'm not sure why the `setFilters` doesn't work as expected. Are the `'{no one}` and `{nothing}` actual options values in the select? What exactly is happening with the date filters.. like is it only clearing the first one? Would you please share the tablesorter initialization code being used?

**Comment by BitStinker** [comment]
As I said, without the date range, the '{no one]' and '{nothing}' options all work as designed. So those objects are not in question...I hope. :) It's just the date range that is causing the setFilter function to fail.

Here are the relevant details:

1. I wanted to have the default state of the table to have no rows shown
2. I used filter_selectSource to add an '{all}' selection.
3. I added filter_functions to handle '{no one}', '{nothing}', and '{all}'.
4. I set the first option values in the filter select boxes to '{no one}' and '{nothing}', respectively in the filterInit event.
5. At the end of the filterInit handler I call setFilter to refresh the table filters.

Here is the relevant code:

so.widgetOptions.filter_selectSource = {
	".cnc-who" 		: 	function (table, column, onlyAvail) {
							var array = $.tablesorter.filter.getOptions(table, column, onlyAvail);
							array.splice( 1, 0, "{all}" );
							return array;
						},
	".cnc-class" 	: 	function (table, column, onlyAvail) {
							var array = $.tablesorter.filter.getOptions(table, column, onlyAvail);
							array.splice( 1, 0, "{all}" );
							return array;
						}
};
so.widgetOptions.filter_functions = {
	".cnc-who"		: 	{
							"{no one}" :	function (e, n, f, i, $r, c) {
												return false;
											},
							"{all}"		:	function (e, n, f, i, $r, c) {
												return true;
											}
						},
	".cnc-class"	: 	{
							"{nothing}"	:	function (e, n, f, i, $r, c) {
												return false;
											},
							"{all}"		:	function (e, n, f, i, $r, c) {
												return true;
											}
						}
};

**Comment by BitStinker** [comment]
One other piece of info:

When the date range filter is in place, the setFilter method does not set the '.cnc-who' or '.cnc-class' filters to the values requested. When the date range filters are not in place, those values are set properly.

**Comment by BitStinker** [comment]
Here is the initFilter event handler:

								var op = tbicnc.table.find( 'select.tablesorter-filter[data-column="1"] option:first-of-type' );
								op.attr( 'value', '{no one}' );
								var op = tbicnc.table.find( 'select.tablesorter-filter[data-column="2"] option:first-of-type' );
								op.attr( 'value', '{nothing}' );
								//tbicnc.table.trigger( 'filterFomatterUpdate' );
								$.tablesorter.setFilters( tbicnc.table, [ '', '{no one}', '{nothing}' ], true );

**Comment by Mottie** [comment]
Hmm, I wonder if it's because there are issues with using the setFilter function in the immediately after the filterInit event.

Either wrap the above code in a `setTimeout` function or use the default filters setting ([`data-value` attribute](http://mottie.github.io/tablesorter/docs/example-widget-filter.html#methods)):

```html
<th class="cnc-date" data-value="1/1/2015 - 12/31/2015">Date</th>
<th class="cnc-who" data-value="{no one}">Who</th>
<th class="cnc-class" data-value="{nothing}">Class</th>
```

**Comment by Mottie** [comment]
If none of that works, please modify [this demo](http://jsfiddle.net/Mottie/abkNM/7107/) to show the issue to make it easier for me to troubleshoot.

**Comment by BitStinker** [comment]
If that were true, then it wouldn't work without the date range filter either...would it?

**Comment by Mottie** [comment]
I'm still not sure exactly what is happening or not happening. Is nothing happening when the datepicker is included with the setFilters function?

The filter formatter needs a little extra time to initialize since it is also applying jQuery date picker to two inputs. The `filterInit` event fires after it has set up everthing, but it is doing it asynchronously from jQuery UI.

**Comment by BitStinker** [comment]
I modified the demo. The test is outlined in the comments. That should make it clearer than anything I could type here. :)

**Comment by Mottie** [comment]
A link would help :wink:

**Comment by BitStinker** [comment]
Oops...I thought that editing the code would do it. Never used JSFIddle. What is the link?

**Comment by BitStinker** [comment]
Is this the link: https://jsfiddle.net/abkNM/7121/

**Comment by Mottie** [comment]
click on the "Update" button then copy the new URL.

**Comment by BitStinker** [comment]
OK. That appears to be the link. Sorry. Don't ya hate nubes? :)

**Comment by Mottie** [comment]
I love nubes... gotta have someone to pick on ;)

**Comment by BitStinker** [comment]
I'm your huckleberry...

**Comment by Mottie** [comment]
Ok, I can only assume that [this demo](http://jsfiddle.net/Mottie/abkNM/7122/) is the goal you had in mind.

Instead of adding an `{all}` option, I just used `data-placeholder="{all}"` to add the option to the top of the select list.

```html
<th data-placeholder="{all}" class="filter-select filter-select-nosort cnc-who">First Name</th>
<th data-placeholder="{all}" class="filter-select filter-select-nosort cnc-class">Last Name</th>
```

Then I added the `filter_selectSource` and `filter_functions` settings from above.

**Comment by BitStinker** [comment]
It appears to be close. I'll play with it and see if I can bend it to my needs.

Thanks!
