### ISSUE TITLE
specific text in the group_dateString

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1052]
Hello again,

i am using the group-date and i used the group_dateString to change the order of the elements of the group

to have something like this:

19 Out (10)

i am using this in two diferent tables,

my question is:

is there a way to insert specific text in the group?

to have something like

"Departures in 19 Out (10)" and "Arrivals in 19 Out (10) ",

because when the users look to the table they dont quite understand what the group refers to,

thanks,

Fabio Ferreira

**Comment by Mottie** [comment]
Hi @fcferreira29!

Did you use the [`group_formatter` callback function](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html#group_formatter)?

Using it allows completely changing the group header text:

```js
group_formatter : function(txt, col, table, c, wo) {
  // If there are empty cells, name the group "Empty"
  return txt === "" ? "Empty" : txt;
}
```

**Comment by fcferreira29** [comment]
Hello,

i just created a workaround to the problem of having diffetent texts to the grouping dates,

i am doing this:

$('.tablesorter2 .group-name').each(function() {

                        var str = $(this).html();

                        str = str.replace('Departures from ', '');

                        $(this).html(str);
                    });

                    $('.tablesorter2 .group-name').each(function() {
                        txt = $(this).html();

                        $(this).html( 'Departures from '+ txt );

                    });

its not the best way but it works,

do you have a better way to do it?

the problem of having two tablesorters on the same page continues,

because one of them is hidden the grouping doen't take effect on the tablesorter and i have to do

initTableSorter(2); (with this the problem is solved)

Thanks

**Comment by Mottie** [comment]
I had to look back at the issues you opened because I don't recall the code used in `initTableSorter(2)`... how does it fix your problem?

Did you try using the `group_formatter` function? If not, try this code:

```js
group_formatter : function(txt, col, table, c, wo) {
  return 'Departures from ' + txt;
}
```

Is this the same project that has a table in different tabs? If so, you'll still need to trigger an "applyWidgets" on the table when the tab becomes visible.

**Comment by fcferreira29** [comment]
this is what i did to make it work

group_dateString  : function(date) {
                  
                  
                var  date_local = date.toLocaleString();
                //return date.toLocaleDateString();
                
                var tmp_date = date_local.split("/");
                //var  time_local = date.toLocaleTimeString();
                //var tmp_time = time_local.split(":");
                
                var date_treated = tmp_date[0]+" "+getMonthNameFromMonthNumber(tmp_date[1]);
                
               text = $('.tablesorter'+id+' .group-date').first().text();
                
                return text.trim()+' in '+date_treated;
              }

this does the trick for both the tablesorters,

the fix you tell me will give both tablesorters the same text before the date.......the tablesorter config is common for both the tables......

**Comment by Mottie** [comment]
Oh, they are different in both tables? In that case you can check the table id or class name in the formatter:

```js
group_formatter : function(txt, col, table, c, wo) {
  return table.id === 'table1' ? 'Departures from ' + txt : txt;
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
