### ISSUE TITLE
How to store the old filter ajax

### ISSUE THREAD

**Issue by likedo** [Mottie/tablesorter#1053]
Hello , thanks for the support.
How do I save the old ajax-filtering?

This is my code:
<pre><code>
tablesorterPager({
	ajaxUrl : 'index.php?rt=search/pagination&className='+className+'&classNameTarget='+classNameTarget+'&pk='+pk+'&page={page}&{filterList:filter}&{sortList:column}',
	// modify the url after all processing has been applied
	customAjaxUrl: function(table, url) {                  
		$(table).trigger('changingUrl', url);        				
		return url;			
	}
	...
	...
	...
});	
</code></pre>

I would like to concatenate the old filter to build a query 
"AND aaa=1 AND bbb=2 AND CCC=3 etc.."

Thank you!

**Comment by TheSin-** [comment]
in the ajax file you need to process the _GET var.  specifically col and fcol so that you can set the ORDER BY and WHERE clauses.  This is very dependant on your setup and have nothing to do with TS directly so it's something we can not really answer for you.  We can't see your data nor do we know the language you are using server side.  I also like to add page and size to my url so server side I can use START and LIMIT to speed things up.

**Comment by Mottie** [comment]
Hi @likedo!

The `{filterList:filter}` placeholder will get replaces with all currently applied filters, so I'm not completely sure what you mean by saving the old ajax-filtering to concatenate it on the query.

If you want to manipulate the ajax url, you can use the [`customAjaxUrl` callback function](http://mottie.github.io/tablesorter/docs/#pager-customajaxurl) to make changes.

**Comment by likedo** [comment]
Hi, thanks for your reply . I explain the problem better .
I noticed that if I use select to filter , the URL is not returned to date with all values ​​of select used but only with the last . As if using the filters textual URL is properly updated .
I would always have the url updated with the list of applied filtering , input select and text input

Here is the code:

<code>
<pre>
//
// filter[8]=1 -> filter select (ok)
// missing the column filter [ 2 ] = 5 -> filter select (missing)
//
index.php?rt=search/pagination&className=dipendenti&classNameTarget=undefined&pk=undefined&page=0&column&filter[8]=1

//
// filter[8]=1 -> filter select (ok)
// filter[3]=test -> filter input text (ok)
// filter[4]=test2 -> filter input text (ok)
//
index.php?rt=search/pagination&className=dipendenti&classNameTarget=undefined&pk=undefined&page=0&column&filter[3]=test&filter[4]=test2&filter[8]=1




$("table").tablesorter({
  			
		theme: "blue",
		widthFixed: false,		
		widgets: ['zebra', 'columns', 'filter', 'pager'],
		widgetOptions : {
			
			filter_external: true,	

			filter_selectSource : function(table, column, onlyAvail){
       			
				if (table.hasInitialized) {
            			
    				var fkName = $("[data-column='"+column+"']").attr("data-fkname");										
        			$.getJSON("../admin/callbacks/getSelectFilterSearch.php?fkname="+fkName, function(data){
            			var result = data.hasOwnProperty('options') ? data.options : false;                			            			
            			$.tablesorter.filter.buildSelect( table, column, result, true );            			
        			});
				}
				return false;	
      		},
      		filter_selectSourceSeparator : '|'					
    	}	
		
  	}).tablesorterPager({

		container: $(".pager"),
		
		ajaxUrl : 'index.php?rt=search/pagination&className='+className+'&classNameTarget='+classNameTarget+'&pk='+pk+'&page={page}&{sortList:column}&{filterList:filter}',
      	
      	customAjaxUrl: function(table, url) {                  
			      		
			$(table).trigger('changingUrl', url);        
						
			return url;						
      	
      	},
      	
      	ajaxObject: {
      		dataType: 'json'			
      	},
		
		
		ajaxProcessing: function(data){
									        					
			if (data && data.hasOwnProperty('rows')) 
			{							
				var r, row, c, d = data.rows,
				// total number of rows (required)
				total = data.total_rows,												
				// array of header names (optional)
				headers = data.headers,
				// all rows: array of arrays; each internal array has the table cell data for that row
				rows = [],
				// len should match pager set size (c.size)
				len = d.length;
												
				// this will depend on how the json is set up - see City0.json
				// rows
				for ( r=0; r < len; r++ ) 
				{				
					row = []; // new row array
					// cells
					for ( c in d[r] ) 
					{
						if (typeof(c) === "string") 
						{
							row.push(d[r][c]); // add each table cell data to row array
						}
					}
																			
					rows.push(row); // add new row array to rows array
				}
												
				// in version 2.10, you can optionally return $(rows) a set of table rows within a jQuery object
				return [ total, rows, headers ];
			}
		},
						
		output: '{startRow} to {endRow} ({totalRows})',
		
		updateArrows: true,
		
		page: 0,
		
		size: 10, //25
		
		fixedHeight: false,
		
		removeRows: true,
		
		cssNext        : '.next',  // next page arrow
		cssPrev        : '.prev',  // previous page arrow
		cssFirst       : '.first', // go to first page arrow
		cssLast        : '.last',  // go to last page arrow
		cssPageDisplay : '.pagedisplay', // location of where the "output" is displayed
		cssPageSize    : '.pagesize', // page size selector - select dropdown that sets the "size" option
		cssErrorRow    : 'tablesorter-errorRow', // error information row
		
		// class added to arrows when at the extremes (i.e. prev/first arrows are "disabled" when on the first page)
		cssDisabled    : 'disabled' // Note there is no period "." in front of this class name
				    	
    });
</pre>
</code>

Thanks.

**Comment by Mottie** [comment]
Sorry, is this still an issue? It would be very helpful if you could provide a demo. You can modify [this one](http://jsfiddle.net/Mottie/uwZc2/), even though it doesn't actually provide sorting or filtering.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
