### ISSUE TITLE
destroyPager really doesn't

### ISSUE THREAD

**Issue by Bratzilla** [Mottie/tablesorter#1055]
Per the current documentation, "Calling this method **will reveal the entire table**, remove the pager functionality, and hide the actual pager", Currently, destroyPager doesn't do that. It seems to simply remove the pager apparatus and show the current page (i.e., the page you are on when destroyPager is called). Revealing the entire table means just that - the whole table is revealed as if there was never any pagination.

Is there a way to fully remove the paging so that the entire table shows on one page? I need this functionality to wrap up my current project piece. Thanks!

**Comment by Bratzilla** [comment]
I have just discovered a workaround based on features already in Tablesorter. It uses the pageSize trigger and setting it on event fire to a very large, unrealistic number. This effectively forces all objects onto the same page and gives me the functionality I need to push through my project. Not idea, but simple and gets the job done for now.

For the long term, though, it wold be nice to have:
- "Select All" option baked into Tablesorter
- A true method to destroy the pager so that the entire table shows

If any of these already exist, please feel free to point me to the documentation. Even if it's experimental, I'll give it a try.

Thanks again!

**Comment by Mottie** [comment]
Hi @Bratzilla!

That does look like an issue. I'm not sure when it was introduced, but I'll try to get it fixed ASAP.

I'll add an "all" setting to the `setPageSize` function to show all rows as well.

**Comment by Bratzilla** [comment]
Great! In the meantime, I've tweaked my workaround even more and developed a much better sever-side method for getting around this issue that works well with current Tablesorter options. I will test the revised pager when it's available. Thanks again!

**Comment by Mottie** [comment]
Hmm, ok very odd... this is definitely related to issue #1020, where a `showAll` setting was added in https://github.com/Mottie/tablesorter/commit/285cef1e70c74367b0e7f308b7c89f87d5ecda26; specifically the `p.showAll = true` on [line 665 ](https://github.com/Mottie/tablesorter/blob/master/addons/pager/jquery.tablesorter.pager.js#L665).

Please comment out that line and test to see if the last problem from #1020 returns... I commented out that line, then destroyed the pager and I still see the child rows... it's been a month so I might be missing some details.

**Comment by Bratzilla** [comment]
I've only had a brief time to test this evening. Show All appears to be functioning properly. I also tested to see if there were any search issues. Thus far, searching seems to work correctly. I will test again when I have some more time and report back if I find any issues.

**Comment by Mottie** [comment]
Any update on this? I'd like to get a new release out soon.

**Comment by Bratzilla** [comment]
Sorry for the delay. Busy morning.

I didn't see any further issues at this time. "Show All" seems to work just fine. 

I'm still working on my project, so if I do come across any further issues I will let you know. Thanks again!

**Comment by Mottie** [comment]
Umm, you mean removing `showAll` works fine or....?

**Comment by Bratzilla** [comment]
Sorry. That's what I get for rushing. :-\

I need to wrap up what I'm working on now so I can get back to my test server. I can give you an update within the next hour or so. Would that work? Sorry for the confusion. Today has been NUTS!

**Comment by Mottie** [comment]
LOL, yeah I don't think I'll push a new release today... I'm aiming for Friday, so no worries.

**Comment by Bratzilla** [comment]
Okay, I've had a little time to work on this again. Here are my current notes. If there is anything that is unclear, please let me know. I tried to get this pushed through before getting sucked into something else. :)

**Test 1 - p.showAll commented out**
- Set the page size option to "all" 
- Triggered select all in the actual table
- Performed search on both Title and Description columns
- Result: Searches returned correctly.

![1 showall_commented_out-select-all-active](https://cloud.githubusercontent.com/assets/2223465/10773136/f04b95be-7cb6-11e5-93c9-ad98c653b8a3.png)

**Test 1 - p.showAll active**
- Repeated same test as outlined above.
- Result: Searches again correctly returned.

![2 showall_enabled-select-all-active](https://cloud.githubusercontent.com/assets/2223465/10773169/1f7e3e04-7cb7-11e5-8f70-4a0da2267ed0.png)


**Interesting glitch** - Regardless of p.showAll, in cases where all items fall on only one (1) page, the page size selector would not select. I've captured a screen so you can see it.
![3 items_per_page_not_setting](https://cloud.githubusercontent.com/assets/2223465/10773256/93d43d62-7cb7-11e5-8d7a-dcf7a0532398.png)

Note that this does not happen if the items have to be split between pages (i.e., # of pages >= 2). Also, the page otherwise behaves properly with respect to filtering, etc. I had initially thought this could be browser-specific (you know, Chrome being Chrome) but the behavior seems pretty consistent across browsers. Of course more thorough testing is needed but I thought I'd report this just in case.

**Comment by Mottie** [comment]
Thanks for the update!

If you are using the most up-to-date version of the pager from the master branch, then when all items are shown, it tries to set the page size to "all"... so if the "all" value isn't one of your options, it will just show an empty select box. Please check to see if this is the problem.

If not, try entering the following into the console and see what value is returned:

```js
$('select:last').val()
```

**Comment by Bratzilla** [comment]
That's right -  page size "all" applies to page and not items per page... do'oh! (－‸ლ)

For "items per page", is it normal behavior for nothing to be selected if "all" is in effect?

I want to fix my screw-ups to get more accurate testing results.

**Comment by Mottie** [comment]
What is "items per page"? The page size should be "all", pager number is "1" and if there was an "items per page" it should either be "all" or the same number as total rows.
