### ISSUE TITLE
formatterUpdated bug

### ISSUE THREAD

**Issue by BitStinker** [Mottie/tablesorter#1056]
formatterUpdated() is called as a result of a call to updateAll(). 

In the process the $cell variable for a tr.tablesorter-filter-row td is sent to formatterUpdated(). 

This $cell's tr has been removed from the table so $cell.closest( 'table' ) returns undefined. 

Finally, $cell.closest( 'table' )[0].config throws an exception (cannot read property 'config' of undefined).

**Comment by Mottie** [comment]
Hi @BitStinker!

Would you please share the code being used? Which filter formatter is being used and how is `updateAll()` being used?

An demo showing this issue would be awesome.

**Comment by BitStinker** [comment]
This is the code we were working on before with the date-range selector filter formatter (yeah, you have nothing better to do than keep track of my posts :) ). Here is the relevant code:

so.widgetOptions.filter_formatter = {
 '.cnc-date' : function($cell, indx) {
  return $.tablesorter.filterFormatter.uiDatepicker( $cell, indx, {
	// from : '08/01/2013', // default from date
	// to   : '1/18/2014',  // default to date
	changeMonth : true,
	changeYear : true
} );
},
 filter_placeholder : {
  from : 'From...',
  to   : 'To...'
 }
};
tbl.tablesorter( so );
tbl.find( 'tbody' ).append( row );
$.tablesorter.updateAll( tbl[0].config, true, function() {} );

Pretty straightforward. I just think in the updateAll() you select the trs then unlink the tablesorter-filter-row from the table (or from the table-sticky) and then iterate the trs (including the tablesorter-filter-row). Selecting the trs after unlinking the tablesorter-filter-row would cure it--if I assume correctly (not a altogether frequent occurrence).

**Comment by Mottie** [comment]
Well, first off don't use `updateAll` unless new content in the `thead` is added. Use [`update()`](http://mottie.github.io/tablesorter/docs/index.html#update), or better yet, use [`addRows`](http://mottie.github.io/tablesorter/docs/index.html#addrows).

Once I get the motivation & the bugs worked out of the `filter_customVal` option, the filter formatter option & extra files will get deprecated.

**Comment by BitStinker** [comment]
I changed your code to trap for the missing table and all is well with it:

var wo = $cell.closest( 'table' );
if( wo.length == 0 )	return;
wo = wo[0].config.widgetOptions;

I was using updateAll() to try to get the select boxes to load (my other issue - #1057). It turns out that updateAll() DOES solve that other issue.

**Comment by Mottie** [comment]
Thanks for sharing the code for a fix! I've implemented something similar.
