### ISSUE TITLE
update doesn't seem to refresh the filter-selects

### ISSUE THREAD

**Issue by BitStinker** [Mottie/tablesorter#1057]
After adding a row to tbody, I call update on the table. The filter-select boxes in the filter row do not reflect the new row's contents. What am I doing wrong?

tbl.find( 'tbody' ).append( row );
$.tablesorter.update( tbl[0].config, true, function() {} );
$.tablesorter.setFilters( tbl, ['', '', newcontent], true );

**Comment by Mottie** [comment]
Hi @BitStinker!

It works for me in [this demo](http://jsfiddle.net/Mottie/856bzzeL/688/).

**Comment by BitStinker** [comment]
I suspected that the use of updateAll() would fix my problem but then I ran into that other issue with updateAll() (#1056). I tweaked your code to eliminate the updateAll() problem and, sure enough, the use of updateAll() instead of update() above does reload the select boxes correctly.

I'll put together a demo that will reproduce the issue...probably later today.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
