### ISSUE TITLE
(Question) Method for hooking into Search event to customize resulting display?

### ISSUE THREAD

**Issue by Bratzilla** [Mottie/tablesorter#1059]
Hopefully this is more of a question than an actual issue (maybe hidden in the documentation somewhere I couldn't find).

Currently, when using search for parent/child rows, the parent will appear even if the search term is not in the parent text (title or description in my case). The problem is that during a quick pre-alpha usability test users repeatedly questioned why that was happening. So I'd like to just nip this problem by hiding parent rows that do not contain the search term. This in theory could be done by adding a "display: none;" after the search to the non-conforming parent row(s). 

What would be the best way to do this? Is there something in the documentation that addresses this? Thanks!

**Comment by Mottie** [comment]
Hey @Bratzilla!

I'm starting to think you shouldn't be using child rows. If a parent row isn't show along with a child row, would the user know what subcategory they are looking in?

From looking at the screenshots you shared in #1020, maybe instead of having a format like this:

```
Category 1 (parent)
 -- Category 4
 ---- Category 11
 etc
```

It might be better to include the parent in each cell:

```
Category 1
Category 1 > Category 4
Category 1 > Category 4 > Category 11
etc
```

Yes, I could add yet another option which can be set to not include a parent row if it doesn't match the search criteria, but to me that defeats the purpose of the parent-child relationship.

**Comment by Mottie** [comment]
Or, did I completely misunderstand your question? I tried [the demo](http://jsfiddle.net/1a5yu8yq/79/) from the other issue, and if I search for say "x", no results show up... but if I search for "3" in the first column, the parent and one child row are shown.

Are you saying you don't want the parent to be included in the results? If so, then I didn't misunderstand...

**Comment by Bratzilla** [comment]
Hmm... once I'd posted, I had started thinking the same thing. The reason for the parent/child relationship has to do with keeping category families together (drag-and-drop sorting for one). I may just go ahead and re-introduce the icons to clearly mark the parent categories as this could help with usability.

So, instead of worrying about yet another option (as if you don't have enough to do), is there a way to fire something upon search completion? I can take it from there. :)

**Comment by Mottie** [comment]
You can use the [filterEnd](http://mottie.github.io/tablesorter/docs/#filterend) event.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
