### ISSUE TITLE
Handle sortend event to bind data manually

### ISSUE THREAD

**Issue by thanh1259** [Mottie/tablesorter#1064]
Hi,

I use tablesorter for my MVC project, i manage to handle sortEnd event to get selected sort column so that i can do sort data manually via ajax, but the problem is, tablesorter do sort before i bind the new data to table, and it may make user confuse. Any method or property i can use to prevent table data change when do sort, means i still want sort event fire but keep data there.

Thanks.

**Comment by Mottie** [comment]
Hi @thanh1259!

You can disable client-side sorting by setting the [`serversideSorting` option](http://mottie.github.io/tablesorter/docs/#serversidesorting) to `true`. This is what the pager uses when an [`ajaxUrl` option](http://mottie.github.io/tablesorter/docs/#pager-ajaxurl) is set.

**Comment by thanh1259** [comment]
Hi Mottie,

Nice, it works :+1:  thanks so much.

One more thing, using 'savesort' option will enable tablesorter can remember last sort order, and it work fine. But because i use tablesorter inside a MVC partial view, and that partial view use for multiple pages, the scenario is in page a1(include partial view), i sort 2nd column, tablesorter remember 2nd colum, then i go to page a2(also include partial view), it automatically set default sort by 2nd column instead of 1st column. I've tried set initial sort order by column 0: { sortInitialOrder: 'asc' }, but it didn't work. How can i solve it?

**Comment by Mottie** [comment]
I think you just need to make each *different* table have a unique ID.

```html
<table id="mvc-page-a1">...</table>
...
<table id="mvc-page-a2">...</table>
```

That way the storage widget is able to target the correct tables.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
