### ISSUE TITLE
scroller widget strange problem,

### ISSUE THREAD

**Issue by prtome** [Mottie/tablesorter#1065]
Hello,
I have a strange problem with the scroller widget. I works perfectly on most of my tables but on one specific page.
I do a query in the database, and separate the resulting data in 3 different tables, that I put in 3 different tabs.
 It works perfectly until I add the scroller widget: only the first table in the first tab is shown correctly, with the scroller. The two other tabs are empty, they show nothing - but the html is correct. It is simply not shown (and I don't see any "hidden" word)
In Firefox, if I click on that void and say " inspect element" then I shows ! 
but not in Chrome or Safari (I am on mac x10.11.1, latest tablesorter)

If I take out the scroller widget from tables in tab 2 and 3 they show perfectly well
Has anybody seen that before and can hint to me where I should look to solve this problem ? thanks
Pat

**Comment by Mottie** [comment]
Hi @prtome!

The scroller widget needs the table to be visible to initialize properly because it needs to calculate column widths. Try triggering an "applyWidgets" event on the table when it becomes visible.

**Comment by prtome** [comment]
Ok ! that is why it does show the first tab - it is visible of course since that is the one being displayed
But I am obviously not understanding how to trigger correctly the applyWidgets. I saw the example in the docs.
my tabs are Atab and Btab,  my tables have id tableA and tableB
and I have a populateTables function where i define all the table sorter stuff.

I wrote
$('#Atab').click(function(e) {
    console.log("in Atab");
    $('#tableA').data("tablesorter").widgets=[ "output","scroller","filter"];
      $('#tableA').trigger('applyWidgets');   
  }); 
$('#Btab').click(function(e) {
    console.log("in Btab");
    $('#tableB').data("tablesorter").widgets=[ "output","scroller","filter"];
      $('#tableB').trigger('applyWidgets');   
  }); 

I have put those "click" inside my function, outside my function, but nothing happens. I get in Atba and Btab in the log, so I know it went in the click function
What else am I missing ? thanks.

**Comment by Mottie** [comment]
Take a look at [this example](http://jsfiddle.net/Mottie/abkNM/794/) which is only for the zebra widget, but is essentially the same code for any widget.

The `activate` callback for jQuery UI tabs is used to either initialize tablesorter or update the widgets:

```js
var tablesorterOptions = {
    theme: 'blue',
    widgets: ["zebra"]
};

$("#tabs").tabs({
    create: function (event, ui) {
        var $t = ui.panel.find('table');
        if ($t.length) {
            $t.tablesorter(tablesorterOptions);
        }
    },
    activate: function (event, ui) {
        var $t = ui.newPanel.find('table');
        if ($t.length) {
            if ($t[0].config) {
                $t.trigger('applyWidgets');
            } else {
                $t.tablesorter(tablesorterOptions);
            }
        }
    }
});
```

**Comment by prtome** [comment]
Thanks, I am doing it differently, because I am not using jqueryUI but Uikit(getuikit.com) . I am simply adding at the end of my function that populates the tables, after the definitions of table sorter, the trigger to apply the widgets.
It works perfectly for all the tabs that are in the same "populate", and not for the tab that is built from  another populate. Since we were having discussions about where to put that tab (in that page or alone) I solved it moving the tab away - and it ended also the discussion ;) 
Thanks again for your help and for this very useful library
Pat

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by prtome** [comment]
yes thank you, I thought I had closed it

I seem to understand now how things work, and trying to get it to work with the tabs using getuitkit. 
The whole system is amazing thanks
