### ISSUE TITLE
scroller widget and colgroup style width

### ISSUE THREAD

**Issue by prtome** [Mottie/tablesorter#1067]
Hello

I have another problem with the scroller widget. In my page I have 3 tabs, with 3 different tables, coming from the same db query (means i split the data after the ajax query, and get it in 3 different variables).
My solution to the "non view " problem has been to fill the table with its own data only when I click on the tab ( I can't get the callback function to work - yet). Works like a charm but ;)
when I open the page, first tab has this for the colgroup:

```html
<colgroup class="tablesorter-colgroup"><col style="width: 12.5%;"><col style="width: 12.4%;"><col style="width: 12.4%;"><col style="width: 12.4%;"><col style="width: 12.4%;"><col style="width: 12.4%;"><col style="width: 12.4%;"><col style="width: 12.5%;"><col style="width: 0.1%;"></colgroup>
```

see last one, width 0.1% - which is perfect for the scrollbar, shows very nicely

But in all the other tabs  or if I go back to tab 1 after visiting the others, colgroup is

```html
<colgroup class="tablesorter-colgroup"><col style="width: 4.9%;"><col style="width: 14.5%;"><col style="width: 10.3%;"><col style="width: 14.5%;"><col style="width: 7.4%;"><col style="width: 17.7%;"><col style="width: 18.5%;"><col style="width: 12%;"></colgroup>
```

the width have changed - but most of all the last one! which means I get a visible line until the scrollbar

my tables have plenty of hidden columns and I thought maybe I missed some "hidden"  in the filter_cellFilter but no, if I take out the scroller, the table shows perfect.
So I suppose it has something to do with the scroller resizing the table ? 
what am I doing wrong ? 
or is this normal behaviour, and I should fix the last column width (but not sure I understand how) ?

Thanks again for your help
Pat

**Comment by prtome** [comment]
Hello
I have "solved" my problem for now using an iframe for the scroll instead of the scroller widget - not as nice, but it works. Until I understand what I am doing and learn to use the callback correctly which might be the solution to all my problems (like also children rows not working in tabs with scroller)
If you have the  time it would be very nice if you could point me to what I am doing wrong  - if it does not take to much of your time. 
Thanks again for all your help
Pat

**Comment by Mottie** [comment]
Hi @prtome!

You can add your own `colgroup` with all the setting you desire, leave off the "tablesorter-colgroup" class name though, and tablesorter won't add an additional one.

If you have a hidden column, make sure to include a hidden `col` within the `colgroup` or the `col` will apply to the next non-hidden column.

If you want to use an iframe instead, maybe include the stickyHeader widget, so the header sticks to the top of the iframe while scrolling.

**Comment by prtome** [comment]
Thanks - but I don't have in my classes the tablesorter-colgroup ? it comes by itself .
good idea for the stickyHeader , I have a look, would be much nicer. 

And I think that what is happening is something as you say, I have hidden columns in the middle of my visible columns (all this to be able to have a nice view of that data, but be able to print the raw data- so it is in hidden columns - maybe I should simplify and do an ajax call to the db instead...- and everything else would work !) and it must be all messed up

Thanks for all your help
pat

**Comment by Mottie** [comment]
Sorry, I know that the `<colgroup>` HTML you shared was added by tablesorter because of that class name. I was saying, manually add that same HTML without the class to keep the column widths you desire.

Are you using the print widget? You can set it up to print all columns, even if some are hidden. Or are you saying that only the hidden columns are to be printed?

**Comment by prtome** [comment]
Oh I see, sorry I di not understood before. Yes I should try.
I am using the print widget, and printing all columns, even those hidden, and it works perfectly.
In fact not all , I don't print the "well formatted" columns, but their hidden versions.

For the sticky widget, I have added the js file, and in the table sorter def I added 
 cssStickyHeaders_attachTo      : $('.contProvider'), // name of my wrapper
      cssStickyHeaders_addCaption    : false,
but it does not stick :( 
I suppose I will find out tomorrow, it is getting late here
Have a nice sunday 
Pat

**Comment by Mottie** [comment]
If the table is inside an iframe, you shouldn't need to use the `attachTo` option. It will attach to the body of the iframe by default.

**Comment by prtome** [comment]
it is in a  uk-scrollable-box  - which I think I need to understand what that is exactly. but it looks like narrow-block you are using in your example in the docs. Which is why I copied the same code. There must be something else that is not working or that I am missing.

I see looking at your html doc page that the head of the table has  style="transform: translate(0px,244px);"   and mine has nothing like that, so obviously the widget is not being taken.
I will try tomorrow with a simpler table, no children, no hidden, no tabs, and make it working there
Thanks again
Pat

**Comment by Mottie** [comment]
Just in case you didn't notice, there is a non-css3 [sticky header widget](http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html). Which might be needed if you need to support older browsers that don't have css3.

If you have a scrollable box, then it gets a little tricker, you'll need to use `attachTo` on the scollable element which may not always be so obvious... but it *usually* is the parent of the table after the scrollable box plugin (not this widget) has initialized.

**Comment by prtome** [comment]
thanks - that was the reason, I was mixing both widgets ...Now it is working, but my scrolled rows are in front of my headers or my headers are transparent .. some CSS to modify, but it is another problem ;)
thanks a thousands
Pat
