### ISSUE TITLE
2.24 bower broken

### ISSUE THREAD

**Issue by ivan1986** [Mottie/tablesorter#1068]
subj - empty package after update

**Comment by trwill** [comment]
+1 also saw the same

**Comment by Mottie** [comment]
Thanks for reporting this problem. I'll push out a new version today.

**Comment by Mottie** [comment]
Grrr, I just tried to install and now the `dist` folder is empty... Are you guys seeing the same thing?

**Comment by trwill** [comment]
yes... dist folder was empty for me first time as well. I now see a few more files in the root tho, previously it was only bower.json and an empty dist folder

**Comment by Mottie** [comment]
So it was fine in v2.23.5?... maybe I'll just completely revert the bower.json file back. The [spec for bower.json](https://github.com/bower/spec/blob/master/json.md) doesn't make it very clear.

**Comment by trwill** [comment]
One of the big differences I notice are the `ignore` values in `bower.json`. I don't see those in the previous tags. The new ignores include all css/js, and the missing folders.

**Comment by Mottie** [comment]
Ok, going back to an empty `ignore` setting works... well, all the files show up, but at least the `dist` isn't empty.
