### ISSUE TITLE
 cssStickyHeaders and hover-highlight conflict ?

### ISSUE THREAD

**Issue by prtome** [Mottie/tablesorter#1069]
hello
I have a unwanted behaviour when using both  cssStickyHeaders and hover-highlight in my table. When doing so, the rows that are scrolled are visible over the header. 
Since I had that problem in my code, I tried to find out what was going on
I have taken the  source code of the cssStickyHeaders page, and simplified it until I had only the table2 example - and began adding what was in my code. I am attaching a screenshot of the problem. 
This happens only when I have : 
	<table id="table2" class="tablesorter  hover-highlight">
without hover-highlight no problem at all . There is nothing else added to the code from the sticky example page. In my css I have theme.default.css to which I appended the hover-highlight css  given in  that specific page.

I wanted to upload the corresponding files but I am not allowed.
I suppose there is a conflict somewhere ?

![screenshot](https://cloud.githubusercontent.com/assets/11536421/10889988/82e5167e-8195-11e5-9959-ff61c7ce19c6.png)

thanks
Pat

**Comment by Mottie** [comment]
Hi @prtome!

There might be some interference from other css... I set up [this demo](http://jsfiddle.net/856bzzeL/712/), and it doesn't look like that screenshot.

**Comment by prtome** [comment]
hi
can you see this http://jsfiddle.net/zzrey6Ln/
it is my first try at jsfiddle, don't know if it works well. I put in there everything and it shows my problem
I'll try to modify yours to see if I reproduce
thanks

**Comment by Mottie** [comment]
When you modify a jsFiddle, click the "Update" button at the top, then copy the new URL.

**Comment by prtome** [comment]
Thanks I had no clue what to do (maybe I should read the docs first ;)
this is the modified link, that i sent before http://jsfiddle.net/zzrey6Ln/1/

Ok - the problem is with the css of hover-highlight
I forked your demo http://jsfiddle.net/kdcq77ph/1/ 
and added the class hover-highlight to the table
and copy pasted the css in http://mottie.github.io/tablesorter/docs/example-css-highlighting.html
and the problem is there

thanks

**Comment by Mottie** [comment]
Hmm, it looks like it's an issue with css transforms and z-indexes, due to a [stacking context](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context).

I won't have time to dig into this until later tonight....

**Comment by prtome** [comment]
thanks, I don't know CSS (very little) unfortunately  which means I cannot help you with that .
But please, don't spend the night on this  ;)  it does not seem to be a common problem to those using tablesorter, and I will be so glad when you get it solved that I can wait for that !
thanks again for your help
Pat

**Comment by Mottie** [comment]
Ok, so I think I tried everything I could without any success.

Since the transform is placing the `thead` under the `tbody`, I have a feeling that any solution that we did find wouldn't work in all browsers. So that leaves use with using the stickyHeaders (non-css) widget (http://jsfiddle.net/zzrey6Ln/2/).

**Comment by prtome** [comment]
Thanks - works perfectly like that.
I will use this non-css widget then
cheers
