### ISSUE TITLE
Filter Widget and Math Widget

### ISSUE THREAD

**Issue by doveyg** [Mottie/tablesorter#1071]
I am currently using 2.18, with the filter widget installed when I tried to include math functionality I noticed that my external search wasn't working correctly, using the following method;

$('table').trigger('search', [ columns ]);

so I decided to upgrade my version of tablesorter but encountered a bug, report here:

https://github.com/Mottie/tablesorter/issues/1070

so i cannot continue and I was wondering if there were any issues with the latest version of tablesorter has any compatibility issues between Filter & Math.

I was also wondering what the third argument in this snippet of code was for, the boolean;

$.tablesorter.setFilters( $('#table'), filters, true );

side issue: the documentation for http://mottie.github.io/tablesorter/docs/example-widget-filter.html is wrong. Tablesorter isn't up to version 2.9 yet, 2.4 is the latest version.

**Comment by Mottie** [comment]
Hi @doveyg!

I haven't noticed any issues with the filter + math widget... try out the main [math widget demo](http://mottie.github.io/tablesorter/docs/example-widget-math.html#demo) - it works perfectly for me. If you are having an issue, after I provide a fix for #1070, then please provide a demo of the issue you're having.

The third argument of [setFilters](http://mottie.github.io/tablesorter/docs/#function-setfilters) will apply the search to the table. If `false` the inputs will get updated, but the actual search won't be applied... in case you want to add rows, or something.

**Comment by Mottie** [comment]
Also, I don't understand what you meant by:

>  Tablesorter isn't up to version 2.9 yet, 2.4 is the latest version.

This fork of tablesorter is currently at v2.24.2.

In this next update, I'll make it so that last parameter defaults to `true`, so you can do this:

```js
// set filters AND apply (the last parameter "apply" is now true by default)
$.tablesorter.setFilters( $('#table'), filters );
```

**Comment by doveyg** [comment]
Sorry, my bad. your right about the versions.

**Comment by doveyg** [comment]
Updated and everything seems to be fine. Thank you!
