### ISSUE TITLE
sortRestart example not working

### ISSUE THREAD

**Issue by rickselby** [Mottie/tablesorter#1072]
OS: Ubuntu 14.04; Browsers: Chrome, Firefox, Opera,

The example https://mottie.github.io/tablesorter/docs/example-option-sortreset-sortrestart.html doesn't do anything; nor does the demo given the last time an issue with sortRestart was raised (http://jsfiddle.net/Mottie/abkNM/4975/).

**Comment by Mottie** [comment]
Hi @rickselby!

Thanks for reporting this issue... it looks like it is from the v2.24.0 update. I'll get it fixed ASAP.

**Comment by Mottie** [comment]
Ok, this problem is now fixed in the master branch... I plan on a new release very soon.
