### ISSUE TITLE
sortRestart with mutiple header rows

### ISSUE THREAD

**Issue by rickselby** [Mottie/tablesorter#1074]
Thanks for getting sortRestart working again! I have an example where I have mutiple header rows (grouping headers together), and when using sortRestart the first 'child' column can't be sorted - the rest work fine. Example:

http://jsfiddle.net/zbsvudLv/

Alphanumeric and Animals columns won't be sorted because of the header row above.

**Comment by Mottie** [comment]
Hi @rickselby!

Thanks again for testing & reporting this issue. I'll have it fixed in the master branch here shortly.

**Comment by rickselby** [comment]
Apparently I didn't save the fiddle... http://jsfiddle.net/zbsvudLv/1/ is the example I was talking about, and it might be a bit quick, but it's not sorting the first column in each 'group'

Thanks for looking into these so promptly!

**Comment by Mottie** [comment]
[This demo](http://jsfiddle.net/Mottie/zbsvudLv/2/) uses the core file in the master branch.

**Comment by rickselby** [comment]
Ah, thanks!
