### ISSUE TITLE
Pager buttons break if using multiple tables

### ISSUE THREAD

**Issue by badbash27** [Mottie/tablesorter#1076]
I am trying to get a page to work where I have multiple tables, and a single pager field. 

I am doing this using javascript / ajax where my tables are held in seperate .php files, and then loaded into a div on the main page upon drop a down selection. When a new drop down is selected, the current table disappears, and the new selected one takes its place.   

What I want to do is keep my current plugins, for this instance, cssStickyHeaders, and keep the pager option at the bottom of the page separate from the table, which is why I do not have a pager div in each of my separate content docs.  I am doing it this way because each table query's a SQL database containing thousands of entries, and I do not want to bog the server down by pre-loading every page if I only need one.  

Currently, My tables are labeled id="table0", id="table1" ..etc. and I have .tablesorterPager({container: '.test0'}); '.test1'.. etc for all of my tablesorter functions.  On the main page, I have a script that changes the class of the pager div to match the pager container on their respective tables.  

Problem I am having is that the first table functions as it should, but when I move to a different table, the pager buttons break.  I am still able to navigate via the drop down, and when the buttons are clicked, the "1 to 30 of 50 rows" updates accordingly. The table just does not change.  I am sure that I am missing something simple, just not sure what it might be.  Any insight would be greatly appreciated. 

I can upload my source code if how I explained my setup is convoluted.

**Comment by Mottie** [comment]
Hi @badbash27!

It sounds like everything is set up properly. I wonder if the problem is in the initialization. The easiest method would be to do something like this ([demo](http://jsfiddle.net/Mottie/abkNM/7227/)):

```js
$(function(){
	$('table').each(function(){
		$(this)
			.tablesorter({
				theme: 'blue',
				// more options...
			})
			.tablesorterPager({
				container: '.' + this.id,
				// more options...
			});
	});
});
```

If that doesn't help, please modify the demo I shared to demonstrate the issue being described.

**Comment by badbash27** [comment]
Changed my code to resemble what you have, and I am still experiencing the same problem.  I am not really able to replicate my site in JSfiddle though because my tables are referenced in external files.  Here are a few excerpts of my program though in the event that it helps:

Script that changes which table is being displayed on the main page by hiding a div, and loading one in it's place as well as changes the pager class to resemble which table is being loaded
```
 $(document).ready(function () { 
  $('.insertData').hide();
  $('#table0').show();
  $('#table0').load('content/table0.php');
  $('#pageView').change(function () {
        $('.insertData').hide();
	$('#pager').attr('class','pager ' + $(this).val()); // changes pager class to new table
        $('#'+$(this).val()).show();
	$('#'+$(this).val()).load('content/'+$(this).val()+'.php');
	
  })
}); 
```

Where tables are inserted:
```
	<div class="wrapper">
		<div class="insertData" id="table0">
			<!--Table0 get's loaded here at start-->
		</div>
		<div class="insertData" id="table1">
			<!--Table1 gets loaded here upon dropdown change-->
		</div>
	</div>
```

Pager script on main page:
```
	<div id="pager" class="pager table0"> 
   <img src="../tablesorter-master/addons/pager/icons/first.png" class="first"/> 
   <img src="../tablesorter-master/addons/pager/icons/prev.png" class="prev"/> 
   <span class="pagedisplay"></span>
   <img src="../tablesorter-master/addons/pager/icons/next.png" class="next"/> 
   <img src="../tablesorter-master/addons/pager/icons/last.png" class="last"/> 
   <select class="pagesize" title="Select page size"> 
      <option value="30" selected="selected">30</option> 
      <option value="40">40</option>
      <option value="50">50</option>
     <option value="100">100</option>
   </select>
   <select class="gotoPage" title="Select page number"></select>
</div>
```

Finally, I have two .php files that hold my tables.  The script at the top of both of them is:
```
$('table').each(function(){
	$(this).tablesorter({
    	theme: "blue",
    	widthFixed: true,
    	headerTemplate: '{content} {icon}',
    	widgets: ["column", "cssStickyHeaders", "filter", "zebra"],
		widgetOptions: {
			cssStickyHeaders_attachTo      : '.wrapper', // or $('.wrapper'
		}
	})
    .tablesorterPager({
    	container: '.' + this.id,
    	cssGoto: ".pagenum",
    	output: '{startRow} - {endRow} / {filteredRows} ({totalRows})'
	});
});
```

**Comment by Mottie** [comment]
Ahhh, in your [load callback function](http://api.jquery.com/load/#callback-function), you'll need to trigger an ["update" method](http://mottie.github.io/tablesorter/docs/#update):

```js
$('#table0').load('content/table0.php', function(){
    $('#table0').trigger('update');
});
```

**Comment by Mottie** [comment]
Actually, since the entire table is being replaced, you might just have to initialize tablesorter again.

**Comment by badbash27** [comment]
Pardon my ignorance, and thank you for your help thus far. But how would should I go about doing that? I attempted your previous example, and that did not work.  I am guessing because table0 is the one the page starts with, where table1 is the one that I imagine would be the one needing to reinitialize tablestorter.

**Comment by Mottie** [comment]
Is the table only being updated once?

Or are you somehow using the pager to update the table contents? If so, it would be easier to use the pager's [`ajaxUrl` option](http://mottie.github.io/tablesorter/docs/#pager-ajaxurl) to interact with your database.

**Comment by Mottie** [comment]
It would be easier to have a discussion if you joined me on `#tablesorter` IRC chat on freenode.net. Or if you need, I can also jump on https://gitter.im/Mottie/tablesorter.

**Comment by badbash27** [comment]
After chatting on IRC, we got the following code working:

``// index.php

<div class="wrapper">
	<div class="insertData" data-table="0"></div>
	<div id="pager" class="pager">
		<img src="../tablesorter-master/addons/pager/icons/first.png" class="first"/>
		<img src="../tablesorter-master/addons/pager/icons/prev.png" class="prev"/>
		<span class="pagedisplay"></span>
		<img src="../tablesorter-master/addons/pager/icons/next.png" class="next"/>
		<img src="../tablesorter-master/addons/pager/icons/last.png" class="last"/>
		<select class="pagesize" title="Select page size">
			<option value="30" selected="selected">30</option>
			<option value="40">40</option>
			<option value="50">50</option>
			<option value="100">100</option>
		</select>
		<select class="gotoPage" title="Select page number"></select>
	</div>
</div>

<script>
$(function () { 

	var $wrapper = $('.insertData'),

	initializeTablesorter = function() {
		$wrapper.find('table').tablesorter({
			theme: "blue",
			widthFixed: true,
			headerTemplate: '{content} {icon}',
			widgets: ["column", "cssStickyHeaders", "filter", "zebra"],
			widgetOptions: {
				cssStickyHeaders_attachTo : '.wrapper', // or $('.wrapper'
			}
		}).tablesorterPager({
			container: '.pager',
			cssGoto: ".pagenum",
			output: '{startRow} - {endRow} / {filteredRows} ({totalRows})'
		});
	};

	$('#pageView').change(function () {
		// clean up previous table
		$wrapper
			.find('table')
			.trigger('destroy')
			.trigger('destroyPager')
			.empty()
			.hide();
		// get new stuff
		$wrapper.load( 'content/' + $(this).val() + '.php', function(){
			// new table loaded, now initialize
			initializeTablesorter();
		});
	})
	// initialize
	.val( 'table0' )
	.change();

});

</script>
```

Just have to say thank you for taking the time to help me out.  Hope this helps other's in the future.
