### ISSUE TITLE
Question about group_formatter?

### ISSUE THREAD

**Issue by gAncient1** [Mottie/tablesorter#1077]
Is there a way to pull the raw data (unparsed) from the cache for group_formatter?

Ex.   A grouping of "0005293" would have a raw data of "0005293", but the cache.normalized would be "5293".

**Comment by Mottie** [comment]
Hi @gAncient1!

Hmm, currently there isn't a way to easily get the raw data to the `group_formatter` function. It would be really easy to provide it as an additional parameter though.

**Comment by gAncient1** [comment]
I see. I was going to try to overwrite the "digit" parser, but this sounds like a much better approach.

**Comment by Mottie** [comment]
Ok, the group widget in the master branch has been updated.

Use it as follows:

```js
group_formatter : function(txt, col, table, c, wo, data) {
    return data.rowData[ c.columns ].raw[ col ];
}
```
