### ISSUE TITLE
Print Delay

### ISSUE THREAD

**Issue by clod986** [Mottie/tablesorter#1081]
From the documentation, I found "Add print delay; allows browsers to render print preview."

Can anyone help me on how I should use it?

EDIT: I'm asking here because I cannot find anything on [the docs](https://mottie.github.io/tablesorter/docs/example-widget-print.html)

**Comment by Mottie** [comment]
Hi @clod986!

The print delay was added internally because browsers like Chrome were not rendering a print preview. More specifically, it delays printing by 10 ms ([ref](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-print.js#L95-L98)) to allow the HTML to render. It is not something you would notice. Also, it is not set up as an option, so there is nothing different you need to do to use it.

**Comment by clod986** [comment]
Hi @Mottie and thank you as usual!

Thanks for explaining how that works. I assume the answer to my next question is a big fat NO, but is there any way in which I can control what the user sees when it triggers the print command? 

In my case, I would like to show them ONLY the print preview but the browser (read Firefox) shows the print preview AND the print/cancel window on top of it, making the print preview useless.

**Comment by Mottie** [comment]
I could add an option to allow choosing between starting the print immediately or opening up the popup window.

**Comment by clod986** [comment]
This is exactly what I was looking for!!!

Thank you @Mottie !!

**Comment by clod986** [comment]
@Mottie works like a charm!

The resulting window doesn't scroll on firefox for me, but I guess it doesn't depend from you

**Comment by Mottie** [comment]
It's not documented, but you can change the popup window parameters. To add scrollbars, add this before initializing:

```js
$.tablesorter.printTable.popupStyle = 'width=500,height=300,scrollbars=1';
```

I guess I should have scrollbars on by default. If you want to see all the other options, look at [this reference](https://developer.mozilla.org/en-US/docs/Web/API/Window/open#Toolbar_and_chrome_features).
