### ISSUE TITLE
sort by tbody tr>td.eq(1).val

### ISSUE THREAD

**Issue by OsipovIgor** [Mottie/tablesorter#1082]
Hi.

How I can sort array of tbodies in table by value in second td

**Comment by Mottie** [comment]
Hi @OsipovIgor!

Would you provide an example? You can modify [this demo](http://jsfiddle.net/856bzzeL/), and please elaborate on how the sort is initialized.

**Comment by OsipovIgor** [comment]
Example: http://jsfiddle.net/fisker228/L8bwW/37/ . When I clicked "test1", I want sort tbodies by values: 589 and 885 at second column, but not sort 'td' on tbody

**Comment by Mottie** [comment]
If I understand correctly, you have two choices...

1. Remove all the extra tbodies (leaving only one tbody) and give the rows that won't be sorted a class name of "tablesorter-childRow" ([demo](http://jsfiddle.net/Mottie/L8bwW/38/))

    ```html
    <tbody>
        <tr style="border-left: solid; border: solid;">...</tr>
        <tr class="tablesorter-childRow"></tr>
        ...
        <tr class="tablesorter-childRow"></tr>
        
        <tr style="border-left: solid; border: solid;">...</tr>
        <tr class="tablesorter-childRow"></tr>
        ...
        <tr class="tablesorter-childRow"></tr>
    </tbody>
    ```

2. Use the sortTbody widget. Add a class name to the main row within each tbody - I used the class name of "main" ([demo](http://jsfiddle.net/Mottie/L8bwW/39/))

    ```html
    <tbody>
        <tr class="main" style="border-left: solid; border: solid;">...</tr>
        <tr></tr>
        ...
        <tr></tr>
    </tbody>
    <tbody>
        <tr class="main" style="border-left: solid; border: solid;">...</tr>
        <tr></tr>
        ...
        <tr></tr>
    </tbody>
    ```

    ```js
    $(document).ready(function () {
      $('#generalInfoTable').tablesorter({
        headers: { 0: { sorter: false } },
        widgets: ['sortTbody', 'zebra'],
        widgetOptions: {
          sortTbody_primaryRow: '.main',
          sortTbody_sortRows: false,
          sortTbody_noSort: 'tablesorter-no-sort-tbody'
        }
      });
    
      $('#generalInfoTable thead th:first-child').removeClass('header');
    });
    ```

    \* NOTE \* I found an issue with the sortTbody widget, which I will fix. So if you use this method, get the sortTbody widget from the master branch!

**Comment by OsipovIgor** [comment]
Thank you so much. It helped.
