### ISSUE TITLE
Can above and below subtotal rows be added by the tablesorter math widget?

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#1083]
As an enhancement, could the math widget add the above and below subtotal rows to the table instead of these rows being specified in the HTML? This might require that `sortList` be set for the first column and sorting turned off for that column. Since I count on tablesorter to sort the table in the first place, I would have to add the subtotal rows using jQuery, which made me wonder if that could be added to tablesorter instead.

**Comment by Mottie** [comment]
Hi @lindonb!

If this capability were added, there are many questions that need to be addressed, and possibly added as options:

* How would one tell the widget where to add the subtotal row? And what if there were multiple subtotal rows?
* Would the cell span across all columns if only one column needed a subtotal, or just add a cell for every column and leave the others empty?
* What happens to columns that don't contain any values, or only have text?

You don't have to worry about sorting moving a subtotal row if it is fixed in place by using either using the [static row widget](http://mottie.github.io/tablesorter/docs/example-widget-static-row.html), or adding the row to be fixed in a separate `tbody`.

**Comment by lindonb** [comment]
Hi @Mottie,

Hmmm, yes, I could see how it would get complicated. In my case, users create a table with rows in no particular order using a type of markdown syntax which then tablesorter fixes up by sorting, etc. So I think I'll be stuck adding with jQuery if I want to offer this option. Thanks for considering.

**Comment by lindonb** [comment]
Hi @Mottie!
Re-opening this for at least a little further discussion. Regarding your questions:

> How would one tell the widget where to add the subtotal row? And what if there were multiple subtotal rows?

This could be based on the `sortList` parameter, creating a subtotal every time there was a break in the sort. Or based on how the grouping widget works. 

> Would the cell span across all columns if only one column needed a subtotal, or just add a cell for every column and leave the others empty?

I would suggest adding a cell for every column, otherwise it's easy to get out of sync with the `colspan` setting when adding/hiding columns

> What happens to columns that don't contain any values, or only have text?

Could the `math_ignore` parameter be used?

Thanks for considering. As I mentioned, in my case I'd have to add using jQuery one way or the other if I decide to offer the feature.

**Comment by Mottie** [comment]
Hey @lindonb!

> > How would one tell the widget where to add the subtotal row? And what if there were multiple subtotal rows?

> This could be based on the sortList parameter, creating a subtotal every time there was a break in the sort. Or based on how the grouping widget works.

What I meant to ask was after which row should the subtotal row be added? `sortList` stores column indexes for sorting. So, I'm guessing you mean the rows for each subtotal would change with sorting and thus mess up the grouping of data. I think that's why it's best to keep the data in separate tbodies.

> I would suggest adding a cell for every column, otherwise it's easy to get out of sync with the colspan setting when adding/hiding columns

Not everyone will want a cell for every column; colspans seems to be really popular, I guess mostly because of the appearance of the table.

> Could the math_ignore parameter be used?

Yes, it could, but this also requires developers to follow a strict no colspan rule.

----

Would you consider a method to manipulate your HTML and create separate tbodies for each subtotal grouping? That would make it easy to create a subtotal row which could contain colspans. I think it might be the easiest solution.

**Comment by lindonb** [comment]
Hi @Mottie,

I guess what strikes me is that the way the HTML has been set in the examples on the math demo page, the first column "sort" has effectively been fixed and is not sortable. Seems like this could also be achieved through the jQuery instead of through HTML without separate tbodies. I.e., using the math widget would fix the first columns sort in whatever way you think best, and add the subtotal rows whenever there was a break in values in the first column. 

I am indifferent on the colspan versus cells question - was just attempting to answer your question there.

But I understand there still be may be problems with this approach. Unfortunately manipulating the HTML doesn't work as well in one use case I have: users create their own tables through a markdown syntax and tablesorter is used to sort the table - including the first column which is the one that needs to be a fixed sort for the subtotals to work.

Thanks again for considering.

**Comment by Mottie** [comment]
The first column is fixed in the math demo because there really isn't anything to sort. All tbody rows in each group of that column have the same content. I was just an example I copied from somewhere else. The second table is fully sortable.

Can you share an example of what a user might input (the markdown is fine) and what the expected result would be? Maybe that would give me a better idea of what you're trying to accomplish and what needs to be done to accomplish it.

**Comment by lindonb** [comment]
After looking at it, having a new data gathering attribute type of `page` would probably do it. E.g., in addition to `col-sum` and `all-sum`, to be able to use `page-sum`, which would exclude rows hidden by the pager in addition to those hidden by filtering.

**Comment by Mottie** [comment]
Maybe I can add an option that allows you to add a custom filter like `:visible` to be applied to the resulting rows.

**Comment by lindonb** [comment]
That should work!
Thanks.

**Comment by Mottie** [comment]
Ok, try that updated code... I didn't spend much time testing it, so it might have a bug in there.

Use it as follows:

```js
math_rowFilter : ':visible:not(.filtered)'
```

\* NOTE: Include `:not(.filtered)` if you want to ignore rows filtered by the filter widget. I made it so if this option is set, it overrides the filtered row check, just in case.

**Comment by lindonb** [comment]
Looks promising, Noted a couple of things:
* Looks like there's a typo in `widget-math.js`, lines 48, 69, 83, where the parameter is referred to as `match_rowFilter` instead of `math_rowFilter`
* Even before this commit I noticed in version 2.24.5 that setting `math_event : 'pagerComplete'` no longer triggered a math recalculation upon paging (this was working in 2.23.5 - not sure when it stopped). This causes a problem with this latest change - it works fine upon initial page load, but doesn't reliably recalculate upon pagination

Thanks for all the quick work on this!

**Comment by Mottie** [comment]
Ok, I fixed my spelling errors LOL...

Hmm, instead of `'pagerComplete'` try `'tablesorter-ready'`... I'll try to figure out why the event isn't firing.

**Comment by lindonb** [comment]
Thanks! 

`tablesorter-ready` didn't work.

**Comment by Mottie** [comment]
Ok, try it now... it was because an internal flag wasn't being cleared properly.

**Comment by lindonb** [comment]
Works like a charm - thanks @Mottie!!

**Comment by lindonb** [comment]
One question - is it possible with the `math_rowFilter` option to choose which footer rows use this and which don't? For example, it might be good to be able to have two total rows, one to show the page total and the other to show the total for the entire table.

**Comment by Mottie** [comment]
Ok, you can now add a data-attribute to the row to override the `math_rowFilter` option (in the master branch):

```html
<tr data-math-filter=":visible">...</tr>
```

**Comment by lindonb** [comment]
Hi @Mottie,

I'm probably being slow but I'm not quite sure how to use this override. Let's say I have two `<tfoot>` rows, both with "col-sum" totals on the same columns. Let's also assume the pager is on and there are multiple pages (so some rows are hidden). How do I make one row have page totals of only visible rows, and the other row have totals of all column amounts even if hidden by the pager?

**Comment by Mottie** [comment]
Try

```html
<tr data-math-filter=":visible:not(.filtered)"> ... </tr> <!-- Page totals (only visible) -->
<tr data-math-filter=":not(.filtered)"> ... </tr> <!-- Totals for everything -->
```

A row with a `data-math-filter` will override the `math_rowFilter` value, so actually the first row probably doesn't need that attribute added if the same value is already set in `math_rowFilter`.

**Comment by lindonb** [comment]
Got it - that seems to work for `col-sum` but not for for `all-sum`. In both cases the console log goes crazy (I have debug set to true) - seems like it goes into a recalculation loop. Not sure if that's just me.

**Comment by lindonb** [comment]
I think the console problem was because I had set `math_event : 'tablesorter-ready'`

When I set back to `pagerComplete`, the console behaves normally. But it seems like I need to use `tablesorter-ready` because otherwise the totals that should be just for visible rows includes all rows when the page first loads. After paging it correctly shows the page total for only visible rows.

**Comment by lindonb** [comment]
Looking at the console with `debug : true` and with `math_event : pagerComplete`, the math widget calculates the sums 3 times. For the sum of visible rows, it is calculate correctly the first two times and then the third time it totals all rows instead of only visible rows.

**Comment by lindonb** [comment]
Also, the `data-math-filter` override doesn't seem to work on `all-sum` - it always calculates as the grand total of all non-filtered rows.

**Comment by lindonb** [comment]
Hi @Mottie - any progress on this one? Do you see the same issue?

**Comment by Mottie** [comment]
Sorry, I forgot about this issue since it was closed. I'll look into it now.

**Comment by Mottie** [comment]
Ok @lindonb!

Please try out the latest updates. It looks like it works perfectly now, and I optimized it   so that the cache won't be updated unless cell content was changed.

**Comment by lindonb** [comment]
Thanks @Mottie!

Couple of things:
* I only got page totals until I changed line 316:
```javascript
// I changed this:
hasFilter = hasFilter || $el.attr( mathAttr + '-filter' ) || wo.math_rowFilter;
// To this:
hasFilter = $el.attr( mathAttr + '-filter' ) || wo.math_rowFilter;
````
* The `all` type doesn't get processed if the `math_priority` is not set. Looks like it's because it's not in the `priority` parameter in the `mathType` function that starts at line 287. But still when I set the `math_priority` option in order to include `all`, I get an error because the `arry` variable set at line 318 is undefined even though `$targetCells` correctly picks up the `all` cells in line 304.

* By the way, seems like the `data-math-filter` attribute now needs to be placed in the cell where `data-math` is set. That's okay but I thought that attribute was set for the row (i.e., for the `tr` element not the `th` element), but perhaps I was wrong about that.

It does seem much more optimized, so great work on that. The debug logging is fantastic by the way - I just recently discovered it and it is really helpful.

**Comment by Mottie** [comment]
Thanks for that awesome feedback @lindonb!

* I'll get line 318 fixed now
* Are you having an issue with the "all" type? It actually gets processed separately, and is always processed last.

    default option
	```js
	// order of calculation; 'all' is last
	math_priority : [ 'row', 'above', 'below', 'col' ],
	```

    recalculate sets it
	```js
	changed = changed || math.mathType( c, $cells, [ 'all' ], hasFilter );
	```

    the function is called inside of a loop because "all" functions may have different filters; which I added to the math demo (only in the master branch at the moment)

* I guess I forgot that I was using the `tr` to set the `data-math-filter`, but I think it make more sense to add it to the cell instead. Each cell uses a different math calculation, so why not use a custom filter for each. Sorry for the confusion, I'll need to update the math docs with this information as well.

**Comment by Mottie** [comment]
Oh, because of that change on line 318, a `data-math-filter` can no longer be set to an empty string, so I added this note to the docs as well:

> The `data-math-filter` attribute is ignored if set to an empty string; instead use `data-math-filter="*"` to target all rows as done in the first example on this page.

**Comment by lindonb** [comment]
> * Are you having an issue with the "all" type?

Yes, the `all` type totals aren't being calculated. The below line seems to be the issue. Since `changed` is true, it never goes to the `mathType` function. 
> `changed = changed || math.mathType( c, $cells, [ 'all' ], hasFilter );`

If I insert `changed = false;` just before this line, the `all` totals appear.

> * I guess I forgot that I was using the tr to set the data-math-filter, but I think it make more sense to add it to the cell instead. Each cell uses a different math calculation, so why not use a custom filter for each. Sorry for the confusion, I'll need to update the math docs with this information as well.

Agree, this change makes sense. Just wanted to point it out for the documentation, which it looks like you took care of.

**Comment by Mottie** [comment]
Doh! I thought I fixed that, but it looks like I only made that change inside the `mathType` function. I'll get that fixed right away!

**Comment by Mottie** [comment]
Are the latest fixes working for you? I am about to push a new release and would hate to have to push another just for a minor fix.

**Comment by lindonb** [comment]
Works great - thanks again @Mottie!

**Comment by Mottie** [comment]
Awesome :joy_cat:
