### ISSUE TITLE
Parser date-sugar missing?

### ISSUE THREAD

**Issue by doveyg** [Mottie/tablesorter#1084]
I'm looking in the repository for the parser-date-sugar.js file and it doesn't seem to be present. Where is it?

I have recently upgraded version, and I have noticed that the date detection on sorting is wrong. Don't know if this is new or not. So I am going to try and include sugar parser to see if it fixes it.

    Format: 2015-11-13 00:14:29

**Comment by Mottie** [comment]
Hi @doveyg!

Yeah sorry, the file is just named [`parser-date`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date.js) because it includes sugar and datejs parsers. Maybe I should rename it to `parser-date-libraries.js`?

**Comment by doveyg** [comment]
Is that rhetorical? Its just a file name. As long as its correct in the documentation it should be sufficient.

**Comment by Mottie** [comment]
Currently, the main documentation clumps all the date parsers into one line:

> Date parsers (v2.8; v2.24.6; includes weekday, month, two-digit year & sugar.js date parsers).

Because it is an all-in-one demo. It is still missing information stating that datejs is supported... I'll guess I'll add that now :stuck_out_tongue:

**Comment by doveyg** [comment]
Sorry I took so long to reply.

Due to the nature of the bug, it sometimes works it sometimes doesn't, how can i verify that i have installed the sugar parser correctly?

I have included the JS files into my HTML pages and am able to see them in the network sources debug window in chrome and also can access the sugar parser in `$.tablesorter.parsers;`

the files i have included are `sugar.min.js` and `jquery.tablesorter.parser-date.js`. 

I will assume to the issue is fixed until being told otherwise by clients.

**Comment by Mottie** [comment]
I hope you mean `parser-date.js`.

The easiest way to verify that the parser is set is to set the `debug` option to `true`, then look in the browser console.

To verify that the parser is working, you'll need to target the table, then look in the cache:

```js
$('table')[0].config.cache[0].normalized
```

The values are in an array, so look for the matching column which should contain date times (time in milliseconds since the epoch). Actually, I think I might add the first few values to the debug log because this is also something that I seem to be constantly doing.
```

**Comment by tcurtin** [comment]
@Mottie -- I know this is old, but I just ran into this as well -- there are some errors in the documentation.
This page: [https://mottie.github.io/tablesorter/docs/example-parsers-dates.html](https://mottie.github.io/tablesorter/docs/example-parsers-dates.html)
says to include scripts `../js/sugar.js` and `../js/parsers/parser-date-sugar.js`, but neither actually exists in the distribution.
sugar is only included minified under docs/js, and parser-date-sugar is apparently included in parser-date.js
This worked for me:
```
<script src="/your/path/to/tablesorter-master/docs/js/sugar.min.js"></script>
<script src="/your/path/to/tablesorter-master/js/parsers/parser-date.js"></script>

```
And then `th class='sorter-sugar'` for the appropriate columns in the table header.

**Comment by Mottie** [comment]
Hi @tcurtin!

[Sugar.js](https://sugarjs.com/) is a separate library. It's not included because it would be best to get the most up-to-date version from the source.

**Comment by tcurtin** [comment]
Fair enough!  The docs should be fixed to indicate that though, and they do still show using parser-date-sugar, which doesn't exist.

Thanks for this library, its been really helpful!

**Comment by Mottie** [comment]
Oh, thanks! I didn't realize that was listed in the docs.

**Comment by Mottie** [comment]
The docs will get updated with the next release... TBD.

**Comment by tcurtin** [comment]
Excellent - thank you!

*Tim Curtin*
Custom Logic Test Data Analysis
*T *+1 802.769.2791 | Tim.Curtin@GlobalFoundries.com
*GLOBALFOUNDRIES* 1000 River Road, Essex Junction, VT 05452

ASIC server access requests:
https://unity.usgfoundries.com/Applications/ASIC_Data_Access
GF Contact tool: https://unity.usgfoundries.com/Applications/GFContacts/
Useful info for ex-IBMers: https://unity.usgfoundries.com/Documents/GF/
