### ISSUE TITLE
How to perform action after the initial sorting of the table completes

### ISSUE THREAD

**Issue by darkred** [Mottie/tablesorter#1086]
I have an HTML table which is sorted successfully using the tablesorter plugin.  
It's sorted initially by columns 3, 0, and 2. 
Here is the code:  
```
$('#tbl').tablesorter ( {
        sortList : [[3,0],[1,0],[2,0]] 
    } );
```
I want to apply some CSS to that table **after** the initial multi-column sorting completes.

Is it possible?
_(I have found the`sortEnd` hook ([link](http://tablesorter.com/docs/example-triggers.html))  but unfortunately it only runs when you click on a column heading to sort by.  It doesn't work on after the initial sorting completes)_

**Comment by Mottie** [comment]
Hi @darkred!

You can bind to the [`tablesorter-initialized` event](http://mottie.github.io/tablesorter/docs/#tablesorter-initialized), or even use the [`initialized` callback function](http://mottie.github.io/tablesorter/docs/#initialized) to do whatever you want.

**Comment by Mottie** [comment]
Oh, and those only work on my fork of tablesorter, not the original (v2.0.5).

**Comment by darkred** [comment]
Thank you very much for the quick answer!
