### ISSUE TITLE
sort and filter Date range parsers in italian language

### ISSUE THREAD

**Issue by gianluis** [Mottie/tablesorter#1087]
hi mottie, so much that I do not write in this forum , but today I came back to work  jquery tables, so 
I again need your help.

how I can sort and filter two dates ( shown in the same column ) written in Italian, as, for example :

July 24, 2015 - August 2, 2015

I had thought to include a timetable , taken from https://mottie.github.io/tablesorter/docs/example-widget-filter-formatter-1.html#custom_filter_formatter_function_information but unfortunately the work I find it is hard and I really can not put the calendar in my column called week .

the table that I created here : http://boardingpass.altervista.org/ and it's the table of the workshift of my job! !O_o

I'd like to solve the problem without losing any other filter already included in the table.

can you give me some suggestions ? Thank you very much and have a nice day!
Gian Luis

**Comment by Mottie** [comment]
Hi @gianluis!

There is a lot of code on that page. Are you using jQuery UI's date selector?

Since you're working with Italian, you might want to use [jQuery Globalize](https://github.com/jquery/globalize) to parse the dates - I already have a [globalize parser set up](http://mottie.github.io/tablesorter/docs/example-parsers-globalize.html); or you can use a custom parser.

If you need help with that parser, please [update this demo](http://jsfiddle.net/1a5yu8yq/) with a reduced case (just the date column) to make it easier to work with.

**Comment by gianluis** [comment]
hi mottie, I've simplified the code. page http://boardingpass.altervista.org/index.html represents the table that I want to obtain, almost fully functional, except for the date column.

page http://boardingpass.altervista.org/esempio.html instead represents the date column. I tried to work on the links you gave me, but I did not understand much because I could not find a way to order the filter in ascending order by date (or pair of dates)

the alternative solution of jquery datapicker is incompatible with the js file inserted in my code.

I also tried to use jQuery UI's given selector but without success!

you have any ideas? 


many thanks in advance :)

**Comment by gianluis** [comment]
ho aggiornato la demo: http://jsfiddle.net/1a5yu8yq/94/

**Comment by Mottie** [comment]
Ok, I ended up updating the following files (so make sure to use the latest version from the master branch) - [demo](http://jsfiddle.net/Mottie/1a5yu8yq/97/):

* `jquery.tablesorter.js` (core) - only to define `$.tablesorter.dates`
* `parser-date-range.js` - added a new date range format which supports "dd MMMM yyyy"
* `widget-filter-type-insideRange.js` - updated to properly format the filter based on the set language.

Note: if you look at the demo code, you'll see some options that you'll need to include (`globalize` & `filter_searchFiltered`) to allow proper parsing:

```js
var ts = $.tablesorter;

if (!ts.dates) { ts.dates = {}; } // not needed if you update jquery.tablesorter.js

ts.dates.months = $.extend({}, {
    // See http://mottie.github.io/tablesorter/docs/example-widget-grouping.html
    // for details on how to use CLDR data for a locale to add data for this parser
    // CLDR returns an object { 1: "Jan", 2: "Feb", 3: "Mar", ..., 12: "Dec" }
    'it': {
        1: 'Gen',
        2: 'Feb',
        3: 'Mar',
        4: 'Apr',
        5: 'Mag',
        6: 'Giu',
        7: 'Lug',
        8: 'Ago',
        9: 'Set',
        10: 'Ott',
        11: 'Nov',
        12: 'Dic'
    }
}, ts.dates.months);

$(function () {
    var $table = $('table').tablesorter({
        debug: false,
        theme: 'blue',
        widgets: ["zebra", "filter", "numbering"],
        globalize: {
            // set column 0 to use Italian month parser
            0: { lang: 'it' }
        },
        widgetOptions: {
            // filter_anyMatch replaced! Instead use the filter_external option
            // Set to use a jQuery selector (or jQuery object) pointing to the
            // external filter (column specific or any match)
            filter_external: '.search',
            // set to false because it is difficult to determine if a filtered
            // row is already showing when looking at ranges
            filter_searchFiltered: false,
            // include column filters
            filter_columnFilters: true,
            filter_placeholder: {
                search: 'Cerca...'
            },
            filter_saveFilters: true,
            filter_reset: '.reset'
        }
    });

});
```

**Comment by gianluis** [comment]
mottie hi, 

thanks for the help, but unfortunately, taking a cue from your demo, I created a table (http://boardingpass.altervista.org/index.html), in which the date range conflicts with the widget pager.

the pager widget is essential, because the lines that will insert in the original project are more than a thousand.

how can I do to reconcile the italian date range with the pager widget?


the same happens with the demo http://boardingpass.altervista.org/index2.html for which setting the pager, the italian date range is not working.

Also in this table, looking for the date of 29 December from the search field just below the written rounds, the result will not be filtered by date range.

how can I do to fix these errors so that finally my table could meet all my filter parameters?

**Comment by Mottie** [comment]
As I stated in my last post, you need to include the [`widget-filter-type-insideRange.js`](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-filter-type-insideRange.js) and [`parser-date-range.js`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date-range.js) files. The extra filter type & parser together allows finding dates or numbers within a range.

Once you add those files, make sure to add the `globalize` option and `$.tablesorter.dates.months.it` data. Because of these settings, you can't use "December" in the filter, you'll have to use "Dicembre".

**Comment by gianluis** [comment]
files the widget-filter-type-insideRange.js and parser-dates-range.js were included in my table:

<pre>
<script type='text/javascript' src='mottie/jquery-2.1.3.js'></script>

  <link rel="stylesheet" type="text/css" href="mottie/normalize.css" />

  <link rel="stylesheet" type="text/css" href="mottie/result-light.css" />

  <link rel="stylesheet" type="text/css" href="css/theme.blue.css" />

  <script type='text/javascript' src="mottie/jquery.tablesorter.js"></script>

  <script type='text/javascript' src="mottie/jquery.tablesorter.widgets.js"></script>

  <script type='text/javascript' src="mottie/widget-filter-type-insideRange.js"></script>

  <script type='text/javascript' src="mottie/parser-date-range.js"></script>

  <script type="text/javascript" src="js/placeholders.js"></script>

</pre>


I also added the option globalize and .tablesorter.dates.months.it date. I wrote in my last comment 29 december, but I wanted to write it in Italian, so 29 DICEMBRE: in any case it does not filter.

in my table I have only one page, because, to simplify I wrote a few lines. if I add a hundred, you'll see that the filter is not working.

**Comment by gianluis** [comment]
i try to  include the widget-filter-type-insideRange.js and parser-date-range.js files in http://boardingpass.altervista.org/index1.html

but it doesnt work! :(

**Comment by Mottie** [comment]
I was going by http://boardingpass.altervista.org/index2.html... it has a few javascript errors on the page. Can you please update that demo to show how the filtering isn't working.

We could speed up interaction if you are willing to chat on the `#tablesorter` channel on freenode.net, or if you want to use gitter, just let me know.

**Comment by Mottie** [comment]
In fact, that page initializes tablesorter like 4 times... can you remove all that extra code? Including, this bit - it's not even valid javascript:

```js
	$(function(){	
	filter_placeholder : {
  search : '', // any default search inputs including the datepicker comparison
  from   : 'Date from...', // datepicker range "from" placeholder
  to     : 'Date to...'  // datepicker range "to" placeholder
}
```

**Comment by gianluis** [comment]
i create the room italy on gitter

**Comment by Mottie** [comment]
From when we last spoke, it sounds like everything is working now, so I'm going to close this issue.
