### ISSUE TITLE
fuzzy search with spaces

### ISSUE THREAD

**Issue by doArcanjo** [Mottie/tablesorter#1088]
Is possible to make a fuzzy search ( with item order, or better yet no order at all ) splitting the items by its spaces (without using any other operators )? 

e.g.:
row: " air momentum 1943"

writting:
 "i ent 43" would catch the row above

Thank you, for this awesome plugin

**Comment by Mottie** [comment]
Hi @doArcanjo!

The fuzzy search is set up to include spaces if you query includes them. In the [main filter demo](http://mottie.github.io/tablesorter/docs/example-widget-filter.html), I set it up so you can search for `~piano` to match `Philip Aaron Wong`.

In [this demo](http://jsfiddle.net/Mottie/856bzzeL/729/), the search is set up to include spaces `~pi an o` will still match the same name.

**Comment by doArcanjo** [comment]
Ok awesome!
Now is possible to have something like this (for a specific column class e.g.: '.oh_fuzzy_love'  ):
 - Without having the '~'     

...
sortLocaleCompare: true
widgetOptions: {
      filter_defaultFilter: {
          '.oh_fuzzy_love' : '~{q}',
       },
       filter_selectSourceSeparator : '  ',
}

"pi an o" -> (find)  "Philip Aaron Wong"

"hà o tie" -> "Thank you Mottie"

**Comment by doArcanjo** [comment]
Ping @Mottie 
Sorry for being rude...

But anyone have achieved the behaviour asked?

I have the behaviour on combos and don't having the same behaviour on table filters, for users who don't want to use '~' , is bad.

Thank you

**Comment by Mottie** [comment]
I'm confused, do you want the users to use `~` or have it set in the `filter_defaultFilter`?

Do you mean "the behaviour on combos" as in an external filter has that set as the default? If you add the same class name as set in the `filter_defaultFilter` to the header cell, it should use that default as well.

**Comment by doArcanjo** [comment]
Hi. Again, thanks for the reply.

I want this behaviour :
"pi an o" -> (find) "Philip Aaron Wong"
"hà o tie" -> "Thank you Mottie"

a) When a table's header (th) has the CSS class "fuzzy_search";
b) without the use of '~' ;
c) Using the target filter cell from the column (not an external filter).

It's exactly the behaviour you provided in example - but without the use of '~' in the start of String;

**Comment by Mottie** [comment]
Oh wow, it looks like I accidentally removed the code ([ref](https://github.com/Mottie/tablesorter/commit/f51b39388a38530753502d7c8a8dffb50418d093#diff-6d479c235668b57d3745338a0754ddf2L1100)) to use column specific `filter_defaultFilter` settings back in v2.24.4! I'll update the master branch with a fix shortly.

**Comment by doArcanjo** [comment]
Thank you.
Please update Bower package too.
