### ISSUE TITLE
Text sorting not working, arghh!

### ISSUE THREAD

**Issue by 1nickt** [Mottie/tablesorter#1093]
Hi, I feel like a dunce because I can't figure this out. I have tablesorter working just fine with one table. But with the others on the site, sorting by text generates a JS error:
```
Uncaught TypeError: Cannot read property 'replace' of undefined
  $.tablesorter.sortNatural @ jquery.tablesorter.js:1693
  $.tablesorter.sortNaturalAsc @ jquery.tablesorter.js:1718
  (anonymous function) @ jquery.tablesorter.js:1591
  $.tablesorter.multisort @ jquery.tablesorter.js:1552
  (anonymous function) @ jquery.tablesorter.js:1528
```
I've tried:
* Letting the plugin detect the content
* `headers: { 3: { sorter: "text" } }`
* `<th class="sorter-text">`

As I said, another table with the JS copied and pasted from this page, works fine. Also, other columns in this table sort fine, (numerical with auto-detection, and dates with `sorter-usLongDate`).

The  data:
```
                    <td class="nowrap expander">
                      {{myDetails.name}}
                    </td>
```
which renders:
```
<td class="nowrap expander ng-binding">
                      Habitat
                    </td>
```
and:
```
<td class="nowrap expander ng-binding">
                      Alliance Data
                    </td>
```
and lastly (only three rows for testing):
```
<td class="nowrap expander ng-binding">
                      foobar
                    </td>
```
Thank you so much for your help.

**Comment by Mottie** [comment]
Hi @1nickt!

Tthat looks like the natural sort parser is getting a numeric value passed to it instead of a string. I didn't add a method to prevent that error as that code is inside a sort function and called many times and more checks means slower sorting.

How are you initializing each table? If they are all initialized by one `$('table')` call, then do not use the `headers` option.

**Comment by 1nickt** [comment]
Hi and thanks for your reply.

I have only one table per page. I am loading the tablesorter JS in the `<body>` of the page (inside a `$(document).ready( function() {` ), because I am using a templating system and the  `<head>` is shared between pages.

The table that is working completely actually uses a unique `id`; the others use the same `id`:
```
<table id='table-sortable' class='tablesorter widget-zebra'>
```
and then in the script:
```
            $(document).ready( function() {
              $("#table-sortable").tablesorter({
```
 ... but again, one page at a time is loading with one table only.

But I don't understand how could a numeric value be getting passed to the parser, given the values I showed?

Does perhaps `<ng-repeat ...` continue to be executed after what jQuery thinks is `$(document).ready`? (The table working without problems is sent complete in the body; the others use `ng.repeat` ... )

But if that were it, why then does both digit sorting and usDateLong sorting work OK in these tables?

Thank you again.

**Comment by Mottie** [comment]
I haven't used angularjs before, but I think you'll need to use something other than a `$(document).ready` function to initialize tablesorter, or at least update it.

I have no idea which solution will work from [these Stackoverflow answers](http://stackoverflow.com/questions/15458609/execute-function-on-page-load)... hopefully one of them will fix this issue.

**Comment by 1nickt** [comment]
Hi again Rob,

tablesorter initializes fine as I have described.

The only issue is sorting by text parser on certain tables. I speculated that it might have to do with the fact that the table is drawn by JS in the browser via Angular's ng-repeat loop, but I can't see how because the other sort parsers work.

I'm afraid the link you posted is not relevant, sorry. Can I provide more info to diagnose why the sorting isn't working?

This is the line that is causing the error:
`1693:			bNum = b.replace( regex.chunk, '\\0$1\\0' ).replace( regex.chunks, '' ).split( '\\0' );`

using the Natural Sort on the values in my OP.

**Comment by Mottie** [comment]
I was thinking the problem might be that the contents of the table are changing, but tablesorter isn't being reinitialized, or updated since angularjs is not completely refreshing the page, just portions of it.

Yes, I know that the natural sort is causing the problem. As I stated before, the function is expecting a string, so it's trying to use replace on a numeric value and throwing a javascript error. I could fix it, but that is just one more check to go through for every sort value, making it slower. The error won't happen if the proper parsers are in place. Did you try using the `debug` option to see which parsers are being set?

Also, please post the tablesorter initialization code being used.

**Comment by 1nickt** [comment]
Hi again,

Don't know about the debug option, sorry. Will look at the doc site.

Entire init code:

```
            $(document).ready( function() {
              $("#table-sortable").tablesorter({
                theme: 'blue',
                // Add icon for various themes
                headerTemplate : '{content} {icon}',
                widgets: ['zebra', 'filter', 'stickyHeaders'],
                widgetOptions: {
                  // extra class name added to the sticky header row
                  stickyHeaders : '',
                  // number or jquery selector targeting the position:fixed element
                  stickyHeaders_offset : 0,
                  // added to table ID, if it exists
                  stickyHeaders_cloneId : '-sticky',
                  // trigger "resize" event on headers
                  stickyHeaders_addResizeEvent : true,
                  // if false and a caption exist, it won't be included in the sticky header
                  stickyHeaders_includeCaption : true,
                  // The zIndex of the stickyHeaders, allows the user to adjust this to their needs
                  stickyHeaders_zIndex : 2,
                  // jQuery selector or object to attach sticky header to
                  stickyHeaders_attachTo : $('.table-sortable'),
                  // jQuery selector or object to monitor horizontal scroll position (defaults: xScroll > attachTo > window)
                  stickyHeaders_xScroll : null,
                  // jQuery selector or object to monitor vertical scroll position (defaults: yScroll > attachTo > window)
                  stickyHeaders_yScroll : null,
                  // scroll table top into view after filtering
                  stickyHeaders_filteredToTop: true
                },
              });
```
and  `table` and `thead` tags:
```              
<table id="table-sortable" class="tablesorter widget-zebra">
                <thead>
                  <tr class="border">
                    <th class="nowrap">
                      Feed&nbsp;ID
                    </th>
                    <th class="nowrap sorter-usLongDate">
                      Created
                    </th>
                    <th class="nowrap">
                      Feed Name
                    </th>
                    <th class="nowrap filter-false sorter-usLongDate">
                      Last&nbsp;Process
                    </th>
                  </tr>
                </thead>
```
* column 0 is correctly sorting numbers (no parser specified)
* column 1 is correctly sorting dates like  'Tue Dec 01 2015' (parser : usDateLong)
* column 2 is failing on sorting text (no parser specified; error: "Uncaught TypeError: Cannot read property 'replace' of undefined")
* column 3 is correctly sorting dates like  'Wed, 25 Nov 2015 13:28:07 GMT' and '-' (parser : usDateLong)

Thanks!

**Comment by Mottie** [comment]
Odd, why does the debug count 14 columns? Are there extra rows added to the `thead` at some point?

Try adding "sorter-text" to column 2.

If you do have extra `thead` rows, add a ["tablesorter-ignoreRow" class](http://mottie.github.io/tablesorter/docs/#cssignorerow) to them.

**Comment by 1nickt** [comment]
SOLVED!

Hi Rob, thanks again.

All I needed was `class='tablesorter-childRow'` on my hidden row. Your last link to the docs led me there. I had tried reimplementing what I had completely according to the docs for child rows, but it turned out I could keep everything as is and just add that one class.

Thank you! Your work is very appreciated.
