### ISSUE TITLE
Scroller Widget doesn't reveal whole table

### ISSUE THREAD

**Issue by 1nickt** [Mottie/tablesorter#1094]
Hi Mottie,

Thanks again for your plugin, it's awesome.  Whenever I think I am done, I find another widget or function that I must have!

So, I've added the scroller widget with fixed columns. There are a couple of problems that I can't figure out:

1) The container containing the table extends past the right-hand edge of the browser window. In the demo, the table container ends before the edge of the browser window. This problem results in there being a horizontal scroll to the page as well as to the table contents, which is what I'm trying to avoid.

2) The table height is limited somehow, even though the container(s) it's in have height 100%. I would like the table to extend to the bottom of the browser window to use all available screen area to show data.

Image showing table not extending down, but overextending right:
<img width="400" alt="ts_scroller_1" src="https://cloud.githubusercontent.com/assets/12807261/11590913/c5b79cda-9a61-11e5-9652-0aae02970d80.png">

3) The table content scrolls horizontally, but not all the way: when I scroll all the way to the left, the rightmost cell is still clipped by the edge of the table.

Image showing page having scrolled left out of the browser window, while table contents have not scrolled all the way into view. this is with maximum scroll to left ... cannot view the final table cell completely unless I widen the window (and reload, see below):
<img width="400" alt="ts_scroller_2" src="https://cloud.githubusercontent.com/assets/12807261/11590981/4164094a-9a62-11e5-903c-a3803cb6a879.png">

4) As you can see the border between the fixed column and the others, does not extend to bottom of the table container (looks like it extends to bottom of last completely visible row upon init, but does not thereafter redraw).

[ 5) This one is definitely not tablesorter since it affects other divs within the same container, but maybe you have a suggestion for me? The width of the (div containing the) table  shrinks each time I resize the browser window; whether I increase or decrease the browser window width the (div containing the) table shrinks, again and again. ]

Thanks Mottie!

**Comment by Mottie** [comment]
Hi @1nickt!

The scroller widget is my least favorite widget. It does a lot of DOM manipulation to wrap the table, add duplicate tables & make all the cells line up. This makes the widget very inefficient and is really slow on large tables.

I really wouldn't recommend using it if you only wanted to freeze a column.

Complaining aside. It sounds like the build-in box-sizing might be overridden in your example. The table and all components inside the scroller have the following css applied:

```css
.tablesorter-scroller * { box-sizing: border-box; }
```

If this gets changed by other css, it make really mess up alignment. So double check to make sure this isn't happening.

If that doesn't appear to be the issue, please modify [this demo](http://jsfiddle.net/Mottie/mqv16pd4/) to duplicate the problem to help me better troubleshoot this issue.

**Comment by 1nickt** [comment]
Hi Mottie,
Thanks for your prompt reply as ever.

What would you recommend instead? It is important to freeze a column or two on the left because there are many columns in the row and the users lose track of which record they're looking at.

I've also noticed that the vertical scrolling with Scroller is much smoother than with StickyHeaders, so I was liking that.

I took the advice I spotted elsewhere in these pages and set in my css:
```
html {
  height: 100%;
  box-sizing: border-box;
}
*, *:before, *:after {
  box-sizing: inherit;
}
```
And as far as I can see all elements have `{ box-sizing: border-box; }`.
I'll try to modify the demo, in the meantime if there's a better alternative I would love to hear your opinion.
Thanks!

**Comment by Mottie** [comment]
[Demo](http://jsfiddle.net/Mottie/mqv16pd4/32/)

* When you wrap the table, use a margin instead of a padding to add space: `<div style="display: block; margin: 8px">`
* Did you try setting the `scroll_height` to some arbitrary height like `scroller_height: 1500`?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
