### ISSUE TITLE
print table blank in google chrome

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1095]
When using print_table() in chrome the pages are blank. The correct number of pages and also the title is there but no data.

It works on firefox and safari

**Comment by Mottie** [comment]
Hi @southmeadows!

Are you using the latest version? Does [this print widget demo](http://mottie.github.io/tablesorter/docs/example-widget-print.html) work for you?

**Comment by southmeadows** [comment]
Below are the versions I have installed. All browsers seem to work fine except Chrome. 

/*! TableSorter (FORK) v2.24.6 *//*
/* Widget: print - updated 2/7/2015 (v2.19.0) *//*
 * jQuery JavaScript Library v1.11.3

**Comment by Mottie** [comment]
Chrome works for me in the print widget demo, is it not working for you? Do you have any extensions installed that might interfere?

**Comment by southmeadows** [comment]
The demo works for me too. There must be something I have wrong, but no idea what to check as it works everywhere else. I disabled all of the extensions but that didnt help.

**Comment by southmeadows** [comment]
I removed Chrome, rebooted and reinstalled. All appears to be good now. Sorry for the hassle. Appreciated the ideas!
