### ISSUE TITLE
TypeError tscss is undefined

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#1096]
Just downloaded the latest build and tried to update an older instance.   I get:

TypeError tscss is undefined, reported in:

/tablesorter/widgets/widget-scroller.js, line 105

**Comment by SPlatten** [comment]
Fixed by inserting:

        if ( tscss == undefined ) {
            tscss = ts.css = {};
        }

to line 41 before:

        $.extend( ts.css, {

**Comment by Mottie** [comment]
`ts.css` or `$.tablesorter.css` should not be undefined unless the `widget-scroller.js` file is loaded before `jquery.tablesorter.js`, which it shouldn't be since it is dependent on the core.

**Comment by SPlatten** [comment]
This is the order in which my scrips were installed to replicate the problem:

<script type="text/javascript" src="/scripts/modernizr.js"></script>
<script type="text/javascript" src="/scripts/jquery/jquery-2.1.4.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/jquery-ui.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/jquery.tablesorter.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/jquery.tablesorter.pager.js"></script>
<script type="text/javascript" src="/scripts/jquery/tablesorter/widgets/widget-scroller.js"></script>
<script type="text/javascript" src="/scripts/jquery/dateentry/jquery.plugin.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/dateentry/jquery.datetimeentry.min.js"></script>
<script type="text/javascript" src="/scripts/jquery/inputmask-3.x/js/jquery.inputmask.js"/></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxcore.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxscrollbar.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxlistbox.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxcombobox.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxpasswordinput.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxbuttons.js"></script>
<script type="text/javascript" src="/scripts/jquery/jqwidgets/jqxmenu.js"></script>
<script type="text/javascript" src="/socket.io/socket.io.js"></script>

**Comment by Mottie** [comment]
The original version of tablesorter is not compatible with jQuery v2.1.4. The scroller widget will not work with the original tablesorter nor is it compatible with the original pager. Please update the core and pager from this fork.
