### ISSUE TITLE
Text-extraction with math-widget

### ISSUE THREAD

**Issue by doArcanjo** [Mottie/tablesorter#1098]
Hi!

I would like to retrieve the value from an input (inside the cell) and use the value in math widget.

To filter this column we use `.group-input`, to return it's value: 
```javascript
textExtraction: {
            '.group-input': function(o) {
                return $(o).find("input").val();
            }
        },
```

The value returned from a custom equation

`$.tablesorter.equations['weight_input'] = function(arry) { console.log(ary)}`
is `[0,0,0]` when there are 3 cells at the target column;

Thank you

**Comment by Mottie** [comment]
Hi @doArcanjo!

Yes, it looks like I haven't updated the internal math code to use the `textExtraction` function. I'll get that fixed in the master branch momentarily.

**Comment by doArcanjo** [comment]
Yes it does!
Thank you.

When do you preview a new release bower/npm version?

**Comment by Mottie** [comment]
I'm thinking this weekend

**Comment by doArcanjo** [comment]
Excellent!
