### ISSUE TITLE
Content Editable: when updated the cell and focus out getting error Uncaught TypeError: Cannot read property '0' of undefined

### ISSUE THREAD

**Issue by kthanesh** [Mottie/tablesorter#1099]
HI

I have  a tablesorter table with contenteditable widget. If the table is editable i will send the editable_columns:[7,8] which need to be edit, if it is not it will set an empty array of columns  editable_columns:[] User may switch from editable to not editable. During this switch I am destroying the table and recreating it.

When i am switching from non editable table to editable table, and when i try to edit and focus out of the cell after editing i am getting the following error 
Uncaught TypeError: Cannot read property '0' of undefined

When debugged i found out that editable widget is calling the $.tablesorter.updateCell method which is passing a "c" object in which the cache key is missing. It is the same function called when i press enter on the cell after editing in which i don't have any issue as the "C" object has the cache key.

Please suggest what i am doing wrong or what i am missing

Thanks

Thanesh

**Comment by Mottie** [comment]
Hi @kthanesh!

Would you please report the line number of that error.

Instead of completely destroying the table, remove the editable widget:

```js
$.tablesorter.removeWidget( $( 'table' ), 'editable' );
```

I found an issue when trying to re-apply the editable widget to the table when so desired, but I just pushed a fix to the master branch (https://github.com/Mottie/tablesorter/commit/fdd82f847e117c3f7197192974af1063a08711ec).

So now you can add the editable widget back like this:

```js
$( 'table' ).trigger( 'applyWidgetId', 'editable' );
```

**Comment by kthanesh** [comment]
Hi Mottie,

Thanks for a prompt response. Will try the above solution.
In widget-editable.js below is the line which is called when focus out, keydown ....

$.tablesorter.updateCell( c, $this.closest( 'td' ), false, function() {

in tablesorter.js,  updateCell function below is the line 

tbcache = c.cache[ tbodyIndex ] 

Thanks

Thanesh

**Comment by Mottie** [comment]
Hmm, I see... the `c.cache` would only be undefined if the table were destroyed. I'll add something to prevent that javascript error, but I would still recommend not destroying tablesorter.

**Comment by kthanesh** [comment]
hmm now i got little confused. Even after destroying and reapplying the table sorter if i edit the cell and press enter it is working fine. I see this issue only on focus out. But as per your comment it should happen on both the events, but it is not that way in my case.

**Comment by kthanesh** [comment]
This fix resolved the issue. thank you
