### ISSUE TITLE
Data replicated when header clicked

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#1100]
I have 3 data rows in a table with sortable headers, when I click on any sortable header the data is replicated, this only occurs once, however I end up with twice the data in they table.

I've tried to replicate this in a JsFiddle, but I'm not sure how to get the full functionality in jsFiddle, for example it isn't showing the images.

http://jsfiddle.net/SimonPlatten/x6gv9xfa/1/

I downloaded the latest tablesorter scripts yesterday.

**Comment by Mottie** [comment]
Hi @SPlatten!

That demo includes tablesorter v2.0.5 along with the original pager. The scroller widget will not work with the original tablesorter. You will need to download tablesorter and the pager from this fork to get the scroller widget to work.

I think this might also solve issue #1096.

**Comment by SPlatten** [comment]
Just downloaded the very latest zip using the link on this site.  I deleted the original folder completely, then unzipped the contents of the download.  The problem is still present.

**Comment by SPlatten** [comment]
Just downloaded the very latest zip using the link on this site. I deleted the original folder completely, then unzipped the contents of the download. The problem is still present.

**Comment by Mottie** [comment]
Please look at [this demo](http://jsfiddle.net/Mottie/mqv16pd4/25/). Look at the "External Resources" section on the left.

**Comment by SPlatten** [comment]
Thank you, I will take a look, can you tell me what the combined.js includes as it isn't used in that demo?

**Comment by Mottie** [comment]
The combined file is `jquery.tablesorter.js` + `jquery.tablesorter.widget.js`:

If you look at [lines 7-8](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.combined.js#L7-L8) of the file you'll see this:

```js
/*! tablesorter (FORK) - updated 12-02-2015 (v2.24.6)*/
/* Includes widgets ( storage,uitheme,columns,filter,stickyHeaders,resizable,saveSort ) */
```

**Comment by SPlatten** [comment]
Thank you.

**Comment by SPlatten** [comment]
I have just implemented the code from your example and it produced the same results....until I added in the 'scroller' widget and the widgetOptions parameters, without this I get the same records repeated in the table, not a problem as I will use it how it is not with the scroller and widgetOptions.  Thank you.
