### ISSUE TITLE
Filter widget - strange behavior in combination with Meteor.

### ISSUE THREAD

**Issue by zorro765** [Mottie/tablesorter#1101]
Hello there!

I noticed that search strings containing " and " or " or " are not working properly in combination with Meteor.

Let's say a cell contains "Romeo and Julia":
Filter: "Romeo" is working
Filter: "Romeo and" is working
Filter: "Romeo and " is not working
Filter: "Romeo and Julia" is not working

Let's say a cell contains "Romeo or Julia":
Filter: "Romeo" is working
Filter: "Romeo or" is working
Filter: "Romeo or " is not working
Filter: "Romeo or Julia" is not working

Let's say a cell contains "Romeo 123 Julia":
Filter: "Romeo" is working
Filter: "Romeo 123" is working
Filter: "Romeo 123 " is working
Filter: "Romeo 123 Julia" is working

Demo application: http://tablesorter_issue.meteor.com/
The app is using the latest jquery.tablesorter.min.js and widget-filter.min.js.
$(".tablesorter").tablesorter({ theme: 'ice', widgets: ["filter"]})

I can't figure out why it behaves like this, do you have any ideas?

**Comment by Mottie** [comment]
Hi @zorro765!

This was just discussed in issue [#1089](https://github.com/Mottie/tablesorter/issues/1089#issuecomment-164092255) about 24 hours ago.

Basically, " and " and " or " ( both surrounded by spaces) are filter type key words which allow the user to query multiple words or filter types - e.g. "1 and 2", "1 or 2", ">10 and <100", etc.

These key words can be changed by [modifying the language](http://mottie.github.io/tablesorter/docs/example-widget-filter.html#localization).

```js
// change "and" & "or" filter key words to something else
$.tablesorter.language.and = "&&";
// these values are used inside of a new RegExp() so any special characters
// will need to be escaped
$.tablesorter.language.or = "\\|\\|";
```

**Comment by zorro765** [comment]
Oh! Unfortunately I didn't find it. Thank you very much!
