### ISSUE TITLE
Math widget format mask for each total

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#1103]
Thanks for all the great work on the math widget. Would it be possible to enhance the format mask feature to allow different masks to be applied to each column, perhaps by setting an option array like for `sortList`?

**Comment by Mottie** [comment]
Hi @lindonb!

Each cell can have a unique [`data-math-mask` attribute](http://mottie.github.io/tablesorter/docs/example-widget-math.html#math_mask) that overrides the `math_mask` widget option.

That will work for you, or am I misunderstanding this request?

**Comment by lindonb** [comment]
Yes, that sounds perfect. Similar to the way the `data-math-filter` attribute in a total cell can be used to override the `math_rowFilter` setting.
