### ISSUE TITLE
Header issue

### ISSUE THREAD

**Issue by RodrigoDiazDuran** [Mottie/tablesorter#1105]
Hello, i have this issue with the header i can´t fix it, i have tried so many css and style, and i do nothing.(sorry for my english).
![image](https://cloud.githubusercontent.com/assets/16299944/11802544/96730460-a2d0-11e5-9874-840637814fe9.png)
this is when i sort the table, while im in this current position., when you move scroller to right, and sort a column

**Comment by Mottie** [comment]
Hi @RodrigoDiazDuran!

Can you please provide the tablesorter initialization code.

**Comment by RodrigoDiazDuran** [comment]
sorry Mottie i´ve discover the solution after several hours, this was assign min-with to header, thanks for your response. regards
