### ISSUE TITLE
Consider deploying as webjar?

### ISSUE THREAD

**Issue by DwayneSmurdon** [Mottie/tablesorter#1108]
Hello,

Have you considered deploying as a webjar as well?  I use the Play framework and this would be great.  The old tablesorter is there, but I'd prefer your forked version.

I am not sure the effort to package/deploy in this fashion, but if you need any help I'll do my best. 

-Dwayne

**Comment by Mottie** [comment]
Hi @DwayneSmurdon!

It looks like someone already created it: https://github.com/webjars/tablesorter

**Comment by DwayneSmurdon** [comment]
Hey Mottie,

Yeah, isn't that the old version you originally forked from?  That's not your current version there, is it?

-Dwayne

**Comment by Mottie** [comment]
The original version is still sitting at v2.0.5 and it looks like it is also there: https://github.com/webjars/jquery-tablesorter

I did [leave a message](https://github.com/webjars/webjars/issues/307#issuecomment-166036130) asking how I can maintain the `pom.xml` in my repo, so we'll have to wait and see.

**Comment by DwayneSmurdon** [comment]
Ahh, I looked right over the pom.xml and it's date.  I saw the other dates as over 2 years ago.  Ok, this is great that it's already up there.  

Perhaps you could just be a contributor on their project.  Then you'd just update pom.xml as needed and submit pull requests.  I don't love having that extra step waiting for them to pull your changes, but it might work out just fine. :)

Thanks for looking into this.  I've enjoyed using tablesorter so far and I'm learning more about it daily.

-Dwayne

**Comment by Mottie** [comment]
See https://github.com/Mottie/tablesorter/pull/1239#issuecomment-235050280.
