### ISSUE TITLE
Wrong above-sum for irregular table

### ISSUE THREAD

**Issue by clod986** [Mottie/tablesorter#1110]
Hi @Mottie ,
lately I'm using your awesome plugin and I keep seeing weird stuff happening in the most random scenarios.

Today I found that above-sum doesn't work properly for this table:
![total_wrong](https://cloud.githubusercontent.com/assets/5764857/11987554/b0684b88-a9e1-11e5-9e61-e487d176814f.PNG)

But if I remove the rowspan from the first cells making the same table regular, the result becomes correct:
![total_correct](https://cloud.githubusercontent.com/assets/5764857/11987558/c8b6a27a-a9e1-11e5-912b-092e83072d42.PNG)

I've chosen to stick to the regular tables, so there's no rush AT ALL, but I just wanted to point this out. My guess is that with above-sum the plugin counts all the `<td>`s with same index in precedent `<tr>`s. If this it the case, I have no idea on how this could be fixed...

I'm not good with forking and helping develop on github, but one day I'll try to be a better help to your project; for the moment take me as a picky tester ;)

**Comment by Mottie** [comment]
Hi @clod986!

It's because you're using `rowspan`s in the `tbody`. `rowspan`s are not currently supported by tablesorter nor the math widget.

**Comment by clod986** [comment]
Thanks for the reply, I didn't know about it but I understand why it is this way...

Merry Christmas @Mottie ;)
