### ISSUE TITLE
Filter widget external inputs event

### ISSUE THREAD

**Issue by zzborn1022** [Mottie/tablesorter#1111]
I have bind filterEnd on two input, and I'd like to know which input triggered the event and the input value in the callback function in filterEnd, thx!

**Comment by Mottie** [comment]
Hi @zzborn1022!

The `filterEnd` event is triggered on the table itself. So if you want to target an input, I would use a delegated bind; something like this:

```js
$('table').on('change', '.tablesorter-filter', function(){
  var $this = $(this),
    val = $this.val();
  // do something with$this & val...
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
