### ISSUE TITLE
can Output Button inside the tablesorter <thead> ?

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1114]
Hi Mottie,

My tablesorter coding below but the "ExportBtn" doesn't if it inside the <thead>, many thanks.

    <table id="RelatedCars">
    <thead>
    <tr>
      <th class="filter-false" data-sorter="false" colspan="3">Title
						<input type="button" class="ExportBtn" value="Export" /></th>
    </tr>
    <tr>
      <th>Col-1</th>
      <th>Col-2</th>
      <th>Col-3</th>
    </tr>
    </thead>
....

Many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

Use the class name set by the [`cssIgnoreRow` option](http://mottie.github.io/tablesorter/docs/#cssignorerow) in the `tr`, like this:

```html
<table id="RelatedCars">
<thead>
<tr class="tablesorter-ignoreRow">
  <thcolspan="3">Title
    <input type="button" class="ExportBtn" value="Export" />
  </th>
</tr>
<tr>
  <th>Col-1</th>
  <th>Col-2</th>
  <th>Col-3</th>
</tr>
</thead>
```

**Comment by airthomas** [comment]
Great, it's work. Thanks so much Mottie.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
