### ISSUE TITLE
Help please...

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#1115]
I'm obviously doing something wrong.  What I want is a table with 4 fixed columns and 7 additional columns that scroll horizontally.

The headers for the fixed columns are:
Activitiy, Project, Task and Rate

The other column headers are:
Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday.

I want a footer with has 8 columns, the first spans the fixed columns with the text: Total Hours, then the remaining 7 columns will show the totals for each day.

As far as I can see the HTML for the table is correct:

    <form class="pager">
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/first.png" width="16" height="16" alt="First" class="first"/>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/prev.png" width="16" height="16" alt="Previous" class="prev"/>
      <span class="pagedisplay">
      </span>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/next.png" width="16" height="16" alt="Next" class="next"/>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/next.png" width="16" height="16" alt="Last" class="last"/>
      <select class="pagesize">
        <option value="10">10
        </option>
        <option value="20">20
        </option>
        <option value="30">30
        </option>
        <option value="40">40
        </option>
        <option value="all">All Rows
        </option>
      </select>
    </form>
    <table id="tblactivity" class="tablesorter">
      <thead>
        <tr>
          <th>Activity
          </th>
          <th>Project
          </th>
          <th>Task
          </th>
          <th style="white-space: nowrap;">Rate £
          </th>
          <th>Sunday
          </th>
          <th>Monday
          </th>
          <th>Tuesday
          </th>
          <th>Wednesday
          </th>
          <th>Thursday
          </th>
          <th>Friday
          </th>
          <th>Saturday
          </th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td align="left">BLAH!!!</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">DO</td>
          <td align="right">35.00</td>
          <td align="right">16:29 for<br />1 hr 30 mins</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">Testing 123.</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">HWENG</td>
          <td align="right">42.00</td>
          <td align="right">19:31 for<br />4 hrs 50 mins</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">asjkdsaljda</td>
          <td align="left">Waiting Time</td>
          <td align="center"></td>
          <td align="right"></td>
          <td align="right">19:32 for<br />1 hr </td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">asdasda</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">SWENG</td>
          <td align="right">32.00</td>
          <td align="right">19:34 for<br />2 hrs 50 mins</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">ssssssssssss</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">DO</td>
          <td align="right">35.00</td>
          <td align="right">19:38 for<br />3 hrs </td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">Software development</td>
          <td align="left">Timekeeper</td>
          <td align="center">SWENG</td>
          <td align="right">40.00</td>
          <td align="right"></td>
          <td align="right">08:00 for<br />8 hrs </td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">Time keeper</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">SWENG</td>
          <td align="right">32.00</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right">09:50 for<br />2 hrs </td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
        <tr>
          <td align="left">Timekeeper</td>
          <td align="left">Productive Non Contract</td>
          <td align="center">SWENG</td>
          <td align="right">32.00</td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right">12:28 for<br />1 hr </td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
          <td align="right"></td>
        </tr>
      </tbody>
      <tfoot>
        <tr>
          <th colspan="4" style="text-align:right">Total Hours
          </th>
          <th id="sdt0" style="text-align:right">13:10
          </th>
          <th id="sdt1" style="text-align:right">8:00
          </th>
          <th id="sdt2" style="text-align:right">3:00
          </th>
          <th id="sdt3" style="text-align:right">
          </th>
          <th id="sdt4" style="text-align:right">
          </th>
          <th id="sdt5" style="text-align:right">
          </th>
          <th id="sdt6" style="text-align:right">
          </th>
        </tr>
      </tfoot>
    </table>
    <form class="pager">
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/first.png" width="16" height="16" alt="First" class="first"/>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/prev.png" width="16" height="16" alt="Previous" class="prev"/>
      <span class="pagedisplay">
      </span>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/next.png" width="16" height="16" alt="Next" class="next"/>
      <img src="/scripts/jquery/tablesorter/addons/pager/icons/next.png" width="16" height="16" alt="Last" class="last"/>
      <select class="pagesize">
        <option value="10">10
        </option>
        <option value="20">20
        </option>
        <option value="30">30
        </option>
        <option value="40">40
        </option>
        <option value="all">All Rows
        </option>
      </select>
    </form>

The initialisation code I have is:

              $('#tblactivity').tablesorter({theme:'blue'
                                          ,widgets:['zebra'
                                                   ,'filter' // <--Removing this resolves issues 1-4 below, but splits the fixed and scrollable columns ?
                                                   ,'scroller']
                                    ,widgetOptions:{scroller_height:400
                                             ,scroller_fixedColumns:4
                                             ,scroller_rowHighlight:'hover'}})
                           .tablesorterPager({container:$('.pager')
                           ,output: '{startRow:input} to {endRow} ({totalRows})'
                           ,updateArrows:true
                           ,page:0
                           ,size:10
                           ,savePages:true
                           ,storageKey:'tablesorter-pager'
                           ,fixedHeight:true
                           ,removeRows:false});                    

I have numerous issues:
1) The fixed columns don'work
2) The footer doesn't line up with the fixed columns.
3) When I click on a column header it adds another header row.
4) The pager 'output' isn't changed as I've requested and shows just the images and the select list.

As far as I am aware I have the kept up to date with the tablesorter scripts and styles.

I have:
modernizr.js, version 2.0.6
jquery-2.1.4.min.js, version v2.1.4
jquery-ui.min.js, version 1.11.4 - 2015-03-11
jquery.tablesorter.pager.css and jquery.tablesorter.pager.js updated 11/22/2015 (v2.24.6)
jquery.tablesorter.js (FORK) v2.24.6
jquery.tablesorter.widgets.js updated 12-02-2015 (v2.24.6)
widget-scroller.js updated 10/31/2015 (v2.24.0)

Sorry, its been a few years since I've worked with this.

**Comment by SPlatten** [comment]
Update....removing 'filter' from the widgets array stops issue no. 3) but introduces another problem were there is now a gap between gap between the fixed columns and the scrollable columns.

**Comment by SPlatten** [comment]
Another issue (5) that I've just noticed is that the footers on the scrollable columns are not showing the contents at all.

**Comment by SPlatten** [comment]
Here is a fiddle which I've tried to reproduce as accurately as possible, hence the additional CSS and Scripts. https://jsfiddle.net/SimonPlatten/d5wuees5/

**Comment by Mottie** [comment]
Hi @SPlatten!

1) Fixed columns do work if you include a `<tr>` in the `tbody`... all I see in the HTML provided are 11 cells (no row definition)
2) Fixed columns in the scroller + colspans do not work. Please see [issue #929](https://github.com/Mottie/tablesorter/issues/929#issuecomment-108106196)
3) I am not seeing a new row added in [this demo](http://jsfiddle.net/Mottie/mqv16pd4/37/).
4) The `<form>` needs a class of `"pager"` added: `<form class="pager">`.
5) Please see number 2.

**Comment by Mottie** [comment]
The demo you just linked included rendered HTML... please provide unrendered HTML.

**Comment by SPlatten** [comment]
Sorry, try this http://jsfiddle.net/SimonPlatten/d5wuees5/3/

**Comment by Mottie** [comment]
Ok... remove the `<center>` wrapper... it's causing all the problems - http://jsfiddle.net/Mottie/mqv16pd4/38/

**Comment by SPlatten** [comment]
Thank you, will take a look.

**Comment by SPlatten** [comment]
Almost there, removing the <center> has removed the gap, I'm still not seeing the content of the footers...on looking with firebug, the elements are all grayed.

**Comment by SPlatten** [comment]
Any ideas why the scrollable footers are not being display?

**Comment by SPlatten** [comment]
Also, can you tell me why the example in jsfiddle with filter present works and mine with it results in additional header rows created with every click ?

**Comment by SPlatten** [comment]
It looks like the footer is actually scrolled left by a couple of columns which would explain why the 3 columns that have content are not visible, question is why is the footer scrolled when the body and header aren't?

**Comment by SPlatten** [comment]
Sorry, missed the comment regarding colspan's...it works now.

**Comment by Mottie** [comment]
That's good to hear. Can I close this issue then?

**Comment by SPlatten** [comment]
Yes, thanks again.
