### ISSUE TITLE
Exclude values in the select filter based on the other filter

### ISSUE THREAD

**Issue by buddalasunil999** [Mottie/tablesorter#1118]
Hi,

I have setup my table with select filters and it works fine. What I am looking for is, when I filter on one column then show only the available options in the other select filters instead of showing everything. Any idea how to implement this?

Thanks in advance for your help.

**Comment by Mottie** [comment]
Hi @buddalasunil999!

Add a [`filter-onlyAvail` class name](http://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes) on the header. See the "discount" column in [this demo](http://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html).

**Comment by buddalasunil999** [comment]
At first I looked at and it didn't work. Now I tried again and it works amazing. Thank you so much :-)
