### ISSUE TITLE
pager issue

### ISSUE THREAD

**Issue by kenbenoit** [Mottie/tablesorter#1122]
I am currently using tablesorter 2.25 with the pager widget 2.24.6 in an .NET MVC application. If I do not return any data to my table from my default controller action to my view I cannot get any subsequent ajax call to request any data, this includes binding to an empty data model as well.  My secnario is I always want my data to be gotten via my ajax method/url. However if I do bind to a valid set of data upon initially serving the view then a second un-necessary subsequent 2nd call to the ajax method will also be made. How can I get the ajax call to fire without having to bind to initial data?

**Comment by Mottie** [comment]
Hi @kenbenoit!

Sorry for not responding earlier. Would you provide your initialization code, and associated HTML? Thanks!

**Comment by Mottie** [comment]
Please provide more details, or I don't know how to help you.

Are you using the built-in pager ajax functionality? See [this working demo](http://mottie.github.io/tablesorter/docs/example-pager-ajax.html) or the [pager documentation](http://mottie.github.io/tablesorter/docs/#pager) for more details.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
