### ISSUE TITLE
Only sort certain columns

### ISSUE THREAD

**Issue by JordanSayner** [Mottie/tablesorter#1123]
I have a checkbox in my first column, but I'm not sure how to make it so that column isn't sortable. I also have another column that I would prefer not to be sortable.

Am I being silly, but I cant see anything in the docs that suggests this is possible.

**Comment by Mottie** [comment]
Hi @JordanSayner!

Please check out [this demo](http://mottie.github.io/tablesorter/docs/example-options-headers.html) on how to disable a column.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
