### ISSUE TITLE
Display "No Records" when tbody is empty

### ISSUE THREAD

**Issue by Boduje** [Mottie/tablesorter#1124]
When filtering a table, I want to show a table row with "No Records" or "No Matches" instead of nothing if there are no matches.  Is this easy to accomplish?  If so, where in the tablesorter js file would that functionality go?

Thanks!

**Comment by Mottie** [comment]
Hi @Boduje!

One of the filter widget demos on the [Home wiki page](https://github.com/Mottie/tablesorter/wiki#widgets) addresses this problem.

  * [No filter result message](http://jsfiddle.net/Mottie/4mVfu/2377/) (with pager) - see [Stackoverflow](http://stackoverflow.com/questions/23129215/tablefilter-plugin-with-null-data).
  * [No filter result message](http://jsfiddle.net/Mottie/4mVfu/5603/) (without pager) - see [Stackoverflow](http://stackoverflow.com/q/34505689/145346).

**Comment by Boduje** [comment]
Heck yeah!  That is exactly what I was looking for.  Thanks for this great plugin!
