### ISSUE TITLE
Value changing on checkboxes in Chrome

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1125]
Hi, Mottie - me again!

I have this strange problem that only occurs in Chrome. It seems that whenever one of the checkboxes (I only have one, per row) is checked, the value of the checkbox changes from the original one (the intended value which should remain) to "true" instead.

Unchecked (original) code:
    `<input type="checkbox" name="selected_reminder_uid" class="reasign" value="5310" unchecked>`

After checking the box:
    `<input type="checkbox" name="selected_reminder_uid" class="reasign" value="true" checked>`

Obviously, I need the value in the second line to remain "5310" instead of "true". Do you know why this is happening? When I render my pages without the tablesorter plugin, this behavior does not occur, even in Chrome (so there is something happening with TS that is doing this.)

**Comment by Mottie** [comment]
Hi @aetna-wsa!

I think different browsers treat the value of a check box input different. I would not use `value`, instead use `data-value` or another attribute.

**Comment by aetna-wsa** [comment]
Thanks, Rob. I thought about that. However, on the same page that uses the `value` attribute it is correctly leaving the value unchanged when checking the checkbox. The difference between these pages are just the use of the TS plugin and using the parser-input-select.js file. Any reason why TS would cause this to be an issue while the page without it works fine?

**Comment by JamoCA** [comment]
I've had an app that has worked for a year or more... updating the latest version of "parser-input-select.js" rewrites the submitted value to "true" instead of the unique IDs that are configured in the form.  The latest versions of Firefox Dev & Microsoft Edge don't rewrite the values to "true".  If I remove the input-select plugin, the form fields are correctly submitted.

**Comment by Mottie** [comment]
Hmm, ok I'll take a look at the code again.

**Comment by Mottie** [comment]
Ok, the parser is fixed in the master branch. Sorry about that!

**Comment by aetna-wsa** [comment]
Oh man, if this works you'll be on my Christmas list for 10 years!

**Comment by Mottie** [comment]
LOL, send me lots of virtual chocolate-chip cookies :wink:

**Comment by JamoCA** [comment]
Thanks!  I've just confirmed that the input parser update works and doesn't rewrite the checked checkbox values to "true".

**Comment by aetna-wsa** [comment]
Confirmed here, too... thanks Rob!

**Comment by aetna-wsa** [comment]
Both of those parsers are failing.

**Comment by Mottie** [comment]
> Both of those parsers are failing.

Both? That file has six parsers:

* `inputs`
* `inputs-numeric`
* `checkbox`
* `select`
* `select-text`
* `textarea`

I know the one you're having issues with is the `checkbox` parser, what other parser is failing?
