### ISSUE TITLE
Table with column Time format and time range

### ISSUE THREAD

**Issue by yogini16** [Mottie/tablesorter#1127]
I'm using jQuery.tablesorter.js. I'm trying to sort data with time format and time range data. It gives incorrect result

Exmaple 
Time before sorting
![image](https://cloud.githubusercontent.com/assets/16700243/12320089/6b7df90c-ba5b-11e5-88b6-0b8a75431d77.png)

after sorting ( issue for both Ascending and descending ) 
![image](https://cloud.githubusercontent.com/assets/16700243/12320197/2d071216-ba5c-11e5-9c40-30d45213a30f.png)

time Frame before sorting 
![image](https://cloud.githubusercontent.com/assets/16700243/12320074/541b9436-ba5b-11e5-8422-9427a5fd6778.png)

after sorting ( issue for both Ascending and descending ) 

![image](https://cloud.githubusercontent.com/assets/16700243/12320320/d65645e4-ba5c-11e5-8b0e-6e4ba59b61ff.png)

**Comment by Mottie** [comment]
Hi @yogini16!

I created [this demo](http://jsfiddle.net/Mottie/856bzzeL/801/) and the time column sorts as expected.

The range column data was modified so that the start time includes the time of day ("AM" or "PM"), and requires the following code & parser to work:

```js
$(function() {
  $.tablesorter.addParser({
    id: 'time-range',
    is: function(str) {
      return false;
    },
    format: function(str, table) {
      // isolate time... ignore month, day and year
      var temp, s, e,
        times = [],
        timeParts = (str || '').match(/([1-9]|1[0-2]):([0-5]\d)(\s[AP]M)|((?:[01]\d|[2][0-4]):[0-5]\d)/gi);
      if (timeParts && timeParts.length === 2) {
        s = new Date('2000/01/01 ' + (timeParts[0] || ''));
        e = new Date('2000/01/01 ' + (timeParts[1] || ''));
      }
      times[0] = s instanceof Date && isFinite(s) ? s.getTime() : '';
      times[1] = e instanceof Date && isFinite(e) ? e.getTime() : '';
      return times.join(' - ');
    },
    type: 'text'
  });

  $('table').tablesorter({
    // debug:true,
    theme: 'blue',
    widgets: ['zebra']
  });
});
```

Also, please note the class name in the header:

```html
<th class="sorter-time-range">Time Frame</th>
```

**Comment by yogini16** [comment]
Hi Mottie,

Thanks a lot for the response.
I tried using  this parser. But It doesn't works. I'm using my own css this might be the reason.
Please suggest the solution independent of css.

**Comment by Mottie** [comment]
I didn't use any css... the "sorter-time-range" was added to set the parser for that column. If you don't want to use a class name, do this instead:

```html
<th data-sorter="time-range">Time Frame</th>
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by yogini16** [comment]
Hi,
As per priorities in the project task. this issue has been kept aside for
some time.
will be working on it afterwords. thanks a lot for the help.

On Mon, Feb 15, 2016 at 12:12 PM, Rob G <notifications@github.com> wrote:

> I'm guessing this issue has been resolved, so I'm going to close it. If
> you continue to have problems, please feel free to continue the discussion
> in this thread.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/1127#issuecomment-184368990>
> .
>



-- 
Regards,
Yogini Pawar
