### ISSUE TITLE
Alphanumeric sort ....weird results

### ISSUE THREAD

**Issue by 06tech** [Mottie/tablesorter#1128]
I have a column in a table that contains product model numbers which can be numbers, alphabetic or special characters or a mixture of both and sorting doesn't seem to work correctly - I tried using the string related modfiers specified here -> https://mottie.github.io/tablesorter/docs/example-options-headers-digits-strings.html but nothing seemed to fix the issue ..

A demo of the problem is here http://www.06tech.com/sorttest.html and the problem column is the 'Model' column - clicking on the header twice you will see row 9 has the model number 'B90' and row 10 is 'A76' ... 

What am I missing here?
Thanks in advance for any advice!

Rich

**Comment by Mottie** [comment]
Hi Rich!

The problem is because tablesorter attempts to auto-detect the type of data contained in each column. In the "Model" column, the first thing it finds is "41593", so it sets the parser to "numeric".

To override the auto-detection of the parser, add a class name to the header:

```html
<th class="sorter-text" width="5%">Model</th>
```

Then the sort is set as "text" and performs an alpha-numeric sort - [demo](http://jsfiddle.net/Mottie/856bzzeL/824/).

**Comment by 06tech** [comment]
Thanks Mottie for the quick response and solution to the issue.

Rich

**Comment by Murmur** [comment]
Do `class="sorter-text"` andor `headers { 1: sorter:"text"}` really work? I have numeric only values but need still use alphanumeric sorting. Values "1", "12" should go first but this example is always using a digit sorting.
http://jsfiddle.net/856bzzeL/840/

**Comment by Mottie** [comment]
Hi @Murmur!

The natural sort is used by default, and it won't sort "1" next to "12" in that table.

What you need to do is use the [`textSorter` option](http://mottie.github.io/tablesorter/docs/#textsorter) like this ([demo](http://jsfiddle.net/Mottie/856bzzeL/842/)):

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra'],
    textSorter: {
    	// plain text sort
    	1: $.tablesorter.sortText
    }
  });
});
```

**Comment by Murmur** [comment]
Ok that was a hidden unexpected parameter. Do you think it would be more intuitive have this mode directly in `headers: { 1: {sorter:"alphanumtext"} }` enum field?

http://jsfiddle.net/856bzzeL/843/

**Comment by Mottie** [comment]
I'm not sure what you mean. The alphanumeric sort is performed by default. Using the `textSorter` option does not require any special class name or `headers` option to work.

Also, in that demo, to disable the sort in the "Notes" column, you'll need to switch the class to `"sorter-false"`

```html
<th class="sorter-false">Notes</th>
```

To get `"{sorter: false}"` to work, you'll need to load in the [metadata plugin](https://github.com/Mottie/tablesorter/blob/master/js/extras/jquery.metadata.js).

**Comment by Murmur** [comment]
I meant an option headers.sorter.{colIdx}=text does not sort "1","12","4",...  I need to give various column specific header values(digit sort etc...). Giving sorter=text  does a natural sort, not real alphanum? I was thinking headers.sorter enum could use text,realtext so this dual text sorting worked through same prop.

**Comment by Mottie** [comment]
Frankly, to me adding this code:

```js
textSorter: {
    // plain text sort
    1: $.tablesorter.sortText
}
```

is just as easy as adding

```js
headers: {
    1: { sorter: "text" }
}
```

even though they do completely different things.

So are you saying you want to be able to add a class name to switch the `textSorter`?

**Comment by Murmur** [comment]
I dont want to press anything but I think my message is lost in translation. Using headers.$colidx.sorter=text vs textsorter.$colidx.tablesorter.sortText does not perform similar text sorting. Thats what I am experiencing. Thinking sorter=text,digit,etc could enable both str sorting modes with consistent property interface. Enum text=as-is, realtext=sort_1,12,31,345,4,...

**Comment by Mottie** [comment]
As I said before, the alphanumeric sort is set by default. So if a column has only numeric values, setting the column to sorter text or digit won't make a difference. If you want the numbers to be sorted as if it were text, then you'd have to set the sorter  to "text" *and* change the `textSorter` to not use the alphanumeric sorting algorhithm, and use a plain text sort instead.
