### ISSUE TITLE
How to re-init tablesorter

### ISSUE THREAD

**Issue by derrickxiang** [Mottie/tablesorter#1131]
I am using the tablesorter plugin in my web project, and my table data is generated dynamically via ajax, I encountered the issue when first time I can see the table sorting is working properly, but when I changed some condition and the table data was updated, then the tablesorter is not working any more, click the header and no response, I'm thinking the issue could be every time I refresh the data I will call the $('#tableid').tablesorter(), but the previous instance not destroied, so fail to re-init the plugin, is this the cause? if yes how should I do to re-init it? thanks.

**Comment by Mottie** [comment]
Hi @derrickxiang!

Tablesorter caches the data from the table for faster sorting but it doesn't automatically update this cache whenever the content of the table changes. You'll need to signal tablesorter to update the cache.

There are various methods that can be used to update the cache.

| Description | Method | Example |
|---|---|---|
| Change to `tbody` content | [update](http://mottie.github.io/tablesorter/docs/#update) | `$('table').trigger('update');` |
| Add new rows to `tbody` | [addRows](http://mottie.github.io/tablesorter/docs/#addrows) | `$('table').trigger('addRows', [ $newRows ]);` |
| Change single `tbody` cell | [updateCell](http://mottie.github.io/tablesorter/docs/#updatecell) | `$('table').trigger('updateCell', [ $cell ]);` |
| Change `thead` content | [updateHeaders](http://mottie.github.io/tablesorter/docs/#updateheaders) | `$('table').trigger('updateHeaders');` |
| Add/remove column | [updateAll](http://mottie.github.io/tablesorter/docs/#updateall) <sup>&dagger;</sup> | `$('table').trigger('updateAll');` |

&dagger; Use "updateAll" sparingly as some widgets don't fare well with being destroyed & reapplied.

If the entire table content is replaced, then it might be best to use the [destroy method](http://mottie.github.io/tablesorter/docs/#destroy), then reinitialize tablesorter.

**Comment by derrickxiang** [comment]
This is exactly what I need, thank you very much!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
