### ISSUE TITLE
Hide column at init. table

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1133]
Hi,
In http://jsfiddle.net/3pS6v/222/, the columns still display. Please help and many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

When setting up the column selector, the default setting of `columnSelector_mediaquery` is `true` which requires  that `data-priority` attributes are set for each header. Setting it to `false` allows hidding columns. I'll make this more clear in the documentation.

```js
$(function() {

	$("table").tablesorter({debug: true,
		theme: 'blue',
		widgets: ['columnSelector'],
		widgetOptions : {
			columnSelector_mediaquery: false,
			columnSelector_columns: {
				0: false,
				2: false
			}
		}
	});

});
```

Also, the [demo](http://jsfiddle.net/Mottie/3pS6v/223/) won't work unless the `widget-columnSelector.js` file is loaded.

**Comment by airthomas** [comment]
Hi Mottie,

I have tried http://jsfiddle.net/Mottie/3pS6v/223/, looks has cache problem, when I change 
from
0: false,
2: false
to
0: false,
1: false
it is work, but if change back 0:false, 2:false, it will not work.

**Comment by Mottie** [comment]
That is happening because the [`columnSelector_saveColumns` option](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-save-columns) is `true` ([demo](http://jsfiddle.net/Mottie/3pS6v/225/)).

**Comment by airthomas** [comment]
great, many thanks Mottie.
