### ISSUE TITLE
Delay Filter looks not work

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1134]
I have set the (filter_searchDelay: 30000000) in below jsfiddle, but looks not work. Would you please help to see see, many thanks.

http://jsfiddle.net/9tBgZ/103/

**Comment by Mottie** [comment]
Hi @airthomas!

Yep, that looks like a bug, thanks for reporting it!

**Comment by Murmur** [comment]
Just found out it's broken in my webapp as well, took most recent  jquery.tablesorter.min.js files(2.25.2) and jquery.tablesorter.widgets.min.js(01-20-2016 v2.25.2) files from the github.

Made a quick hack to see if this works and the following change did works, but I do not know enough inner details if this is a proper fix.

**jquery.tablesorter.widgets.min.js**
```
			searching : function (a, c, d) {
				var e = a.config.widgetOptions;
				clearTimeout(e.filter_searchTimer),
				e.filter_liveSearch ? e.filter_searchTimer = setTimeout(function () {
						b.checkFilters(a, c, d)
					}, e.filter_liveSearch ? e.filter_searchDelay : 10) : b.checkFilters(a, c, d)				
				//"undefined" == typeof c || c === !0 ? e.filter_searchTimer = setTimeout(function () {
				//		b.checkFilters(a, c, d)
				//	}, e.filter_liveSearch ? e.filter_searchDelay : 10) : b.checkFilters(a, c, d)
			}
```
