### ISSUE TITLE
External Filter by Date Range (datepicker)

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1135]
Hi,

I have prepared http://jsfiddle.net/abkNM/7575/, and I want to apply external filter by 2 fields.

I want to result display the date column equals to Date-1 or Date-2, since I will apply ajax pager, means I need to pass Date-1 and Date-2 values to JSON page.

Many thanks.

**Comment by airthomas** [comment]
hi,

First problem is solved in http://jsfiddle.net/abkNM/7573/, only want to know how to implement external filter by date range (2 fields).

Thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

If you look at the home wiki page under [Widgets](https://github.com/Mottie/tablesorter/wiki#widgets), look for "Filter widget", then "date pickers" and you'll find some demos that use a date range picker.

Right now these demos are applied to a filter inside the table, but can be modified to target an input outside the table:

  * [Bootstrap-daterangepicker](http://jsfiddle.net/abkNM/2188/) - uses [dangrossman/bootstrap-daterangepicker](https://github.com/dangrossman/bootstrap-daterangepicker) plugin.
  * [jQuery Date Range Picker](http://jsfiddle.net/Mottie/abkNM/2919/) - uses [longbill/jquery-date-range-picker](https://github.com/longbill/jquery-date-range-picker) plugin.
  * [jQuery Datepicker](http://jsfiddle.net/Mottie/abkNM/2914/) - uses [keith wood datepicker](http://keith-wood.name/datepick.html#range) plugin.
  * [jQuery Filament Group Datepicker](http://jsfiddle.net/Mottie/abkNM/2915/) - uses [Filament Group Date Range Picker](http://filamentgroup.com/lab/date-range-picker-using-jquery-ui-16-and-jquery-ui-css-framework.html) plugin.

This would work better than trying to add code for two inputs.

**Comment by airthomas** [comment]
great and thanks your help.
