### ISSUE TITLE
Filter-select matches partially

### ISSUE THREAD

**Issue by LvLynx** [Mottie/tablesorter#1136]
Hi,
Seems that on latest version class="filter-select" does partial match for filtering. As I understand it should be exact.

I created fiddle with 1st column filter-select 2nd column "filter-select filter-match". At the moment they both work the same.

http://jsfiddle.net/5p3cjxd1/2/

**Comment by Mottie** [comment]
Hi @LvLynx!

Thanks for reporting this problem. I'll have a fix available in the master branch shortly.

**Comment by Mottie** [comment]
[updated demo](http://jsfiddle.net/Mottie/5p3cjxd1/3/)
