### ISSUE TITLE
Column to have asc/reset sort direction, rest colums asc/desc/reset direction

### ISSUE THREAD

**Issue by Murmur** [Mottie/tablesorter#1137]
I have one column where SortByASC or Reset(nosort) are only sane options, DESC is not required. Remaining columns may use Asc/Desc/Reset options. I could not find attributes to do it. Possible?

**Comment by Mottie** [comment]
Hi @Murmur!

Set a `lockedOrder` value inside the [`headers` option](http://mottie.github.io/tablesorter/docs/#headers).

**Comment by Murmur** [comment]
Sort of works. I was trying to have double-arrow,down-arrow,double-arrow state changes. Using a lockedOrder prop it goes double-arrow,down-arrow,(sticked to desc). I cannot reset an ordering anymore. Tried giving multiple values of allowed sorting state but failed.

```
  ,headers: {
    0: { lockedOrder:"desc" }
  } 
```

**Comment by Mottie** [comment]
Ok, try this instead ([demo](http://jsfiddle.net/Mottie/856bzzeL/855/))

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    initialized: function(table){
    	table.config.sortVars[0].order = [ 1,2 ];
    }
  });
});
```

**Comment by Murmur** [comment]
That was a hidden secret. I do see a weird side effect if `sortReset:true` attribute was also given. Column's sorting state is double-arrow,down-arrow,double-arrow,double-arrow,down-arrow instead of double-arrow,down-arrow,double-arrow,down-arrow,...
http://jsfiddle.net/856bzzeL/856/

**Comment by Mottie** [comment]
Yeah, I'm not sure how to fix that... when `sortReset` is `false` there are only two order states. When `true`, there are three states: asc, desc and reset... hard to make a locked column sort one direction and reset when the `sortReset` is looking for three states.
