### ISSUE TITLE
headers sorter text issue

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1138]
Hi Mottie,

In http://jsfiddle.net/eY8uH/1525/, I have config the column sorted by "text", but looks not work.

Thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

This fork of tablesorter uses an alphanumeric sort by default. If you want a plain text sort, you'll need to set the [`textSorter` option](http://mottie.github.io/tablesorter/docs/#textsorter) as well ([demo](http://jsfiddle.net/Mottie/eY8uH/1526/)):

```js
$(function() {
  $("table").tablesorter({
    headers: {
      0: {
        sorter: 'text'
      }
    },
    textSorter: $.tablesorter.sortText
  });
});
```

**Comment by airthomas** [comment]
It is work, many thanks.
