### ISSUE TITLE
Problem on Table Title and headers{}

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1141]
Hi Mottie,

Please help to review http://jsfiddle.net/abkNM/7601/...

when I removed "<tr></tr><th colspan="5">Title</th></tr>", then everything correct.

Many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

Tables don't have a title, they have a [caption](https://www.w3.org/TR/html-markup/caption.html) - [demo](http://jsfiddle.net/Mottie/abkNM/7602/).

I would appreciate it if you would only open an issue if there is a problem with the tablesorter code, or if you have an enhancement request. If you need help with making a demo work, or just have a question, please use IRC (freenode) in the `#tablesorter` channel, or [Gitter](https://gitter.im/Mottie/tablesorter) and then if no one answers, try [Stackoverflow](http://stackoverflow.com/questions/tagged/tablesorter).

Opening an issue in GitHub may get your question answered quickly (for now), but it also distracts me from other work that I am trying to do.

Thank you.

**Comment by airthomas** [comment]
Hi Mottie,

I'm follow this https://mottie.github.io/tablesorter/docs/example-pager-ajax.html...

and the title is for put the pager class, if applied <caption>, the above issue is fixed, but the layout is different with <thead>.

Many thanks.

**Comment by airthomas** [comment]
I have changed my css to match the style, many thanks and I will try on Stackoverflow if is a question.

**Comment by airthomas** [comment]
Hi Mottie,

After added 'scroller' to http://jsfiddle.net/4mVfu/5854/, the caption location looks wrong....

Thanks.

**Comment by Mottie** [comment]
Honestly, I would add the pager controls outside of the table - http://jsfiddle.net/Mottie/4mVfu/5855/

I'll fix the caption problem, but if you add a fixed column, it looks wrong to have the caption scroll horizontally.
