### ISSUE TITLE
Broken multi-column sort

### ISSUE THREAD

**Issue by quentindemetz** [Mottie/tablesorter#1142]
I can't get this to work locally and it seems even the demo on the documentation page doesn't work.

**Steps to reproduce**
- Scroll to the first table on http://mottie.github.io/tablesorter/docs/index.html
- Sort by "Account #"
- Hold down SHIFT key and sort by "Age"

**Outcome**
Age column is not sorted at all.
![screen shot 2016-01-26 at 13 26 18](https://cloud.githubusercontent.com/assets/2451971/12580491/6bbe4d48-c430-11e5-8a7b-3ac2d8508d44.png)

**Comment by Mottie** [comment]
Hi @quentindemetz!

The primary sort on the "Account #" column does not have any duplicate entries, so when a secondary sort is added to the "Age" column, nothing appears to happen.

Try sorting the "First Name" column first - it has four "Bruce" entries - then apply a secondary sort on the "Age" column. A tertiary sort can also be applied to the "Difference" column to see that further sorting is still applied.

**Comment by quentindemetz** [comment]
Ah yes, that's right, sorry for the oversight and thanks for the clear explanation!
