### ISSUE TITLE
Problems with remove-me class, default selectorRemove not removed

### ISSUE THREAD

**Issue by ecbbce** [Mottie/tablesorter#1143]
The specific rows still have the .remove-me class, the row isn't removed, please see attached screenshots of HTML and result. 

With debugging the c.$table.find( c.selectorRemove ).remove(); line 1244 and1430 in the tablesorter.js are not called.

![capture](https://cloud.githubusercontent.com/assets/2444655/12614700/d8edd984-c501-11e5-9054-af296eb4f44a.PNG)
![capture2](https://cloud.githubusercontent.com/assets/2444655/12614720/ef2c5162-c501-11e5-9dea-b06050037614.PNG)

**Comment by Mottie** [comment]
Hi @ecbbce!

That row shouldn't have a height unless there is some css to add that height which overrides the row style.

The reason that row exists is to maintain column sizes. The only time the "remove-me" rows get removed is when an update is triggered, or the table is resized. So, it should be there.

If you would share a demo showing this issue, you can use [this demo](http://jsfiddle.net/Mottie/mqv16pd4/), I can help figure out why that row has a height when it shouldn't.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
