### ISSUE TITLE
Include custom data attribute in filtering

### ISSUE THREAD

**Issue by Boduje** [Mottie/tablesorter#1147]
I couldn't find anything similar in a search, so if I missed it, I apologize.

I am pulling a recordset of items from a database.  Some of those items have been "tagged" with extra grouping information, similar to Twitter hashtags.  Those tags are written at the row (tr) level in a "data-tag" attribute.  Is there an easy way to include that attribute in the filtering widget?

**Comment by Mottie** [comment]
Hi @Boduje!

Would you share an example of the HTML, and what data is to be included? Do you want that extra data to always be included, or would the user need to use a special symbol to search that extra data?

**Comment by Boduje** [comment]
Here's an example:

`<tbody aria-relevant="all" aria-live="polite">
	<tr class="odd" role="row" id="306" data-tags="easy, welding">
		<td class="p9">...</td>
		<td class="p30 has-icons">...</td>
		<td class="p8 center">...</td>
	</tr>
	<tr class="even" role="row" id="332" data-tags="armor, ar500, target">
		<td class="p9">...</td>
		<td class="p30 has-icons">...</td>
		<td class="p8 center">...</td>
	</tr>
	<tr class="odd" role="row" id="421" data-tags="">
		<td class="p9">...</td>
		<td class="p30 has-icons">...</td>
		<td class="p8 center">...</td>
	</tr>
	...
</tbody>`

Not all rows will have tag information, which will leave the attribute empty, but the data-tags attribute would always need to be included.

**Comment by Boduje** [comment]
Or...

I could attach the 'data-tags' attribute to a specific column and only include it when filtering on that column.  That might be an easier way.  What do you think?

**Comment by Mottie** [comment]
I think the easiest solution would be to add a `textExtraction` function that targets specific columns, or it can be applied to all columns - ([demo](http://jsfiddle.net/Mottie/856bzzeL/886/))

```js
$(function() {
	$('table').tablesorter({
		theme: 'blue',
		textExtraction: function(node, table, columnIndex){
			if (columnIndex === 0) {
				// add data-tags content to the end of the cell content
				return node.textContent + ' ' + $(node).parent().attr('data-tags');
			}
			return node.textContent
		},
		widgets: ['zebra', 'filter']
	});
});
```

I added colors to the demo so it is easier to see if the right rows are showing up.

**Comment by Boduje** [comment]
Dang, I see that in the documentation now.  That's what I get for only searching GitHub.  LOL

Anyway, your code snippet works like a charm and gives me a great headstart for any future mods.

Thanks again for this great package!

**Comment by Boduje** [comment]
Just in case anyone else can benefit from this, I wound up attaching my tags to a specific field instead of to a row.  Then I modified Mottie's example to:

```javascript
textExtraction: function(node, table, columnIndex)
{
	if ($(node).hasClass('tagged'))
	{
		return node.textContent + ' ' + $(node).attr('data-tags');
	}
	return node.textContent
},
```

**Comment by Mottie** [comment]
If a data-attribute is undefined, jQuery will return an empty string... so this is also possible:

```js
textExtraction: function(node, table)
{
    return node.textContent + ' ' + $(node).attr('data-tags');
},
```

If the data-attribute is undefined, the extra space at the end will get stripped out when the data is cached.
