### ISSUE TITLE
print_title CSS?

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1148]
How can I set the CSS for the print_title?  Is there an example somewhere?

**Comment by Mottie** [comment]
Hi @southmeadows!

What `print_title`? Would you share your HTML & initialization code?

**Comment by Mottie** [comment]
Oh, if you mean the print widget `print_title` option, that is added to the popup window as a title ([demo](https://jsfiddle.net/Mottie/bdddtbts/1/)):

![2016-02-01 20_44_56-fred](https://cloud.githubusercontent.com/assets/136959/12738274/e411472a-c924-11e5-91d8-1a455fd787a5.png)


You can't style the window title bar without changing the options in your OS.

**Comment by southmeadows** [comment]
See in your example print_title is = "Fred"
How do you change the style on this?

**Comment by Mottie** [comment]
You can't... that is a browser popup window which is styled by your operating system. The only way to style it is to change the operating system theme.

**Comment by southmeadows** [comment]
What does this do:

print_styleSheet : 'css/theme.blue.css', // add the url of your print stylesheet

**Comment by Mottie** [comment]
Adds an additional style to the popup window... see [`print_styleSheet` option](http://mottie.github.io/tablesorter/docs/example-widget-print.html#print_stylesheet).

Essentially, it takes that url and adds this to the popup:

```html
<!-- print_styleSheet : 'css/theme.blue.css' -->
<link href="css/theme.blue.css" rel="stylesheet">
```

**Comment by Mottie** [comment]
And before you ask... `print_extraCSS` does this:

```html
<style>
/* predefined styles here */
/* extra css added below 
 print_extraCSS : 'img { display: none; }'
*/
img { display: none; }
</style>
```

**Comment by southmeadows** [comment]
so basically the problem is the tablesorter doesnt have a title so the CSS doesnt have anything to do with it. The CSS and the extraCSS only controls the style of the table itself. Is that right?

**Comment by Mottie** [comment]
If you want to add a title to the table, then add a `<caption>` ([demo](https://jsfiddle.net/Mottie/bdddtbts/2/))...

```html
<table>
  <caption>Title</caption>
  <thead>...</thead>
  <tbody>...</tbody>
</table>
```

then you can use the `print_extraCSS` option to style it:

```js
print_extraCss : 'caption { font-size: 30pt; }'
```

**Comment by southmeadows** [comment]
That works great. Thank you so much for the help!
