### ISSUE TITLE
cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by ashish-bhanderi** [Mottie/tablesorter#1151]
When I applied sorting on first column which contains text, 

At that time it gives an error "cannot read property 'replace' of undefined" in function **sortNatural**
Line no: 1760
aNum = a.replace( regex.chunk, '\\0$1\\0' ).replace( regex.chunks, '' ).split( '\\0' );

because variable **a** is undefined.

Can you please put condition over-there?

**Comment by Mottie** [comment]
Hi @ashish-bhanderi!

The natural sort function only accepts strings. There is a note at the start of the function:

> // Natural sort - https://github.com/overset/javascript-natural-sort (date sorting removed)
 // this function will only accept strings, or you'll see 'TypeError: undefined is not a function'
 // I could add a = a.toString(); b = b.toString(); but it'll slow down the sort overall

If you're seeing an error, then the first column in your table must be parsing values... please make sure that a "text" parser is being used.

**Comment by ashish-bhanderi** [comment]
I am applying sorting on text fields only.
The case is below.
In my table suppose I have three values ("BBB", "ddd", "eee");

So, For the first iteration it should compare **"BBB"** and **"ddd"**. Instead of that it is doing below thing.
First iteration value of variable **a ** is **undefined ** while value of variable **b** is "BBB".
in next iteration value of variable **a** will be "BBB",  while value of variable **b** will be "ddd".

That's why I am asking to put below condition 
**if(a != undefined)**
aNum = a.replace( regex.chunk, '\0$1\0' ).replace( regex.chunks, '' ).split( '\0' );

**Comment by Mottie** [comment]
Would you please modify [this demo](http://jsfiddle.net/856bzzeL/) so that it duplicates this error.

Sorry, I am being stubborn, because the natural sort function is used a lot while sorting and any extra code means it slows down that much more... it may not be noticeable in small tables in Chrome, but try a large table in Internet Explorer.

Once I have time to integrate clusterize into the code, it may not be much of an issue anymore.

**Comment by Mottie** [comment]
Any update on this issue?

**Comment by ashish-bhanderi** [comment]
I found other solution.
Code was fine.
Thanks

**Comment by roctoll** [comment]
Hey @ashish-bhanderi! what solution did you find? I have the same problem for empty rows..

**Comment by Mottie** [comment]
Hi @roctoll 

I'm not sure why you're getting an undefined error, but ok ok I give in... I'll add a fix to fallback to an empty string, but I still don't think I need to add a `.toString()`.

**Comment by melisekp** [comment]
Had the same problem.
Found out that instead of closing my table row tag i opened another and while most browsers take this correctly. Tablesorter seems to add an empty row and so it find that undefined value. 
Well double-check your html :)
