### ISSUE TITLE
Disabling liveSearch does not work

### ISSUE THREAD

**Issue by kelesi** [Mottie/tablesorter#1152]
In v2.25.3 setting "filter_liveSearch : false" does not disable liveSearch. It was working in v2.23.5.

**Comment by kelesi** [comment]
Seems like the issue is in
`.bind( 'search change keypress '.split( ' ' ).join( namespace + ' ' ), function( event )`

where this condition
`if ( wo.filter_initialized && ( event.which === 13 || event.type === 'search' ||
    event.type === 'change' && this.value !== c.lastSearch[column] ) ) {`

has been changed to this
`if ( wo.filter_initialized && ( event.which === tskeyCodes.enter || event.type === 'search' ||
    // only "input" event fires in MS Edge when clicking the "x" to clear the search`
`    ( event.type === 'change' || event.type === 'input' ) && this.value !== c.lastSearch[column] ) ) {
`

When removing the added condition 
`event.type === 'input'`, the disabling of liveSearch works.

Or replacing it with 
`( event.type === 'change' || (event.type === 'input' && wo.filter_liveSearch === true))`

I am not sure why the `event.type === 'input'` condition has been added to the function, so I am not sure what is the correct way for fixing this.

**Comment by Mottie** [comment]
Hi @kelesi!

I'm looking into this now. Thanks for reporting the issue and doing some troubleshooting!

**Comment by Mottie** [comment]
Ok, I have a fix available in the master branch... I was trying to write a unit test, but sadly I've run out of time for messing around this morning :wink:

**Comment by Mottie** [comment]
Version 2.25.4 is now available with this fix!

**Comment by kelesi** [comment]
Hi @Mottie,
Seems like disabling live search does not work again since v2.27.7.

**Comment by Mottie** [comment]
Hi @kelesi!

Sorry for the delay in responding, I've just returned from a much needed extended vacation.

It appears that the liveSearch setting was bypassed when an "input" event listener was included to fix issue #1280. I'll need to figure out the best way to deal with this new issue... either ignore the "input" event when the `filter_liveSearch` option is `false`, or check for a mobile device and only include in that case.

**Comment by Mottie** [comment]
Setting the `liveSearch` to `false` was fixed in v2.28.11. Please let me know if you encounter any issues with the changes.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
