### ISSUE TITLE
Problem with tablesorter & Grouping

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1153]
hello,

i am having a new problem with the using of the tablesorter and grouping

i have a table with fields like "name","date_birth".....etc....and i have applied the widget to the field date_birth,

the problem is when i search in the header field for a string that does not exist in the list i get the error

"TypeError: e.rowData is undefined" (line 208) in the file widget-grouping.js

can you tell me what is the problem?

Best Regards,

Fábio Ferreira

**Comment by Mottie** [comment]
Hi Fábio!

Are you using the most up-to-date tablesorter & grouping widget? Using an older version of tablesorter is the only reason I can think that would cause the error you shared.

If you are using the latest versions, then would you please modify [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/) to show me the problem. It would make troubleshooting so much easier. Thanks!

**Comment by fcferreira29** [comment]
is there a new version of the grouping? the one we have here is  /*! Widget: grouping - updated 11/10/2015 (v2.24.4) */ Date: Fri, 5 Feb 2016 08:58:18 -0800From: notifications@github.comTo: tablesorter@noreply.github.comCC: fcferreira@msn.comSubject: Re: [tablesorter] Problem with tablesorter & Grouping (#1153)Hi Fábio!

Are you using the most up-to-date tablesorter & grouping widget? Using an older version of tablesorter is the only reason I can think that would cause the error you shared.

If you are using the latest versions, then would you please modify this demo to show me the problem. It would make troubleshooting so much easier. Thanks!

**Comment by Mottie** [comment]
That is the most current version... what about tablesorter?

**Comment by fcferreira29** [comment]
2.25.3 Date: Fri, 5 Feb 2016 09:17:37 -0800From: notifications@github.comTo: tablesorter@noreply.github.comCC: fcferreira@msn.comSubject: Re: [tablesorter] Problem with tablesorter & Grouping (#1153)That is the most current version... what about tablesorter?

**Comment by Mottie** [comment]
Then please reproduce the error in the jsfiddle, so it is easier for me to troubleshoot.

**Comment by Mottie** [comment]
Any update on this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
