### ISSUE TITLE
sub totals

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#1154]
Is there a SIMPLE example of subtotals. For example if I have 2 columns, person name, and total. When person name changes create a sub total.

Totals for all the columns works great already but haven't figured out how to do the sub totals. All of the examples I have found have all kinds of cool features but I just would like the one simple one I hope.

Thank you in advance!

**Comment by Mottie** [comment]
Hi @southmeadows!

Try [this demo](http://jsfiddle.net/Mottie/abkNM/7679/)

Script

```js
$(function () {
    $('table').tablesorter({
        theme: 'blue',
        widgets: ['zebra', 'math']
    });
});
```

HTML

```html
<table>
	<thead>
		<tr>
			<th>Name</th>
			<th>Amount</th>
		</tr>
	</thead>
	<tbody>
		<tr><td>Joseph</td><td>$ 423</td></tr>
		<tr><td>Lawrence</td><td>$ 5,908</td></tr>
		<tr><td>Maria</td><td>$ 6,502</td></tr>
		<tr><td>Matt</td><td>$ 4,170</td></tr>
	</tbody>

	<tbody class="tablesorter-infoOnly">
		<tr>
			<th></th>
			<th data-math="above-sum">above-sum</th>
		</tr>
	</tbody>

	<tbody>
		<tr><td>Jerry</td><td>$ 3,643</td></tr>
		<tr><td>Frank</td><td>$ 4,456</td></tr>
		<tr><td>Missy</td><td>$ 6,235</td></tr>
		<tr><td>Nancy</td><td>$ 3,868</td></tr>
	</tbody>

	<tbody class="tablesorter-infoOnly">
		<tr>
			<th></th>
			<th data-math="above-sum">above-sum</th>
		</tr>
	</tbody>

	<tbody>
		<tr><td>Suzy</td><td>$ 507</td></tr>
		<tr><td>Kim</td><td>$ 1,082</td></tr>
		<tr><td>Kyle</td><td>$ 820</td></tr>
		<tr><td>Roger</td><td>$ 737</td></tr>
	</tbody>

	<tbody class="tablesorter-infoOnly">
		<tr>
			<th></th>
			<th data-math="above-sum">above-sum</th>
		</tr>
	</tbody>

</table>
```

**Comment by southmeadows** [comment]
Supposing the data had the same name several times like Joseph in your example. The example you have set up the table with 3 sections. Suppose it was one section and the name column was sorted. So when a name changes then it shows the sub total.  In my real world I have names coming from a database along with the amount. I guess I could manually code it to check the last name compared to the current row and then code in the sub total section like your example. But I think your tablesorter knows how to do this by itself?

**Comment by Mottie** [comment]
So is the user interacting with the entire database, or looking at sections loaded with ajax? Are you saying you want a row added after each name group with a subtotal? Is there more than one column with subtotals?

**Comment by southmeadows** [comment]
it would be like below from the database as an example. I load the table using PHP and generating the rows in the table like below.  The table would have been sorted by name in the actual application. 

`<tbody>
        <tr><td>Suzy</td><td>$ 507</td></tr>
	<tr><td>Roger</td><td>$ 737</td></tr>
   	 <tr><td>Kyle</td><td>$ 920</td></tr>
	<tr><td>Roger</td><td>$ 277</td></tr>        
	<tr><td>Kim</td><td>$ 1,082</td></tr>
    	 <tr><td>Suzy</td><td>$ 507</td></tr>   
    	 <tr><td>Kyle</td><td>$ 820</td></tr>
        <tr><td>Roger</td><td>$ 997</td></tr>
    </tbody>`

**Comment by Mottie** [comment]
Maybe you can use the group widget instead of the math widget... it adds a group header which you can modify using the [`group_callback` option](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html#group_callback) to sum up the values in the cells above.

**Comment by southmeadows** [comment]
Is there a simple example of this with summing the above too? Sorry I know there are excellent examples of everything but its so hard to figure out just the part I need and then make it work.

**Comment by Mottie** [comment]
Ok, try [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/19/):

```js
$(function() {

  $("table").tablesorter({
    theme: "blue",
    sortList: [[0,0]],
    widgets: ["group", "columns", "filter", "zebra"],
    widgetOptions: {
      group_callback: function($cell, $rows, column, table) {
        // callback allowing modification of the group header labels
        // $cell = current table cell (containing group header cells
        //   ".group-name" & ".group-count"
        // $rows = all of the table rows for the current group; table = current table (DOM)
        // column = current column being sorted/grouped
        var subtotal = 0;
        $rows.each(function() {
          var txt = $(this).find("td").eq(1).text().replace(/[$,]/g, '');
          subtotal += parseFloat(txt);
        });
        $cell.find(".group-count").append("; subtotal: $" + subtotal);
      }
    }
  });

});
```

```html
<table class="tablesorter">
	<thead>
		<tr>
			<th class="group-word">Name</th>
			<th class="group-false">Amount</th>
		</tr>
	</thead>
	<tbody>
		<tr><td>Joseph</td><td>$ 423</td></tr>
		<tr><td>Lawrence</td><td>$ 5,908</td></tr>
		<tr><td>Maria</td><td>$ 6,502</td></tr>
		<tr><td>Maria</td><td>$ 4,170</td></tr>
		<tr><td>Suzy</td><td>$ 3,643</td></tr>
		<tr><td>Maria</td><td>$ 4,456</td></tr>
		<tr><td>Maria</td><td>$ 6,235</td></tr>
		<tr><td>Joseph</td><td>$ 3,868</td></tr>
		<tr><td>Suzy</td><td>$ 507</td></tr>
		<tr><td>Lawrence</td><td>$ 1,082</td></tr>
		<tr><td>Joseph</td><td>$ 820</td></tr>
		<tr><td>Lawrence</td><td>$ 737</td></tr>
  </tbody>
</table>
```

**Comment by southmeadows** [comment]
Thank you for the help! This didnt quite work but I manually created the sub totals in PHP while I was reading in the table.  
Thank you!!!
