### ISSUE TITLE
removeWidget "pager" not working as expected

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1155]
Hi,

I try to set up an table that by default uses the "pager" widget. The user has the choice to switch off the pager and enable the "grouping" widget. I've put together a [simple demonstration](http://jsfiddle.net/amair/uwh87bm3/), that tries to remove the pager like this:

```js
$('table').trigger('destroyPager');
$('table').trigger('removeWidget', 'pager');
```

After clicking "Destroy Pager" I see an error in the Javscript console:
`TypeError: p is undefined`

Now each time I click a column header I see another error:
`TypeError: c.pager is undefined`

If I destroy the pager like this alternate way:
```js
$('table')[0].config.widgets = ['zebra', 'group'];
$('table').trigger('destroyPager');
```

... then it works.

Actually the error messages are independent of the "grouping" widget, but I wonder what's going wrong here. Is "removeWidget" not supposed to remove the "pager" widget?

Regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Thanks for reporting this problem!

I'll fix the javascript error, but it isn't necessary to trigger both of these methods.

```js
$('table').trigger('destroyPager');
$('table').trigger('removeWidget', 'pager');
```

Do one, or the other.

It also is not necessary to redefine the `widgets` options to remove the `"pager"` widget. I'll update the demo to show this change.

**Comment by a-mair** [comment]
@Mottie: thanks, works!
