### ISSUE TITLE
"zebra" not working if filtering collapsed groups.

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1156]
Hi,

I'm using the "zebra", "filter" and "grouping" widgets together. Opening collapsed groups will show a wrong "zebra" if filtering happened while they had been collapsed.
Might be due to only selecting `tr:visible` rows in the zebra widget. Maybe you shouldn't rely on  ":visible" as this might have performance implications (see [http://api.jquery.com/visible-selector/](url)) and move to a CSS class to identify rows that are not filtered but hidden due to another reason?

Regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Actually the `:visible` selector is necessary, especially when striping filtered rows.

I am seeing this same issue, so I think I'll just reapply the zebra widget when collapsed groups are opened up.

**Comment by a-mair** [comment]
@Mottie: thanks!
