### ISSUE TITLE
iQuery issue in Filter Widget processRows

### ISSUE THREAD

**Issue by jasongabel** [Mottie/tablesorter#1157]
I keep getting this error: Uncaught TypeError: Cannot read property 'test' of undefined and the undefined seems to be the iQuery in tfsRegex
It seems to be that the iQuery is undefined even though I can see it is in the init for tfs, but this may be overridden by tsfRegex = tsf.regex;

**Comment by Mottie** [comment]
Hi @jasongabel!

Would you share the code being used to initialize tablesorter, and is there a specific query that reproduces this error?

Some tests aren't defined until the filter widget is initialized, so that might be part of the issue.

**Comment by Mottie** [comment]
Any update on this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
