### ISSUE TITLE
Adding "grouping" widget to sorted table logs JS error

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1158]
Hi,

I think I've found another problem. I've put together a [simple demonstration](http://jsfiddle.net/amair/0j84jztb/).
You simply have to click the "Name" table header to sort that column. Then you have to click "Destroy pager" to switch from "pager" to "grouping".
Now you'll get a JS error: `TypeError: can't convert undefined to object`

Regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Sorry, I've been short of free time today... anyway, I ended up modifying the group widget. The fix will be available in the master branch shortly.

**Comment by a-mair** [comment]
@Mottie: thanks!
