### ISSUE TITLE
Crash in IE10 and IE11 when appending table rows

### ISSUE THREAD

**Issue by brendanfalkowski** [Mottie/tablesorter#1159]
Posting this for reference. Took me a long time to trace this back to a failure in IE (not tablesorter).

When you append a large number of rows to `<tbody>` IE crashes. I thought tablesorter was crashing on re-sort, but it turns out IE needs some specific optimization. Read these:

http://jquery-howto.blogspot.com/2009/02/5-easy-tips-on-how-to-improve-code.html

I was already doing suggestions 1 + 2 + 4. Number 3 made the difference. For whatever reason IE freaks out when you append a huge number of adjacent elements (like `<tr>`) in one string to the `<tbody>`.

But if you append the `<tbody>` with a huge number of children, then it doesn't. Just having a wrapping parent element makes it survive the operation.

So rewriting my JS like this prevented IE from crashing every time:

``` javascript
// Update <tbody> with response.
if (insertionType === 'replace') {
    markup.push(
        '<tbody>',
            rows.join(''),
        '</tbody>'
    );
} else if (insertionType === 'append') {
    var currentRows = $jQ('.tablesorter tbody').html();

    markup.push(
        '<tbody>',
            currentRows,
            rows.join(''),
        '</tbody>'
    );
}

// Remove existing <tbody> and inject a new <tbody>
$jQ('.tablesorter tbody').remove();
$jQ('.tablesorter').append(markup.join(''));

// Must use "updateRows" not "update" event because Prototype is also loaded.
// See: https://github.com/Mottie/tablesorter/issues/217
var sortList = [[0, 1]];
$jQ('.tablesorter').trigger('updateRows', [sortList, false]);
```

**Comment by brendanfalkowski** [comment]
Marking this issue CLOSED because it's an ask/answer in one.

**Comment by Mottie** [comment]
Hi @brendanfalkowski!

Thanks for sharing!
