### ISSUE TITLE
Print Widget on nested tables

### ISSUE THREAD

**Issue by clod986** [Mottie/tablesorter#1160]
Hi @Mottie,
I have an issue while printing nested tables: the widget will print both.

I have a table nested inside a td, both tables with their own unique print button and unique id. When I print the inner table, both print windows will open (the outer table opens last).

Thank you!

**Comment by Mottie** [comment]
Hi @clod986!

I created [this demo](https://jsfiddle.net/bdddtbts/3/) and both tables are printed separately. So, I don't think it's a problem with the print widget.

If you need help with the code, please modify the demo with your code and I'll see what I can do.

**Comment by clod986** [comment]
Hi @Mottie ,
after feeling stupid for a couple of days I realized is a Firefox only issue.

You can test it directly on the link you gave me.

**Comment by Mottie** [comment]
Oh! Sorry, I didn't even think about trying the demo in Firefox. Now I'm feeling dumb too ;)

I'll have an patch in the master branch here shortly.

**Comment by Mottie** [comment]
Alternatively, if you ever run into an issue like this, in this or another plugin, you can use [`triggerHandler`](http://api.jquery.com/triggerHandler/), instead of `trigger`, which executes the event on the current element without having the event propagate.

```js
$('#table2').triggerHandler('printTable');
```
