### ISSUE TITLE
Storage: Storing of falsy non-null values other than empty strings.

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1163]
It seems to me like the documentation of the storage widget (https://mottie.github.io/tablesorter/docs/#function-storage) implies that any non-null value can be stored. 

But the code itself only allows empty strings and non-falsy values (therefore e.g. no 0). See https://github.com/Mottie/tablesorter/blob/ca24e6b550783485615eab9e4bc78d94c3e13d79/js/widgets/widget-storage.js#L70:
```javascript
// allow value to be an empty string too
if ((value || value === '') && window.JSON && JSON.hasOwnProperty('stringify')) {
```
(Exception for strings introduced in https://github.com/Mottie/tablesorter/commit/3e9b5d56ce7385fc148df755034398f60505159e#diff-91dd7fb07f6fad39c868aea0f8750172L84)

Any reason for not allowing other non-falsy non-null values as well?

**Comment by Mottie** [comment]
Hi @Herst!

I originally wrote the storage widget so that if no value was passed to the `value` parameter, it would assume you wanted to get the value from storage.

I don't see any problem with changing that line to use `typeof value !== 'undefined'` instead of checking for a "truthy" value.

**Comment by Mottie** [comment]
I'll push a new release this weekend.

**Comment by Herst** [comment]
I thought it might have had something to do with the cookie fallback but it works then that's great. Also, don't forget to change the documentation again.

**Comment by Herst** [comment]
Or simply don't allow ```null``` either:
```
if (typeof value !== 'undefined' && value !== null && window.JSON && JSON.hasOwnProperty('stringify')) {
```

**Comment by Mottie** [comment]
Umm, where exactly is the documentation does it show the limitations?

**Comment by Herst** [comment]
https://mottie.github.io/tablesorter/docs/#function-storage

**Comment by Herst** [comment]
>  value of the variable that is saved (for saving only); set to null if wanting to get a value with options.

**Comment by Herst** [comment]
> When using the storage utility to _get_ a value and use custom table options, set the value parameter to ````null```.

**Comment by Mottie** [comment]
Thanks!

**Comment by Herst** [comment]
Thanks!

BTW, just wondering: is it common in JS libraries to use ```undefined``` for empty parameters in the middle? It sure makes parameter handling a bit easier and I can't think of any obvious downsides.

**Comment by Mottie** [comment]
I don't know if it's common... it's pretty much like how jQuery UI does it - see the [slider api docs](http://api.jqueryui.com/slider/#method-value) on getting and setting a value.

I guess I could add two separate functions, one to get and one to set...

**Comment by Herst** [comment]
Nah, I just meant optional parameters that aren't at the end, e.g. `foo(a, b, c)` where `b` and `c` are optional so you can write `foo(a)`, `foo(a, b)`, `foo(a, b, c)`, but also `foo(a, undefined, c)` but nevermind. I tend to think about things too much. :sweat_smile:

**Comment by Mottie** [comment]
The last parameter are options that can override the data-attribute settings and widget options. You'll really only need to use it if you are storing something in a non-standard way or on a table that doesn't have tablesorter applied - either way, it'll be pretty rare, I think.
