### ISSUE TITLE
Problem with tablesorter & Grouping latest version

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1167]
hello guys,

i am having a problem with the latest version of the grouping (2.25.4)

the first time the table is rendered, the grouping is ok, but when i use filters the grouping stops working correctly dates get mixed (example i get 2 march and 3 march on the same grouping) (this problem only pops out when you choose a filter, when i used the version 2.23.3 this problem was not happening, 

is there any new developments on the grouping that may have affected the tablesorter?

thanks,

Fábio Ferreira

**Comment by Mottie** [comment]
Hi @fcferreira29!

Would you please modify [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/) to demonstrate this issue.

Also, there have been a lot of changes to both the grouping and filter widget between v2.23.3 and the current version. Please test, the versions in between to help me narrow down when the change occurred.

Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
