### ISSUE TITLE
Question about lazyload

### ISSUE THREAD

**Issue by fcferreira29** [Mottie/tablesorter#1168]
Hello guys,

the lazyload is suposed to show images when we scroll down, my question is...

the images from all the pages load eaven when we are not on the page, why is that?

the lazyload effect works fine on the first page, but on the other pages the images are already loaded, is that normal?

Thanks,

Fabio Ferreira

**Comment by Mottie** [comment]
Hi @fcferreira29!

Did you find your answer?
