### ISSUE TITLE
Problem with filter when formatter is included and using logical modifiers

### ISSUE THREAD

**Issue by TheSin-** [Mottie/tablesorter#1170]
using

http://mottie.github.io/tablesorter/docs/example-widget-formatter.html

in first col type ```super or man``` 0 results.
it's also aero with ```and```, ```&&```, ```|```

when I test this on the filter example page, it doesn't start to filter as I type ```_and``` (_ being the space) in the formatter example it does, I assume this it because it's being taken as a literal.  If I have time I will dig into this just want dot document the issue either way.

**Comment by Mottie** [comment]
Hi @TheSin-!

It looks like the problem you're seeing is because the "and" and "or" searches are set to look for an exact match by default - did I change that? - so all you need to do is add a `"filter-match"` class to the header cells ([demo](http://jsfiddle.net/Mottie/svfry8vh/2/))

```html
<th class="emphasize filter-match">Super Hero</th>
<th class="supercar filter-match">Super Car</th>
```

**Comment by TheSin-** [comment]
it must have changed as I haven't changed anything and it used to work. let me play on my side to see if I can get it working using filter-match.

**Comment by TheSin-** [comment]
yup filter-match fixed it.  Can I set filter-match as the default?

**Comment by Mottie** [comment]
No, you need the class name.... should I add an overall option?

**Comment by TheSin-** [comment]
well that is gonna suck for me, 100s of tables with 10+ cols per table :\  I mean I can do it just sucky job for a changed behaviour without a way to put it back to what it was ;)

**Comment by TheSin-** [comment]
that being said I think it was changed to fix filter-select having filter-match behaviour.  I think I remember when that happened.

**Comment by Mottie** [comment]
Ok, I'll add an option... gimme a min :stuck_out_tongue_closed_eyes:

**Comment by Mottie** [comment]
LOL, ok we'll talk about it some more in chat :wink:
