### ISSUE TITLE
How to sort the 3rd when the table returned sorted by sortList default?

### ISSUE THREAD

**Issue by tanobi92** [Mottie/tablesorter#1171]
My code:
I want to sort the 3rd, the table returned sorted by sortList default:   sortList: [[0, 1]].
now it sort according to the 2nd click.
```
// create
$("#tbInfo").tablesorter({
            // sort default Symbol
            sortList: [[0, 1]],
            sortReset: true,
            //sortRestart: true,
            //sortInitialOrder: 'desc'
        });
// click sort
$("#tbInfo thead tr th").click(function () {
            $("#tbInfo").trigger("update");
        })
```
Help me, please! Thank you very much!

**Comment by Mottie** [comment]
Hi @tanobi92!

I am not sure I understand your question.

Anyway, remove the `// click sort` code because it updates the internal cache, while trying to sort the table on the clicked column. It does not do what you want.

**Comment by tanobi92** [comment]
HI @Mottie! Thank you for answer!
My English is bad. :)
default: sort by sortList (example: [0,1]).
the first: asc(or desc).
the secound: desc (or asc).
the third: default.
It same this website:
https://banggia.vndirect.com.vn/chung-khoan/
You click: menu "HNX" -> click header "Tong KL" three times.
You see: 
+ default: sort by Ma CK.
+ click header "Tong KL" the first: desc.
 click header "Tong KL" the secound: asc.
 click header "Tong KL" the third: default.
Help me, please! Thank!

**Comment by Mottie** [comment]
What is your question?

How to stop the third default?... set the `sortReset` option to `false`, or remove it because it has a default of `false`.

**Comment by tanobi92** [comment]
I set the sortReset option to false, or remove it . But click header the third, it sorting in desc( same the first)

**Comment by Mottie** [comment]
I still don't understand what you want. What do you expect to happen?

**Comment by tanobi92** [comment]
I have 1 list.
When load that list, its default by id and fill in the table. Now I want click on header 1 of column and table get sorted by that rule:
- First click: sort desc.
- Second click: sort asc.
- Third click: no more sort (like when just loaded)
I tried like you help, as do sortReset=False, but when I testing in 3rd click, my table still sort like 1st click
My js:fiddle:
http://jsfiddle.net/TaNoBi/hsxpj0qo/19/
I hope you can understand what I say.

**Comment by Mottie** [comment]
Oh, you want the `sortReset` to be `true` then... sorry for the confusion.

I think it has been working all along. In the demo you linked, you are using Bootstrap v4-alpha and I haven't tested that version yet.

In [this demo](), I added:
* The ["bootstrap" theme](https://github.com/Mottie/tablesorter/blob/master/css/theme.bootstrap.css).
* [`headerTemplate` option](http://mottie.github.io/tablesorter/docs/#headertemplate) needed for bootstrap themes.
* And the ["uitheme" widget](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-uitheme.js), also needed by the bootstrap theme.

```js
$(function() {
  var thUnsort, th, thSort;
  // Loai bo nhung thang nao co colspan >1 k cho sort. VD: du mua, khop lenh, du ban
  //ths = $('#' + tableid + ' thead tr:eq(0) th');
  thUnsort = $('#tbOPB thead tr th[colspan]');
  thSort = $('#tbOPB thead tr th:not([colspan])');
  for (var i = 0; i < thUnsort.length; i++) {
    if (thUnsort[i].colSpan > 1) {
      thUnsort[i].className += ' sorter-false';
      thUnsort[i].style.cursor = 'default';
    } else {

    }
  }
  $('#tbOPB').tablesorter({
    // sort default Symbol
    sortList: [
      [0, 0]
    ],
    sortReset: true,
    theme: 'bootstrap',
    headerTemplate: '{content} {icon}',
    widgets: ['uitheme']
  });
});
```

With the "unsorted" icons showing, you can tell that the sort is reset on the third click.

**Comment by Mottie** [comment]
I'm not sure why the sort arrows aren't showing up... check out [this Bootstrap v3 demo](http://mottie.github.io/tablesorter/docs/example-widget-bootstrap-theme.html).

**Comment by tanobi92** [comment]
@Mottie ! I want  third click to TC: no more sorted by TC, my table sorted by Ma CK  (like when just loaded).

**Comment by Mottie** [comment]
Oops, I meant this demo: http://jsfiddle.net/Mottie/hsxpj0qo/21/

It does not sort the TC column on the third click.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
