### ISSUE TITLE
Add Filter Widget by class not working since update

### ISSUE THREAD

**Issue by megatom** [Mottie/tablesorter#1172]
Hello,
I apply the Filter Widget by adding the class "widget-filter" to all tables that should have the Filter ability.
After updating from 2.18 to 2.25 the Filter Widget is applied but if I type something in the input, nothing is filtered.

**Comment by Mottie** [comment]
Hi @megatom!

It seems to work for me in [this demo](http://jsfiddle.net/Mottie/856bzzeL/911/).

Please make sure that you are loading either the `jquery.tablesorter.widgets.js` or `widget-filter.js` file, and that the "widget-filter" class is added to the table element.

**Comment by megatom** [comment]
html,body{font-size:12px;background-color:#fff;color:#333;font-family:sans-serif,Arial,Verdana,"Trebuchet MS";line-height:1.4;}Hi Rob,

Yes. Your demo is working fine, even with my options. http://jsfiddle.net/856bzzeL/912/
But for example this table do not accept filter: http://www.deine-berge.de/Vergleichstabellen.
Is there a kind of debug to find the error?

Tom

Rob G schrieb am 03.03.2016 17:47:


Hi @megatom!

It seems to work for me in this demo.

Please make sure that you are loading either the jquery.tablesorter.widgets.js or widget-filter.js file, and that the "widget-filter" class is added to the table element.

**Comment by Mottie** [comment]
Ahh, you're using a custom theme... you just need to add a css definition:

```css
.filtered { display: none; }
```

**Comment by Mottie** [comment]
And yes, there is a [`debug` option](http://mottie.github.io/tablesorter/docs/#debug).

**Comment by megatom** [comment]
html,body{font-size:12px;background-color:#fff;color:#333;font-family:sans-serif,Arial,Verdana,"Trebuchet MS";line-height:1.4;}That really was it!
Thank you.
But it must changed since 2.18, because there it works without this css line.

Rob G schrieb am 03.03.2016 18:22:


Ahh, you're using a custom theme... you just need to add a css definition:


.filtered { display: none; }

**Comment by Mottie** [comment]
The change was actually made in 2.19 ([ref](https://github.com/Mottie/tablesorter/commit/11ff8c4ab15c84557688e219a3906b6ac262aa1d))... and I'll add a bunch more alerts in the documentation to make this a bit more obvious.

**Comment by Mottie** [comment]
Ok, hopefully adding more notices will help take care of this issue.
