### ISSUE TITLE
Cannot reset saved filter on page reload

### ISSUE THREAD

**Issue by smartygus** [Mottie/tablesorter#1173]
I like and need the ability to save the filters, so I have the `filter_saveFilters` option set to true in my `widgetOptions`.

But I also need to ability to sometimes reset/remove the saved filters from the storage, just like one can by triggering `saveSortReset`. My scenario is that sometimes I replace the entire table via AJAX (and then re-enable tablesorter), and in that case I want to keep the filter, but when the user triggers a whole page reload, I want to discard any saved filters, and reset to an unfiltered state.

I first tried just triggering `filterReset`, and that seems to clear the filter input field (I'm using a single external search field) okay, but the saved filter was still being applied somehow.

Then I tried to remove the saved filters from storage by myself using:

```javascript
$.tablesorter.storage($('table.filterable'), 'tablesorter-filters', '')
```

but for some reason this doesn't work either; somehow the optioned are still being retrieved and applied to the table, and I don't know how. If I print out the contents of the `tablesorter-filters` storage before and after the above line of code is run, it shows that the history exists before, and after, it is empty, but despite this, when I reload my page, it is still applying the saved filter somehow. If I check the contents of `tablesorter-filters` directly on the javascript console in Chrome after the page and loaded, it shows the saved filters as being there again.

Weirdly, if I run either the command to trigger `filterReset` or the one to clear the `tablesorter-filters` key from storage directly from the javascript console in Chrome, they both seem to work as I would expect, and if I then reload the page, the table is properly unfiltered. But not when I run it from a function in my code (this function runs on the jQuery $(document).ready) event.

Any ideas what could be going on? Perhaps I'm just doing something wrong.

Thanks heaps
Michael

**Comment by Mottie** [comment]
Hi Michael!

That is strange indeed!... I wonder though if there is a `data-value` attribute set in the header cell

```html
<th data-value="blah">Content</th>
```

When the filter widget initializes and there are no set filters, then a `data-value` value will be applied to that column.

Anyway, I'll add a `"filterSavedReset"` trigger which will clear the stored filter values.

**Comment by Mottie** [comment]
In the master branch, the `widget-filter.js` file now includes a "filterResetSaved" method. Please try it out and let me know if it fixes the issues you're having.

**Comment by smartygus** [comment]
Thanks heaps for your amazingly-quick response Rob!

I was using the convenient [gem](https://github.com/themilkman/jquery-tablesorter-rails) from themilkman to add it to the rails asset pipeline, so I had to re-jigger the includes a bit to be able to use the master version of the filter widget instead of that that was bundled with the gem. But I figured it out.

First the bad news: I tried doing what I was doing before, but with the new 'filterResetSaved' trigger, and I still encountered the same problem where the saved filter was still being retrieved from somewhere and being re-applied.

And now the good news: I dug a bit deeper, and with the help of the debug mode, and some debug output of my own I managed to figure out why it was happening. It was (as often seems to be the case in javascript, at least for me anyway :grin:) a problem with the order in which the code was being executed. My call to reset the saved filter data was happening somewhere during the middle of the initialisation of the filter widget.

In the `setDefaults` function in the filter widget, it retrieves the saved filters from storage, and sets the 'lastSearch' data attribute on the table with this info. This data attribute is of course used to filter the table as the initialisation continues. My problem was that I was reseting the storage *after* it had already been loaded into the 'lastSearch' attribute. So it was successfully resetting the storage, but then the table was being filtered using the values from the data attribute, and these values were then in turn being pushed back into the storage :joy: 

It's a bit tricky, because if I understand it correctly, to be able to respond to the 'filterResetSaved' trigger, it first has to be bound to the table, which is done in the beginning of the filter widget initialisation. The call to setDefaults (which pulls the data out of storage and caches it in the data attribute) happens later in the initialisation. So in my case the triggering of the 'filterResetSaved' event needs to happen during the initialisation of the filter widget, after the trigger events have been bound, but before setDefaults has been called.

I have made a change to bind my sort and filter reset code to the 'tablesorter-initialized' event, and this actually seems to work. But I'm not sure if this is just luck :smile:

Can you think of a better way to make this scenario work reliably?

**Comment by Mottie** [comment]
Well, if you don't want to use storage, why not set the [`filter_saveFilters` option](http://mottie.github.io/tablesorter/docs/#widget-filter-savefilters) to `false`?

Otherwise, you could execute this bit of code *before* initializing tablesorter:

```js
$.tablesorter.storage($('table.filterable'), 'tablesorter-filters', '');
```

**Comment by Mottie** [comment]
If you do want to save the filters, but only ignore it in some circumstances, you could set the `filter_saveFilters` to `false`, then set it to `true` after initialization:

```js
$('table').tablesorter({
  // ... other options
  widgetOptions : {
    filter_saveFilters: false
  },
  initialized: function(table) {
    table.config.widgetOptions.filter_saveFilters = true;
  }
});
```

**Comment by smartygus** [comment]
I do use the storage for certain cases, which is why I have it enabled.

But you're right, accessing the tablesorter storage function directly can be done at anytime, and I could do this before initialising anything. I just wasn't sure if this was considered 'stable' in from an API sense. This definitely seems like more of a sure thing in terms of ensuring correct execution though.

Thanks heaps for your help, I really appreciate it!

**Comment by Mottie** [comment]
You're welcome! <img title=":_ happy :" src="https://cloud.githubusercontent.com/assets/136959/13559407/7996bb94-e3d9-11e5-9b36-a39832cd3ceb.gif">

**Comment by smartygus** [comment]
Ok, just some further followup:

As far as I can tell, accessing (or trying to set something in) the $.tablesorter.storage still relies on some of the setup/config that is done in the tablesorter initialisation, so I wasn't able to simply reset the value from storage before even initialising tablesorter (it doesn't throw any errors, it just doesn't seem to do anything).

But your other comment about setting the filter_saveFilters config to false initially gave me an idea on how to make it work as reliably as possible.

What I've done is set the filter_saveFilters option to false in the initialisation parameters when I want to reset the filters, which in turn prevents the filter widget from pulling any saved filter values from the storage during its initialisation, I remove the values from storage myself<sup>1</sup> after tablesorter has finished initialisation, and then I re-enable the filter_saveFilters config option once the 'filterInit' event has fired.

Thanks again :smiley: 

----------

1. I'm doing it 'manually' via the $.tablesorter.storage function at the moment, but once the 'filterResetSaved' trigger is available in the next release and that is propagated into the gem wrapper from themilkman, I'll switch over to that, because I think it's probably cleaner in the long run (thanks for adding it!)

**Comment by Mottie** [comment]
Version 2.25.6 is now available.
