### ISSUE TITLE
Pager misbehaviour when dynamically adding rows

### ISSUE THREAD

**Issue by DaveGahan** [Mottie/tablesorter#1176]
Hi !

I'm trying to dynamically add rows to an empty tablesorter (with a 25 rows sized pager).

Everything works fine when pager is not enabled.

Otherwise, first pages are empty, one is a third loaded and last ones are correct.

Here's the code I use :

![image](https://cloud.githubusercontent.com/assets/12768499/13643625/1011d744-e622-11e5-9e3d-4fa9c6edf9f0.png)

And that is the resut : 

![1](https://cloud.githubusercontent.com/assets/12768499/13643786/cdf25b6c-e622-11e5-8bef-242332ee4e58.jpg)
![2](https://cloud.githubusercontent.com/assets/12768499/13643795/d2400a8e-e622-11e5-8734-f2b64e57c6bc.jpg)
![3](https://cloud.githubusercontent.com/assets/12768499/13643799/d59ca12e-e622-11e5-9b55-ed28ed321ce2.jpg)
![4](https://cloud.githubusercontent.com/assets/12768499/13643801/d901cfe2-e622-11e5-9778-66a73dbdcd1b.jpg)

Any idea ?

Thanks.

PS: I'm using last version.

**Comment by Mottie** [comment]
Hi @DaveGahan!

I think the issue might be that tablesorter and the pager need to be initialized outside of that ajax function, that is if that code gets executed more than once.

So do something like this:

```js
var $table = $('#ecritures')
  .tablesorter({ /* options */ })
  .tablesorterPager({ /* options */ }),

  config = $table.data('tablesorter');

function getRows(url, urldata) {
  $.get(
    url,
    urldata,
    function(data) {
      var row = '';
      // process data
      $.tablesorter.addRows( config, row, true );
    }
}
```

**Comment by Mottie** [comment]
Here is [a demo](http://jsfiddle.net/Mottie/1a5yu8yq/115/)

**Comment by DaveGahan** [comment]
Hi Mottie. 

I just figured out there is a missing "/" in each row closure.

![36617827](https://cloud.githubusercontent.com/assets/12768499/13669109/95f8a640-e6c1-11e5-979f-12d8a2f1d2cc.jpg)

Anyway, I putted tablesorter init away from ajax request. It's way cleaner like that.

Now I'm trying to clear all rows before displaying new ones.

Thanks again, keep on this great work :-)
