### ISSUE TITLE
Uncaught TypeError: $(...).tablesorter(...) is not a function

### ISSUE THREAD

**Issue by yao23** [Mottie/tablesorter#1179]
html code:

    script(type='text/javascript' src='/js/jquery/jquery-latest.js')
    script(type='text/javascript' src='/js/jquery/jquery_tablesorter.js')

main.js code:

    $(document).ready(function() {
       $('#target_table').tablesorter();
    });

I can console.log($('#target_table').attr('class')) and get 'tablesorter' but it complains error as title when $('#target_table').tablesorter(); The table has thead and tbody tags and it loads jQuery and tablesorter library correctly as inspect element shows. Actually I tried to use tablesorter library and it works in Google App Engine but Keystone framework. Is there anyone having similar issue before?

Chrome console log:

    Uncaught TypeError: $(...).tablesorter is not a function                    main.js:2 
    (anonymous function)	@	main.js:2
    c.extend.ready	        @	jquery-latest.js:26
    L	                    @	jquery-latest.js:33

**Comment by Mottie** [comment]
Hi @yao23!

Whenever I see this error: `$(...).tablesorter is not a function` it makes me think that more than one copy of jQuery is being loaded on the page. Please make sure that only one copy of jQuery is loaded.

**Comment by yao23** [comment]
Hi @Mottie ,

I did load jQuery once, if commented the line for latest jQuery library code, it complains:

    Uncaught ReferenceError: jQuery is not defined(anonymous function) @ jquery_tablesorter.js:1046
    Uncaught ReferenceError: $ is not defined main.js:1

There should be some other reason, thanks still.

**Comment by Mottie** [comment]
Are you using a `noConflict()` somewhere?

Would you share a bit more of your code? If you have a page online, it would make it easier for me to help troubleshoot if I could see the problem... It still sounds like there is a loading issue.

**Comment by yao23** [comment]
You are right, I use Keystone framework which loads another jQuery copy in the footer section after check Network status with inspect in Chrome. It works perfect after delete the line of include jQuery code. Thanks a lot. @Mottie

**Comment by Carolinercraig** [comment]
This thread helped me to investigate what was happening. Maybe this helps others. I had the same issue, my table were rendered from a database and so I added the noConflict function right before the tablesorter() call and it finally worked! https://api.jquery.com/jquery.noconflict/
