### ISSUE TITLE
Filtering does not work with delayInit until click on header

### ISSUE THREAD

**Issue by mcd-php** [Mottie/tablesorter#1180]
https://jsfiddle.net/083605ay/

Expected: Click on either input for search will trigger init, any activity will work.
Fact: Typing into input does nothing, until click on any column header.

P.S.
1. I can't remove delayInit, since my data are loaded by AJAX in N+1 way for heavy caching and offloading work to client.
2. Until proper fix, please tell me how can I trigger init by click on filter input from external code (in jsfiddle ?).

**Comment by Mottie** [comment]
Hi @mcd-php!

Thanks for reporting this issue. It looks like it is currently set to only update the cache after filtering if you use the pager addon/widget... I'll fix that issue shortly.

**Comment by Mottie** [comment]
Ok, all fixed and a new version is available... [this demo](https://jsfiddle.net/083605ay/1/) points to the files available on GitHub's gh-pages, becuase CDNJS hasn't updated just yet.

**Comment by mcd-php** [comment]
Thanks a lot ! Works, CDN updated, demo updated to CDN: https://jsfiddle.net/083605ay/2/
