### ISSUE TITLE
Filter event after setting initial filter?

### ISSUE THREAD

**Issue by mikeahmarani** [Mottie/tablesorter#1181]
filterInit, filterStart, filterEnd all fire BEFORE the data-value attribute sets the initial filter. Is there an event that fires after this so I can do something with the filtered rows?

**Comment by Mottie** [comment]
Hi @mikeahmarani!

Did you find your answer?

**Comment by mikeahmarani** [comment]
@Mottie 

Yeah I did, thanks Rob. Great fork!
