### ISSUE TITLE
How to add a button to the filter row?

### ISSUE THREAD

**Issue by xiao0720** [Mottie/tablesorter#1182]
Hi, I want to put a button element into the filter row, tried different methods but still haven't got a working code. Could you please help. Many thanks :)
![screen](https://cloud.githubusercontent.com/assets/9721723/13950391/9c2a6e9e-f022-11e5-927d-93cd1946bd79.png)

**Comment by Mottie** [comment]
Hi @xiao0720!

Use the [`filterInit` event](http://mottie.github.io/tablesorter/docs/#filterinit) to target the filter cell & add the button. I left the button alignment and styling up to you in [this demo](http://jsfiddle.net/856bzzeL/963/):

```js
$(function() {
  $('table')
    .on('filterInit', function() {
      var c = this.config,
        $button = $('<button type="button">Add Student</button>').on('click', function() {
          alert('open popup');
        })
      c.$filters.eq(0).append($button);
    })
    .tablesorter({
      theme: 'blue',
      widgets: ['zebra', 'filter']
    });
});
```

**Comment by xiao0720** [comment]
Works for me, many thanks Mottie. 👍
