### ISSUE TITLE
Dynamic correction of the table size

### ISSUE THREAD

**Issue by TomFly74** [Mottie/tablesorter#1183]
Hello !
sorry for my English :)
If using a dynamic table width, I suggest to add these following lines in the file "jquery.tablesorter.widgets.js" @lines: 2451 ( Widget: stickyHeaders - updated 3/1/2016 (v2.25.5) )
Code:
        //resize row sticky Header Dynamical
	$table.resize(function() {
	    resizeHeader();
	});

if corrects the bug on "sticky header" who do not take all size table in case of dynamic expansion of the table such as the expansion of the table by a cursor (col-cursor) to the "div" that contains the table.

Here the bug picture:
![bug tablesorter](https://cloud.githubusercontent.com/assets/18016994/13972136/5abda70e-f096-11e5-9b06-6e1d9a23b5d9.jpg)

Here the image of the correction "sticky header":
![bug tablesorter -correction](https://cloud.githubusercontent.com/assets/18016994/13972355/3dc55456-f098-11e5-95e6-9fb8f7db3431.jpg)

TomFly74

**Comment by Mottie** [comment]
Hi @TomFly74!

Thanks for reporting this problem! What line number would that be in the [`widget-stickyHeaders.js` file](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-stickyHeaders.js)?

Do you know Git well enough to provide a pull request?

**Comment by TomFly74** [comment]
Hi @Mottie !

The line number in the file "widget-sticky Headers.js" is 268 (addition of code).

No, I do not think it useful;)
unless this feature could be more fluid because it changes in spurts,

**Comment by Mottie** [comment]
Oh, last thing. Would you set up a demo (modify [this one](http://jsfiddle.net/Mottie/f36416oy/)), so I can test the change to make sure it is fixed? Thanks!

**Comment by TomFly74** [comment]
without modification:
http://jsfiddle.net/TomFly74/f36416oy/18/
Try to move the cursor:
![bug tabl js](https://cloud.githubusercontent.com/assets/18016994/13986616/b0768bf8-f103-11e5-87b7-80a37c59a889.jpg)

With the modification
http://jsfiddle.net/TomFly74/f36416oy/20/

**Comment by Mottie** [comment]
Ok, thanks again for your help! The fix is currently only available in the master branch. I'm not sure yet when the next version will be released.

**Comment by Mottie** [comment]
A new release is now available!
