### ISSUE TITLE
Problem with trigger("updateAll")

### ISSUE THREAD

**Issue by TomFly74** [Mottie/tablesorter#1184]
Hi,
My problem is when I use the code to update the table, everything works well,
```js
function updateTable( ){					
	var resort = true,
	  // add a callback, as desired
	  callback = function(table){
		alert('table updated!');
	  }

	// let the plugin know that we made a update, then the plugin will
	// automatically sort the table based on the header settings
	$("table").trigger("updateAll", [ resort, callback ]);
};
```

But when I comment the line or I remove the "alert('table updated!')", it not update the table  ?!

**Comment by Mottie** [comment]
Hi @TomFly74!

First off, make sure you are only using `updateAll` if the `thead` *and* `tbody` content has changed. Use `update` if only the `tbody` content has changed.

Please elaborate on what you mean by the table is not updated. Would you provide a demo of this problem?

**Comment by TomFly74** [comment]
The demo would be too complicated :/

the table that updates via an ajax call : the content is present.
`//ajax
				//requête ajax, appel du fichier recherche.php
				$.ajax({
					type: "GET",
					url: "modules/document/fonctions/refreshExplorer.php?"+val_getURL,
					dataType : "html",
					//affichage de l'erreur en cas de problème
					error:function(msg, string){
						alert( "Error !: " + string );
					},
					success:function(data){
						//alert(data);
						//on met à jour le div zone_de_rechargement avec les données reçus
						//on vide la div et on le cache
						//$(".dossier_explorer").empty().hide();
						//on affecte les resultats au div
						//$(".dossier_explorer").html(data);
						
					
						$( 'table#tablFolder tbody' ).append( data );
					
						//updateTable();
							//recup contenu
					
						//on affiche les resultats avec la transition
							$( 'table#tablFolder ' ).fadeIn(2000);
					
					}
				});
`
 However all the widgets are not rechager (only resize widget ) : Zebra, shorts, checkbox...
Without "alert()" in  callback = function(table): 
![alert_sans](https://cloud.githubusercontent.com/assets/18016994/13994399/d6f2ba56-f124-11e5-9756-27639e97370b.jpg)

Witch "alert()" in  callback = function(table) : all widget is ok
![alert_avec](https://cloud.githubusercontent.com/assets/18016994/13994362/b7574ff4-f124-11e5-80fc-22441dfa56ba.jpg)

I have changed updateAll by update but always the same worries!

**Comment by Mottie** [comment]
Try this instead:

```js
 $( 'table#tablFolder tbody' )
    .append( data )
    .trigger('update');
```

The [`resort` option](http://mottie.github.io/tablesorter/docs/#resort) is set to `true` by default, so you don't need to include it or the callback.

**Comment by TomFly74** [comment]
No change :/

**Comment by Mottie** [comment]
Set the [`debug` option](http://mottie.github.io/tablesorter/docs/#debug) to `true` and please share with me the console output *after* the ajax call.

**Comment by TomFly74** [comment]
`Initializing tablesorter jquery.tablesorter.js:235
Built headers: ( 10ms ) jquery.tablesorter.js:616:1
Object { length: 6, 6 de plus… } jquery.tablesorter.js:617:5
Detecting parsers for each column jquery.tablesorter.js:647
  No parsers detected! jquery.tablesorter.js:717:6
Completed detecting parsers ( 1ms ) jquery.tablesorter.js:719:1
Building cache for 0 rows (showing 0 rows in log) ( 0ms ) jquery.tablesorter.js:968
console.table(): jquery.tablesorter.js:980

Start initializing widgets jquery.tablesorter.js:1993
Initializing resizable widget jquery.tablesorter.js:1933
Completed initializing resizable widget ( 15ms ) jquery.tablesorter.js:1947:1
Completed initializing 3 widgets ( 17ms ) jquery.tablesorter.js:2014:1
Start applying widgets jquery.tablesorter.js:1993
Updating stickyHeaders widget jquery.tablesorter.js:1941
Completed applying stickyHeaders widget ( 7ms ) jquery.tablesorter.js:1947:1
Updating zebra widget jquery.tablesorter.js:1941
Completed applying zebra widget ( 1ms ) jquery.tablesorter.js:1947:1
Completed applying 3 widgets ( 10ms ) jquery.tablesorter.js:2014:1
Overall initialization time:  ( 53ms ) jquery.tablesorter.js:337:1
`

**Comment by Mottie** [comment]
That is telling me that no parsers are detected, so it's not finding the rows in the tbody. What does the data returned from the ajax success look like? The way the code is adding it, it would have to be an HTML string of rows e.g. `"<tr><td><input type="checkbox"></td><td>...</td></tr><tr>...</tr>'`

**Comment by TomFly74** [comment]
However here is the result of ajax 'console.log(data)':
`

							<tr  id="ligne_0" style="height:50px;" >
					<td style="text-align:center;"  >
						<INPUT type="checkbox" name="radio_select" name="0" id="0" value="0"  >
					
					</td>
					<td  style="text-align:center;"  >
													<a href="?ftp=COMPTABILITE/2015 - Exercice 1/" class="href_dossier_liste_img">
									<img src="modules/document/images/ico/folder.png" style="max-width:30px; max-height:30px" border="0" >
								</a>
												</td>
					<td  >
														<a href="?ftp=COMPTABILITE/2015 - Exercice 1/" class="href_dossier_liste_nom">
									2015 - Exercice 1								</a>
													
											</td>
					<td  style="text-align:center">
						0,0 B					</td>
					<td   style="text-align:center">
							2016/03/22 18:32:17					</td>
					<td  >
						I/O
					</td>
					
								<tr  id="ligne_1" style="height:50px;" >
					<td style="text-align:center;"  >
						<INPUT type="checkbox" name="radio_select" name="1" id="1" value="1"  >
					
					</td>
					<td  style="text-align:center;"  >
													<a href="?ftp=COMPTABILITE/2016 - Exercice 1/" class="href_dossier_liste_img">
									<img src="modules/document/images/ico/folder.png" style="max-width:30px; max-height:30px" border="0" >
								</a>
												</td>
					<td  >
														<a href="?ftp=COMPTABILITE/2016 - Exercice 1/" class="href_dossier_liste_nom">
									2016 - Exercice 1								</a>
													
											</td>
					<td  style="text-align:center">
						0,0 B					</td>
					<td   style="text-align:center">
							2016/03/21 19:23:46					</td>
					<td  >
						I/O
					</td>
					
								<tr  id="tbl_nofound" style="display:none;"  > 
					<td  colspan="8">
						
					</td>
				</tr>
`

**Comment by TomFly74** [comment]
It works!

I modify:
jQuery.noConflict();
jQuery("table").trigger("update");

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by iryanjan18** [comment]
I have problem also with trigger `updateAll` since it's not updating the data. I'm using the `ajaxProcessing` and when I add a record I would want to reload the table data. How to properly fetch new data and reload to table?

```
$('#documentsTable').tablesorter({
			sortLocaleCompare: true,
			headerTemplate: '{content} {icon}',
			showProcessing: true,
			theme: 'bootstrap',
			widthFixed: true,
			fixColumnWidth: true,
			widgets: ['filter', 'uitheme', 'columns', 'zebra'],
			widgetOptions: {
				zebra: ['even', 'odd'],
				columns: ['primary', 'secondary', 'tertiary'],
				filter_serversideFiltering: true,
				filter_reset: '.reset',
				filter_cssFilter: 'form-control'
			}
		})
		.tablesorterPager({
			container: $(".ts-pager"),
			cssGoto  : ".pagenum",
			removeRows: true,
			output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
			processAjaxOnInit: true,
			updateArrows: true,
			page: 0,
			pageReset: 0,
			size: 10,
			savePages: true,
			ajaxObject: { type: 'get', dataType: 'json' },
			ajaxError: null,
			ajaxUrl: 'get_data?page={page}&size={size}&{filterList:filter}&{sortList:column}',
			ajaxProcessing: function(data) {
				var total, rows;
				total = data.total;
				rows = data.rows;
                                 // more data
				});
				return [ total, rows ];
			}
		});

// refresh table
function reloadTable() { $("#documentsTable").trigger("updateAll"); }
$('#refresh-btn').on('click', function() { reloadTable(); });
```
