### ISSUE TITLE
British Date Format - not sorting properly

### ISSUE THREAD

**Issue by noggie108** [Mottie/tablesorter#1185]
Hi

I'm using Tablesorter but I cant seem to sort me table by the british date format:

31-Feb-2016
01-Mar-2016
10-Mar-2016

How can I implement this? 

thanks in advance

**Comment by Mottie** [comment]
Hi @noggie108!
Wow, British have 31 days in February?!  Shows how far behind us yanks are... <img title=":_tuzki_teehee:" src="https://cloud.githubusercontent.com/assets/136959/13203716/665ac5c2-d883-11e5-87ef-bbb0be4e1d81.gif"> 

Anyway, you'll need a custom parser since a date with dashes (`-`) won't parse in Firefox ([demo](http://jsfiddle.net/856bzzeL/970/))

```js
$(function() {

  $.tablesorter.addParser({
    // set a unique id
    id: 'special-date',
    is: function() {
      return false;
    },
    format: function(str) {
      // replace the dash in the date with a space
      var date = new Date(str.replace(/-/g, ' '));
      return date instanceof Date && isFinite(date) ? date.getTime() : str;
    },
    // set type, either numeric or text
    type: 'numeric'
  });

  $('table').tablesorter({
    debug: true,
    theme: 'blue',
    widgets: ['zebra']
  });

});
```

**Comment by noggie108** [comment]
Hi Rob

Yeah my bad about 31 days in Feb.... :-(

Anyway it still only seems to sort by the first numeric value and not by the entire date e.g.

01-Mar-2016
02-Jun-2016
03-Jan-2016

I was hoping to get it to sort like (or descending):
03-Jan-2016
01-Mar-2016
02-Jun-2016

**Comment by Mottie** [comment]
The "special-date" parser I shared above is working for me on Chrome and Firefox. Are you seeing that it isn't working in a particular browser?

**Comment by noggie108** [comment]
It was me being stupid (for the second time :-( )

I owe you a beer

**Comment by Mottie** [comment]
LOL no worries!
