### ISSUE TITLE
print widget with child rows

### ISSUE THREAD

**Issue by hosamalzagh** [Mottie/tablesorter#1188]
I use tablesorter with print widget and child rows

all my child rows are hidden and I have a "show details" link in each row to show the child row for this row only

but print widget print all child rows not only the expanded one

is there something I missed or a class to use to only print shown child rows

thank you

**Comment by Mottie** [comment]
Hi @hosamalzagh!

What is the [`print_rows` option](http://mottie.github.io/tablesorter/docs/example-widget-print.html#print_rows) setting? If set to `"all"` it will print everything. By default, it is set to `"f"` to only print filtered rows ([demo](https://jsfiddle.net/Mottie/bdddtbts/4/))

If you are using different class names or method of showing/hiding child rows, the `print_rows` option can also be set as a row selector, e.g.

```js
print_rows : ":not(.filtered):not(.tablesorter-childRow)"
```

This setting would create the following css definition in the print popup window:

```css
tbody tr:not(.filtered):not(.tablesorter-childRow) { display: table-row !important; }
```

If none of that helps, please share an example of the HTML and javascript. Ideally, please modify the demo to show the problem to make it easier for me to troubleshoot. Thanks!

**Comment by hosamalzagh** [comment]
thank you 
this helps me a lot

I was using a custom class to hide child rows and that was the problem

thanks again and good luck
