### ISSUE TITLE
sorter-false for bootstrap themes

### ISSUE THREAD

**Issue by lesilent** [Mottie/tablesorter#1189]
It appears that the css for the bootstrap themes are missing the lines to set the cursor to default when sorting is disabled on a column. I think the following lines need to be added:

.tablesorter-bootstrap thead .sorter-false {
	cursor: default;
}

**Comment by Mottie** [comment]
Hi @lesilent!

Thanks for letting me know! I'll have this fixed in the next update.

**Comment by Mottie** [comment]
[demo](http://jsfiddle.net/Mottie/njj5b5vc/68/)
