### ISSUE TITLE
Dropbox theme has no arrows

### ISSUE THREAD

**Issue by sowinski** [Mottie/tablesorter#1190]
Hi,

the dropbox theme doesn't show any arrows. 
To reproduce the error download the last zip. Open index.html and replace:
`<link href="dist/css/theme.default.min.css" rel="stylesheet">`
with
`<link href="dist/css/theme.dropbox.min.css" rel="stylesheet">`
and add to tablesorter theme : 'dropbox'
`	$(function(){
		$('table').tablesorter({
			theme 	       : 'dropbox',
			widgets        : ['zebra', 'columns'],
			usNumberFormat : false,
			sortReset      : true,
			sortRestart    : true
		});
	});`

Is there any workaround to fix this issue?

Thank you :)

**Comment by Mottie** [comment]
Hi @sowinski!

The dropbox theme needs a [`headerTemplate` setting](http://mottie.github.io/tablesorter/docs/#headertemplate) that includes an `{icon}` ([demo](http://jsfiddle.net/Mottie/856bzzeL/1000/)):

```js
$(function () {
  $('table').tablesorter({
    theme: 'dropbox',
    // dropbox theme doesn't like a space between the content & icon
    headerTemplate: '{content}{icon}',
    sortList: [[0,0]],
    widgets: ['zebra', 'columns']
  });
});
```

**Comment by sowinski** [comment]
Thank you!
