### ISSUE TITLE
Custom table row output when using ajaxProcessing

### ISSUE THREAD

**Issue by lurajon** [Mottie/tablesorter#1192]
Hi,
I need to add custom class attribute to each table row when in the ajaxProcessing function in the tablesorterPager widget.

I am using this code;

```js
ajaxProcessing: function(data){
        if (data && data.hasOwnProperty('rows')) {
          var indx, r, row, c, d = data.rows,
          // total number of rows (required)
          total = data.total_rows,
          // array of header names (optional)
          headers = data.headers,
          // cross-reference to match JSON key within data (no spaces)
          headerXref = headers.join(',').replace(/\s+/g,'').split(','),
          // all rows: array of arrays; each internal array has the table cell data for that row
          rows = [],
          // len should match pager set size (c.size)
          len = d.length;
          // this will depend on how the json is set up - see City0.json
          // rows
          for ( r=0; r < len; r++ ) {
             ...
            rows.push(row); // add new row array to rows array
          }
          // in version 2.10, you can optionally return $(rows) a set of table rows within a jQuery object
         return [ total, rows, headers ];
    }
  },
```
which outputs 

```html
<tr><td>..</td><td>...</td></tr>
```

I would like to add class and/or id attributes for each such as;

```html
<tr class="row-'+ data.rows[i].value +'"><td>..</td><td>...</td></tr>
```

Is this possible? I could not find any hints in the API.

Best regards,

Jone

**Comment by Mottie** [comment]
Hi @lurajon!

Check out the documentation for the `ajaxProcessing` function... there is an example there for returning an "[array (rows as jQuery object)](http://mottie.github.io/tablesorter/docs/#array_rows_as_jquery_object)" in which the rows are built as an HTML string. Please let me know if you get stuck or need help.

**Comment by lurajon** [comment]
Sweet!

Exactly what I was looking for! Sorry that I missed it from the documentation.

My rows now have the classes I need. 

Thank you.
