### ISSUE TITLE
Reset Filters and return to Default Sort order

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1193]
I opened this on stackoverflow, but I wanted to make sure it was noticed.

I've successfully reset filters with the filterReset trigger. I've tried every sort of option to resort to the default sorting following the docs on the website, here, but it is of no use. I've tried sortReset, sortRestart, and others, but nothing gets me back to my default sort order. What I need is a "reset" button that returns the table to it's initial state (sortList intact and filters reset.) Help me Obi-wan-Mottie, you're my only hope!

This is what I have, which is not working for the sorting, but is at least resetting the filters.
HTML:` <a href="#" id="reset-link">reset</a>`

JavaScript:
```
$('#reset-link').click(function(){
    $('#mytable').trigger('sortRestart').trigger('filterReset');
    return false;
});
```

**Comment by Mottie** [comment]
Hi @aetna-wsa!

I [replied yesterday](http://stackoverflow.com/a/36698995/145346)...

Reverse the order of the triggers ([demo](http://jsfiddle.net/Mottie/856bzzeL/1005/))

```js
$(function() {
  var $table = $('#mytable');
  $('#reset-link').click(function() {
    $table.trigger('filterReset').trigger('sortReset');
    return false;
  });
  $table.tablesorter({
    theme: 'blue',
    sortList: [[0, 0], [1, 0], [2, 0]],
    widgets: ['filter', 'zebra']
  });
});
```

**Comment by aetna-wsa** [comment]
Sorry I missed that. Thank you so much!

**Comment by Mottie** [comment]
No problem! :grin:
