### ISSUE TITLE
Sort on numeric select list (dropdown) values

### ISSUE THREAD

**Issue by scotself** [Mottie/tablesorter#1194]
I have looked a good bit in closed issues and such to see if perhaps it's my implementation or if I could find a clue, but I don't seem to be able to get this right. I can set "sorter" : "select" as part of my config and set it for the column containing a select list of numeric values (1-30), but when we sort, it is sorting like this:
1
1
10
11
2
22
3
...

Any recommendations on how to get this to do a true numeric sort on the current value of the selected option in the dropdown of each row? Thank you for such a wonderful contribution. I could have never pulled something like this off myself. Bravo.

**Comment by Mottie** [comment]
Hi @scotself!

I'm glad you're finding this fork useful :grinning: 

First, make sure that the [`parser-input-select.js` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) is being loaded. Then add a `"sorter-select"` class name to the header for the select column ([demo](http://jsfiddle.net/Mottie/856bzzeL/1008/)):

```html
<table class="tablesorter">
  <thead>
    <tr>
      <th>Name</th>
      <th class="sorter-select">Value</th>
    </tr>
  </thead>
  <tbody>
    ...
  </tbody>
</table>
```

If you ever find that you need use additional processing, like parse a date or currency value inside a select, use `"extractor-select"` then `"sorter-date"`, or whatever. The "extractor" method will grab the raw data, like from a select or input, and the "sorter" will parse the data. See [this demo](http://mottie.github.io/tablesorter/docs/example-extractors-parsers.html) for an example.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by scotself** [comment]
Sorry, took me a while to get back to testing this. The sorting is working, but just not using numeric values to sort properly as in the OP. I can click the header to sort, but it wants to sort as if the numbers are text. I tried setting extractor : "select", sorter : "number" (along with "numeric", and "integer", wasn't sure which it should be and couldn't find in docs), but those never worked. Only sorter : "select" ever worked for me, but only treating the numbers as text, so I get 1, 11, 12, 2, 3, etc...here's the actual code I have now.

`
      $('#group-assignment').tablesorter({
        headers: {4: { extractor: "select", sorter: "number"}},
        sortList: [[4,0]],
      });
`

Appreciate any assistance!

**Comment by Mottie** [comment]
Would you please modify [this demo](http://jsfiddle.net/Mottie/bbxxomhx/12/) to show me the issue you're having.

**Comment by scotself** [comment]
Wow. I'm so sorry, but it seems I somehow got an old version of the code. I grabbed a fresh, un-minified version of the latest of the tablesorter as well as the select parser file and it works a treat. The fiddle certainly helped me realize it HAD to be something on my side, though, so thanks! 👍

**Comment by Mottie** [comment]
No worries! I'm glad you found the problem :smile:
