### ISSUE TITLE
'applyWidgetId' not working as expected for 'filter'

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1197]
Hi,

I try to add the "filter" widget to an existing tablesorter using "applyWidgetId" but it doesn't work as expected. "filter_initialized" (and others) won't be set.
Example: http://jsfiddle.net/amair/my0xjf1c/

It works if I use `widgets: ['zebra', 'filter'],` and remove the `removeWidget` and `applyWidgetId` calls.

Any idea what's wrong here?

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Hmm, that is odd. It *looks* like the filter widget is initializing properly, but it isn't... I'll try to look into this issue when I get some free time.
