### ISSUE TITLE
columnSelector not updating popup content when saving selection

### ISSUE THREAD

**Issue by csebe** [Mottie/tablesorter#1198]
Hi,

Incredible useful library and plugins, thank you very much for all!

I have the following issue:
I initialize the tablesorter and the columnSelector widget as follows:

```js   
$(document).ready(function() {
        $('#bigsortable').tablesorter({
            theme: 'default',
            widgets : ['stickyHeaders','filter','saveSort','columnSelector'],
            widgetOptions : {
[...]
                columnSelector_saveColumns: true,               
                columnSelector_mediaqueryState: false,
                columnSelector_mediaqueryName: 'All columns',
                columnSelector_columns : {
                    0 : "disable",
                    1 : "disable",
                    2 : "disable",
                    3: true,
                    4: true,
                    5: true,
                    6: false,
                    7: false,
                    8: false,
                    9: true,
                    10: true,
                    11: false,
                    12: false,
                    13: "disable"
                }
            }
});
```

My purpose is to save user columns' selection between refreshes (hence the columnSelector_saveColumns : true) and to allow them to manually reset to the initial layout using a "Reset" button. FOr the reset part I use this code:
```js
$('#bigsortable').trigger('refreshColumnSelector',[ 'selectors', [3,4,5,9,10] ]);
```

As long as columnSelector_saveColumns is on false, it works great!
But if I put it on true the behaviour is like this:
The columns update in the table according to columnSelector_columns definition above, so reset works on the table, but the checkboxes in the popover do not update corespondingly (and remain on what was saved before). Consequently, when refreshing the page, the popover content and the columns in the table sync again, but again as it was saved before and not in the "initial" mode.

I would appreciate any help,

Thanks in advance,

Lian

**Comment by Mottie** [comment]
Hi @csebe!

Yes, you're right. It isn't updating the stored values as it should. I'll look into fixing this issue when I get some free time.

**Comment by Mottie** [comment]
This issue has been fixed in the latest release!

**Comment by csebe** [comment]
Thank you very much for the prompt fix!
I'll give it a try!
All the bests,
Lian
