### ISSUE TITLE
Checkboxes not changing based on global "select all" checkbox

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1199]
When clicking on the 'Select All' checkbox in the header of the table, it correctly checks all those below it. When deselecting a couple of those checkboxes, again the global checkbox is displayed correctly by changing its appearance (different look, based on browser.) 

However, I would expect the behavior to be that all checkboxes would be selected once again if I click the 'Select All' box again. But, this is not the case. Instead, it appears nothing has changed (all the same boxes are checked from before, and the ones I manually deselected are empty.) If I click the 'Select All' box again, it clears all the checks below it (which would make sense had the previous click selected all again.)

Any ideas? I'm using IE11

**Comment by Mottie** [comment]
Hi @aetna-wsa!

Odd, I was just looking at [this demo](http://jsfiddle.net/Mottie/y5dmhybr/) which I know was working perfectly before; but now it seems that the header checkbox isn't behaving.

I'll try to look into this problem and look to address your issue when I get some free time.

**Comment by Mottie** [comment]
Please try the updated `parser-input-select.js` available in the master branch. Hopefully it is behaving as you expect.

**Comment by aetna-wsa** [comment]
Unfortunately, no, it is not working. I made a jsfiddle, which I could see in Firefox, but not in IE (which is where the problem is) to see if it would help you: https://jsfiddle.net/e0027jq1/3/

**Comment by Mottie** [comment]
Oh, the problem is in IE...

I found out there is a problem with indeterminate checkboxes in IE ([bug reported](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/7344418/)), so the code now listens for a "click" instead of only a "change" event, and sets the correct `checked` state of the indeterminate checkbox.

Please try [this updated demo](https://jsfiddle.net/Mottie/e0027jq1/5/).

**Comment by Mottie** [comment]
Ugh, one more fix because IE is being IE...

**Comment by aetna-wsa** [comment]
Perfect -- looks like you nailed it! (Not knowing what the second "ugh" is about, though.) Will IE *ever* stop being a thorn in our collective sides?

**Comment by Mottie** [comment]
A new release is available!
