### ISSUE TITLE
Multiline caption in the table with fixed column

### ISSUE THREAD

**Issue by max5555** [Mottie/tablesorter#1202]
There is a problem with fixed column vertical position: http://jsfiddle.net/max5555/hyw5nz30/

**Comment by Mottie** [comment]
Hi @max5555!

Thanks for reporting this issue. I'll get it fixed soon!

**Comment by Mottie** [comment]
There is an update available for the scroller widget in the master branch. Once I get a few more bugs closed, I'll release the next version.
