### ISSUE TITLE
Pager reset issue

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1203]
I'm still on IE with another issue. When I navigate to another page with the pager widget (e.g. results 11-20) and then navigate away from the page, the page number is getting saved. When I navigate away and return, I'd expect the pagination to start on page 1 again (e.g. results 1-10) but instead it is coming back to the page it was on before navigating away.

How do I force the pager widget to "reset" upon loading the page again?

**Comment by Mottie** [comment]
If you don't want the pager to "remember" the last page, set the [`savePages` option](http://mottie.github.io/tablesorter/docs/#save-pages) to `false`.

**Comment by aetna-wsa** [comment]
Perfect, thank you Rob! (I apologize for not locating this -- this is a massive library with a ton of documentation. Both are phenomenal, I just don't always find what I'm looking for. :)
