### ISSUE TITLE
Multiline caption in the table with stickyHeaders_includeCaption : false

### ISSUE THREAD

**Issue by max5555** [Mottie/tablesorter#1205]
Two headers appear in the case of multiline caption and `stickyHeaders_includeCaption : false`. See [Screenshot](https://nimbus.everhelper.me/client/notes/share/458713/v2w4alxk7ioqtw8xgolx) and [demo](http://jsfiddle.net/max5555/0vuntdnL/).

**Comment by Mottie** [comment]
Hi @max5555!

Thanks for reporting this issue! I'll have it fixed in the master branch shortly.

**Comment by Mottie** [comment]
Once the raw git version updates, you can try the changes in [this demo](http://jsfiddle.net/Mottie/f36416oy/23/).

**Comment by max5555** [comment]
Adding http://mottie.github.com/tablesorter/js/jquery.tablesorter.widgets.js brakes the fix. Compare [workin](http://jsfiddle.net/max5555/0vuntdnL/8/) [not working](http://jsfiddle.net/max5555/0vuntdnL/7/).

**Comment by Mottie** [comment]
So far, I've only updated the `widget-stickyHeaders.js` and dist folder `widget-stickyHeaders.min.js` files. The `jquery.tablesorter.widgets.js` file usually only gets updated when a new release is available.
