### ISSUE TITLE
group-text doesn't handle "<" and ">"

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1206]
Hi,

if I use "group-text" for a column that contains cells having "<" or ">" in them like `"My Self <email address>"` the group header looses the "<...>" part.

Best regards
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Would you please modify [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/) to provide an example of the problem? Thanks!

**Comment by a-mair** [comment]
Group by "animals" and you'll see that the "Aardvark" header looses "<test>".

**Comment by Mottie** [comment]
Please provide a link to the demo.

**Comment by a-mair** [comment]
Sorry, I thought modifying and updating your demo would be enough: http://jsfiddle.net/4ac5kr3o/27/

**Comment by Mottie** [comment]
The fix is now available in the master branch in the `widget-grouping.js` and the dist `widget-grouping.min.js` files.

Here is an [updated demo](http://jsfiddle.net/Mottie/4ac5kr3o/28/) which might take a few minutes to update the file.

**Comment by a-mair** [comment]
Hi,

thanks for fixing the problem, but I think
`var name = data.currentGroup.replace(/</g, '&lt;').replace(/>/g, '&gt');`
should be
`var name = data.currentGroup.replace(/</g, '&lt;').replace(/>/g, '&gt;');`
 (`&gt` replaced by `&gt;`)

I also noticed that I now get this error: `TypeError: data.currentGroup.replace is not a function`

Regards,
Andreas

**Comment by Mottie** [comment]
Thanks! Everything is updated now.
