### ISSUE TITLE
Bootstrap theme and problem with resizable column handle location

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1207]
Testcase: https://jsfiddle.net/Herst/Lq0re9s3/

To reproduce:
1.) Load the page or click "run" to begin anew.
2.) Try to resize the first column, you will see that the mouse pointer does not change at the position between the columns (see screenshot) but instead at an offset position (position about where the red X is in the scree
3.) Resize any column or resize the page/frame.
4.) Suddenly everything works as expected and the handle for resizing is at the position you would expected.

![resizable_problem](https://cloud.githubusercontent.com/assets/1042176/15014899/ea7e876c-1208-11e6-9788-17fb85a20557.png)

**Comment by Mottie** [comment]
Hi @Herst!

Thanks for reporting this problem. I'll look into it as soon as possible.

**Comment by Mottie** [comment]
Ok, it should be all fixed. Try [this updated demo](https://jsfiddle.net/Mottie/Lq0re9s3/1/) once the `widget-resizable` file updates.

Note: I only updated the `widget-resizable.js` and "dist" folder `widget-resizable.min.js` files in the master branch. Once a new release is available, the combined file will get updated.

**Comment by Herst** [comment]
I can confirm that it works (in my project). Thank you!
