### ISSUE TITLE
how can I get the current sortOrder in the sortEnd event?

### ISSUE THREAD

**Issue by finira** [Mottie/tablesorter#1208]
I want to get the current sortOrder  in every sortend event.(desc or asc)
so how can I get it ?

**Comment by Mottie** [comment]
Hi @finira!

The [`sortList` option](http://mottie.github.io/tablesorter/docs/#sortlist) is updated after every sort. It will contain an array of the current sort ([demo](http://jsfiddle.net/Mottie/r25tag6k/1/)):

```js
$(function () {
  $('table')
    .on('sortEnd', function(){
      $('.sortlist').text(this.config.sortList);
    })
    .tablesorter({
      theme: 'blue'
    });
});
```

I'm not sure what you want to do with the information, but please be aware that the `sortList` contains an array of arrays. The inside array contains the zero-based index of the column and the sort direction (`0` for ascending and `1` for descending).

```js
console.log(this.config.sortList);
// [[0,1],[2,0]]
// [0,1] = column 0 (first column), descending sort
// [2,0] = column 2 (third column), ascending sort
```

Alternatively, the `aria-label` of the header, or even the header class name (`tablesorter-headerAsc` or `tablesorter-headerDesc`), can be used to provide additional information ([demo](http://jsfiddle.net/Mottie/r25tag6k/2/)):

```js
$(function() {
  $('table')
    .on('sortEnd', function() {
      var c = this.config,
        list = '';
      $.each(c.sortList, function(i, v) {
        list += '<li>' + c.$headerIndexed[v[0]].attr('aria-label') + '</li>';
      });
      $('.sortlist').html('<ul>' + list + '</ul>');
    })
    .tablesorter({
      theme: 'blue'
    });
});
```

**Comment by finira** [comment]
Hi @Mottie !
thanks for your answering.
I've found the sortList before ,and I added some function in your code .

At line 203 , I added a variable currentSortOrder to remenber the current order.
At 1607 ,I add a function putCurrentOrder to get the current order to currentSortOrder from sortList
`putCurrentOrder:function(sortList) {
			if(sortList&&sortList.length){
				ts.currentSortOrder  = {'0':'asc','1':'desc','2':'unsort'}[sortList[ 0 ][ 1 ]]||'';
			}
		},
`
and a function getCurrentOrder which return the currentSortOrder .
`getCurrentOrder:function() {
			return ts.currentSortOrder;
		},`

and in function multisort ,I invoke the putCurrentOrder to set current order from sortList.
`var tbodyIndex, sortTime, colMax, rows,
				table = c.table,
				dir = 0,
				textSorter = c.textSorter || '',
				sortList = c.sortList,
				sortLen = sortList.length,
				len = c.$tbodies.length;
			ts.putCurrentOrder(sortList);`

(only multisort is used in my program so I invoke the method in this function)

and I can get the current order like this:
`corder = $.tablesorter.getCurrentOrder();`

That's my temp plan,and I complete it ,thank you ~

**Comment by Mottie** [comment]
I wouldn't recommend changing the plugin code. The reason is that when you update the tablesorter core code, all that extra code will need to be added back.

The best solution would be best to loop through each `sortList` column/sort direction pair inside a `sortEnd` callback function as I've already shared.

**Comment by finira** [comment]
Thank you .
So , will you consider adding a function for getting current order in the next version?

**Comment by Mottie** [comment]
Hmmm, I might consider adding something like the following code... ([demo](http://jsfiddle.net/Mottie/nvzb9crt/)):

```js
$.tablesorter.currentSortLanguage = {
  0: 'asc',
  1: 'desc',
  2: 'unsort'
};

$.tablesorter.currentSort = function(table) {
  // allow passing DOM & jQuery object
  table = $(table)[0];
  var indx,
    c = table.config,
    lang = $.tablesorter.currentSortLanguage,
    unsort = lang[2],
    // see https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/fill
    // order = new Array(c.columns).fill(unsort),
    // the above ES6 will not work in all browsers, so
    // we're stuck with this messy code to fill the array:
    order = Array
      .apply(null, Array(c.columns))
      .map(String.prototype.valueOf, unsort),
    sortList = c.sortList,
    len = sortList.length;
  for (indx = 0; indx < len; indx++) {
    order[sortList[indx][0]] = lang[sortList[indx][1]];
  }
  return order;
};
```

It can be used as follows:

```js
$(function() {
  $('table')
    .on('sortEnd', function() {
      console.log($.tablesorter.currentSort(this));
    })
    .tablesorter({
      theme: 'blue',
      widgets: ['zebra']
    });
});
```

Or, you can call `$.tablesorter.currentOrder(table)` at any time after tablesorter initializes to get an array of sorts.

This code might just be more bloat added to the core, so maybe I'll add it into a separate `tablesorter.utilities.js` file... let me think about it.

**Comment by finira** [comment]
Woo!!
that's cool .
waiting for the new version now.
