### ISSUE TITLE
missing group header for empty cells

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1209]
Hi,

if you run this [demo](http://jsfiddle.net/amair/msjx88rb/) you'll see that rows without comment won't have a group header.

It works if you initialize `data.group` to `undefined` in `findColumnGroups()`.

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

Thanks for reporting this problem! I'll have a fix in the master branch shortly.
