### ISSUE TITLE
Having performance issue when there are many columns

### ISSUE THREAD

**Issue by jrmusa** [Mottie/tablesorter#1210]
Due to the user's request, my page needs to represents a lot of columns on tablesorter, but it is getting more slower if it shows more columns(e.g. 100 columns) even it has only one row!

Is there any workaround/solution to solve this kind of issue?
Thanks!

**Comment by Mottie** [comment]
Hi @jrmusa!

First off, I would try to convince the user that 100's of columns isn't practical on mobile devices. I for one would hate to finger swipe like a mad person to just look at data in the last column. 

That aside, if you're using the latest version, then there only a few things that can be done to improve initialization speed:

* Set the [`delayInit` option](http://mottie.github.io/tablesorter/docs/#delayinit) to `true`. This prevents processing of the cache until after the user initializes a sort or applies a filter.
* Set the [`headerTemplate` option](http://mottie.github.io/tablesorter/docs/#headertemplate) to an empty string. This prevents modifying the HTML inside of each header cell. If you're using a theme that requires an icon, make sure to include that in the markup.
* Minimize use of data-attributes and class names that set parsers, extractors and other header option. Instead use the [`headers` option](http://mottie.github.io/tablesorter/docs/#headers) to set these, if needed.
* Lastly, set the [`debug` option]() to `true` and look in the console for the process that takes the longest. Then let me know, and I'll see if there is anything that can be done to improve it.

**Comment by Mottie** [comment]
As @Herst pointed out in IRC, you should also make sure that the `widthFixed` and pager `fixedHeight` options are set to `false` (default settings) as they both use jQuery's `":visible"` selector which does cost a lot on performance.

**Comment by jrmusa** [comment]
Thanks for recommandation and unfortunately user didn't want to change the design, however I tried to set it up according to your suggestion and got a little bit faster only.

Environment: IE11 with 54 rows and 101 columns
Setting:
$('#designyield').tablesorter({
	theme: 'blue',
	delayInit: true,
	headerTemplate: "",
	widthFixed: false,
	fixedHeight: false,
	debug: true,
	widgets: ["stickyHeaders"],
	ignoreCase: false,
	widgetOptions: {
		stickyHeaders_offset: 50

Debug log:
[Before]
[object Object]
Completed detecting parsers (74ms)
Building cache for 54 rows (449ms)
Completed initializing 1 widget (1ms)
Completed applying stickyHeaders widget (827ms)
Completed applying 1 widget (827ms)
Overall initialization time:  (3506ms)
Time until DOMready:  10953ms
Time until everything loaded:  11042ms
[After]
[object Object]
Completed detecting parsers (72ms)
Completed initializing 1 widget (1ms)
Completed applying stickyHeaders widget (753ms)
Completed applying 1 widget (753ms)
Overall initialization time:  (2677ms)
Time until DOMready:  10108ms
Time until everything loaded:  10161ms

It takes more than 10 seconds with 2677ms of tablesorter, when I focus on tablesorter, it still needs 2.6 seconds to prepare data on IE11, however, it only takes 885ms on FF.

**Comment by Mottie** [comment]
Hmm, try initializing the sticky headers widget after tablesorter initializes ([demo](http://jsfiddle.net/f36416oy/24/)):

```js
$(function() {

  $('table').tablesorter({
    debug: true,
    theme: 'blue',
    widgets: [], // no widgets
    widgetOptions: {
      stickyHeaders_offset: 50
    },
    initialized: function() {
      // adjust the delay as desired... probably best to have it run after
      // the page has finished loading everything.
      setTimeout(function() {
        // initialize the stickyHeaders widget here
        $('table').trigger('applyWidgetId', 'stickyHeaders');
      }, 2000);
    }
  });

});
```

**Comment by jrmusa** [comment]
Wow, reduce more time as below:

> [object Object]
> Completed detecting parsers (70ms)
> Completed initializing 1 widget (1ms)
> Completed applying 1 widget (0ms)
> Overall initialization time:  (1931ms)
For FF, it only takes 483ms!

**Comment by Mottie** [comment]
It would probably be about the same if you use the [css3 sticky header widget](http://mottie.github.io/tablesorter/docs/example-widget-css-sticky-header.html) which doesn't clone the header; it uses css3 to translate the `thead`. Sadly, not everyone likes it because it isn't as smooth in IE.

I don't think we can reduce the initialization time any more than that in IE. It's javascript engine is the slowest out of all the browsers. I bet the overall initialization time is even better in Chrome.

**Comment by Herst** [comment]
> Sadly, not everyone likes it because it isn't as smooth in IE.

Also, there are z-issues: https://jsfiddle.net/Herst/1byz4jay/

**Comment by TheSin-** [comment]
z issues are just theme issues, just correct in your css is all, it's a very easy fix.

**Comment by Mottie** [comment]
Hmm, that isn't a simple z-index issue... It doesn't appear to do anything. Oddly using `translate3d` with a z translation doesn't do anything either.

I did eventually get it to work, but I had to add negative z-indexes to the entire tbody, tbody rows, cells & buttons... and remove zebra striping ([demo](https://jsfiddle.net/Mottie/1byz4jay/2/)) - it's not pretty.

**Comment by TheSin-** [comment]
or just move the thead under the tbody in the html markup, that is what I did and it worked perfectly.

**Comment by Herst** [comment]
@TheSin- That's interesting, it goes against the HTML5 standard (https://www.w3.org/TR/html5/tabular-data.html#the-thead-element and https://www.whatwg.org/specs/web-apps/current-work/#the-thead-element: *"before any tbody"*) but it works.

**Comment by Mottie** [comment]
You're a fart smeller, that does work!

**Comment by TheSin-** [comment]
it works cause of how it's rendering things, stuff at the bottom of html markup naturally renders above things on top of it.  HTML is interpretive, so it renders as it reads.  It is against standard but once in a while I have no choice but to do things like this.
