### ISSUE TITLE
How do I include more widgets when installing tablesorter by npm install?

### ISSUE THREAD

**Issue by liangliang** [Mottie/tablesorter#1214]
It seems like that a few widgets are included after npm install tablsoter. 

But I want to include the scroller widget, how to do that？

Regards,
Liang

**Comment by Mottie** [comment]
Hi @liangliang!

Using `npm install tablesorter` will add the entire contents of the [`dist` folder](https://github.com/Mottie/tablesorter/tree/master/dist), so all widgets are available. You will need to point to the desired widget(s) in a `<script>` tag in the HTML file.

**Comment by liangliang** [comment]
Hi @Mottie, 

Thanks for the reply. Yeah, all js are in dist folder. But when I require('tablesorter'), it only includes jquery.tablesorter.combined.js which doesn't contain the scroller widget. Guess I will require('scoller-widget') manually.

**Comment by Mottie** [comment]
Sorry, I suck at npm & all that require factory node thingies.

If you have a nice solution that allows you to customize what widgets are loaded and/or required, I'd be happy for a PR :grinning:

**Comment by FascistDonut** [comment]
@liangliang - Did you ever figure this out? I'm having the exact same problem.

**Comment by tlorens** [comment]
@liangliang Having the same problem.  What's the proper method here?  I'm ok with having to use multiple ```require()```  But I can't seem to figure out the naming to get it to load correctly.
