### ISSUE TITLE
Space allocated for hidden  column

### ISSUE THREAD

**Issue by AbhishekKumar26** [Mottie/tablesorter#1215]
I am applying widget on a table which has first row hidden and n rows visible.
On applying the widget, the row for search box gets extended to an extra column. Please find the widget configuration below. Using version: '2.26.0'

```js
var tableEmptyDependencyStyleOption = $.extend(true, {}, globals.tableSorterOptions, {
	// sort on the first column in ascending order, Hidden columns are considered for numbering
	sortList: [[0, 0]],
	widgets: ['zebra'],//, 'resizable'
	widgetOptions: {
		filter_cellFilter: ['disabled', '', '', '', '', 'disabled'],
		filter_columnFilters: true,
		filter_cssFilter: "form-control",
	},
```

**Comment by Mottie** [comment]
Hi @AbhishekKumar26!

When hiding a column, use css to do it. Something like this:

```css
.tablesorter tr th:nth-child(1),
.tablesorter tr td:nth-child(1) {
  display: none;
}
```

where the `1` in `nth-child` is the one-based index (start counting from one instead of zero) of the column you want to hide.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
