### ISSUE TITLE
Sticky Headers with fixed content above it

### ISSUE THREAD

**Issue by Maaaarc** [Mottie/tablesorter#1217]
Hey,

I have some fixed content at the top of my page like buttons and stuff and a table below it like in this fiddle: 
http://jsfiddle.net/wx1oacun/
I put the table into a wrapper with padding-top. As long as I don't use overflow for the wrapper, which I don't want to use, the sticky headers are still placed at the top of the page and not at the position of the wrapper.
Is this an issue or how can I make this working?

Thanks a lot,
Marc

**Comment by Mottie** [comment]
Hi @Maaaarc!

Set the [`stickyHeaders_offset` option](http://mottie.github.io/tablesorter/docs/#widget-sticky-headers-offset) to either a pixel value, or a jQuery selector pointing to the element at the top ([demo](http://jsfiddle.net/Mottie/wx1oacun/1/)):

```js
$('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'stickyHeaders'],
    widgetOptions: {        
        stickyHeaders_offset: ".sticky"
    }
});
```

**Comment by Maaaarc** [comment]
Thanks for the fast response. I've seen this option bevor but somehow I can't make it work. I added stickyHeaders_offset: ".topelement" to the fiddle http://jsfiddle.net/6wpb154s/ where topelement is the class name of the div with the fixed position at the top.

**Comment by Mottie** [comment]
The demo you just shared needs to include the "stickyHeaders" widget:

```js
 widgets: ['zebra', 'stickyHeaders'],
```

**Comment by Maaaarc** [comment]
Oh lol... thanks ^^

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
