### ISSUE TITLE
Unable to really disable tablesorter for a column

### ISSUE THREAD

**Issue by Cartman34** [Mottie/tablesorter#1219]
Hi,

I am using a check all checkbox in a table header and i am experiencing some trouble with Tablesorter 2.26.1.
Tablesorter removes my element from the DOM and places it in a wrapper even if i disabled it for this column. This never should happen, a plugin must not modify DOM for element that is not agreeing with final developer.

For other experiencing the same issue, the alternative solution is to use $(this).uniqueId().attr('id') to keep a selector of it and to use $('body').on("change", yourSelector, function() { ... }); to bind change on it.
This is not the best solution, this is only an acceptable solution, the real solution is to fix tablesorter.

**Comment by Mottie** [comment]
Hi @Cartman34!

If you don't want tablesorter to manipulate the headers, then set the [`headerTemplate` option](http://mottie.github.io/tablesorter/docs/#headertemplate) to an empty string.

I'll probably end up rewriting/removing the header template code eventually. It was coded to work best with older versions of IE, and now that should no longer a problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
