### ISSUE TITLE
Filter-exact not working if there is -(hyphen) in the td text

### ISSUE THREAD

**Issue by afzal273** [Mottie/tablesorter#1220]
If there is - (hyphen) in the td text for example Student - 02 and filter-exact class is set on the table header, on selecting Student - 02 nothing shows up. I'm wondering if this is because the - is treated like a subtraction? Please help me with a fix. Thanks for your help!

**Comment by Mottie** [comment]
Hi @afzal273!

When your search contains a dash surrounded by spaces, the filter thinks you want a range. To have the filter ignore the range search for a column, use the [`filter_excludeFilter` option](http://mottie.github.io/tablesorter/docs/#widget-filter-exclude-filter) to disable the "range" type of filters for that column ([demo](http://jsfiddle.net/Mottie/wty134u7/3/)):

```js
$('table').tablesorter({
  theme: 'blue',
  widgets: ['zebra', 'filter'],
  widgetOptions: {
    filter_excludeFilter: {
      0: 'range'
    }
  }
});
```

**Comment by Mottie** [comment]
Oops, you asked about "filter-exact". That class name actually only applies when a user is performing an "or" or "and" search (e.g. "foo or bar") - I guess that might be a bit confusing :disappointed:.

What you'll need to do is include a [`filter_defaultFilter` option](http://mottie.github.io/tablesorter/docs/#widget-defaultfilter) for that same column ([demo](http://jsfiddle.net/Mottie/wty134u7/6/)):

```js
$('table').tablesorter({
  theme: 'blue',
  widgets: ['zebra', 'filter'],
  widgetOptions: {
    filter_defaultFilter: {
        // "{query} - a single or double quote signals an exact filter search
    	0 : '"{q}'
    },
    filter_excludeFilter: {
      0: 'range'
    }
  }
});
```

**Comment by afzal273** [comment]
Thanks for your response!

I tried it on jsfiddle it works perfectly - http://jsfiddle.net/afzal273/59epsqug/2/ <http://jsfiddle.net/afzal273/59epsqug/2/> (When I select student - 01 or student - 02, I get the row I'm looking for). Somehow it doesn't work on my computer or a web server :-/. There if I select student - 01 or student - 02 in the name column nothing shows up, but student06 etc show up just fine.

 The CSS, JS I'm including is -


<link rel="stylesheet" href="../css/theme.bootstrap.css">
<link rel="stylesheet" href="../css/jquery.tablesorter.pager.css">

<script src="../js/jquery-1.11.3.min.js"></script>
<script src="../js/jquery.tablesorter.min.js"></script>
<script src="../js/jquery.tablesorter.widgets.js"></script>
<script src="../js/jquery.tablesorter.pager.js"></script>
<script>

    $(function() {
        $("table").tablesorter({
            theme: "bootstrap",


            widthFixed: true,

            headerTemplate: '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!

            widgets: ["uitheme", "filter"],
            headers: { 6: { sorter: 'grades' } },

            widgetOptions: {
                filter_reset: ".reset",
                filter_cssFilter: "form-control"

            }
        });
    });

Not sure what's going on. Any ideas? Thanks for your help.

Best,
Afzal.

**Comment by Mottie** [comment]
Please make sure you're using the most up-to-date version of the tablesorter files. Also, the code that was shared doesn't include the `filter_defaultFilter` or the `filter_excludeFilter` option settings.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
