### ISSUE TITLE
Full CSS, please !

### ISSUE THREAD

**Issue by mcd-php** [Mottie/tablesorter#1222]
In my web projects, I use ASSET_INFIX variable to load minified CSS and JS in production and full in debug.

Some lonely 404 flew by among many successful dependencies, it was this project. 

So I had to kludge my asset pipeline for exception.

**Comment by Mottie** [comment]
Hi @mcd-php!

Sorry, are you asking to include the non-minified css along with the minified in the `dist` folder? If you're loading the entire repository, then you can point your scripts to `./css` folder.

**Comment by TheSin-** [comment]
I'm just guessing here, but I assume that since he uses a class to do all the loading, that it expects both the min and full version in the same folder.  That being said The current way isn't that abnormal and he might just need to make a symlink from the css to the dist folder which won't break git updates.  Either way I'm not sure it's an issue for here, if anything maybe a request.

**Comment by mcd-php** [comment]
No, I load from [cdnjs](https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.2/css/theme.bootstrap.min.css), and [removing .min gives 404](https://cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.2/css/theme.bootstrap.css).

So I believe the issue should be resolved by guidelines of https://github.com/cdnjs/cdnjs and probably some other major providers like this. Probably this requires min/max files alongside, like in https://cdnjs.com/libraries/jqueryui

**Comment by TheSin-** [comment]
ahh there is the info we needed, you on this @Mottie I don't thin kI have access to cndjs to help, I've never used it before.

**Comment by Mottie** [comment]
Ahh, ok... I just need to include the css & probably the js folders in this [`package.json` section](https://github.com/Mottie/tablesorter/blob/master/package.json#L50-L57)

```js
  "autoupdate": {
    "source": "git",
    "target": "git://github.com/Mottie/tablesorter.git",
    "basePath": "",
    "files": [
      "dist/**/*",
      "css/*",
      "js/*"
    ]
  },
```

This updates CDNJS automatically, but won't happen until a new release is available.
