### ISSUE TITLE
Pager plugin form issue

### ISSUE THREAD

**Issue by barbmc** [Mottie/tablesorter#1224]
I just downloaded the latest versions of tablesorter and widgets as I wanted to use the pager widget.

Unfortunately it doesn't work. Even though I have set the size to 20, my table still loads with all rows, and selecting different numbers of rows does nothing.

I already have my table in a form, I'm guessing this is part of the issue as nested forms don't work. However, I moved the pager div after my existing form and that made no difference

I don't see any errors in firebug.

```js
$("table")
    .tablesorter({
      widgets: ['zebra','pager'],
      widgetOptions: {

        // jQuery selectors
        pager_selectors: {
          // target the pager markup (wrapper)
          container: $('.pager')
        },

        // Number of visible rows
        pager_size: 20

      }
    });
```

I tried to include my php code but it rendered in the message, so I removed it.

**Comment by Mottie** [comment]
Hi @barbmc!

Please make sure that the class names from the pager markup match the default settings in the `pager_selectors` ([demo](http://jsfiddle.net/Mottie/yfwwzvL8/318/)):

HTML

```html
<div class="pager">
  <img src="/icons/first.png" class="first" />
  <img src="/icons/prev.png" class="prev" /> <span class="pagedisplay"></span>
  <!-- this can be any element, including an input -->
  <img src="/icons/next.png" class="next" />
  <img src="/icons/last.png" class="last" />
  <select class="pagesize" title="Select page size">
    <option selected="selected" value="10">10</option>
    <option value="20">20</option>
    <option value="30">30</option>
    <option value="40">40</option>
  </select>
  <select class="gotoPage" title="Select page number"></select>
</div>
```

Snippet

```js
pager_selectors: {
  // target the pager markup (wrapper)
  container: $('.pager'),

  // make sure all these selectors target the HTML classes
  first: '.first',
  prev: '.prev',
  next: '.next',
  last: '.last',
  gotoPage: '.gotoPage',
  pageDisplay: '.pagedisplay',
  pageSize: '.pagesize'
},
```

Also, please check that previous page settings that are saved to local storage aren't interfering by setting the [`pager_savePages` option](https://mottie.github.io/tablesorter/docs/#save-pages) to `false`.

**Comment by barbmc** [comment]
debug shows this

"pager" widget code does not exist!

I have included
<script src="js/jquery.tablesorter.min.js"></script>
<script src="js/jquery.tablesorter.widgets.js"></script>

and added the js from the demo

What else do I need?

**Comment by barbmc** [comment]
I worked out I need to add widget-pager.js, now all is working.
