### ISSUE TITLE
Save number of rows selected

### ISSUE THREAD

**Issue by barbmc** [Mottie/tablesorter#1225]
I see pager has a savePages option to save the page and page rows. I would like to save the page rows but not the page - is this possible?

**Comment by Mottie** [comment]
Hi @barbmc!

Do you only want to save the count, or an array with the ID's from the selected rows? Is the server set up to return selected rows by ID, or something?

Please share an example of the HTML markup, you can replace/remove the sensitive data, I just wanted to see how things are laid out.

**Comment by barbmc** [comment]
I only want to save the number of rows per page selected in the pagesize selectDate: Wed, 1 Jun 2016 20:43:08 -0700

**Comment by Mottie** [comment]
Maybe this code will work for you? ([demo](http://jsfiddle.net/Mottie/yfwwzvL8/319/))

```js
$(function() {
  $('table')
    .on('pagerComplete', function() {
      // "checked" class added to row by the parser-input-select.js code
      var count = $(this).children('tbody').children('tr.checked').length;
      console.log(count);
    })
    .tablesorter({
      theme: 'blue',
      widthFixed: false,
      widgets: ['zebra', 'pager']
    });
});
```

**Comment by barbmc** [comment]
Maybe I need to explain myself better.

I have many users that use my website using tablesorter.

The default page size is 10 rows. If a user changes that to say 20, I assume they would always like that pagesize until they change it again. So I would like to set that as the default for them.

Could I use the code below to get the pagesize they have set and then put it in a cookie?Date: Wed, 1 Jun 2016 21:12:55 -0700

**Comment by Mottie** [comment]
Oh, well, there is a pager [`savePages` option](https://mottie.github.io/tablesorter/docs/#save-pages) which when set to `true` will save the user selection to local storage.

I don't understand what that has to do with checkboxes.

**Comment by barbmc** [comment]
Yes but that saves the page they were on as well. I want the pagesize saved, but they should always start at the first page.Date: Wed, 1 Jun 2016 21:48:52 -0700

**Comment by Mottie** [comment]
Ok, now I finally understand. I got confused when I read "rows selected" which I took to mean each row had a checkbox to select it.

Anyway, to achieve what is required, set the pager `savePages` option, then ignore the set page number on initialization ([demo](http://jsfiddle.net/Mottie/yfwwzvL8/321/)):

```js
$(function() {
  $('table')
    .on('pagerBeforeInitialized', function() {
      // this always resets to the first page on initialization
    	this.config.pager.page = 0;
    })
    .tablesorter({
      theme: 'blue',
      widthFixed: false,
      widgets: ['zebra', 'pager'],
      widgetOption: {
      	pager_savePages: true
      }
    });
});
```

**Comment by barbmc** [comment]
Sorry for confusing you.

That's perfect - thanks!!!Date: Thu, 2 Jun 2016 04:00:40 -0700

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
