### ISSUE TITLE
0x800a138f - JavaScript runtime error: Unable to get property 'storage' of undefined or null reference

### ISSUE THREAD

**Issue by atovarlanz** [Mottie/tablesorter#1226]
When try to implement this demo http://jsfiddle.net/Mottie/abkNM/17/, in Asp.Net MVC 4, this demos works well except these part of code

`$('table')
    .bind('filterInit', function() {
        // check that storage ulility is loaded
        if ($.tablesorter.storage) {
            // get saved filters
            var f = $.tablesorter.storage(this, 'tablesorter-filters') || [];
            $(this).trigger('search', [f]);
);
        }
    })
    .bind('filterEnd', function(){
        if ($.tablesorter.storage) {
            // save current filters
            var f = $(this).find('.tablesorter-filter').map(function(){
                return $(this).val() || '';
            }).get();
            $.tablesorter.storage(this, 'tablesorter-filters', f);
        }
    });
`
Display the following error : 0x800a138f - JavaScript runtime error: Unable to get property 'storage' of undefined or null reference.

I attach the files tablesorter and tablesorter.widget that correspond with the demo. and charged using the bundle.config

The demo is fully functional except these part of code mentioned.

Any idea or suggestion , thanks a lot

**Comment by Mottie** [comment]
Hi @atovarlanz!

I'm not sure why you're seeing that javascript error. Actually, I'm not very familiar with Asp.Net, so I have never heard of a bundle.config.

Did you know you can set the [`filter_saveFilters` option](https://mottie.github.io/tablesorter/docs/#widget-filter-savefilters) to accomplish the same thing as the code you shared?

**Comment by atovarlanz** [comment]
I implement the demo exactly as fiddle demo. With the files of tablesorter,
in other words, i copy and paste the code fully functional fiddle to a
asp.net mvc4. The code runs great except the events delegates (filterinit
and filterend) . But i not understand the error, I check about jquery
version but its no the problem. I not sure about whats its the exactly error

Alejandro Tovar

**Comment by Mottie** [comment]
Oh, if the code is *exactly* as it is from the jsFiddle, then make sure to wrap all the code inside a document ready function...

```js
$(function() {
  // put all the code from the javascript pane here
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
