### ISSUE TITLE
No Data Found can't show with columnSelector

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1231]
Hi Mottie,

Please find http://jsfiddle.net/4mVfu/6048/, and when hide first column with filter, the No Data Found row can't be shown.

Many thanks,
Thomas

**Comment by Mottie** [comment]
Hi @airthomas!

Because the `showError` function doesn't determine which columns are visible or hidden, the cell and therefore the entire row is hidden.

The easiest workaround would be to pass a message with the HTML included ([demo](http://jsfiddle.net/Mottie/4mVfu/6050/))

```js
var row = "<tr><td></td><td colspan='6'>No Data Found</td></tr>";
$.tablesorter.showError(table, row);
````

**Comment by airthomas** [comment]
Hi Mottie,

Great, many thanks your explanation.
