### ISSUE TITLE
Grouping widget triggers an error when switching to next page

### ISSUE THREAD

**Issue by KarlBaumann** [Mottie/tablesorter#1232]
In [this example](http://jsfiddle.net/Mottie/1xdy78qv/2/), when switching to next page, grouping does not work anymore and it triggers an error 
`widget-grouping.js:211 Uncaught TypeError: Cannot read property '6' of undefined`

**Comment by TheSin-** [comment]
what browser, I'm not seeing the error at all.

**Comment by KarlBaumann** [comment]
Google Chrome Version 51.0.2704.103 m on Windows 7, 64bit

**Comment by TheSin-** [comment]
let me dust off chrome and give it a shot, stand by

**Comment by TheSin-** [comment]
Same version but on MacOS, but still no error at all.  I'll wait for @Mottie to get up I guess since he has access to windows.

**Comment by Mottie** [comment]
Thanks for reporting this issue! I'll have the problem fixed in the master branch shortly.
