### ISSUE TITLE
Sticky header not calculating position correctly

### ISSUE THREAD

**Issue by Boduje** [Mottie/tablesorter#1234]
I've been using Tablesorter now for some time and love it!  I recently updated a website layout and now my tablesorter tables are no longer in DIVs.  They are centered using CSS (margin:0 auto;) with a maximum width.

The problem I am experiencing come from differences in how browsers calculate the position of the sticky header.

Here is the code in Firefox 46:
`<div style="position: fixed; top: 0px; left: 328px; visibility: visible; z-index: 2; width: 1248px;" class="tablesorter-sticky-wrapper tablesorter-sticky-visible">`

Here is the code in Chrome 51:
`<div style="position: fixed; top: 0px; left: 0px; visibility: visible; z-index: 2; width: 1248px;" class="tablesorter-sticky-wrapper tablesorter-sticky-visible" >`

You can see that Firefox has calculated the left positioning (328px) to keep the sticky header centered.  Google Chrome has not - left position is zero '0'.

Is this a bug or do I need to add something to the tablesorter init?

**Comment by Mottie** [comment]
Hi @Boduje!

The sticky header widget from this fork doesn't use `position:fixed`. If you look at the [stickHeaders widget demo](https://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html#table2) , the second table is wrapped in a div that is centered. The sticky headers table is appended to that wrapping div.

If that doesn't help, please modify [this demo](http://jsfiddle.net/Mottie/f36416oy/27/) and I will modify it to get it working.

**Comment by Boduje** [comment]
I reverted my test table back to having to having a "row->span" wrapper and all is good.  What sucks now, is that I have to go back and rewrap a bunch of tables.  I guess that's what I get for trying a shortcut that only Firefox likes.  LOL

Thanks for your time and assistance, Mottie!!

**Comment by Mottie** [comment]
If you're wrapping the table with a span, all you should need to do is set the css for that element to `display:block`.
