### ISSUE TITLE
Search Backspace not triggering?

### ISSUE THREAD

**Issue by devin42r** [Mottie/tablesorter#1235]
When using class "search" on input bar, it appears that backspace key is not triggering tablesorter search. Is that keycode intentionally ommitted?

**Comment by devin42r** [comment]
When using class "search" on input bar, it appears that backspace key is not triggering tablesorter search.  Is that keycode intentionally ommitted?

**Comment by Mottie** [comment]
Hi @devin42r!

Filter searches are based on the following events: `search change keypress input` and if the last search is not the same as the current search.

I just tested a search in [this demo](http://jsfiddle.net/Mottie/bbxxomhx/54/) and the backspace was working for me. If that demo doesn't work, then let me know what browser you're using. If it does work, then please modify that demo to reproduce the problem.

**Comment by devin42r** [comment]
Double back space was working, but for some reason just the one was not triggering.  Resolved by manually triggering search on table.tablesorter if keyup keycode 8...
