### ISSUE TITLE
Filter attributes which are not in column

### ISSUE THREAD

**Issue by egemenozkan** [Mottie/tablesorter#1236]
I need to filter which i have added on <tr></tr> as attribute. I am using  textextration, but i have more attributes which needs filtering than columns. Please lead me to solve this problem.

```js
 textExtraction : {
	      1: function(node, table, cellIndex){return $(node).parent().data('departure-time')},
	      2: function(node, table, cellIndex){ return $(node).parent().data('duration-time') },
	      3: function(node, table, cellIndex){ return $(node).parent().data('arrival-time') },
	      4: function(node, table, cellIndex){ return $(node).parent().data('price') },
	      0: function(node, table, cellIndex){ return $(node).parent().data('airline') },
	      5: function(node, table, cellIndex){ return $(node).parent().data('airport') },
	    },
```

**Comment by Mottie** [comment]
Hi @egemenozkan!

If you want to filter a column based on the parsed data, set a [`"filter-parsed"` class name](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes) in each header; or, add a `filter:"parsed"` inside the [`headers` settings](https://mottie.github.io/tablesorter/docs/#headers).

If that doesn't work, please share an example of the HTML being used.

**Comment by egemenozkan** [comment]
Thank you @Mottie , for quick response.
I have 6 columns on each row, however attributes are almost 15.  I have added to <tr>; for example, data-airline, data-arrival-time etc. I am calling with setFilter function via external functions or external ui range sliders.  `$.tablesorter.setFilters($flights, filters, true);` I can only set 6 filters. I should add more filter.

**Comment by egemenozkan** [comment]
@Mottie , I have solved by adding hide columns. add function per column. It works efficiently. If you have new suggestions, please share with us.

**Comment by Mottie** [comment]
I'm glad you found a solution! Sadly, I don't have any suggestions because I would have to guess at the code and HTML.
