### ISSUE TITLE
columnSelector with multiple rows and colspan

### ISSUE THREAD

**Issue by ArthurJam** [Mottie/tablesorter#1238]
Hello,

First, Thx for your version of tablesorter.

I have a problem with columnSelector widget.
When I hide a column in relation with a colspan, the widget works and correclty update the colspan value in the first header row..
Surprisingly, when i hide a simple column, the widget does not mask the column in the first header row.

Demo : https://jsfiddle.net/50v3ppwk/10/

Sorry for my poor english.

**Comment by Mottie** [comment]
Hi @ArthurJam!

Thanks for reporting this problem. I will look into it soon.

**Comment by Mottie** [comment]
I've updated the column selector widget in the master branch. Please make sure it is working as expected ([demo](https://jsfiddle.net/Mottie/50v3ppwk/11/)).

I plan to push a new release soon (meaning, the change will be available in the CDN).

**Comment by ArthurJam** [comment]
Hi,
It's working as expected now.
Your responsiveness is impressive, thx.

**Comment by Mottie** [comment]
A new release is now available!

**Comment by ptijul** [comment]
I'm reopening this issue as I also have problems when using colspan and rowspan. 
See the fiddle [here ](https://jsfiddle.net/dntay90v/3/)(based on last version available on CDN v.2.28.1).

When I unselect the Portfolio column (the first column) and observe that the column "Portfolio" becomes hidden but also the Type 1 column (the first column of the second header row)
...When I unselect the second column this also hides the second column of the second row....and so on.

Can you plan to add this to a near future release ? 
Thanks for this tool, I really like it ;-)

**Comment by Mottie** [comment]
Hi @ptijul!  I've fixed the problem in the master branch. I don't plan on releasing a patch just yet... Once some other minor issues have been resolved, you can expect a new patch.

**Comment by ptijul** [comment]
Wow ! You're awesome !! So fast.
Thanks for the demo, I need to deliver a new release to our clients by the end of next week so I'll download this current version of the master version temporarily until a new version comes up.

Thanks a lot !!
