### ISSUE TITLE
About licensing

### ISSUE THREAD

**Issue by aicooole** [Mottie/tablesorter#1244]
Sorry for filling your issues, but I have a question about the license.

I found the following difference about it.

On README.md(https://github.com/Mottie/tablesorter/blob/master/README.md), it says that this lisence is MIT "**and**" GPL license.
But on the other hand, your original document(http://tablesorter.com/docs/) says that this lisence is MIT "**or**" GPL license(just pick!)

I'm wondering which one is correct.
I would appreciate if you could answer my question.

 - In additional, I found a mistake on README.md .
 Original examples and docs URL is wrong(http, not https).

Regards,

**Comment by Kostronor** [comment]
Hey there @aicooole,

First of all you got the wrong website, this here is Motties fork, the docs are located here: https://mottie.github.io/tablesorter/docs/

And both state that it is a **Dual-Licence**, which normally means you can choose the licence you want to use. 

I would be curious how to **and* two licences, Is only stuff allowed that both licences allow? That sounds not really permissive :wink: 

But I'm an outsider like you, maybe @Mottie can clear this up and make documentation consistent.

**Comment by Mottie** [comment]
Hi @aicooole!

Thanks for pointing out the link issues. I copied the license from the original tablesorter, but I might have messed up the wording... **and** and **or**, they're pretty much the same right? LOL. Well, it is supposed to be **or**. You pick the license you want to use.

@Kostronor I don't think you can **and** two licenses, unless part of the code is copied from another project, or something.

**Comment by aicooole** [comment]
Hi @Mottie 
Thank you for answering my question.
I'm relieved to hear that my understanding is right.(I mean I can pick the license).

@Kostronor 
I also appreciate your advice, thanks.
