### ISSUE TITLE
Ajax table with CSS in row

### ISSUE THREAD

**Issue by QewQew** [Mottie/tablesorter#1246]
How can I get custom CSS into an ajax loaded table row?

**Comment by Mottie** [comment]
Hi @QewQew!

If you look at the [`ajaxProcessing` pager option](https://mottie.github.io/tablesorter/docs/index.html#pager-ajaxprocessing), you'll find multiple examples of how to serve and process data.

* The "Object" section shows that the server can provide processed HTML. So you would have the server add the desired row class name.
* In the "Array (total only)" and "Array (rows as jQuery object)" sections, the example shows that you could add a row class name while building the HTML.
