### ISSUE TITLE
Grouping: group_collapsed

### ISSUE THREAD

**Issue by mtgtnt** [Mottie/tablesorter#1247]
when setting group_collapsed: true
it does nothing. Am I missing something?
http://jsfiddle.net/bu3wha9d/

**Comment by Mottie** [comment]
Hi @mtgtnt!

Hmm, that looks like a bug.

It looks like what happened is when the `group_saveGroups` option was added to save which groups were collapsed, it overrode the intended behavior. If you set the `group_saveGroups` to `false`, all headers will start collapsed.

I'll see if I can find a solution, or at the very least update the documentation.

**Comment by Mottie** [comment]
[Here's a demo](http://jsfiddle.net/Mottie/bu3wha9d/1/)... I had to add a reset button to clear out the saved groups before it would behave.

**Comment by mtgtnt** [comment]
This is working great for initial load of table. Now the next part is when the table changes, for example with an ajax call. Using .trigger("update") will not collapse the rows.

**Comment by Mottie** [comment]
If you still have `group_saveGroups` set as `true`, then you'll need to clear out the saved groups before triggering an update ([demo](http://jsfiddle.net/Mottie/bu3wha9d/3/))

```js
$('.update').click(function() {
  // don't pass this function the $table jQuery object
  $.tablesorter.grouping.clearSavedGroups($table[0]);
  $table.trigger('update');
});
```

**Comment by mtgtnt** [comment]
I had just put the same thing together and about to post my findings. You beat me to it :)

**Comment by Mottie** [comment]
A new release is now available!
