### ISSUE TITLE
ts.getFilters(...).join is not a function,

### ISSUE THREAD

**Issue by ukeller** [Mottie/tablesorter#1250]
jquery 2.4.4
tested on FF and Chrome on Windows 2012 Server

70b882c44f27c4fce6ba9bbd3e0f1aecf9c41f97 introduces a change that breaks the library for me. ts.getFilters(...) can return a Boolean for which join is not defined

**Comment by Mottie** [comment]
LOL, I just opened #1249. Thanks!

**Comment by Mottie** [comment]
Ok, this "should" be fixed in the master branch now. I consider this a breaking change to the API, so this will be provided with the next release (v2.27.0).
