### ISSUE TITLE
jquery in Filter Functions

### ISSUE THREAD

**Issue by egemenozkan** [Mottie/tablesorter#1252]
Hello,
I am trying to use filter in group. with parsers, group can not be filtered. And also i am trying to own function with jquery, however it does not work. Is it possible to use jQuery in filter_functions ?

```
var filterFunctions ={
			2 : function(e, n, f, i, $r, c, data) {

				 console.log($($r));
				 console.log($r);
				 var packageId = $r[0].dataset['package'];
				 $('tr.package_'+ packageId).each(function(){
					 $(this).hide();
				 });
				return true;
			}
	}
```

**Comment by Mottie** [comment]
Hi @egemenozkan!

The `$r` is already a jQuery object of the table row. So, yes you can use jQuery.

I would recommend not using `dataset` because it's [not supported in IE < 10](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_data_attributes#Issues). Instead try this:

```js
var filterFunctions = {
  2 : function(e, n, f, i, $r, c, data) {
    var packageId = $r.attr('data-package');
    $('tr.package_'+ packageId).hide();
    return true;
  }
}
```

**Comment by egemenozkan** [comment]
Ok, I did. Thank you.
