### ISSUE TITLE
resizable width set programmatically

### ISSUE THREAD

**Issue by lennae24** [Mottie/tablesorter#1253]
After calling the tablesorter, i want to set resizable_widths programmatically. But what happened is when using below code:

`$("#tableId")[0].config.widgetOptions.resizable_widths = [
        '20%', '10%', '10%', '70%'
];
$("#tableId").trigger("updateAll");`

The resize functionality doesn't work anymore.

**Comment by Mottie** [comment]
Hi @lennae24!

I've had issues with the resize widget not working well after an "updateAll". Is there a reason why "updateAll" is being used? To update the widget, you only need to trigger [`applyWidgets`](https://mottie.github.io/tablesorter/docs/#applywidgets) on the table.

```js
$("#tableId")[0].config.widgetOptions.resizable_widths = [ '20%', '10%', '10%', '70%' ];
$("#tableId").trigger("applyWidgets");
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
