### ISSUE TITLE
Can Pager use a large AJAX dump

### ISSUE THREAD

**Issue by Boduje** [Mottie/tablesorter#1254]
Is there a way to store a large AJAX dump in a variable and have Pager use that for sorting, filtering, and paging instead making numerous calls back to the server for everything?

Basically, return the full recordset for the table, say 1,000 rows, instead of telling the server to only show 10 rows, then 10 rows more, then 10 rows more...

**Comment by TheSin-** [comment]
if it's the full set why use ajax? why not just load it to start with and use the pager without ajax (cause that is what you are describing) :D

**Comment by Boduje** [comment]
Yeah, that's basically what I want to do, but didn't see an example of how to do that.  All I saw were AJAX examples.

**Comment by Boduje** [comment]
Forget it.  I have bigger issues now.  I just updated Tablesorter and the widgets to latest versions, and now filtering doesn't work on any page - isn't even visible.  :-(  I was using v2.25.0

**Comment by TheSin-** [comment]
make sure you have display: none; on .filtered if you have you're own class.

**Comment by Mottie** [comment]
Also, don't forget to use the `debug` option to check what's going on.
