### ISSUE TITLE
Initialization fails with Webpack

### ISSUE THREAD

**Issue by rdicroce** [Mottie/tablesorter#1255]
I'm trying to use tablesorter with Webpack, but when I load the resulting JS in a browser, I get "ReferenceError: jQuery is not defined".

I'm not 100% sure, but I think the problem is the IIFEs that register tablesorter as a jQuery plugin. The function definitions use '$' as the jQuery variable name, but when the function is invoked, the provided argument is 'jQuery'. Which works if jQuery is loaded on the page by a normal script tag, but not when using a module loader.

The jQuery/$ mish-mash was copypasta'd into all the widgets as well, so they all need fixing.

**Comment by Mottie** [comment]
Hi @rdicroce!

Hmm, the IIFEs are added inside the `Gruntfile.js`, so it should be an easy fix. 

I've never used webpack before, so before I modify the file and push a new release, I would really appreciate it if you would please verify that that is truly the cause.

**Comment by rdicroce** [comment]
Confirmed: after modifying the IIFEs to use $ instead of jQuery, it works.

**Comment by Mottie** [comment]
Thanks! I plan on pushing out a new release soon.
