### ISSUE TITLE
Filter function return value it is not acceptable

### ISSUE THREAD

**Issue by egemenozkan** [Mottie/tablesorter#1256]
Hello,
I am trying to filter grouping rows. I have written custom filterFunctions, and textExtraction. 
textExtractions works efficiently while sorting. While filtering, tablesorter calls custom filterFunctions, it gives true or false. However, it does not add ".filtered" or any class to row to hide/show  when it is true/false.

**Comment by Mottie** [comment]
Hi @egemenozkan!

Please share the code you are using.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
