### ISSUE TITLE
jQuery UI carat

### ISSUE THREAD

**Issue by jcander** [Mottie/tablesorter#1257]
In both **/dist/js/jquery.tablesorter.widgets.js** and **/dist/js/jquery.tablesorter.widgets.min.js**, the icon "caret" is spelled as "carat".  In the jQuery UI themeroller, it is spelled as "caret".

Because of this, the sorter arrows don't display correctly.

I have updated my files and thought I would make you aware of this issue.  Thanks!

**Comment by Mottie** [comment]
Hi @jcander!

I haven't updated to jQuery UI v1.12.0, but it does look like they renamed that class from "carat" to "caret". I'll probably have to include both to support the change.

Thanks!

**Comment by Mottie** [comment]
The change has only been made to the `widget-uitheme.js` file in the master branch. Once the next release is available, all the other files will get updated.
