### ISSUE TITLE
Issue with dangrossman/bootstrap-daterangepicker plugin

### ISSUE THREAD

**Issue by swinston100** [Mottie/tablesorter#1258]
I am trying to implement the following example - http://jsfiddle.net/abkNM/2188/ - as follows
My table's first column is the one I wish to impliment the filter on.

```js
$(function(){
  var $table = $("#revenuetable")
  
  .tablesorter({
    // this will apply the bootstrap theme if "uitheme" widget is included
    // the widgetOptions.uitheme is no longer required to be set
    theme : "bootstrap",
    // new in v2.7. Needed to add the bootstrap icon!
    headerTemplate : '{content} {icon}',
    // widget code contained in the jquery.tablesorter.widgets.js file
    // use the zebra stripe widget if you plan on hiding any rows (filter widget)
    widgets : [ "uitheme", "filter", "zebra" ],
    widgetOptions : {
      // reset filters button
      filter_reset : ".reset",
      // extra css class name (string or array) added to the filter element (input or select)
      filter_cssFilter: ['datepicker'],
      
      //filter_saveFilters: true
    },
    
    //sort the first column in ascending order by default
    sortList: [[0,1]]
    
  })
  
  .on('apply.daterangepicker', function(){
    $table.trigger('search');
  })
  
  .tablesorterPager({
    // target the pager markup - see the HTML block below
    container: $(".ts-pager"),
    // target the pager page select dropdown - choose a page
    cssGoto  : ".pagenum",
    // remove rows from the table to speed up the sort of large tables.
    // setting this to false, only hides the non-visible rows; needed if you plan to add/remove rows with the pager enabled.
    removeRows: false,
    // output string - default is '{page}/{totalPages}';
    output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
    //initial number of rows per page
    size: '10'
  })
  
  $('.datepicker').daterangepicker();;
  
  $('.reset').click(function(){
    //reset page and size on pager widget
    $('#revenuetable').trigger('pageAndSize', [1, 10]);
    //reset back to sortng by first column, ascending
    $('#revenuetable').trigger( 'sorton', [ [[0,1]] ] );
  });
  
});
```

I have included the minified script from your example in another file, without it I get another error so i know it is being read.
Any ideas or thoughts would be greatly appreciated. Thanks!

Steven

**Comment by Mottie** [comment]
Hi @swinston100!

Make sure to include all the other "External Resources" from that demo, which includes [`moment.min.js`](http://cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js).

**Comment by swinston100** [comment]
Hi Mottie
Thanks for the the quick reply.
I have included them.
Is there a particular order needed? 
Or is there a chance there is a clash with some other JS I am using elsewhere?

**Comment by Mottie** [comment]
I "think" moment.js needs to be loaded before the datepicker, and of course the tablesorter core needs to be loaded before the widgets & parsers. Other than that the order shouldn't matter.

If you're not seeing an error, what is happening? Are the filters even working? Or are you just not seeing the datepicker popup?

**Comment by swinston100** [comment]
The filters work , just no datepicker pop up.
I decided to create a single page (with jade) and start from zero.

```jade
doctype html
html
  head
    script(src='//ajax.aspnetcdn.com/ajax/jQuery/jquery-2.2.4.min.js')
    script(rel='//cdnjs.cloudflare.com/ajax/libs/moment.js/2.5.1/moment.min.js')
    script(rel='//netdna.bootstrapcdn.com/font-awesome/4.0.3/css/font-awesome.min.css')
    script(src='//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.6/js/jquery.tablesorter.min.js')
    script(src='//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.6/js/jquery.tablesorter.widgets.min.js')
    script(src='//netdna.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js')
    link(rel='stylesheet' href='//maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css')    
    link(rel='stylesheet' href='//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.26.4/css/theme.bootstrap.min.css')
    script(src='/javascripts/daterangepicker.min.js')
    script(src='/javascripts/demo.js')
  body
    button.reset reset
    table.tablesorter
      thead
        tr
          th w
          th w
          th w
          th Dates
      tbody
        tr
          td abc 1
          td 234
          td Ox
          td Jan 2, 2014

```

where `demo.js` is 

```js
$(function() {
  var $table = $('table')
    .tablesorter({
      theme: 'bootstrap',
      headerTemplate: '{content} {icon}',
      widgets: ['zebra', 'filter', 'uitheme'],
      widgetOptions: {
        filter_reset: '.reset',
        filter_cssFilter: ['', '', '', 'datepicker']
      }
    })
    .on('apply.daterangepicker', function() {
      $table.trigger('search');
    });
  $('.datepicker').daterangepicker();
});
```
 and `demo.css` is the CSS from your fiddle.

I still get the same error, having tried switching the script order many times.

Any ideas where I have gone wrong?

Thanks!

Steven

**Comment by swinston100** [comment]
![capture](https://cloud.githubusercontent.com/assets/10415661/16916200/4b8b3b50-4d04-11e6-9688-762836aa4bbb.JPG)
This is the error by the way!

**Comment by swinston100** [comment]
![image](https://cloud.githubusercontent.com/assets/10415661/16916995/55b4ef5a-4d08-11e6-8d2b-665647f8d8f5.png)
One other quick thing. I see it's easy to make a date range filter text as shown above.
is there anyway to change the filter format so that it is DD-MM-YYYY and not MM-DD-YYYY?
Thanks!

**Comment by swinston100** [comment]
I'm using nodejs by the way - maybe this is something to do with it?
http://blog.npmjs.org/post/112064849860/using-jquery-plugins-with-npm

**Comment by Mottie** [comment]
Try using the [non-minified version of date-picker](https://github.com/dangrossman/bootstrap-daterangepicker/blob/master/daterangepicker.js) and see where the error is occurring.

As for changing the date format, you'll need to use the datepicker's `locale` option to set that ([docs](http://www.daterangepicker.com/)).

**Comment by swinston100** [comment]
The non-minified version doesn't provide any more clues sadly.
The date format issue is not to do with date picker. Tablesorter, as it stands can be filtered by a range of dates (such as "06/29/2015 - 06/30/201") but only in the US Date format.

**Comment by Mottie** [comment]
The clue I needed was the line number of the error :grin: 

Anyway, I found the problem ([updated demo](http://jsfiddle.net/Mottie/ddLrqa5o/)):

1. The demo was using dates in the table formatted as `Jan 01, 2015`, when it should be consistent with the format you want, specifically `DD-MM-YYYY`.
2. An older version of the datepicker and moment.js were being used with the latest version of jQuery.
3. The last version of Bootstrap isn't compatible with jQuery 3.0+; so the demo is using jQuery v2.2.4.
4. The date format for the datepicker was added to format the range value.

```js
$(function() {
  var $table = $('table')
    .tablesorter({
      theme: 'bootstrap',
      headerTemplate: '{content} {icon}',
      dateFormat: "ddmmyyyy",
      widgets: ['zebra', 'filter', 'uitheme'],
      widgetOptions: {
        filter_reset: '.reset',
        filter_cssFilter: ['', '', '', 'datepicker']
      }
    })
    .on('apply.daterangepicker', function() {
      $table.trigger('search');
    });
  $('.datepicker').daterangepicker({
    locale: {
      format: 'DD-MM-YYYY'
    },
    startDate: '20-09-2013',
    endDate: '20-01-2015'
  });
});
```

**Comment by swinston100** [comment]
Thanks, you are a legend :+1:  :-) much appreciated!
