### ISSUE TITLE
How to Force Zebra Widget Update

### ISSUE THREAD

**Issue by zuve** [Mottie/tablesorter#1259]
I am currently using an external search bar, as it was much easier to use than the filter widget. However, because the search is made outside the plugin, the Zebra widget does not apply, until I do something that involves the plugin, such as sorting via one of the columns. Once I do that, Zebra refreshes and the rows have alternating colors again. How can I refresh Zebra forcibly? For example, refresh it within the search.js file? A simple way of refreshing zebra on a set amount of time would work, if it wouldn't cause any noticeable lag from the constant update. Any ideas would be helpful.

**Comment by TheSin-** [comment]
I'd recommend using the external filter that is builtin

https://mottie.github.io/tablesorter/docs/example-widget-filter-any-match.html

**Comment by Mottie** [comment]
You can refresh the zebra widget by refreshing all the widgets by triggering an [`appyWidgets` event](https://mottie.github.io/tablesorter/docs/#applywidgets):

```js
$('table').trigger('applyWidgets');
```

**Comment by zuve** [comment]
Thank you Mottie. Works perfectly and can be executed within the external search.js file.
