### ISSUE TITLE
Issue with columnSelector container 

### ISSUE THREAD

**Issue by snpefk** [Mottie/tablesorter#1260]
Hi! I have a strange behavior of columnSelector. When I init tablesorter i got a extra checkbox selectors for table and I can't understand why it happening  because i do nothing with container. Here is an example:
![2016-07-20 12 57 58](https://cloud.githubusercontent.com/assets/2883201/16976532/b45921bc-4e79-11e6-9b10-880ef41833a6.png)

**Comment by Mottie** [comment]
Hi @snpefk!

Are there hidden columns that the widget isn't hiding? If so, make sure to [disable](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#removing_a_column_from_the_selector) that column.

**Comment by snpefk** [comment]
No, there aren't any hidding columns. I have only 5 columns: 

`<thead>
    <tr>
        <th>№</th>
        <th>Специалист</th>
        <th>Цена</th>
        <th>Количество</th>
        <th>Сумма</th>
    </tr>
</thead>
<tfoot>
    <tr>
        <td></td>
        <td><b>Итого:</b></td>
        <td data-column="2">&nbsp;</td>
        <td data-column="3">233</td>
        <td data-column="4">16950</td>
    </tr>
    
</tfoot>
<tbody aria-relevant="all" aria-live="polite">
    <tr>
        <td>1</td>
        <td><a href="#" class="toggle">Case Neuromancer Dorset</a></td>
        <td></td>
        <td>1</td>
        <td>200</td>
    </tr>
    
</tbody>
            `

But widget return 7 selectors. And I also don't want to disable columns selectors manually beacuse i use same function for init table for diff tables. Is there another way to do this?

**Comment by Mottie** [comment]
Please make sure your HTML is valid. You can also set the [`debug` option](https://mottie.github.io/tablesorter/docs/#debug) to `true` and make sure that only 5 columns are being processed.

**Comment by snpefk** [comment]
I'm not sure but looks like my HTML is valid. Debug mode says that only 5 columns init. But I'm slightly confused about two columns in debug last table: (index) and empty one. There is supposed to be there?
![2](https://cloud.githubusercontent.com/assets/2883201/16979398/11d56a42-4e8b-11e6-9987-1b89ad38680f.png)

**Comment by Mottie** [comment]
Try [this validation service](https://validator.w3.org/#validate_by_input) because there is an extra column. 

I bet it's a `colspan` that adds an extra column, or two, or maybe two `<td>`'s in a row.

**Comment by snpefk** [comment]
That's right! It was colspan in `tfoot`. I didn't noticed because I'm copied that fragment from example. My fault. Sorry for disturb ant thank you.
