### ISSUE TITLE
How to Properly Sort a Column with Multiple Lines of Text

### ISSUE THREAD

**Issue by zuve** [Mottie/tablesorter#1263]
A table I am working on has one column in it which has multiple lines of text in one table cell. It appears:
<td>value1: example1
value2: example2
value3: example3</td>

When I attempt to sort this column, the table is sorted by its default sort, simply using the first column to sort. Is there a way to assign a custom value to that column that it uses to sort? If possible, it would be great to have a drop down list in the header of the column so that I could select to sort by one of a few custom attributes in the TD's for that column.

**Comment by Mottie** [comment]
Hi @zuve!

On the [home wiki page](https://github.com/Mottie/tablesorter/wiki#sorting) under sorting are several examples of sorting one column by multiple values. This might be the demo of interest to you; along with the associated [Stackoverflow](http://stackoverflow.com/questions/36060289/custom-sort-buttons-in-jquery-tablesorter-headers) question.

http://jsfiddle.net/abkNM/7862/

**Comment by zuve** [comment]
I'm wondering if it would be possible to do the same thing as your demo, but instead use a dropdown menu built in to the column to sort Data1, Data2, or Data3. In addition, would there be some way to set it so that it did not change the sorting(ascending or descending) when changing the dropdown menu?

**Comment by Mottie** [comment]
That requires even less code ([demo](http://jsfiddle.net/Mottie/abkNM/8415/)):

```js
$(function() {

  var $cell;
  $('table').tablesorter({
    theme: 'blue',
    textSorter: function(a, b) {
      var x = a.split('|'),
        y = b.split('|'),
        i = $cell.val();
      return $.tablesorter.sortNatural($.trim(x[i]), $.trim(y[i]));
    },
    initialized: function() {
      $cell = $('table thead .sort');
    }
  });

});
```
