### ISSUE TITLE
Bower install - invalid-meta warnings

### ISSUE THREAD

**Issue by stonio** [Mottie/tablesorter#1264]
I have imported `devDependencies` `"tablesorter": "jquery.tablesorter#^2.26.6"` in my `bower.json` file.

Command `bower install` displays:

	bower tablesorter#^2.26.6         invalid-meta The "description" is too long, the limit is 140 characters
	bower tablesorter#^2.26.6         invalid-meta The "main" field cannot contain minified files
Can we fix these warnings?

**Comment by Mottie** [comment]
Hi @stonio!

Wow bower is picky, it doesn't like minified css? Hmm, I guess I could copy one un-minified file over.
