### ISSUE TITLE
bower.json - add other attributes

### ISSUE THREAD

**Issue by stonio** [Mottie/tablesorter#1265]
Could you add other (recommended) attributes in `bower.json`?
+ [moduleType](https://github.com/bower/spec/blob/master/json.md#moduletype)
+ [keywords](https://github.com/bower/spec/blob/master/json.md#keywords)
+ [authors](https://github.com/bower/spec/blob/master/json.md#authors)
+ [homepage](https://github.com/bower/spec/blob/master/json.md#homepage)
+ [repository](https://github.com/bower/spec/blob/master/json.md#repository)

**Comment by Mottie** [comment]
Hi @stonio!

LOL I had all those in the bower.json originally, but removed them because there is a lot of duplication from the `package.json` file.... oh well.
