### ISSUE TITLE
Filter Widget External Inputs

### ISSUE THREAD

**Issue by ugrinwald** [Mottie/tablesorter#1267]
Hi Mottie.
In your example for Filter Widget External Inputs (https://mottie.github.io/tablesorter/docs/example-widget-filter-external-inputs.html) selecting the options  "Columns 0,3" and "Columns 1-2" does not seem to be working as expected. i.e. filter is still acting on ALL columns and not the one selected from select drop down.

**Comment by Mottie** [comment]
Hi @ugrinwald!

Thanks, I'll take a look.

**Comment by ugrinwald** [comment]
Thanks for looking into this Mottie
