### ISSUE TITLE
How to sort a table generated from JSON

### ISSUE THREAD

**Issue by zuve** [Mottie/tablesorter#1268]
I am currently making a table generated from JSON using the following loop:

```js
			window.onload = function() {
				var data = abilityStats.Abilities[0].Fast;
				
				for (var i in data) {
					var name = data[i].Name;
					var type = data[i].Type;
					var damage = data[i].Damage;
					var DPS = data[i].DPS;
					var energy = data[i].Energy;
					var EPS = data[i].EPS;
					document.getElementById('myTableBody').innerHTML += '<tr><td>' + name + '</td><td>' + type + '</td><td>' + damage + '</td><td>' + DPS + '</td><td>' + energy + '</td><td>' + EPS + '</td></tr>';
					$('table').trigger('applyWidgets');
				}
			}
```

And while the apply widgets is working to zebra the rows, sorting the headers, which are hard coded, they do not sort anything. Clicking on the headers makes the arrow appear, but no sorting happens.

**Comment by Mottie** [comment]
Hi @zuve!

Whenever new content is added to the `tbody`, you'll need to update the internal cache. Instead of using "applyWidgets", you'll need to use [`"update"`](https://mottie.github.io/tablesorter/docs/#update).

```js
$('#myTableBody')
  .html("...")
  .trigger("update"); // the "update" event bubbles up to the table
```
