### ISSUE TITLE
Date Sort 

### ISSUE THREAD

**Issue by jennardson** [Mottie/tablesorter#1270]
Hello, 

I have a table of search results with over 50,000 columns in the edge case scenario. All sorts work great except for the date sort. 

I have it in MM/DD/YYYY HH:MM AM format. At a certain point in the algorithm, it will no longer sort the dates - so the first half of my results are sorted by date, but the rest is still out of order. It would also be great for the time to be in 12 hour format rather than 24 hour format (I am looking for a date format trick.) I will attach a photo as an example and I will mark where the date sort stops.

Thank you in advance,
Jenna

![datesort](https://cloud.githubusercontent.com/assets/20860719/17445848/3c148d46-5b0c-11e6-916c-d5bd27fa3660.JPG)

**Comment by Mottie** [comment]
Hi @jennardson!

Change the [`dateFormat` option](https://mottie.github.io/tablesorter/docs/#dateformat) to `"ddmmyyyy"`.

There is also a [metric parser](https://mottie.github.io/tablesorter/docs/example-parsers-metric.html) which can sort your size column, if you include sizes like `MB`.

**Comment by Mottie** [comment]
Are you using the pager (with ajax)? How are you adding rows to the table?

**Comment by jennardson** [comment]
I am not using a pager. I am just appending the rows of data to the table with JavaScript.

**Comment by Mottie** [comment]
Then after adding rows to the table, you'll need to [trigger an "update"](https://mottie.github.io/tablesorter/docs/#update):

```js
$("tbody")
  .append("<tr>...</tr>")
  .trigger("update");
```

**Comment by jennardson** [comment]
Unfortunately, that did not work. It will sort everything else all the way through, just not the date.

**Comment by Mottie** [comment]
Please share the code you're using.

**Comment by jennardson** [comment]
Thank you, but unfortunately I can't due to client restrictions.

**Comment by Mottie** [comment]
I just want to see the code that adds rows to the table, and triggers an update. I don't need details. That stuff can be removed.

**Comment by jennardson** [comment]
Let me clear it with my client. This may take me a minute.

**Comment by Mottie** [comment]
One more thing you can check... make sure the new rows are being added to the same `tbody` as the others.

And as for changing the date format, it might be best to do that conversion while adding the new rows to the table since you're talking about a huge number of rows.

**Comment by Mottie** [comment]
Any update on this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
