### ISSUE TITLE
sortRestart not working on chrome

### ISSUE THREAD

**Issue by Kindot** [Mottie/tablesorter#1273]
Hi,
thanks for this script, it is very useful. I am using it with chrome and the only thing that doesn't work is the sortRestart option, that instead works on other browsers.
Is there a solution for this?
Thanks in advance

**Comment by Mottie** [comment]
Hi @Kindot!

I just tested the option in [this demo](http://jsfiddle.net/Mottie/bbxxomhx/119/). It's working for me as expected.

Are you sure you don't mean to use the `sortReset` option?

* [`sortRestart`](https://mottie.github.io/tablesorter/docs/#sortrestart) - Click on each header once, then click each again, this option will make the initial sort direction *always* start with an ascending sort (as set by the [`sortInitialOrder` option](https://mottie.github.io/tablesorter/docs/#sortinitialorder)).
* [`sortReset`](https://mottie.github.io/tablesorter/docs/#sortreset) - Click on a header a third time to remove the sort from the column (reset to the original table order).

**Comment by Kindot** [comment]
I am sure it's sortRestart, I am trying it for two days, fcturi.altervista.org/statistiche.php (it takes a bit to load, I will fix it later XD) try by yourself.
Actually i tried that demo on chrome and it worked so i didn't try it on a different browser, but now I am sure that works on edge and not on chrome :( I really don't know why

**Comment by Kindot** [comment]
Omg it's not working to me :S can it be the chrome version or something like that? I will try to uninstall and reinstall it, however thanks for the support :)

**Comment by TheSin-** [comment]
working in safari

**Comment by Kindot** [comment]
It works in chrome on my android phone, so there is something wrong with my pc. Thanks again and good job with this script ;)

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
