### ISSUE TITLE
doc - Error 404 links

### ISSUE THREAD

**Issue by stonio** [Mottie/tablesorter#1275]
I have check links of page https://mottie.github.io/tablesorter/docs/ with _[W3C Link Checker](https://validator.w3.org/checklink?uri=https%3A%2F%2Fmottie.github.io%2Ftablesorter%2Fdocs%2F&hide_type=all&depth=&check=Check)_ and found 3 broken links: 

 + http://sugarjs.com/sorting
 + http://sugarjs.com/dates
 + widget-build-table.html (https://mottie.github.io/tablesorter/docs/widget-build-table.html)

**Comment by Mottie** [comment]
Hi @stonio!

Thanks for reporting this! I spent a bunch of time updating the demos to use Sugarjs v2.0+, but ran into a few issues - see [demo](https://mottie.github.io/tablesorter/docs/example-option-custom-sort.html).
