### ISSUE TITLE
Custom Pager Controls Error

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1276]
I'm getting pages to the left of page 1 (e.g. 0 or -1  0) and getting a superfluous extra page at the end that does not belong (e.g. 1  |  2  |  3  |  4  where there are only three pages of results.

Examples from Issue 1:
![pag_error1](https://cloud.githubusercontent.com/assets/10552379/17868489/0930544a-687d-11e6-9434-e0806eb5722c.png)
![pag_error2](https://cloud.githubusercontent.com/assets/10552379/17868490/0931c29e-687d-11e6-907f-8acf54d1f8c0.png)
Issue 2:
![pag_error3](https://cloud.githubusercontent.com/assets/10552379/17868493/0a21e4a4-687d-11e6-8dfd-61853b3bc875.png)

**Comment by Mottie** [comment]
Hi @aetna-wsa!

Please modify [this demo](https://jsfiddle.net/Mottie/Lr6p93xu/3/) to duplicate the issue because I can't get it to behave in that manner. Thanks!

**Comment by aetna-wsa** [comment]
Fire is out -- updated all files and it is working properly now. Thanks.

**Comment by aetna-wsa** [comment]
Scratch my last comment - problem remains in IE11. I'm working on a fiddle.

**Comment by aetna-wsa** [comment]
Okay, here is the problem in IE.
https://jsfiddle.net/dihakz/zjte5Lgc/

**Comment by Mottie** [comment]
The page numbers should no longer be out-of-range. The fix is currently only available in the master branch.

[Updated demo](https://jsfiddle.net/Mottie/zjte5Lgc/1/)

**Comment by Mottie** [comment]
Grrr, I think I broke a few things.

**Comment by Mottie** [comment]
Ok, *now* it should all be fixed.

I've also changed a few things!

* Modified `adjacentSpacer` and `distanceSpacer` to include surrounding span element.

    ```js
    // spacer for page numbers next to each other
    adjacentSpacer : '<span> | </span>',
    // spacer for page numbers away from each other (ellipsis = &amp;#133;)
    distanceSpacer : '<span> &#133; <span>',   
    ```
  this will allow you to add a class name or change the wrapping element to fit your page style 
* **Using the keyboard has changed!**
  * The keyboard keys will only work IF a pager element has focus.
  * The `addKeyboard` function now includes <kbd>left</kbd>, <kbd>right</kbd>, <kbd>up</kbd>, <kbd>down</kbd>, <kbd>pageUp</kbd>, <kbd>pageDown</kbd>, <kbd>Home</kbd> and <kbd>End</kbd>.
  * A new `pageKeyStep` option was added to allow setting the number of pages to skip on <kbd>pageUp</kbd> or <kbd>pageDown</kbd>.

Again, these updates are currently only available in the master branch.

[Updated demo](https://jsfiddle.net/Mottie/zjte5Lgc/2/)

**Comment by aetna-wsa** [comment]
Confirmed this is no longer an issue. Thanks, Rob!

**Comment by Mottie** [comment]
Tablesorter v2.27.7 is now available.
