### ISSUE TITLE
Tablesorter doesn't work with node.

### ISSUE THREAD

**Issue by rokshis** [Mottie/tablesorter#1277]
I can't manage to get the tablesorter to be working with node and webpack.

It is successully installed.

Example of my code is:

`require('tablesorter')

$(function() {
     // some procedures
     $('#testtable').tablesorter()
})
`
The error it throws is: "Uncaught TypeError: $(...).tablesorter is not a function"
I have to mention, that it works just all fine if the tablesorter is included as a script via html in head.

**Comment by Mottie** [comment]
Hi @rokshis! Sorry I didn't get back to you sooner... I've been having computer issues.

Did you solve the problem? Maybe you can share how it was fixed here in case others encounter a similar issue.

**Comment by rokshis** [comment]
I just needed to export global jQuery in order for the tablesorter to work.
