### ISSUE TITLE
emptyTo not working with custom parser

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#1278]
empty or emptyTo seem to be working correctly, but not if applied to a column with a unique parser. My parser is as follows, if that helps:

```
$.tablesorter.addParser({
	id: 'pihmsDate',
	is: function(s){
		return false;
	},
	format: function(s){
		s = s.replace(/JAN/,01).replace(/FEB/,02).replace(/MAR/,03).replace(/APR/,04).replace(/MAY/,05).replace(/JUN/,06).replace(/JUL/,07).replace(/AUG/,08).replace(/SEP/,09).replace(/OCT/,10).replace(/NOV/,11).replace(/DEC/,12);
		s = s.replace(/(\d{2})[\/\-](\d{1,2})[\/\-](\d{4})/, '$3/$2/$1');
		return $.tablesorter.formatFloat(new Date(s).getTime());
	},
	type: 'numeric'
});

```

**Comment by Mottie** [comment]
Hi @aetna-wsa!

The parser isn't returning an empty string, it is returning `NaN` because `new Date("").getTime()` returns `NaN` which is what the `formatFloat` function returns.

Try these changes:

```js
$.tablesorter.addParser({
    id: 'pihmsDate',
    is: function(s){
        return false;
    },
    format: function(s){
        var str = s.replace(/JAN/,01).replace(/FEB/,02).replace(/MAR/,03).replace(/APR/,04).replace(/MAY/,05).replace(/JUN/,06).replace(/JUL/,07).replace(/AUG/,08).replace(/SEP/,09).replace(/OCT/,10).replace(/NOV/,11).replace(/DEC/,12);
        str = str.replace(/(\d{2})[\/\-](\d{1,2})[\/\-](\d{4})/, '$3/$2/$1');
        var date = str ? new Date(str) : str;
        return date instanceof Date && isFinite( date ) ? date.getTime() : s;
    },
    type: 'numeric'
});
```

Actually, I'm not sure why that parser is needed, at least for English named dates. I believe all modern browsers will correctly parse dates with the three letter month name:

```
> new Date('JAN 02 2016')
// Sat Jan 02 2016 00:00:00 GMT-0600 (Central Standard Time)
> new Date('02 JAN 2016')
// Sat Jan 02 2016 00:00:00 GMT-0600 (Central Standard Time)
```

**Comment by aetna-wsa** [comment]
Wow... I never considered that NaN was the value being returned. Nor did I know that three letter month names can be parsed as easily as any other date - I always found it to be an awkward format. Both these solutions work, but I'm going to go with shortDate, now, with the format of dd-mmm-yyyy

I appreciate the help, Rob. Thank you!

**Comment by aetna-wsa** [comment]
I am now using shortDate with the format described above. When I sort that column in either ascending or descending order, all empty cells stay at the bottom. Shouldn't the behavior reverse when moving from asc to desc (or vice versa)?

**Comment by Mottie** [comment]
The [`emptyTo` option](https://mottie.github.io/tablesorter/docs/#emptyto) has multiple settings - try them in [this demo](https://mottie.github.io/tablesorter/docs/example-option-sort-empty.html).

**Comment by aetna-wsa** [comment]
Perfect! The additions of `emptyMax` and `emptyMin` are fantastic. Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
