### ISSUE TITLE
Sorting dates like: "dd-mm"

### ISSUE THREAD

**Issue by theogeels** [Mottie/tablesorter#1279]
Hello,
Thank you for the nice tablesorter plug-in! I want to sort columns with a date-format of 'dd-mm', so without the year information. We don't actually need the year and is shortens the width of the column.
How do I proceed? Thanks in advance!

**Comment by Mottie** [comment]
Hi @theogeels!

For this you'll need to create a custom parser... If the year doesn't matter then I picked an arbitrary year of 2000; no other reason really <img title=":_ drunk :" src="https://cloud.githubusercontent.com/assets/136959/13512352/ab7bd68e-e15f-11e5-8475-64f2678be28e.gif">

Create a parser to flip the month & day, add the arbitrary year and then check if it's a valid date:

```js
$.tablesorter.addParser({
  id: 'dd-mm',
  is: function() {
    return false;
  },
  format: function(str) {
    var date,
      // force dd-mm to use some arbitrary past date so
      // sorting stays consistent
      s = str.split('-').reverse().join('/') + '/2000';
    date = s ? new Date(s) : s;
    return date instanceof Date && isFinite(date) ? date.getTime() : str;
  },
  type: 'numeric'
});
```

Also make sure to include a class name in the header

```html
<th class="sorter-dd-mm">Date</th>
```

Or, include a [`headers` option](https://mottie.github.io/tablesorter/docs/#headers) to set the sorter.

Initialize tablesorter and it should work - [demo](https://jsfiddle.net/Mottie/aqt73vz2/)!

**Comment by theogeels** [comment]
Thanks a lot Mottie!
Nice solution, but it just didn't work in my application. It's quite a complex page I have been php-ing together anyway. Don't get the reason. Now back to using the 'order' option of mysql and another. ajax-read.
