### ISSUE TITLE
Filter only firing input event in Firefox for Android

### ISSUE THREAD

**Issue by Corrodian** [Mottie/tablesorter#1280]
When browsing to
https://mottie.github.io/tablesorter/docs/example-option-show-processing.html

My Android Firefox 48 only fires an input event when a key is pressed in the filter columns which is ignored by the tablesorter code unless the input field is empty. There's a comment in the code:
'only "input" event fires in MS Edge when clicking the "x" to clear the search'

This means on desktop the search happens on every keypress and on mobile only after pressing the virtual keyboard's search key. On Android Chrome it works on every keypress.

**Comment by Mottie** [comment]
Hi @Corrodian!

Thanks for letting me know.

**Comment by Mottie** [comment]
Hi @Corrodian! I added a "fix" to the master branch. Please test it and let me know if it behaves as you expect. Thanks!

**Comment by Corrodian** [comment]
@Mottie Thanks for the quick fix.

Tested on Windows 10 desktop Firefox 48, Chrome 52, Edge, IE 11 and Opera 39.
Android Firefox 48 and Chrome 52.

Seems to be working without issues.

**Comment by Mottie** [comment]
Tablesorter v2.27.7 is now available.
