### ISSUE TITLE
Grouping Widget headers

### ISSUE THREAD

**Issue by mabuzer** [Mottie/tablesorter#1281]
I used tablesorter, things work great for me, but I'm currently having an issue related to how enable grouping from user drag-and-drop of given header, instead of clicking while keeping the click for sorting only.

Thanks for your help.

**Comment by Mottie** [comment]
Hi @mabuzer!

I'm not sure I understand exactly what you're asking. Do you want the ability to drag and drop group headers? Do you mean something [like this](http://demos.telerik.com/kendo-ui/grid/index)?

**Comment by mabuzer** [comment]
Yes, exactly, I was able to implement the D&D part, but I cannot disable grouping from table headers. I was asking if there's an easy way, to have the group widget installed while disable the group action from the headers.

**Comment by Mottie** [comment]
You can remove the binding from the table headers like this:

```js
c.$table.off('click', 'tr.group-header');
```

I would love to see what you've done. Could you modify [this demo](https://jsfiddle.net/Mottie/5vdxyng0/) with what you have? I have started using [dragula](https://github.com/bevacqua/dragula/) in my projects and I think it's awesome! I've included it in the external resources if it would work for you.

**Comment by mabuzer** [comment]
Thank you for the [dragula](https://github.com/bevacqua/dragula/) link, I use jquery-ui for d&d, of course,  later on I will fork you fiddle, and have the code for you. 

Thank you for your quick reply.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
