### ISSUE TITLE
Grouping: Case Sensitive option

### ISSUE THREAD

**Issue by mtgtnt** [Mottie/tablesorter#1284]
I have been trying to find a way to not loose case when using group.
Example:
Test Role A (TRA)
Test Role B (TRB)

It seems that everything is converted to lower case before grouping and must then use text-transform (uppercase is not an option though I wish it was). Is there a way to stop this from occurring and allow it to group case sensitive?

**Comment by Mottie** [comment]
Hi @mtgtnt!

The group widget pulls data from the cache which is set to all lower case by the [`ignoreCase`](https://mottie.github.io/tablesorter/docs/#ignorecase) option. If setting that to `false` doesn't work for you, maybe I can figure something else out.

**Comment by mtgtnt** [comment]
That worked as required. I should have seen that property.

The other problem I am running into now is when using sortResetKey.
Together with grouping, it removes the grouping also.

I need to be able to do both or either.
Examples:
1) Table has multisort and user resets. It clears the sort and removes the grouping. It should keep the grouping.
2) Table has been sorted and user wants to remove the grouping to view entire table without group headers. I cannot find a way to do this. I am probably again missing the property to do this.

**Comment by Mottie** [comment]
There is a [`group_forceColumn` option](https://mottie.github.io/tablesorter/docs/example-widget-grouping.html#group_forcecolumn). Set it to apply a group without a sort, but keep in mind that grouping unsorted content will possibly result in repeated group headers.

You can change this setting dynamically. To apply the change use [`applyWidgets` method](https://mottie.github.io/tablesorter/docs/index.html#applywidgets).

```js
$('table').trigger('applyWidgets');
```

**Comment by mtgtnt** [comment]
group_forceColumn wont work as the groups need to change based on the first sort column.
I think it may be best to just remove the option of reset unless there is a way to reset to default 'sortList'.

As for the dynamic changes with applyWidgets, perfect. I see how the example works now. Testing that now.

**Comment by mtgtnt** [comment]
This actually works better since its required to have it sorted on at least one column due to the grouping.
I set sortResetKey: '' so they dont use.

Thanks for your time on all of this.

**Comment by Mottie** [comment]
Awesome!
