### ISSUE TITLE
Grouping Widget: Separate grouping and sorting

### ISSUE THREAD

**Issue by cgarwood** [Mottie/tablesorter#1286]
It would be nice to have separate grouping and sorting.

For example if you have the table:

| ColA | ColB | ColC |
| --- | --- | --- |
| A | 2 | 5 |
| A | 1 | 3 |
| B | 1 | 7 |
| B | 3 | 2 |

It would be nice to group the table by ColA (sorted alphabetically), but sort the table within the groups by ColB or ColC

**Comment by Mottie** [comment]
Hi @cgarwood!

Is the first column never sorted? If you set the [`group_forceColumn` option](https://mottie.github.io/tablesorter/docs/example-widget-grouping.html#group_forcecolumn) and sort "ColC" the group headers will show "B", "A", "B" - [demo](https://jsfiddle.net/Mottie/4ac5kr3o/48/).

If you use `sortForce` to always sort the first column along with `group_forceColumn`, then maybe this gives you the result you want ([demo](https://jsfiddle.net/Mottie/4ac5kr3o/49/))?

```js
$(function(){

  $("#groups").tablesorter({
    theme : "blue",
    sortForce: [[0, 0]],
    widgets: [ "group", "filter", "zebra" ],
    widgetOptions: {
      group_forceColumn: [0]
    }
  });

});
```

**Comment by cgarwood** [comment]
@Mottie thanks for the quick reply!

The second example using sortForce and group_forceColumn is closest to what I'm wanting to achieve, but I would like to be able to switch which column is used for grouping without editing the JS file (for example, with a Group By: dropdown above the table). Is that possible using that method?

**Comment by Mottie** [comment]
The `group_forceColumn` option can be dynamically set... so in your dropdown, you can modify it then apply whatever sort you want.

**Comment by Mottie** [comment]
I'm not completely opposed to adding a new feature, I'd need to get a better idea of how to implement it when I do.

**Comment by cgarwood** [comment]
So it seems that I have to set sortForce and group_forceColumn to whatever I want the grouping to be, and then actually click on a table header to change the sort options once the page loads. This gives me the correct grouping. However, for some reason it doesn't give me the correct grouping on first load of the page, I have to actually click a table header to get it to fix the groups. From outside of the constructor how would I go about changing the sortForce and group_forceColumn values?

**Comment by Mottie** [comment]
Add a `sortList` option to apply an initial sort ([demo](https://jsfiddle.net/Mottie/4ac5kr3o/50/)):

```js
$(function(){
  $("#groups").tablesorter({
    theme : "blue",
    sortForce: [[0, 0]],
    sortList: [[0, 0]],
    widgets: [ "group", "filter", "zebra" ],
    widgetOptions: {
      group_forceColumn: [0]
    }
  });
});
```

**Comment by kczx3** [comment]
How can we avoid something such as this when using your method?
[https://jsfiddle.net/5hqdxotm/](url)

The initial sort is not abiding by the group_forceColumn.  When you click to sort after initialization, then it functions correctly.

**Comment by Mottie** [comment]
Hi @kczx3! I'm not sure what you are expecting. The grouping is applied to the second column... please remember that the `group_forceColumn` uses zero-based column indexing.

**Comment by kczx3** [comment]
Correct, but why are there two groups for "B"?  If you sort on column A after the demo loads, then the two group B's become one.  How can we make it do this on load?

**Comment by Mottie** [comment]
Ahh, I forgot that setting a `sortList` initially and through the API will ignore the `sortForce`  and `sortAppend` settings. This allows you to programmatically set the sort without interference. I should make that more explicit in the documentation. Changing this behavior now would break backwards compatibility.

So on initialization, also include the `sortForce` column - [demo](https://jsfiddle.net/waxhjyzL/2/).

```js
$(function(){

  $("#groups").tablesorter({
    theme : "blue",
    sortForce: [[1, 0]],
    sortList: [[1,0], [0, 0]],
    widgets: [ "group", "filter", "zebra" ],
    widgetOptions: {
      group_forceColumn: [1]
    }
  });

});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
