### ISSUE TITLE
How call tablesorter a second time (after changing the data in the table)?

### ISSUE THREAD

**Issue by Gitward** [Mottie/tablesorter#1287]
After running tablesorter on a give table using

```
$("#table").tablesorter();
```

I remove to content of the table using:

```
$("#table").html("<thead>...</thead><tbody>...</tbody>");
```

And add new entries using:

```
$("#table").find('tbody').append("<tr>...</tr>")
```

In Order to make the new contents sortable, I run tablesorter again:

```
$("#table").tablesorter();
```

Infortunately, the table is not sortable afterwards - why?

**Comment by Mottie** [comment]
Hi @Gitward!

Tablesorter binds to the header cells, so when you remove any cells in the `thead` you essentially need to rebind to the header cells. This can be done in one of these three ways:

1. Completely reinitialize tablesorter. Meaning, [destroy](https://mottie.github.io/tablesorter/docs/#destroy) it then re-apply it.

    ```js
    // pass a false boolean to *not* remove the 
    // "tablesorter" class name to prevent a FOUC
    // .trigger("destroy", [removeAllClasses, callback]);
    $("#table").trigger("destroy", [false, function(){
        // reinitialize tablesorter
        $("#table").tablesorter();
    }]);
    ```

2. It might be easier to wrap the table in a `<div id="wrapper">...</div>`, or something similar. Then use `$("#wrapper").empty();` to clear out the table. But, there is an issue with a memory leak (#1034) using this method that I can't seem to isolate.

3. Lastly, there is an ["updateAll" method](https://mottie.github.io/tablesorter/docs/#updateall) which can be used when modifying both the `<thead>` and `<tbody>` content, but it has not been well optimized to work with all widgets. I don't know which widgets you're using, so please test this method carefully.

I'm not sure which method would work best in your case so try each one out and see

**Comment by Herst** [comment]
You are not just removing the contents of the table but also all the columns, headers and such. Is this really what you want?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
