### ISSUE TITLE
[FYI] Incorporated Tablesorter into Grav CMS

### ISSUE THREAD

**Issue by Perlkonig** [Mottie/tablesorter#1290]
I've created [a plugin to incorporate Tablesorter](https://github.com/Perlkonig/grav-plugin-tablesorter) into [Grav CMS](http://getgrav.org).

Thanks for a great fork! I was glad I found it!

**Comment by Mottie** [comment]
Thanks @Perlkonig!

I've added a link to to the main readme!
<img title=":_badger:" src="https://cloud.githubusercontent.com/assets/136959/13512240/15d31412-e15f-11e5-8577-06cff0976977.gif">

**Comment by Perlkonig** [comment]
Cheers!
