### ISSUE TITLE
HTML table data changes, possible to update only data?

### ISSUE THREAD

**Issue by shawnp0wers** [Mottie/tablesorter#1294]
It's possible I'm a bit too dumb to even ask the right question, but I've been pulling my hair out for days. My apologies in advance.

I have a fairly large (1300 rows, 25 columns) HTML table generated from a PHP script. I'm using sorting and filtering, and even set up the widgets to save the sort/filter information. Refreshing the page does allow me to keep the sort/filter info I had. Which is awesome.

The problem is, refreshing the page is disruptive, as the page blanks, the table loads, stretches, then applies the tablesorter code, and is back to where it was. I'd really like to refresh just the HTML data in the table (not the thead or tfoot, just tbody) using AJAX, but when I do, I lose all tablesorter functionality.

I'm a good PHP scripter, but Javascript befuddles me. I basically copy/paste/pray. From what I can tell I need to somehow do a $("#table").trigger("update") after reloading the DIV, but I can't figure out how to make that happen. Honestly, even understanding what the trigger line is/does is slightly beyond my reach.

If your initial thought is "RTFM, loser", well, fair enough. But I've read the docs, and I'm missing something. I've tried both an automatic refresh with AJAX (again, copy/pasted code), and I've tried creating a button to refresh the data. Both _do_ refresh the data, but no matter what I do, I can't get tablesorter to continue working. Any help would be greatly appreciated, and again, I apologize for my ignorance.

**Comment by Mottie** [comment]
Hi @shawnp0wers!

No worries!

So are you using the pager addon, plugin or your own ajax functions to update the table?

The easiest method would be to use the pager widget, or plugin, along with setting the ajax options to communicate with your server and have it return just the data (raw HTML would be the easiest) for the `tbody`. The [`ajaxProcessing` option "object" example](https://mottie.github.io/tablesorter/docs/#object) would be the best one to use. When using the pager with the built-in ajax, you won't need to trigger an "update" on the table.

If you don't want to use the pager widget/addon, I could better help you if you shared the code you are using. There are a bunch of demos on the [home wiki page](https://github.com/Mottie/tablesorter/wiki) which also provide examples. This demo in particular might help you: http://jsfiddle.net/Mottie/ns6xhf5m/.

I'm going on vacation next week, for a month, but I'll be available until then. After that, use the IRC channel for additional help: [![irc-image]][irc-url]

[irc-url]: https://kiwiirc.com/client/irc.freenode.net#tablesorter
[irc-image]: https://img.shields.io/badge/irc-%23tablesorter-yellowgreen.svg

Hmm, I just noticed that the demo using the pager widget that I just shared above doesn't work properly. You have to sort the empty table before it'll work. I'll try to fix that tonight; but the pager addon demo doesn't appear to have any issues: http://jsfiddle.net/Mottie/9nfu2ja5/.

**Comment by shawnp0wers** [comment]
I just want to follow up, Mottie is an incredible human being (or possibly cyborg, we didn't really discuss it). This code ended up being the solution:

http://jsfiddle.net/Mottie/ns6xhf5m/6/

Basically, make sure to add <table id="status"> to identify the table that should be refreshed, and this script refreshes the page based on the timer, or by pressing a button.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
