### ISSUE TITLE
Filter input loses focus with customPagerControls

### ISSUE THREAD

**Issue by themilkman** [Mottie/tablesorter#1296]
Hi again @Mottie,

I think there is a bug in the (btw really great, thanks!) customPagerControls widget.

Typing 'M' in the Major column filter at your example below and waiting for the filter result, the input focus is set to the pager-section, not the filter input anymore where you might continue typing.

beta-testing/example-pager-custom-controls.html

Tested under Linux with Firefox and Chromium.

Cheers!

**Comment by Mottie** [comment]
Hmm, that is a problem.

Ok, I'll try to get a fix in soon.

Just so you know, I'm going out of town next week, for a month. So I'll try to get stuff cleaned up before I go.

**Comment by themilkman** [comment]
Okay, thanks for for taking a look at it! 

And in advance: have a good journey :)

**Comment by themilkman** [comment]
Thanks for your quick release, works like a charm :-)
