### ISSUE TITLE
Sort Horizontally by using tablesorter plugin

### ISSUE THREAD

**Issue by Albion87** [Mottie/tablesorter#1300]
Hi,
Is there any way to sort horizontally (from left - right)  by using Tablesorter.
Here's the way i tried http://jsfiddle.net/Albion87/pnyamdwf/12/
with this it's easy to sort vertically but don't know how to sort horizontally( sort when select a row)

**Comment by Mottie** [comment]
Hi @Albion87!

Sorting horizontally would require the reordering of the columns. That is not currently possible with tablesorter. I think what you might be looking for is something like [pivottable](http://nicolas.kruchten.com/pivottable/examples/index.html). Also see #838.

**Comment by Mottie** [comment]
This feature likely won't happen, unless you would prefer to pivot the table... then please follow #838.
