### ISSUE TITLE
Grouping with pager don't take the last row into account.

### ISSUE THREAD

**Issue by PeuX** [Mottie/tablesorter#1302]
Hi, first thanks for your great work :)
In my project i use your tablesorter with group widget and pager plugin.
I notice that the last row, if it has a different group the plugin don't group it.
For change this behavior i change this line in widget-grouping.js - Line 211 (v2.27.6):
`end = hasPager ? p.endRow - ( p.ajax ? p.startRow : 0 ) : norm_rows.length;`
to 
`end = hasPager ? p.endRow +1 - ( p.ajax ? p.startRow : 0 ) : norm_rows.length;`
It work for me but i don't know if it has side effect...

Bye (and thanks again for your work :) )

**Comment by Mottie** [comment]
Hi @PeuX!

Sorry for the long delay, I've been on an extended vacation.

Thanks for reporting this problem. I will try to spend some time looking at this problem once I catch up with other higher priority issues. It would help me greatly if you could provide an example - you can modify [this demo](https://jsfiddle.net/wty134u7/53/). Thanks!

**Comment by Mottie** [comment]
Any update on this issue? A demo of the problem would really help me troubleshoot the problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
