### ISSUE TITLE
widget-math and prefix/suffix

### ISSUE THREAD

**Issue by zod6** [Mottie/tablesorter#1305]
Documentations says that there are options math_prefix and math_suffix but in code I only see math_wrapPrefix and math_wrapSuffix.
Bug in docs or code?

**Comment by Mottie** [comment]
Hi @zod6!

Sorry for the long delay in responding, I've been on an extended vacation.

This does look like a bug in the code. I changed it in the code, but when I tested it, it wasn't working as expected. I'll take a better look at it once I catch up with my other work.
