### ISSUE TITLE
 StickyHeaders: widget doesn't update sticky header class names after sorting

### ISSUE THREAD

**Issue by sanex3339** [Mottie/tablesorter#1306]
Hi, i got following problem - StickyHeaders widget doesn't update sticky header class names after sorting.

I look at widget source code and looks like event on this line not triggered:
https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-stickyHeaders.js#L213

For test i replaced `'pagerComplete' + namespace` event on `click` event and class names became changing.

code:

``` javascript
import 'tablesorter/dist/js/jquery.tablesorter';
import 'tablesorter/dist/js/jquery.tablesorter.widgets';

//...

$el.tablesorter({
    widgets:['stickyHeaders'],
    widgetOptions: {
        stickyHeaders_attachTo: container,
        stickyHeaders_appendTo: container
    }
});
```

**Comment by sanex3339** [comment]
Ping

**Comment by sanex3339** [comment]
ping

**Comment by Mottie** [comment]
Hi @sanex3339!

Sorry for not responding earlier... I was on a month-long vacation and I got back a little over a week ago. In a rush to catch up, I thought I responded to this issue since it is related to #1313.

Once I get settled, I will start working on tablesorter issues again.

Sorry for the delay!

**Comment by sanex3339** [comment]
Thank you

**Comment by Mottie** [comment]
Ok, now that I've had a little time to look at this, I can reproduce the issue. Would you please update [this demo](https://jsfiddle.net/wty134u7/58/) to show the problem?

I added this same request in issue #1313, so if you see one there, you probably won't need to make another demo. 

Thanks!

**Comment by sanex3339** [comment]
So, we found problem. 
In normal header in all unsorted columnbs all `<th>` elements have `tablesorter-headerUnSorted` classes.

In sticky header `<table>` `<th>` elemens in unsorted columns don't have `tablesorter-headerUnSorted` classes and this looks strange.

In our project we have following styles:

```
    &.tablesorter-headerUnSorted {
      .tablesorter-header-th-variant("\f0dc", @at-main-color-silent);
    }

    &.tablesorter-headerDesc {
      .tablesorter-header-th-variant("\f0dd", @at-main-color);
    }

    &.tablesorter-headerAsc {
      .tablesorter-header-th-variant("\f0de", @at-main-color);
    }
```

So, this styles works fine in main `<thead>` and don't work for sticky `<thead>` because this `<thead>` don't have `tablesorter-headerUnSorted`  class.

**Comment by Mottie** [comment]
Ok, now I'm even more confused. 

The demo does have the `tablesorter-headerUnsorted` class on sticky header table cells. I just checked this in Chrome, Firefox and IE11... Edge isn't working just yet.

What is the `&` in the SASS indicating? The sticky header table is appended *after* the original table, so if it an ID, then that may be the issue.

**Comment by sanex3339** [comment]
We have 2 cells in sticky table, `cellA` and `cellB`.
By default they both have class `tablesorter-headerUnSorted`.

Now click on `cellA` one or few times. Then click on `cellB` one or few times.
After that, `cellA` wont have class `tablesorter-headerUnSorted`

**Comment by sanex3339** [comment]
![out](https://cloud.githubusercontent.com/assets/9210534/20599739/d7ccc2de-b260-11e6-868d-9b7fc901f1d4.gif)

**Comment by Mottie** [comment]
Thanks! I see the problem now!

**Comment by sanex3339** [comment]
thanks!
