### ISSUE TITLE
Tablesorter output colspan issue

### ISSUE THREAD

**Issue by kittensareprettyokay** [Mottie/tablesorter#1309]
I was having some issues outputting a CSV with multiple header rows, some of which included colspan attributes. I resolved the issue by modifying my local widget-output file, but I wanted to share the issues I was having here. 

The issue was that the colspan headers were being repeated an appropriate amount of times, except for the first cell, which was repeating twice instead of the specified four times. My issue was in the process colspans section of the code. 

When looping through to colspanLen, it starts from an index of one 
for (col = 1; col <= colspanLen; col++)

Then when it was supposed to increase the cellIndex count based on the number of filled cells in this line
while (typeof tmpRow[rowIndex][cellIndex] !== 'undefined') { cellIndex++; }
it would start from index of zero. Since the colspan iteration starts from 1, the element in the 0 position of the temporary row was always undefined, and would break the loop. 

The solution that has worked for me is to change the colspan iteration to be zero indexed. 
for (col = 0; col < colspanLen; col++)

**Comment by thezoggy** [comment]
sounds like cellIndex just needs to be initialized with 0? costs less than checking type/lookups

**Comment by Mottie** [comment]
Hi @kittensareprettyokay!

Try setting the [`output_duplicateSpans`](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_duplicatespans) option to `false`.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
