### ISSUE TITLE
tablesorter refresh search after jquery append

### ISSUE THREAD

**Issue by devin42r** [Mottie/tablesorter#1310]
I am using a function to insert a search input bar at the top of page.  How can I refresh table to have it recognize that search bar after insertion?

**Comment by Mottie** [comment]
Hi @devin42r!

Use the [`$.tablesorter.filter.bindSearch`](https://mottie.github.io/tablesorter/docs/#function-bindsearch) function to bind to your custom search input. Make sure to include a `data-column="#"` attribute for a specific column, or `data-column="all"` attribute to search the entire table.

**Comment by devin42r** [comment]
Thanks Mottie!  This works great!
