### ISSUE TITLE
resetToLoadState with pager plugin followed by column sort causes error

### ISSUE THREAD

**Issue by nessalc** [Mottie/tablesorter#1311]
There's probably a better way to do what I'm trying to do, but I discovered this apparent issue along the way. In a certain set of circumstances, the pager plugin and resetToLoadState methods don't get along:

To reproduce:
1. load page
2. trigger resetToLoadState
3. click on column heading to sort
    - Chrome gives the following: `jquery.tablesorter.pager. Uncaught TypeError: Cannot read property 'ajax' of undefined`
    - Firefox gives the following: `TypeError: p is undefined` (also pointing to jquery.tablesorter.pager.)

If, however, the pager is destroyed, then restored, the error does not occur.

I have been able to do this using developer console using Chrome 54.0.2840.71, 54.0.2840.87 and Firefox 47.0, 48.0.2, 49.0.2 on the example page [here]().

**Comment by Mottie** [comment]
Hi @nessalc!

That does sound like a problem. I'll spend more time troubleshooting this issue when I get some free time.

Have you tried the pager widget? It is essentially the same as the plugin rewritten into widget form although it should behave much better when using the `resetToLoadState` method.
