### ISSUE TITLE
Pager controls are not being applied to the Sticky header

### ISSUE THREAD

**Issue by KarlBaumann** [Mottie/tablesorter#1313]
![sticky-header](https://cloud.githubusercontent.com/assets/11026930/20069156/b7fbc380-a51b-11e6-9030-005865a8492d.gif)

**Comment by Mottie** [comment]
Hi @KarlBaumann!

Thanks for letting me know! I'll look into this once I've caught up.

**Comment by Mottie** [comment]
Ok, now that I've had a little time to look at this, I can reproduce the issue. Would you please update [this demo](https://jsfiddle.net/wty134u7/58/) to show the problem?

You don't need to add the angled header, just break the pager controls ;)

**Comment by Mottie** [comment]
@KarlBaumann Any update on this? If there is still a problem, please share a demo showing it.

**Comment by KarlBaumann** [comment]
I will create a demo myself. I don't know how to update your demo to brake the controls, since I dont know which part exactly brakes it.

**Comment by Mottie** [comment]
Well, just having the HTML and javascript would help! Are you using the pager addon or widget?

**Comment by Mottie** [comment]
Fixed in the master branch... here is a link to the demo I shared in chat for others to test

http://jsfiddle.net/ns6xhf5m/11/
