### ISSUE TITLE
Unable to add custom stuff to a print

### ISSUE THREAD

**Issue by JackCommodore** [Mottie/tablesorter#1314]
Hi! I explain you what i want to do and the problem i'm finding.
Im using table sorter with print widget. Im trying to print the table and i would like to add a header and 
/or footer with logos and other stuff. Obviously all this stuff are not present into the normal php page.

I think i have to focus into the "print_extraCSS" i have in the same php page and here is what i'm trying:
			print_extraCSS   : ".try { width:100%; height:50px; background-color:red; }",  

Then right after the `<div class="table sorter">` i put a `<div class="try">` but nothing is shown during the print.

This is the right thing to do or i'm wrong?
Thanks

**Comment by Mottie** [comment]
Hi @JackCommodore!

The print table only prints the table, but you can use the [`print_callback` option](https://mottie.github.io/tablesorter/docs/example-widget-print.html#print_callback) to include any extra HTML along with the table - [demo](https://jsfiddle.net/Mottie/bdddtbts/15/)

```js
$(function () {

    // v2.24.6, change popup print & close button text
    // See print_now description
    $.tablesorter.language.button_print = "Print";
    $.tablesorter.language.button_close = "Close";

    $(".tablesorter").tablesorter({
        theme: 'blue',
        widgets: ["zebra", "filter", "print"],
        widgetOptions: {
            print_title: '', // this option > caption > table id > "table"
            print_dataAttrib: 'data-name', // header attrib containing modified header name
            print_rows: 'f', // (a)ll, (v)isible, (f)iltered, or custom css selector
            print_columns: '', // (a)ll, (v)isible or (s)elected (columnSelector widget)
            // add any extra css definitions for the popup window here
            print_extraCSS: '.try { width:100%; height:50px; background-color:red; }',
            // add the url of your print stylesheet
            print_styleSheet: 'https://mottie.github.io/tablesorter/css/theme.blue.css',
            print_now: false, // Open the print dialog immediately if true
            // callback executed when processing completes - default setting is null
            print_callback: function (config, $table, printStyle) {
                // do something to the $table (jQuery object of table wrapped in a div)
                // or add to the printStyle string, then...
                // print the table using the following code
                var toPrint = $('.try')[0].outerHTML + $table.html();
                $.tablesorter.printTable.printOutput(config, toPrint, printStyle);
            }
        }
    });

    $('.print').click(function () {
        $('.tablesorter').trigger('printTable');
    });

});
```

**Comment by JackCommodore** [comment]
Thank you @Mottie! This worked and is definitely something i'm going to use in my project.

I also have 3 quick question about printing i'm unable to solve or find a solution. I don't know if i an post it here or if i have to open another thread.
Anyway:
1) I cannot understand why, when i try to print, the pdf or the print shows up without a table border in the right side.
2) There is a way to have, as in the normal php view, a different background for the header? Anything i try brings to a white background header.
3) The same as n.2 for the result's rows. There is a way to set up alternate colors for the even and odd rows?

Thanks!

![mottie_try](https://cloud.githubusercontent.com/assets/23474991/20358373/de170c66-ac2b-11e6-915f-7f9e15054fa4.jpg)

**Comment by Mottie** [comment]
Is the URL in the `print_styleSheet` loading properly? Or do you have the css added to the `print_extraCSS` option?

Or maybe the class names are matching? I would have to see an example of the problem to better help.

**Comment by JackCommodore** [comment]
Just to make it easier... its also happening with the jsfiddle demo you post. that should work, right?

**Comment by Mottie** [comment]
It looks like the border that is showing is actually from the `tr`. So if you include the following definition ([demo](https://jsfiddle.net/Mottie/bdddtbts/23/)):

```js
print_extraCSS: 'tr { border: 0; }'
```

**Comment by JackCommodore** [comment]
When i press print a popup is opening. I'm able to modify this popup's table style but still the print's preview and the print are with white background. Does the popup and the print take in consideration different css declaration?

**Comment by Mottie** [comment]
Oh, I understand now... in the print dialog, make sure to check the "Background graphics" option.

This is what it looks like in Chrome

![color-printing](https://cloud.githubusercontent.com/assets/136959/20385388/d56c7a1e-ac7c-11e6-90b9-81a4dea08208.gif)

**Comment by JackCommodore** [comment]
You are right!! It's the first time that something like that is happening (generally it prints everything by default)! Thanks

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
