### ISSUE TITLE
Sorting does not work with AngularJS using ng-repeat

### ISSUE THREAD

**Issue by quinn123** [Mottie/tablesorter#1315]
Hello,

I created a simple html table and populated it using Angular ng-repeat.  Sorting does not work on this table.  The HTML for the table is attached.  If I remove the ng-repeat and populate the table rows individually, the sorting works as expected.

Does tableSorter support Angular / ng-repeat?  The difference here is that each <td> has the 'ng-binding' class applied to it and the <tr> has ng-scope applied.

Is there a trick to getting this to work with AngularJS?

Thanks,
Steve

[ng-repeat.txt](https://github.com/Mottie/tablesorter/files/592924/ng-repeat.txt)

``

**Comment by Mottie** [comment]
Hi @quinn123!

I haven't used angularjs, so I might not be much help in troubleshooting the problem. Maybe the discussion in #1093 will help you? Also, try setting the `debug` option to `true` and check the console.

If it doesn't help, could you set up a demo to make it easier to see and possibly troubleshoot the problem?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
