### ISSUE TITLE
Math widget: Please clarify default recalculation behavior

### ISSUE THREAD

**Issue by Chealer** [Mottie/tablesorter#1317]
According to [the documentation of the Math widget](https://mottie.github.io/tablesorter/docs/example-widget-math.html),

> By default, recalculations are performed after:
> 
> [...]
>     After any triggered "update" which may change a cell value.

Please clarify what is meant by "triggered "update" which may change a cell value.".

**Comment by Mottie** [comment]
Hi @Chealer!

I've added an explanation to the documentation. It's still in the master branch, so the actual documentation has not yet been updated.

Anyway, a `triggered "update"` refers to the ["updateComplete" event](https://mottie.github.io/tablesorter/docs/#updatecomplete) which is fired after an "update", "updateAll", "updateCell" or "addRows" method has completed.

**Comment by Chealer** [comment]
Thank you @Mottie. While that clarifies, I still find the first sentence taken alone unclear. If I understand correctly, I would suggest:

>     After any call to a tablesorter method which may change a cell value.
>     After the updateComplete event is fired (which happens after tablesorter methods which may change cell values are called).
