### ISSUE TITLE
Math widget: please specify math_mask

### ISSUE THREAD

**Issue by Chealer** [Mottie/tablesorter#1320]
The [documentation of the Math widget](https://mottie.github.io/tablesorter/docs/example-widget-math.html) advertises the math_mask option, which allows controlling the output format.

While there are examples of accepted values, there is unfortunately no description of their effect or any actual specification.

Value "0" appears to allow formatting as simple integers (i.e. 123198.8992 shows as "123198").

**Comment by Mottie** [comment]
Hi @Chealer!

Did you expand the `math_mask` option? The description contains a lot more details on how to use the mask. It also provides a link to my [fork of the javascript-number-formatter plugin](https://github.com/Mottie/javascript-number-formatter); along with [this demo](http://mottie.github.io/javascript-number-formatter/).

Essentially the difference between using `#` and `0` is that when a value of zero is passed to the function, the `#` mask will return an empty string whereas the `0` mask will return a zero. I will add a note in the documentation.

**Comment by Chealer** [comment]
Thanks for the change @Mottie . I had expanded, but there is no formal specification of how the mask is analyzed either in the example page or in the plugin's documentation.

It took me a few minutes to understand the following:

> When there's only one symbol is supplied, system will always treat the single symbol as Decimal. For instance, $.tablesorter.formatMask( '#,###', 1234567.890) will output 1234567,890.

I recommend putting that bullet and the following bullet in the same bullet, and to substitute

> When there's only one symbol is supplied, system will always treat the single symbol as Decimal.

 with

> When the mask contains a single symbol, that symbol will be treated as the decimal mark.

"symbol" should also be replaced with a more exact description, since "#" is also a symbol.
