### ISSUE TITLE
Fallback row instead of empty table

### ISSUE THREAD

**Issue by flinhardt** [Mottie/tablesorter#1322]
Hi, is there a chance to display a row, if there are no rows to left to show? That would be nice.

**Comment by Mottie** [comment]
Hi @flinhardt!

You can use the `initialized` callback function to add a row if the table is empty ([demo](https://jsfiddle.net/bbxxomhx/219/))

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    initialized: function (table) {
    	if (table.config.totalRows === 0) {
        // "remove-me" class added to rows that need to be removed
        // when the table data needs to be reprocessed, like
        // after adding new rows
      	$(table).append('<tr class="remove-me"><td colspan="4">Nothing to see here</td></tr>');
      }
    }
  });
});
```

And here are two examples from the [main wiki page](https://github.com/Mottie/tablesorter/wiki) to show a row when applying a filter with no returned results - [with the pager](http://jsfiddle.net/Mottie/4mVfu/2377/) and [without the pager](http://jsfiddle.net/Mottie/4mVfu/5603/).

**Comment by flinhardt** [comment]
Thank you very much! Had no luck to get this thing working, yet. I'll keep trying.

**Comment by Mottie** [comment]
Did you try copying the code from the demo I shared? And are you seeing any errors in the console?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
