### ISSUE TITLE
table sorting  not working in  sticky header (clone header)

### ISSUE THREAD

**Issue by thayanithi** [Mottie/tablesorter#1323]
Sorting working fine with original header,  After sticky header created sorting not working,  But filters are working fine.
I am using table sorter version : 2.25.4 and widget-stickyHeader version : 2.27.0

![original_header](https://cloud.githubusercontent.com/assets/6103805/20562173/4fb0ca20-b1a8-11e6-9267-5f40d93d21ad.PNG)
![sticky_header](https://cloud.githubusercontent.com/assets/6103805/20562179/5190ccdc-b1a8-11e6-99b4-86fe3063748a.PNG)

**Comment by Mottie** [comment]
Hi @thayanithi!

I believe this is related to #1306 and #1313. I'll look into this issue very soon!

**Comment by Mottie** [comment]
Would you please update [this demo](https://jsfiddle.net/wty134u7/58/) to show the problem?

I added this same request in issue #1306 and #1313, so if you see a demo in either post, you probably won't need to make another demo. 

Thanks!

**Comment by Mottie** [comment]
Also, please use the most up-to-date tablesorter core and widget versions.

**Comment by Mottie** [comment]
This should be working now!
