### ISSUE TITLE
Question: Input filters 98%

### ISSUE THREAD

**Issue by fallen-rve** [Mottie/tablesorter#1324]
I am curious as to why you set the table header filters to 98%, if you have a specific reason.
https://github.com/Mottie/tablesorter/blob/0161acff0af65d351c148c4382f872d517e7248f/css/high-specificity/theme.blue.specific.css#L203
File: theme.blue.specific.css
Line: 203
```
.tablesorter-blue input.tablesorter-filter,
.tablesorter-blue select.tablesorter-filter {
	width: 98%;
        // ....
```

**Comment by Mottie** [comment]
Hi @fallen-rve!

Setting the width to 100% did not look aesthetically appealing to me. Also setting the value to 100% without setting the `box-sizing` to `border-box` would cause the input or select to be wider than the cell. When a width isn't set, there can be a lot of extra padding surrounding the input or select.

Do you have an alternate solution? I would love some feedback!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
