### ISSUE TITLE
Grouping + Filter widget with child rows documentation broken or unclear

### ISSUE THREAD

**Issue by Chealer** [Mottie/tablesorter#1325]
The documentation contains [a page about "Grouping + Filter widget with child rows"](https://mottie.github.io/tablesorter/docs/example-widget-grouping-filter-childrows.html). This page contains a demo which has no description. It is hard to understand what is supposed to be displayed, but it seems to be broken. I can see 3 grey lines for France, 5 for UK. If I click the arrow to expand the second, third and fourth UK lines, nothing appears. If I expand the first, the remaining 4 disappear, which is either broken or most confusing.

This happens in Firefox 50.

**Comment by Mottie** [comment]
Hi @Chealer!

Thanks for reporting this problem. I'll try to get to it soon... too much turkey and napping planned for today!

**Comment by Mottie** [comment]
I noticed that the bug is not present locally, so if you use the `widget-group.js` file in the master branch, it will work as expected. The fix is from PR #1301.

**Comment by Chealer** [comment]
Hi Mottie. No rush - I took a different approach to my problem - but thanks for the information.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by Chealer** [comment]
This does appear to be solved.
Thanks
