### ISSUE TITLE
IE8 still supported?

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1327]
From *README.md*:
> Cross-browser: IE 6.0+, FF 2+, Safari 2.0+, Opera 9.0+, Chrome 5.0+.

But then  e.g. the following code in `widget-uitheme.js` which I would consider a core widget breaks IE8 (and probably below):
```javascript
if (c.widgets.indexOf('filter') > -1) {
```

You would have to change it to use `$.inArray()`.

**Comment by Mottie** [comment]
Hi @Herst!

Thanks for letting me know. I'll have it fixed in a moment.
