### ISSUE TITLE
Child Rows always show for every search filter

### ISSUE THREAD

**Issue by aayush26** [Mottie/tablesorter#1328]
I have posted a detailed question at SO:
http://stackoverflow.com/questions/40794816/tablesorter-child-row-always-shows-for-every-search-filter

Please help in identifying the issue.
Thanks.

**Comment by Mottie** [comment]
Hi @aayush26!

I set up this demo, and it appears to work as expected.

If you are using a custom theme for tablesorter, please make sure that the following definition is included:

```css
.tablesorter-filter {
  display: none;
}
```

**Comment by aayush26** [comment]
Thanks a lot.
