### ISSUE TITLE
sortAppend / sortForce broken in 2.28

### ISSUE THREAD

**Issue by MVKozlov** [Mottie/tablesorter#1331]
null reference in jquery.tablesorter.js, line: 2433, column: 8
2.27.8 work ok
```
	jQuery("#testtable").tablesorter({
	    sortAppend: [[0, 's']],
	}); 
```

**Comment by Mottie** [comment]
Hi @MVKozlov!

Sorry, it looks like I forgot to update the `dist`  file... the fix is already in the master branch. I'll go ahead release a patch!
