### ISSUE TITLE
sticky header with searchfilter out of line

### ISSUE THREAD

**Issue by ingridmarleen** [Mottie/tablesorter#1333]
I have a problem with the sticky header when adding the filter. Only then, from the second cell of, the cells are moving about a px to the left.
Border collapse is on, no padding to the tables, exept from the ones on the theme. I am using blue theme with lettertype 12/12 verdana

**Comment by Mottie** [comment]
Hi @ingridmarleen!

I am not able to duplicate the issue you're having. Please modify [this demo](https://jsfiddle.net/Mottie/f36416oy/34/) to show the issue... maybe it's a css definition messing things up?

**Comment by ingridmarleen** [comment]
Hi Rob,

Thanks for the fast reply! It occurs on some tables and I could resolve it
on most because there were some padding definitions on the original tables,
but that's not the case anymore.
Are there some other css definitions that can mess it up?
The demo is working flawless

2016-12-09 18:21 GMT+01:00 Rob Garrison <notifications@github.com>:

**Comment by Mottie** [comment]
Hmm, maybe you should set the box-sizing css definitions ([ref](https://www.paulirish.com/2012/box-sizing-border-box-ftw/)), just in case:

```css
html { box-sizing: border-box; }
*, *:before, *:after { box-sizing: inherit; }
```

Most theme css files add `4px` of padding to the table cells and the sticky headers widget uses the same class names, so everything should stay lined up.

**Comment by ingridmarleen** [comment]
I'll try this one of these days, although from my memory it is already set. 
I'll let you know. 
Thanks for the support!

Greetz, Ingrid

Verstuurd vanaf mijn iPhone

**Comment by ingridmarleen** [comment]
Unfortunately, it won't work. But I think it depends on calculations and
rounding.
On differnt window sizes it works, on others it is slightly out of line.
But thanks for the support!

2016-12-09 22:33 GMT+01:00 Ingrid Marleen van den Boom <amarinde@gmail.com>:

**Comment by Mottie** [comment]
Were you ever able to duplicate the problem in the jsFiddle?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
