### ISSUE TITLE
Only sorting one direction in ie8

### ISSUE THREAD

**Issue by rnesolydev** [Mottie/tablesorter#1334]
First ... I am new to jquery and tablesorter.  

I installed the original tablesorter by Christian Bach.  It was working just fine, but I noticed that it did not work with ie8 and above and it did not work with Chrome.  So I installed your version.  It now works great for Chrome and IE9 +...  

What is happening on IE8 is that I can sort the table only in descending order.  My table has two columns, I can sort one column and then the other.  But if I try and change the sort direction, nothing happens.   If I try a few times, then I get a script error 438 "File: jquery-1.2.6.min.js, Line: 26, Column: 2102."

I saw in your documentation to use Jquery version 1.2.6 so that is what I am using.

Any ideas?

**Comment by Mottie** [comment]
Hi @rnesolydev!

First off, you do not need to support any IE version older than IE11 ([ref](https://www.microsoft.com/en-us/WindowsForBusiness/End-of-IE-support) and [ref](http://venturebeat.com/2016/01/12/microsoft-ends-support-for-ie8-ie9-ie10-and-windows-8/)).

Secondly, I would suggest using a newer version of jQuery. Even though the core and pager still support jQuery v1.2.6 (see [this demo](https://mottie.github.io/tablesorter/)), most of the available widgets do not. Look at the [widget priority table](https://mottie.github.io/tablesorter/docs/#Widget-options) for version support.

If you are still encountering problems, then please use a non-minified version of jQuery (no `.min.js`) and let me know the version & error you're seeing.

**Comment by rnesolydev** [comment]
Thank you Mottie.

I wish I did not have to support anything below ie 11.  But, by group policy in my office, everyone is forced down to ie7.    

I upgraded to jQuery to 1.4.3, and after adjusting the CSS to support the images for sort direction, it looks like everything is now working.

Thank you for your support.

**Comment by Herst** [comment]
IE7 mode inside IE8+ or really IE7 (I really hope it isn't latter because it would mean you are using Vista or XP)? I remember that there used to be problems with the the older IE rendering modes insider newer IE versions, this could be one of them

**Comment by rnesolydev** [comment]
Ya, I am not sure why they forced it all the way down to ie7.  We are currently have ie11 and are running Windows 7.   I did not know they were doing that (I am new here).  I found out when I was verifying my changes for different browsers.
