### ISSUE TITLE
Glyphicon not visible in column selector panel

### ISSUE THREAD

**Issue by ptijul** [Mottie/tablesorter#1335]
Hi, 

My employer have asked me to replace some HTML column name by their corresponding glyphicon (used everywhere in our platform and really straightforward). 
However, I see the glyphicon is not displayed. 

A demo is visible [here](https://jsfiddle.net/dntay90v/5/) (check with the first column to demonstrate the problem but in my case I'm going to about 10 columns).

**Comment by Mottie** [comment]
Hi @ptijul!

The columnSelector currently only grabs the text from the headers, then uses the template in the [`columnSelector_layout` option](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-layout). It wouldn't be difficult to grab the HTML instead, but I'm not sure if that would always be ideal.

I would have to add a new option to include HTML, or maybe only include HTML if the header is empty... I think the second approach sounds better to me.

**Comment by Mottie** [comment]
The fix is in the master branch... I'm still not sure when the next patch will be released.

**Comment by ptijul** [comment]
Hi @Mottie !

Wow thanks a lot for this very quick fix. The second option is good as the default.
If one wants to use the html even if there is text in the header text, how can we adapt the columnSelector_layout option?
Best regards

**Comment by Mottie** [comment]
Actually, I forgot about the data-attribute... you could also do this ([demo](https://jsfiddle.net/Mottie/dntay90v/6/)):

```html
<th rowspan='2' data-selector-name="<i class='glyphicon glyphicon-user test'></i>">
  <i class='glyphicon glyphicon-user'></i>
</th>
```

So, I think I'll actually revert this last update and add a callback function. This would give you much more control over the content added to the column selector popup.

```js
columnSelector_layoutCustomizer: function($cell, name, index) {
  // return the HTML for the first column only
  return index === 0 ? $cell.html() : name;
}
```

\* Note the `$cell` jQuery object would point to the div inside each header cell (class name of "tablesorter-header-inner").

**Comment by ptijul** [comment]
It's very nice with the data-attribute. I'm doing like this.
Thanks for the release, the timing fits perfectly my timing ;-)
Thank you for the 2 demos

Note : The version is still 2.28.1 instead of 2.28.2 (row 11 and 35 from tablesorter.js). I updated manually on my side but I just wanted to let you know.

**Comment by Mottie** [comment]
Thanks for letting me know about the version number.. v2.28.3 is now available.
