### ISSUE TITLE
Group widget and IE7 issue

### ISSUE THREAD

**Issue by rnesolydev** [Mottie/tablesorter#1339]
I am having a problem using the group option with IE7 (I know, I should not have to support IE7 but I do, they force IE to version 7 here where I work).

It seems to be working on IE8 and above but not below.

I am getting "Member not found" in my jquery.js file (v 1.7)  I have tried newer version up thru 1.9 all the same issue.    

I am using tablesorter version v2.28.1.

The error is occurring on the return "**return ( ret.nodeValue = value + "" );**".  See code below.  

Does anyone know a workaround for this issue?
```

// IE6/7 do not support getting/setting some attributes with get/setAttribute
if ( !getSetAttribute ) {

	fixSpecified = {
		name: true,
		id: true
	};

	// Use this for any attribute in IE6/7
	// This fixes almost every IE6/7 issue
	nodeHook = jQuery.valHooks.button = {
		get: function( elem, name ) {
			var ret;
			ret = elem.getAttributeNode( name );
			return ret && ( fixSpecified[ name ] ? ret.nodeValue !== "" : ret.specified ) ?
				ret.nodeValue :
				undefined;
		},
		set: function( elem, value, name ) {
			// Set the existing or create a new attribute node
			var ret = elem.getAttributeNode( name );
			if ( !ret ) {
				ret = document.createAttribute( name );
				elem.setAttributeNode( ret );
			}
			return ( ret.nodeValue = value + "" );
		}
	};

```
Here is my script for sorting and grouping my gridview ...

```
 <script type="text/javascript">
        $(document).ready(function () {
            $("#<% =gvDetails.ClientID %>").tablesorter({
                sortForce: [[0, 0]],
                widgets: ["group", "columns", "zebra"],
                widgetOptions: {
                group_forceColumn : [0],   
                group_enforceSort : false
                }
            });
        });
    </script>
```

**Comment by Mottie** [comment]
Hi @rnesolydev!

Well, this is actually a problem with jQuery... ([ref](https://bugs.jquery.com/ticket/12577)), but only if you run IE11 in IE7 compatibility mode. If you are truly using IE7, then this problem shouldn't show up.

The actual problem is that in IE7, aria definitions are properties. So trying to use `elem.setAttributes` to set something like "aria-sort", causes the error. To get around this, you'd have to use `elem.ariaSort` (camel-cased) to set the property. BUT, I don't know if that even provides "true" aria support to IE7.

I don't plan on dropping aria support nor do I want to modify the code to make exceptions for IE7. So I think the easiest solution would be to modify your copy of jQuery. If you look at comment 14 of that jQuety bug report I linked above, you'll see some code that does fix the problem, but I think a less invasive modification would work better:

```js
set: function( elem, value, name ) {
  // skip if trying to set aria-attributes in IE7
  if ( name.indexOf("aria-") > -1 ) { return; }
  // Set the existing or create a new attribute node
  var ret = elem.getAttributeNode( name );
  if ( !ret ) {
    ret = document.createAttribute( name );
    elem.setAttributeNode( ret );
  }
  return ( ret.nodeValue = value + "" );
}
```

**Comment by rnesolydev** [comment]
Thank you Mottie for getting back to me.  That defiantly is better.  It is now grouping in all my versions of my browsers.  

However,  I now have a new problem.  I am trying to group on just my first column.   The problem I am having is that the data in that column is a three letter code.  It can be mixed alpha and numeric.  It seems to be grouping by the first character only.

I have tried "group-word", "group-text", "group-word-999" all with the same results ...

In the example below it should be grouping by "6CU", "6CY", "BFE", "PKM", "POQ". But, its grouping by "6", "B", "P".     

Is there something I am missing to force the grouping by the full text of the column?

Here is the text from the first column ...  
```
6 (7)
6CU  
6CU  
6CU  
6CU  
6CY  
6CY  
6CY  
b (4)
BFE  
BFE  
BFE  
BFE  
p (8)
PKM  
PKM  
PKM  
PKM  
POQ  
POQ  
POQ  
POQ  
```

Just incase you need it Here is my script ...

```
      $(document).ready(function () {
          $("#<% =gvDetails.ClientID %>").tablesorter({
              sortList: [[0,0],[1,0]],
              sortForce: [[0, 0]],
              widgets: ["group", "columns", "zebra"],
              widgetOptions: {
                  group_forceColumn: [0],
                  group_enforceSort: true
              }
          });
      });
```

**Comment by Mottie** [comment]
Are you adding the "group-word" class to the column header cell ([demo](https://jsfiddle.net/Mottie/4ac5kr3o/55/))?

```html
<th class="group-word">IDs</th>
```

You can also use "group-letter-3".

If that doesn't work, then please try to reproduce the issue in the demo I shared.

**Comment by rnesolydev** [comment]
I am using the "gridview" dotnet control to build the table.    I had it on the control within the ItemTemplate.  Now that I think about it, it does make sense to put it at the header level.

Just in case if anyone else has this issue, the way I had to get the class added to the header was to do the following at the Databound event.

`       gridview.HeaderRow.Cells[0].CssClass = "group-word";`

Thank you Mottie.
