### ISSUE TITLE
When using Select2 Filter, the filter doesn't display when returning to the page 

### ISSUE THREAD

**Issue by James-Rollins** [Mottie/tablesorter#1340]
I have a tablesorter where I have several filters using select2.  Tablesorter is set up to save the filters.  When I return to the page the filter works, but doesn't display what's filtered in the select2.  

Current versions:
Select2 Version: 3.5.2
Tablesorter.combined Version: 2.27.8

v/r
James Rollins

**Comment by Mottie** [comment]
Hi @James-Rollins!

Are you using the [select2 filterFormatter](https://mottie.github.io/tablesorter/docs/example-widget-filter-formatter-select2.html)? Sadly, I haven't had a chance to work on updating the code to work with select2 v4+. The demo I linked is using v3.4.6, I haven't tested it on your v3.5.2.

Would you please [modify this demo](https://jsfiddle.net/Mottie/bbxxomhx/260/) to show me the problem.

**Comment by James-Rollins** [comment]
Rob,
Thanks for the fiddle.  I updated them demo, as you requested.  While doing so, I think I at least found the culprit.  In my demo the pipe is present in the filter.  The filter still works, but it doesn't display in the filter box.

https://jsfiddle.net/James_Rollins/bbxxomhx/269/

Thanks,
James Rollins

Begin forwarded message:

**Comment by Mottie** [comment]
Sorry for not responding earlier, but it appears that this issue has been resolved. I just tested the select2 filters and the pipe is showing. I'll go ahead and close this issue, but if you continue to have problems, please feel free to reopen this issue.
