### ISSUE TITLE
ajax call is not happeing with tablesorter pager

### ISSUE THREAD

**Issue by amitkumar1992** [Mottie/tablesorter#1341]
I am new to jquery and tablesorter. Below is the code for sorting the table with pagination using ajax call.
Despite following several other issues on this and trying out all the changes in the pager configuration, the server doesn't receive the ajax request. Please help. 
Thank you in advance.

  
[ajax.txt](https://github.com/Mottie/tablesorter/files/666051/ajax.txt)

**Comment by Mottie** [comment]
Hi @amitkumar1992!

The code you provided should work. 

Are you testing the code on a local server? The Chrome browser won't allow access to local files, but Firefox will work.

If you continue to have problems, set the [`debug` option](https://mottie.github.io/tablesorter/docs/#debug) to `true` and look in the browser console (press <kbd>F12</kbd> to open it) for more information.

**Comment by amitkumar1992** [comment]
Hi @Mottie !

First of all thanx for your reply.

I am testing the code on the local server which is Ruby TCP server.

The result is same in both firefox and chrome.

I am attaching the snapshot of the debug result on the browser along with the server code and terminal snapshot just for reference. 

The ajax request is not reflecting in the terminal.


![debug result](https://cloud.githubusercontent.com/assets/17593376/21388609/0ad70480-c7a3-11e6-9183-c9748ef19f96.png)
[server.txt](https://github.com/Mottie/tablesorter/files/666258/server.txt)
![terminal](https://cloud.githubusercontent.com/assets/17593376/21388610/0adfe9ba-c7a3-11e6-8d22-e281d078b0e9.png)

**Comment by Mottie** [comment]
Oh, you're using the original tablesorter v2.0.5, download, or link to the versions provided by this repo.

**Comment by amitkumar1992** [comment]
Thank you very much for the help. This resolved my problem.
