### ISSUE TITLE
Position: absolute on tablesorter-pager

### ISSUE THREAD

**Issue by crashtheparty** [Mottie/tablesorter#1342]
I have been trying to remove the auto-generated "position: absolute" from the pager but trying to change it via my own code has produced nothing so far and all of the fixes for this issue I have found use the older version of tablesorter and not this one. How would I fix this?

**Comment by Mottie** [comment]
Hi @crashtheparty!

It sounds like you're using the original tablesorter & pager plugin. The only way to override the inline `position:absolute` is to add an `!important` flag:

```css
.pager {
    position: static !important;
}
```

**Comment by crashtheparty** [comment]
Oh. I downloaded the old version first, then removed it and added the new version, and it was overwriting something because my computer crashed and I had to restart my local server and now it works fine. Very odd, but thanks!
