### ISSUE TITLE
Filter is not firing

### ISSUE THREAD

**Issue by rnesolydev** [Mottie/tablesorter#1345]
I have been using the table sorter and I am now trying to add the Filter option.  The filter box is coming up, but no filtering is taking place.  I am sure its just that I am missing something but I can not figure out what I forgot to add.

I am using version 2.28.3 of the tablesorter.js.

I added the widgetoptions property, the filter to the headers property,  and added filter to the widgets property.  The javascript looks like this …

 ```
$("#<% =gvContractors.ClientID %>").tablesorter({
                showProcessing: true,
                sortList: [[1, 0], [2, 0]],
                headers: { 0: { sorter: false, filter: false} },
                widgets: ["zebra", "filter"],
                widgetOptions: {
                    filter_liveSearch: true,
                    filter_columnFilters: true,
                    filter_reset: '.reset'
                }
            })
```

Here is the css that I added ...

```
/* filter row */
.tablesorter-filter-row td {
  background: #ffe7c6;
  line-height: normal;
  text-align: center; /* center the input */
  -webkit-transition: line-height 0.1s ease;
  -moz-transition: line-height 0.1s ease;
  -o-transition: line-height 0.1s ease;
  transition: line-height 0.1s ease;
}
/* optional disabled input styling */
.tablesorter-filter-row .disabled {
  opacity: 0.5;
  filter: alpha(opacity=50);
  cursor: not-allowed;
  background: #ffe7c6;
  border-style : none;
}

/* hidden filter row */
.tablesorter-filter-row.hideme td {
  /*** *********************************************** ***/
  /*** change this padding to modify the thickness     ***/
  /*** of the closed filter row (height = padding x 2) ***/
  padding: 2px;
  /*** *********************************************** ***/
  margin: 0;
  line-height: 0;
  cursor: pointer;
}
.tablesorter-filter-row.hideme .tablesorter-filter {
  height: 1px;
  min-height: 0;
  border: 0;
  padding: 0;
  margin: 0;
  /* don't use visibility: hidden because it disables tabbing */
  opacity: 0;
  filter: alpha(opacity=0);
}

/* filters */
.tablesorter-filter {
  width: 95%;
  height: inherit;
  margin: 4px;
  padding: 4px;
  background-color: #fff;
  border: 1px solid #bbb;
  color: #333;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: height 0.1s ease;
  -moz-transition: height 0.1s ease;
  -o-transition: height 0.1s ease;
  transition: height 0.1s ease;
}
```

**Comment by Mottie** [comment]
Hi @rnesolydev!

I think you're just missing this css:

```css
/* rows hidden by filtering */
.tablesorter .filtered {
	display: none;
}
```

The class name is set by the [`filter_filteredRow` option](https://mottie.github.io/tablesorter/docs/#widget-filter-filteredrow).

**Comment by rnesolydev** [comment]
Thank you!!!  That was it.  The first example I found out there did not have it in the CSS.  I see it now in other examples.

**Comment by Mottie** [comment]
You're welcome!

Was the example in the docs here? I would like to update the code.

**Comment by rnesolydev** [comment]
Mottie,
  Sorry to bother you again.  But I closed this issue to soon.  This is working for ie7 (default in my workplace).   But when I try this in Chrome or ie8 and above it does not work. Using the developer tools in IE, it looks like it is not finding the css for the filtering.  Sorting is working, but filtering is not.  

My script now looks like this ...

```
            $("#<% =gvContractors.ClientID %>").tablesorter({
                showProcessing: true,
                sortList: [[1, 0]],
                headers: { 0: { sorter: false, filter: false} },
                widgets: ["zebra", "filter"],
                widgetOptions: {
                    filter_liveSearch: true,
                    filter_columnFilters: true,
                    filter_childRows: true,
                    filter_filteredRow: "filtered"
                }
            })
```

**Comment by Mottie** [comment]
Hmm, try inspecting the rows and see if the "filtered" class is being applied.

If it is applied, then maybe there is a css definition overriding the `display:none`? Or, maybe the name is misspelled in the css? Is the css file loading?

If it isn't being applied, make sure there aren't any errors in the console. What exactly is happening? Is there no change when you enter a query in the filter? Is this when errors show up in the console?

And please clarify what you mean by "not finding the css"?

**Comment by rnesolydev** [comment]
I am using the same css for ie7 and for ie10, so I do not think I have any misspellings.  I checked again and do not see any errors.  I am using the "developer tools F12" from ie to debug this, and the developer tools for Chrome.

The main thing that is not happening is the filter is not working.  I type a string in the filter box and nothing happens.  Also,  I modified the class "tablesorter-filter-row .disabled" class to change the background color so the filter box does not show.  It picks up that background color change in ie7 but not in ie10.

Here is a screen shot of the source in IE7.   It shows that it is using the "tablesort-filter" class in my css.

![image](https://cloud.githubusercontent.com/assets/24481435/21620864/482f8c46-d1ab-11e6-892c-d72e52dbbd6b.png)

Here is a screen shot of the same source in IE10.  It shows that it did not find the "tablesort-filter" class.

![image](https://cloud.githubusercontent.com/assets/24481435/21621032/1f8a4aaa-d1ac-11e6-8db9-d5fe50c6c053.png)



Something that might add complexity to this is that I am using a dot.net gridview control to build my table.

**Comment by rnesolydev** [comment]
Update:  I just confirmed that when I type in a character in the filter box, the tablesorter.widgets.js IS getting executed.  So, I am assuming the program is running correctly, its just not getting hidden.

It looks like the class is getting updated with the filtered class but it is not filtering out.  Here is a screen shot of a row that should have been filtered.  Notice the class "odd filtered".
![image](https://cloud.githubusercontent.com/assets/24481435/21622521/bab155ae-d1b2-11e6-8091-905a7f68c344.png)

**Comment by Mottie** [comment]
How are you loading the stylesheet?

If you are using conditional comments, they are [no longer supported in IE10](https://msdn.microsoft.com/en-us/library/hh801214(v=vs.85).aspx).

**Comment by rnesolydev** [comment]
The stylesheet is loaded via our .net "Masterpage"...

`<link rel="stylesheet" href="./StyleDotNet.css" type="text/css" title="Sstyles" />`

We have no conditional comments.

If this will help.  Here is all the CSS code I added after I started to use "tablesorter".  I am using it for sorting, grouping, and filtering.  I know its a bit long, but I thought it might help.   But only sorting and filtering on this particular table.


```
/* for jquery table sorter */
table.tablesorter {
    font-family:arial;
    background-color: #ffe7c6;
    margin:10px 0pt 15px;
    font-size: 8pt;
    width: 100%;
    text-align: left;
}
table.tablesorter thead tr th, table.tablesorter tfoot tr th {
    background-color:  #DDB786;
    border: 1px solid #FFF;
    font-size: 8pt;
    padding: 4px;
}
table.tablesorter thead tr .header, .tablesorter-header {
    background-image: url(images/bg.gif);
    background-repeat: no-repeat;
    background-position: center right;
    cursor: pointer;
}
table.tablesorter tbody td {
    color: #3D3D3D;
    padding: 4px;
    background-color: #dbb27d;
    vertical-align: top;
}
table.tablesorter tbody tr.odd td {
    background-color:#ffe7c6;
}
    table.tablesorter tbody tr.even td {
    background-color:#fff;
}
table.tablesorter thead tr .headerSortUp, .tablesorter-headerAsc {
    background-image: url(images/asc.gif);
    border-bottom: #000 2px solid;
}
table.tablesorter thead tr .headerSortDown, .tablesorter-headerDesc, .tablesorter-headerSortDown {
    background-image: url('images/desc.gif');
    border-bottom: #000 2px solid;
}
table.tablesorter thead tr .headerSortDown, 
table.tablesorter thead tr .headerSortUp,
table.tablesorter thead tr .tablesorter-headerDesc,
table.tablesorter thead tr .tablesorter-headerAsc {
    background-color: #cd954c;
}
.tablesorter-default thead .sorter-false {
    background-image: none;
    cursor: default;
    padding: 4px;
}

tr.group-header td {
  background: #d29f5d;
}
.group.group-name {
  text-transform: uppercase;
  font-weight: bold;
}
.group-count {
  color: #999;
}
.group-hidden {
  display: none;
}
.group-header, .group-header tdp-header tr {
   {
  user-select: none;
  -moz-user-select: none;
}
/* collapsed arrow */
tr.group-header td i {
  display: inline-block;
  width: 0;
  height: 0;
  border-top: 4px solid transparent;
  border-bottom: 4px solid #888;
  border-right: 4px solid #888;
  border-left: 4px solid transparent;
  margin-right: 7px;
  user-select: none;
  -moz-user-select: none;
}
tr.group-header.collapsed td i {
  border-top: 5px solid transparent;
  border-bottom: 5px solid transparent;
  border-left: 5px solid #888;
  border-right: 0;
  margin-right: 10px;
}

/* rows hidden by filtering */
.tablesorter .filtered {
	display: none;
}

/* filter row */
.tablesorter-filter-row td {
  background: #ffe7c6;
  line-height: normal;
  text-align: center; /* center the input */
  -webkit-transition: line-height 0.1s ease;
  -moz-transition: line-height 0.1s ease;
  -o-transition: line-height 0.1s ease;
  transition: line-height 0.1s ease;
}

/* optional disabled input styling */
.tablesorter-filter-row .disabled  {
  opacity: 0.5;
  filter: alpha(opacity=50);
  cursor: not-allowed;
  background: #ffe7c6;
  background-color: #ffe7c6;
  border-style : none;
}

/* hidden filter row */
.tablesorter-filter-row.hideme td {
  /*** *********************************************** ***/
  /*** change this padding to modify the thickness     ***/
  /*** of the closed filter row (height = padding x 2) ***/
  padding: 2px;
  /*** *********************************************** ***/
  margin: 0;
  line-height: 0;
  cursor: pointer;
}
.tablesorter-filter-row.hideme * {
  height: 1px;
  min-height: 0;
  border: 0;
  padding: 0;
  margin: 0;
  /* don't use visibility: hidden because it disables tabbing */
  opacity: 0;
  filter: alpha(opacity=0);
}

/* filters */
.tablesorter-filter {
  width: 90%;
  height: inherit;
  margin: 4px;
  padding: 4px;
  background-color: #fff;
  border: 1px solid #bbb;
  color: #333;
  -webkit-box-sizing: border-box;
  -moz-box-sizing: border-box;
  box-sizing: border-box;
  -webkit-transition: height 0.1s ease;
  -moz-transition: height 0.1s ease;
  -o-transition: height 0.1s ease;
  transition: height 0.1s ease;
}
```

**Comment by rnesolydev** [comment]
OMG!!  I found a typo in the css.  There was an extra bracket.  

Sorry to have bothered you.

Strange that ie7 ignored the error,  but ie8 (plus)  does not ignore it.
