### ISSUE TITLE
grouping widget

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#1346]
https://mottie.github.io/tablesorter/docs/example-widget-grouping.html
* the grouping widget css here works nicely.. even with uitheme bootstrap..   that css should be a file so its easily includeable/minifed for those that want to use it :)

* the 'reset saved collapsed groups' doesnt appear to do anything

https://mottie.github.io/tablesorter/docs/example-widget-grouping-filter-childrows.html
* missing `Page Header` section

**Comment by Mottie** [comment]
Hi @thezoggy!

Thanks! I'll include a `widget.grouping.css` file in the theme folder. As for the "reset saved collapsed groups", I forgot to load `widget-storage.js` when I switched from using the `jquery.tablesorter.widgets.js` file to loading each widget separately for testing.

**Comment by thezoggy** [comment]
note that you left out one item, the page header section (which tells you what js to load) for the widget-grouping-filter-childrows page..

**Comment by Mottie** [comment]
Oh oops, I only updated the page header in the main group demo.
