### ISSUE TITLE
columns widget

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#1347]
https://mottie.github.io/tablesorter/docs/example-widget-columns.html
doesnt work with uitheme bootstrap...  looks like the themes lack the css required for this plugin..

**Comment by Mottie** [comment]
Hi @thezoggy!

Well I didn't add columns widget css to the bootstrap theme because of https://bootswatch.com/, which has many different bootstrap styles and adding a "default" theme wouldn't match on some of them.

I guess I could add the necessary definitions and developers could modify it as needed.

**Comment by Mottie** [comment]
Done!

**Comment by Mottie** [comment]
Added columns widget to all Bootstrap demos:

* https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v4.html
* https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v3.html
* https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v2.html

\* Note: renamed demo file names

**Comment by thezoggy** [comment]
seems like the 2nd column colors match the border color..  may want to tweak it slightly?

**Comment by Mottie** [comment]
I actually copied the column colors straight from the default theme...  If I remember correctly, I darkened the colors by 5% for each column from tertiary -> secondary -> primary. What changes would you suggest?

**Comment by thezoggy** [comment]
the secondary one needs to be darker or lighter.. it blends into the bootstrap table border too much and looks odd
