### ISSUE TITLE
export/copy to excel

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#1349]
noticed that on this 'grid' they have a export to excel/pdf and also a copy to excel..
http://demos.telerik.com/kendo-ui/grid/excel-export
http://demos.telerik.com/kendo-ui/grid/copy-to-excel

didnt tablesorter used to have the export feature? cant seem to find it...

**Comment by thezoggy** [comment]
looks like this was brought up under: https://github.com/Mottie/tablesorter/issues/963
wonder if we could just serve up a copy to csv since thats just serializing the data?

**Comment by Mottie** [comment]
Hi @thezoggy!

The [output widget](https://mottie.github.io/tablesorter/docs/example-widget-output.html) allows you to output csv, tsv and JSON. Excel should still properly load these files.

To copy data directly to excel would require a method to select table cells. I don't have anything like that yet.

**Comment by Mottie** [comment]
I just tested it, I saved a CSV file with a `.xls` extension and loaded it in Excel. It thought the file was corrupt, but still allowed me to load it... everything looks good.

**Comment by thezoggy** [comment]
thanks, couldnt find that one.. also btw that page looks like its missing the page header section..
https://mottie.github.io/tablesorter/docs/example-widget-output.html

**Comment by thezoggy** [comment]
on that output widget.. 
i would say offer up an option to change if it includes the header/footer in the output: no header+footer, header only, none
since normally I've never seen a footer in a csv file.. and i know the header is optional..

**Comment by Mottie** [comment]
LOL thanks... there are a lot of demos missing the page header; it's hard to be consistent ;)

As for the header & footer.. there are options:

* [`output_headerRows`](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_headerrows)
* [`output_includeFooter`](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_includefooter)

I just haven't included the options in the popup, which by the way is completely customizable.

**Comment by thezoggy** [comment]
yeah, the option is in one popup but not in the other.. no worries :)

**Comment by Mottie** [comment]
Actually, the `headerRows` option is set up to include all header rows, or just the last. I need to add a `includeHeaders` option.

**Comment by Mottie** [comment]
I discovered that if you set the [`output_separator`](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_separator) to a tab (`"\t"`), open a popup and copy the contents... you can now paste directly into Excel and the data will be added into separate cells.

**Comment by thezoggy** [comment]
nice, good to know
