### ISSUE TITLE
CSV and BOM

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#1353]
Hello,

I just have a little problem when I use output widget. I have some accents in my table (also in header rows). I try to encod the output with : 
```js
output_encoding     : 'data:text/csv;charset=utf8,%EF%BB%BF'
```
But my accents in the output are not set correctly. If I open my outputed file, save it with BOM and open it once again with Excel, it work perfectly. 

Before BOM : 
![image](https://cloud.githubusercontent.com/assets/12936546/22457166/a08049ca-e796-11e6-896c-8d8f88448c40.png)
After saving with BOM : 
![image](https://cloud.githubusercontent.com/assets/12936546/22457180/b0d8a088-e796-11e6-89d4-ab8ffd6ddaaa.png)

Any suggession ? 

By advance thanks a lot for you help

**Comment by ciadch** [comment]
Ok after some tests, it seems to work with : 
```js 
output_encoding 		: 'text/plain;charset=utf-8,',
```

**Comment by Mottie** [comment]
Hi @ciadch!

That's good to know! Thanks for bringing this issue up! I'll add a note in the docs with your findings.
