### ISSUE TITLE
Default widgetOptions are overwritten

### ISSUE THREAD

**Issue by TheMrH** [Mottie/tablesorter#1356]
When i set some defaults with 
`$.extend(true, $.tablesorter.defaults, {
			widgetOptions: {
				stickyHeaders_includeCaption: true,
				filter_columnFilters: false
			},
...
`
and I have multiple tables on a page the defaults get overwritten in jquery.tablesorter.js @ line 1932 applyWidgetOptions:
`$.extend( true, ts.defaults.widgetOptions, widget.options );`

**Comment by Mottie** [comment]
Hi @TheMrH!

I see what you're saying, but I can't duplicate the problem you're having... if I add a `widgetOptions` to the defaults, they it will be applied to all tables ([demo](http://jsfiddle.net/Mottie/856bzzeL/1106/))

```js
$.extend(true, $.tablesorter.defaults, {
  widgetOptions: {
    filter_placeholder: {
      search: 'Search...'
    }
  }
});

$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'filter'],
    widgetOptions: {
      // filter_placeholder: { search: 'x' }
    }
  });
});
```

If I comment out the `filter_placeholder` option inside the initialization code in the demo, it overrides the default setting, as it should.

Would you please modify that demo to show the issue you're describing?

**Comment by TheMrH** [comment]
Hello @Mottie ,

Thank you for the swift reply and demo code. I've added another table which shows the problem at hand: the second table does not have the defaults applied, in this case no search text in the filter fields.

**Comment by Mottie** [comment]
Please modify the demo I shared, then use the "Update" button at the top. Then please, copy the new URL and share it with me.

**Comment by TheMrH** [comment]
Oops, I didn't know the url would be updated. Here is the new url: [updated demo](http://jsfiddle.net/856bzzeL/1108/).

All I did was add a second table.

**Comment by Mottie** [comment]
Hi @TheMrH!

Sorry for the delay! I've been out of the country for the past 3 weeks. I do see the issue now and believe I have a fix. It will be available in the master branch for now. Expect a new release soon.
