### ISSUE TITLE
Events on tables with "build table widget" don't fire

### ISSUE THREAD

**Issue by bbBowser** [Mottie/tablesorter#1370]
Hello you,
maybe I am missing something, but it seems like events are not working correctly, when the data of the table comes from a json. They just don't seem to fire.

```
$('#myTable2').tablesorter({
				theme: 'blue',
				widgets: ['zebra'],
				widgetOptions: {
					build_type: 'json',
					build_source: {url: 'dashboard.php?ajax=test2', dataType: 'json'}
				}
			}).bind("sortStart",function(e, t){
					alert('aaa');

			$("#myTable8").tablesorter({
				theme: 'blue'
			}).bind("sortStart",function(e, t){
					alert('bbb');
				});
```
myTable2 does not fire any events, myTable8 does work as expected.
Am I missing something here or is this expected behaviour?

(Version 2.28.5)

thx bbBowser

**Comment by Mottie** [comment]
Hi @bbBowser!

Currently, the build widget only works when targeting non-table elements:

```html
<div id="myTable2">
  <table>...</table>
</div>
```

So to bind to events, you'll need to target the table inside the div ([demo](https://jsfiddle.net/Mottie/gzysy10p/2/)); internally, all triggered events use jQuery's [`triggerHandler`](http://api.jquery.com/triggerHandler/) function which doesn't allow for event propagation because it would be troublesome to have events like `sortStart` bubble up from a nested table.

```js
$('#table')
  .tablesorter({
    theme: 'blue',
    widgets: ['zebra'],
    data : dataObject
  })
  .find('table')
  .on('sortStart', function(){
    alert('ok');
  });
```

**Comment by Mottie** [comment]
I'll need to update the documentation... I thought I had it in there :(

**Comment by bbBowser** [comment]
Oh of course. I should have noticed.
Thank you for your quick reply. Keep up the good work :)

**Comment by Mottie** [comment]
Oh, just in case the table is very large, you might need to bind the events inside of the `initialized` callback ([demo](https://jsfiddle.net/Mottie/gzysy10p/3/))

```js
$('#table').tablesorter({
  theme: 'blue',
  widgets: ['zebra'],
  data: dataObject,
  initialized: function(table) {
    $(table).on('sortStart', function() {
      alert('ok');
    });
  }
});
```

**Comment by Mottie** [comment]
New release is available and the documentation has been updated.
