### ISSUE TITLE
cssStickyHeaders not attached to div

### ISSUE THREAD

**Issue by luchopb** [Mottie/tablesorter#1371]
Hello,

My webpage has a bootstrap navbar fixed to top, and when I use stickyheaders they are behind the navbar, I want them to be under de navbar but I can't do it.  I set the option  `      cssStickyHeaders_attachTo      : '.navbar', ` but still not working...

Someone please can explain to me how it works?

**Comment by Mottie** [comment]
Hi @luchopb!

Please modify [this demo](https://jsfiddle.net/Mottie/z8Lacguz/35/) to help me troubleshoot the problem.

**Comment by Mottie** [comment]
Oh, I think I understand... set the `cssStickyHeaders_offset` option - [demo](https://jsfiddle.net/Mottie/z8Lacguz/36/)

```js
$(function () {
	$('table').tablesorter({
		theme: 'bootstrap',
		headerTemplate: '{content}{icon}',
		widgets: ['zebra', 'cssStickyHeaders', 'uitheme'],
		widgetOptions: {
      cssStickyHeaders_offset: $('.navbar').height(),
			cssStickyHeaders_attachTo: null
		}
	}).tablesorterPager({
		container: $('.ts-pager'),
	});
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by luchopb** [comment]
Yes, thank you so much for your help. It worked!!
