### ISSUE TITLE
how selector childrow to sort?

### ISSUE THREAD

**Issue by qingshangyun** [Mottie/tablesorter#1372]
I use childrow to bind some row ,but it always use the hasChilrow to sort, i want use a childRow to sort?how to do ?thank you.
other way , how to make some row don't sort ?

**Comment by Mottie** [comment]
Hi @qingshangyun!

Please elaborate on what you want. Do you want to only sort childRows? or to sort both the hasChildrow (parent) and the childRows?

To prevent rows from sorting, you'll need to either add the rows inside of a [separate tbody](https://mottie.github.io/tablesorter/docs/example-multiple-tbodies.html), or use the [static row widget](https://mottie.github.io/tablesorter/docs/example-widget-static-row.html).

**Comment by qingshangyun** [comment]
@Mottie Firstly,thanks very much.My question is a bit complicated.I want to click a thead.th to sort by one childrow , other chidrows  and hasChildrow doesn't sort .but they can move with the childrow who is sorted. In addttion , i click other thead.th to sort by another childrow .
so, my idea is sort by some row ,and pervent other rows. i'll use separate tbody to have a try .
thank you ,thank you ...

**Comment by Mottie** [comment]
I am still not clear as to what you're asking. Would you please [modify this demo](http://jsfiddle.net/Mottie/sdsobvp9/) and explain what happens. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
