### ISSUE TITLE
Performance issues with a few hundred rows x 7 columns

### ISSUE THREAD

**Issue by zenichanin** [Mottie/tablesorter#1374]
I'm having some major performance issues with a few hundred rows and 7 columns. It basically takes like 5-10 seconds for sort to complete when you click on the table header.  

As far as what features I'm using, it would be the `cssChildRow`, `headerTemplate`, `cssIcon`, `cssIconAsc`, `cssIconDesc`, and `cssIconNone` which looks like this:

````
$('table.keywords').tablesorter({
	cssChildRow: 'expand-child',
	headerTemplate: '{content} {icon}',
	cssIcon: 'tablesorter-icon fa',
	cssIconAsc: 'fa-sort-alpha-asc',
	cssIconDesc: 'fa-sort-alpha-desc',
	cssIconNone: ''
});
````

Any tips to improve performance?  Funny thing is even when I turn on debug, it doesn't show accurate times. For example, "Applying sort" value is like 6 ms and is written to console before the sort is even completed. In fact, all of the things are written to the console before the sort is visually completed.

Would appreciate any help or suggestions to fix this issue. It works flawlessly with less than 30 or so rows. But once it get into 100-300, it's painfully slow.

**Comment by Mottie** [comment]
Hi @zenichanin!

Maybe you can set the [`delayInit` option](https://mottie.github.io/tablesorter/docs/#delayinit) to prevent the parsing of table data until a user interacts with the table, e.g. sort or filter. [This demo](https://mottie.github.io/tablesorter/docs/example-option-delay-init.html) of the `delayInit` option has a table with 20 columns and 3,150 rows. There is a slight delay when you sort, but it's nothing in the realm of 5-10 seconds... at least in the Chrome browser.

Maybe there is another script slowing things down? Or maybe you're using a different browser/OS combo? Either way, it would be better to use the pager even if all the data is contained on the current page. It speeds up rendering.

**Comment by zenichanin** [comment]
Thanks @Mottie.  I've tried `delayInit` and it doesn't seem to help at all.  The problem is not really while the table loads, it just kinda "freezes" for a couple of seconds when you click to sort it. But the debug shows it's already completed the sort, however, visually, the table doesn't sort the rows after those seconds pass by.

Would `cssChildRow` make the sort slower since it has to sort of account for every other row?  I also have the last column set as unsortable since there's buttons in that column, so I don't know if that would effect the performance. 

I might play around with it and try replicating it in JSfiddle or something so that it can be shown better.

**Comment by Mottie** [comment]
Having child rows would would likely speed up the sort since those rows aren't included while sorting - the child rows are combined with the parent row in the cache, so they are sorted and moved around as a block.

**Comment by zenichanin** [comment]
Ahh ok I found the culprit.  For some reason the [protip](https://github.com/DoclerLabs/Protip) script I'm using is making tablesorter super slow.  Once I remove it, it sorts super fast. I'll have to investigate this further with protip developer.  Thanks for your help @Mottie!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by zenichanin** [comment]
Yep issue solved.  Here's the solution in the unlikely event that someone else is experiencing it. 

https://github.com/DoclerLabs/Protip/issues/32
