### ISSUE TITLE
"not sure if this actually works in IE9 and older..." – It does not.

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1379]
Just for fun I tested my project in (a real) IE8 and things are still largerly working (concerning table sorter in some parts thanks to my browser switches, e.g. no column selector widget for IE8) the output plugin breaks stuff when using the download option (pop-up works fine):

```js
// fallback to force file download (whether supported by server).
// not sure if this actually works in IE9 and older...
window.open( wo.output_encoding + encodeURIComponent(data) + '?download', '_self');
```
I can report back that it does not work in IE8, the odd and nonsensical error message is: `The data area passed to a system call is too small.`

For me personally IE8 is not of the highest concern even if I'm targeting an audience where IE8 might be more likely than on the internet (e.g. ancient offline control PCs running XP which are just there to access the intranet and web UIs of devices), but in the future I might switch to jQuery 3 and Bootstrap 4 so IE8 has to be let go anyway at some point.

**Comment by Mottie** [comment]
Hi @Herst!

LOL, that is an odd error indeed. If I remember, I copied that part of the code from an older version of [FileSaver.js](https://github.com/eligrey/FileSaver.js). I haven't looked into updating it in a while, but I haven't heard any complaints (I'm not counting this report 😉).

Oh, but I did hear that FileSaver.js is now working on Safari browsers... if the output widget isn't working for you, load in FileSaver.js and set the [`output_savePlugin` option](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_saveplugin) to see if that changes anything.

**Comment by fjmartinez** [comment]
Hi @Mottie ,
I have the same issue than @Herst , and I try the solution using [FileSaver.js](https://github.com/eligrey/FileSaver.js), but FilerSaver doesn't support IE9 and older... So maybe I need look for other solution, do you know other implementations?

**Comment by Mottie** [comment]
Hi @fjmartinez!

Do you need to support IE9 and older? [Microsoft doesn't support those versions any more](https://blogs.msdn.microsoft.com/ie/2014/08/07/stay-up-to-date-with-internet-explorer/)...

> After January 12, 2016, only the most recent version of Internet Explorer available for a supported operating system will receive technical support and security updates. For example, customers using Internet Explorer 8, Internet Explorer 9, or Internet Explorer 10 on Windows 7 SP1 should migrate to Internet Explorer 11 to continue receiving security updates and technical support.

**Comment by Herst** [comment]
Until yesterday you could've argued that IE9 support would still make sense, being a browser supported by Microsoft since it's the latest available IE version for Microsoft Vista, but since today the support for that OS version ended altogether (hooray)… 

BTW, speaking of IE9 I just noticed that it does not work in IE9 either (or at least IE10 in IE9 mode), same strange error message.

**Comment by Mottie** [comment]
I have no idea what to do about that...

**Comment by Herst** [comment]
I don't think there is anything you can do and I also don't expect you to for the reason mentioned before (not a problem of any supported Desktop/Server/Mobile browser), so I'm going to close this, just thought I let you know.
