### ISSUE TITLE
Sorting column  in JQuery Modal Dialog using image alternate text

### ISSUE THREAD

**Issue by ronibduk** [Mottie/tablesorter#1380]
Hi

I am using tablesorter.js v2.28.6, tablesorter.widgets.js v2.28.6, jquery-3.1.1, jquery-ui 1.12.1 for sorting data. It is working fine with the text column. But my first column is little bit different. Please see below -

```
<table class='tablesorter'>
	<thead>
		<tr>
			<th>happy II sad </th>
			<th>Col 1</th>
			<th>Col 2</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td>
				<img src="happy.png" alt="happy">
				<span>1</span>
				<p>12:02 am</p>
			</td>
				this is col1
			<td>
			</td>
			<td>
				this is col2
			</td>
		</tr>
		<tr>
			<td>
				<img src="sad.png" alt="sad">
				<span>2</span>
				<p>11:02 am</p>
			</td>
				this is col1-1
			<td>
			</td>
			<td>
				this is col2-2
			</td>
		</tr>
	<tbody>
</table>
```

I like to sort the table when any 1 text is clicked (either happy or sad). When I click on happy, it will sort the table with happy. If it is not possible, then currently I am using filtering as well. So, in filter text box, I can type the 'happy' text and it will sort. Could you please let me know is this possible or not. If possible, please give me an example.

Thanks

**Comment by Mottie** [comment]
Hi @ronibduk!

Yes, it is possible! 😸

First off, the HTML isn't rendering correctly. "Col 1" has text in-between the table cells. This text ends up getting rendered outside of the table, at least in Chrome. Also, the `<tbody>` at the end of the table should be a closing `</tbody>` or the table gets an extra empty tbody added.

As a quick aside, in this fork of tablesorter, the `ipAddress` parser was moved into the separate `parser-network.js` file to make way for the now built-in image parser. 

The built-in image parser looks in the attribute set by the [`imgAttr` option](https://mottie.github.io/tablesorter/docs/#imgattr). If not set, it falls back to `"alt"`. If the image doesn't have anything set in the attribute, the parser uses the table cell text instead. In [this demo](https://jsfiddle.net/bbxxomhx/383/), the alt text is added, but the number and time in the image column are completely ignored.

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    imgAttr: 'alt', // default setting
    widgets: ['filter', 'zebra']
  });
});
```

To include the text from the image cell, you'll need to write a custom parser - [demo](https://jsfiddle.net/bbxxomhx/385/):

HTML (this sets the custom parser)

```html
<th class="sorter-image-and-text">happy II sad</th>
```

JS

```js
$(function() {

  $.tablesorter.addParser({
    id: 'image-and-text',
    is: function() {
      return false;
    },
    format: function(str, table, cell) {
      return ($(cell).find('img').attr(table.config.imgAttr || 'alt') || '') + str;
    },
    // filter widget flag; true = always use parsed data
    parsed: true,
    type: 'text'
  });

  $('table').tablesorter({
    theme: 'blue',
    imgAttr: 'alt', // default setting
    widgets: ['filter', 'zebra']
  });

});
```

**Comment by ronibduk** [comment]
Hi Mottie

This is great, sorry for my html typing. This is what I am exactly looking for. Many thanks for your help.

Thanks

**Comment by Mottie** [comment]
Hehe no need to apologize, I'm trying to help! 🍬

**Comment by ronibduk** [comment]
Thanks
