### ISSUE TITLE
Scroller widget doesn't scroll on Safari (Mac and iPhone)

### ISSUE THREAD

**Issue by davidjkrause** [Mottie/tablesorter#1382]
Put together a JSFiddle for a different issue #1376 but I've found that the same example also doesn't scroll horizontally on Safari.  It works fine on Chrome on Mac, Linux, and Android devices, and it also scrolls on Firefox.

Example here: https://jsfiddle.net/e1waajt1/1/

Is there something I'm missing that would cause this to not scroll horizontally on Safari?

**Comment by TheSin-** [comment]
Thanks for reporting this, I'm the resident Safari "debugger" and sadly I don't use scroller at all so I didn't catch this.

Either way I've made a fix here https://jsfiddle.net/e1waajt1/3/ you can see it's just a one line to css and it's to counter bootstrap.css which is messing with max-width on anything with the class of table.

@Mottie has been made aware of it and will likely commit a fix or at least log this as something required for anyone using bootstrap.css

Either way if you add that to your code it should work till we get a perm solution here.

**Comment by davidjkrause** [comment]
Adding that CSS fixed it, thanks so much for the quick suggestion.

**Comment by Mottie** [comment]
Thanks @TheSin-!

I wonder if that fix also needs to be included for Bootstrap v4?

I think the easiest solution would be to add that css definition to the scroller widget. I tested the demo in the other up-to-date browsers and it works fine.
