### ISSUE TITLE
Filter leaving the totals row (static)

### ISSUE THREAD

**Issue by darindaniel** [Mottie/tablesorter#1383]

**Comment by Mottie** [comment]
<img title=":_badger:" src="https://cloud.githubusercontent.com/assets/136959/13512240/15d31412-e15f-11e5-8577-06cff0976977.gif">

**Comment by darindaniel** [comment]
How does one use the filter widget while keeping a calculated row and the bottom un filtered.

**Comment by Mottie** [comment]
Add a `<tfoot>`.

**Comment by darindaniel** [comment]
hahaha ty....
