### ISSUE TITLE
Ajax request firing multiple times on page load

### ISSUE THREAD

**Issue by KaiserWolfTaco** [Mottie/tablesorter#1384]
Hi,
  First off, thanks for maintaining this repo.  Tablesorter fits pretty much all my needs and is by far the most robust table I've used. Anyways, this seems to occur in versions v2.28.6 and up.  I have a table that uses ajax to get its rows.  When the page loads, the table fires off a random number of GET requests to my backend server. Sometimes its 5, other times its 20.  I have no retry logic in my code and when i downgrade tablesorter to version 2.28.5, this behavior stops. Any ideas?
Thanks

**Comment by Mottie** [comment]
Hi @KaiserWolfTaco!

Mmm tacos... now I'm hungry. Errr, I think this might be the same issue as reported by @alexweissman in IRC.

I think I've isolated the problem, but try setting the [`pageReset` option](https://mottie.github.io/tablesorter/docs/#pager-page-reset) to `false` first to see if that prevents the issue you're seeing from occurring. If that does fix it, then I'll release a new patch.

**Comment by KaiserWolfTaco** [comment]
Thanks for the prompt reply. Tacos are awesome. Sorry, but that didn't fix the problem.  I tried with 2.28.7 and I should note I'm using "pager_pagerReset" with widgetOptions.  Here are some of my settings:

> pager_output: "{startRow} - {endRow} / {filteredRows} ({totalRows})",
> pager_removeRows: true,
> pager_css: {
> container: "tablesorter-pager",
> errorRow: "tablesorter-errorRow",
> disabled: "disabled"
> },
> pager_ajaxUrl: "admin/users_rows/page/{page}/size/{size}/sort/{sortList:column}/filter/{filterList:filter}",
> pager_pageReset: false,
> pager_startPage: 0,
> pager_size: size,
> pager_savePages: false,
> pager_processAjaxOnInit: true,

**Comment by Mottie** [comment]
Oh... well I have updated the filter and pager widget/addon in the master branch. Please try the update and see if *that* fixes the problem. If not, I'll need to investigate further.

**Comment by KaiserWolfTaco** [comment]
Sorry, that didn't work either. Jquery is at #3.2.1

**Comment by Mottie** [comment]
Is there any way you could modify the demo I shared to reproduce the problem?

@alexweissman did this last update fix the problem you were having?

**Comment by KaiserWolfTaco** [comment]
Which demo?

**Comment by Mottie** [comment]
<img title=":_ derp :" src="https://cloud.githubusercontent.com/assets/136959/13559387/49e2ecce-e3d9-11e5-8a16-73cbfdb7230e.gif"> sorry... [this demo](http://jsfiddle.net/Mottie/ns6xhf5m/).

**Comment by fernandog** [comment]
@Mottie i learned that sometimes you need to do this: @KaiserWolfTaco otherwise user don't get a notification in email. just the bell in github page

**Comment by Mottie** [comment]
Another pager widget update is available in v2.28.11, please let me know if this problem still occurs.

**Comment by KaiserWolfTaco** [comment]
That fixed it! Thanks Mottie
