### ISSUE TITLE
Custom filter widget with a button

### ISSUE THREAD

**Issue by omriran** [Mottie/tablesorter#1385]
Hi there,

Is there any way to get the custom filter widget (matching all columns) working on a button click? I do have a large table and the dynamic filtering is slow and sometimes get 'stuck'.

Thanks
Omri

**Comment by Mottie** [comment]
Hi @omriran!

Check out the [`filter_liveSearch` option](https://mottie.github.io/tablesorter/docs/#widget-filter-livesearch). It can be set to `false` or a specific number of characters needed before it activates.

Alternatively, you can [trigger a "search"](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#methods) on the table or use [`$.tablesorter.setFilters`](https://mottie.github.io/tablesorter/docs/#function-setfilters) with the chosen filters - [demo](http://jsfiddle.net/Mottie/abkNM/9244/)

```js
$(function() {
  var $table = $('table');
  $table.tablesorter({
    theme: 'blue',
    widthFixed: true,
    widgets: ['zebra', 'filter'],
    widgetOptions: {
      filter_columnFilters: false
    }
  });
  $('#start-search').click(function() {
    var c = $table[0].config,
    	filters = [];
    // set "any" search in last column + 1
    filters[c.columns] = $('#search').val();
    // $.tablesorter.setFilters($table, filters); <- same as triggering a search
    $table.trigger('search', [filters]);
  });
});
```

**Comment by omriran** [comment]
Thanks @Mottie !!! This is exactly what I was looking for

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
