### ISSUE TITLE
Make resizable-handle computed height exclude tfoot?

### ISSUE THREAD

**Issue by no3rdw** [Mottie/tablesorter#1386]
When using the resizable widget, the handles extend over the table's footer which often contains paging controls.  If the handle overlaps the paging controls, the paging controls do not function when clicked.  

When searching for this issue I found a jsfiddle posted by Mottie when  which highlights it perfectly:
https://jsfiddle.net/Mottie/Lq0re9s3/1/

In that example, the column headers are displayed in the tfoot as well, and I see how having the handle extend over them would be helpful.  Maybe use an optional class on the row within the tfoot to decide whether to include the row's height in the resizable-handle height?

**Comment by Mottie** [comment]
Hi @no3rdw!

Good point! I'll add a new `resizable_includeFooter` option in the next update.

**Comment by Mottie** [comment]
This new option is available in the master branch. Once issue #1384 has been resolved, I'll release the next patch.

**Comment by no3rdw** [comment]
Wow, now that's good service! ;)  Thanks so much for the super-fast response, Mottie!
