### ISSUE TITLE
Table not updating after changing a value in table

### ISSUE THREAD

**Issue by tarifrudrapur** [Mottie/tablesorter#1388]
I am using tablesorter and when we change a value inside a table row using a modal.
DOM successfully changed after a callback.
I am calling this function after callback

here is some code example 
```

var resort = $( '.tableInvestors:last' )[ 0 ].config.sortList,
       callback = function( table ){
            $( '.tableInvestors:last' ).trigger( 'updateAll' );
        };
$( '.tableInvestors:last' ).trigger( 'update', [ resort, callback ] );
```

Default sort is [[ 6, 0 ]]
A updated value display in the bottom.
It should be display according to its custom parser.

**Comment by Mottie** [comment]
HI @tarifrudrapur!

I would suggest using the [`updateCell` method](https://mottie.github.io/tablesorter/docs/#updatecell) to update a single table cell... I would not recommend using "updateAll" unless you are changing the contents of the `<thead>`.

```js
var $cell = $('#myTarget');
$cell.html('some new data');
$('.tableInvestors:last').trigger('updateCell', [ this, resort, callback ]
```

Also, from the looks of the code shared above, an updateAll is triggered immediately after an update... this would update the table twice. And if you want to resort on the same table values, then you would only need to pass a [`true` boolean value](https://mottie.github.io/tablesorter/docs/#update), or set the global [`resort` option](https://mottie.github.io/tablesorter/docs/#resort).

**Comment by tarifrudrapur** [comment]
Hey @Mottie Thanks for reply

I apply above example but still no luck.
I tried using hard code value to see the result.
And DOM data i already modified before apply this script
so there is no use of 
`$cell.html('some new data');`
here is some code example.
```
        var $cell =  $('div#a07W0000002QEhEIAW.slds-truncate.status-dropdown-btn'),
            resort = true,
            callback = function( table ) {
                
            };
        $('.tableInvestors:last').trigger('updateCell', [ this, resort, callback ]);
```

What should i do in order to work it.
At least it work when we click on header to sort.

**Comment by Mottie** [comment]
It sounds like the `this` in the `trigger('updateCell', [ this, ...])` is *not* pointing to the table cell that was modified. Replace the `this` with `$cell` and check that it works.

**Comment by tarifrudrapur** [comment]
@Mottie 

Still getting the same error.
Info: I am using salesforce lightning framework. I don't think that happen because of that as sorting and custom parser work well.

**Comment by Mottie** [comment]
Oops, I see that the updateCell code I shared had the `this` in it... sorry.

Are you sure the `$cell` variable is targeting the correct table cell?

**Comment by tarifrudrapur** [comment]
@Mottie 
The above error gone now.

Let me share some code 

```
$.tablesorter.addParser({ 
                    // set a unique id 
                    id: 'status',
                    is: function(s) {
                        // return true so this parser is auto detected 
                        return false; 
                    },  
                    format: function(s) { 
                        // format your data for normalization 
                        for(var i=0; i<getTypeList.length;i++){
                            s = s.replace(getTypeList[i],i);
                        }
                        return s;
                    }, 
                    // set type, either numeric or text 
                    type: 'numeric' 
                });
                
                $('.tableInvestors:last').tablesorter({
                    widthFixed: true,
                    debug: true,
                    //widgets: ['stickyHeaders'],
                    delayInit: true,
                    initialized : function(table){
                        // var topH = $('#oneHeader').height() + $('.slds-page-header__detail-row').height() + 15;
                        var $table = $('.tableInvestors:last');
                        $table.floatThead({
                            top: 148 + 43,
                            zIndex: 1
                        });
                    },
                    showProcessing: true,
                    cssAsc: 'slds-is-sorted slds-is-sorted--asc',
                    cssDesc: 'slds-is-sorted slds-is-sorted--desc',
                    sortList: [[5,0]],
                    headers: {
                        0: { sorter: false },
                        1: { sorter: false },
                        5: { sorter: 'status' }
                    }
                });
```


After value chnage in DOM i am calling following fuction

```
 var $cell =  $('article > div.slds-card__body > div > table > tbody > tr.slds-hint-parent.allselectbuttonsvg > td:nth-child(6)'),
            resort = true, // or [ [0,0], [1,0] ] etc
            callback = function( table ) {
                
            };
        $('.tableInvestors:last').trigger('updateCell', [ $cell, resort, callback ]);
```


Now a row is freeze at the top and also column 5 is not working. All other column sorting working

**Comment by Mottie** [comment]
Hmm, ok try using just update instead:

```js
$('.tableInvestors:last').trigger('update');
```

**Comment by tarifrudrapur** [comment]
@Mottie 

Initially it goes down when we update a field.
and when we sort using header it goes top and down. Not work according to custom parser.

**Comment by Mottie** [comment]
I can't tell what the custom parser is doing because `getTypeList` values weren't shared. Does the column sort properly before updating the cell?

**Comment by tarifrudrapur** [comment]
@Mottie 

Yes custom parser and all sorting work well before updating a value.

and `getTypeList` is my custom array string for custom sorting.

I think that issue must be of custom parser. What should i do now? It's headache for me. :(

**Comment by Mottie** [comment]
Open the console (press <kbd>F12</kbd> in your browser and click on the console tab), then copy and paste the following code into the window:

```js
var column = 5;
console.log($.map($('table')[0].config.cache[0].normalized, function(item) {
	return item[column];
}));
```

This will display the parsed column data... make sure it looks correct.

**Comment by tarifrudrapur** [comment]
**This is parser debug result at the starting**

![tablesorter1](https://cloud.githubusercontent.com/assets/15000719/25379205/e5b32b28-29c9-11e7-98a8-4f45e479a5f8.png)

![tablesorter2](https://cloud.githubusercontent.com/assets/15000719/25379253/0dda56e4-29ca-11e7-935a-25a57475e1d4.png)


**After a value update log**
![table3](https://cloud.githubusercontent.com/assets/15000719/25379278/23ffeaba-29ca-11e7-8fe7-b53455eedcc0.png)

![table4](https://cloud.githubusercontent.com/assets/15000719/25379284/289acc3e-29ca-11e7-9328-73b798b8ba87.png)


> I think sorting not work according to parser after a value. And if we remove the custom parser from the tablesorter then it's working and updating sort properly.

**Comment by Mottie** [comment]
> When we update a value it goes up or down according to sort order and when we update a new cell value then the older one goes a right row means older one is updating correctly but the new value still present either in top or bottom

Sorry for not replying earlier. Is this still a problem? It sounds like maybe an incorrect `$cell` pointer is being passed to the `"updateCell"` method. It might be easier to switch to using `"update"` if more than one cell is being changed.

**Comment by tarifrudrapur** [comment]
@Mottie 
It's not working either with **updateCell** or ****
update method.

The updated item goes up or down according to sort direction. It should be at a proper position according to custom parser.

**Comment by Mottie** [comment]
Hmm, so the "status" column is the one of interest correct?

Maybe the parser needs to be set as "text" instead of "numeric" because the values are strings and aren't parsed.

```js
$.tablesorter.addParser({ 
    // set a unique id 
    id: 'status',
    is: function(s) {
        // return true so this parser is auto detected 
        return false; 
    },  
    format: function(s) { 
        // format your data for normalization 
        for(var i=0; i<getTypeList.length;i++){
            s = s.replace(getTypeList[i],i);
        }
        return s;
    }, 
    // set type, either numeric or text 
    type: 'text' 
});
```

If it still doesn't work as expected, look closely at the parsed column values by using the console code which I described how to use above:

```js
var column = 5;
console.log($.map($('table')[0].config.cache[0].normalized, function(item) {
	return item[column];
}));
```

**Comment by tarifrudrapur** [comment]
@Mottie 
It's working perfect now. when i change it's value *numeric* to 'text'.

Thank You very much..

**Comment by tarifrudrapur** [comment]
@Mottie 
Sorry i am opening this issue again as i still facing same issue.

I tried to test it with without parser and still not sorting according to string after a value update.
here is some logs ..

> This screenshot taken before updating a value in row

![11](https://cloud.githubusercontent.com/assets/15000719/25850158/d0c13d52-34de-11e7-8a68-63eab0355a03.png)
![2222](https://cloud.githubusercontent.com/assets/15000719/25850160/d0c74b66-34de-11e7-95f5-7e4937c00fb9.png)

> This screenshot taken after i update **3rd row status value to _Init_**

![333](https://cloud.githubusercontent.com/assets/15000719/25850159/d0c51d78-34de-11e7-8405-0f61bdfcebaf.png)
![444](https://cloud.githubusercontent.com/assets/15000719/25850161/d0c81000-34de-11e7-95a8-2022b7a256cb.png)




> **The target sorting column is `Status`  and in the screenshot the last one Log is display by your above code**
`var column = 5;
console.log($.map($('table')[0].config.cache[0].normalized, function(item) {
	return item[column];
}));`


**Table is not even updating without any custom parser. Please help me out on this issue**

**Comment by Mottie** [comment]
Is this code still being used?

```js
var $cell =  $('article > div.slds-card__body > div > table > tbody > tr.slds-hint-parent.allselectbuttonsvg > td:nth-child(6)'),
  resort = true, // or [ [0,0], [1,0] ] etc
  callback = function( table ) {};
$('.tableInvestors:last').trigger('updateCell', [ $cell, resort, callback ]);
```

Are we sure the `$cell` is pointing to the correct cell? Did you try changing the trigger to "update"?

**Comment by tarifrudrapur** [comment]
@Mottie 
No i am using `$('.tableInvestors:last').trigger('update'); ` only

**Comment by Mottie** [comment]
I could better help isolate the problem if you would please [modify this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to show the issue. Please make sure to remove any sensitive data from the table.

**Comment by tarifrudrapur** [comment]
@Mottie 
Sorry for they delay in reply.
I found the solution for that.
The issue was in the custom parser


Here is the code

```
        $.tablesorter.addParser({ 
                    // set a unique id 
                    id: 'status',
                    is: function(s) {
                        // return true so this parser is auto detected 
                        return false; 
                    },  
                    format: function(s) { 
                        // format your data for normalization 
                        for(var i=0; i<getTypeList.length;i++){
                            if(s == getTypeList[i])
                                return i;
                        }
                        return -1;
                    }, 
                    // set type, either numeric or text 
                    type: 'numeric' 
                });
```

**Comment by tarifrudrapur** [comment]
@Mottie 
Thanks for your valuable reply.
