### ISSUE TITLE
OnSort type function

### ISSUE THREAD

**Issue by ceb21** [Mottie/tablesorter#1390]
Can you add a onsort function, or is there one like this available where I can run the example code below:

			$(document).ready(function() { 
				$("#myTable").tablesorter({
					sortList: [[0,1],[2, 1]],
					sortMultiSortKey: "ctrlKey",
					onSort: function(column, order){
						var sortList = [];
						if(column == 0){		// set sorting based on group column
							sortList = [2,order];
						}else{					// set group column sort with all columns
							sortList = [0,order];
						}
						return sortList;
					}
				}); 
			});

**Comment by Mottie** [comment]
Hi @ceb21!

I'm not quite sure what you're trying to do, but you can bind to the [`sortBegin` event](https://mottie.github.io/tablesorter/docs/#sortbegin) and modify the [`sortList`](https://mottie.github.io/tablesorter/docs/#sortlist). It doesn't include any parameters like your `onSort` example, but you can access the processed `sortList` before modifying it - [demo](https://jsfiddle.net/Mottie/bbxxomhx/402/):

```js
$(function() {
  $('table')
  .on('sortBegin', function(event, table) {
    // use this or table
  	this.config.sortList = [[0,0]];
  })
  .tablesorter({
    theme: 'blue',
    sortList: [[0, 1], [2, 1]],
    sortMultiSortKey: "ctrlKey"
  });
});
```

I'm not sure what kind of grouping you have set up, but have you checked out the [group widget](https://mottie.github.io/tablesorter/docs/example-widget-grouping.html)? Also, you might find the [`sortAppend` option](https://mottie.github.io/tablesorter/docs/#sortappend) useful, or even interesting.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by ceb21** [comment]
Yes got it working
