### ISSUE TITLE
Regression between 2.28.3 and 2.28.8

### ISSUE THREAD

**Issue by ptijul** [Mottie/tablesorter#1391]
Hi @Mottie,

I found a regression on my side after migrating from 2.28.3 to 2.28.8 (to test my issues posted this morning on stackoverflow that you've kindly answered).

The problem occurs only for tables loaded dynamically with AJAX. As I can't deliver a jsFiddle, see [the image here](https://ibb.co/eJoxVk) to see the result. The body columns are not aligned to their header columns.

Before that, I just needed to initialize the tablesorter plugin.
Hopefully I found a workaround : 
`$('.tablesorter-scroll').trigger('sorton', [ [[0,0]] ]);
This refresh the table sorter and the table is properly designed...however a unnecessary sort is done.

I'm fine with that, just wanted to let you know. 

Best regards

P.S: If you want I can download all realeses between and test to identify which version has produced that.

**Comment by Mottie** [comment]
Hi @ptijul!

I can't tell if this is an actual bug or not... How are you using ajax to update the table? Are you calling the "update" method after the html has updated? If it does turn out to be a bug, I'll let you know if you could help by looking at a specific version where the problem started - thanks!

To prevent column resizing, you could set the [`widthFixed` option](https://mottie.github.io/tablesorter/docs/#widthfixed) to `true`.

**Comment by ptijul** [comment]
Hi @Mottie,

Here is my code when clicking on a point of a highchart graphic (in the _select_ function).
Basically, I'm just removing the hidden class and add the HTML code in container. The HTML is returned by '_myBlock.php_' :

`$('#sectorContainer').highcharts({
        data: {
            table: 'tableSector',
            endColumn : 2
        },
        chart: {
            type: 'column'
        },
        plotOptions: {
            column: {
                cursor: 'pointer'
            },
            series : {
                allowPointSelect : true,
                point : {
                    events: {
                        select: function(e) {
                            var clickedItemIndex = arguments[0].target.series._i + 1; // + 1 because index0 in graphic corresponds to index1 in HTML table (first column is the sectorType)
                            var clickedCategoryIndex = this.category;
                            $tdInfoValues = $('#tableSector tbody tr:eq(' + clickedCategoryIndex + ') td:eq(' + clickedItemIndex + ')');
                            var selectedBusinessId = $tdInfoValues[0].getAttribute('data-sector-id');
                            var selectedLevel = $tdInfoValues[0].getAttribute('data-level');

                            $.ajax(
                                {
                                    url: 'myBlock.php',
                                    type: 'get',
                                    contentType: 'application/x-www-form-urlencoded; charset=ISO-8859-1',
                                    beforeSend: function (jqXHR) {
                                        jqXHR.overrideMimeType('application/x-www-form-urlencoded; charset=ISO-8859-1');
                                    },
                                    data: {
                                        selectedBusinessId: selectedBusinessId,
                                        selectedLevel: selectedLevel,
                                        serieName: this.series.name,
                                        categoryName: this.name,
                                        lang: phpLanguage
                                    },
                                    success: function (data, status) {
                                        $ajaxContainer = $('#ajaxContainer-sector'); // it's an empty span
                                        $ajaxContainer.removeClass('hidden');
                                        $ajaxContainer.html(data);
                                    },
                                    error: function (xhr, desc, error) {
                                        console.log(xhr);
                                        console.log('Details' + desc + ' \\nError' + error);
                                    }
                            })
                        }
                    }
                }
            }
        }
    });`

Thanks for the hint regarding 'widthFixed option'. I tried with the option to true (see [here](https://ibb.co/h78LY5)) it's better but still not acceptable. 

I'm not calling any update method. It wasn't necessary with version 2.28.3 but it seems now it is. So I replace my sorton trigger by triggering the update method and is great. I keep like this. Thanks ! I prefer that solution.

Sure no problem, I'm pleased to help If I can. Just tell me if you need it depending on my reply above and I'll go through all the versions and test.

**Comment by Mottie** [comment]
Oh, I'm glad that fixed the problem! Tablesorter has always been set up to require that the cache be updated after any changes are made to the table. I'm not sure why it was working for you before.

**Comment by ptijul** [comment]
Thanks ;-). Yes I guess so. In fact before calling the AJAX my table doesn't exist, I'm creating it so the update might not be necessary. If I click a second time, I'm replacing the HTML inside my span.  I don't know neither. Nevermind, it works and I'm following your recommendation.

P.S: I've just tested, the regression on my side was caused by the _tablesorter.widget_ file. But too many changes to go one after one. I keep like this, you can close the issue,it's up to you. Thanks again !

**Comment by Mottie** [comment]
Optimally, if the table headers don't change, then the ajax can replace the content in the `<tbody>`. If that is the case, then triggering an "update" would work best. If the table is completely replaced, then you would need to reinitialize tablesorter on the new table.

**Comment by ptijul** [comment]
Thanks you're right. Anyway it's not the case for always. The table is not loaded by default. Let's imagine this exemple : the graphic shows the list of browsers with their usages. Then the first time the detail table doesn't exist.  So by clicking on the "Internet Explorer" items, this loads a table via AJAX to list all the region using IE. Then he can click on "Firefox" or "Chrome" and then the table will list data concerning "Firefox" or "Chrome". In that second case, I might update only the `<tbody>` you're right ;-). Thanks for your time !

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
