### ISSUE TITLE
Math widget does not seem to load.

### ISSUE THREAD

**Issue by devnuhl** [Mottie/tablesorter#1392]
```
jQuery('.tablesorter')
                          .tablesorter({
                              widgets: ['zebra', 'filter', 'stickyHeaders', 'math'],
                              theme: 'metro-dark',
                              debug: true,
                              widgetOptions: { ... }
});
```
Widget file for math (v2.28.0) exists on site, but config options for math widget claimed to be unrecognized, '"math" widget code does not exist!', and math widget related functionality appears to be nonfunctioning. Tablesorter is `version : '2.28.5'`

**Comment by Mottie** [comment]
Hi @devnuhl!

You'll need to load the math widget using a script tag:

```html
<script src="../js/widgets/widget-math.js"></script>
```

I'll update the documentation to make that more clear.

**Comment by devnuhl** [comment]
I thought I might need to do that, but when I rechecked the script tags I was using to get the other widgets I was loading, I thought including the widgets.js might have been doing it dynamically. Thanks.

**Comment by Mottie** [comment]
the `tablesorter.widgets.js` file includes a few of the more commonly used widgets... you can see which ones by looking for the red &dagger; under [Plugins/Widgets in the examples](https://mottie.github.io/tablesorter/docs/#Examples) section of the documentation.

**Comment by devnuhl** [comment]
Looking through the code issuing output to the console with math_debug, I'm not seeing any events being triggered that I can use. Is it correct that the math widget issues no triggers/events?

**Comment by Mottie** [comment]
You are correct, there are no triggers/events after the math widget completes calculation, but there are two callback functions:

* [`math_complete`](https://mottie.github.io/tablesorter/docs/example-widget-math.html#math_complete) is executed after each calculation.
* [`math_completed`](https://mottie.github.io/tablesorter/docs/example-widget-math.html#math_completed) is executed after *all* calculations are done.

**Comment by devnuhl** [comment]
I was trying to figure out if I need to modify one of those, and it seems like I might for now (as a stopgap) until I find a better solution. Thanks again.

**Comment by Mottie** [comment]
Sorry, what issue are you encountering? You could trigger an event from inside the `completed` callback, or if you need I don't have any problems with adding internal triggers or other enhancements.

**Comment by devnuhl** [comment]
it was not related to TS specifically. but I was tracking the cache at a page level, and checking it against current filters, and if they didn't match, i would update the filters using the math results. somehow, even when it should not have been updating the filters (and debug output showed it wasn't), it was triggering an update to the table. visually nothing was happening, but debug output showed a lot was happening. It's resolved now. 

At this point, I'm just trying to write a new equation for combining the filter with math, so I can do a col-minabove, where I don't just get the min from the column, but ensure it is equal to or greater than the filter value. Effectively a round-up result. The issue I've been running into with just the filter was that I can't limit the results to just the next highest number. Column values 2, 4, 6: searching 4 results in 4, searching 3 results in 4. I'm using col-min after custom filter of n >= f, then resetting the filter to =<result>.
