### ISSUE TITLE
$.tablesorter.updateCell is not a function - parser-input-select.js

### ISSUE THREAD

**Issue by azjol** [Mottie/tablesorter#1393]
Hello,
I am using tablesorter 2.17.8 from jquery plugins. I tried to add parser-input-select.js 2.28.0 because of selecting all rows. Selecting all rows works perfectly, but if I check single row, console writes **$.tablesorter.updateCell is not a function**. Do you know, how should I fix it?? 

```
$(function(){
	var pagerOptions = { 	// define pager options
		container: $(".pager"), // target the pager markup - see the HTML block below
		output: '{startRow} - {endRow} / {filteredRows} ({totalRows})', // output string - default is '{page}/{totalPages}'; possible variables: {page}, {totalPages}, {startRow}, {endRow} and {totalRows}
		fixedHeight: true, // table row set to a height to compensate; default is false
		cssGoto: '.gotoPage' // go to page selector - select dropdown that sets the current page
	};

	// Initialize tablesorter 
	$("table")
		.tablesorter({
			theme: 'blue',
			headerTemplate : '{content} {icon}', // new in v2.7. Needed to add the bootstrap icon!
			widthFixed: true,
			widgets: ['zebra', 'cssStickyHeaders', 'filter','columnSelector']
		})
		.tablesorterPager(pagerOptions); // initialize the pager plugin


});
```

**Comment by Mottie** [comment]
Hi @azjol!

Please update your version of tablesorter. In the documentation under [`updateCell`](https://mottie.github.io/tablesorter/docs/#updatecell) you'll see that the `$.tablesorter.updateCell` direct function method wasn't added until tablesorter v2.23.0. If you encounter any issues from upgrading, please let me know.

**Comment by azjol** [comment]
**AWESOME!**
It works Mottie! I would like to say BIG THANK you for what have you done. It is amazing!!

**Comment by Mottie** [comment]
Hmm, it should be automatically selecting only visible rows. So rows hidden by the filter should not be checked.... there is a [`checkboxVisible` option](https://mottie.github.io/tablesorter/docs/#checkboxvisible) to change the behavior, but it is set to `true` by default. Setting it to `false` will check all rows, all the time.

**Comment by azjol** [comment]
Yeee, could be! It is quite missleading because after disabling filter is everything checked...But i will find out soon. Anyway, than you for answering!

**Comment by azjol** [comment]
Well, As you wrote....I had variable` checkboxVisible` set on **false**, so I changed it and it works perfectly. Thank you so much Mottie!!
