### ISSUE TITLE
widget-output ignore charset, always use UTF-8

### ISSUE THREAD

**Issue by fjmartinez** [Mottie/tablesorter#1396]
Hello,

I have a simillar issue to #1353 ,
If I change from "data:text/csv" to "text/plain" the result is downloaded and opened in a notepad, but the output enconding is always "UTF-8", I mean, if I set the 
`output_encoding 		: 'data:text/csv;charset=windows-1252,',`
then the downloaded file has always the UTF-8 charset. 
![imagen](https://cloud.githubusercontent.com/assets/686618/25846262/7af968e0-34b1-11e7-9533-c5150c71bfdf.png)

It's seems like something wrong in my configuration or the output process. Can you test to get an output in other charset different to UTF-8 or BOM?

**Comment by Mottie** [comment]
Hi @fjmartinez!

Hmm, sorry I don't have a quick and easy answer for you.

I tried:
* Setting the output as you described above -&gt; UTF-8 No-BOM
* Setting the output to utf-8 with a BOM ([demo](https://jsfiddle.net/Mottie/yL1qon7e/8/)) -&gt; UTF-8 No-BOM
* Using a [text-encoding](https://github.com/inexorabletash/text-encoding) library using windows-1252 ([demo]()) -&gt; UTF-8 No-BOM
* Using [windows-1252](https://github.com/mathiasbynens/windows-1252) encoder ([demo](https://jsfiddle.net/Mottie/yL1qon7e/9/)) -&gt; UTF-8 No-BOM

\* Note the last two methods do require you to include [FileSaver.js](https://github.com/eligrey/FileSaver.js).

I'll investigate this more when I get some free time.

**Comment by Herst** [comment]
BOM for UTF-8 is strongly discouraged BTW, no idea what the issue with Excel is.

BTW, Excel has other major problems with `.csv` files: I heard that the regional settings of the PC affect whether Excel just accepts CSVs using commas (`,`) or semicolons (`;`) as delimiters.

**Comment by fjmartinez** [comment]
I'm not an expert in regexp, 
But if I change the line 349 in the widget-output.js, to evaluate always true, the generated csv has UTF-8 BOM charset. So maybe the bug is in the regexp. 
Change the line 349 from:
`bom = (/^\s*(?:text\/\S*|application\/xml|\S*\/\S*\+xml)\s*;.*charset\s*=\s*utf-8/i.test(wo.output_encoding)) ?
					[ '\ufeff', data ] : [ data ];`
To:
`bom = [ '\ufeff', data ] ;`

I know that this workaround if not a solution, but i think that the final fix is near, someone with experience can take a look in these line?

Thanks

**Comment by Mottie** [comment]
Sorry for taking so long to respond...

From looking at the definition of a [Byte order mark (BOM)](https://en.wikipedia.org/wiki/Byte_order_mark) on Wikipedia, you'll see that Windows-1252 does not support a BOM. Under "Usage" you'll see this paragraph:

> The UTF-8 representation of the BOM is the (hexadecimal) byte sequence `0xEF,0xBB,0xBF`. A text editor or web browser misinterpreting the text as ISO-8859-1 or CP1252 will display the characters `ï»¿` for this.

Anyway, [Windows-1252](https://en.wikipedia.org/wiki/Windows-1252) (a.k.a. CP1252) is a legacy character encoding and shouldn't be used anyway.

**Comment by Mottie** [comment]
If you *must* have a BOM included, you can add it to the `output_encoding` without needing to modify the widget code:

```js
output_encoding : 'data:text/csv;charset=windows-1252,%EF%BB%BF',
```

**Comment by fjmartinez** [comment]
mmm... I'm sorry, I think that I have missed something.
But the issue still happening, I mean, it doesn't matter the output_enconding variable, because always the exported file will be in UTF8 encoding.

**Comment by Mottie** [comment]
If you want to change the encoding, you actually *have to change the encoding*... if you click the link to `js-csv-encoding`, then click the [`text-encoding` link](https://github.com/inexorabletash/text-encoding#non-standard-behavior) you see the following note under "Non-Standard Behavior":

> As required by the specification, only encoding to utf-8 is supported. If you want to try it out, you can force a non-standard behavior by passing the `NONSTANDARD_allowLegacyEncoding` option to TextEncoder and a label.

It's really a pain, so make sure you *really* need the specific encoding before deciding to use it.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
