### ISSUE TITLE
Debug shows 0 rows in log even when there are rows in table.

### ISSUE THREAD

**Issue by Miega** [Mottie/tablesorter#1397]
I'm trying to get the table I created to sort, but only the `thead` is working properly. Looking at my debug logs, I can see the following:

`Building cache for 0 rows (0 rows in log) and 12 columns (0ms)`

The problem is that I *clearly* have a full table created (a dynamically created one that shows up on the site as valid HTML), but it appears that tablesorter isn't seeing them! I am totally lost here. Why is the plugin not seeing my rows?

**Comment by Mottie** [comment]
Hi @Miega!

Without seeing the HTML, I would guess that the HTML is malformed, but you said it was valid. Is the entire table dynamically created or is the content being added to an already initialized table?

If the content is dynamically added, then please check that the rows are being added inside the `<tbody>`.

And lastly, does this problem occur in a specific browser, or multiple browsers?

**Comment by Miega** [comment]
Thanks for the reply!

The skeleton of the table is in the base HTML. Upon loading, the tabular content is dynamically added to the table. I can confirm that the content is being made within the `<tbody>`. I've tested this on Chrome and IE with the same results.

**Comment by Mottie** [comment]
Would it be possible to duplicate the problem [in a demo](http://jsfiddle.net/856bzzeL/)? Please be sure to remove any sensitive data from the table.

**Comment by Miega** [comment]
Due to where and how we store all of our tabular data, I am unable to duplicate the issue in a demo. I can tell you that it uses AJAX calls to create each row when the HTML loads. I also created a function that, when called, initializes the `tablesort` plugin. I had it run after the script was finished with making the table, but that doesn't seem to have changed anything...

**Comment by Mottie** [comment]
What about opening the developer tools inspector and copying the rendered HTML?

**Comment by Miega** [comment]
I can close this issue! The function used to start the plugin needed to be placed within our getJSON statements in our backend JavaScript. Looks like while the plugin loads fine, It wasn't seeing the table created, because it was seeing the table *before* any data was loaded in.

Lesson learned: keep track of where you're initializing your plugins!
