### ISSUE TITLE
Composer update issue

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#1398]
When trying to update to version 2.28.9 through composer, I get the following error:

Problem 1
   - Installation request for mottie/tablesorter ^2.28.9 -> satisfiable by mottie/tablesorter[v2.28.9].
   - mottie/tablesorter v2.28.9 requires jquery ^1.2.6 -> no matching package found.

I am using jquery ^3.1.0, also through composer.

Any idea what the issue might be? I was wondering if the `^1.2.6` in the `composer.json` file should be `>=1.2.6` based on [this link](https://getcomposer.org/doc/articles/versions.md#caret), but then presumably others would have this issue too.
Thanks,

**Comment by Mottie** [comment]
Hi @lindonb!

It looks like it should work... but maybe I need to add the `components/` to the beginning of the `jquery`?

See https://semver.mwl.be/#?package=components%2Fjquery&version=%5E1.2,6&minimum-stability=stable

**Comment by Mottie** [comment]
Ahhh, using `>=1.2.6` allows you to use v2.0+

https://semver.mwl.be/#?package=components%2Fjquery&version=%3E%3D1.2.6&minimum-stability=stable

**Comment by Mottie** [comment]
Please let me know if this fix works.... it may not work until the next version is released.

**Comment by lindonb** [comment]
Okay, will test when the next version is released. And yes, my composer.json has query in components/jquery so adding "components/" makes sense. Thanks for the quick response!

**Comment by Mottie** [comment]
Hey @lindonb!

New release available! Please let me know if composer is happy.

**Comment by lindonb** [comment]
Works like a charm!
