### ISSUE TITLE
Please clarify GPL license version and copyright holders

### ISSUE THREAD

**Issue by paulgevers** [Mottie/tablesorter#1400]
First off, I am working on getting your project into Debian (to fix Debian bug 731095¹). One of the most critical things to get stuff into Debian is to get license and copyright holder information correct.

Now, the license in the package.json file says "MIT or GPL-2.0", however, README.md has links to the licenses for tablesorter and it links to MIT and the current GPL license at GNU.org. The current GNU.org license reads GPL version 3 or later (I would write as GPL-3+). Can you please clarify which version(s) of the GPL you mean?

Further, the copyright is assigned to Christian Bach (2007), which, if I understand correctly, was the author of tablesorter before the fork. Since then a lot has happened. I would at least expect from Mottie/Rob Garrison to consider himself copyright holder (from 2011 until 2017). Would you agree with that view?

¹ https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=731095 : "[libjs-jquery-tablesorter] Please consider switching tablesorter to alternate upstream"

**Comment by christianbach** [comment]
I don't mind giving the copyright for the fork to Rob. I haven't done any work on tablesorter since 2007.

**Comment by paulgevers** [comment]
@christianbach ouch, I see that I phrased this wrong. What I meant is "Rob Garrison to ALSO consider himself copyright holder". So in my opinion there is no need to disclaim copyright for the work done.

**Comment by Mottie** [comment]
@christianbach that's great thank you! If you would add me as a collaborator, I could help a bit with the maintenance of your repo as well. I won't go so far as make it the same as my fork, but I think adding a new release is definitely in order.

@paulgevers my intention was to copy the same licenses from the original plugin. If they don't match, that's my fault and I'll correct it ASAP.

**Comment by Mottie** [comment]
@paulgevers The original version of tablesorter doesn't specify the version of GPL - the link on [tablesorter.com](http://tablesorter.com/docs/) points to [this general GPL license page](https://opensource.org/licenses/gpl-license.php).

So, I'm guessing the intended version was to be GPLv2, since v3 came out around the same time as tablesorter... I think. I seem to remember v3 is more restrictive as well. Will that work for both of you?

I'll go ahead and set everything here to use GPLv2, but really it doesn't matter to me.

**Comment by paulgevers** [comment]
Also the proposed template text in GPLv2 was " either version 2 of the License, or (at your option) any later version". So if just judging from that, it would be GPL-2+. But either way, as long as the license is considered free by Debian, I don't care extremely which one you choose, as long as it is unambiguous (and the MIT license is already free, so any alternative would be fine. But of course both GPL-2 and GPL-3 (or GPL-2+ or GPL-3+) are free as well).

**Comment by Herst** [comment]
@christianbach If you are at it, you please also mention and link to Rob's fork on your site, I see people in various forums (e.g SE) getting confused.

**Comment by Mottie** [comment]
Version  2.28.10 is now available.
