### ISSUE TITLE
Column Selector Options gets cleared when you trigger UpdateAll

### ISSUE THREAD

**Issue by ankurppatel** [Mottie/tablesorter#1406]
Hi Mottie,

I am using tablesorter with "zebra", "filter", "pager", "mark", "resizable", "columnSelector" widgets.
I have used Ajax call method to populate data in to table.

I am facing issue with Column Selector widget. Out of 14 columns in my table, I have only set 2 columns whose <th> property doesn't contain " data-priority='critical' " property. That means those columns will come up as option to show/hide. 
I don't want 'Auto' option in that list that's why I have set following properties
 columnSelector_mediaquery: false,
 columnSelector_mediaqueryHidden: true,
 columnSelector_mediaqueryState: false

Now, I am using my own functionality of Add, Update and Delete. So, whenever I perform any of this operation I am refreshing the table by using  $("#grd").trigger('updateAll'); method
When I do this it clears all the options (to show/hide) of 'Column Selector' widget.

Would you be able to help me with this?

Options before Save
![image](https://cloud.githubusercontent.com/assets/19592344/26436371/2ac2dca2-4155-11e7-86a9-25fba8918e3c.png)

Options after Save
![image](https://cloud.githubusercontent.com/assets/19592344/26436390/55587b02-4155-11e7-8b5f-5913f542f5a7.png)

**Comment by Mottie** [comment]
Hi @ankurppatel!

I wouldn't recommend using "updateAll" unless the content in the `<thead>` is being modified. Otherwise, I have found a solution which will be available in the master branch shortly.

Thank you for reporting this problem.

**Comment by ankurppatel** [comment]
Thank you for the quick response @Mottie  .. I must say you are champ :) 

Would you able to suggest me any other option than UpdateAll. I have seen update and updateRows option but I didn't know how to use it.
- How would i just update the particular row?
- How would I add the new row to table after the Add operation?

Thank you once again.

**Comment by Mottie** [comment]
Thanks! 😸!

If you update the content of the table (one more more rows) use the [`update`](https://mottie.github.io/tablesorter/docs/#update) method (`updateRows` is an alias which was added because `update` was interfering with another library).

If you are adding a new row, then either add it yourself and trigger an "`update`, or use the [`addRows`](https://mottie.github.io/tablesorter/docs/#addrows) method. Either way works.

You can find code examples of the above methods in the documentation.

**Comment by Mottie** [comment]
v2.28.12 has been released with the fix!

**Comment by ankurppatel** [comment]
Thank you @Mottie  .. I will try that ..

Cheers
