### ISSUE TITLE
How to disable <th> border on click

### ISSUE THREAD

**Issue by Maciejszuchta** [Mottie/tablesorter#1408]
Hello
I need to disable the border that appears on th when I click the column that I'm sorting.
Is there a way to achieve this ?

![image](https://cloud.githubusercontent.com/assets/12434636/26576516/6b4020a0-4529-11e7-9c75-a0d43154139b.png)

Regards.

**Comment by Mottie** [comment]
Hi @Maciejszuchta!

That is an [accessibility](https://en.wikipedia.org/wiki/Web_accessibility) outline added by the browser. It is recommended to [never remove it](http://a11yproject.com/posts/never-remove-css-outlines/); but you can modify the style.

If you **don't care about accessibility** &mdash; I hope you do &mdash; then add this css:

```css
th { outline: none; }
```

**Comment by Maciejszuchta** [comment]
Thank you it worked :) 
Very nice plugin !!!
