### ISSUE TITLE
headerTemplate and cssIcon should not be applied when th is declared as non-sortable

### ISSUE THREAD

**Issue by Antoniossss** [Mottie/tablesorter#1409]
So if I have following headers:
```
                    <th>Complete</th>
                    <th>Incomplete</th>
                    <th data-sorter="false">Complete </th>
                    <th data-sorter="false">Incomplete</th>
```

And i iniliatize tablesorter like that:
```
 $(val).tablesorter({
            cssIconAsc: 'fa fa-caret-up',
            cssIconDesc:'fa fa-caret-down',
            cssIconNone:'fa fa-sort',
            headerTemplate:'{content} {icon}'
        })  

```
All headers including non-sortable gets cssIconNone appended. 

Right now as a woraround, I removed `headerTemplate` from settings and manually setup sortable headers like this:

```

                     <th>Complete <i class="tablesorter-icon fa fa-sort"/></th>
                     <th>Incomplete <i class="tablesorter-icon fa fa-sort"/></th>
```

Is this a bug? Or am I using tablesorter wrong?

**Comment by Mottie** [comment]
Hi @Antoniossss!

The `headerTemplate` will apply to all headers by default, as you might want to have an icon showing in a disabled header. You can modify this behavior using the [`onRenderTemplate` callback](https://mottie.github.io/tablesorter/docs/#onrendertemplate); the index parameter matches the index of the header and not necessarily the column when you have more than one header row.

There is also a [`onRenderHeader` callback](file:///Z:/Repos/+Tablesorter/tablesorter/docs/index.html#onrenderheader) which can be used to manipulate the header contents.

When a column is disabled, a `sorter-false` class name is always added. You can use this to alter the style of the disabled header.

Given the above information, I could see a benefit in adding a new `cssIconDisabled` option.

**Comment by Antoniossss** [comment]
This would very handy and clean solution like adding `data-cssIconDisabled=true` to <th> markup. Good to know it is not a bug just a lack of feature. Consider a request :) Thank you quick replay

**Comment by Mottie** [comment]
A `cssIconDisabled` option has been added and is now available in the master branch.

I'm not sure where `data-cssIconDisabled=''` came from as the `cssIcon` options are not currently available to be set using a data-attribute. Did you need a different disabled icon depending on the column? I think this might be an edge case and would be better handled using the [`onRenderHeader` callback](https://mottie.github.io/tablesorter/docs/#onrenderheader).

**Comment by Mottie** [comment]
Version 2.28.13 is now available.
