### ISSUE TITLE
Changing Display To Mobile

### ISSUE THREAD

**Issue by TaylorFoster90** [Mottie/tablesorter#1410]
I used this plugin before this fork.

Before I ask my question I just wanna say, REALLY nice plugin. I am in love with all the options.

On the original plugin ( I used it about a year ago ) I remember it was able to collpase to mobile. It was a really neat feature. Does this fork have that feature as well? Cant seem to find it.

**Comment by Mottie** [comment]
Hi @TaylorFoster90!

Thanks! I'm not sure what you mean by "collapse to mobile", but there is a [reflow widget](https://mottie.github.io/tablesorter/docs/example-widget-reflow.html) that will change the table layout for narrow screens.

**Comment by TaylorFoster90** [comment]
@Mottie this is exactly the widget I was talking about! TYSM!
