### ISSUE TITLE
Allow function to dynamically calculate stickyHeaders_offset

### ISSUE THREAD

**Issue by MartinMuzatko** [Mottie/tablesorter#1412]
Hello.

My fixed header is responsive, it resizes on mobile. However, tablesorter does not account for that as it looks.

I think the height is only retrieved once on initialization, not when making the sticky header visible.

**Comment by Mottie** [comment]
Hi @MartinMuzatko!

Hmm, both the stickHeaders and cssStickyHeaders widgets *should* allow for updating of the offset widget option dynamically, but you won't see the updated value get applied until the page is scrolled, or you trigger a "resize" event on the window.

And of course I just tested it and it didn't work 🤣 

I'll spend some time on this today.

**Comment by MartinMuzatko** [comment]
Thank you :)

**Comment by Mottie** [comment]
Ok, this fix is now available in the master branch for the `stickyHeaders` widget. The `cssStickyHeaders` widget was already working properly.

If you don't want to trigger a "resize" event, you could also trigger a "stickyHeadersUpdate" event on the table to apply the modified offset:

```js
$('table').trigger('stickyHeadersUpdate');
```

**Comment by Mottie** [comment]
Here's a demo that changes the offset after 5 seconds: https://jsfiddle.net/f36416oy/42/
