### ISSUE TITLE
Scrollable table with sticky header

### ISSUE THREAD

**Issue by MartinMuzatko** [Mottie/tablesorter#1413]
Hello! 
I have a somewhat specific problem.
Our company is using huge tables to display documentation.
The tables have a fixed with but should have fixed headers but should be scrollable on X axis.

The headers are already refreshed when scrolling vertically, but not horizontally.

Example: https://codepen.io/MartinMuzatko/pen/xrKbmv

I know I can attach an event handler on init. But how do I tell tablesorter to reposition on scroll?
`refreshWidgets` does not do the trick, but this is the only event that is documented. :/

Thank you in advance @Mottie  :)

Second problem would be, to cut the sticky header to be only the size of the table. Since it is a fixed element, I have to trim it manually, which is not that big problem, since I have the init event.

Best,
Martin

**Comment by Mottie** [comment]
Hi @MartinMuzatko!

I think you might be better off with the css sticky headers widget... it can be a little "jumpy" but it works perfectly without any options for your situation - https://codepen.io/Mottie/pen/dRbNRK

**Comment by MartinMuzatko** [comment]
Ah! Didn't find that in the documentations :) Beautiful :D
