### ISSUE TITLE
Uncaught Error sortNatural (im sorting strings)

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1415]
Here's the console error:

jquery.tablesorter.js:1522 Uncaught TypeError: a.replace is not a function
    at $.extend.tablesorter.ts.sortNatural (http://localhost:62126/Scripts/tablesorter/jquery.tablesorter.js:1522:12)
    at $.extend.tablesorter.ts.sortNaturalAsc (http://localhost:62126/Scripts/tablesorter/jquery.tablesorter.js:1548:15)
    at http://localhost:62126/Scripts/tablesorter/jquery.tablesorter.js:858:61
    at Array.sort (native)
    at multisort (http://localhost:62126/Scripts/tablesorter/jquery.tablesorter.js:820:11)
    at http://localhost:62126/Scripts/tablesorter/jquery.tablesorter.js:796:6

And here's a screen:

![image](https://cloud.githubusercontent.com/assets/11836187/26733281/5230c93c-4788-11e7-9bb6-2cd15f551ec7.png)

**Comment by MoMack20** [comment]
It happens when sorting on the #packages column which is a string. Odd thing is, it only happens when I add a column for the table for expanding a row. The expansion and everything works with child table, but then sorting on this column breaks. I have 19 columns with the expansion column and 18 without it (when it sorts fine). I'm at a loss with where to go from here. Any help is appreciated

**Comment by Mottie** [comment]
Hi @MoMack20!

The natural sort algorithm doesn't convert the values it is sorting into strings... this was done because the conversion was making the sort take a lot longer in older versions of IE. It probably isn't necessary anymore, but since it is still in place.

To get around this issue, make sure to set the `# Packages` column parser to digit:

```html
<th class="sorter-digit"># Packages</th>
```

**Comment by MoMack20** [comment]
The columns are strings though. That's what's confusing. No other numerical column in the table sorts using sortNatural. Only this one. And only after I add the 19th column into the table

**Comment by MoMack20** [comment]
Thanks for the speedy response btw. I really appreciate it

**Comment by Mottie** [comment]
If you could [duplicate the issue in a demo](https://jsfiddle.net/Mottie/bbxxomhx/), it would make it easier for me to troubleshoot the problem.

**Comment by Mottie** [comment]
There... I'm going to stop worrying about slow IE 😸

**Comment by MoMack20** [comment]
I don't think I would be able to recreate this anomaly. Its only happened so far  when add that 19th column. Nothing changes in the table but a column at the beginning of the table that has "+" for all the rows. I'll try to get you more details

**Comment by Mottie** [comment]
Try the updated version in the master branch... I've only modified the `jquery.tablesorter.js` file. The next release will be shipped very soon.

**Comment by MoMack20** [comment]
I'm working with fork 2.28.0

**Comment by MoMack20** [comment]
On the debug, why does it not show the last 3 columns?

![image](https://cloud.githubusercontent.com/assets/11836187/26736340/a3b14b32-4793-11e7-8282-726c58c153e9.png)

**Comment by Mottie** [comment]
Is that the debug *after* the columns are added and an "updateAll" is triggered?

**Comment by MoMack20** [comment]
All the columns are added to dom at one time before the tablesorter function is called

**Comment by Mottie** [comment]
In that case, it sounds like the HTML of the extra columns might not be valid.

**Comment by MoMack20** [comment]
I construct the html the exact same way for another table that has less columns and everything works fine.
Really tryna wrap my head around this lol. I might just have to suck it up and spend some time trying to replicate this in a demo

**Comment by Mottie** [comment]
Check the HTML in the DOM... use the developer tools to inspect it.

**Comment by MoMack20** [comment]
The DOM looks fine to me.
![image](https://cloud.githubusercontent.com/assets/11836187/26737206/2a515d6e-4797-11e7-9f9d-1bbdc16ab23b.png)

Every other row is identical and the header table matches.

Adding that first column with the "+" seems to be what triggers the problem (without that column it works great).

Here's the error message since I update the tablesorter.js 

![image](https://cloud.githubusercontent.com/assets/11836187/26737299/7d6ba324-4797-11e7-9089-33f30c0f7922.png)

**Comment by MoMack20** [comment]
I'm sorry for the inconvenience. It seems like such a unique case that its something that I'm doing wrong, but I just can't pin it down :/

**Comment by Mottie** [comment]
Try adding a `"sorter-false"` to disable sorting for that column - https://jsfiddle.net/bbxxomhx/437/

**Comment by MoMack20** [comment]
Disabling works. But I would really like to be able to sort by that column if I could.

**Comment by Mottie** [comment]
it's a column full of `+`'s isn't it?

**Comment by MoMack20** [comment]
That column works. When its clicked it adds and child row and then it changes to a "-". You can sort by which row is displaying its child, which works. The column in the first image with the header "# Pacakges" is the one the that causes the error.

**Comment by MoMack20** [comment]
It seems that the 17th column always has the sorting error. I've shuffled the column order and it doesn't matter which column-value is there, the 17th always errors on sort.

**Comment by Mottie** [comment]
In the debug log, does the parser get set to "digit"? Again, a "sorter-digit" class name should be added to the header cell.

**Comment by MoMack20** [comment]
The log only shows the first 16 columns. It errors out on pure strings as well (when all the rows for that column are "yes"

**Comment by MoMack20** [comment]
I'm using the scroller widget if that makes any difference

**Comment by MoMack20** [comment]
Stepping through the debugger. 
![image](https://cloud.githubusercontent.com/assets/11836187/26739682/d24bd95a-47a0-11e7-9551-5545b7d289ed.png)

this is in the file jquery.tablesorter.js

In the locals, you can see that the variable "a" is a table row. And it is pointed a the last row in my table

**Comment by Mottie** [comment]
Please try v2.28.13 and see if it resolves your issue.

**Comment by MoMack20** [comment]
Hello again Mottie, sorry I was away over the weekend. I updated to v2.28.13 and no longer get a console error, but a sort is not being applied to the column.

**Comment by MoMack20** [comment]
![image](https://cloud.githubusercontent.com/assets/11836187/26787996/ccbc58e4-49d9-11e7-9e03-c9a3adcf4a47.png)

A table row is still being passed in for sorting instead of the contents of each column. Is there a script that I could have written that interferes with the sorting script?

**Comment by MoMack20** [comment]
Is there anyway I can get the debug to show me more than 16 columns?

**Comment by Mottie** [comment]
Please share some code... I have not seen a single line of the code being used.

**Comment by MoMack20** [comment]
Haha, sorry about that. This is everything I use to interact with tablesorter

InitializeGrid: function(tableHtml, container, tableId) {
        $(container).children().each(function () {
            if($(this).attr("id") != "spinner")
                $(this).remove();
        });
        $(container).append(tableHtml);
        var $scroller = $('.tablesorter-scroller-table');
        var scrollPos = 0;
        $(".Grid").tablesorter({
            cssChildRow: "childTableRow",
            theme: "metro-dark",
            widgets: ['scroller', 'zebra'],
            widgetOptions: {
                scroller_height: "650",
                scroller_upAfterSort: false,
                zebra: ["odd", "even"],
            },
            debug: true
        })
        .bind("sortStart", function (e, t) {
            ShowLoadingSpinner();
            $scroller = $('.tablesorter-scroller-table');
            scrollPos = $scroller.scrollspy().scrollTop();
        })
        .bind("sortEnd", function (e, table) {
            $(".tablesorter-header").each(function () {
                $(this).find("div").html(function () {
                    return $(this).data("noSort");
                });
            });
            $(".tablesorter-headerAsc").each(function () {
                $(this).find("div").html(function () {
                    return $(this).data("sortUp");
                });
            });
            $(".tablesorter-headerDesc").each(function () {
                $(this).find("div").html(function () {
                    return $(this).data("sortDown");
                });
            });
            $("#GridContainer").width("80%");
            $("#" + tableId).tablesorter().trigger("update", false);
            $("#GridContainer").width("99.6%");
            $("#" + tableId).tablesorter().trigger("resize");
            $scroller.scrollTop(scrollPos);
            FillRemainingHeight(tableId);
            HideLoadingSpinner();
        });
        $(".Grid").find("th").find("div").each(function () {
            $(this).data("sortUp", "<span style=\"float:right;\">&#9650;</span>" + "<span>" + $(this).html() + "</span>");
            $(this).data("sortDown", "<span style=\"float:right;\">&#9660;</span>"+ "<span>" + $(this).html() + "</span>");
            $(this).data("noSort", $(this).html());
        });
        FillRemainingHeight(tableId);
        $(window).resize(function () {
            FillRemainingHeight(tableId);
        })
        $(".Grid").tablesorter().trigger("update", false);
    }

**Comment by Mottie** [comment]
Sorry, I've been busy/distracted recently. Did you find a solution?

**Comment by MoMack20** [comment]
I just swapped places between one of the columns that won't need sorting with that column. Such a peculiar occurrence though.

**Comment by timkingman** [comment]
@MoMack20 Does your table have all rows the same length? I saw behavior like this (and even breaking on column 17), and eventually tracked it down to having a footer row that had fewer columns than the main tbody. Adding empty cells to that row fixed my sorting for all columns.

**Comment by MoMack20** [comment]
!!!! I think that's it! I put together all the table stuff on the server side and I don't think i changed my colspan for the footer. I'll try it when i get back to work

**Comment by MoMack20** [comment]
It worked! It would've been another week or so until i realized that mistake. Gotta remember to always check the footer when the error doesnt make any sense lol

**Comment by Mottie** [comment]
I just added a `console.error` message when a mismatch of column size is found. By default, only the `thead` and `tfoot` are checked. The cells in the `tbody` are only checked by certain widgets like the math and column selector widget (only when a `colspan` exists).

You'll now see an error message similar to this:

> Invalid or incorrect number of columns in the THEAD or TFOOT; expected x, but found y columns

**Comment by TheSin-** [comment]
This change seems to break if using columnSelector widget with a foot using colspan, since the colspan is updated to count only visible rows, the thead to tfoot count will not match

**Comment by TheSin-** [comment]
last commits fixed my reported issue

**Comment by Mottie** [comment]
Fixed in v2.28.15!
