### ISSUE TITLE
can't get icons to show up on my sorted table

### ISSUE THREAD

**Issue by w-** [Mottie/tablesorter#1416]
just testing tablesorter out right now
the demos on the site all display properly for me. 
when i attempt to apply on my own table, none of the sort icons show up.
am i missing something?

```
<table id="abe_data">
	<thead>
		<tr>
			<th>Name</th>
			<th>Total</th>
		</tr>
	</thead>
	<tbody>			
		<tr>
			<td>{{ item.first_name }} {{ item.last_name }}</td>
			<td></td>
		</tr>			
	</tbody>
</table>

<script>
  $("#abe_data").tablesorter({
  	"theme": 'dropbox'
  });
  
</script>
```

**Comment by Mottie** [comment]
Hi @w-!

For a few themes, you'll need to include an `{icon}` placeholder in the `headerTemplate` ([demo](https://jsfiddle.net/bbxxomhx/436/):

```js
$(function() {
  $('table').tablesorter({
    theme: 'dropbox',
    headerTemplate: '{content}{icon}'
  });
});
```

Themes like Bootstrap and jQuery UI would require the "uitheme" widget to work properly.

**Comment by w-** [comment]
Amazing response time. 
I literally just figured this out  after going to see the source on the themes page.
Thank you @Mottie !!
And thank you for your work on this library.
