### ISSUE TITLE
Parser for 2nd generation data

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1417]
I thought I'd ask before I wrote my own parser. Is there an existing one that handles data that's wrapped one generation down such as 
`<td><button>press me</button></td>`
or
`<td><span>new span</span></td>`

**Comment by Mottie** [comment]
Hi @MoMack20!

The default text parser extracts all text content from the table cell. So in both of the cases you shared, only the text would be extracted. If you have other content that you want to exclude, you can use the [`textExtraction` callback](https://mottie.github.io/tablesorter/docs/#textextraction) and set it to apply to the entire table, or a specific column. You don't necessarily *need* to have a custom parser.

**Comment by MoMack20** [comment]
Thank you. Turned out to be another issue with footers lol.
