### ISSUE TITLE
Tablesorter resorting in combination with setInterval and CSS3 animation

### ISSUE THREAD

**Issue by savicmi** [Mottie/tablesorter#1423]
I make an application for betting where I load new JSON data on every 3s and if it is necessary, add, delete or update some rows. I use tablesorter plugin and it's working great, but I have one specific case. If there is a result change, I add "highlight" CSS class so that row will pulse about 8 seconds in orange using CSS3 animation and after completing of animation, that class is removed. This works perfectly, but if I use tablesorter resort option, that animation starts again on every 3s and practically never ends, because it lasts longer than set interval (8s is less than 3s). So, if I put resort option to false, the problem with animation doesn't exist and it will be continuous until it's finished, but I would like to use resort option on every update.

To better explain the situation, here is a JSFiddle https://jsfiddle.net/savicmi/h9gpqrwn/15/ that demonstrates the problem. If it is added a row with Basketball in it, that row's background will pulse. It seems that tablesorter redraws table's body if it is resort == true, and probably it is the reason for starting CSS3 animation from the beginning instead of continuous duration up to the end of an animation. How can this be solved?

**Comment by Mottie** [comment]
Hi @savicmi!

I modified your demo a bit... instead of applying the animation immediately after you add the row, I applied it *after* the "update" method finished processing via the callback method ([demo](https://jsfiddle.net/Mottie/h9gpqrwn/16/)):

```js
$(document).ready(function() {
  var isFirst = true;

  $(".table-liveevents").tablesorter({
    sortList: [
      [1, 0]
    ],
    ignoreCase: true,
    textExtraction: {
      '.sorter-date': function(node, table, cellIndex) {
        var dat = node.textContent.split(/\/|\s|\:/);
        var date = dat[1] + '/' + dat[0] + '/' + dat[2] + ' ' + dat[3] + ':' + dat[4];
        return new Date(date).getTime();
      }
    },
    resort: true
  });

  var data = {
    "live_ev": [{
      "id": 206622,
      "date": "28/06/2017 11:55",
      "name": "Evtimova, Dia - Dulgheru, Alexandra",
      "sport": "Tennis"
    }, {
      "id": 206553,
      "date": "28/06/2017 11:40",
      "name": "Sabanin, Yan - Matsukevitch, Denis",
      "sport": "Tennis",
    }, {
      "id": 206754,
      "date": "28/06/2017 13:05",
      "name": "Crvena Zvezda - Partizan",
      "sport": "Basketball"
    }]
  };

  function animate() {
    var $basketball = $('.table-liveevents').find('tr:has(td:contains("Basketball"))');

    if ($basketball.length > 0 && isFirst == true) {
      $basketball.addClass("highlight").one('webkitAnimationEnd mozAnimationEnd msAnimationEnd oAnimationEnd animationend', function() {
        $(this).removeClass("highlight");
      });
      isFirst = false;
    }
  }

  function addRow(data, table) {

    if (table.find('tr#r_' + data.id).length == 0) {
      var tr = document.createElement('tr');
      tr.id = 'r_' + data.id;
      tr.className = 'details';
      for (var j = 1; j <= 3; j++) {
        var td = document.createElement('td');
        td.appendChild(document.createTextNode(data[Object.keys(data)[j]]));
        tr.appendChild(td);
      }
      table.find('tbody').append(tr);
      // .trigger( 'addRows', [ $row, resort, callback ] );
      table.trigger('update', [true, animate()]);
    }
  }

  setInterval(function() {
    var i = Math.floor(Math.random() * data.live_ev.length);
    addRow(data.live_ev[i], $('.table-liveevents'));
  }, 3000);

});
```

Oddly, I tried to use the [`addRows` method](https://mottie.github.io/tablesorter/docs/#addrows) to update the internal cache, but it wasn't applying the sort. I'll have to look into that when I get some more free time. But the demo I shared above is using "update" and it appears to work as you would expect.

**Comment by savicmi** [comment]
Great, thanks! It's now working.

**Comment by savicmi** [comment]
Hi @Mottie. After more testing, this unfortunately doesn't work as expected. It works only correctly if it's animated last added row, and then the animation will last about 8s ( 4x2s blinking) as expected. In other cases, the animation restarts when other row is added to the table. For example, if the row which includes Basketball is added as the first, the animation will start, but if a new row is added in the meantime, before the end of that animation, the table is updating and the previous animation starts from the beginning. It means that the animation will last longer, in this small example with 6 rows, 10-20s instead of 8s, but in my real project, I have many more rows for adding, deleting and updating, so the animations never end, and after some time almost the entire table is blinking orange :)

If you have any idea how to overcome this, let me know. Thanks.

**Comment by Mottie** [comment]
It you add rows faster than the animation time, the animation is reset when the rows are re-appended to the table after sorting. I think the easiest solution would be to add a separate timer for each highlight and then remove the pulse animation in the callback... e.g.

```js
$row.addClass('pulse');
setTimeout(function(){
  $row.removeClass('pulse');
}, 3000);
```

It's not as nice as having the animation with a built-in timer, but it'll be more consistent.

**Comment by savicmi** [comment]
Ok, thank you. It will be acceptable.
