### ISSUE TITLE
Adding/removing columns with filter+pager causes mismatched filter column count

### ISSUE THREAD

**Issue by InhumanSoul** [Mottie/tablesorter#1425]
Adding/removing columns on a table with the filter and pager widgets causes the filter row to have mismatched columns compared to the rest of the table. However, this problem only appears the first time a column is added/removed. Thereafter everything works as expected (until the page is reloaded).

Since 2.18.14 this now also displays a console error (due to #1415).

I've made [this jsFiddle](http://jsfiddle.net/qkn6ye4o/6/) to showcase the error.
If you remove the pager widget the error goes away, so I guess it has something to do with the filter+pager combination.

**Comment by Mottie** [comment]
Hi @InhumanSoul!

If you're going to completely clear out the table and add new content, it would be better to destroy the instance of tablesorter, then reinitialize it - [demo](http://jsfiddle.net/qkn6ye4o/8/).

```js
var table = [{C1: "Row 1", C2: "with", C3: "data", C4: "some"},
            {C1: "Row 2", C2: "with", C3: "data", C4: "more"},
            {C1: "Row 3", C2: "with", C3: "data", C4: "extra"}];

$(function() {
  var jTable = $("#myTable");
  jTable.append($("<thead></thead>"));
  jTable.append($("<tbody></tbody>"));
  tablesorterInit(jTable);

  $("#enableC4").on("change", refreshTable);
  refreshTable();
});

function refreshTable() {
  var columnNames = ["C1", "C2", "C3"];

  if ($("#enableC4").prop("checked")) {
    var columnNames = ["C1", "C2", "C4", "C3"];
  }

  populateTable($("#myTable"), table, columnNames);
}

function tablesorterInit(jTable) {
  jTable.tablesorter({
      theme: "blue",
      widgets: ["filter"]
    })
    .tablesorterPager({
      removeRows: false
    });
}

function populateTable(jTable, table, columnNames) {
  var tBody = jTable.find("tbody");
  var tHead = jTable.find("thead");

  // remove tablesorter, but leave the class names in place (`false` flag)
  jTable.trigger('destroy', false);

  //Populate header
  tHead.empty();
  var headerRow = $("<tr></tr>");
  columnNames.forEach(function(name) {
    headerRow.append($("<th></th>", {
      text: name,
      class: "filter-match"
    }));
  });
  tHead.append(headerRow);

  //Populate body
  tBody.empty();
  for (var i = 0; i < table.length; i++) {
    var rowElement = $("<tr></tr>");
    columnNames.forEach(function(name) {
      rowElement.append($("<td></td>").append(table[i][name]));
    });
    tBody.append(rowElement);
  }

	tablesorterInit(jTable);
}
```

I've never been happy with the behavior or performance of the "updateAll" method, it needs to be rewritten. I would recommend avoiding it if at all possible.

**Comment by InhumanSoul** [comment]
That works for me. Thank you @Mottie.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by InhumanSoul** [comment]
I have resolved my problem. However, since it is still a bug in the "updateAll" method I figured I'd leave the issue open.

If you're curious, I didn't end up using your suggested solution, partly because it was slow on larger tables and partly because I realized I didn't actually need to change the order of the columns. So I ended up using the column selector widget instead.
