### ISSUE TITLE
Reflow and Filter Widgets

### ISSUE THREAD

**Issue by xichro** [Mottie/tablesorter#1426]
I've been playing with Reflow after adding multiple widgets (I didn't even know it existed!) and I can't find a way to hide all but one column to filter on when in a mobile-friendly view (max-width: 480px). I'd like to hide all .tablesorter-filter elements except one, because it's the most used column for filtering based on a unique ID. I'd rather do this dynamically with js rather than with css. I can either show all filter input boxes, or none, but no in-between as I'd like.

Is there a solution that can help with this?

**Comment by Mottie** [comment]
Hi @xichro!

You can use the reflow and columnSelector widget together (see [second demo here](https://mottie.github.io/tablesorter/docs/example-widget-reflow.html#demo)). And to keep one column visible, you would need to add a `data-priority="critical"` to the header.

If you have still having trouble, then please modify [this demo](https://jsfiddle.net/k8qjkL9p/) to show me the problem and I will try to help.

**Comment by xichro** [comment]
Hi @Mottie,

Thanks for the reply. I've updated the [above demo](https://jsfiddle.net/k8qjkL9p/2/) to show what I mean (I don't think I need columnSelector :) ). When you resize the content window to a mobile format you can see that all filters are showing with all column headers. However, I'd like for all column headers to show but only one filter, say for instance in this example only the one linked to Name.

Thanks!

**Comment by Mottie** [comment]
Hmm, one way is to add a class to the "Name" column filter (using [`filter_cellFilter`](https://mottie.github.io/tablesorter/docs/#widget-filter-cellfilter), then hide everything except that filter in the media query ([demo](https://jsfiddle.net/k8qjkL9p/3/)).

```css
@media ( max-width: 35em) {
  /* hide all filters except the name column filter */
  .tablesorter-filter-row td:not(.name) {
    display: none;
  }
  /* ... */
}
```

```js
$(function() {
  // simple reflow widget + columnSelector & stickyHeaders widgets
  $("#table2").tablesorter({
    theme: 'bootstrap',
    headerTemplate: '{content}{icon}',
    widgets: ['zebra', 'uitheme', 'reflow', 'filter'],
    widgetOptions: {
      // add "name" class to "Name" column
      filter_cellFilter : [ 'name' ],
      
      // class name added to make it responsive (class name within media query)
      reflow_className: 'ui-table-reflow',
      // header attribute containing modified header name
      reflow_headerAttrib: 'data-name',
      // data attribute added to each tbody cell
      // it contains the header cell text, visible upon reflow
      reflow_dataAttrib: 'data-title'
    }
  });
});
```

**Comment by xichro** [comment]
This works well for the first column filter, however it didn't for any other. I've instead removed the filter_cellFilter and adapted the CSS to match the following:
`@media ( max-width: 480px ) {
	.tablesorter-filter-row td:not(:nth-child(5)) {
		display: none;
	}
}`

See [here](https://jsfiddle.net/k8qjkL9p/5/) for the updated code.

In the end it was more of a CSS fix than a tablesorter one (unless we can specify the correct cellFilter in tablesorter somehow?). Thanks for assisting me though @Mottie.

**Comment by Mottie** [comment]
> can specify the correct cellFilter in tablesorter somehow?

The [`filter_cellFilter` option](https://mottie.github.io/tablesorter/docs/#widget-filter-cellfilter) adds class names to the filter table cells, you can define a different name for each column (set with an array), or define the same name for all columns (set as a string).

**Comment by xichro** [comment]
Thanks @Mottie, I've modified your original code to match an array to specify the column.
