### ISSUE TITLE
Pager buttons or links for pages instead of select dropdown

### ISSUE THREAD

**Issue by nasospsa** [Mottie/tablesorter#1427]
Is there any change to implement also a buttons ui for changing pages?
Not just buttons for first prev next last.

**Comment by Mottie** [comment]
Hi @nasospsa!

If you look in the [docs under "work-in-progress"](https://mottie.github.io/tablesorter/docs/#demos), you'll find a link to a [Custom pager control script demo](https://mottie.github.io/tablesorter/beta-testing/example-pager-custom-controls.html). The code in this demo uses the [pager-custom-controls](https://github.com/Mottie/tablesorter/blob/master/beta-testing/pager-custom-controls.js) extension which overrides the built-in pager controls.

You can use it or at least get an idea from the code on how to implement your own custom pager.

Also, there are other examples on the [home wiki page](https://github.com/Mottie/tablesorter/wiki#widgets) under "Pager" using simplePaginator.js and @TheSin-'s custom pager with progress bar.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
