### ISSUE TITLE
icon-white class within bootstrap 3 theme conflicts with icomoon CSS selector

### ISSUE THREAD

**Issue by manuelra** [Mottie/tablesorter#1432]
Icomoon (https://icomoon.io/#docs) which provides numerous glyphicons to bootstrap includes on its CSS files a wide scope selector [class*="icon-"]. 

When using tablesorter's bootstrap theme the icomoon selector will conflict with the icon-white class proposed on tablesorter documentation (https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v3.html), and the icon will be not properly presented.

  $.tablesorter.themes.bootstrap = {
 ...
    icons        : '', // **add "icon-white"** to make them white; this icon class is added to the <i> in the header
...
}

**Comment by Mottie** [comment]
Hi @manuelra!

Thanks for pointing this out... I'll have it fixed in the master branch soon.
