### ISSUE TITLE
tablesorter no longer binding to jquery correctly?

### ISSUE THREAD

**Issue by laytong** [Mottie/tablesorter#1433]
As of 2.28.8 upwards. When I upgrade I get $(...).tablesorter is not a function.
I both require jquery  and `require('tablesorter')` at the top of the file but from that version onwards it can't seem to find it. Any ideas would be helpful.

Thanks.

**Comment by Mottie** [comment]
Hi @laytong!

I haven't changed the factory wrapper recently, so I'm not sure why you're seeing that error. Are you using the version in the `dist` folder?

**Comment by laytong** [comment]
Hey thanks for responding so quickly

So we install tablesorter via yarn and then our build system uses browserify to pull it in via require. There's definitely something rather strange going on?

**Comment by Mottie** [comment]
Not that I'm aware of...

**Comment by laytong** [comment]
Since I can't pinpoint the cause I guess I'll close this for now. If I can find a way to consistently reproduce I'll re-open. 😢
