### ISSUE TITLE
External Date Range Filter Not Updating Table

### ISSUE THREAD

**Issue by DoctorWhite** [Mottie/tablesorter#1434]
I have a table that is already filtered by an external search field and I want to filter it by two additional fields for dates (to and from). I don't want to add the filter row however, so my solution was to add it and then have the two external fields update the range fields. This is the existing code for initialization.

<pre><code>$('#checks_table').tablesorter({
    dateFormat: 'us',
    widthFixed: true,
    headers: {
      0: {sorter:'digit'},
      3: {sorter: 'text'},
      6: {sorter: 'digit'}
    },
    widgets: ['zebra', 'filter'],
    widgetOptions : {
      filter_external : '.search',
      filter_reset: '.reset',
      filter_hideFilters: true,
      filter_formatter: {
        5 : function($cell, indx){
          return $.tablesorter.filterFormatter.uiDatepicker($cell, indx, {
            textFrom: 'From',
            textTo: 'To',
            changeMonth : true,
            changeYear : true
          });
        }
      }
    }
  }).tablesorterPager(pagerOptions);
  $('#checks_table').bind("sortStart", function() {
    $('.datepicker').datepicker('hide');
 });
$('.datepicker-header-from').datepicker({
    showOn: 'both',
    buttonText: false,
    onSelect: function(dateText, inst) {
      $('input.dateFrom').val(dateText);
      $('#checks_table').trigger('search',false);
    },
    changeMonth: true,
    changeYear: true
  });
  $('.datepicker-header-to').datepicker({
    showOn: 'both',
    buttonText: false,
    onSelect: function(dateText, inst) {
      $('input.dateTo').val(dateText);
      $('#checks_table').trigger('search',false);
    },
    changeMonth: true,
    changeYear: true
  });</code></pre>
The datepicker code is updating the fields, but it isn't triggering the filtering. Is there a way to make these fields search while staying hidden?

**Comment by Mottie** [comment]
Hi @DoctorWhite!

If I am understanding correctly... instead of using the filter formatter and triggering a 'search' in the `onSelect`, store the from/to dates in a variable and use the [`setFilters` method](https://mottie.github.io/tablesorter/docs/#function-setfilters).

If you need help implementing it, then please modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) with the code you are using to make it easier for me to troubleshoot and provide a solution.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
