### ISSUE TITLE
Tablesorter Warning! "table.config.widgetOptions.filter_functions" option not recognized

### ISSUE THREAD

**Issue by Miega** [Mottie/tablesorter#1436]
I'm getting this warning whenever I try to test my table filters.

`Tablesorter Warning! "table.config.widgetOptions.filter_functions" option not recognized`

I have `jquery.tablesorter.js` and  `jquery.tablesorter.widgets.js` included in my `<HEAD>`, and they're ordered correctly.

**Comment by Mottie** [comment]
Hi @Miega!

That is a warning that is meant to remind you that the named option was seen in the `widgetOptions`, but either the widget has not been initialized or the option has a misspelling.

In this case, it the filter widget was not initialized, and the option was set.

If it is incorrect, then please share the code you are using to initialize tablesorter.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
