### ISSUE TITLE
Support for Pager with few million filtered rows

### ISSUE THREAD

**Issue by KarlBaumann** [Mottie/tablesorter#1437]
I am using tablesorter with few million rows, the data is processed on serverside, and is pretty quick, but the problem is to calculate the number of filtered rows, because mysql has to do full table scan to get this number.

So I want to know, is it possible to **use pagination without knowing amount of filtered rows**?

**Comment by Mottie** [comment]
Hi @KarlBaumann!

You can set the pager [`output`](https://mottie.github.io/tablesorter/docs/#pager-output) to display whatever information you want the user to see. The [`ajaxProcessing` function](https://mottie.github.io/tablesorter/docs/#object) doesn't require a filtered row count value, it's optional, but the total row count is required so the pager knows when it has reached the end.

**Comment by KarlBaumann** [comment]
But total row number is needed to detect end only when filter is not used. In cases when filtering is done, filtered row count is the end.
Am I wrong?

**Comment by Mottie** [comment]
Hmm, I think the easiest work-around for this would be to set the `filteredRows` value equal to the `totalRows`.

**Comment by KarlBaumann** [comment]
It looks like tablesorter already does that, but then pager is not able to correctly detect the last page.

**Comment by Mottie** [comment]
Fixed per our discussion in IRC using the following code:

```js
pager_ajaxProcessing: function (result, table, xhr) {
  if (result) {
    result.rows = $(result.rows);
    var pager = table.config.pager,
      rows = result.rows.length;
    // set the filteredRows to the current page * size setting,
    // add one so the next page is still available
    result.filteredRows = pager.size * (pager.page + 1) + 1;
    if (rows < pager.size) {
      // adjust filteredRows size to prevent paging to the next empty page
      result.filteredRows += rows - pager.size;
    }
    // ...
    return result
  }
},
```
