### ISSUE TITLE
All Groups Disappear after Content Changing and Update Triggered

### ISSUE THREAD

**Issue by mhoffmann10** [Mottie/tablesorter#1439]
I have modified the basic example of the grouping widget for a dashboard I am creating.

There are 2 columns that the user will be changing and after these changes the table needs to resort the data.

When I change one of the data cells the table data is completely hidden.  By click on the header again I get get it to reset and show all data is now in it's new appropriate spot. 

Any suggestions as to why this may be happening?

```

$("input[name='sort']").change(function() {
		var sort = $(this).val();
		var call_id = $(this).parent().parent().children("input[name='call_id']").val();
		console.log(sort);
		console.log(call_id);
		
		var dataString = 'sort='+ sort + '&call_id=' + call_id;
			
	    $.ajax({
	        data: dataString,
			type: 'POST',
			url: '<?php echo base_url(); ?>admin/updatesort/'
	    });
	    
		$('table.dispatchsort').trigger('update',[true, console.log('triggered')]);
	});

```
```

$("table.dispatchsort").tablesorter({
    theme : "blue",
    sortForce: [[1,0]],
    sortList: [[1,0],[0,0]],
    headers: {
      0: { sorter: "inputs" },
      1: { sorter: "select-text" }
    },
    emptyTo: 'top',
    widgets: [ "group", "columns", "filter", "zebra" ],
    widgetOptions: {
      group_collapsible : true,
      group_collapsed   : true,
      group_count       : " ({num})",
      group_saveGroups  : false,

      group_formatter   : function(txt, col, table, c, wo, data) {
        return txt === "" ? "Unrouted" : txt;
      },
    },
});

```

**Comment by Mottie** [comment]
Hi @mhoffmann10!

When the ajax call completes, that's when the update needs to be triggered on the table. Try this change to the code:

```js
$.ajax({
  data: dataString,
  type: 'POST',
  url: '<?php echo base_url(); ?>admin/updatesort/'
}).done(function(data) {
  if (data) {
    // add the data to the table here?
    $('table.dispatchsort').trigger('update',[true]);
  }
});
```

I'm not sure where the content of the table is being updated, but if it is missing it should be done immediately before the update is triggered.

If the entire page is being updated, then you'll need to make sure that tablesorter is initialized on document end or move the initialization code to the bottom of the page (immediately before the `</body>` tag).

**Comment by mhoffmann10** [comment]
I put together a jsfiddle to demonstrate the issue I am having.

https://jsfiddle.net/mhoffmann10/99vtmkgm/

If you got under the UNROUTED group and select one of the options from the select menu or change one of the values in the sort column, the groups will all disappear.  They will reappear if you resort the list.  I cannot seem to figure out what I am doing that is misconfigured.

I have changed my update function on the live site to only execute after the ajax call is complete, but that did not seem to help this situation.  Thanks!

**Comment by Mottie** [comment]
Sorry for taking so long to respond!

I found the problem... because the `parser-input-select` is being used, it automatically updates the select value in the cache using the "updateCell" method. So when extra code is included to trigger an "update", it is removing all the group header rows.

I [updated the demo](https://jsfiddle.net/Mottie/99vtmkgm/2/) by commenting out the trigger update lines and it appears to be working as expected.

**Comment by mhoffmann10** [comment]
Wow, thank you so much.  I must have tried everything else to solve this.  I appreciate your time in solving this.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
