### ISSUE TITLE
Search and Select filter not working

### ISSUE THREAD

**Issue by tarifrudrapur** [Mottie/tablesorter#1440]
I am using tablesorter in salesforce lightning component.
The sorting is working perfect but i don't know why **Search** filter and **Select** filter is not working.

here is some log and codes

```
        $(targetTable).tablesorter({
                widthFixed: true,
                //delayInit: true,
                debug: true,
                widgets: ["filter"],
                widgetOptions : {
                    // filter_anyMatch replaced! Instead use the filter_external option
                    // Set to use a jQuery selector (or jQuery object) pointing to the
                    // external filter (column specific or any match)
                    filter_external : '.search',
                    // add a default type search to the first name column
                    filter_defaultFilter: { 1 : '~{query}' },
                    // include column filters
                    filter_columnFilters: true,
                    filter_placeholder: { search : 'Search...' },
                    filter_saveFilters : true,
                    filter_reset: '.reset',
                    filter_cssFilter : "custom-input-filter"
                },
                textExtraction: {
                    3: function(node, table, cellIndex) {
                        return $(node).find("span.extract-alias").text();
                    }
                },
                cssAsc: 'slds-is-sorted slds-is-sorted--asc',
                cssDesc: 'slds-is-sorted slds-is-sorted--desc',
                headers: {
                    0: { filter: false },
                    2: { filter: false },
                    5: { sorter: false, filter: false },
                    6: { sorter: false, filter: false },
                    7: { sorter: false, filter: false },
                    8: { sorter: false, filter: false },
                    9: { sorter: false, filter: false }
                }
            });
```

Some screenshots

> This is GUI 

![filter1](https://user-images.githubusercontent.com/15000719/28872947-f90d58e2-77a8-11e7-848e-2dac05c56d11.png)

> Log when init

![filter22](https://user-images.githubusercontent.com/15000719/28872946-f90d3984-77a8-11e7-8d80-ccedea2d3fab.png)

> Log when search something

![filter3](https://user-images.githubusercontent.com/15000719/28872945-f90998f6-77a8-11e7-903d-4e7d555ab246.png)

**Comment by Mottie** [comment]
Hi @tarifrudrapur!

Everything appears to be working... I set up [this demo](https://jsfiddle.net/Mottie/bbxxomhx/522/). It is properly applying a fuzzy search to the second column and the dropdown is working.

I don't see any data that would make a search for "A10" produce any results.

If you are still having issues, please modify the demo I shared to show the problem.

**Comment by tarifrudrapur** [comment]
Thanks for your response @Mottie 
Yes your demo is working properly. But in salesforce lightning component it is not working.
If that possible to get value of filter input so i can create my own jQuery search that must be work.

Help me to get these value when user input a text.
Like we are getting in debugger.
`Filter: Starting filter widget search (10) ["", "ABC", "", "", "", "", "", "", "", ""]`

**Comment by Mottie** [comment]
Use the [`$.tablesorter.getFilters` method](https://mottie.github.io/tablesorter/docs/#function-getfilters).

**Comment by tarifrudrapur** [comment]
Thanks @Mottie 
Now my search filter working using my custom jquery search function.
Here how.
```
var filters = $.tablesorter.getFilters($tableDom);
helper.customFilter(component, filters[1], 1)
```
As in position `filters[1], 1`  i have a search filter.
And in position `filters[3], 3` and `filters[4], 4` i have a select filter.
When i am selecting a value in select option. I am able to get its value in this `$.tablesorter.getFilters($tableDom)` function but option not get selected after choosing one from option.
Example.
I choose a option from dropdown select. I got a value in my function. But select filter automatically reset. There should be a my selected option.

May be this is a strange issue. But if we can handle select option manually so we can do somethings.
Please reply when you available.

**Comment by Mottie** [comment]
> I got a value in my function. But select filter automatically reset.

I'm not sure how that is happening. If you need to set the filters programmically, use [`$.tablesorter.setFilters` method](https://mottie.github.io/tablesorter/docs/#function-setfilters).

If that doesn't work, please share the code that interacts with the filters.
