### ISSUE TITLE
ColumnSelector

### ISSUE THREAD

**Issue by Mottie** [Mottie/tablesorter#1443]
## ColumnSelector + Grouping:

When hiding the first column, the grouping row is also removed - [demo](https://jsfiddle.net/Mottie/4ac5kr3o/63/) - reported in IRC.

## ColumnSelector

When hiding many columns, then clicking "auto", the columns are not properly readjusted. Found in the above demo, but it doesn't appear to be related to the grouping widget. Oddly, I cannot reproduce in the [main columnSelector demo](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html).

**Comment by Mottie** [comment]
Fixed in https://github.com/Mottie/tablesorter/commit/86e2b7c3555be36f1ac8cd4c28e3bf3657d8e238 and  https://github.com/Mottie/tablesorter/commit/6a663b5138a8ec4210d4c1976f3ae6947b20b3f0.

**Comment by KarlBaumann** [comment]
Thanks @Mottie :)

**Comment by Mottie** [comment]
This should be all fixed in v2.29.0!
