### ISSUE TITLE
New event handler resiazbleStopResize

### ISSUE THREAD

**Issue by asapostolov** [Mottie/tablesorter#1444]
Hey there!

I needed to add a new event handler in order to be able to sync and save column sizes on the server.

So I added this code at the end of `stopResize` event in Resizable widget:

`c.$table.triggerHandler('resiazbleStopResize');`

And I can bind to this event handler via:

```
$table.bind("resiazbleStopResize", function (e, table) {
    alert("resiazbleStopResize");
});
```

I wondered if this would be a desirable functionality for me to make a pull request for? It's really simple and needs a little bit of documentation.

**Comment by Mottie** [comment]
Hi @asapostolov!

That's fine! I can add it if you don't want to, but I would prefer to use `resizeComplete` instead of `resizeStopResize`... it makes more sense to me.

**Comment by Mottie** [comment]
Added in v2.29.0 - [see docs](https://mottie.github.io/tablesorter/docs/example-widget-resizable.html#events).
