### ISSUE TITLE
Column limit - Not showing 41st column

### ISSUE THREAD

**Issue by edrackus** [Mottie/tablesorter#1446]
[CBISProjectPortfolioEd.zip]
![screen shot of portion of right side of project page](https://user-images.githubusercontent.com/30511329/29234347-f9f833e8-7ebb-11e7-905c-e7c98b5acfba.jpg)(https://github.com/Mottie/tablesorter/files/1219231/CBISProjectPortfolioEd.zip)

I have a large table for displaying various project status indicators inside a SharePoint webpart that currently has 40 columns.  When I add the 41st column, it will not display.  If I switch the 40th and 41st columns, the new column displays.  I have validated the html.

As an aside, I also have sticky headers and can use a y-scrollbar to "anchor" inside a wrapper within a SharePoint web part.  Has anybody gotten sticky headers to work inside a SharePoint web part by using a SharePoint web part class or id to attach to?

**Comment by Mottie** [comment]
Hi @edrackus!

For the sticky headers, you need to set the dimensions of the wrapper before it'll make it scroll and get the sticky header to properly "stick" - [demo](https://jsfiddle.net/Mottie/f36416oy/45/).

There is no limit on the number of columns, so I'm not sure why it isn't working for you. The markup in the file you shared *appears* to be correct, but you should still check if the HTML is valid. Maybe you can modify the above demo to duplicate the problem to make it easier for me to troubleshoot.

**Comment by edrackus** [comment]
Rob,
I did verify the that the HTML is valid.  When I get a chance, I'll try to dump the contents of the list and hard code a table with 41 column entries to check your tool apart from SharePoint.
The sticky header works attaching to the wrapper.  I reset the height dynamically after the table loads.  It would be nice to get it to work by attaching to something inside a SharePoint web part and using the "top" of the web part as an anchor.  I tried everything I could think of with no success.  I know this is beyond the scope of your project.  The project owner is satisfied with my modified solution.
Ed Rackus 

    On Friday, August 11, 2017 6:22 PM, Rob Garrison <notifications@github.com> wrote:
 

 Hi @edrackus!For the sticky headers, you need to set the dimensions of the wrapper before it'll make it scroll and get the sticky header to properly "stick" - demo.There is no limit on the number of columns, so I'm not sure why it isn't working for you. The markup in the file you shared appears to be correct, but you should still check if the HTML is valid. Maybe you can modify the above demo to duplicate the problem to make it easier for me to troubleshoot.—

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by edrackus** [comment]
Rob,
Sorry for not getting back to you, but this turned out to be an error in correctly setting up the 41st column.  I caught it when I worked on a bigger monitor.
Ed Rackus 

    On Wednesday, September 27, 2017 9:28 PM, Rob Garrison <notifications@github.com> wrote:
 

 Closed #1446.—
