### ISSUE TITLE
BS4 beta

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1450]
From <https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v4.html>:
> NOTE!: Bootstrap v4.x is still in alpha development.

Not anymore, it's a beta now. BTW, did anything relevant change?

**Comment by Mottie** [comment]
Hi @Herst!

I don't know, I've been too busy to check.

**Comment by Herst** [comment]
I am experimentally trying to port a larger project, will take some time, but I will report back.

**Comment by Herst** [comment]
Ported the project and nothing looks broken but it does not look very nice why I will wait for a usable theme before going live with this. Tablesorter looks from what I can gather, at most the colors might not be exactly the same as used by default BS4 theme.

**Comment by Mottie** [comment]
I updated the Bootstrap v4 demo in the docs... what is it you don't like? Is it the sort arrows, or because I'm not using Font Awesome icons in the demo? I was tired when I made the v4 demo, so I didn't bother with "nice" icons.

**Comment by Herst** [comment]
Sorry, I should have clarified, I dislike the look of BS4 in general.
