### ISSUE TITLE
Change text for filter

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#1451]
Hello,

Sorry for my question but I'm looking for a way to change text for filter, I have : 

```html
<tr>
   <td data-?="my search and filter text">MY CURRENT TEXT_</td>
</tr>
``

What is the correct data or css to filter and search for other text

By advance thanks for your help ¨

Cheers

**Comment by ciadch** [comment]
Ok i found with data-text attribute... sorry for that

**Comment by ciadch** [comment]
Hi,

I reopen this case because I'm looking for a way to add text into filter with colspan td, for exemple : 
```html
<table>
   <thead><tr>
      <th>HEAD 1</th>
      <th>HEAD 2</th></tr></thead>
   <tbody><tr>
      <td colspan=2" data-text="MY TEXT">MY CONTENT</td></tr></tbody>
</table>
```

With this exmple, how can I "force" data-text to be fitred by first th ? 

Thanks for your help

**Comment by Mottie** [comment]
Hi @ciadch!

There are two issues with the markup ([demo](https://jsfiddle.net/bbxxomhx/611/)):

* Move the data-attribute to the `<th>` inside the `<thead>`.
* Use `data-value` unless the [`filter_defaultAttrib` option](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#filter-default-attrib) was modified to use `data-text`.

```html
<table>
  <thead>
    <tr>
      <th data-value="MY TEXT">HEAD 1</th>
      <th>HEAD 2</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td colspan="2">MY CONTENT</td>
    </tr>
    <tr>
      <td colspan="2">MY TEXT</td>
    </tr>
  </tbody>
</table>
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by ciadch** [comment]
Ho sorry @Mottie,

I was sure I answered you. My bad. But everything is OK now.

Many thanks !
