### ISSUE TITLE
Uncaught TypeError: Cannot read property 'attachTo' of undefined

### ISSUE THREAD

**Issue by robdaniel** [Mottie/tablesorter#1452]
I'm having an issue with using the columnSelector. My scripts are called in this order:

    <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
    <script src="~/js/tablesorter/jquery.tablesorter.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/tablesorter/jquery.tablesorter.widgets.js"></script>

and my js on my _Layout.cshtml is what you gave:

    $(function () {
            /*** Bootstrap popover demo ***/

            // initialize column selector using default settings
            // note: no container is defined!
            $(".bootstrap-popup").tablesorter({
                theme: 'blue',
                widgets: ['zebra', 'columnSelector', 'stickyHeaders'] // Also tried deleting 'zebra' and 'stickyHeaders
            });

            // call this function to copy the column selection code into the popover
            $.tablesorter.columnSelector.attachTo($('.bootstrap-popup'), '#popover-target');

            $('#popover')
              .popover({
                  placement: 'right',
                  html: true, // required if content has HTML
                  content: $('#popover-target')
              });
        });

I was getting a ".tablesorter is not a function" but I fixed it by reordering the scripts. I have the widgets folder in the same directory as the jquery.tablesorter.js file but is it somehow not accessing the columnSelector widget .js file correctly?

**Comment by Herst** [comment]
From <https://mottie.github.io/tablesorter/docs/>: 

> jquery.tablesorter.widgets.js (includes the jQuery UI theme, columns styling, resizable columns, filter, sticky header and save sort widgets).

No `columnSelector`.

**Comment by robdaniel** [comment]
So are you trying to say the problem is the widgets.js file or claiming the columnSelector is not a widget?

https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html

**Comment by Mottie** [comment]
@Herst is right... the columnSelector widget code is not being loaded. You'll need to include the file inside a `<script src="widget-columnSelector.js"></script>`

The plugin will report missing widget code in the console, but only if you have the `debug` option set to `true`... maybe I should have it always show a warning in this case?

**Comment by Mottie** [comment]
Yes

**Comment by robdaniel** [comment]
Success. Thanks! Side note: I'm new to this kind of licensing. If we decide to implement this in a commercial way, do I need to go about purchasing a license from you? I saw the licensing section of the readme but I'm not sure what to take from it haha

**Comment by Mottie** [comment]
Nope, the project is dual licensed (pick either one) by the original author.

* http://www.opensource.org/licenses/mit-license.php (MIT)
* http://www.gnu.org/licenses/gpl.html (GPLv2)

If I understand the lawyer talk, all you need to do is make sure that the license in the code stays in tact, or something like that.

**Comment by robdaniel** [comment]
Oh ok I get it now. Thanks!

**Comment by robdaniel** [comment]
Is there an area where questions can be asked that aren't necessarily "problems"? I have a question but don't want to clutter this post with unrelated questions.

**Comment by Mottie** [comment]
Here are links to IRC, Gitter and StackOverflow - https://github.com/Mottie/tablesorter#questions

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
