### ISSUE TITLE
ProcessAjaxOnInit Not Working On Page Load

### ISSUE THREAD

**Issue by DoctorWhite** [Mottie/tablesorter#1456]
I'm attempting to use the Ajax Plugin, and the processAjaxOnInit option isn't working. I have it set to true and the table is not loading, even though it is empty on load. These are my options:
```
$('.tablesorter').tablesorter({
    widthFixed: false,
    sortList: [[0,0]],
    headers: {
      7: {sorter: false },
      8: {sorter: false }
    },
    widgets: ['zebra', 'filter'],
    widgetOptions : {
      filter_external : '.search',
      filter_defaultFilter: { 1 : '~{query}' },
      filter_columnFilters: false,
      filter_reset: '.reset'
    }
  }).tablesorterPager({
    processAjaxOnInit: true,
    container: $('.pager'),
    output: '{page}/{filteredPages}',
    size: 100,
    pageReset: false,
    fixedHeight:false,
    ajaxUrl: 'get_properties?page={page}&{sortList:col}&{filterList:fcol}&size={size}',
    ajaxError: null,
    ajaxObject: {
      type: 'GET',
      dataType: 'json'
    },
    ajaxProcessing: function (data) {
      if (data && data.hasOwnProperty('rows')) {
        var indx, r, row, c, d = data.rows,
        total = data.total_rows,
        headers = data.headers,
        headerXref = headers.join(',').replace(/\s+/g,'').split(','),
        rows = [],
        len = d.length;
        for ( r=0; r < len; r++ ) {
          row = [];
          for ( c in d[r] ) {
            if (typeof(c) === "string") {
              indx = $.inArray( c, headerXref );
              if (indx >= 0) {
                row[indx] = d[r][c];
              }
            }
          }
          rows.push(row);
        }
        return [ total, rows, headers ];
      }
    }
  });
```

**Comment by Mottie** [comment]
Hi @DoctorWhite!

The default setting of `processAjaxOnInit` is `true`. The table should be populated on init after it processes the first ajax call. 

Please add a `debug: true` and see if there are any issues. Also check what the server is returning some data. And that the data is in the expected format for the `ajaxProcessing` function being used.

**Comment by DoctorWhite** [comment]
I know the server is returning data in the correct format because it works when I sort. However, the plugin is not sending any request. There is no request in the network tab when I monitor.

**Comment by Mottie** [comment]
Is that code wrapped in a document ready function? Or at the bottom of your page?

What does the debug log report?

**Comment by DoctorWhite** [comment]
The code is wrapped in a document ready function and it is at the bottom of the page.  The debug log has no errors, though it has two warnings saying the goto selector and size selector were not found. It basically says the table was indeed initialized, it built the headers, detected no parsers, builds a cache of 0 rows (since the table starts with an empty tbody), it applied my two widgets, then it initialized the pager, threw the warnings, and completed. It was bit long-winded, but I could paste the whole thing if you like.

**Comment by Mottie** [comment]
Hmm, oh, please make sure you're using the latest version of the plugin... including the pager. There was an issue in the past where nothing would be added to the table until the user sorted or filtered the table.

If that doesn't work, then please try to modify [this demo](http://jsfiddle.net/Mottie/9nfu2ja5/) to duplicate the issue.

**Comment by DoctorWhite** [comment]
It appears there was a difference between my pager file and the live version. I'm unsure why the change resulted in the table not loading, but I suspect it was assuming that the table was pre-populated at some point. Now it works.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
