### ISSUE TITLE
span attrtibute

### ISSUE THREAD

**Issue by KJThaDon** [Mottie/tablesorter#1457]
I cannot figure out how to sort a column that has spans in it...I have span classes inside some that I need to sort by a custom attribute, or any attribute at that...Can someone help me out please. Thank you.

**Comment by Mottie** [comment]
Hi @KJThaDon!

Please share an example of the HTML you're using and what you expect to happen when you sort - you can modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/)).

Also please elaborate on what you mean by spans... `<span>`, colspan or rowspan? What custom attribute?

**Comment by KJThaDon** [comment]
I have about five td's that output these values...

`<td>
<?php // TOTAL 5 MARKS
foreach($_33ext['feats'] as $val)
if (($val['name'] == '5mr') && ($val['value'] == '1' || $val['value'] == '2' || $val['value'] == '3' || $val['value'] == '4' || $val['value'] == '5' || $val['value'] == '6' || $val['value'] == '7' || $val['value'] == '8' || $val['value'] == '9' || $val['value'] == '10')) {
echo str_repeat('<span data-value="'.$val['value'].'" class="mark fivemr"></span>', $val['value']);
}
?>
</td>`


```
.mark:before {
	content: '\25A0';
	font-size: 11px;
}
.fivemr:before {
	color: #DCDC00;
```

The <span> tags inside the td, will output ■ ■ ■ according to the value retrieved...I would like to sort the columns by the square count. I tried adding `data-value="'.$val['value'].'"` which does output the correct number into the value="" output, but does not change the effect of sorting.

**Comment by Mottie** [comment]
The `data-value` needs to be on the `<td>`. If you can't get it to work, then please modify the demo.

**Comment by KJThaDon** [comment]
I cannot put it on the `<td>` because the value isn't generated until after the td is created, and it is inside the td, therefore the $val['value'] variable won't display...

Thank you

**Comment by Mottie** [comment]
Then try the [`textExtraction` callback](https://mottie.github.io/tablesorter/docs/#textextraction).... inside you can count the number of spans. Something like this:

```js
textExtraction : {
  // Use column zero-based index or jQuery selector string
  // to target the column
  0: function(node, table, cellIndex) {
    return $(node).find('.mark').length;
  }
}
```

**Comment by KJThaDon** [comment]
Getting an error with that function.

"Uncaught SyntaxError: Unexpected token :"

**Comment by Mottie** [comment]
Updated my last comment with the full code... maybe there was an extra colon in the code?

**Comment by Mottie** [comment]
Demo - https://jsfiddle.net/bbxxomhx/620/

**Comment by KJThaDon** [comment]
Thank you sir! Looks like it's working. Can you add multiple columns with commas? I have 6 columns that use this.

**Comment by Mottie** [comment]
The `textExtraction` method will work with a jQuery selector as well as a zero-based index.... it's all in the documentation.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
