### ISSUE TITLE
Sort not working when custom selectorHeaders 

### ISSUE THREAD

**Issue by brynmrk** [Mottie/tablesorter#1459]
Hi, first thanks for this wonderful plugin. I've got a problem about sorting when I set my own selectorHeaders. Can't find any other issues related to this.

Here is my code for initialization,
`
count_header_index = $("#summary_count_header").index()
  $(".tablesorter").tablesorter({sortList: [[ count_header_index, 1 ]], selectorHeaders: "> thead th span, > thead td span"})
`

**Comment by Mottie** [comment]
Hi @brynmrk!

There does appear to be an error. I'll need spend some time to find the problem. Thanks for reporting it!

**Comment by Mottie** [comment]
This has been fixed in the master branch... I still have a little work to do before the next release.

Here is a demo of it working - http://jsfiddle.net/856bzzeL/1223/

Note that the [`selectorSort` option](https://mottie.github.io/tablesorter/docs/#selectorsort) also needs to target the spans.

**Comment by brynmrk** [comment]
Hi @Mottie, just bumping on this since I just realized that the icon in the span doesn't change, even on your jsfiddle demo.

**Comment by Mottie** [comment]
Wow, that's odd. I could have sworn it was working. I wonder what happened.

**Comment by Mottie** [comment]
Ok, it should be working now (master branch update)... try the same demo above.

**Comment by brynmrk** [comment]
Thanks for the fast reply, I just checked the demo and I think the whole tablesorter is not working. Here is the screenshot. I've tried to refresh many times, still like this.

![screen shot 2017-10-19 at 07 51 35](https://user-images.githubusercontent.com/19178579/31747918-5dcbeb6e-b4a2-11e7-91ac-29546b7843c9.png)

**Comment by Mottie** [comment]
I just tested it again and it's working for me. Are you seeing any errors in the console? Check the demo in a different browser.

**Comment by brynmrk** [comment]
Forgot to check the console, yes it's showing error on the css part since it's not using https. It's working now, Thanks (Y).

**Comment by Mottie** [comment]
Fixed in v2.29.2.
