### ISSUE TITLE
Multisort Columns is occurring, but in wrong order.

### ISSUE THREAD

**Issue by DoctorWhite** [Mottie/tablesorter#1461]
I am sorting two columns (one with a custom parser first, that just gets the text from the val() of an input). The second column is normal text. The columns are sorted in reverse order to what I specify. There are a lot of blanks in the custom parsed column, but using the emptyTo variable didn't change things. It appears that the column I specified second is the one being sorted first. My sortList is [[6,0],[3,0]].
```
$('.tablesorter').tablesorter({
    widthFixed: false,
    sortList: [[6,0],[3,0]],
    emptyTo: 'emptyMin',
    headers: {
      7: {sorter: false },
      8: {sorter: false }
    },
    widgets: ['zebra', 'filter'],
    widgetOptions : {
      filter_external : '.search',
      filter_defaultFilter: { 1 : '~{query}' },
      filter_columnFilters: false,
      filter_reset: '.reset',
      filter_searchDelay: 1000
    }
  })

**Comment by Mottie** [comment]
Hi @DoctorWhite!

Are you using the ["inputs" parser](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js#L19-L30) from the [parser-input-select.js](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) file? There isn't a built-in input parser.

I modified the group widget [demo](https://jsfiddle.net/4ac5kr3o/66/) by adding a `sortList` and it appears to be working properly for me.

**Comment by DoctorWhite** [comment]
Whoops, this was the page that I had using ajax sorting. So that must be a back end query thing.
