### ISSUE TITLE
Table sorter not working even though all code is there

### ISSUE THREAD

**Issue by tjferry14** [Mottie/tablesorter#1464]
I've made a fiddle to demonstrate, hopefully someone can help me out-or notice something that I haven't. To me, it looks to be all the correct code. 

https://jsfiddle.net/auoqwp8p/5/

**Comment by Mottie** [comment]
Hi @tjferry14!

The call to initialize tablesorter needs to be inside the sheetrock callback ([demo](https://jsfiddle.net/Mottie/auoqwp8p/6/)):

```js
$('#audio-backend').sheetrock({
  url: mySpreadsheet,
  query: sql,
  rowTemplate: bandsTemplate,
  callback: function(error, options, response) {
    if (!error) {
      if ($('#audio-backend tr').length == 1) {
        $('#audio-backend').append("<h3>No results.</h3>")
      }
    } else {
      $('#audio-backend').append('<h3>Error.</h3>');
    }
    $("#audio-backend").tablesorter();
  }
});
```

**Comment by tjferry14** [comment]
Thank you!
