### ISSUE TITLE
Pager doesn't show rows after changing sort order

### ISSUE THREAD

**Issue by pevgeniev** [Mottie/tablesorter#1466]
There is an issue with the pager when sorting twice on the same column. First it hides the rows, that are not in the current page, but after the reverse sort it doesn't show them.
The error is in renderTable when using pager_removeRows = true:

`if ( !wo.pager_removeRows ) {
     tsp.hideRows( c );
} else{
	ts.clearTableBody( table );
 ....
`
The code in else adds the necessary number of rows, but since they already have display='none' set to them from the previous sort and there is no code to show them, they end up being hidden.
My initial fix was to call tsp.hideRows(c) befor the closing 'else' like:
`ts.processTbody( table, $tb, false );
 tsp.hideRows( c );
}`
but since I don't know well enough this plugin, I don't know if that would be optimal and correct solution.

**Comment by Mottie** [comment]
Hi @pevgeniev!

I set up [this demo](https://jsfiddle.net/Mottie/Lr6p93xu/22/) using the pager widget with `pager_removeRows` set to `true` and I'm not seeing the problem. Would you please modify the demo to duplicate the problem you're seeing.

**Comment by pevgeniev** [comment]
Hi,
I've updated the demo.
Apparently the bug happens when one uses the widget-build-table.js plugin

Regards

**Comment by pevgeniev** [comment]
Sorry, here it is:
https://jsfiddle.net/Lr6p93xu/26/

**Comment by Mottie** [comment]
Sorry, busy day... I'll look at this tomorrow.

**Comment by Mottie** [comment]
Sorry for the long delay! 😿This *should* be fixed in v2.30.0!
