### ISSUE TITLE
Update input tag nested in td of the already appended rows

### ISSUE THREAD

**Issue by hatimhaidry** [Mottie/tablesorter#1473]
Hi Mottie,

I have a table in which the rows contains 4 nested input element in 4 consecutive td. 

In first iteration, 3 out of 4 input element have given value and appended in table. And the values are shown in html table.

Now in 2nd iteration, the value of 4th input element has been calculated and need to be updated in table. I am updating the value in 4th input element, however the table is not showing the same.

This issue is occurring when i am using 'scroller' plugin. But prior to that it was working fine.
 
May be the TableSorter cache has not been updated yet. Please help on how to do the same. 

Thanks & Regards
Hatim

**Comment by Mottie** [comment]
Hi @hatimhaidry!

What code are you using to parse the input values? And what code is used to update the cache after the input value has changed?

There are several parsers in the [`parser-input-selector.js` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) that will take care of the inputs for you. They *should* still work with the scroller widget; but it would be easier if you could provide a demo or share the HTML and JS being used.

**Comment by hatimhaidry** [comment]
Hi Mottie,

I am simply updating the input element nested in td with document.getElementById("txtSrNo").value = "43". And after that I called $("#TableID").trigger("update", true);. It works correctly with widgets: ['zebra', 'resizable', 'stickyHeaders', 'filter'].

However if I add widget scroller as widgets: ['zebra', 'resizable', 'stickyHeaders', 'filter', 'scroller']. It does not update the table. This issue is only occurring when i am adding 'scroller' plugin. But prior to that it was working fine.

Please suggest

Thanks & Regards
Hatim

**Comment by Mottie** [comment]
Instead of updating the entire table (using [`update`](https://mottie.github.io/tablesorter/docs/#update)), update the cached value of that cell using [`updateCell`](https://mottie.github.io/tablesorter/docs/#updatecell).

**Comment by hatimhaidry** [comment]
I tried updateCell as well, however not working. The "update" is working fine with ['zebra', 'resizable', 'stickyHeaders', 'filter'] plugins.

But not working with ['zebra', 'resizable', 'stickyHeaders', 'filter', 'scroller'] plugins. It means that 'the 'scroller' plugin is having issue in updating the cache.

Please help.

Also, for issue number 1472, we require to implement table in such a way that the column will be resizable as well as first certain columns need to be fixed during horizontal scrolling including Sticky Headers, Filters and Zebra features.

Need your support in both the issues.

Thanks & Regards
Hatim

**Comment by Mottie** [comment]
The stickyHeaders widget isn't compatible with the scroller widget... the scroller widget adds two to three additional copies of the table to create the scroll effect. When you freeze a column, it adds 3 more copies. On top of that, the stickyHeaders widget adds a copy of the header. It gets to be a big mess trying to keep everything in alignment and positioned properly. I fear this issue won't *soon* be resolved.

I could help you with implementing the updateCell code, but it would be easier for me to modify the already written code than for me to write it from scratch and guess at the implementation.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by hatimhaidry** [comment]
As you have said in issue number 1473 that the Scroller widget has lot of incompatibilities with other widgets and suggested to check for datatables. Hence I am looking for datatables.

However, the issue is still there in using tablesorter plugin. And I would appreciate and need to use tablesorter in our application if this issue resolve. 

Hence requesting you to please resolve scroller widget incompatibilities with other widgets and then close this issue

Thanks
Hatim

**Comment by Mottie** [comment]
Oh oops, I didn't mean to close this issue.

**Comment by Mottie** [comment]
The scroller is currently incompatible with the stickyheaders widget. I've centralized all of the scroller widget incompatibilities into one issue (#1487). Please follow any progress there.
