### ISSUE TITLE
Print table without table border after first page in Firefox

### ISSUE THREAD

**Issue by Alchaves** [Mottie/tablesorter#1475]
Hi!

I'm having issues with the print widget. It only aplies the borders on the first page, all the ohters pages have no borders at all...

![print_no_borders_firefox](https://user-images.githubusercontent.com/6002053/32658234-f2d64d7e-c610-11e7-8db4-29be5ab0f6b6.jpg)

In Chrome, Edge and IE 11 the print it's fine. I only see this occuring in Firefox 56.0.2.

**Comment by Mottie** [comment]
Hi @Alchaves!

The print widget applies the same stylesheet to the entire table within the popup. If the borders aren't printing, I would assume it's a problem with the browser. Sorry I can't be of more help.

**Comment by Alchaves** [comment]
Hi @Mottie!

Apparently, with the new version of Firefox (Quantum 57.0) the problem it's solved...
Thanks anyway for your help.
