### ISSUE TITLE
Are nested tables with the scroller widget

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1476]
I am trying to have a table with expandable rows that contains other tables with scrollers. It works fine when initialize the sub tables without the scroller widget. When I use the scroller widget, it gets the child table a "tablesorter-scroller-footer" even though it doesn't have a footer and all 3 of the "tablesorter-scroller-*" div's have a width of 0 for their individual styles. If I uncheck the "width: 0px" box in the dev tools, it will show 2-3 different tables. Just wondering if anyone else has come across this

**Comment by Mottie** [comment]
Hi @MoMack20!

The scroller widget creates duplicates of the original table to create the scrolling effect. If you want to open an expandable row, make sure to add a unique id data-attribute to the row since an actual ID must be unique.

Try something like this:

```js
var $wrapper = $('.table-wrapper');
$wrapper.on('click', 'tr.collapsible', function(){
  var id = $(this).data('row-id');
  $wrapper.find('[data-row-id="' + id + '"]').toggleClass('expanded');
});
```
