### ISSUE TITLE
Filter issue, question about change in 2.21

### ISSUE THREAD

**Issue by grimmySwe** [Mottie/tablesorter#1477]
I had an old Tablesorter (2.15.10) that I updated to the state of the art (2.29.0) to get some new functionality. In this update my filters stopped working. No matter what I write in the filters all rows are still visible. I tracked this down and it seems that in 2.21 there was a change from using toggle:

```
$rows.eq(rowIndex).toggle(showRow).toggleClass(wo.filter_filteredRow, !showRow);
```
to using display = 'none' and adding a css rule for .filtered class.
```
$row.toggleClass( wo.filter_filteredRow, !showRow )[0].display = showRow ? '' : 'none';
```
I have solved it by updating my css, but I am a little curious about why you remove the toggle, and that the `.display = showRow ? '': 'none';` doesn't seem to do anything for me.

**Comment by TheSin-** [comment]
IIRC he did it to stay compact with jQuery that was removing the show/hide functions, and using css classes was the replacement.

**Comment by grimmySwe** [comment]
But toggle is still part of jQuery or? and for me the `[0]display = showRow ? '' : 'none';` doesnt seem to matter.

**Comment by TheSin-** [comment]
I hav eno idea I know it was a big discussion, they may have reverted their idea, this was 3.x pre release IIRC.  Either way using the filtered class and making sure you have a .filtered in your css for the desired behaviour is how it works now.  This allows other options, some might want to do a strike threw for example, others might want an animation to fade out. etc etc. This change leaves more options to the developer and less code and exceptions in the TS base.

**Comment by Herst** [comment]
It might also be worth noting that checking whether something has a class or not is much cheaper than checking whether it's `:visible` so in general toggling visibility using classes is the way to go (if possible).

**Comment by grimmySwe** [comment]
Regarding the css class I have nothing to add. The part I am curios if it wouldn't be clearer to have:
```
$row.toggleClass( wo.filter_filteredRow, !showRow );
```
As I read the code, I thought the display was actually doing something.

**Comment by Mottie** [comment]
I'm still out of town, so I'm answering this from memory... toggleClass was dropped to maintain compatibility with jQuery v1.2.6.

**Comment by grimmySwe** [comment]
And with toggleClass you mean toggle or?

**Comment by Mottie** [comment]
I mean the [`toggleClass` method](http://api.jquery.com/toggleClass/) added by jQuery. The `state` parameter wasn't added until v1.3.
