### ISSUE TITLE
How to update the table when I add more columns

### ISSUE THREAD

**Issue by wasabiiii** [Mottie/tablesorter#1479]
Hi,Mottie
I have a table with 18 columns,I want to add more 10 columns(both thead and tbody) when I click a button.
But when I append these more columns to thead and tbody,the columns which are new added can't sort.

I tried to use：

```js
$("#bond_table").trigger("destroy", [
  false,
  function() {
    // reinitialize tablesorter
    $("#bond_table").tablesorter();
  }
]);
```
Also I tried：

```js
$("#bond_table").trigger("updateAll");
```

But all they didn't work, which console the error:
**Invalid or incorrect number of columns in the THEAD; expected 18, but found 28 columns**

So how to update the table when I add more columns?

Thank you very much!!

**Comment by Mottie** [comment]
Hi @wasabiiii!

Would you please modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to duplicate this issue. It'd help me to see how the columns are being added.

**Comment by wasabiiii** [comment]
Hi @Mottie ，

I just find the cause of the problem is that I use a plugin named "[StickyTableHeaders](https://github.com/jmosbech/StickyTableHeaders)".When I remove this plugin,the error disappear.

Then I use your widget stickyHeaders，it works!!

Thanks a lot for your reply!!

**Comment by Mottie** [comment]
Awesome 😸

**Comment by Pikamander2** [comment]
For people getting here from Google, it looks like this issue can also occur if your colspan values are incorrect.

For example, I had a table with 10 columns, and one of the cells in the table spanned 10 columns. I reduced the number of columns down to 9, but forgot to change the colspan attribute, so the `checkColumnCount` function in jquery.tablesorter.min.js was getting confused.
