### ISSUE TITLE
Integration of tablesorter in puppetboard: problem with sorting IP addresses

### ISSUE THREAD

**Issue by emlun007** [Mottie/tablesorter#1480]
Hello

I have been trying to integrate tablesorter in puppetboard (https://github.com/voxpupuli/puppetboard) to sort my IPv4 addresses that are sorted alphabetically. I have included the plugins in the <head> and started tablesorter on my table:

html code:

```
      <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.0/js/jquery.tablesorter.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/jquery.tablesorter/2.29.0/js/parsers/parser-network.min.js"></script>
```

js code:

```
      $(document).ready(function() { 
           $('#inventory_table').tablesorter();
 }); 

```

But the IPv4 addresses are still sorted alphabateically. Am I missing something?

**Comment by Mottie** [comment]
Hi @emlun007!

The `ipv4Address` (a.k.a. `ipAddress`) parser may not be auto-detecting the address. Please use the [header option](https://mottie.github.io/tablesorter/docs/example-parsers-ip-address.html) or add a `sorter-ipv4Address` class name to the column header cell.

If that doesn't help, please modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to show the issue.

**Comment by emlun007** [comment]
If I get it correctly, I need to add:

```
      $(document).ready(function() 
        { 
           $(".tablesorter").tablesorter({
     sortList: [[0,0],[1,0]],
     headers: {
      1: { sorter: 'MAC' },
//      2: { sorter: 'ipAddress' }, this parser is auto-detected
      3: { sorter: 'ipv6Address' }
    }
   
      });

 });
```
I tried to uncomment "2: { sorter: 'ipAddress' }, this parser is auto-detected" but then the whole page does not work

**Comment by Mottie** [comment]
The `headers` option needs to target the column's zero-based index. So the code should look something like this if the IPv4 address is in the 3rd column:

```js
$(function() {
  $(".tablesorter").tablesorter({
    sortList: [[0,0], [1,0]],
    headers: {
      2: { sorter: 'ipAddress' }
    }
  });
});
```

If you're still having trouble, please modify the demo with your HTML and I can see where the problem might be. Use similar dummy data if you have security concerns.

**Comment by emlun007** [comment]
I have tried to use your demo, and it works perfectly but then when I use my own javascript it does not sort:
https://jsfiddle.net/vz99z1v6/
What could be wrong with my code?

**Comment by Mottie** [comment]
It looks like code for both DataTables and tablesorter exist. Things that were preventing it from working include some of the following:

* The dropdown function (not jQuery UI?) doesn't exist so it's causing a javascript error and stopping the code from executing. Press <kbd>F12</kbd> and look in the console for these errors.
* Other code like the script loader and the non-existent DataTables plugin may also stop the javascript execution on that page.
* The tablesorter selector (`.tablesorter`) doesn't exist on the page.
* The External resources section of the jsFiddle demo was not loading the `parser-network.js` file.
* The IP address column had the parser set to "MAC".

I updated the demo: https://jsfiddle.net/Mottie/vz99z1v6/3/

* The tablesorter selector was changed to `.table.sortable`.
* All DataTable and dropdown code was removed.
* Removed the nested `$(document).ready(function(){ /*...*/ });` function... it can be rewritten as `$(function(){ /*...*/ });`
* Loaded the network parser file.
* Set the correct parser in the `headers` section.

```js
$(function() {

  $(".table.sortable").tablesorter({
    sortList: [[0, 0], [1, 0]],
    headers: {
      1: { sorter: 'ipAddress' }
    }
  });

});
```

**Comment by emlun007** [comment]
When I removed all DataTable and dropdown code, my page could not load any data:

![no_data_avilibale on page](https://user-images.githubusercontent.com/32731446/33309942-412dfed2-d420-11e7-95a0-684390944ac1.png)

I have tried to load my Ajax data with DataTables:

```
  var table = $('#{{ table_html_id }}').DataTable({
    // Permit flow auto-readjust (responsive)
//    "autoWidth": true,
    // Activate "processing" message
//    "processing": true,
    // Activate Ajax mode
    "serverSide": false,
    // Responsive
    "responsive": true,
    // Defer rendering out of screen lines (JIT)
    "deferRender": true,
    // Data loading URL
    "ajax": "{{ ajax_url }}",
    // Paging options
      "lengthMenu": {{ length_selector }},
    "pageLength": {{ default_length }},
    // Search as regex (does not apply if serverSide)
//    "search": {"regex": true},
    // Default sort
//    "order": [[ 0, "desc" ]],
    // Custom options
    {% if extra_options %}{% call extra_options() %}Callback to parent defined options{% endcall %}{% endif %}
  });
```
And then apply tablesorter:

```
$(function() {
  $(".table.sortable").tablesorter({
    sortList: [[0, 0], [1, 0]],
    headers: {
      1: { sorter: "ipAddress" }
    }
  });
});
```
But it is still sorting alphabetically. Do I need special options or widgets to sort Ajax data? No matter what I do with the table, it is always sorting alphabetically.

**Comment by Mottie** [comment]
Don't use DataTables *and* tablesorter together.

You can load the data using [tablesorter's build widget](https://mottie.github.io/tablesorter/docs/example-widget-build-table.html#setup__object_json_file_via_ajax).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
