### ISSUE TITLE
In a sticky header, the class of the header cell icon is not updated after sorting

### ISSUE THREAD

**Issue by aureplop** [Mottie/tablesorter#1483]
Hi!

Using the v2.29.0, I think I found a bug in the `stickyHeader` widget. In a sticky header, it seems that the class of the header cell icon is not updated after sorting with the values of `cssIconAsc` and `cssIconDesc`. The css class of these icons is stuck at the value of `cssIcon`.

Here is a demo: https://jsfiddle.net/ebocsju7/2/

**Comment by Mottie** [comment]
Hi @aureplop!

Thanks for reporting this problem, I'll get it fixed in the master branch shortly.
