### ISSUE TITLE
IPv4 & IPv6 address parsers example could be clarified

### ISSUE THREAD

**Issue by grimmySwe** [Mottie/tablesorter#1484]
In the example page:
https://mottie.github.io/tablesorter/docs/example-parsers-ip-address.html

there is a comment
```
<!-- load ipv6 parser -->
<script src="../js/parsers/parser-network.js"></script>
```

For me that comment indicates that only the ipv6 needs the parser-network.js, but doesn't it contain all the network related parsers? So maybe change the comment to "load mac, ipv4 and ipv6 parsers"

**Comment by Mottie** [comment]
Hi @grimmySwe!

Yes, good idea! I'll fix it in the master and it'll be available with the next release.
