### ISSUE TITLE
Resizable handle getting added to last visible column if remaining columns are hidden

### ISSUE THREAD

**Issue by praveenpillai** [Mottie/tablesorter#1485]
I am using v.2.28.11 of tablesorter.

Issue - 
If the last column (or last few columns) is hidden by default, then resizable handle is getting added to the last visible column even if "resizable_addLastColumn" is set to false.

Issue in line no. 2803 of jquery.tablesorter.widgets.js
`if ( !$header.is(':visible')) {
           $this.hide();
}`

Fix:
`if ( !$header.is(':visible') || (!wo.resizable_addLastColumn && (c.$table.find('th:gt('+column+'):visible').length==0))) {
       $this.hide();
} `

Please review.

**Comment by Mottie** [comment]
Hi @praveenpillai!

Thanks for reporting this issue and sharing a fix. I've updated the `widget-resizable.js` file, but not the `jquery.tablesorter.widgets.js` file, yet. I have some code cleaning and other minor work to do before the next release... hopefully I'll get it done this weekend.

**Comment by Mottie** [comment]
Fixed in v2.29.2.
