### ISSUE TITLE
Send actual page size with ajax

### ISSUE THREAD

**Issue by SangSuantak** [Mottie/tablesorter#1488]
Related to #1366

What should i do if i want to send page `size` with actual values rather than `all`? I don't know if this matters but this `size` value will come from a configuration/variable rather than the select option (`.pagesize`).

Also, what's the point of the `size` option in `tablesorterPager` default options? I changed this value to `2` to display 2 rows per page but to no effect. It still sends `all` with my `ajax` requests.

Using:
 * `jQuery`: `1.10.2`
 * `jquery.tablesorter.combined.js`: `2.29.2`
 * `jquery.tablesorter.pager.min.js`: `2.28.8`

```
self.tblResult.tablesorter({
  widthFixed: true,
  sortLocaleCompare: true,
  sortList: [
    [5, 0]
  ],
  widgets: ['filter'],
  widgetOptions: {
    filter_serversideFiltering: true,
    filter_columnFilters: false,
    filter_saveFilters: false
  },
  textExtraction: {
    5: function(node, table, cellIndex) {
      return $(node).find('.sortBy').text();
    }
  }
}).tablesorterPager({
  container: self.pager,
  ajaxUrl: self.searchURL + '?PageNo={page+1}&PageSize={size}&SortBy={sortBy}&SortDirection={sortDirection}',

  customAjaxUrl: function(table, url) {
		//Custom ajax logic
  },
  ajaxError: null,
  ajaxObject: {
    type: 'GET', // default setting
    dataType: 'json',
    cache: false
  },

  ajaxProcessing: function(data) {
    if (data && data.hasOwnProperty('rows')) {
      if (data.rows !== '') {
        self.PostSearchProcessing(true, false);
        return [data.total_rows, $(data.rows)];
      } else {
        self.PostSearchProcessing(false, false);
        return [];
      }
    } else {
      self.PostSearchProcessing(false, true);
    }
  },

  processAjaxOnInit: true,
  output: '{startRow} to {endRow} ({totalRows})',
  updateArrows: true,
  page: 0,
  size: 10, //What's the point of this value?
  savePages: true,
  storageKey: 'tablesorter-pager',
  pageReset: 0,
  fixedHeight: false,
  removeRows: false,
  countChildRows: false,
  cssNext: '.next', // next page arrow
  cssPrev: '.prev', // previous page arrow
  cssFirst: '.first', // go to first page arrow
  cssLast: '.last', // go to last page arrow

  cssPageDisplay: '.pagedisplay',
  cssPageSize: '.pagesize',

  cssDisabled: 'disabled', // Note there is no period "." in front of this class name
  cssErrorRow: 'tablesorter-errorRow' // error information row                    
});

**Comment by Mottie** [comment]
Hi @SangSuantak!

The "all" size setting is for convenience. Use an exact number if desired; but if the user can add rows, you'll need to make sure to update the page size locally.

The pager `size` setting is for the *initial* page size setting. Once the user changes it, the value is saved to local storage and overrides the initial setting. To disable this, set the [`savePages` option](https://mottie.github.io/tablesorter/docs/#save-pages) to `false`.

**Comment by SangSuantak** [comment]
Thanks @Mottie , that works like a charm.

Closing the thread since it's solved now.
