### ISSUE TITLE
Filtering using a natural sort

### ISSUE THREAD

**Issue by bogal** [Mottie/tablesorter#1490]
In my app i have a column that can have digits 1-10 (including decimals), or the string 'All'. I am able to sort these columns with the following code:

` 
 $("table").tablesorter({
	  textSorter: {
	      1: function(a, b) {
	        x = parseFloat(a);
	        y = parseFloat(b);
	        return x === 0 && y === 0 ?
	          b.length - a.length :
	          $.tablesorter.sortNatural(a, b);
	      }
	  },
});
`

... i was wondering if the same can be applied to filtering? I am using the filter widget and whilst it works as it should, would like the filtering to always include rows with 'All' in the results? So when the dropdown is populated with the values from the table, say the user selects 3, all rows containing 3 and All are filtered. This should only happen on this column, other columns that are filterable(?) should not have this behaviour.

**Comment by Mottie** [comment]
Hi @bogal!

I'm not exactly sure what you mean.

If you want rows with "All" to always show, then try the following code ([demo](https://jsfiddle.net/Mottie/bbxxomhx/771/)):

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'filter'],
    widgetOptions: {
      filter_defaultFilter: {
      	// "all" will always show
        1: '{q}|all'
      }
    }
  });
});
```

**Comment by bogal** [comment]
Again, thanks for the quick reply. Your interpretation of the issue is spot on, and although the fiddle shows exactly what i am looking to achieve, it isn't working on my site. On mine (i should have stated), i am not using an input to filter the results, but the select (dropdown) box - that is the only difference between them.

**Comment by Mottie** [comment]
What I think you need then is to add the following classes to the header ([demo](https://jsfiddle.net/Mottie/z3fh8woo/) & [ref](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes)):

```html
<th class="filter-select filter-match">Numeric</th>
```

**Comment by bogal** [comment]
Works perfectly. Thanks for taking the time to help, much appreciated :)
