### ISSUE TITLE
What's the proper way to resort a table after changed its cells?

### ISSUE THREAD

**Issue by ProgrammingLife** [Mottie/tablesorter#1491]
I change cells in a big table so I should use resort = false:

`$( ".table" ).trigger( "updateCell", [ someCell, false ] );`

How to resort it manually saving a previous sort order of a previously chosen cell after I've done all the changes in a table?

**Comment by Mottie** [comment]
Hi @ProgrammingLife!

If you're updating a single cell, then change the `false` to `true` within the "updateCell" trigger ([ref](https://mottie.github.io/tablesorter/docs/#updatecell))

```js
// $( "table" ).trigger( "updateCell", [ cell, resort, callback ] );
$( ".table" ).trigger( "updateCell", [ someCell, true ] );
```

If you've updated more than one cell, then either change the resort flag to `true` in the last update, or trigger a new `sorton` ([ref](https://mottie.github.io/tablesorter/docs/#sorton)):

```js
var $table = $( ".table" );
var config = $table[0].config;
$table.trigger( "sorton", [ config.sortList ] );
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
