### ISSUE TITLE
ipv6 Sorting Issues

### ISSUE THREAD

**Issue by shiggins8** [Mottie/tablesorter#1494]
Hello, I have an issue where the ipv6 sorter is not working as expected. here is the list of ip addresses so that you can verify that it is not working correctly: 

- fd33:2222::101
- fd33:2222::102
- fd33:1111::103
- fd33:1111::201
- fd33:1111::203
- fd33:1111::103
- fd33:1111::101
- fd33:1111::102

I have inspected the cache and see that each address is assigned a long decimal number that, in theory, should be correct, however the sorting on my site is incorrect. Any thoughts or reasons why these particular addresses would not sort properly?

**Comment by Mottie** [comment]
Hi @shiggins8!

Oh! I guess I forgot to consider the [`Number.MAX_SAFE_INTEGER`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MAX_SAFE_INTEGER) when converting the ipv6 into a numerical value.

I'll get this problem fixed shortly.

**Comment by Mottie** [comment]
This has been fixed in v2.29.3 - [demo](https://jsfiddle.net/Mottie/bbxxomhx/780/)

**Comment by shiggins8** [comment]
Thank you very much, I appreciate your rapid response and all the great work on the plug in!
