### ISSUE TITLE
How to set default sort, reset filter, and reset to first page with postback once?

### ISSUE THREAD

**Issue by phamngocphu** [Mottie/tablesorter#1496]
Hi Mottie,

I'm using tablesorter() and tablesorterPager() with custom ajax for my table.
My table have filtering, sorting on sticky table and a button to refresh table to first page and with my default sort and clear filter text.
I configed a default sort with sortList = [ [1, 0], [2, 0] ]
In my steps:
-1: input some filter text. A postback to server to get data with this filter text.
-2: click on column to change sort. Another postback to server to get and sort data with filter text (in step 1)
-3: hit refresh button. In this button event, I use 3 triggers: 'filterReset', 'sorton' and 'pagerUpdate' and there are 3 postback to server

So, how to do 3 task with only one postback to server in my case?

Thank you,

**Comment by Mottie** [comment]
Hi @phamngocphu!

To reset the filters without postback, use the [`setFilters` method](https://mottie.github.io/tablesorter/docs/#function-setfilters).

Update the sort by modifying the [`sortList` option](https://mottie.github.io/tablesorter/docs/#sortlist).

Then use the [`pagerUpdate` method](https://mottie.github.io/tablesorter/docs/#pagerupdate).

```js
var $table = $('#my-table');
$.tablesorter.setFilters($table, [], false);
$table[0].config.options.sortList = [[1, 0], [2, 0]];
table.trigger('pagerUpdate');
```

**Comment by phamngocphu** [comment]
I have tried your code. But I could not find options attribute in $table[0].config, just sortList attribute in $table[0].config

Some cases with your code:
-1: Only click sort another column, then hit refresh button. It postback once but not reset sort arrow on UI as my default sort
-2: Only input a letter "a" to filter text on a column, the hit refresh button. It resets filter text success but still postback twice. And if I try these steps (input letter "a" on this column and hit refresh button) again about 3 times, my table does not postback at inputting letter "a" step.
-3: input a letter "a" to filter text on a column, then click sort on this column, then hit refresh button, then input letter "a" to filter text on this column a gain, no postback occur.

Please help my review them.
Thank you

**Comment by Mottie** [comment]
> I could not find options attribute in $table[0].config

Oops! That should be `$table[0].config.sortList`, I was typing in a hurry

As for the other issues, please share the code you're using.

**Comment by phamngocphu** [comment]
$.tablesorter.setFilters($table, [], false);
This code may be reset only $table[0].config.lastSearch and $table[0].config.lastCombinedFilter
I saw another 2 arrays in pager like lastSearch:
- $table[0].config.pager.currentFilters
- $table[0].config.pager.last.currentFilters
It still save the old search data after using setFilters function.
Any problem about postback?

**Comment by Mottie** [comment]
Sorry for not replying sooner. Did you get this worked out?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
