### ISSUE TITLE
Name attribute of inputs in filter

### ISSUE THREAD

**Issue by pierresh** [Mottie/tablesorter#1499]
Hello,

I think it would be very useful to have the ability to set the name attribute of inputs in filters (I am using Tablesorter with ajax calls). I think this could be set like this (similar to initialization of values):

`<th data-name='my_name_attribute'>Field 1</th>`

I just made some tests in _jquery.tablesorter.widgets.js_, the code below does the job but that is probably not the cleanest way to achieve it.

```
buildFilter = $( '<input type="search">' ).appendTo( $filter );

/* My modification is below: */
if ($(table).find('thead tr:first th').eq(column).data('name') != undefined) {
	buildFilter.attr('name', $(table).find('thead tr:first th').eq(column).data('name'));
}
```

Thanks

**Comment by Mottie** [comment]
Hi @pierresh!

You can create your own custom filter row ([demo](https://jsfiddle.net/Mottie/729pgngw/)), or add the name attribute within a callback bound to the [`filterInit` event](https://mottie.github.io/tablesorter/docs/#filterinit):

Custom HTML Row:

```html
<tr class="tablesorter-ignoreRow filters">
  <td><input name="foo" type="search" data-column="0" /></td>
  <td><input name="bar" type="search" data-column="1" /></td>
  ...
</tr>
```

Script

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'filter'],
    widgetOptions: {
      filter_columnFilters: false,
      filter_external: 'tr.filters input'
    }
  });
});
```

**Comment by pierresh** [comment]
Hi @Mottie ,

Thanks a lot for your prompt reply, this works perfectly 👍
