### ISSUE TITLE
Make table adapt to changes in column visibility 

### ISSUE THREAD

**Issue by Rsasbrink** [Mottie/tablesorter#1500]
Hi,
I have a table in my webpage which uses horizontal scrolling, fixed Columns on the left and sorting.
Anyhow, I have a custom modal where I can select visibilities for each column. Like the Column Selector Widget, but custom made. I looking for a function which can make my table adapt to this. 
At the moment the table is not adapting very well and everything is skewed as soon as I try to hide a column. (Columns are set to "display:none;" when hiding)
![image](https://user-images.githubusercontent.com/17177640/35323044-8d291ecc-00ec-11e8-9cdb-512005b89e8a.png)

**Comment by Rsasbrink** [comment]
Is it possible to let the table re-render so it calculates everything again. and forgets about the hidden columns?  Or something like that.

**Comment by Rsasbrink** [comment]
Hi Mottie, 
I am using the scroller widget, but when I decide to hide a th and td based on a class. The rest of the cols are crooked. I was hoping the plug-in could see this happening and re-arranged the cols. 
Giving a demo is hard since it's a password protected project.

**Comment by Mottie** [comment]
Try using the [`setFixedColumnSize` method](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#methods). Leaving out the `size` parameter causes a refresh.

```js
$("table").trigger("setFixedColumnSize");
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
