### ISSUE TITLE
Editable radiobuttons in table.

### ISSUE THREAD

**Issue by Rsasbrink** [Mottie/tablesorter#1502]
Hi, I have a field with 3 radiobuttons in each row of my table which sets the status of that "appointment row". When I click it it puts a ajax call to my backend. However:
When I click on some of those radiobuttons to set some of those statuses it works and those statusses are getting updated in my backend space. But, when I select another sorting it sorts the table but RESETS those radiobuttons selected values to its original state. After a full refresh (which I don't want) I can see those new values and sort them.

![image](https://user-images.githubusercontent.com/17177640/35441212-eeb29b70-02a2-11e8-83dc-092f7f6bddc9.png)

**Comment by Mottie** [comment]
Hi @Rsasbrink!

It sounds like you need add a specific parser for that column... It doesn't have a radio parser included, but you should still load in the [`parser-input-select.js`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) file to handle automatically updating the cache when the content changes. Then include the following parser, and set it in the appointment column:

HTML

```html
<th class="sorter-radio">Appointment status</th>
```

Script

```js
$.tablesorter.addParser({
	id : 'radio',
	is : function() {
		return false;
	},
	format : function( txt, table, cell ) {
		var $input = $( cell ).find( 'input:checked' );
		return $input.length ? $input.val() : txt;
	},
	parsed : true, // filter widget flag
	type : 'text'
});
```

**Comment by Mottie** [comment]
The "radio" parser has been included in the `parser-input-select.js` file. Please let me know if you encounter any more issues.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
