### ISSUE TITLE
How to keep buttons in columns after ajax call?

### ISSUE THREAD

**Issue by Dayvidrc** [Mottie/tablesorter#1503]
Hello,

I'd like to know the easyest way to have a column with buttons and keep them after an ajax call. I'm having problems with this. My table is pre rendered with buttons but when I execute something that fires the ajax call, the table body is rendered without my buttons column.

Any advice I appreciate

**Comment by Mottie** [comment]
Hi @Dayvidrc!

I would be able to better help you if I saw some code. How is the table set up? How is the ajax call preformed and rendered after? What widgets or addons are being used? Etc.

This can be provided by modifying [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to show the basic HTML and JS. Please make sure not to include any sensitive data.

**Comment by Dayvidrc** [comment]
Hi Mottie!

I tried to put some code in that tool you've just provided. I have never used that before. I don't know if that is enough for you, but it is basically the way I'm trying to use tablesorter with tablesorterPager and sort the table via ajax call. As I said before, after an ajax call to sort my table, the column with buttons disappears.

If you need any additional information, please let me know.

**Comment by Mottie** [comment]
Oh, after you make the changes to the jsfiddle, click the save button at the top, then copy the new URL and paste it here.

**Comment by Dayvidrc** [comment]
Oh, that's my bad.

Let's try again: [My demo](https://jsfiddle.net/bbxxomhx/794/)

**Comment by Mottie** [comment]
I'm not sure what JSON is being returned, but you can include an entry in the array with `<input type="button" value="Delete" />`, or you can add it within the `ajaxProcessing` function:

```js
for (r = 0; r < len; r++) {
  row = [];                          
  for (c in d[r]) {
    if (typeof (c) === "string") {
      row.push(d[r][c]);
    }
  }
  // add Delete button column
  row.push('<input type="button" value="Delete" />');
  rows.push(row);
}
```

**Comment by Dayvidrc** [comment]
That's perfetc. It worked for me.

Thank you very much Mottie.
