### ISSUE TITLE
How to use filter-select when there are keywords like 'OR', 'AND' in table cells?

### ISSUE THREAD

**Issue by thobho** [Mottie/tablesorter#1505]
Hi!
I have a problem with filter-select option. I have in table column values like 'temperature value or humidity'. I dropdown list with correct entries but when I choose this one with the word "OR" I get no correct filter. I tried to add class 'filter-exact' but it still does not work.

Best regards,
Thobho

**Comment by Mottie** [comment]
Hi @thobho!

The filter's default setting for "and", "or" and "to" can be modified by providing a [`language`](https://mottie.github.io/tablesorter/docs/example-widget-filter.html#localization) setting:

```js
$.extend($.tablesorter.language, {
  to  : '-',
  or  : '\|', // escape any special regexp characters, for now
  and : '&&'
});
```

The settings must not include surrounding spaces, and can not be an empty string.

In the next update, I'll catch the above problems to:
* Remove surrounding spaces
* Work around empty strings. 
* Automatically escape special regular expression characters.

Related: https://github.com/Mottie/tablesorter/issues/1089#issuecomment-164088751 & https://github.com/Mottie/tablesorter/issues/1101

**Comment by Mottie** [comment]
I ended up reverting the automatic escaping of special regular expression characters. It's already documented that it must be done and the change would not be backwards compatible; but the update will still trim surrounding spaces and allow empty strings to be set.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
