### ISSUE TITLE
not an issue, just need your help (sorry) - scrollTop on a fixed column, scroller, tablesorter

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#1507]
i can't seem to be able to scroll this fixed column'd scroller tablersorter to the bottom.
 
i've tried waiting on the scrollerComplete event, but even $('#tbl').scrollTop (200);  doesn't scroll it down at all...  Got any ideers for me?  I only need it to happen on page load.

**Comment by Mottie** [comment]
Hi @Stephen-Hazel!

Try using `$('#tbl').parent().scrollTop (200);` ([demo](https://jsfiddle.net/Mottie/ft3qyjns/20/))

```js
$('table').on('scrollerComplete', function() {
  $(this).parent().scrollTop(200);
});
```

**Comment by Stephen-Hazel** [comment]
AWESOME.  Thank youuu, SIR !
