### ISSUE TITLE
Various problems detected with 2 header lines

### ISSUE THREAD

**Issue by JohnSmall** [Mottie/tablesorter#1508]
This expands on [this issue](https://github.com/Mottie/tablesorter/issues/1362)

Description: I have a table with two header rows. The top one I use to label groups of related columns, and the lower one is the columns themselves. None of the top columns should be able to sort the table and only some of the bottom columns should be able to sort the table.

Problem: I can't unsort the lower columns when I initialise tablesorter with 

     headers: {X: {sorted: false}}

The top row seems to be the one that headers is trying to target for unsorting. I can see that if I have `<thead><tr class='tablesorter-ignorerow'> etc` set then it doesn't put the sorting up/down arrows on the columns. But it does add a whole bunch of stuff to the columns in the row e.g. 

   ` data-column="0" scope="col" role="columnheader"`

So it's not completely ignoring that header row.

If I removed `class='tablesorter-ignorerow'` then I can use

     `headers: {X: {sorted: false}}`

To set columns to be unsorted on the top row. 

So it looks like `class='tablesorter-ignorerow'` only partially ignores the row. It adds attributes to the columns in that row and it's targeting that row for unsorting via `headers: {X: {sorted: false}}
`
Which is why I can't unsort the columns in the bottom row. 

I need to unsort the columns because I need to attach events to be triggered when the column gets clicked, but tablesorter is capturing the click.

**Comment by Mottie** [comment]
Hi @JohnSmall!

If you set the `tablesorter-ignoreRow` (capital "R" is needed) on the first row, the `headers` option will completely skip that row when it starts its zero-based indexing of table header cells.

I wouldn't actually recommend using the `headers` option. It's a layover from the original tablesorter and as you have noticed, can be very confusing when you have multiple rows or include a `rowspan` or `colspan` in the header. Instead add a `sorter-false` class to the column to disable.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
