### ISSUE TITLE
Sticky Header - Header flies down the screen when scrolling

### ISSUE THREAD

**Issue by JesperGJensen** [Mottie/tablesorter#1511]
Hi

I have a weird issue, with Sticky Headers.
I have a layout that is 100% of the screen height with a Header and Body.
Only the body has a scrollbar and the Header is always visible.
I am trying to get the Sticky Header to adhere to the top of the Body when scrolling the body, but i am unable.
When i scroll my body, the Header starts at the top and then flies down and below the screen.

I have created a JSFiddle example, that reproduces my problem.
http://jsfiddle.net/dczpvkad/3/

I hope this example helps illustrate my problem

**Comment by Mottie** [comment]
Hi @JesperGJensen!

The `.body` element needs to have a `position: relative` defined on it to make it work as expected ([demo](http://jsfiddle.net/dczpvkad/4/)):

```css
.body {
  position: relative;
  height: 200px;
  overflow-y: auto;
}
```

**Comment by JesperGJensen** [comment]
Thank you, that improves my situation.
I still have some weird behavior, but currently unable to recreate it in JSFiddle.
I will update if i manage to recreate my issue in JSFiddle.

**Comment by JesperGJensen** [comment]
I found the source of my problems, I had my Tables encased in Bootstrap rows with col-xs-12
This cause my sticky headers to be off by about 90px. I removed the Div around my tables and the problem was resolved.
Was probably some of my CSS that caused it.

Now the sticky header for the top level table is fine
