### ISSUE TITLE
Scroller with Hidden Columns

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1513]
Are there still troubles with the scroller widget and hiding columns? Would it be solvable by having the resize function check to see if that element is visible or not before it goes to make the percentage for its colgroup?

**Comment by Mottie** [comment]
Hi @MoMack20!

There is a fix for issue #1506 in the master branch, but it hasn't been released yet. That fix hides the extra `<col>` in the fixed column because Firefox was giving the hidden columns a width. I haven't encountered an issue with the resize function.

**Comment by MoMack20** [comment]
Do I need to use the column selector widget? Currently I am just using css to hide the columns and javascript to reduce the colspans where needed. When the columns are hidden and I call an update, the sizing gets all out of wack. To compensate I make the columns visible on update then hide them again on scroller complete, but the 200 ms delay on scroller update is a noticeable blip

**Comment by Mottie** [comment]
It's up to you if you want to use the column selector widget - it uses css to hide the columns & js to adjust the colspans as you described. How are the sizes getting out of whack? Is the `<col>` in the `<colgroup>` also being hidden?

**Comment by MoMack20** [comment]
Working on getting some screenshots, but the column hides fine when I call hide() (which i call on the colgroup column too) but when I trigger.update() the table comes back with space for the hidden column in the body table

**Comment by MoMack20** [comment]
Before hidding the column
![image](https://user-images.githubusercontent.com/11836187/36117721-ae5b5972-1008-11e8-91cd-cac6de6d63b3.png)

After hiding the column
![image](https://user-images.githubusercontent.com/11836187/36117938-6233c574-1009-11e8-8e8f-f54d25b95068.png)


After trigger update
![image](https://user-images.githubusercontent.com/11836187/36117881-38d1514c-1009-11e8-9c7d-fd25accfabad.png)

**Comment by MoMack20** [comment]
Missed one.
This is after trigger update and with scrolling over to the right
![image](https://user-images.githubusercontent.com/11836187/36118014-a5bd3370-1009-11e8-9899-3f10115a46d3.png)

**Comment by Mottie** [comment]
Oops, I didn't address this in v2.29.6... I'll make sure this is on my to-do list for the next release.

**Comment by MoMack20** [comment]
I found out my flaw. The css must also be set with colspan > col:nth-child as well as the th/td nth-child
