### ISSUE TITLE
Custom Popup with Column Selector Not Populating with Dynamically Created Table

### ISSUE THREAD

**Issue by khupka** [Mottie/tablesorter#1517]
I am creating a dynamic table and adding the data-priority attribute to my columns, but the columns are not populating in the popup.  Here is the code to generate the headers:

```js
var header$ = $("<thead/>");
var headerTr$ = $("<tr/>");
var headerTh$ = $("<th/>");
headerTh$.attr("data-priority", 1);

headerTr$.append(headerTh$.html("Index"));

for (var i = 0; i < data.length; i++) {
  var rowHash = data[i];

  for (var key in rowHash) {
    if ($.inArray(key, columnSet) == -1) {
      columnSet.push(key);
      var headerTh$ = $("<th/>");
      headerTh$.attr("data-priority", 1);
      headerTr$.append(headerTh$.html(key));
    }
  }
}
```

The attribute is getting added to the table, but there are no results in the popup.

![screen shot 2018-02-25 at 10 05 33 am](https://user-images.githubusercontent.com/5291688/36644725-814bea4a-1a13-11e8-8eac-25456d26e990.jpg)

![screen shot 2018-02-25 at 10 04 22 am](https://user-images.githubusercontent.com/5291688/36644718-5b0c7b74-1a13-11e8-8f10-825230f8681c.jpg)

If I include the demo table in the HTML, it does populate:
```html
<table class="tablesorter bootstrap-popup">
  <thead>
    <tr>
      <th data-priority="critical">Rank</th>
      <th data-priority="3">First Name</th>
      <th data-priority="critical">Last Name</th>
      <th data-priority="4">Age</th>
      <th data-priority="4">Total</th>
      <th data-priority="5">Discount</th>
      <th data-priority="6">Date</th>
    </tr>
  </thead>
  <tbody>
    <!-- ... -->
  </tbody>
</table>
```

![screen shot 2018-02-25 at 10 08 54 am](https://user-images.githubusercontent.com/5291688/36644766-f6a07554-1a13-11e8-9687-0ef7c3f0f5b4.jpg)

**Comment by Mottie** [comment]
Hi @khupka!

Try initializing the table after it's been updated; or trigger an [`applyWidgets` method](https://mottie.github.io/tablesorter/docs/#applywidgets) after the priority attributes have been set.

If that doesn't work, please modify [this demo](https://jsfiddle.net/Mottie/mcn8o3yu/) to show the issue.

Thanks!

**Comment by khupka** [comment]
Hi @Mottie!

I figured out that I was actually initializing the table twice which was causing the issue!  Thank you so much for the quick response!
 
:)
