### ISSUE TITLE
Filter "filter-onlyAvail" doesn't work if "showProcessing:true"

### ISSUE THREAD

**Issue by JamoCA** [Mottie/tablesorter#1518]
Using v2.29.6, I added "filter-onlyAvail" to a column and it didn't work until I removed `showProcessing:true`.  Is this a bug or are they incompatible with one another?  (If incompatible, can the demo be updated?)

**Comment by Mottie** [comment]
Hi @JamoCA!

Oh wow, nice find! I'll get this fixed in the master branch shortly.

**Comment by Mottie** [comment]
V2.30.0 is now available.
