### ISSUE TITLE
Adding Rows to Cache

### ISSUE THREAD

**Issue by MoMack20** [Mottie/tablesorter#1519]
Is there a way to add a row to cache without it being in the table first? I have implemented virtual scrolling and paging that keeps only the visible elements connected to DOM so the sorting stays smooth and so does the rest of the ui. But now I can't add anything new to the table once this happens because it takes only whatever is in the DOM and makes the new cache out of those select rows.

**Comment by Mottie** [comment]
Hi @MoMack20!

There isn't any internal method to add rows without first appending it to the table; but you can add new data directly into the cache - just don't use the "update" method or it's be over-written.

If you want to modify the core to get the `addRows` method to work, then remove this line (and the preceeding `||`):

```js
( ts.getClosest( $row, 'table' )[ 0 ] !== c.table )
```

If you don't want to modify the core, then copy the code starting around [line 1419](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L1419) to update the cache.

**Comment by MoMack20** [comment]
Thanks @Mottie
