### ISSUE TITLE
Filtering not working with certain input

### ISSUE THREAD

**Issue by carlosperezb** [Mottie/tablesorter#1520]
I noticed this in a project of mine and have been able to reproduce it easily and consistently. It seems like filtering using the "filter-onlyAvail" option is not working when some row contains the pattern " - " in its content.

You can test this in https://jsfiddle.net/carlosperezb/sLe60me7/. Try and modify any city name to include the " - " pattern, run and select it under the city filter. The results seems to be inconsistent. For instance, changing Indianapolis to "India - napolis" returns it but also Los Angeles and Milwaukee. Changing it to "X - Indianapolis" returns a bunch of cities, but not itself.

**Comment by Mottie** [comment]
Hi @carlosperezb!

The behavior you're seeing is the "range" type filter processing a range of values.

For example if you search for `1 - 10`, the filter will return the value range of 1 to 10.

This also works with letters. For example, a search for `a - c` will result in entries from `aardvark` to `Czech`. Adding more letters will narrow the range, `India - napolis` (or the reverse range) `napolis - India` will return matches of words starting with `India` and ending with `napolis` (e.g. `Napa` (valley)).

Good news is that you can disable this type of search per column. Set the [`filter_excludeFilter` option](https://mottie.github.io/tablesorter/docs/index.html#widget-filter-exclude-filter) for that column, or all columns ([demo](https://jsfiddle.net/Mottie/bbxxomhx/916/)):

```js
$(function(){
  $("table").tablesorter({
    widgets: ["filter"],
    widgetOptions : {
      filter_excludeFilter : {
        // target a column by class name or column index (zero-based)
        0 : 'range',
        // target all columns; separate multiple filter types using spaces
        '.tablesorter-header' : 'fuzzy regex'
      }
    }
  });
});
```

**Comment by carlosperezb** [comment]
Hi @Mottie!

Alright that makes sense! I had not seen those options in the documentation and could not make sense of it. 

Thank you for the quick answer!

**Comment by Mottie** [comment]
If you can think of a way to improve the documentation, please let me know.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
