### ISSUE TITLE
rebuild / reload filter-select instead of buildSelect

### ISSUE THREAD

**Issue by azjol** [Mottie/tablesorter#1523]
Hello,
I use a server-site filtering and send data, which should be in the filter-select. This is the code of the building filter-select:

`$.tablesorter.filter.buildSelect( "table", key, data.filter_listbox[value], false );`

Can you help me, how to reload / rebuild filter select instead of building? I use `ajaxProcessing` function and **filter-select is duplicated after ajax processing** if I use a code above.

**Comment by Mottie** [comment]
Hi @azjol!

Use the [`filter_selectSource` option](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource) to provide the select options. There is an example in the documentation.

**Comment by azjol** [comment]
Mottie, thank you for your response.
I have read the documentation, but I would like to refresh filter-select every ajaxProcessing. It works well now, but unfortunately filters are duplicated every ajaxProcessing, so maybe I need some function to empty select filters and build again every ajaxProcessing

**Comment by Mottie** [comment]
Did you pass `true` as a fourth parameter?

```js
// call the buildSelect function; pass `true` to replace the contents of the select
$.tablesorter.filter.buildSelect( table, column, result, true, onlyAvail );
```

**Comment by azjol** [comment]
Ahh, awesome. My fault. Thank you so much!
