### ISSUE TITLE
Feature Request: validateOptions only if debug=true

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1528]
Hi,

I think the title says it all: don't validateOptions if debugging is off to not wast time on start.
Another reason for that wish is that I fill widgetOptions when initializing tablesorter and later add/remove widgets (e.g. filter). This will flood the error log.
Or can you suggest a better way to temporarily enable/disable widgets? At the moment I use removeWidget and applyWidgetId.

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

This would be a reasonable change, now that you can debug each component. My intention was to reduce developer frustration, but yeah user perceived performance is more important.
