### ISSUE TITLE
showAllRows sets p.size to p.totalPages, should be p.totalRows

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1529]
Hi,

in widget-pager.js showAllRows sets p.size to p.totalPages but my guess is that it should be set to p.totalRows. Using v2.30.0.

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

LOL, thanks for letting me know! It's only been broken for a year ([ref](https://github.com/Mottie/tablesorter/commit/4f43c31b7c949396334951222af82cfb307e452a))!

**Comment by a-mair** [comment]
Hi @Mottie,

thanks for fixing! You might consider removing "console.log(p.totalRows, p.totalPages);" again.

**Comment by Mottie** [comment]
LOL
