### ISSUE TITLE
Feature Request: use pager_savePages only if pager_startPage not given

### ISSUE THREAD

**Issue by a-mair** [Mottie/tablesorter#1530]
Hi,

I think that pager_startPage (and pager_size) should be preferred if they are given in the widgetOptions even if pager_savePages is is enabled. What do you think?

Best regards,
Andreas

**Comment by Mottie** [comment]
Hi @a-mair!

My thinking is that the user preferences would take precedence over the default values. Personally, if I was on page 50, and had to select that page every time I went to a site, I'd be frustrated - unless the pagination was set up to allow direct input of the page (e.g. click on the ellipsis in [this plugin](http://flaviusmatis.github.io/simplePagination.js/)).

**Comment by a-mair** [comment]
Hi @Mottie,

yes, that's how I would expect as a user too and I don't want to change that.
I have the use case that a user can add a row to the tablesorter. By design the webpage has to be replaced completely (incl. tablesorter), but I know the added row. From that information I can calculate pager_startPage. In any other case pager_startPage won't ne defined.

**Comment by Mottie** [comment]
Maybe it would be easier to update the storage directly?

```js
$.tablesorter.storage( table, table.config.widgetOptions.pager_storageKey, {
  page: 2,
  size: 10
});
```

**Comment by a-mair** [comment]
I'm not sure if it's easier/preferable:
- I guess that tablesorter ("table") has to be initialized already, hasn't it?
- There has to be code that deals with "pager_savePages true or false", "storage available" etc., while this is already taken care of in the pager widget

**Comment by Mottie** [comment]
> tablesorter ("table") has to be initialized already

Yes, `table` is equivalent to `$('table')[0]`, and tablesorter need to have been initialized to have `table.config` values.

> code that deals with "pager_savePages true or false", "storage available"

I'm not sure what you mean.

**Comment by a-mair** [comment]
> Yes, table is equivalent to $('table')[0], and tablesorter need to have been initialized to have table.config values.

I'm not sure if I get it right:
- I initialize the table: $('table').tablesorter( { /* config */ });
- Then I run your $.tablesorter.storage(...) suggestion?
But does the pager then re-read the storage?

> I'm not sure what you mean.

Right, that's quite too short. I mean if pager_savePages is false I can't use $.tablesorter.storage(...). In that case I have to go the current way and set pager_startPage. If pager_savePages is true I have to check if $.tablesorter.storage(...) is usable.

**Comment by Mottie** [comment]
Oh, I meant to update the storage after the row has been added and the new page has been calculated.

What if you use the [`pageSet` method](https://mottie.github.io/tablesorter/docs/#pageset) instead?

**Comment by a-mair** [comment]
Thanks, I'll consider your suggestions and see how they perform.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
