### ISSUE TITLE
scroller tablesorter - best way to add columns and rows

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#1532]
not a bug.  just a question about the best way to do something.

I'm using a scroller tablesorter to "drill down" into data.
The table starts with only 1 key and a bunch of summary rows.
Click a plus and it adds a new key column and a bunch of detail rows above the existing summary row.
The plus turns into a minus.  Click that and the new detail rows go away and the new key column is tossed.
 
I've got most of that worked out with jquery.  But it doesn't seem like I can just add a column to the "pre magic"'d scroller tablesorter table and then just refresh it.

I'm going to do some more investigating, but I thought I'd ask the guy who wrote this baby how feasible adding rows and columns to the underlying table and refreshing it...  umm, if that can work...?

**Comment by Mottie** [comment]
Hi @Stephen-Hazel!

Yeah, adding and removing columns in tablesorter has always been troublesome. I tried using the [`addRows` method](https://mottie.github.io/tablesorter/docs/#addrows), but it isn't set up to work with fixed columns yet 😿.

I set up [this demo](https://jsfiddle.net/b2bb3tLs/) and got everything working:

```html
<!-- button cell -->
<td><button type="button" class="delete">x</button></td>

<!-- add button -->
<button id="add">Add Row</button>
```

```js
  $('#add').click(function() {
    $row = $(`<tr>
      <td><button type="button">x</button></td>
      <td>Fred</td>
      <td>Gwynne</td>
      <td>100</td>
      <td>1313 Mockingbird Lane</td>
      <td>CA</td>
      <td>90210</td>
      <td>(714) 123-1313</td>
      <td>herman@munster.com</td>
      <td>Herman! Herman, please! How many times do I have to tell you not to pound stakes while I'm around? You know it gives me heartburn!</td>
    </tr>`).appendTo($('table tbody'));
    //$('.tablesorter-scroller-table table').trigger('addRows', $row);
    $('.tablesorter-scroller-table table').trigger('update');
  });

  $('body').on('click', '.delete', function() {
    var index = $(this).closest('tr').index();
    $('.tablesorter-scroller > .tablesorter-scroller-table tbody tr').eq(index).remove();
    $('.tablesorter-scroller-table table').trigger('update');
  });
```

**Comment by Mottie** [comment]
Oh, and to add and remove columns (*cringe*), you'll probably have better luck [destroy](https://mottie.github.io/tablesorter/docs/#destroy)ing tablesorter and reinitializing it, instead of using [`updateAll`](https://mottie.github.io/tablesorter/docs/#updateall).

**Comment by Stephen-Hazel** [comment]
welp, then i think i'm gonna have to keep a list of all the +d and -d spots, ajax em to php and have it rebuild the whole fricken table plus detail, and init the scroller tablesorter.  That's gonna be slow.  I wonder if loading all the detail into a javascript array after page init and then having javascript rebuild all the +d thing would be faster...  Hmmm...  The thing is, I'm competing with Excel :(  No fair.

**Comment by Mottie** [comment]
Instead of adding rows, what if clicking on the "+" opened a modal?

**Comment by Stephen-Hazel** [comment]
those damn users don't want that :(  Anyways, you answered my questions - redo the dang table cuz ya gots ta.  I appreciate your help, dude !!  You're the bEST.
