### ISSUE TITLE
click savebutton -> insert to MySQL

### ISSUE THREAD

**Issue by Dokhra** [Mottie/tablesorter#1533]
Hello Everyone,

does anyone have an idea how i can save the data with "click_on_save_button" to MySQL Database (including childrows):
https://mottie.github.io/tablesorter/docs/example-child-rows-filtered.html

Best Regards,
M

**Comment by Mottie** [comment]
Hi @Dokhra!

On the front-end you could use the [output widget](https://mottie.github.io/tablesorter/docs/example-widget-output.html) to process the table data to output JSON, then send that data to your server.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
