### ISSUE TITLE
Sorting bug in the jsFiddle for Bootstrap (in Wiki)

### ISSUE THREAD

**Issue by egmfrs** [Mottie/tablesorter#1536]
The column Languages does not sort when clicked. The headers code section needs to be updated:

```
		headers: {
			// set 'sorter : false' (no quotes) to disable the column
			0: { sorter: 'text' },
			1: { sorter: 'digit' }, //CHANGE THIS TO 'text' TO FIX!!
			2: { sorter: 'text' },
			3: { sorter: 'url' }
		},
```
This looks like it's been copied and pasted from somewhere else as 'url' doesn't make sense either.

**Comment by Mottie** [comment]
Hi @egmfrs!

The wiki pages are editable by everyone. I would appreciate it if you could fix it.

**Comment by egmfrs** [comment]
Hi - the error is within your jsfiddle though, with your username in the url

**Comment by Mottie** [comment]
I updated the "tablesorter Bootstrap with pager" demo. Was that the only one?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by egmfrs** [comment]
@Mottie it was the only one I came across. Thanks!
