### ISSUE TITLE
Any way to sort by timestamp but only display date in the column?

### ISSUE THREAD

**Issue by egmfrs** [Mottie/tablesorter#1537]
I have a "submitted date" column in my table. I only want the users to see the date MM/dd/yyyy in the column, for brevity (rather than the full data: MM/dd/yyyy hh:mm:ss)

The default sort is by submitted date so most recent should show at the top of the table.
However with only the date showing, the most recent submission does not always go straight to the top because it will share the same date as other submitted that day.

Is there any known way around this problem? Can I have the Submitted date column sort based on a hidden column which contains the full date and time? Or can I put the timestamp in a hidden data field inside the column which will be used in the sorting process, rather than the text shown to the user.

**Comment by Mottie** [comment]
Hi @egmfrs!

You have a few options:

1. Include a `data-text` attribute with the timestamp (modifiable by the [`textAttribute` option](https://mottie.github.io/tablesorter/docs/#textattribute; [demo](https://jsfiddle.net/Mottie/bbxxomhx/1091/)).

    ```html
    <td data-text="Jul 6, 2018 5:22 PM">7/6/2018</td>
    ```

2. Use a custom [`textExtraction` function](https://mottie.github.io/tablesorter/docs/#textextraction) to get the data from an attribute, array or hidden element in the cell (same demo as above).
3. Hide the time in the cell ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1092/)).

    ```html
    <td>7/6/2018 <span class="hidden">5:22 PM</span></td>
    ```

**Comment by egmfrs** [comment]
Many thanks for your response. I got the first option working. I had quite a sticking point with this and couldn't work out why it worked in your fiddle and not in my project. Then I realised it was all about changing the the 0 to a 2 on this line in all of my default code.
`      2: function(node, table) {`

**Comment by Mottie** [comment]
By the way, all of the column functions work by setting a column class name as well:

```html
<th class="date">Date</th>
```

```js
textExtraction: {
  '.date': function(node, table) { ... }
}
```

**Comment by egmfrs** [comment]
Ah, so the number was the index of the column?! I struck lucky then as my date column was third in, coincidentally the same as your jsfiddle.

**Comment by Mottie** [comment]
Yes, the zero-based index of the column.
