### ISSUE TITLE
How to Initialize a new table

### ISSUE THREAD

**Issue by cardosor** [Mottie/tablesorter#1539]
I am calling the whole table from a php page using ajax. So I have a DIV lets say: `<DIV id="data">`, then I use: 
`document.getElementByID('data').innerHTML = response` from the php page, which is `<table id="table"> table contend <table>`, the table does not initialize, how do I initialize it? Thanks in advance.

**Comment by Mottie** [comment]
Hi @cardosor!

After you update the `innerHTML` of the element, you will need to call the tablesorter plugin.

```js
$('#data')
  .html(response)
  .tablesorter({ /* options */ });
```

If the table is populated server-side then you'll need to initialize tablesorter when the document is ready  (see the [getting started](https://mottie.github.io/tablesorter/docs/#Getting-Started) section.

If you continue to alter the table content, then initialize tablesorter first, then update the `tbody` and trigger "update" event on the table - you can follow the example in [this demo](https://mottie.github.io/tablesorter/docs/example-ajax.html).

[Here is a demo](https://jsfiddle.net/Mottie/bbxxomhx/) that initializes an in-place table showing nearly all the options.

**Comment by cardosor** [comment]
Thanks for the response. It seems to be applying the plugin to the data, as I can click on the headers (text) and sort the columns, but the table is not getting formatted with CSS, it looks like plain text. Do I have to call a method to apply CSS formatting?

**Comment by Mottie** [comment]
If you're using an already defined theme, you can either add the name using the [`theme` option](https://mottie.github.io/tablesorter/docs/#theme) or add it as a class name to the table, e.g. the blue theme would need the class name `tablesorter-blue` added to the `table`. If you include the default theme and initialize tablesorter with no options, the default theme will be applied.

If you're using a custom theme, make sure to include the following definition:

```css
.filtered { display: none; }
```

If you need to alter that class name, then set the [`filter_filteredRow` widgetOption](https://mottie.github.io/tablesorter/docs/#widget-filter-filteredrow).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
