### ISSUE TITLE
Unable to Sort Column with table sorter 

### ISSUE THREAD

**Issue by gitpuneetsvyas** [Mottie/tablesorter#1543]
I am using table sorter version 2.0.3  and jquery 1.3.1.min when i tried to sort a column having input text it was not working since it is old app do we have any workaround?
MyAppTableSorter is  wrapper for original table sorter where we are just defined some parser for date and checkbox.

```js
$("table.tablesorter").MyAppTableSorter(
  {
    //hideSearchResultsLabel: true
  }
);
```

**Comment by Mottie** [comment]
Hi @gitpuneetsvyas!

There is an input parser available in the [`parser-input-select.js` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) - you can see it working in the [grouping widget demo](https://mottie.github.io/tablesorter/docs/example-widget-grouping.html) (next to last column).

To make it work, include the above file, then add a class name of `sorter-inputs` to the header.

```html
<th class="sorter-inputs">Inputs column</th>
```

**Comment by gitpuneetsvyas** [comment]
Thanks Mottie;as this is a legacy app we don't have option to upgrade from 2.0.3 to 2.7.11 version.
Could you please provide some pointers how we can do with 2.0.3 version?
Appreciate your time and help!!

**Comment by Mottie** [comment]
The widget *should* work with that older version... but instead of adding a `sorter-inputs` class, you'll need to add it to the `headers` option.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
