### ISSUE TITLE
Horizontal scroller jumps slightly to the left when sorting last column

### ISSUE THREAD

**Issue by tlembrechts** [Mottie/tablesorter#1545]
I'm using the "scroller" widget for the fixed column functionality, but when I try to sort the last column the table jumps slightly to the left. To reproduce it you can use the fixed column demo:
[https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#fixed-demo](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#fixed-demo)
Before sorting:
![image](https://user-images.githubusercontent.com/18407067/39550819-4da4f54c-4e6b-11e8-84a1-501bf94e3653.png)
After sorting:
![image](https://user-images.githubusercontent.com/18407067/39550862-71a22460-4e6b-11e8-8ac4-a035ccd168d0.png)

I have tried all different settings that the widget offers, but the issue remains.

**Comment by Mottie** [comment]
Hi @tlembrechts!

Thanks for reporting this problem! I'll get a fix in the master branch shortly. It'll be available in the next update.
