### ISSUE TITLE
sorter-false no longer working on multiple row header

### ISSUE THREAD

**Issue by mtgtnt** [Mottie/tablesorter#1550]
https://stackoverflow.com/questions/16823951/tablesorter-with-two-header-rows

You can see even the [jsfiddle ](http://jsfiddle.net/Mottie/4mVfu/403/) is no longer working.

**Comment by Mottie** [comment]
Hi @mtgtnt!

Actually it is working as expected. The top 3 cells have sorting disabled, but the second row has not been disabled. If you wish to disable sorting completely, then add `sorter-false` to all `thead` cells.

**Comment by mtgtnt** [comment]
If you click on the "January / February / March" cells, it shouldnt sort, but it does.

**Comment by Mottie** [comment]
Oh weird... I thought I fixed that a few weeks ago in https://github.com/Mottie/tablesorter/commit/ce0405b2fb5e579a2b0bf23a3128491bb5f9e3bc... I'll take another look. Thanks!

**Comment by mtgtnt** [comment]
I had updated files on the server about a month ago and it took till now to troubleshoot what users were telling me so I went looking and found that jsfiddle and confirmed what I was seeing locally. It's not a big issue, just trying to keep PEBKAC's from clicking where they shouldn't and then complaining that it did something unexpected. I wanted to let you know about it. :)

**Comment by Mottie** [comment]
Hehe thanks... I found the problem. It's because of some minor changes to determine which column is being sorted when there is a `colspan` - see #1524.
