### ISSUE TITLE
Parser-input-select.js error

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#1554]
After [this commit](https://github.com/Mottie/tablesorter/commit/0c75f5f7d2f6fbbbd570053f1644e35d656ebb6f#diff-d29c344bff8509d3a2d3e2693ef3f35a) the following error occurs for me at line 148 of `parser-input-select.js`:
> TypeError: $el[0] is undefined

It seems that the `updateCheckbox` function is run twice and the error happens the second time. Changing line 148 to check for undefined fixes the issue for me:
Replace: 
`if ($el[0].nodeName !== 'INPUT') {`
With this:
`if (typeof $el[0] !== 'undefined' && $el[0].nodeName !== 'INPUT') {`
Not sure if this is the best fix or there is another root problem.
Thanks,
lindonb

**Comment by Mottie** [comment]
Hi @lindonb!

Thanks for reporting this problem. I'll get it fixed ASAP.
