### ISSUE TITLE
table sorter working only for one column not for others

### ISSUE THREAD

**Issue by shreya-khajanchi** [Mottie/tablesorter#1555]
jquery.tablesorter.js:1291 Uncaught TypeError: Cannot read property 'sortDisabled' of undefined
    at HTMLTableCellElement.<anonymous> (jquery.tablesorter.js:1291)
    at HTMLTableCellElement.dispatch (jquery-latest.min.js:3)
    at HTMLTableCellElement.r.handle (jquery-latest.min.js:3)

**Comment by Mottie** [comment]
Hi @shreya-khajanchi!

Please make sure your [HTML is valid](https://validator.w3.org/). Then please let me know which version of tablesorter is being used, and share the initialization code. If you're not using the most recent version, then please update it and let me know if the error persists.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
