### ISSUE TITLE
CSS Sticky Header Widget Jumps Around in Windows 10

### ISSUE THREAD

**Issue by genebaker** [Mottie/tablesorter#1557]
Using the following markup, the table header does not stick exactly to the top of the table while the table content is scrolled. It moves down and up several pixels during scrolling,

jQuery("#nvsDialListTableId").tablesorter({
      widthFixed: true,
      sortList: [[1], [1]],
      debug: true,
      headers: {
        0: { sorter: "inputs" },
        1: { sorter: "inputs" },
        2: { sorter: "inputs" },
        3: { sorter: "inputs" }
      },
      widgets: ["saveSort", "filter", "cssStickyHeaders"],
      widgetOptions: {
        cssStickyHeaders_attachTo: ".scrollable-diallist-table",
        cssStickyHeaders_offset: 0,
        cssStickyHeaders_addCaption: true,
        cssStickyHeaders_filteredToTop: true
      }
    });

OS: Windows 10 Pro
Version: 1709
OS Build: 16299.431
Firefox: 60.0.2
Edge: 41.16299.402.0
IE: 11.431.26299.0

Chrome 67.0.3396.87 works perfectly.

**Comment by Mottie** [comment]
Hi @genebaker!

Making the header stick using css has been wrought with issues. The sticky header does stick, but it can be jumpy while scrolling in most browsers... I believe this is due to how browsers apply a transform to table elements. Also, the rendering of a transformed header has odd behaviors in some browsers, like the border isn't included with the transformed cell.

These same issues has come up before, and I really think the best solution is to switch to using the non-css3 sticky headers widget; but yes, it doesn't work perfectly in Chrome 😉.

**Comment by genebaker** [comment]
Thanks for the feedback. Switching to Scroller Widget.

**Comment by Mottie** [comment]
LOL, the scroller widget has a lot more compatibility issues. I meant for you to try the [stickyHeaders widget](https://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html) - there are two stickyHeaders widgets, one that doesn't use css3 transforms and one that does.

**Comment by genebaker** [comment]
OK - switched to stickyHeaders. The cssStickyHeaders was too slow for my app anyway. But, I am not able to get the headers to stick. The table is dynamically loaded (500+ records) on page load and the tablesorter headings work great. Do you see any problems in the tablesorter portion of my code?

jQuery("table").tablesorter({   //Only table on the page
      widthFixed: true,
      showProcessing: true,
      headerTemplate: "{content} {icon}",
      sortList: [2,0],
      debug: true,
      headers: {
        0: {
          sorter: "inputs"
        },
        1: {
          sorter: "inputs"
        },
        2: {
          sorter: "inputs"
        },
        3: {
          sorter: "inputs"
        }
      },
      widgets: ["saveSort", "stickyHeaders", "filter"],
      widgetOptions: {
        stickyHeaders_Offset: 200,   //so I can see the headers if they render in an unexpected place
        stickyHeaders_zIndex : 99,
        stickyHeaders_attachTo : jQuery(".scrollable-diallist-table"),   //the table wrapper
        stickyHeaders_yScroll : null,
        stickyHeaders_filteredToTop: true
        }
      });

**Comment by Mottie** [comment]
The only thing I can think of is to make sure this css is included:

```css
.scrollable-diallist-table {
  position: relative;
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
