### ISSUE TITLE
Scroller Widget Show Additional Scrollbar in Firefox

### ISSUE THREAD

**Issue by genebaker** [Mottie/tablesorter#1559]
In Firefox, the Scroller Widget is showing two y overflow scrollbars. The thin (null) scrollbar is applied to classes tablesorter-scroller and tablesorter-scroller-has-fixed-columns and is correct. The second scrollbar is applied to the class tablesorter-scroller-table and is not correct. If I disable the auto overflow in the Inspector the problem temporarily goes away. But, if I put in a css override the the scrollbars go away in every browser.

Any thoughts on this would be most appreciated.

OS: Windows 10 Pro
Version: 1709
OS Build: 16299.431
Firefox: 60.0.2

Chrome, Edge, and IE work fine
Edge: 41.16299.402.0
IE: 11.431.26299.0
Chrome:  67.0.3396.87

Scroller Widget code:

```js
  jQuery("#nvsDialListTableId").tablesorter({
  widthFixed: true,
  showProcessing: true,
  headerTemplate: "{content} {icon}",
  sortList: [[1], [1]],
  debug: true,
  headers: {
    0: {
      sorter: "inputs"
    },
    1: {
      sorter: "inputs"
    },
    2: {
      sorter: "inputs"
    },
    3: {
      sorter: "inputs"
    }
  },
  widgets: ["saveSort", "filter", "scroller"],
  widgetOptions: {
    scroller_fixedColumns: 4,
    scroller_height: 441,
    scroller_upAfterSort: true,
    scroller_jumpToHeader: true,
    scroller_addFixedOverlay: false,
    scroll_barWidth: null,
    scroller_rowHighlight: "hover"
  }
});
```

**Comment by Mottie** [comment]
Hi @genebaker!

I'm not seeing any issues in the [fixed column demo](https://mottie.github.io/tablesorter/docs/example-widget-scroller.html#fixed-demo) in the documentation or in [this jsFiddle demo](https://jsfiddle.net/Mottie/ft3qyjns/). Would you please modify the jsFiddle to show the problem... make sure to click on "**Update**" after you're done and copy the updated url and paste it in a comment here.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
