### ISSUE TITLE
stickyHeaders & checkboxes scrolling issue

### ISSUE THREAD

**Issue by bzukatolahht** [Mottie/tablesorter#1560]
There are several reports similar to this issue but it is still present in 2.30.6.  The issue is that scrolling a table that contains a checkbox, in a stickyHeader, causes the header based checkbox to show incorrect state.

Recipe to recreate, and demo of issue, is on jsfiddle...

https://jsfiddle.net/olah_fiddle_bz18/xpvt214o/272607/

Thank you.

**Comment by Mottie** [comment]
Hi @bzukatolahht!

Thanks for letting me know. I'll try to get this fixed soon.

**Comment by Mottie** [comment]
This fix will be available in the next update... which may not be for a week, or so.

**Comment by bzukatolahht** [comment]
Awesome!  Thank you Mottie!
