### ISSUE TITLE
checkbox within TH causes output from output widget to show "TRUE" or "FALSE" regardless of whether there is header text or not

### ISSUE THREAD

**Issue by dmarra** [Mottie/tablesorter#1565]
I have a table which has a few columns that, in addition to header text, also have checkboxes which act as a "select all" feature. All of this works fine, until I export it using the output widget. The resulting CSV file is missing the text from the header, instead using the check state of the checkbox to determine what the column header should be.

Maybe I am doing something wrong, but this seems like a bug. I am using v2.30.4

**Comment by Mottie** [comment]
Hi @dmarra!

You can use the [`output_formatContent` callback](https://mottie.github.io/tablesorter/docs/example-widget-output.html#output_formatcontent) to determine what is sent to the output widget... in this case you can send the content when it's processing the header and the parsed data otherwise ([demo](https://jsfiddle.net/Mottie/yL1qon7e/35/)):

```js
$(function() {

  var $table = $('table');

  $('.download').click(function() {
    $table.trigger('outputTable');
  });

  $table.tablesorter({
    theme: 'blue',
    widgets: ['zebra', 'output'],
    widgetOptions: {
      output_formatContent: function(c, wo, data) {
      	return data.isHeader ? data.content : data.parsed;
      }
    }
  });
});
```

**Comment by dmarra** [comment]
This looked promising, but for some reason data.parsed is always
undefined...

This particular table uses a custom parser; could that be the reason why?

**Comment by Mottie** [comment]
Ah, the demo is using the "checkbox" parser in the [`parser-input-select` file](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js#L50-L67). Your custom parser may not be returning a human readable "checked" or "unchecked" value.
