### ISSUE TITLE
Uncaught TypeError: Cannot read property 'toString' of undefined at Object.sortNatural

### ISSUE THREAD

**Issue by own3mall** [Mottie/tablesorter#1566]
I'm receiving the below error on the latest version of tablesorter (along with my older version of v2.29.5):

>
> Uncaught TypeError: Cannot read property 'toString' of undefined
>     at Object.sortNatural (jquery.tablesorter.min.js:formatted:1319)
>     at Object.sortNaturalAsc (jquery.tablesorter.min.js:formatted:1364)
>     at jquery.tablesorter.min.js:formatted:1235
>     at Array.sort (native)
>     at Object.multisort (jquery.tablesorter.min.js:formatted:1209)
>     at jquery.tablesorter.min.js:formatted:1183

It seems to not like the column data which consists of the following:

```
<td class="centerAlign userGlimpse"><img src="https://serv1.dragndropz.com/user_images/2018_07_09/thumbs/397_cXSCjb_chronic_I_miss_u.jpg" alt="rawr57"><br><span class="linkActor underline visitUser">rawr57</span></td>
```

Attached is a screenshot showing the problem:

<a href='https://serv1.dragndropz.com/user_images/2018_07_09/398_ngjDoq_error_tablesorter_toString_undefined.png' target='_blank'><img src='https://serv1.dragndropz.com/user_images/2018_07_09/thumbs/398_SMwOIq_error_tablesorter_toString_undefined.png' alt='Attached Image Hosted by DragNDropz www.dragndropz.com'></a>

Any idea why this might be happening?

**Comment by Mottie** [comment]
Hi @own3mall!

What parser is being set for that column? Would you please share the tablesorter initialization code being used.

**Comment by own3mall** [comment]
I didn't set one.  Just using the default. 

```
function styleAndMakeTablesSortable(){
	$(".sortableTable").tablesorter({
		theme : 'blue'
	}); 
	
	// Rehighlight on sort
	$(".sortableTable").bind("sortEnd", function() {
		styleTableAlternatingRowColors();
	});
	
	// Trigger change since the table contents have probably changed
	// Documentation https://github.com/Mottie/tablesorter/issues/1131
	$(".sortableTable").trigger('update');
	
	styleTableAlternatingRowColors();
}
```

**Comment by Mottie** [comment]
I still can't duplicate the issue. By default, the "image" parser is set and extracts the alt attribute from the image. If there is no alt attribute, then it falls back to the text within the cell.

Is there any other script that might be interfering?

Also, you don't need to use `trigger('update')` immediately after initializing tablesorter.

No matter the cause, I'll modify that bit of code in the core to ensure that the parameters are not undefined.

**Comment by own3mall** [comment]
I'm not sure why it was happening either.  I'll try to put together a JSFiddle.  Pretty sure nothing else was interfering with the script.  It was just crashing for some reason.

**Comment by own3mall** [comment]
Figured it out.  The HTML was bad.  My closing </tr> tags were actually <tr> opening tags (missing the closing slash).  

Now that I've fixed that, I no longer have the issue.  Sorry about that... minor syntax errors can drive a person crazy.  

However, I still think it's a good idea to have those checks you put in even though it was totally my fault.  Thanks for working on this.  :+1:
