### ISSUE TITLE
filter-select does not filter properly

### ISSUE THREAD

**Issue by jh-deleon** [Mottie/tablesorter#1567]
-using the latest jquery
-observed on the 3rd column of the table
-no specified filter_functions on 3rd column
-other column filtering are working fine
-76 options in that filter
![image](https://user-images.githubusercontent.com/41314019/42794088-b51c5132-89af-11e8-9476-116f3bfd4eae.png)

**Comment by Mottie** [comment]
Hi @jh-deleon!

The dash makes the filter think it's looking for a range. See #1520 for instructions on how to disable it.

**Comment by jh-deleon** [comment]
thanks for the quick response! this resolves the issue :)
