### ISSUE TITLE
Issue with Widget-Output

### ISSUE THREAD

**Issue by svenema** [Mottie/tablesorter#1568]
Hello,

i have a weird issue with the output plugin, on my intranet page it does not work with the filter plugin enabled.
Even with debug enabled nothing happens when .trigger('outputTable') is used.
When copying my code to fiddle: http://jsfiddle.net/64vjwL3a/ It works fine.

**Comment by Mottie** [comment]
Hi @svenema!

It's difficult to claim that it works fine when the demo only had one row! I had to modify the demo by adding new rows and cleaning up the table - next time, please do not paste in the already rendered table into the demo, it breaks the filter and makes the html difficult to read.

Anyway, now I can verify it's working - https://jsfiddle.net/Mottie/wty134u7/304/ - I think the issue might be that the demo is pulling the tablesorter files directly from this repository. The script tags included in the demo used a relative path, so they weren't loading the code from your source. What I mean it, please make sure you're using all the latest tablesorter files.

While cleaning up the demo, I also forgot about loading code from mixed protocols `https` vs `http` which was preventing some code from working. Silly GitHub.

**Comment by svenema** [comment]
The Demo worked, pasting to the 250lines would not matter ;)

The version and location of TableSorter was not the issue, i had downloaded the latest version yesterday.
Changing to the repository did not fix the problem but put me in in the right direction.
The problem was with the local jquery.min.js file, changing this solved the issue.
To bad neither tablesorter (debug) or jquery prompted any output on the error.

Thank you very much Though

**Comment by Mottie** [comment]
What error were you seeing?
