### ISSUE TITLE
ajax json with backslash will fail to display

### ISSUE THREAD

**Issue by airthomas** [Mottie/tablesorter#1569]
Hi Mottie,

Please visit (https://jsfiddle.net/sEwM6/8106/), in line 11 "backslash" cannot display.

If changed to "\\", then able to display.

Many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

A backslash is used as an escape character in JavaScript. So a `"\"` is really an escaped double quote. If you want to display a backslash, you'll need to escape the backslash, i.e. `"\\"`.

Maybe [this article](https://mathiasbynens.be/notes/javascript-escapes#single) helps explain it better.

**Comment by airthomas** [comment]
great, after applied below in my php json then work. Thanks.

str_replace("\\", "\\\\", $iContent);
