### ISSUE TITLE
is there a way to use sorttext but move empty string to bottom

### ISSUE THREAD

**Issue by jh-deleon** [Mottie/tablesorter#1573]
Hi,

I tried checking the documentation on possible sorting but found none when it comes to empty string. I would resort to last option to use if(a === '') if there is no other way but it will affect the performance of the sorting. Let me know if more info is needed.
Thank you!

**Comment by jh-deleon** [comment]
Hi,

Combining the if(a === '') and sorttext did the trick.

**Comment by Mottie** [comment]
Hi @jh-deleon!

There is a built-in option called [`emptyTo`](https://mottie.github.io/tablesorter/docs/#emptyto) which has a default to sort empty strings to the bottom - [here's the main demo](https://mottie.github.io/tablesorter/docs/example-option-sort-empty.html).
