### ISSUE TITLE
Datetime Strings Not Sorting Properly?

### ISSUE THREAD

**Issue by own3mall** [Mottie/tablesorter#1574]
Hi All,

For some reason, my datetime strings aren't sorting properly on this page https://dynamix.run/donate.php

What is strange is that the below page doesn't appear to have any problems doing something very similar to what I'm trying to do:

https://mottie.github.io/tablesorter/docs/example-option-date-format.html

I followed the guide there too and put these classes in the th:

`sorter-shortDate dateFormat-mmddyyyy`

What am I doing wrong?  Is it because I also have seconds in the string?

I initialized the sorter using this code:

```
$(".sortableTable").tablesorter({
	theme : 'blue'
}); 
```

**Comment by Mottie** [comment]
Hi @own3mall!

It's not working because `7/28/2018 20:00:00 PM` is *not* a valid date... `7/28/2018 8:00:00 PM` is valid.

**Comment by own3mall** [comment]
Oh, I didn't notice that (even after looking at those dates several times).  Converting it to the 12 hour format works, but it seems that JavaScript dates are more easily parsed with the 24 hour format, so I'm not sure how "7/28/2018 20:00:00 PM" is invalid.  I guess the PM isn't necessary if you're using military time, but I'm not sure how that is an invalid date.  

```
date.getHours()
```

Is a lot easier than:

```
function get12HourFormat(hours){
	return ((hours + 11) % 12 + 1);
}
get12HourFormat(date.getHours());
```

Appreciate your help!  Thanks!

**Comment by Mottie** [comment]
![](https://user-images.githubusercontent.com/136959/43744545-20b33a32-99a0-11e8-9414-03442980b84e.png)

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
