### ISSUE TITLE
Can this plugin lock rows together?

### ISSUE THREAD

**Issue by Jaxel** [Mottie/tablesorter#1578]
I explain my issue here:

https://stackoverflow.com/questions/51942104/jquery-sortable-tables-with-adjoining-rows

**Comment by Mottie** [comment]
Hi @Jaxel!

If you add the class name set by the [`cssChildRow` option](https://mottie.github.io/tablesorter/docs/#csschildrow) - default is `tablesorter-childRow`.  Demo links available on that page.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
