### ISSUE TITLE
Webpack / Yarn / requires()

### ISSUE THREAD

**Issue by tlorens** [Mottie/tablesorter#1579]
I'm unable to get the Pager/pagination plugin to load.  I'm not an expert at using Webpack, but for the most part I've been guessing right thus far in getting this prototype application going.  

**This works**
```const tableSorter = require('tablesorter');
var $evidenceTable = $("#evidenceListing").tablesorter()
```

**This does not.** 
```
const tableSorter = require('tablesorter');
var $evidenceTable = $("#evidenceListing").tablesorter().tablesorterPager(pagerOptions);
```

I noticed that it seems to be using the 'combined.js' file when the build process runs.  I can't seem to find the tableSorter in the output.  

Am I missing something?  I'd like to adhere to the build process without going out of band and side-stepping things and just jamming the JS file in the pages with a script tag.

**Comment by Mottie** [comment]
Hi @tlorens!

Now that I think about it, the main problem is that only the `jquery.tablesorter.combined.js` file is using a [UMD](https://github.com/umdjs/umd) wrapper. All the other js (in `extra`, `parsers` and `widgets` folder) files in the `dist` folder are wrapped in an [IIFE](https://developer.mozilla.org/en-US/docs/Glossary/IIFE).

I'll have to add a script to wrap all the js files in a UMD to fix this problem. Once that's done, you'll need to access the files using a path through `node_modules`. Something like this:

```js
var folder = './node_modules/tablesorter/dist/';

var tablesorterPager = require(folder + 'js/extras/jquery.tablesorter.pager.min.js');
var pathToCss = folder + 'css/jquery.tablesorter.pager.min.css';
```

**Comment by Mottie** [comment]
Tablesorter v2.31.0 is now available, and on npm.

All widgets, parsers & extras javascript files should now work as follows:

```js
var $ = require("jquery");

var folder = "./node_modules/tablesorter/dist/";
require("tablesorter"); // tablesorter function is returned, but it is attached to jQuery
require(folder + "js/parsers/parser-metric.min.js"); // jQuery is returned, not the parser
require(folder + "js/widgets/widget-math.min.js"); // jQuery is returned, not the widget

// tablesorterPager is returned, but you still initialize it from jQuery
var tablesorterPager = require(folder + "js/extras/jquery.tablesorter.pager.min.js"); 

$(".sortable")
  .tablesorter({
    headers: {
      3: { sorter: "metric" }
    },
    widgets: ["zebra", "math"]
  })
  .tablesorterPager({
    container: $(".pager")
  });

```
