### ISSUE TITLE
pager_ajaxProcessing could be a useful default function

### ISSUE THREAD

**Issue by toabi** [Mottie/tablesorter#1580]
See [widgets/widget-pager.js#L94](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-pager.js#L94) - if you don't configure it, it returns nothing, even if your ajax endpoint already returns the data in exactly the format you would need.

In that case you then have to everywhere configure `pager_ajaxProcessing: function(data){return data}`.

Could that not be the default?

**Comment by Mottie** [comment]
Hi @toabi!

That makes total sense. I'll update both pagers (addon & widget) and it will be available in the next release.

**Comment by toabi** [comment]
By the way, what's more futureproof? Using the plugin or the widget? Thanks for that quick response too! 🎉

**Comment by Mottie** [comment]
I'm maintaining both for now, but I plan on phasing out the addon in the future.
