### ISSUE TITLE
Can't get sticky headers to work AT ALL....

### ISSUE THREAD

**Issue by Jaxel** [Mottie/tablesorter#1581]
This is my code:

	this.$target.tablesorter({
		widgets: ['zebra', 'cssStickyHeaders'],
		widgetOptions: {
			cssStickyHeaders_offset: 50,
			cssStickyHeaders_addCaption: true,
			cssStickyHeaders_attachTo: null,
			cssStickyHeaders_filteredToTop: true,
			cssStickyHeaders_zIndex: 10
		}
	});

You can see it running here:
https://8wayrun.com/wiki/mitsurugi-frame-data-sc5/

As you can see, the sorting, and the zebra are working fine. However, the sticky headers don't activate. Don't know why.

**Comment by Mottie** [comment]
Hi @Jaxel!

It doesn't look like the `widget-cssStickyHeaders.js` file is being loaded on that page.

I can tell it isn't loaded by looking in `$.tablesorter.widgets` array in the dev tools console. It only contains the built-in zebra widget.

**Comment by Jaxel** [comment]
Ah... yep.

**Comment by jjxtra** [comment]
cssStickyHeaders_zIndex also appears to be ignored and unused

**Comment by Mottie** [comment]
The `cssStickyHeaders_zIndex: 10` line was included in the documentation by accident. I have removed it and added an [options table to that page](https://mottie.github.io/tablesorter/docs/example-widget-css-sticky-header.html#options).
