### ISSUE TITLE
Sort numbers as text

### ISSUE THREAD

**Issue by Zero2Cool** [Mottie/tablesorter#1583]
Using v2.30.3 I have a need for numbers to be sorted as if they were text.   I've tried using the  class="sorter-text" in the th and it's still sorting the same way. 

Desired Result
00101
00101
0010101
0010102
0010103
0010104
0010105
00102
00103

Actual Result
00101
00101
00102
00103
0010101
0010102
0010103
0010104
0010105

**Comment by Mottie** [comment]
Hi @Zero2Cool!

The natural sort algorithm is stripping out the leading zeros. You'll need to switch to the plain text sorter. See #409 & #1571 for demos.

**Comment by Zero2Cool** [comment]
The demo it works as expected, but in the MVC application, it's still behaving as described earlier.

Here's how the tablesorter is being initlised. 

$(function () {
    $(".table-tablesorter").tablesorter({
        theme: "bootstrap",

        widthFixed: true,

        // widget code contained in the jquery.tablesorter.widgets.js file
        // use the zebra stripe widget if you plan on hiding any rows (filter widget)
        // the uitheme widget is NOT REQUIRED!
        widgets: ["filter", "columns", "zebra"],

        widgetOptions: {
            // using the default zebra striping class name, so it actually isn't included in the theme variable above
            // this is ONLY needed for bootstrap theming if you are using the filter widget, because rows are hidden
            zebra: ["even", "odd"],

            // class names added to columns when sorted
            columns: ["primary", "secondary", "tertiary"],

            // reset filters button
            filter_reset: ".reset",

            filter_defaultFilter: {
                // do exact match on select columns
                '.filter-select': '={q}'
            },
            textSorter: {
                0: $.tablesorter.sortText
            },
            // extra css class name (string or array) added to the filter element (input or select)
            filter_cssFilter: [
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm custom-select', // select needs custom class names :(
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm',
                'form-control form-control-sm'
            ]
        }
    });

});

**Comment by Mottie** [comment]
The `textSorter` should be outside of the `widgetOptions` since it's a core option. Also, the `0` is targeting the column using a zero-based index. Change this to target the appropriate column, or you could use the class name of that column, e.g.

```
textSorter: {
  '.item-id': $.tablesorter.sortText
}
```

**Comment by Zero2Cool** [comment]
Perfect, thank you.
