### ISSUE TITLE
How to best build clickable rows with ajax backend

### ISSUE THREAD

**Issue by toabi** [Mottie/tablesorter#1584]
I have a ajax backed table which received the data in the format `{total, filteredRows, rows, headers}`.

Is there any way to give rows some `data-url` attributes, or add a hidden column so I can add a onclick handler to trs to open that URL?

Would it make sense to build a widget for that? (Which has configured which table column is the link, then hides that column and on-click of a row opens that url?)

I couldn't find a really good way to do that yet.

**Comment by Mottie** [comment]
Hi @toabi!

I'm assuming you're using the pager... you can use the [`ajaxProcessing` callback function](https://mottie.github.io/tablesorter/docs/#pager-ajaxprocessing) to process the return ajax data and add attributes or styling as desired - look at the "Array (total only)" example.

**Comment by toabi** [comment]
Building the HTML on the client myself is something I would try to avoid.

My solution now is:

Modifying the `ajaxProcessing` to be:

    function(data){
        data.rows = $(data.rows);
        return data;
    }

And render the HTML of the rows already in the backend. For example in my generic tablesorter-backend at the end of `serialize_row(self, object)` I do now

    row = u'<tr data-absolute-url="{}">'.format(object.get_absolute_url())
    row += u''.join(u'<td>{}</td>'.format(value) for value in values)
    row += u'</tr>'

and then also `''.join(rows)` before serialising the object.

I wonder if the `ajaxProcessing` couldn't still be `return data` and the code which builds the table sees that `rows` isn't an array but a string and therefore assumes it's the whole `tbody` content. (And wraps it into `$()` if really necessary.

**Comment by Mottie** [comment]
If you look at the example, you'll see that the `ajaxProcessing` function only needs to return a `total`. You can modify and add the rows to the table within that function.
