### ISSUE TITLE
Multi-columns-sorting works only after the first manual sorting

### ISSUE THREAD

**Issue by automatix** [Mottie/tablesorter#1585]
Hello!

Following scenario: I have a table with columns `A`, `B`, `C`, and `D`. All the columns excepting the `C` are sortable. The Default sorting is: `D [DESC]`,  `A [ASC]` . Working fine. But now I want to add a further column (`D`) to the sorting (<kbd>SCHIFT</kbd> `+` `click` on the column's head).

**Expected behavior**: The _primary_ and the _secondary_ sorting remain as they are. A tertiary sorting (by `D`) is added. The table is sorted by three columns.

**Observed behavior**: The _primary_ and the _secondary_ sorting get reset. The table is now sorted only by the column `D`.

My code:

```
$(function () {
    $("#content .table").tablesorter({
        textExtraction: function (node, table, cellIndex) {
            n = $(node);
            return n.attr('data-normalized') || n.text();
        },
        headers: {
            2: {
                sorter: false
            }
        },
        cancelSelection: true,
        sortList: [
            [3,1], [0,0]
        ],
        widgets : ['columns'],
        widgetOptions : {
            columns : ['primary', 'secondary', 'tertiary'],
            columns_thead : true,
            columns_tfoot : true
        }
    });
});
```
For me it seems to be a bug, but maybe it's just about configuration?..

Best regards,
Ilya

**Comment by Mottie** [comment]
Hi @automatix!

Thanks that looks like a bug! I found a work-around until I get some time to fix the code base. Add the following code ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1701/)):

```js
initialized: function(table) {
  table.config.last.sortList = table.config.sortList;
}
```

**Comment by automatix** [comment]
Thank you very much!

**Comment by Mottie** [comment]
Fixed in the master branch... I'll include it in the next update.
