### ISSUE TITLE
Is there an event fired when a child row is opened ?

### ISSUE THREAD

**Issue by ggglyke** [Mottie/tablesorter#1588]
Hi, I use table sorter with child rows. In each child row I want to have a comment feed in a div with limited height. I want this div to scroll to bottom to show the most recent comments. I tried to run the jquery fonction to scroll onload() but since the div is initially hidden it doesn't work. It works when I re-run the function when the child div is open but that's not what I want. So maybe if there is en event I can listen to and fire my scroll function when child row is shown ?

Thanks

**Comment by Mottie** [comment]
Hi @ggglyke!

There is no built-in code to show/hide child row content. In the code used to toggle the div, you can try to include a `setTimeout` set to how ever long the animation is set, or bind to the [`animationEnd` event](https://developer.mozilla.org/en-US/docs/Web/Events/animationend) provided by the browser.

**Comment by ggglyke** [comment]
Hi @Mottie 
Thanks for your reply. The trick with a `setTimeout` set to 1ms fired when toogle is clicked kind of worked so thank you. But I wonder if that is the cleanest way to do this ?
