### ISSUE TITLE
removing a column seems to keep the wrong thead data

### ISSUE THREAD

**Issue by corbosman** [Mottie/tablesorter#1589]
I have an app where I dynamically add/remove columns based on user input. This data is fetched from the server and, using vuejs, is added to data arrays.  I noticed that when I remove a column and tell tablesorter to re-init, it actually keeps the wrong thead data and I see a th field of the column I removed, but with the proper tbody. I made a mimimal fiddle to show the issue, just run and click on the button. That should remove the "animals" column, but the thead is wrong. The tbody is correct. 

https://jsfiddle.net/corbosman/eywraw8t/414116/

I have verified that the underlying table structure is correct. I even tried postponing the re-init after the click for 5 seconds to be absolutely sure that vue had updated the thead. If you remove the tablesorter methods you see that vue properly updates the tables.

**Comment by Mottie** [comment]
Hi @corbosman!

Hmm, I don't know Vue well enough to give you a solution... It appears that Vue is possibly confusing the header cells because they have been heavily modified by this plugin? If I destroy tablesorter immediately after initializing it, it leaves the header cells with all these extra attributes ([demo](https://jsfiddle.net/Mottie/srpmd3az/)):

```html
<th class="" tabindex="0" scope="col" role="columnheader" aria-disabled="true" unselectable="on" aria-sort="none" style="user-select: none;">Animals</th>
```

Maybe this is why it isn't working? Is there something like in React where you [assign a key to an element](https://reactjs.org/docs/lists-and-keys.html#basic-list-component)?

**Comment by corbosman** [comment]
Well, let's remove vue from the equation, at least where the table is concerned. A new fiddle that just uses jquery to update the table. Im merely using vue to handle the click event. So the click just removes the dom elements, and re-inits tablesorter, all through jquery.

https://jsfiddle.net/corbosman/km7yq4a9/5/

**Comment by Mottie** [comment]
Oh! When the destroy method is called, it "restores" the original header content... I think that's the culprit. If you rearrange the order or destroy, then remove the column it works - at least it worked in [this demo](https://jsfiddle.net/Mottie/km7yq4a9/10/) but it didn't work in Vue (I tried), so I'm guessing it might be a race condition in Vue.

```js
removeAnimals() {
	$('table').trigger('destroy');
	$('.animal').remove();
  this.init();
}
```

**Comment by corbosman** [comment]
It's definitely some interaction between vue's virtual dom and the real dom. I have to postpone for 2 dom redraw cycles in vue before I can call tablesorter. That seems to fix the issue for me. It's not a bug in tablesorter, but simply the fact that trying to have 2 JS libraries trying to manage the dom is probably a bad idea. If only there was a vue library that was as good as tablesorter :)
