### ISSUE TITLE
jquery selector for table id doesn't work

### ISSUE THREAD

**Issue by mcsmithers** [Mottie/tablesorter#1592]
I am trying to use the tablesorter and it works if I use the selector for table like `$("table").tablesorter({...})`, but for my table with the id of "table", `$("#table").tablesorter({...})` does not work.  

I would normally be fine with this, but there's other table-like elements in my DOM that get affected by all being selected if I call for table elements rather than a single one.

**Comment by Mottie** [comment]
Hi @mcsmithers!

I'm not sure why it isn't working for you, but it works in [this demo](https://jsfiddle.net/Mottie/bbxxomhx/1785/).

**Comment by mcsmithers** [comment]
Yeah, that's strange.  I built my stuff from a similar example though one that sorts the tbody elements.

```
        $(function () {

            //this doesn't work but the one ethat does has side effects
                $("#table").tablesorter({
                widgets: ['sortTbody', 'zebra'],
                widgetOptions: {
                    sortTbody_lockHead: true,
                    sortTbody_primaryRow: '.summary',
                    sortTbody_sortRows: true,

                    // include child row content while filtering the second demo table
                    filter_childRows: true
                }
            });    
        });
```

I can't think of why this might be.  It is a dynamically generated table from d3 nests.

**Comment by Mottie** [comment]
At the end of the `renderTable` function, add this ([demo](https://jsfiddle.net/Mottie/wt2snaky/3/)):

```js
$('#table').trigger('update');
```

**Comment by mcsmithers** [comment]
Ah, but the selector for `#table` itself when calling the table sorter
still seems to have issues.  I was hoping to get the table sorter to work
on only that specific table since it's affecting other UI elements like
datepickers.

**Comment by mcsmithers** [comment]
Cool :) . Getting closer.  It still seems like the original selector to instantiate tablesorter  for the specific table isn't working (`$('#table').tablesorter({...})`).  It needs to act on that specific table since otherwise it is affecting date pickers that are also tables as far as their element type.

**Comment by Mottie** [comment]
If the table is completely empty when that function is called, it will abort. Setting the `debug: true` option will show this message in the console:

> Stopping initialization! No table, thead or tbody `<table id=​"table">​​</table>​`

**Comment by mcsmithers** [comment]
Ah, interesting.  I got that behavior in my fiddle.  So that's what the issue is since that particular table is.  I see that happening in my fiddle with the debug statement added.  That's unexpected.

**Comment by mcsmithers** [comment]
Any suggestions maybe?  I don't seem to find anything that stands out too much on what I have versus similar projects using the library.

**Comment by Mottie** [comment]
Ok, I found the problem in this code:

```js
const table = d3.select('#table').append('table');
```

What that does is appends a table inside the original table

![](https://user-images.githubusercontent.com/136959/47588825-05458d00-d92d-11e8-8b74-cf5af3b5c55d.png)

Also, because the table is completely removed, I'd destroy the instance before re-initializing it ([demo](https://jsfiddle.net/Mottie/wt2snaky/48/)):

```js
// create new table
const table = d3.select('#table');

...

$('#table')
  .trigger("destroy", false)
  .tablesorter({
    widgets: ['sortTbody', 'zebra'],
    widgetOptions: {
      sortTbody_lockHead: true,
      sortTbody_primaryRow: '.summary',
      sortTbody_sortRows: true,

      // include child row content while filtering the second demo table
      filter_childRows: true
    }
  });

// toggle rows
$('#table').find('.summary').off('click').on('click', function () {
  // hide other rows when clicking on primary row
  $(this).nextUntil(".summary").toggleClass('filtered');
});

```

**Comment by Mottie** [comment]
Hmm, actually that toggle rows code should be changed to use delegation:

```js
$('#table').off('click').on('click', '.summary', function () {
  // hide other rows when clicking on primary row
  $(this).nextUntil(".summary").toggleClass('filtered');
});
```

Otherwise that may be adding a memory leak.

**Comment by mcsmithers** [comment]
Wow, this is brilliant, works like a charm.  Thank you so much for making something like this.  I had to go with d3 since other libraries wouldn't allow nesting like this and your tablesorter library really made something amazing become possible.
