### ISSUE TITLE
Pager plugin cdns for very simple pagination

### ISSUE THREAD

**Issue by mcsmithers** [Mottie/tablesorter#1594]
Hi,

I am trying to use the pager plugin with the following cdns:

` <script src="https://mottie.github.io/tablesorter/js/jquery.tablesorter.widgets.js"></script>`
  `<script src="https://mottie.github.io/tablesorter/addons/pager/jquery.tablesorter.pager.js"></script>`
`  <script src="https://mottie.github.io/tablesorter/js/jquery.tablesorter.widgets.css"></script>`

I am basing this off of what's on JS fiddle.  Is there any example of a fiddle that shows just the plugin and not the widget out there?  The docs (https://mottie.github.io/tablesorter/docs/example-pager.html) seem to suggest that a plugin is what I want since I am not using AJAX to populate the table.  I have an HTML table (same one for an issue I posted last week) that's working and can use some pagination, but I have been running into issues such as the pager options not working.  I don't need anything too fancy, just having 25, 50, and all entries.  Is there a really simple way we can create one with those CDNs?

Thanks!

**Comment by TheSin-** [comment]
using GitHub as a live repo is never a good idea!

**Comment by TheSin-** [comment]
https://stackoverflow.com/questions/17341122/link-and-execute-external-javascript-file-hosted-on-github

**Comment by Mottie** [comment]
Tablesorter is also hosted on CDNJS: https://cdnjs.com/libraries/jquery.tablesorter

There are a ton of demos on the main wiki page. Under [basic demos](https://github.com/Mottie/tablesorter/wiki#basic-demos) are jsFiddles that use both the pager addon and widget, with and without ajax.

**Comment by mcsmithers** [comment]
Thanks.  I tried out the demo at (https://codepen.io/TheSin/pen/vGnAa) and am trying to make something that resembles it.  Think this must be pretty close, but I can't quite seem to get it to work.  Lines 701-765 are where you can see I am trying to use the plugin and the widgets: [Here's where it is so far](https://jsfiddle.net/uprazvf8/).  It tells me that `.tablesorterPager is not a function`.

**Comment by TheSin-** [comment]
you can not apply table sorter to a div.  I changed the init on #table table, to just #table and I converted #table form a div to a table.

That is a good start to get table sorter loading for you at least.

**Comment by mcsmithers** [comment]
Thank you, I fixed that.  I think I fixed the worst of it now by using the main example.  [This](https://jsfiddle.net/mcsmitheslc/tLwvck64/76/) is the latest.  It no longer sorts, but at least there's no errors.

**Comment by Mottie** [comment]
Oh, I totally forgot... the pager is built to only work with a single `tbody` because it's already complicated enough having multiple tbodies sort. If you *must* include the pager, I would suggest dropping the multiple tbodies.

To get the demo to work, change the `$('#table table')` selector to `$('#table')` since the table is the element with that ID.

**Comment by mcsmithers** [comment]
Ah, I see.  I'll have to keep the separate tbodies since it's supposed to be nested like that.  Dang, if the plugin for paging ever is able to handle those too someday, that would be awesome.

Thank you so much for your help!  I love this project and will have to use it for more D3 tables.
