### ISSUE TITLE
Add option to filter-select dropdown, not replace

### ISSUE THREAD

**Issue by helikopterodaktyl** [Mottie/tablesorter#1597]
I am using select filters. In general they work fine, however I would like to customize the fields.

Obviously I can use this https://mottie.github.io/tablesorter/docs/example-widget-filter-custom.html , the "Custom Select ("City" or "Total" column)" section almost does what I need. Comment says "// Add these options to the select dropdown (regex example)". But there's the problem, it doesn't add these options to the select dropdown, it replaces the dropdown values with specified ones.

What I'd like to do, is have the default dropdown values, and add a single custom one. Is that possible?

**Comment by Mottie** [comment]
Hi @helikopterodaktyl!

The [`filter_selectSource` option](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource) will allow you to adapt or append custom options ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1830/)):

```js
$(function() {
  $("table").tablesorter({
    theme: 'blue',
    widthFixed: true,
    widgets: ["zebra", "filter"],
    widgetOptions: {
      filter_selectSource: {
        0: function(table, column, onlyAvail) {
          // get an array of all table cell contents for a table column
          var array = $.tablesorter.filter.getOptions(table, column, onlyAvail);
          array.push('_Custom');
          return array;
        }
      }
    }
  });
});
```

**Comment by helikopterodaktyl** [comment]
Wow! Thanks for the quick reply! But in this case, I can't set a custom filter function for _Custom anymore? I mean, if it's not in the table values, there's no use filtering for the exact match with it :(

**Comment by Mottie** [comment]
Take a look at the documentation, there's an example where you can assign a regular expression as a value.

**Comment by helikopterodaktyl** [comment]
Ahh ok, I used filter_functions on the newly created value and it works. Thanks!
