### ISSUE TITLE
Strange sorting on particular column

### ISSUE THREAD

**Issue by mcsmithers** [Mottie/tablesorter#1599]
Loving all the features of the tablesorter.  I noticed a strange issue on a specific column in my project.  I am not sure if it's something to do with my data or not, but here's a recording of how it shows up: https://share.vidyard.com/watch/cAova83KeyJeQAEEMwYaPf?.  As you can see, the other column, sort when clicked, but my "Revenue" one.  The aria-label changes each time it's clicked, so that's a good sign.

**Comment by mcsmithers** [comment]
Hey guys, I fixed it on my own quite accidentally.  Thank you though for making this wonderful tool.

**Comment by Mottie** [comment]
It looked like it might have been due to an unclosed tag, `</td>` maybe? I'm glad you figured it out!

Next time if you have a quick question, you can jump on IRC or Gitter (which I hardly use any more), or jump on Slack - https://tablesorter.slack.com (I just set this up)

**Comment by mcsmithers** [comment]
Very cool!  I'll sign up once it's open for invites.  I am slowly converting people over to this tool with all the freedom it offers.

**Comment by Mottie** [comment]
I posed this link in the main readme: [Slack](https://join.slack.com/t/tablesorter/shared_invite/enQtNDc2NTczODg0NjkzLWRmYzE2NjIzNjM2ZWE1NzkyNzFkNjM4NjY0OTIyOTM3NDRmNWRhMjgxMTk5MjFhNzM3NWIzMWU1ZTc1NTZlOGE).

Please let me know if it doesn't work.

**Comment by mcsmithers** [comment]
Perfect!  Works perfectly
