### ISSUE TITLE
Missing Change log of  2.31.1 

### ISSUE THREAD

**Issue by AviHafner** [Mottie/tablesorter#1607]
hi 

What are the changes in version  2.31.1  ?

**Comment by Mottie** [comment]
Oops sorry! I added them to the readme, but forgot to copy them over to the wiki

https://github.com/Mottie/tablesorter#version-2311-2018-11-20

**Comment by Mottie** [comment]
Fixed https://github.com/Mottie/tablesorter/wiki/Changes#version-2311-2018-11-20
