### ISSUE TITLE
filter-select does not work with pager

### ISSUE THREAD

**Issue by jh-deleon** [Mottie/tablesorter#1611]
Hi,
i use the pager plugin and load rows through ajax. i also need to use filter-select class in the th. when i try to select, only the "All' option is there that comes from the data-placeholder. is this expected or am i missing something?

Thanks!

**Comment by Mottie** [comment]
Hi @jh-deleon!

After the rows are added, make sure to update tablesorter's internal cache by triggering an [`update`](https://mottie.github.io/tablesorter/docs/#update). If that still doesn't work, set the [`filter_selectSource` option](https://mottie.github.io/tablesorter/docs/#widget-filter-selectsource) with the desired select values.

**Comment by jh-deleon** [comment]
Hi @Mottie,
Thanks, 'update' worked. Where would you recommend to place the trigger? Is it after initializing the tablesorter or a function somewhere in pagerOptions?
