### ISSUE TITLE
'addRows' event  breaks the sorting functionality of tablesorter

### ISSUE THREAD

**Issue by ayoubde** [Mottie/tablesorter#1613]
Hello, 
I am appending rows to tablesorter by using Ajax call here is my code:

` $.ajax({
            type: "GET",
            url: ajaxURL,
            contentType: "application/json; charset=utf-8",
            datatype: "ajax",
success: function (data) {
           
                $("#myTable tbody").children().remove();
               
                $row = $(data),
                resort = true;
                $('#myTableTable')
                    .find('tbody').append($row)
                    .trigger('addRows', [$row, resort]);
                return false;}});`

The code below breaks the sorting functionality of the table sorter with the following error message: "Uncaught TypeError: Cannot read property 'length' of undefined"
Any suggestions?! Thanks!

**Comment by ayoubde** [comment]
Hi @Mottie, the data passed from the ajax call has a set of rows that start with <tr> and end with </tr>
I can't see any missing <tr>.

**Comment by Mottie** [comment]
Please make sure `data` contains what is expected... I wonder if that should be `data.data`, but that's just a guess.

**Comment by ayoubde** [comment]
That was white spaces between the rows. I called a partial view via Ajax that had space before and after the rows. I cleaned it up the spaces and the error disappeared.
