### ISSUE TITLE
How to apply filters on a nested tablesorter?

### ISSUE THREAD

**Issue by ayoubde** [Mottie/tablesorter#1616]
I have tablesorter  with a parent/child rows when the user expand the parent row I display the child row as nested tablesorter but the nested tablesorter doesn't have filters. I enabled filters but they didn't show up.

`
$(".nestedTablesorter")
                    .tablesorter({
                        theme: 'bootstrap',
                        widthFixed: true,
                        headerTemplate: '{content} {icon}',
                        widgets: ["uitheme", "filter", "columns", "zebra"],
                        widgetOptions:
                        {
                            zebra: ["even", "odd"],
                            columns: ["primary", "secondary", "tertiary"],
                            filter_columnFilters: true,
                            filter_reset: ".reset",
                            filter_cssFilter: "form-control"
                        },
                        cssChildRow: "tablesorter-childRow"
                    });
`

![tablesorterissue](https://user-images.githubusercontent.com/18560035/50996711-a685bd80-14f0-11e9-8689-480f84f76f09.PNG)

**Comment by Mottie** [comment]
Hi @ayoubde!

Would you please modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/) to show the problem?

**Comment by ayoubde** [comment]
Hi @Mottie, 
I fixed it. On the Toggle click event I (destroy & Initiate) tablesorter and that solved the problem.
`$('.tablesorter').delegate('.toggle', 'click', function () {$(".nestedTablesorter").trigger("destroy");
        $(".nestedTablesorter") .tablesorter(...); });`

**Comment by ayoubde** [comment]
I am going to close that issue. Thanks!
