### ISSUE TITLE
"filter-select" class produces JS error : Cannot read property 'text' of undefined

### ISSUE THREAD

**Issue by ayoubde** [Mottie/tablesorter#1622]
I want to make a filter as dropdownlist to filter data based on a selected value. 
I added "filter-select" class to the header of my table sorter but I got the follwing error
     "**Uncaught TypeError: Cannot read property 'text' of undefined**"
here is my example 
`<th class="filter-select" data-placeholder="Choose a gende">Gender</th>`

**Comment by Mottie** [comment]
Hi @ayoubde!

Without seeing an example, I can only guess that the HTML isn't valid.

**Comment by ayoubde** [comment]
@Mottie  yes, it's an HTML issue (HTML is not vallid). I will close that issue.
