### ISSUE TITLE
stickyheader not aligned when tbl is using margin:auto

### ISSUE THREAD

**Issue by jh-deleon** [Mottie/tablesorter#1624]
Hi,

I tried checking available options (attachto config or -sticky css) on how to center the table including the stickyheader however I am not getting the expected result. Do you know how to do this by maybe just applying #tbl_id-sticky {margin:auto}
Thanks!

**Comment by jh-deleon** [comment]
Hi,

I actually figured it out using the attachto config.
<div style='text-align: center'>
  <div class='wrapper'> 
    <table>
    ...
    </table>
  </div>
</div>
I'm still curious if there's a better way to do it. :)

**Comment by Mottie** [comment]
Hi @jh-deleon!

I think that the `wrapper` might have been missing a `position: relative` css setting.

**Comment by jh-deleon** [comment]
Hi @Mottie ,

Thanks for the response.
Yes, I used the css applied to wrapper in the documentation. The problem I was encountering is not actually related to tablesorter as I was trying to make the div follow the width of the child table so that it will appear to be centered.
