### ISSUE TITLE
The table thead can not selected

### ISSUE THREAD

**Issue by xxfaxy** [Mottie/tablesorter#1625]
We often select the table and paste into Excel for data analysis,But now The table thead can not selected

![2019-01-18 11-35-15](https://user-images.githubusercontent.com/3325895/51363938-2f19e480-1b15-11e9-9594-b77a5e7c2f70.png)

**Comment by Mottie** [comment]
Hi @xxfaxy!

The [`cancelSelection` option](https://mottie.github.io/tablesorter/docs/#cancelselection) is set to `true` by default. When set, it prevents selection in the header which may occur if you're clicking and dragging on the header or resizing the headers with the widget. Set this option to false to allow text selection ([demo](https://jsfiddle.net/Mottie/bbxxomhx/1961/)):

```js
$(function() {
  $('table').tablesorter({
    theme: 'blue',
    cancelSelection: false
  });
});
```
