### ISSUE TITLE
filter widget in filter-exact mode not working correctly with texts containing minus symbol

### ISSUE THREAD

**Issue by pakud** [Mottie/tablesorter#1626]
the filter widget for column configured with class="filter-select filter-exact" gives an empty result when i select it to include only rows containing this combination of characters: [space][minus][space]

you can see it in http://jsfiddle.net/4terfLn0/ - for the column cf1 select filter 'bb - bb'

instead of getting a single row matching that criteria no rows are displayed.

i can reproduce this issue under 2.31.1 and with a trunk version

thanks a lot for all your work on the tablesorter!

**Comment by Mottie** [comment]
Hi @pakud!

It sounds like the range filter is interfering with your results. See #1220 for a solution.

**Comment by Mottie** [comment]
I've added a FAQ - https://github.com/Mottie/tablesorter/wiki/FAQ#dashes-in-content
