### ISSUE TITLE
"pagerComplete" event does not get executed if filters are unchanged

### ISSUE THREAD

**Issue by larsbonczek** [Mottie/tablesorter#1631]
When I press enter inside a filter input, the search gets executed even if the filters have not changed.

See here
https://github.com/Mottie/tablesorter/blob/fa56764ad5630ed3ab9da4a30fdb8dd34bfbaf1f/js/jquery.tablesorter.widgets.js#L1275
and here (`filter === false` here because the event type was 'keypress')
https://github.com/Mottie/tablesorter/blob/fa56764ad5630ed3ab9da4a30fdb8dd34bfbaf1f/js/jquery.tablesorter.widgets.js#L1366-L1367

The "filterStart" event gets fired here
https://github.com/Mottie/tablesorter/blob/fa56764ad5630ed3ab9da4a30fdb8dd34bfbaf1f/js/jquery.tablesorter.widgets.js#L1382
but the "pagerComplete" event never gets fired for some reason: (The `false` means that the "pagerComplete" event shouldn't be fired - but why?)
https://github.com/Mottie/tablesorter/blob/fa56764ad5630ed3ab9da4a30fdb8dd34bfbaf1f/js/widgets/widget-pager.js#L279

This causes my loading animation to be displayed on "filterStart", but never to get removed.

**EDIT** It wasn't the "filterEnd" event that didn't get fired as I first thought but the "pagerComplete" event.

**Comment by Mottie** [comment]
Hi @larsbonczek!

Thanks for investigating this problem! I apologize for not responding sooner. I would greatly appreciate a PR with a fix. Maybe prevent setting the `filter` to `false` if the last key was an enter? That way line 1366 would stop the flow.

**Comment by larsbonczek** [comment]
Is it okay if I submit a pull request without having really tested it? I still have my solution from a month ago somewhere, but I don't have time to go back and test it again right now.

**Comment by Mottie** [comment]
Thanks again!
