### ISSUE TITLE
Sort using <time> element

### ISSUE THREAD

**Issue by malcomio** [Mottie/tablesorter#1657]
As far as I can see, it isn't possible to sort tables which contain `<time>` elements, without.

Here's an example Codepen: https://codepen.io/malcomio/pen/eorvJB

Each cell in the date column includes markup like this:
```
<time datetime="2019-04-22">Monday 22nd April</time>
```

However, the `<time>` element seems to be ignored, and only the text inside it is used for sorting.

Am I missing something in the documentation?
https://mottie.github.io/tablesorter/docs/example-option-date-format.html doesn't seem to mention it.

**Comment by Mottie** [comment]
Hi @malcomio!

Use the [`textExtraction` function](https://mottie.github.io/tablesorter/docs/#textextraction) to get the `datetime` attribute ([demo](https://codepen.io/Mottie/pen/MRGOwL)):

```js
$(function() {
  $("table").tablesorter({
    dateformat: "yyyymmdd",
    textExtraction: {
      0: function(node, table, cellIndex) {
        return $(node).find('time').attr('datetime');
      }
    }
  });
});
```

**Comment by malcomio** [comment]
nice - thanks :)
