### ISSUE TITLE
ColumnSelector select all checkbox not working properly

### ISSUE THREAD

**Issue by RajuTicvic** [Mottie/tablesorter#1682]
@Mottie !
Here i attached my code as jsfiddle link,
the problem is when i click the **auto** in column button the address column has disappeared, but the child is added in end of the column. 
Can you fix it?
In scroller : https://jsfiddle.net/rajuticvic/kqxgwaor/
In stickyHeader : http://jsfiddle.net/rajuticvic/05d2ne9h/

**Comment by Mottie** [comment]
Hi @RajuTicvic!

Hmm, that is weird. I'll take a look.

**Comment by RajuTicvic** [comment]
@Mottie!
I have almost finished my project using your plugin,
now risky to switch to another plugin. so please resolve the bug please let me know.

**Comment by Mottie** [comment]
Try the updated [columnSelector widget](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-columnSelector.js). I haven't pushed a new release, so it's only available in the master branch for now.

**Comment by RajuTicvic** [comment]
@Mottie thank you so much

**Comment by Mottie** [comment]
Sorry for the super-long delay! Version 2.31.2 is now available.
