### ISSUE TITLE
"Check all" Checkbox in thead doesn't work with stickyHeaders

### ISSUE THREAD

**Issue by gerdos** [Mottie/tablesorter#1686]
There is a closed issue with the very same title marked as solved, however the issue still persists.

Here is a JSFiddle demo about it: https://jsfiddle.net/u0whny65/

Also the sticky header acts weird, but that does not happen on my local machine.

**Comment by Mottie** [comment]
Hi @gerdos!

Two things are missing ([updated demo](https://jsfiddle.net/Mottie/L6815mgf/2/)):

1. The parser input select script.
2. CSS to make the wrapper have a position: relative.

Not really missing, but get rid of the `onchange="select_all()"` in the header input. The header is duplicated, so the id isn't unique anymore. And that code will interfere with the parser script.
