### ISSUE TITLE
Can't get sort icons to appear

### ISSUE THREAD

**Issue by delawago** [Mottie/tablesorter#1696]
I downloaded Tablesorter 2.31.1 through NuGet in VS.  I can get the sort to work on the table but I cannot see the sort icon.  I have tried looking at others problems with this and can't find any solutions that work for me.  Any help would be appreciated.

	<meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Table Test</title>
    <link rel="stylesheet" href="Content/jquery.mobile-1.3.2.min.css" />
    <script src="Scripts/jquery-1.9.1.min.js"></script>
    <script src="Scripts/jquery.mobile-1.3.2.min.js"></script>
    <script type="text/javascript" src="Scripts/tablesorter/jquery.tablesorter.combined.js"></script>
   
  
    <script>
        $(function () {
            $("#myTable").tablesorter({
                theme: 'dropbox',
                cssIcon: 'tablesorter-icon',
                headerTemplate: '{content}{icon}',
                widgets: ['uitheme']
            });
        });
    </script>
       

    <table id="myTable" class="tablesorter">
        <thead>
            <tr>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Email</th>
                <th>Due</th>
                <th>Web Site</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>Smith</td>
                <td>John</td>
                <td>jsmith@gmail.com</td>
                <td>$50.00</td>
                <td>http://www.jsmith.com</td>
            </tr>
            <tr>
                <td>Bach</td>
                <td>Frank</td>
                <td>fbach@yahoo.com</td>
                <td>$50.00</td>
                <td>http://www.frank.com</td>
            </tr>
            <tr>
                <td>Doe</td>
                <td>Jason</td>
                <td>jdoe@hotmail.com</td>
                <td>$100.00</td>
                <td>http://www.jdoe.com</td>
            </tr>
            <tr>
                <td>Conway</td>
                <td>Tim</td>
                <td>tconway@earthlink.net</td>
                <td>$50.00</td>
                <td>http://www.timconway.com</td>
            </tr>
        </tbody>
    </table>

**Comment by Mottie** [comment]
Hi @delawago!

I tried, but couldn't get jQuery mobile to work with the table after 15 minutes of trying. I don't like to give up, but honestly that library hasn't been updated in about 2 years; I think there are better solutions.

The dropbox theme probably isn't being applied because the dropbox style wasn't loaded - [demo](https://jsfiddle.net/Mottie/bbxxomhx/2023/).

**Comment by delawago** [comment]
I had to add my own css.  Found from another post.
.tablesorter-header {
    background-image: url(data:image/gif;base64,R0lGODlhFQAJAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAkAAAIXjI+AywnaYnhUMoqt3gZXPmVg94yJVQAAOw==);
    background-position: center right;
    background-repeat: no-repeat;
    cursor: pointer;
    white-space: normal;
    padding: 4px 20px 4px 4px;
}
.tablesorter-headerAsc {
    background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjI8Bya2wnINUMopZAQA7);
}
.tablesorter-headerDesc {
    background-image: url(data:image/gif;base64,R0lGODlhFQAEAIAAACMtMP///yH5BAEAAAEALAAAAAAVAAQAAAINjB+gC+jP2ptn0WskLQA7);
}
.tablesorter .sorter-false {
    background-image: none;
    cursor: default;
    padding: 4px;
}
