### ISSUE TITLE
Bootstrap 4 is not in beta anymore

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#1706]
…as claimed at https://mottie.github.io/tablesorter/docs/example-option-theme-bootstrap-v4.html

In fact there is already Bootstrap 4.4 and Boostrap 5 is also already under its way.

**Comment by Mottie** [comment]
Hi @Herst!

Thanks, I'll update Bootstrap & remove the beta tags in this next release.

**Comment by Mottie** [comment]
Done!
