### ISSUE TITLE
Multiple <thead> Elements - Ignore Some

### ISSUE THREAD

**Issue by own3mall** [Mottie/tablesorter#1718]
I've got a `<thead>` row that is using a `position: sticky` CSS style rule.  How do I get tablesorter to completely ignore this thead section and do nothing to it?  Right now, the click event for the elements within this thead row are not firing because of tablesorter's `stopPropagation()` code.

Here's an example:

https://jsfiddle.net/oza7uv5w/

Scroll down the table.  Notice how the "GO" button is always visible due to sticky positioning?  Click on the "GO" button.  Nothing happens.  Expected behavior is for this button's events to trigger.  How do I get tablesorter to only init the second `<thead>` section?

**Comment by Mottie** [comment]
Hi @own3mall!

First off, it isn't valid HTML to have a table with more than one `thead`.

If you want to have tablesorter ignore a row in the header, add the "tablesorter-ignoreRow" class to it. This class name can be modified by the [`cssIgnoreRow` option](https://mottie.github.io/tablesorter/docs/#cssignorerow).

Here is an [updated demo](https://jsfiddle.net/Mottie/4yjurn0t/4/):

```html
<table class="sort">
  <thead class="ignoreTableSorter">
    <tr class="tablesorter-ignoreRow sticky-position">
      <th colspan="3" class="sorter-false"><input class="test" type="button" value="GO"></th>
    </tr>
    <tr class="sticky-position2">
      <th>ID</th>
      <th>Name</th>
      <th>Day</th>
    </tr>
  </thead>
  <!-- ... -->
</table>
```

**Comment by own3mall** [comment]
@Mottie Didn't know that.  Figured it was valid since you have multiple `<tbody>`. 

I will rework my HTML.  Thanks for the info!

**Comment by Mottie** [comment]
You can have multiple `<tbody>`s

The wording is kind of weird, but here are the references:

[`<tbody>`](https://html.spec.whatwg.org/multipage/tables.html#the-tbody-element)
> As a child of a table element, ... but only if there are no **tr** elements that are children of the table element.

[`<thead>`](https://html.spec.whatwg.org/multipage/tables.html#the-thead-element) 
> As a child of a table element, ... but only if there are no other **thead** elements that are children of the table element.

[`<tfoot>`](https://html.spec.whatwg.org/multipage/tables.html#the-tfoot-element)
> As a child of a table element, ... but only if there are no other **tfoot** elements that are children of the table element.
