### ISSUE TITLE
Tablesorter: hide certain filter boxes when on mobile phones

### ISSUE THREAD

**Issue by ravenlost** [Mottie/tablesorter#1719]
Hi folks,

I'm using jQuery's Tablesorter v-2.31.3.

So essentially, I have a large table that doesn't quite fit nicely on mobile devices (too much columns of data). I've decided to hide columns using a CSS class I created "hideme" :

`<style> 
/* CSS Specific for phones, tablets, etc.  */
@media only screen and (max-width: 767.98px){
  .hidemeOnPhones {
    display: none;
  }
}
</style>`

I've added class="hidemeOnPhones" to all of my table's TD's and TH's I don't want showing up when viewing the page on smartphones...

That works as planned.HOWEVER, my page is still somewhat broken. For one thing, it seems like the filter boxes for all columns I've hidden still exists, as if the tablesorter still counted them in... I get this:

![tablesorter01](https://user-images.githubusercontent.com/62449156/77209292-39ab8180-6afe-11ea-95d2-492a01522b18.png)

So, I also tried appending this 'hidemeOnPhones' class to my last 4 columns in my filter_cssFilter:

`filter_cssFilter: [
  'form-control form-control-sm',
  'form-control form-control-sm',
  'custom-select custom-select-sm', 
  'form-control form-control-sm',
  'form-control form-control-sm',
  'form-control form-control-sm hidemeOnPhones',
  'form-control form-control-sm hidemeOnPhones',
  'form-control form-control-sm hidemeOnPhones',
  'form-control form-control-sm hidemeOnPhones'
]`

Now, I get this: 

![tablesorter02](https://user-images.githubusercontent.com/62449156/77209400-77a8a580-6afe-11ea-94fe-bfaf399dd7d5.png)

The filter's last 4 input boxes don't show up, but still, I have a spanning problem here...

Yet, I don't think putting 'hidemeOnPhones' on my last 4 entries of filter_cssFilter is the best thing... 

Note that I'm also using the tablersorter.Pager. This pager is in the table's footer:
`<th colspan="100%" class="ts-pager">... </th>`

I've noticed that if I force my pager's row with a colspan="5" (number of columns shown in phones), then it's perfect for smartphones, but of course breaks on desktops : 

![tablesorter03](https://user-images.githubusercontent.com/62449156/77209455-960ea100-6afe-11ea-9cd9-229263423b8c.png)

I've tried to also add a custom CSS class in my pager's cell that would take care of changing colspan, but whatever I found doesn't change my colspan at all, regardless which browsers...

`<style>
@media only screen and (max-width: 767.98px){
  .setPagerColSpan {
    column-span: 5; /* W3C */
    -webkit-column-span: 5; /* Safari & Chrome */
    -moz-column-span: 5; /* Firefox */
    -ms-column-span: 5; /* Internet Explorer */
    -o-column-span: 5; /* Opera */
   }
}
</style>`

So, wondering if there's a way I could do this properly with what Tablesorter has to offer?

Thanks for you time and help!

Cheers. Pat

**Comment by Mottie** [comment]
Hi @ravenlost!

Try the [columnSelector widget](https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html). It automatically adjusts colspans when the screen narrows.

Sadly, you can't adjust table colspans using CSS; percentages don't work either. The CSS `column-span` definitions only applies to block elements, not table elements.

**Comment by ravenlost** [comment]
Hmm thought it would be it, but I can't even get it to work properly.... I based myself on the exemple in [https://mottie.github.io/tablesorter/docs/example-widget-column-selector.html](url) (CSS only popup), except I'm not using the DIV Column selector button (I just want them all to show/hide based on screen size).

My table's header is like so:

&lt;thead class="pt-2">
&nbsp;&nbsp;&lt;tr>
&nbsp;&nbsp;&nbsp;&lt;th data-sorter="false" data-filter="false" class="columnSelector-disable">&nbsp;&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="critical">ID&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="5" class="">IS_ADMIN&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="3" class="">ACTIF&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="critical">USERNAME&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="2">FNAME&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="2">LNAME&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="4" class="">EMAIL&lt;/th>
&nbsp;&nbsp;&nbsp;&lt;th scope="col" data-priority="6" class="">MODIFIED_DATE&lt;/th>
&nbsp;&lt;/tr>
&lt;/thead>

Yet, all columns still show up when I resize my screen, thus having me to scroll left/right... 

Not sure what I'm doing wrong... can I share my JS code perhaps?
[http://corbeauperdu.ddns.net/prestadesk/js/prestadesk.tablesorter.main.js](url)

If you have time and will :)

Many thanks again for your help!
Pat

**Comment by Mottie** [comment]
Would you please [update this demo](https://jsfiddle.net/Mottie/mcn8o3yu/) to show the problem. Having the HTML, JS & CSS all together would make troubleshooting so much easier.

**Comment by ravenlost** [comment]
Arghhh turns out I needed to also:

> <script src="js/jquery-tablesorter/widgets/widget-columnSelector.min.js"></script>

Since I didn't need to do this for the columns, or filters widget, I figured it was the same for the columnSelector widget! This is confusing... :(

Now, it works as planned. However, I still decided I wanted the "choose columns" buttons... Doing so, I have, yet another problem. The table headers seem to show through the dropdown column selector... see:

![Screenshot_2020-03-22_13-41-26](https://user-images.githubusercontent.com/62449156/77249812-f9eeb200-6c43-11ea-8885-00e4c6d0b82c.png)

And even more importantly, I have a bunch of empty column checkboxes (a lot!)... Looking in Chrome's developper tool, I do have 1 error saying:


> jquery.tablesorter.combined.min.js:4 Invalid or incorrect number of columns in the THEAD or TFOOT; expected 100, but found 9 columns


I haven't counted the checkboxes shown, but I'm guessing it'll be 100.... 

Any ideas for me ? Thanks again a million :)

**Comment by ravenlost** [comment]
UPDATE: turns out I can't use colspan="100%" in my footer's cells! I forced it back to colspan="9" and the multiple checkboxes are gone. Now the count is right, but I still have the problem with the header's going through the column selection box...

**Comment by Mottie** [comment]
Oh, I'm glad you've made progress!

It sounds like you need a `z-index` added to the column selector:

```css
.columnSelector {
  width: 120px;
  position: absolute;
  top: 30px;
  padding: 10px;
  background: #fff;
  border: #99bfe6 1px solid;
  border-radius: 5px;
  z-index: 1;
}
```

**Comment by ravenlost** [comment]
You're awesome !!! Fix my issues :) It's working beautifully :))

Can I bother you with one last question ?

How could I make it so that my button stays on a different color when AUTO is not selected, and I've clicked back on my button to close the menu (a way of telling me something else, or nothing at all then AUTO is selected...). Otherwise, knowing that my filter actually still searches all columns, even the hidden ones, I need to be able to tell user's there's a "column filter" on...

Cheers!

**Comment by TheSin-** [comment]
like in this example?

https://codepen.io/TheSin/pen/xkgKj

**Comment by Mottie** [comment]
Oh, I was thinking they meant this - [demo](https://jsfiddle.net/Mottie/gy9sfubz/)

To add:
- Add "auto-on" class to button

  ```html
  <label class="columnSelectorButton auto-on" for="colSelect1">Column</label>
  ```

- Add css class. It's got a pretty high specificity because I added it at the top of the demo page

  ```css
  .columnSelectorWrapper #colSelect1 + label.auto-on {
    background-color: green;
  }
  ```

- Then this bit of JS

  ```js
  $('.custom-popup, initialized').on('columnUpdate', function() {
  	var isAutoOn = $('#columnSelector input[data-column="auto"]').prop('checked');
    console.log('auto on?', isAutoOn)
    $('.columnSelectorButton').toggleClass('auto-on', isAutoOn);
  });
  ```

**Comment by TheSin-** [comment]
Yup that’s the same thing

**Comment by ravenlost** [comment]
No, I mean the actual "Select Columns" button:

![01](https://user-images.githubusercontent.com/62449156/77253412-4fce5480-6c5a-11ea-927f-f3a7f04a4b05.png)

When I click the the button, it changes color; then I need to reclick it to close down the column selection... I'd like it to stay a different color when I've *unchecked* Auto in it...

**Comment by Mottie** [comment]
That's what I did in the demo I shared.

**Comment by ravenlost** [comment]
Ahh sorry I missed it... looking at it right no

**Comment by TheSin-** [comment]
The demo I shared also changes if columns are in manual

**Comment by ravenlost** [comment]
Alright, I made it work for a few tweaks of your last demo :))

Now, my button remains grey, unless AUTO is unchecked! 

Yet, I was just trying to make it so that it still "temporarily" puts it to the blue color, while the menu is opened...  and when closing the menu, go back to grey if AUTO is on...

I figured I needed to create a custom class like:

`.columnSelectorButtonClicked { background-color: #5797d7; }`

and I added an id="columnSelectorButton" to my label:
`<label class="columnSelectorButton auto-on" for="colSelect1" id="columnSelectorButton">Select Columns</label>`

and finally, in my JS, try to do something like:

> $('.columnSelectorButton').click(function() {
       &nbsp;&nbsp;&nbsp;&nbsp;var element = document.getElementById("columnSelectorButton");
       &nbsp;&nbsp;&nbsp;&nbsp;element.classList.add("columnSelectorButtonClicked");
}

but it didn't work... I've looked into:
element.classList.toggle("columnSelectorButtonUnClicked");
element.toggleClass("columnSelectorButtonClicked");

I just can't quite figure it out yet... I'm no good with JS... :(

**Comment by Mottie** [comment]
That might only require a css modification ([demo](https://jsfiddle.net/Mottie/gy9sfubz/6/))

```css
.columnSelectorWrapper #colSelect1:not(:checked) + label.auto-on {
  background-color: grey;
}
```

**Comment by ravenlost** [comment]
Thank you so much !! Still had to tweak some things, but youve put me on the right track and now it's just how I wanted :)) 

Now to get that output widget working to just download the full table in CSV format and I'm done... :)) Gonna go do some reading... Cheers again!

**Comment by Mottie** [comment]
Here's another super simplified demo of the output widget - [demo](https://jsfiddle.net/Mottie/yL1qon7e/).

All of these demos are on the [home wiki page](https://github.com/Mottie/tablesorter/wiki).

**Note** most of the demos are set to use jQuery edge, which is breaking the demos since it's removing some vital functions. Set the jQuery version to 3.4.1 or lower to make it work again.

**Comment by ravenlost** [comment]
Awesome. all is working fine now...

http://corbeauperdu.ddns.net/prestadesk/templates/prestadesk_data_list.php

Just how I wanted it to be. We can close this case I guess. Many many thanks :)
