### ISSUE TITLE
Weird behaviour with ajax pager

### ISSUE THREAD

**Issue by matheusfausinoEquals** [Mottie/tablesorter#1723]
Hi,

I'm facing a weird behaviour of tablesorter with pager and ajax. The expected behaviour is tablesorter let the sort and pagination on server side and only call the ajax when the user change the sort direction or the result page.
But the tablesorter is calling ajax request only in one direction( "ASC") of sorter (For the pagination eveything is ok). While I was debugging the source code of tablesorter (both tablesorter.js and tablesorterpager.js), I figured out that the trigger for "sortEnd" is being called for both directions, but the handler method registered in pager.js is not called by the jquery when the direction is "DESC".

Any help would be great!

If is needed more informations let me know.

tablesorter version: 2.27.6
jquery version: 1.7.1

**Comment by Mottie** [comment]
Hi @matheusfausinoEquals!

Would you please share the code you're using to initialize tablesorter & the pager?

**Comment by matheusfausinoEquals** [comment]
Hi, @Mottie.

After investigations here, I figured that some team member changed the version of tablesorter.js but not the pager.js and this is the cause of the weird behaviour mentionated here. The fix was upgrade both components to same version.

Sorry for make you waste time and thank you for your attention.
