### ISSUE TITLE
Sticky Headers and Filter Row

### ISSUE THREAD

**Issue by Zero2Cool** [Mottie/tablesorter#1725]
Is it possible to hide the filter row when the duplicate table header becomes visible?

**Comment by Mottie** [comment]
Yes

**Comment by Zero2Cool** [comment]
> Yes, here's a [demo](https://jsfiddle.net/Mottie/f36416oy/117/)
> 
> ```css
> .tablesorter-stickyHeader .tablesorter-filter-row {
>   display: none;
> }
> ```

This will retain the original header with the filters visible and functioning, correct?

**Comment by Mottie** [comment]
That css will only hide the filter row in the sticky header.

**Comment by Mottie** [comment]
All the filter inputs will remain functional, even the hidden ones.

**Comment by Zero2Cool** [comment]
Perfect, thank you!
