### ISSUE TITLE
table sorting not working if we add timezone. date format dateFormat:'MMM dd HH:mm:ss z yyyy'

### ISSUE THREAD

**Issue by vijaybokka** [Mottie/tablesorter#1728]
if we add timezone (z,zz) then it's sorting the column by alphabetical order . it should sort by date .

**Comment by Mottie** [comment]
Hi @vijaybokka!

The built-in [`dateFormat` option](https://mottie.github.io/tablesorter/docs/#dateformat) only accepts three "basic" formats ([source](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L2792-L2805)):

- `"mmddyyyy"` (default)
- `"ddmmyyyy"`
- `"yyyymmdd"`

If you need a specific date format, try:
- Creating a specific parser,
- Use the [`date-parser`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date.js) which works with either sugar or date.js
- Or, add a `data-` attribute to each cell which contains a date format that will work with the existing parser(s).

**Comment by vijaybokka** [comment]
Thank you.
