### ISSUE TITLE
Install via Composer only the subfolder /dist with JS and CSS files

### ISSUE THREAD

**Issue by pedro-mendonca** [Mottie/tablesorter#1731]
In the documentation you don't have any info on installing Tablesorter via composer, only via npm, it would be awesome to add it.
Also, installing via Composer installs the full repo, would be great to add only the /dist subfolders (js and css) as it happens with the npm install.

Thanks for your great software :)

Related to #1355

**Comment by Mottie** [comment]
Hi @pedro-mendonca!

Thanks, I'll look into adding instruction & fixing what gets included. I may not get to this until the weekend (or later), since I've been super busy. Any help would be appreciated! 😸

**Comment by pedro-mendonca** [comment]
@Mottie I think that it needs to have some export-ignore settings in the .gitattributes file.
Can you please test it?

**Comment by pedro-mendonca** [comment]
I've followed the example of the npm installed package, kept only these:
- `/dist`
- `CHANGELOG.md`
- `README.md`
