### ISSUE TITLE
Do not sort first row?

### ISSUE THREAD

**Issue by hazcod** [Mottie/tablesorter#1749]
Hi, I have a 'overall statistics' row in the first row, which should *not* be sorted/changed/swapped when clicking on columns.
It does not seem to work when using `<tr class="font-weight-bold tablesorter-ignoreRow" role="row">`. Ideas?
This is not in `thead`, but in `tbody`.

**Comment by Mottie** [comment]
Hi @hazcod!

Try the [static row widget](https://mottie.github.io/tablesorter/docs/example-widget-static-row.html).

**Comment by hazcod** [comment]
Works! Thank you @Mottie !
