### ISSUE TITLE
Get col-sum cells to calculate the average on TFOOT

### ISSUE THREAD

**Issue by ken-colvin** [Mottie/tablesorter#1750]
- Using the math widget I can easy do a col-sum, however, for the "true" average of a column I have this scenario:
- I want to get the value of 2 TFOOT col-sum so I can calculate the Average.
- For example, I have col-sum for Num Entries and Total Minutes Spent
- I want the TFOOT value for Average Minutes spent be col-sum(Total Minutes Spent) / col-sum(Num Entries)
- In other words, the TFOOT value for Average Minutes Spent needs to be calculated based on the other 2 TFOOT cell values

![image](https://user-images.githubusercontent.com/8449843/88501270-97f6de00-cf90-11ea-8a2a-ca1c72033d78.png)

**Comment by Mottie** [comment]
Hi @ken-colvin!

Set that cell to use the "row-mean" calculation

```html
<tr>
  <th data-math="above-sum"></th>
  <th data-math="above-sum"></th>
  <th data-math="row-mean"></th>
</tr>
```

You can see all the included math formulas in this table: https://mottie.github.io/tablesorter/docs/example-widget-math.html#table2

There are also instructions on how to add your own custom formula in the [attribute settings section](https://mottie.github.io/tablesorter/docs/example-widget-math.html#attribute_settings) on that same page.

**Comment by ken-colvin** [comment]
I do not think it is the row-mean

|Count|Sum|Average
|-------|-----|--------
|10|10|1
|5|5|1
|10|15|1.5
|sum-above=20|sum-above=30|row-mean =(20+30) / 2 = 25
|20|30|what I need is 30/20=1.5

What I need is 30/20=1.5 which gives me the "true" average that will go in tfoot under Average column 
The Average column is giving the average for each Sum/Count cells
Do you understand?

**Comment by Mottie** [comment]
Try using `above-mean`

**Comment by ken-colvin** [comment]
That's not going to work.  I need to get the value in the tfoot for those
two col-sum to calculate the average for the tfoot average column.  Is
there a way to extract these two col-sum values in the tfoot?

**Comment by Mottie** [comment]
It's not perfect, but try this ([demo](https://jsfiddle.net/Mottie/cy7kq08f/)):

```js
/* Documentation for this tablesorter FORK can be found at
 * http://mottie.github.io/tablesorter/docs/
 */
$(function() {

	$.tablesorter.equations.ratio = function(array, config) {
    // Could calculate "Infinity" if the count column is zero
  	return array[1] / array[0];
  };

  $("table").tablesorter({
    theme: 'blue',
    widgets: ['math', 'zebra'],
    widgetOptions: {
      math_mask: '#,##0.##',
      math_priority: ['col', 'row']
    }
  });
});
```

**Comment by ken-colvin** [comment]
Thanks - That worked perfectly!
Great job on this widget.
