### ISSUE TITLE
Keyword highlighting request when using Filter widget?

### ISSUE THREAD

**Issue by ravenlost** [Mottie/tablesorter#1756]
I couldn't yet find an answer, so asking here:

Is it possible to do keyword highlighting when using the filter search capabilities?

Something like: [https://www.jqueryscript.net/table/Simple-jQuery-Table-Filter-Plugin-with-Keyword-Highlight-Table-Searching.html](https://www.jqueryscript.net/table/Simple-jQuery-Table-Filter-Plugin-with-Keyword-Highlight-Table-Searching.html)

But working in your Tablesorter ;)

Cheers!

**Comment by Mottie** [comment]
Hi @ravenlost!

If you look at the [main wiki page under "Misc"](https://github.com/Mottie/tablesorter/wiki#misc) you'll see a bullet that has "Use with Mark.js". Try out the "basic" and "per column" demos there. For the second demo, you'll need to change jQuery to 3.3.1 to get it to work.

**Comment by ravenlost** [comment]
> Hi @ravenlost!
> 
> If you look at the [main wiki page under "Misc"](https://github.com/Mottie/tablesorter/wiki#misc) you'll see a bullet that has "Use with Mark.js". Try out the "basic" and "per column" demos there. For the second demo, you'll need to change jQuery to 3.3.1 to get it to work.

Awesome! Thank you for this :+1:
