### ISSUE TITLE
Filter row below <TH> tag not appearing

### ISSUE THREAD

**Issue by dugaquilin** [Mottie/tablesorter#1778]
Hi, 

I've made a page that is built with Javascript, including all the elements of the table that I'd like to use the filter feature.
I have a hand made page in the same folder and it renders correctly.
I can't figure out how to get the javascript built page to render the filter row.

The one thing I noticed when inspecting the 2 pages is that in the hand made page, there are <tr role="row" class=tablesorter-filter-row... Which are missing from the javascript built page. 

I am thinking that hand made page somehow invokes the required .js files correctly and on the javascript built page the required .js files are not being invoked correctly (I assume that the <tr role="row"  html is inserted automatically but I don't unserstand how to make that magic happen.

Any help you could render would be appreciated.
Thank you
D.

**Comment by Mottie** [comment]
Hi @dugaquilin!

It sounds like you're trying to add the filter row manually? Are you including the filter widget, that'd be an easier way to go.

I'm not completely understanding what is the issue here. Please modify [this demo](https://jsfiddle.net/Mottie/dj8c0fr7/) to duplicate the problem so I can better help you.

**Comment by dugaquilin** [comment]
Thank you for your response.
I can't modify the example you gave, my Javascript is weak.

My page has the .css and .js files included.  I assume this is what you mean by "including the filter widget"  

CSS includes:
<head>
    
<link rel="stylesheet" href="./css/theme.blue.css"> 
<link rel="stylesheet" href="./css/table0.css"> 
<link rel="stylesheet" href="./css/headers1.css"> 
<link rel="stylesheet" href="./css/table1.css"> 
<link rel="stylesheet" href="./css/filter1.css"> 
<link rel="stylesheet" href="./css/sort1.css"> 

JS includes:
<body>
<script type="text/javascript" src="./js/filter1.js"></script> 
<script type="text/javascript" src="./js/sort1.js"></script> 
<script type="text/javascript" src="./js/jquery-latest.min.js"></script> 
<script type="text/javascript" src="./js/jquery.tablesorter.js"></script> 
<script type="text/javascript" src="./js/widget-filter.js"></script> 
<script type="text/javascript" src="./js/jvminfo2.js"></script> 

I am not trying to add the filter row manually, My observation comes from me inspecting the page at runtime.  I noticed that the manually created .html page inserts / adds the correct(required) tags and class entries.

Below is an image of the page with the filter not working.
![image](https://user-images.githubusercontent.com/30957173/109309432-473eb080-7811-11eb-9a54-7e6dc6a801fb.png)

Below is an image of the working page (there are way more tags with class entries in the functional page.
![image](https://user-images.githubusercontent.com/30957173/109309852-d0ee7e00-7811-11eb-80f7-79563185c6ef.png)

I was thinking that a simple element refresh would get the widget(.js) to kick in and modify(expand) all the widget tags to include the things like (tablesorter-blue tablesorter36c19b84e28dc hasfilters; th added in class values the <tr role="row" class="tablesorter-filter-row tablesorter-ignoreRow">   
Which the widget seems to generate, and my challenge is that the one page is not generating(back filling) the extra tags that get the widget to work.

The page you asked me to modify is in a form of javascript I am not familar with(sorry, real old school aka javascript noob).

I included below my javascript function that builds the <th> portion of the page.
// ------------------------------------------------------------
function buildTH(table, tr) {
    //-------------
    // <THEAD> text
    var thead = document.createElement('thead');
//    var theadatt1 = document.createAttribute("id");
//    theadatt1.value = "myTHead";
//    thead.setAttributeNode(theadatt1);

    table.appendChild(thead);

    // ------------------------------------------------------------------
    // 2021-02-23 Build the <TH> tags.  As needed by the 
    //            Table with filtering included.
    //            New functions used:
    //                document.createAttribute
    //                .value 
    //                .setAttributeNode
    // ------------------------------------------------------------------
    //------------------------------
    // COLUMN 1 - CHECKBOX
    //------------------------------
    var thtext1 = document.createTextNode('');
    var th1 = document.createElement('th');
    //checkbox
    var attr1 = document.createAttribute("data-placeholder");
    var attr2 = document.createAttribute("class");
    attr1.value = "d";
    attr2.value = "filter-match";
    th1.setAttributeNode(attr1);
    th1.setAttributeNode(attr2);

    //------------------------------
    // COLUMN 2 - EDIT
    //------------------------------
    var thtext2 = document.createTextNode('Site Id');
    var th2 = document.createElement('th')
    //EDIT
    var att2a = document.createAttribute("data-placeholder");
    var att2b = document.createAttribute("class");
    att2a.value = "d";
    att2b.value = "filter-match";
    th2.setAttributeNode(att2a);
    th2.setAttributeNode(att2b);

    //------------------------------
    // COLUMN 3 - Delete Icon
    //------------------------------
    var thtext2a = document.createTextNode('Delete');
    var th2a = document.createElement('th')
    //DELETE
    var att22 = document.createAttribute("data-placeholder");
    var att23 = document.createAttribute("class");
    att22.value = "d";
    att23.value = "filter-match";
    th2a.setAttributeNode(att22);
    th2a.setAttributeNode(att23);

    //------------------------------
    // COLUMN 4 - Edit Icon 
    //------------------------------
    var thtext2b = document.createTextNode('Edit');
    var th2b = document.createElement('th')
    //site id
    var att11 = document.createAttribute("data-placeholder");
    var att12 = document.createAttribute("class");
    att11.value = "d";
    att12.value = "filter-match";
    th2b.setAttributeNode(att11);
    th2b.setAttributeNode(att12);

    //------------------------------
    // COLUMN 5 - ENVIRONMENT
    //------------------------------
    var thtext3 = document.createTextNode('ENV');
    var th3 = document.createElement('th');
    //env
    var att3a = document.createAttribute("data-placeholder");
    var att3b = document.createAttribute("class");
    att3a.value = "DEV";
    att3b.value = "filter-match";
    th3.setAttributeNode(att3a);
    th3.setAttributeNode(att3b);

    //------------------------------
    // COLUMN 6 - ALIAS
    //------------------------------
    var thtext4 = document.createTextNode('App Name / Alias');
    var th4 = document.createElement('th');
    //alias
    var att4a = document.createAttribute("data-placeholder");
    var att4b = document.createAttribute("class");
    att4a.value = "ie. int* or bel*|wbel*";
    att4b.value = "filter-match";
    th4.setAttributeNode(att4a);
    th4.setAttributeNode(att4b);

    //------------------------------
    // COLUMN 7 - ZONE
    //------------------------------
    var thtext5 = document.createTextNode('Internal/External');
    var th5 = document.createElement('th');
    //zone
    var att5a = document.createAttribute("data-placeholder");
    var att5b = document.createAttribute("class");
    att5a.value = "ie. inter or Ext";
    att5b.value = "filter-match";
    th5.setAttributeNode(att5a);
    th5.setAttributeNode(att5b);

    //------------------------------
    // COLUMN 8 - URL
    //------------------------------
    var thtext6 = document.createTextNode('URL');     
    var th6 = document.createElement('th');
    //URL
    var att6a = document.createAttribute("data-placeholder");
    var att6b = document.createAttribute("class");
    att6a.value = "ie. B*{space} or br*|c";
    att6b.value = "filter-match";
    th6.setAttributeNode(att6a);
    th6.setAttributeNode(att6b)

    //------------------------------
    //CREATE THE TABLE HEADER ROW
    //<tr><th>site id</th><tr>
    //------------------------------
    table.appendChild(thtext1);
    th2.appendChild(thtext2);
    th2a.appendChild(thtext2a);
    th2b.appendChild(thtext2b);
    th3.appendChild(thtext3);
    th4.appendChild(thtext4);
    th5.appendChild(thtext5);
    th6.appendChild(thtext6);

    // ROW
    tr.appendChild(th1);
    tr.appendChild(th2);
    tr.appendChild(th2a);
    tr.appendChild(th2b);
    tr.appendChild(th3);
    tr.appendChild(th4);
    tr.appendChild(th5);
    tr.appendChild(th6);

    // append ROW to TABLE
    // OLD (with no thead)
    // table.appendChild(tr);

    // first attach the ROW to the THEAD
    thead.appendChild(tr);
    // then attach the thead to the table.
    table.appendChild(thead);
}

**Comment by Mottie** [comment]
That helps a little... it does appear you are including the filter file (including the `widget-filter.js` script file). I also see the row being added in the rendered HTML meaning that the filter widget was initialized in the settings.

It'd help me if you could share the code being used to initialize tablesorter. Also, I still don't quite understand what you're trying to do... I think you mean all the code you shared is used to build the table, then initialize tablesorter?

The `buildTH` function can be greatly simplified by using `innerHTML` 

```js
// guessing tr is an empty row element? It isn't needed here...
function buildTH(table, tr) {
  var thead = document.createElement('thead');
  table.appendChild(thead); // don't do this twice
  thead.innerHTML = `
    <tr>
      <th data-placeholcer="d" class="filter-match"></th>
      <th>include more header cells..</th>
    </tr>`;
}
```

For the `tbody` portion, you will want to be more cautious if you're including user-generated values.

Then after all the build functions are done... call `$('table').tablesorter(/* options here */)`

**Comment by dugaquilin** [comment]
you say "code being used to initialize tablesorter"  This may be important.  I don't understand.  what is this?  I just put the <table> tag in with the class="tablesorter" and that is all.... My issue could be that I am actually not doing an initialization.  How is that normally done.

**Comment by dugaquilin** [comment]
Using the .innerHTML I simplified the .html page.  it has only 2 rows and those rows are static html.
I am seeing the same behavior.  I included the much smaller demo page below.  I'm hoping this helps.

<html> 
    <head>

        <link rel="stylesheet" href="site.css">
        <link rel="stylesheet" href="./css/navbar.css"> 

        
        <link rel="stylesheet" href="./css/theme.blue.css"> 
        <link rel="stylesheet" href="./css/table0.css"> 
        <link rel="stylesheet" href="./css/headers1.css"> 
        <link rel="stylesheet" href="./css/table1.css"> 
 
 
 

        

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<title>Show Sites</title>
<link rel="icon" type="image/png" href="images/favicon.png"/>



<script type="text/javascript" src="./js/jquery-latest.min.js"></script> 
<script type="text/javascript" src="./js/jquery.tablesorter.js"></script> 
<script type="text/javascript" src="./js/widget-filter.js"></script> 
<script type="text/javascript" src="./js/jvminfo2.js"></script>

</head>

<body>




 

 
<nav>
    <ul>
        <li><img alt="bg" src="./img/delete1.png:></li>
        <li class="appTitle">Helper</li>
        <li>menu3</li>
    </ul>
</nav>

 
 
 
 
 


<button id="fetchDataButton" class="findBtn" onclick="makeTable()">Show All Sites</button>
<br>
<br>
<br>
<div id="fetchData"></div>

<script>
// ------------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------
// ------------------------------------------------------------------------------------------

// ------------------------------------------------------------
function makeTable() {
    var table = document.createElement('table');
    document.createAttribute('table')

    //<table id="table" class="tablesorter">
    var tableatt1 = document.createAttribute("id");
    tableatt1.value = "table";
    var tableatt2 = document.createAttribute("class");
    tableatt2.value = "tablesorter";

    table.setAttributeNode(tableatt1);
    table.setAttributeNode(tableatt2);
    table.createHead;

    //-------------------------------------------------------
    // Get Anchor for table - where DIV = fetchData
    //-------------------------------------------------------
    var mainContainer = document.getElementById("fetchData");
    var tr = document.createElement('tr');

    buildTH(table, tr);
    // ---------------------------------------------------
    // CREATE THE TBODY block
    // ---------------------------------------------------
    var tbody = document.createElement('tbody');
    var tbatt1 = document.createAttribute("aria-live");
    var tbatt2 = document.createAttribute("aria-relevant");
    tbatt1.value = "polite";
    tbatt2.value = "all";
    tbody.setAttributeNode(tbatt1);
    tbody.setAttributeNode(tbatt2);
    
    table.appendChild(tbody);
    tbody.innerHTML=`
    <tr class="alt">
    <td>button</td>
    <td>id</td>
    <td>del</td>
    <td>edit</td>
    <td>DEV</td>
    <td><a href="https://google.ca"><img src="../img/delete.png" width="16"></a></td>
    <td><a href="https://google.ca">Internal</a></td>
    <td>https://google.ca</td>
    </tr>
    <tr class="alt">
    <td>button</td>
    <td>id</td>
    <td>del</td>
    <td>edit</td>
    <td>PROD</td>
    <td>IDM</td>
    <td><a href="https://www.google.com">Internal</a></td>
    <td>https://www.google.com</td>
    </tr>
    `;
    mainContainer.appendChild(table);
}

// ------------------------------------------------------------
function buildTH(table, tr) {
    //-------------
    // <THEAD> text
    var thead = document.createElement('thead');
//    var theadatt1 = document.createAttribute("id");
//    theadatt1.value = "myTHead";
//    thead.setAttributeNode(theadatt1);


    table.appendChild(thead);
    thead.innerHTML = `
      <tr> 
        <th class="filter-match"></th> 
        <th class="filter-match">Site Id</th> 
        <th class="filter-match">Delete</th> 
        <th class="filter-match">Edit</th> 
        <th class="filter-match">ENV</th> 
        <th class="filter-match">App Name / Alias</th> 
        <th data-placeholder="ie. inter or Ext" class="filter-match">Internal/External</th> 
        <th data-placeholder="ie. B*{space} or br*|c" class="filter-match">URL</th> 
      </tr> `;
}
 
</script> 
<script type="text/javascript">
    // -----------------------------------------
    // Initialize the JQuery filtering blue table
    // -----------------------------------------
    //        $(document).ready(function()
    //    $(function(){
    //            $("#table").tablesorter();
    //    });
    $(function() {
      $('table').tablesorter({
        theme: 'blue',
        widgets: ['zebra', 'columns', 'filter'],
        widgetOptions: {
            filter_column: true,
            filter_placeholder: {search: 'Search'},
            filter_reset: '.reset'
        },
        filter_columnFilters: true
      });
    });
</script>
    
</body> 
</html>

**Comment by dugaquilin** [comment]
I have been iterating continuously with small tweaks here and there.  
To me it feels like the tablesorter is not working correctly,   I see now that the tablesorter adds some <TR> tags with a bunch of class values to engage the filter.
I also understand that this is the job of the tablesorter to make happen.  It's just that with my javascript built page, the tablesorter is not working correctly.  

I have put an alert in to the INIT function, and it shows me the INIT function is being triggered.
I've also removed all the .css from the page to reduce interference.  only using ./css/theme.blue.css now, with same results.

**Comment by dugaquilin** [comment]
I saved the example to https://jsfiddle.net/oLcx2at6/
