### ISSUE TITLE
Pager removeRows: true. How to manipulate hidden rows?

### ISSUE THREAD

**Issue by itsdai** [Mottie/tablesorter#1781]
How would I select & modify the columns from all the rows that are hidden from removeRows : true?

I'm using tablesorterPager and an external show/hide column function. Setting removeRows to false fixes it but I need it on. Since it's the next pages are completely hidden, the show/hide column function can't select it.

**Comment by Mottie** [comment]
It's kinda convoluted (to keep everything backwards compatible)

- Start by looking in the `$('table')[0].config.cache[ {tbodyIndex} ].normalized` array
- Each element is a row
- The last entry in the row is an object
- The object contains:
  - `child` - array of any associated child rows
  - `raw` - raw un-parsed table cell text
  - `order` - original row index
  - `$row` - jQuery obj of the row element

See https://mottie.github.io/tablesorter/docs/#variable-cache for examples

**Comment by itsdai** [comment]
I received an error : Uncaught TypeError: $(...)[0].config is undefined when running

`$('.tablesorter')[0].config.cache[0].normalized[0];`
and
`var config = $('#mytable').data('tablesorter');`

**Comment by Mottie** [comment]
Check it inside of the [`initialized` callback](https://mottie.github.io/tablesorter/docs/#initialized).

**Comment by itsdai** [comment]
Thank you Mottie!
