### ISSUE TITLE
filter_external will not perform single character filters when filtering all columns.

### ISSUE THREAD

**Issue by runnermatthew** [Mottie/tablesorter#1796]
I have tables with columns that have single character values. If I limit my external filter to anything less than all of the columns I am able to filter by a single character. Specifying 'all' or specifying '0-x' where x is the number of columns - 1 won't filter until there are two characters in my external filter input. I'm looking for a workaround or a direction forward.

https://mottie.github.io/tablesorter/docs/example-widget-filter-external-inputs.html

**Comment by Mottie** [comment]
Hi @runnermatthew!

Set the [`filter_liveSearch`](https://mottie.github.io/tablesorter/docs/#widget-filter-livesearch) widget option to a number, like `1`.

**Comment by runnermatthew** [comment]
@Mottie Thanks, can't believe I missed that in the documentation.
