### ISSUE TITLE
Does multicolumn sort work?

### ISSUE THREAD

**Issue by paklein** [Mottie/tablesorter#1812]
I'm trying the demo here https://mottie.github.io/tablesorter/docs/, and am getting the result in the image by clicking on First Name, then shift + Last Name. Thanks.

![63108E53-1741-47A6-8F53-8938329F5402](https://user-images.githubusercontent.com/1054460/161331596-0e1a1982-eb06-450f-ab9e-550032447f1a.jpeg)

**Comment by Mottie** [comment]
Hi @paklein!

Yes, it does work. Keep clicking on the Last name column and you'll see that only the first 4 rows change.

**Comment by paklein** [comment]
Oh, duh. Thanks for the quick reply.
