### ISSUE TITLE
Safari 16.2 not loading pages with tablesorter

### ISSUE THREAD

**Issue by 0hwow** [Mottie/tablesorter#1832]
Safari 16.2 doesn't load tablesorter, this happens even with demo pages.

Error message: A problem repeatedly occured with...

![Screenshot 2022-12-15 at 23 48 19](https://user-images.githubusercontent.com/34716587/207983567-16ea0d7f-79a2-44a4-a381-34c49d2e2116.png)

**Comment by TheSin-** [comment]
Need to see the console cause I'm on Safari 16.2 and it's working fine for me.

**Comment by 0hwow** [comment]
> Need to see the console cause I'm on Safari 16.2 and it's working fine for me.

I get this repeated error in console:

error	10:00:23.250050+0100	Safari	[0x7fb93818aa20] Bad CurrentVBLDelta for display 59592768 is zero. defaulting to 60Hz.

**Comment by 0hwow** [comment]
Solved. Thank you.
