### ISSUE TITLE
column reordering

### ISSUE THREAD

**Issue by rharsh** [Mottie/tablesorter#186]
may be this will help somebody, Click on column header and drag to another column to rearrange columns. may be can be added to the widgets common file, checked across chrome & IE decent performance over 50 sample records. only checked with the bootstrap theme though

may be can write a small CSS.for dragging purpsoe

```javascript
$.tablesorter.addWidget({
	id: 'col-reorder',
	init: function(table, thisWidget) {
      var wo = table.config.widgetOptions;
      $(table).find('thead th').mouseup(function() {
         var endNdx=$(this).index();
         if((wo.startColNdx != endNdx) && (wo.startColNdx >-1) && (endNdx>-1)) {
            var rows = jQuery('thead tr, tbody tr', $(table));
            var cols,colFrom,colTo;
            if((wo.startColNdx<endNdx) && ((endNdx-wo.startColNdx))==1) {
               colFrom = endNdx;
               colTo = wo.startColNdx;
            }else {
               colFrom = wo.startColNdx;
               colTo = endNdx;
            }
            rows.each(function() {
               cols = jQuery(this).children('th, td');
               cols.eq(colFrom).detach().insertBefore(cols.eq(colTo));
            });
         }
         wo.startColNdx=-1;
      }).mousedown(function(){
         wo.startColNdx = $(this).index();
      });
	},
	format: function(table, init){
	},
	remove: function(table, c, wo){
	}
});
```

**Comment by Mottie** [comment]
Instead of working on the column reorder widget, I've modified the jQuery UI dragtable widget to work with tablesorter - check out [the demo](http://mottie.github.io/tablesorter/docs/example-dragtable.html).

**Comment by adnanp78** [comment]
Hello Mottie.
Is there possible to set initial collums and hide all other columns not set. For exemple orginal table have collumns 1,2,3,4,5,6 and we want to set to display only column 5,3,6 in this order ?
Tnx

**Comment by Mottie** [comment]
Hi @adnanp78!

It sounds like you might want the [columnSelector widget](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html) instead of column reordering. The column reordering widgets are both kinda clunky anyway; I'm not happy with either.

To initially hide columns, set the [`columnSelector_columns` option](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-columns)  or class name/data-attribute in the designated column.
