### ISSUE TITLE
Default Pager Size with .tablesorter.storage

### ISSUE THREAD

**Issue by invisiblekid** [Mottie/tablesorter#197]
Hey guys,

Really enjoying using this great app. Very much looking forward to seeing what v3 brings, but in the mean time I have a small issue really.

I have my tablesorterPager settings referencing size in local storage:

size: $.tablesorter.storage( $table[0], 'tablesorter-pagesize')

If this isn't set I get an empty Pager (even if the default is set). Is there a way I can check for local storage entries and if it is empty I can set a default size in the app?

I have written a small if statement checking if tablesorter-pagesize is null, and while it kinda worked it wasn't robust enough to use, nor did it work where I had multiple tables either on the same page, or on the same site.

Any help would be much appreciated.

**Comment by airthomas** [comment]
Hello,

In http://jsfiddle.net/tomChai/zr14L69w/2/, I want to added 2 buttons to tablesorter for some action with jquery. One button called "onPopup" is worked to alert the message, but another one called "choose" is not work..... any idea ? 

Many thanks,
Thomas

**Comment by Mottie** [comment]
Hi @airthomas!

If you want to bind to elements within the table, you need to use [delegated event bindings](http://api.jquery.com/on/#direct-and-delegated-events) .

[Updated demo](http://jsfiddle.net/zr14L69w/5/)

```js
$('table').on('click', '.choose', function(){
    alert("b");
});
```

**Comment by airthomas** [comment]
many thanks Mottie.
