### ISSUE TITLE
Incorrect sorting in Icelandic

### ISSUE THREAD

**Issue by laddi** [Mottie/tablesorter#212]
I have a problem with text sorting using Icelandic characters.  The problem is that character equivalents aren't really suitable since there is a strict sorting order for each character, the accented characters and then the special Icelandic characters (þ [thorn] and ð [eth]).  The sorting is actually the same as specified on the sugar.js [array sorting page](http://sugarjs.com/sorting) which is as follows:

AÁ[ÀÂÃĄ]BC[ĆČÇ]D[Ď]ÐEÉ[ÈĚÊË]ĘFG[Ğ]H[ı]IÍ[ÌİÎÏ]JKL[Ł]MN[ŃŇÑ]OÓ[ÒÔ]PQR[Ř]S[ŚŠŞ]T[Ť]UÚ[ÙŮÛÜ]VWXYÝZ[ŹŻŽ]ÞÆ[ŒØÕÅÄ]Ö (characters in brackets not in Icelandic alphabet)

But using the sortLocaleCompare sorts á/Á, for example, as an a/A which is wrong because a > á.  Also ö/Ö is mixed in with the O's but is actually the last letter in the alphabet.  And þ/Þ is last behind both æ/Æ and ö/Ö even though both of them should be behind þ/Þ.

Any ideas on a possible fix for this or, better yet, use the correct sorting as specified in the sugar.js documentation?  Or is there possibly a character to number (place in alphabet) conversion I could use?

**Comment by Mottie** [comment]
Just to update you, Sugar has since exposed the sort functions so there is no longer a need to extract out specific code from that library. All you need to get a proper Icelandic alphabetical sort is to do the following ([demo](http://jsfiddle.net/Mottie/abkNM/5468/)):

```js
$(function () {

    Array.AlphanumericSortOrder = 'AaÁáBbCcDdÐðEeÉéĘęFfGgHhIiÍíJjKkLlMmNnOoÓóPpQqRrSsTtUuÚúVvWwXxYyÝýZzÞþÆæÖö';
    Array.AlphanumericSortIgnoreCase = true;
    // see https://github.com/andrewplummer/Sugar/issues/382#issuecomment-41526957
    Array.AlphanumericSortEquivalents = {};

    $('table.tablesorter').tablesorter({
        widgets: ['zebra'],
        textSorter: {
            0 : Array.AlphanumericSort
        }
    });

});
```

**Comment by laddi** [comment]
Cool, thanks! :D
