### ISSUE TITLE
tablesorter resize issue.

### ISSUE THREAD

**Issue by beenabegum2012** [Mottie/tablesorter#215]
I used your tablesorter for displaying data. I used also that for resizing column, the whole things working fine & it is awesome. I have only one issue in resize column through header. If I change the width of column through the header it change the width other columns it’s just like puzzle. I would like to request you how I can make the column width adjustment just like excel. I hope you understand what I want. I would like to again advance thank you for my help.

Your earlier reply will appreciated

**Comment by Mottie** [comment]
Hi @sennz!

Please see issue #781 for a demo & code which combines reorder + resizable + filter. In the next update, I'll include a mod to the [jQuery UI dragtable widget](http://akottr.github.io/dragtable/) (requires jQuery UI sortable).

**Comment by sennz** [comment]
Thanks. I will try the demo code.

**Comment by Mottie** [comment]
New [dragtable](http://mottie.github.io/tablesorter/docs/example-dragtable.html) demo available.
