### ISSUE TITLE
isoDate parser cannot cope with ISO-8601 combined dates and times

### ISSUE THREAD

**Issue by exterrestris** [Mottie/tablesorter#247]
The regex used by the isoDate parser will match an ISO-8601 date/time such as **2013-02-18T18:18:44+00:00**, but cannot parse such a date - it instead returns an empty string.

I have worked around this by disabling the isoDate parser, and using my own - it cannot parse non-GMT times, but this is sufficient for my needs. I believe the date.js library can parse ISO-8601 dates successfully however.

```
var iso8601date = /^([0-9]{4})(-([0-9]{2})(-([0-9]{2})(T([0-9]{2}):([0-9]{2})(:([0-9]{2})(\.([0-9]+))?)?(Z|(([-+])([0-9]{2}):([0-9]{2})))?)?)?)?$/;

$.tablesorter.addParser({
// set a unique id
id : 'iso8601date',
is : function(s) {
    return s.match(iso8601date);
},
format : function(s) {
    var result = s.match(iso8601date);

    if (result) {
    var date = new Date(result[1], 0, 1);

    if (result[3]) {date.setMonth(result[3] - 1);}
    if (result[5]) {date.setDate(result[5]);}
    if (result[7]) {date.setHours(result[7]);}
    if (result[8]) {date.setMinutes(result[8]);}
    if (result[10]) {date.setSeconds(result[10]);}
    if (result[12]) {date.setMilliseconds(Number('0.' + result[12]) * 1000);}

    return date;
    }

    return 0;
},
type   : 'numeric'
});
```

**Comment by matthewslaney** [comment]
Hi Mottie,

Thanks for tablesorter, it's great. I was running into problems with ISO 8601 sorting as well and found this bug. However, your update didn't actually resolve it for me. Here's the updated parser that I created that works for me.

```javascript
    ts.addParser({
        id: "isoDate",
        is: function(s) {
            return (/^\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}T\d{2}:\d{2}:\d{2}[\+,\-]\d{2}:\d{2}/).test(s);
        },
        format: function(s, table) {
            return ts.formatFloat((s !== "") ? (new Date(s).getTime() || "") : "", table);
        },
        type: "numeric"
    });
```

**Comment by Mottie** [comment]
Hi @matthewslaney!

The "isoDate" parser in the latest version makes sure that a valid date is obtained, so it now looks like this:

```js
ts.addParser({
	id : 'isoDate',
	is : function( str ) {
		return /^\d{4}[\/\-]\d{1,2}[\/\-]\d{1,2}/.test( str );
	},
	format : function( str, table ) {
		var date = str ? new Date( str.replace( /-/g, '/' ) ) : str;
		return date instanceof Date && isFinite( date ) ? date.getTime() : str;
	},
	type : 'numeric'
});
```

**Comment by matthewslaney** [comment]
@Mottie,

Ah. That makes sense. The only part I was updating was the regex. The version I gave will now properly match the true ISO 8601 format: 2013-02-18T18:18:44+00:00.

**Comment by Mottie** [comment]
Well the ["iso8601date" parser](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-date-iso8601.js) is separate from the built-in ["isoDate" parser](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L2538-L2550). I left off the time portion of the "isoDate" parser intentionally since it was meant to be a bit more generic because not everyone includes a time.

**Comment by matthewslaney** [comment]
I see. I guess my confusion is that out of the box a table with the full date and time is not properly parsed. I was just trying to contribute a quick fix since I found this project so useful.

**Comment by Mottie** [comment]
Hmm, I think you're right... the default "shortDate" parser would catch any basic formats. Maybe I should replace the "isoDate" with and "iso8601date" parser.... or remove it from the core.
