### ISSUE TITLE
tablesorter + ajax pager + filter

### ISSUE THREAD

**Issue by efib** [Mottie/tablesorter#270]
Hi,
when im using tablesorter with ajax processing pager and filter for each column.
the pager work perfect with the ajax but when im adding the widget 'filter' to the tablesorter im keep getting the same request for page 0 constantly (can be seen in the network at chrome)
i saw there was a bug similar to this that has been solved. but for me it is still happening, even after updating the libraries, 
please advice..
Thanks !

**Comment by airthomas** [comment]
I have applied pager with ajax, after that how can I setup the tbody td alignment ? without ajax, I can apply <td align="right"> etc, many thanks.

**Comment by Mottie** [comment]
Hi @airthomas!

Have you looked at the code for the [`ajaxProcessing` callback function](http://mottie.github.io/tablesorter/docs/#pager-ajaxprocessing)?

Here is a [full working example](http://jsfiddle.net/Mottie/uwZc2/)

**Comment by airthomas** [comment]
i got it, thanks Mottie, will you consider to add this feature to tablesorter such as tbodyAlignment etc instead of by ajaxProcessing. Many thanks.

**Comment by Mottie** [comment]
I don't understand what you mean by tbody alignment? And how would it be different from ajaxProcessing?
