### ISSUE TITLE
Sticky headers with a fixed page header.

### ISSUE THREAD

**Issue by leenooks** [Mottie/tablesorter#294]
Hi, I'm just discovered this great library (and new to jquery generally), and am getting your library to do what I want, with 1 minor exception.

My webpage uses bootstrap, and my nav at the top is using navbar-fixed-top - resulting in the header banner staying when users scroll down the page.

If my page has a table, and I'm using your library to stick the header at the moment it is sticking behind my page navbar.

I couldnt figure out what setting I needed to make, so that:
- stickyheader would leave the table header below the page navbar, instead of scrolling behind it.

(I was able to fix this by modifying the jquery.tablesorter.widget.js, around line 757, changing "top : 0" to "top : 57" (which is my required offset).)
- scrolling the table would scroll at the bottom of the table header, not half way through it (after my offset).

(I was able to fix this by modifying the jquery.tablesorter.widget.js around line 843, modifying sTop to add 57 (which is my required offset).)

Both fixes are from commit version 5980d0e (which I got when I downloaded).

Ideally, this should be a config item or better still, it would be great if you can automatically figure out the required offset should be (and maybe the configure item might only require the class name that contains the position:fixed).

If there is a way of doing what I'm trying to achieve, then great - please let me know :)

**Comment by rgautam08** [comment]
Hello @Mottie,

First of all I would like to thanks for providing marvelous features like table sorter. 
Intention to emanate this forum , I am facing with sticky header issue.

In my  case, since table has more than 20 columns table come up with horizontal scrollbar.
When I scroll down the page, Sticky header appears and goes outside the screen and not adjust with actual table.    

 Expectation like :- 
      
        Sticky header should stick with table not screen window and time of horizontal scroll harmonize with actual table.

Please help me to handle the scenario . Looking forward to your solution.

**Comment by Mottie** [comment]
Hi @rgautam08!

Please check out the [`stickyHeaders_attachTo` option](http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html#stickyheaders-attachto). There is also [a demo](http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html#table2) on that page with which you can examine the code.

I hope that answers your question.

**Comment by budwig** [comment]
stickyHeaders_offset worked fine for me, thanks for the tip :)
