### ISSUE TITLE
Column width when using the Filter widget, to match the column content, even if narrow

### ISSUE THREAD

**Issue by PanzP** [Mottie/tablesorter#296]
I love the Filter widget, but some of my columns have narrow data such as "age" or "gender". I'd like these columns to fit their content width, as a normal table does, but when I use the Filter widget, I get columns all pretty much the same width. Is there a fix ?

**Comment by danieltenefrancia** [comment]
Hi Mottie . I know this has been resolved 2 years ago . but I'm facing the same problem only that I'm using table sorter with scroller. but the size of my columns on the last part of my table seems not to bind with the size of its content . I hope you can help -_-

**Comment by Mottie** [comment]
Hi @danieltenefrancia!

Can you provide a demo? (modify [this one](http://jsfiddle.net/Mottie/mqv16pd4/) if you need a starting point)

**Comment by danieltenefrancia** [comment]
![wew](https://cloud.githubusercontent.com/assets/16300290/12262068/61705226-b960-11e5-9653-776bfed33bb0.jpg)

Hi Mottie . here's a snapshot of the result of my table after implementing scrollers .

**Comment by Mottie** [comment]
Sorry, a snapshot doesn't help. I can't help find the problem from an image.

**Comment by danieltenefrancia** [comment]
Hi @Mottie Good Day 

I have updated the demo you told me to modify and it shows the same result as my table [GitHub](http://jsfiddle.net/mqv16pd4/41/) please do check

**Comment by danieltenefrancia** [comment]
T_T

**Comment by Mottie** [comment]
LOL sorry, I really don't like the scroller widget so I try to avoid dealing with it... and I forgot :stuck_out_tongue: 

Maybe @TheSin- can take a look? :grin:

**Comment by oglops** [comment]
How can I make the width fixed ? but still resizable ? I don't want the column get resized when you are typing in the filter, when the list is long, it starts getting annoying. 

http://jsfiddle.net/abkNM/8822/

when you are typing in animals or sites filter which has long strings, the width starts jumping around.

**Comment by Mottie** [comment]
Hi @oglops!

Set the [`widthFixed` option](https://mottie.github.io/tablesorter/docs/#widthfixed) to `true` ([demo](http://jsfiddle.net/Mottie/abkNM/8823/)).

**Comment by oglops** [comment]
Thanks! It seems the popping is minimized after I set width for all columns, but there is one problem that when the list is long,  screen right edge has a scroll bar, when you type something does not exists into the filter, the scroll bar disappears ( of course ), but this causes the widths of all columns to re-distribute. ([demo](http://jsfiddle.net/abkNM/8828/))

**Comment by Mottie** [comment]
There isn't much I can do about the scroll bar... maybe you would want to set the columns width in the css using pixels. The `widthFixed` option sets the widths using a percentage.

**Comment by RajuTicvic** [comment]
Hi @Mottie,
I used the Fixed column, the horizontal scroll has working only when i was enter text in filter input  or resize the window. Why?
