### ISSUE TITLE
Scroller Widget Hides Data with jQuery UI Tabs

### ISSUE THREAD

**Issue by ScottGeiger** [Mottie/tablesorter#333]
I am having a problem with the scroller widget combined with jQuery UI tabs.  I have a table on a non-active tab.  When I click on the tab the table body data is not displayed, only the headers show.  If I disable the tabs the scroller works.  I have added the code to trigger the widgets when activating a new tab and no luck.  I am using the following tablesorter setup:

```
    $("#mytable").tablesorter({
    emptyTo: "bottom",
    sortInitialOrder: "asc",
    widgets : ["uitheme", "zebra", "resizable", "filter", "scroller"],
    widgetOptions: { 
        zebra: ["even", "odd"],
        scroller_height: 100 }
    });
```

If I remover the "scroller" widget the table appears correctly, adding it back and the table body data disappears.  I made a jsfiddle so you can see what is happening here: http://jsfiddle.net/scottgeiger/B5ULA/2/

**Comment by KennedyIhe** [comment]
I resolved my issue by calling (".tablesorter").trigger("applyWidgets"); on hidden UI tabs
