### ISSUE TITLE
individual filter reset button missing in bootstrap theme

### ISSUE THREAD

**Issue by bbodenmiller** [Mottie/tablesorter#356]
The filter reset button exists in the default theme:
![normal](https://f.cloud.github.com/assets/1192780/866578/d157d6d2-f698-11e2-99b9-4a30f05238c3.PNG)

But in the bootstrap theme it is missing:
![bootstrap](https://f.cloud.github.com/assets/1192780/866579/d16e2be4-f698-11e2-8c44-ace3b26e9cb6.PNG)

How can I fix this? I haven't found it working in any demos or been able to reverse engineer how the default theme works to fix it.

**Comment by tongtongdlut** [comment]
I met the same problem. You can try this:
input[type="search"] {
  -webkit-appearance: searchfield;
}

input[type="search"]::-webkit-search-cancel-button {
  -webkit-appearance: searchfield-cancel-button;
}

**Comment by vcfvct** [comment]
@tongtongdlut 
Your magic works like a charm!
Thank you!

**Comment by RahulGuptaVE** [comment]
@tongtongdlut 
you saved my day. Thank you so much  !!!!
