### ISSUE TITLE
tablesorter -Pager plugin not working in IE 11

### ISSUE THREAD

**Issue by sumannetpro** [Mottie/tablesorter#377]
Table sorter pager plugin not working in IE 11 

 Please click the below example link given by table sorter in IE 11

http://tablesorter.com/docs/example-pager.html 

Table body is not visible. Header, footer are getting displayed but the table rows are not visible in IE 11 

Any help in this regards is highly appreciated.

Thanks,

Suman.

**Comment by guo54329** [comment]
针对IE高版本不能显示tbody中内容的处理：
问题主要出现在jquery.tablesorter.js里面的863行的IE浏览器类型的判断上面。
解决：将此行if($.browser.msie)的条件
$.browser.msie
改为
!!window.ActiveXObject || "ActiveXObject" in window
即可解决问题！
IE高版本不在使用msie作为判断其类型的标识。

**Comment by guo54329** [comment]
第二种解决方式：在https://stackoverflow.com/questions/19504252/answer/submit页面，Christian Davén提供了一个https://github.com/Mottie/tablesorter，这个版本也解决了此问题，但将项目至于服务器上之后thead中单元格右侧的小箭头显示不正常，路径需要修正，显得比较麻烦。

**Comment by Mottie** [comment]
Hi @guo54329!

My version of tablesorter does not use `$.browser.msie`... this was deprecated in jQuery v1.3 and completely removed in jQuery v1.9 - http://api.jquery.com/jQuery.browser/
