### ISSUE TITLE
pager plugin with child rows

### ISSUE THREAD

**Issue by ghost** [Mottie/tablesorter#396]
The pager plugin does not take account of child rows, basing it's calculation for the number of pages and how many rows to put on each page by the rows array.  Since child rows are added to their parent, they get missed in these calculations.

This is easily seen by adding `class="tablesorter-childRow"` to some of the rows in http://jsfiddle.net/Mottie/4mVfu/1/.  For example, if I add the class only to the `<tr>` for `Student02`, it shows 11 students on the first page, with a page size of 10.

**Comment by Mottie** [comment]
@ar-lab Ok, I finally got around to making the filtering of child row content work. Please see [this comment](https://github.com/Mottie/tablesorter/issues/574#issuecomment-102228700) for more details.

**Comment by Craga89** [comment]
:+1: to getting back to this. I know all too well how easy it is to let this stuff slip *looks at own repos massive backlog*

**Comment by Mottie** [comment]
@Craga89 Check out [ZenHub](https://www.zenhub.io/), it's really been helping me organize and prioritize issues :zap:

**Comment by Craga89** [comment]
+1 to that @Mottie, looks awesome

**Comment by ar-lab** [comment]
@Mottie Good job!
