### ISSUE TITLE
Filter Plugin with just one text box

### ISSUE THREAD

**Issue by prainho** [Mottie/tablesorter#405]
Is it possible to use the filter plugin with just one text box to search all the rows/columns in the entire table?

Or if it's not possible do you plan to add support to this feature?

what I want is something like this:

http://projects.gregweber.info/demo/flavorzoom.html

using table sorter plugin

**Comment by erikssonpontus** [comment]
Hi @Mottie! 
Can you add keyup for [http://mottie.github.io/tablesorter/docs/example-widget-filter-any-match.html](this)?
