### ISSUE TITLE
Columns only sort one way until it resets

### ISSUE THREAD

**Issue by braseidon** [Mottie/tablesorter#408]
I've got Tablesorter set up with the Pager and I'm loading the table data via JSON. The JSON is being populated by my MySQL database since there are way too many rows to sort at once (12k+ in the staging setup).

For some reason now after using JSON, the table will only sort one way until you click the header a third time and it resets. Then it'll sort the opposite way. I've checked my code multiple times and I can't see any issues with it - although I'm no JS pro.

URL to my table: http://www.domainsontap.com/domain-stock/

**Comment by dmarra** [comment]
There is a special place in hell for people who do not explain their solutions @braseidon

**Comment by braseidon** [comment]
@dmarra dude you're about 5 years late XD, there's no way I can remember, sorry.
