### ISSUE TITLE
sorting question - 2.13.3 not sorting <empty> items

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#419]
On 2.1.19, when sorting a date column where the values was empty (which would be at the bottom of the list by default), however the dataset of the empty values would be sorted.
Now on 2.13.13, the empty value dataset are no longer sorted... how do i return this back to how it was in 2.1.19?

Curious to know if there was an option that got changed / something got broken.

```
$(document).ready(function(){

    $("#showListTable:has(tbody tr)").tablesorter({
        sortList: [[5,1],[1,0]],
        textExtraction: {
            3: function(node) { return $(node).find("span").text().toLowerCase(); },
            4: function(node) { return $(node).find("span").text(); },
            5: function(node) { return $(node).find("img").attr("alt"); }
        },
        widgets: ['saveSort', 'zebra', 'stickyHeaders'],
        headers: {
            0: { sorter: 'isoDate' },
            1: { sorter: 'loadingNames' },
            3: { sorter: 'quality' },
            4: { sorter: 'eps' }
        }
    });

});
```

**Comment by kotarao** [comment]
Hi,

need help on grid tablesorter.

TableSorter is not working when date field first row is empty. when I enter some date on first field , sorting is working fine.

Please can you help me what I need to change here?

$(document).ready(
			$(function () {
                $('#GridViewSummaryResults').tablesorter({
                    widgets: ['zebra'], theme: 'blue', headers: { 0: { sorter: false } }, emptyTo: 'top',
                    textExtraction: {
1: function (node, table, cellIndex) { return $(node).find("span").text(); },
						2: function (node, table, cellIndex) { return $(node).find("span").text(); },
                        3: function (node, table, cellIndex) { return $(node).text(); },
                        4: function (node, table, cellIndex) { return $(node).text(); }						
					}

				});

			})
		);
		
My HTML code is 

<table class="grid tablesorter" id="GridViewSummaryResults" cellspacing="0" style="width: auto;">
	<colgroup>		
		<col width="85" />
		<col width="250" />
		<col width="100" />
		<col width="90" />
		<col width="70" />
	</colgroup>

	<thead>
		<tr>			
			<th>
				Order #
			</th>
			<th>
				Customer
			</th>
			<th>

				PO
			</th>
			<th>
				Date
			</th>
			<th>
				Total
			</th>
		</tr>
	</thead>

	<tbody>
		
			<tr>				
				<td  >
					<a href="javascript:alert('Order # SO71774')">SO71774</a>
				</td>
				<td>
					 <span id="GridViewSummaryResults_name1">Good Toys</span>					
				</td>
				<td>
					 <span id="GridViewSummaryResults_PO1">PO348186287</span>					
				</td>
				<td>
				
				</td>
				<td>
					$972.78
				</td>

			</tr>
						
		
			<tr class="even">				
				<td  >
					<a href="javascript:alert('Order # SO71775')">SO71775</a>
				</td>
				<td>
					 <span id="GridViewSummaryResults_name2">Cycle Clearance</span>					
				</td>
				<td>
					 <span id="GridViewSummaryResults_PO2">PO58159451</span>						
				</td>
				<td>
					01/06/10
				</td>
				<td>
					$2,313.13
				</td>

			</tr>
			
			
		
			<tr>				
				<td  >
					<a href="javascript:alert('Order # SO71776')">SO71776</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name3">West Side Mart</span>						
				</td>
				<td>
					<span id="GridViewSummaryResults_PO3">PO19952192051</span>	
					
				</td>
				<td>
					10/01/15
				</td>
				<td>
					$87.09
				</td>
			</tr>
			<tr class="even">				
				<td  >
					<a href="javascript:alert('Order # SO71777')">SO71777</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name4">Demand Distributors</span>
					
				</td>
				<td>
					<span id="GridViewSummaryResults_PO4">PO20097113391</span>						
				</td>
				<td>
					07/01/17
				</td>
				<td>
					$1,267.82
				</td>

			</tr>
			
		<tr>				
				<td  >
					<a href="javascript:alert('Order # SO71776')">SO71786</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name5">West Side Mart5</span>						
				</td>
				<td>
					<span id="GridViewSummaryResults_PO5">PO19952192041</span>	
					
				</td>
				<td>
					&nbsp;
				</td>
				<td>
					$87.09
				</td>
			</tr>
			<tr class="even">				
				<td  >
					<a href="javascript:alert('Order # SO71777')">SO71778</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name6">Demand Distributors6</span>
					
				</td>
				<td>
					<span id="GridViewSummaryResults_PO6">PO20097113396</span>						
				</td>
				<td>
					&nbsp;
				</td>
				<td>
					$1,267.82
				</td>

			</tr>
		<tr>				
				<td  >
					<a href="javascript:alert('Order # SO71676')">SO71786</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name7">West Side Mart8</span>						
				</td>
				<td>
					<span id="GridViewSummaryResults_PO7">PO19952192041</span>	
					
				</td>
				<td>
					07/01/10
				</td>
				<td>
					$87.09
				</td>
			</tr>

		<tr class="even">				
				<td  >
					<a href="javascript:alert('Order # SO71777')">SO71778</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name8">Demand Distributors6</span>
					
				</td>
				<td>
					<span id="GridViewSummaryResults_PO8">PO20097113396</span>						
				</td>
				<td>
					&nbsp;
				</td>
				<td>
					$1,267.82
				</td>

			</tr>
		<tr>				
				<td  >
					<a href="javascript:alert('Order # SO71676')">SO71786</a>
				</td>
				<td>
					<span id="GridViewSummaryResults_name9">West Side Mart8</span>						
				</td>
				<td>
					<span id="GridViewSummaryResults_PO9">PO19952192041</span>	
					
				</td>
				<td>
					12/15/09
				</td>
				<td>
					$187.09
				</td>
			</tr>
		</tbody>

</table>

**Comment by kotarao** [comment]
sorting screen shot for your reference:-

![image](https://user-images.githubusercontent.com/17110401/178567765-2fc2cd46-c71a-4c6d-b7ae-5eb2e08bac23.png)
