### ISSUE TITLE
mutiple tbody grouping and pager 

### ISSUE THREAD

**Issue by karthickkumarganesh** [Mottie/tablesorter#458]
Hi,

Am using mutiple tbody grouping and pager together and uses class="tablesorter-no-sort" to exclude the row count (group heading ) in paging  this work fine when we a single page ,

here i show 50 records per page , when i have 25 records , the group heading is excluded in paging ,with the same code when the records gets above 50 , the group heading also included in paging .

```html
<tbody class="tablesorter-no-sort overdue" id="heading_0" style="">
    <tr id="0_0" style="">
        <th colspan="8" align="left" style="padding-left:10px">Over Due</th>
    </tr>
</tbody>
```

**Comment by AntonyThason** [comment]
Hi @karthickkumarganesh 

I want to implement the pager with multiple tbody. I am not using AJAX data source. Please send me the sample code to achieve this functionality.

Thanks
Antony

**Comment by karthickkumarganesh** [comment]
Hi Antony ,

what exactly are you doing ,can you please mention more here

**Comment by AntonyThason** [comment]
Hi Karthik,

Thanks for your reply...

I have a single table which contains multiple tbody. I am using "tablesorter.js..." for sorting and paging functionalities for this table. Sorting worked well as we expected but pager not working properly. Below is the sample table we are using...

<table>
	<thead>
        <tr>
			<th>Name</th>
			<th>Start Date</th>
			<th>Dosage</th>
        </tr>
    </thead>
	<tbody class="priority">
		<tr>
			<td>Test1</td>
			<td>11/12/2012</td>
			<td>40 MG</td>
		</tr>
		<tr>
			<td>Test2</td>
			<td>11/12/2014</td>
			<td>40 MG</td>
		</tr>
		<tr>
			<td>Test3</td>
			<td>11/12/2012</td>
			<td>40 MG</td>
		</tr>
	</tbody>
	<tbody class="normal">
		<tr>
			<td>Test4</td>
			<td>11/12/2012</td>
			<td>40 MG</td>
		</tr>
		<tr>
			<td>Test5</td>
			<td>11/12/2014</td>
			<td>40 MG</td>
		</tr>
		<tr>
			<td>Test6</td>
			<td>11/12/2012</td>
			<td>40 MG</td>
		</tr>
		<tr>
			<td>Test7</td>
			<td>11/12/2012</td>
			<td>40 MG</td>
		</tr>
	</tbody>
</table>


Thanks
Antony

**Comment by Mottie** [comment]
Hi @AntonyThason!

As stated before, the pager only works with the first non-info tbody.

@karthickkumarganesh, I don't know why I didn't think of this before, but you could use the [`ajaxProcessing` option](http://mottie.github.io/tablesorter/docs/#object) to add the data to the separate tbodies, something like this:

```js
ajaxProcessing: function(result, table, xhr){
    if (result && 'data' in result) {
        var c = table.config,
            data = {};
        // "total" is a required property!
        data.total = result["total_rows"];

        c.$tbodies.eq(0).html( result.tbody1 );
        c.$tbodies.eq(1).html( result.tbody2 );

        return data;
    }
}
```

The `totalRows` value will not be accurate, because the pager will only page through that many rows, so maybe you can modify the `output` option to not include it.

Also, the `fixedHeight` will only work on the first tbody.

Other than that, I think it will work, but I haven't tested it.

**Comment by AntonyThason** [comment]
Hi Mottie,

I tried the above code but no luck. ajaxProcessing is never called for me. Shall i do anything more. I dont want to call any server side page. 

Thanks
Antony

**Comment by Mottie** [comment]
Ok, [here is an example](http://jsfiddle.net/Mottie/uwZc2/32/) using filltext.com as a data source, so the demo won't sort or allow filtering but it should give you an idea of how it could be done.

```js
$(function(){
	var $table = $('table'),
		size = 5;

	$table
		.tablesorter({
			theme: 'blue',
			widthFixed: true,
			widgets: ['zebra', 'columns']
		})
		.tablesorterPager({
			container: $(".pager"),
			size: size,
			// set to false otherwise it remembers setting from other jsFiddle demos
			savePages: false,
			ajaxUrl: "http://www.filltext.com/?callback=?",
			customAjaxUrl: function(table, url) {
				// need to dynamically update page size
				// since adding 'rows : size' in ajaxObject.data doesn't
				// dynamically update the size
                // take size X 2, so we grab extra data for the second tbody
				table.config.pager.ajaxObject.data.rows = table.config.pager.size * 2;
				return url;
			},
			ajaxObject: {
				data: {
					// rows   : size, // this doesn't work because size can't be updated dynamically
					'#'    : '{index}',
					'ID'   : '{randomNumberLength|3}',
					'First': '{firstName}',
					'Last' : '{lastName}',
					'State': '{usState|abbr}',
					'Info' : '{lorem|3}'
				}
			},
			ajaxProcessing: function (data, table) {
				if (data) {
					var col, row, txt,
                        c = table.config,
						// make # column show correct value
						index = c.pager.page,
						headers = [ '#', 'ID', 'First', 'Last', 'State', 'Info' ],
						len = headers.length,
						json = {},
						rows = [];
					size = data.length;
					for (row = 0; row < size; row++){
						txt = '<tr>';
						for (col = 0; col < len; col++) {
							txt += '<td>';
                            // make # column show correct index
							txt += col === 0 ? index * size + row + col + 1 : data[ row ][ headers[col] ];
							txt += '</td>';
						}
						rows.push( txt + '</tr>' );
					}
					json.total = 100; // only allow 100 rows in total
					json.filteredRows = 100; // no filtering
					json.headers = headers;
                    // add data to first tbody (only include 1/2 of the rows)
                    c.$tbodies.eq(0).html( rows.splice(0,size/2).join('') );
                    // add data to second tbody - c.$tbodies does not include info tbodies
                    // so the index only increases by one here
                    // add remaining rows
                    c.$tbodies.eq(1).html( rows.join('') );
					// Don't return rows with the json
					return json;
				}
			},
			output: '{startRow} to {endRow} of {filteredRows} ({totalRows})'
		});
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
