### ISSUE TITLE
pager not working with multiple tables in page. Only 1st 10 item visible

### ISSUE THREAD

**Issue by eyeris** [Mottie/tablesorter#478]
Hi I am using table sorter with bootstrap3
everything is ok when there is only one table in page 

like `$("table").tablesorter({......`

But when there are several tables with `<table>` in page. the pager doesnt work. the arrows are disabled and its strange that only the first 10 items are visible. No arrows are working.

I tried everything so far but failed. Can anyone help.

**Comment by teefars** [comment]
Hi, I was struck in the same issue, and I'm concerned about tons of tables on my application. So I made this simple code that gives IDs to tables, numbered as they appear in the code, and apply the specific pager to each of them.

```javascript
  $(".tablesorter table").each(function(pageTableCount){
    // Check if pageTableCount was initialized, and add 1 to its value
    pageTableCount !==null ? pageTableCount++ : 1;
    // Get the table and add ID with counter
    table = $(this);
    table.attr("id","table-sorter-"+pageTableCount);
    // Does the same with the pager
    pager = table.parent().find(".tablesorter-pager");
    pager.attr("id","table-sorter-pager-"+pageTableCount);
    // Initiate the tablesorter
    table.tablesorter()
    .tablesorterPager({
      container: "#table-sorter-pager-"+pageTableCount
    });
  })
```

**Comment by pearlbells** [comment]
Please check the live demo . Using tablesorter plugin you can add multiple tables in one page.
http://www.pearlbells.co.uk/table-pagination/

**Comment by Mottie** [comment]
Most of the code won't work with this forked version of tablesorter, but most of it would only require a simple change (for the pager Addon, not the widget).

## addPageList

In your version, it doesn't include filtered rows (using the filtered widget):

```js
function addPageList(table) {
  var i, len,
    c = table.config,
    p = c.pager;
  p.filteredRows = 0;
  normalized = c.cache[ 0 ].normalized;
  len = normalized.length;
  for ( i = 0; i < len; i++ ) {
    p.filteredRows += p.regexRows.test( normalized[ indx ][ c.columns ].$row[ 0 ].className ) ? 0 : 1;
  }
  p.filteredPages = Math.ceil( p.filteredRows / p.size );
  p.totalPages = Math.ceil(p.totalRows / p.size);
  c.container.find('ul').empty();
  for (i = 1; i <= c.filteredPages; i++) {
    c.container.find('ul').append('<li>' + i + '</li>');
  }
}
```

## setPage

In my forked version, you have access to these methods:

```js
$('table').trigger( method, [ value(s) ] );
```

* `pageAndSize` - See http://mottie.github.io/tablesorter/docs/#pageandsize
* `pageSet` - See http://mottie.github.io/tablesorter/docs/#pageset
* `pageSize` - See http://mottie.github.io/tablesorter/docs/#pagesize

## addClass

In my forked version, use `table.config.pager` instead of `table.config`

```js
function addClass(table){
    var p = table.config.pager;
    p.$goto.children().removeClass('active');
    p.$container.find('li').eq(p.page).addClass('active');
}
```

## click Event

```js
table.config.pager.$goto.on( 'click', 'li', function() {
  var pageNum = parseInt( $(this).html(), 10 ) - 1;
  $(table).trigger('pageSet', pageNum);
  return false;
});
```

**Comment by pearlbells** [comment]
Hi ,

thanks for the reply. I have used the tablesorter plugin to add sorting and pagination to one of my wordpress plugins. I am not sure which version i have used.

but my needs includes : 
i) Display multiple tables in one page
ii) Navigate to the selected page
iii) Change the navigation list dynamically based on the size selected

For that i have added the function that listed in my blog to meet my needs that seems working.

anyway thank you very much the reply.

Pearl

**Comment by SqualaDesign** [comment]
Hi, I have the same problem with the last version of tablesorter 2.31.1 
I created a web application in PHP that calls tables from database and includes the pager but I now created a page with 3 tables and only 1 pager is working.
I don't have any ID only classes
Thanks

**Comment by Mottie** [comment]
Hi @SqualaDesign!

Please make sure to initialize each pager separately - refer to [this example in the comments above](https://github.com/Mottie/tablesorter/issues/478#issuecomment-130422592).

**Comment by SqualaDesign** [comment]
> Hi @SqualaDesign!
> 
> Please make sure to initialize each pager separately - refer to [this example in the comments above](https://github.com/Mottie/tablesorter/issues/478#issuecomment-130422592).

I don't have different pager and also no of them has IDs

**Comment by Mottie** [comment]
Please share the code being used so we can help troubleshoot the problem.
