### ISSUE TITLE
Colspan causing sorting errors

### ISSUE THREAD

**Issue by derikb** [Mottie/tablesorter#485]
Had a table with a column that was a simple number. When I tried to sort on that column I kept getting a:

Uncaught TypeError: Object 0 has no method 'replace' jquery.tablesorter.js:1093

and then, if I clicked again, a:

Uncaught TypeError: Object 533 has no method 'replace'  jquery.tablesorter.js:1093

(the table had 534 rows, so that's the first and the last)

I notice issue #474 related to colspan and my table had a colspan for the column previous to my numeric column (that column was sorting fine). I removed the colspan and... everything works fine.

Here's the full error from Chrome's console (line numbers are to the unminizied version 2.14.5 file):

Uncaught TypeError: Object 0 has no method 'replace' jquery.tablesorter.js:1093
ts.sortNatural jquery.tablesorter.js:1093
ts.sortNaturalAsc jquery.tablesorter.js:1119
(anonymous function) jquery.tablesorter.js:699
multisort jquery.tablesorter.js:661
(anonymous function) jquery.tablesorter.js:637

**Comment by Mottie** [comment]
Well, I added very basic support for a table when an **entire column** is set with `colspan`... I have not thoroughly tested it with all widgets, but so far it is working well with the filter widget ([demo](http://jsfiddle.net/Mottie/856bzzeL/681/)).

It *should* work with `colspan`s in the `tbody`, but again, this has not been thoroughly tested. I added it to the master branch to hopefully get some help with that :)

**Comment by Mottie** [comment]
Closing this issue, please refer to #746 to monitor for updates on tbody colspan support.

**Comment by chandreshd** [comment]
Hello @Mottie 

i am having issue with colspan and rowspan

so kindly can you give me some hints to solve them

and also i am using colspan at any place like thead, tbody, tfoot

its something urgent for me

thanks
