### ISSUE TITLE
Widgets incompatibility: Scroller and (beta) reorder

### ISSUE THREAD

**Issue by NickWilde1990** [Mottie/tablesorter#495]
If the scroller widget is active then the reorder widget will totally fail.
I was just playing around and discovered that this afternoon (since November at least and still a problem with the latest master version

**Comment by Mottie** [comment]
Can you try [this demo](http://jsfiddle.net/Mottie/abkNM/4870/), which uses the [jQuery UI dragtable widget](http://akottr.github.io/dragtable/) (requires sortable), to see if it solves the issues you are having.

**Comment by Mottie** [comment]
The scroller is currently incompatible with the reorder widget. I've centralized all of the scroller widget incompatibilities into one issue (#1487). Please follow any progress there.
