### ISSUE TITLE
Column Selector addon and multiple headers

### ISSUE THREAD

**Issue by jorje29** [Mottie/tablesorter#501]
I've checked this example : http://jsfiddle.net/Mottie/3pS6v/4/

Is there a way to use Column Selector addon in a table with multiple headers like the one below ?

( I just present the thead of the table )

<thead>

        <tr>
            <th colspan='2'></th>
            <th colspan='5'>First</th>
            <th colspan='5'>Second</th>
        </tr>

        <tr>
            <th data-priority="critical">Name</th>
            <th data-priority="critical">Major</th>

            <th data-priority="6">Sex</th>
            <th data-priority="4">English</th>
            <th data-priority="5">Japanese</th>
            <th data-priority="3">Calculus</th>
            <th data-priority="2">Geometry</th>

            <th data-priority="7">Sex</th>
            <th data-priority="8">English</th>
            <th data-priority="9">Japanese</th>
            <th data-priority="10">Calculus</th>
            <th data-priority="11">Geometry</th>
        </tr>

</thead>

**Comment by Mottie** [comment]
Sorry for taking so long to get this done. This enhancement is currently available in the master branch.
