### ISSUE TITLE
scroll to row with stickyHeaders

### ISSUE THREAD

**Issue by pigobyte** [Mottie/tablesorter#537]
Hello everyone,
  I'm sorry for my english ..
could someone explain to me how to scroll a table with stickyHeaders and select a row using the row id?

thanks to all

**Comment by robertlight** [comment]
I think what we're looking for is something of the sort:

$('mytable').tablesorter().scrollRowToView(rowIndex)

perhaps with an optional animation?

**Comment by Mottie** [comment]
Hi @robertlight!

There are currently two demos on the [main wiki page](https://github.com/Mottie/tablesorter/wiki#misc) that have code to scroll a row to the top of the page (visible under the sticky header). Both currently require the row to have an ID:

* http://jsfiddle.net/Mottie/abkNM/896/
* http://jsfiddle.net/abkNM/2178/

There isn't one specifically for a row index, but I don't think it would be too difficult to modify that code.
