### ISSUE TITLE
tablesorterPager  linking to alternative ajaxprocessing and ajaxurl

### ISSUE THREAD

**Issue by norway77** [Mottie/tablesorter#540]
Hi Mottie,
I've been using the new custome pager (beta) and maybe this is the issue.  but I haven't set it up with the old paging but here is the problem.
I have the initial pager code set up going to a  
 ajaxUrl:pagingpage_1.asp?page={page}&size={size}&{sortList:col}
everything is working fine. I"m doing an ajax call with json and the rows and record cound come back and I have it set up to be doing serverside for all sorting and paging.

Now I have two tables on the page.  Table1 is effected by this pager.  Both table1 and table2 use tablesorter.    I have another button that updates both tables.  I go to a server and grab the json data and then update the tables.  

``` js
$("#table1")
.tablesorter()
.tablesorterPager({
    ajaxUrl: "bothTablesData.asp?page={page}&size={size}&  {sortList:col}",
    ajaxObject: {
        dataType: 'json'
    },
    ajaxProcessing: function(data){

        var $table1=$(data.table1var);
        var $table2=$(data.table2var);
        var $table1RowCount=$(data.totalRowsVar);

        $('#table2 tbody').html($table2);
        $('#table1 tbody').html($table1);
        $('#table2').trigger("update");
        return [ $table1,$table1RowCount[0]];
```

This all works fine, but then something funny happens.
The pager links.  1,2,3,4,5... and the number of recs links  10 20 30.. and the sort links all trigger both the 
`pagingpage_1.asp?page={page}&size={size}&{sortList:col}` and `"bothTablesData.asp?page={page}&size={size}&  {sortList:col}"`,
Now i realize it may be because i initialized the `.tablesortPager()` again on the button that updates both tables. But It's weird that it calls both of these ajaxurls and when
I use the prev,next << or >> it just calls the  `pagingpage_1.asp?page={page}&size={size}&{sortList:col}` 
I realize this is in beta and i can take the custom pager part out and try the old paging system but just wanted to run this by you and see if it makes any sense or if there is a reason for this happening or something I am doing wrong

I can give you better snippets of code if you need it.
best
danny

**Comment by Federico-G** [comment]
Hi Mottie,
I've been using the new pager widget and I get a similar problem with "oldAjaxSuccess" that process twice the pager_ajaxProcessing function. The problem I have is that the function is **called twice** but not in init, but every time I do a **sort**. With the workaround you post works great:
```javascript
ajaxObject : {
    dataType: 'json',
    success: { }
}
```

But it's only a workaround and the widget shouldn't do that.

Thanks


Trace:
* **First call**
ts.pager.renderAjax @ tablesorter-pager.js:644
ts.pager.getAjax.p.ajaxObject.success @ tablesorter-pager.js:782
ts.pager.getAjax.p.ajaxObject.success @ tablesorter-pager.js:785

* **Second call**
ts.pager.renderAjax @ tablesorter-pager.js:644
ts.pager.getAjax.p.ajaxObject.success @ tablesorter-pager.js:782
