### ISSUE TITLE
Sticky header - full height wrapper

### ISSUE THREAD

**Issue by ric79** [Mottie/tablesorter#564]
Hello everybody!

I would know if sticky header (cfr; http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html) could you be user with a wrapper having
- x scroller enabled (if necessary)
- no y-scrolling (full height!)

I'm using Bootstrap 3 and, with other tables, I'm used to wrap them with **table-responsive** class (cfr: http://getbootstrap.com/css/#tables-responsive). 

Is there a way to obtain the same effect?

Riccardo

**Comment by JanOonk** [comment]
I think I am in the same boot because I have my table inside a div which takes as much height as possible (height: 100%) so it is not a fixed height as in your examples http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html
I really would like to have this feature. @ric79 did you manage to find a solution or @Mottie is this feature still on your radar?

**Comment by Mottie** [comment]
Hi @JanOonk!

You can do it now using the `stickyHeaders_attachTo` and `stickyHeaders_yScroll` options.

```js
$('#table').tablesorter({
    theme: "bootstrap",
    widthFixed: true,
    headerTemplate: '{content} {icon}',
    widgets: ['zebra', 'stickyHeaders', 'uitheme'],
    widgetOptions: {
        stickyHeaders_attachTo: '.table-responsive',
        stickyHeaders_yScroll: $(window)
    }
});
```

I had to fix a few minor bugs to get the header to work properly. Hopefully adding a `position:relative` style to the `.table-responsive` div won't break anything.

Oddly, I have the demo working perfectly locally, but when I created this ([demo](http://jsfiddle.net/856bzzeL/28/)), the header shifts and resizes incorrectly. I'll try to look at this again tomorrow.

Anyway, you can check out the updates in the master branch.

**Comment by JanOonk** [comment]
Hi,

thanks for your reply and effort. I updated your example to match my case and tried to minimize the test case as good as possible:
http://jsfiddle.net/856bzzeL/30/

It doesn't work yet. Hopefully this testcase can help you.

**Comment by Mottie** [comment]
Oh wait, it does work!

http://jsfiddle.net/856bzzeL/32/

The problem was that the demo was pointing to jQuery v3.0.0-pre which was not calculating the widths the same as the current version. When I change the version to 2.1.0, it works fine.

**Comment by JanOonk** [comment]
Ok now your example works, but mine (also when you change jQuery to 2.1.0) still doesn't :(

**Comment by Mottie** [comment]
@JanOonk! I'm not sure what to make of your demo... it's not really a full height, scrolling with the page kind of demo. I wonder if the [scroller widget](http://mottie.github.io/tablesorter/docs/example-widget-scroller.html) might work better for you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
