### ISSUE TITLE
Pager resets to page one after table rebuild

### ISSUE THREAD

**Issue by dandanknight** [Mottie/tablesorter#565]
Hi Mottie,

I've just updated to 2.15.12 from 2.13, the pager plugin I was using  (jquery.tablesorter.pager.js) was dated 5/27/13.

I have a table with a large number of items, an ajax call refreshes the table every few seconds, and rebuilds the entire table in the fashion...

```
$.ajax({
    type:'GET',
    url: 'some/url',
    success:function(data){
         var tbl_body = "";
         $.each(data, function(){
               tbl_body += makeRow(this);
          }); 
          $("#dbTable tbody").html(tbl_body);
          $("table").trigger("update");
    }
});
```

With the new pager plugin, after this happens, the pager goes back to page one as soon as the trigger update is executed, whereas the old pager plugin maintained the page that it was previously on.

Is this something I am doing incorrectly, has a feature changed, or is it a bug?

I am initializing my table as follows....

```
    $("#dbTable").tablesorter({
    theme : "blackice",
    widthFixed: false,
    cssChildRow: "tablesorter-childRow",
    headerTemplate : '{content} {icon}',
    widgets : [ "uitheme", "filter", "resizable", "saveSort", "zebra"],
    widgetOptions : {
        filter_ignoreCase : true,
        filter_reset : ".reset",
        resizable : true,
        resizable_addlastcolumn : true
    }}).tablesorterPager({
        container: $(".pager"),
        size : 10,
        cssGoto  : ".pagenum",
        savePages : true,
        removeRows: false,
        updateArrows: true,
        output: '{startRow} to {endRow} of {filteredRows} ({totalRows} total)'
    }));
```

I'd very much appreciate your help/input.

Thanks.

**Comment by Yogananda-st** [comment]
Thanks you so munch
