### ISSUE TITLE
The option processAjaxOnInit has no effect when rows is a jQuery object

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#572]
I may not have a good understanding of what `processAjaxOnInit` is supposed to do, but it looks like it is not invoked if the rows returned from `ajaxProcessing` are a jQuery object based on the following code from around line 488 of `widget-pager.js`:

``` js
//...
d = result.rows
//...
if (d instanceof jQuery) {
    // append jQuery object
    c.$tbodies.eq(0).empty().append(d);
} else if (l) {
    // build table from array
    for ( i = 0; i < l; i++ ) {
        tds += '<tr>';
        for ( j = 0; j < d[i].length; j++ ) {
            // build tbody cells; watch for data containing HTML markup - see #434
            tds += /^\s*<td/.test(d[i][j]) ? $.trim(d[i][j]) : '<td>' + d[i][j] + '</td>';
        }
        tds += '</tr>';
    }
    // add rows to first tbody
    if (wo.pager_processAjaxOnInit) {
        c.$tbodies.eq(0).html( tds );
    } else {
        wo.pager_processAjaxOnInit = true;
    }
}
```

But I thought that ajax would have been stopped well before this since by this point the rows have already been fetched by ajax, so no reason not to add them to the table. 

Here's an example of how it works now and the problem I was hoping to salve with this option:
1. Go to web page which is a php file. This file fetches rows from a database and displays them in a table in HTML
_(this is where I thought the `processAjaxOnInit` option would prevent ajax from running, but the option comes into play later)_
2. With tablesorter on, `customAjaxUrl` will now run and call the php file again, fetching the same rows again
3. `ajaxProcessing` will manipulate the result
4. `processAjaxOnInit` will prevent rows from being added if rows is not an object when rendering the ajax result

What I have done to avoid the double-fetching of rows is alter the php code in step one so that it doesn't fetch the rows initially, instead they are fetched when the php file is called again in step two (I include a parameter in the custom ajax url that tells the php file it's an ajax call). I was hoping that workaround wouldn't be needed and that this option would simply cause step 2 to not run upon initialization of the table.

Not sure if this is a bug report or a wish, but hopefully it makes sense.
Regards,

**Comment by Mottie** [comment]
I just added an option named `initialRows` (in the master branch). When `processAjaxOnInit` is `false` and this option is set, no initial ajax call to the server is done ([demo](http://jsfiddle.net/Mottie/uwZc2/55/)):

```js
$(function(){
  $table.tablesorter({
    widgets: ['pager'],
    widgetOptions : {
      pager_processAjaxOnInit: false,
      pager_initialRows: {
        // these are both set to 50 initially
        // the server can return different values
        // and the output will update automatically
        total: 50,
        filtered: 50
      },
      // other ajax settings...
    }
  });
});
```
