### ISSUE TITLE
Range-Filter on childrows?

### ISSUE THREAD

**Issue by TheMassassian** [Mottie/tablesorter#574]
Hello,

is there a way to use the rangefilter on childrow elements?
I have a table with a column 'value', each value is a numeric attribute.
Some of the rows have childrow(s). When I filter for the exact value of a childrow I get the parent row, but when I use a rangefilter like 2000 - 6000 I won't get the parent row.

example

Est_Number Inv_Number Value
parent: 20120xx        | 2012011  |    1000
child:                     | 2012012   |    5000

**Comment by antoinegoutagny** [comment]
+1 for child row filtering per column instead of all content. That would be a great improvement!

**Comment by Mottie** [comment]
Ok, I finally got around to making the filtering of child row content work!

The only caveat I can think of right now is that if the child row contains any `colspan` or `rowspan`, the filtering may not align to the correct column... I may have to add a `data-column` to each child row to ensure that the correct column is being filtered; but I'll leave that for another day.
