### ISSUE TITLE
migrating to jQuery 1.9.x

### ISSUE THREAD

**Issue by thezoggy** [Mottie/tablesorter#586]
upgrading a project to newer jquery version, going through local code and libs to see what we need to address before making the switch.. 

https://github.com/jquery/jquery-migrate/blob/master/warnings.md

.parseJSON -- https://github.com/jquery/jquery-migrate/blob/master/warnings.md#jqmigrate-jqueryparsejson-requires-a-valid-json-string

`jquery.tablesorter.widgets.js` - I parseJSON being used here which may need the || "null" to make it work the same across all jquery versions?

and
https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-build-table.js#L35 ?

**Comment by Mottie** [comment]
Hey zoggy!

Now that I look back at my first comment, I didn't have the `null` wrapped in quotes; but I guess [it doesn't matter](https://github.com/jquery/jquery-migrate/blob/master/test/core.js#L154).

Anyway, I was just testing the storage and build widgets with migrate plugin v1.2.1 and I don't see any warnings now.  I'll go ahead and make these changes, just-in-case. Sorry for taking so long to fix this issue.
