### ISSUE TITLE
Chart capabilities for Tablesorter

### ISSUE THREAD

**Issue by Tedd22** [Mottie/tablesorter#612]
Lot of people needs a graphic representation of their data. I think it would be a great plus for tablesorter if it includes a function for converting table to chart. It could be a connector with a jquery open source charting tool (I like very much <a href="http://www.flotcharts.org/">Flot</a>). When clicking on a "display chart" button, the data of the table would be passed to the charting tool and the chart would appear on the same page than the table.

I realize this is a big challenge and I'm sure that a function like that would answer a real need and would make Talbesorter yet more complete and attractive !

What do you think about the idea ?

Thanks in advance !

**Comment by Mottie** [comment]
A chart widget which outputs data for Google charts, Highcharts and FusionCharts is now available - see [the chart widget demo](http://mottie.github.io/tablesorter/docs/example-widget-chart.html).

Please post a request here if you need to add support for other charting plugins... an example of the data format would be very helpful.
