### ISSUE TITLE
External select

### ISSUE THREAD

**Issue by Tedd22** [Mottie/tablesorter#671]
Hi,

I'd like to use external select (dropdown list), like external input. The select should work exactly the same way select does inside the table. It should list all the values of the column.

Is it a way to do this ?

Thanks in advance !

Ted

**Comment by JTatum95** [comment]
Hey @Mottie it looks like your fiddle is broken. It is pulling all of the items from the column as [Object object] which is a rather unhelpful datatype for sorting. Shouldn't be too bad of a fix.

**Comment by Mottie** [comment]
Updated! http://jsfiddle.net/Mottie/ahk7cgqp/

**Comment by Mottie** [comment]
The `getOptionSource` function isn't documented, so I forgot about this issue. I'll add documentation for it in the next update.
