### ISSUE TITLE
Double click required to click link in table after filter

### ISSUE THREAD

**Issue by dmmusil** [Mottie/tablesorter#685]
I use the tablesorter, filter, and pager together. When I filter one column and then attempt to click a link in the filtered table, nothing happens except that the filter input loses focus. Clicking a second time activates the link and takes me to its destination.

Is this a bug or is there a setting I should be using to avoid this?

Here is my setup:

```
    $(function () {
    var pagerOptions = {
        container: $(".pager"),
        output: '{startRow} - {endRow} / {filteredRows} ({totalRows})',
        removeRows: false,
        fixedHeight: true,
        cssGoto: '.gotoPage',
        size: 20,
        cssPageSize: '.pagesize',
    };

    $("#jobs").tablesorter(
        {
            textSorter: {
                0: $.tablesorter.sortNatural
            },
            sortList: [[0, 0]],
            widgets: ["filter"],
            widgetOptions: {
                filter_columnFilters: true,
                filter_ignoreCase: true,
                filter_hideFilters : false
            }
        }
    ) // Make the table sortable



    .tablesorterPager(pagerOptions);
});
```

**Comment by miksteri** [comment]
I'm still experiencing this issue. I have tried earlier and latest versions.

So, when i search and try to click item link it does not work. If i search and click anywhere else first and then click link it works, but not straigth when clicking a item link while focus is in search box.

**Comment by Mottie** [comment]
Hi @miksteri!

Can you provide a demo if this issue? If the links require javascript to work, then it would be best to use [delegated event binding](http://api.jquery.com/on/#direct-and-delegated-events). Here is an example:

```js
$( 'table' ).on( 'click', '.external-links', function() {
    // do something
});
```

**Comment by miksteri** [comment]
Now I found a version that the links works correctly:
/*! tableSorter 2.16+ widgets - updated 4/23/2014 (v2.16.0)

I don't know the reason why other version didn't work.

**Comment by Mottie** [comment]
Please provide a demo of the issue.
