### ISSUE TITLE
Initial size of page is half of intended size

### ISSUE THREAD

**Issue by aruballo** [Mottie/tablesorter#700]
Hello,

I am using the pager plugin with your tablesorter (tablesorter works great!). I have set the size to 10; however only 5 initial rows ever show up. If I continue on paging, only 5 rows continue showing up. However, once I hit one of the columns to sort the page, the table shows the correct page size. If I click the paging arrows afterwards, they also show the correct page size. So in other words, my table only seems to show half the intended page size, until a column is clicked for sorting. At which point, the page sizes stay the correct size. I tested this by changing the sizes; 20 shows 10, 30 shows 15, etc. 

the table i am using follows the exact format from the examples, my call to the plugin and sorter is as follows:

$("#transTable").tablesorter().tablesorterPager({container: $("#pager"), size: 10}); 

Thanks!

**Comment by Mottie** [comment]
Is this issue resolved? I still can't duplicate the problem reported here... is there a way you can provide a demo?

Maybe you can use [this demo](http://jsfiddle.net/Mottie/uwZc2/) to duplicate it? This demo uses filltext.com to use json to populate the table, so it isn't possible to sort or filter.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
