### ISSUE TITLE
AJAX Filtering occasionally removes filter text

### ISSUE THREAD

**Issue by devnuhl** [Mottie/tablesorter#733]
I see this on some pages where we use tablesorter, and less or not at all on others. I thought it was not happening with the newer version (2.17.8), but seems it still is. When filtering an ajax'd table, while typing, the filter text will sometimes lose a few characters. My guess, at the moment, is that during a keyup event that is sending the request to the server, it is writing the text sent as the filter to the field, which can result in loss of typed text beyond what was sent. 

Perhaps ~~there could be a 500ms delay before the request is sent, or~~ it could simply not overwrite the filter text with what was used to filter (if that is actually the case). I just tried to read through the code for widgets, and I see a few places where the filters are being set, but fairly sure that sticky headers are not in use. There is only one place in the filter widget that sets them, and not sure if that is relevant either. I've confirmed that at the time of event firing, sticky headers are not enabled.

Is this a side effect of having filter_liveSearch enabled, and does it need to overwrite the filter text in the input? We would like to not disable the live search, but we don't want to get bad results because we lose text while typing either.

**Comment by Mottie** [comment]
This is all fixed now! :smiley_cat:
