### ISSUE TITLE
Idea: Web workers for sorting

### ISSUE THREAD

**Issue by brainfoolong** [Mottie/tablesorter#736]
I love this tablesorter. But at some point it will freeze the browser because of the big amount of data. For example a table with 2000 rows takes a few seconds to be sorted, until the sort is finished the browser will be freezed. 
In the case when a user change manually the sort by clicking on a header it's intended to take some time. But especially in the case of dynamically and on page startup sort this is a bit annoying.
With the new technology of "Web Workers" we can avoid this problem. Just putting the heavy work on a second thread will prevent browser from freezing.
Maybe you should consider this, it's a massive improvement for the tablesorter.

**Comment by marcinrosinski** [comment]
Hi guys, do you have any ETA on that, it would be very cool feature

**Comment by Mottie** [comment]
I have looked into it, but I would need figure how to get around a few issues before I can even get it working. And I am busy with lots of other things that have higher priority.

So, I can't give you a definite timeline... ETA: pending.
