### ISSUE TITLE
Weird sort behavior when table rows contains rows with colspan

### ISSUE THREAD

**Issue by gahataka** [Mottie/tablesorter#746]
I have a table where I load this configuration : 

```js
{
    headers:{
        0:{sorter:false},
        1:{sorter:'text'},
        2:{sorter:'text'},
        3:{sorter:'text'},
        4:{sorter:false},
        5:{sorter:false},
        6:{sorter:'digit'},
        7:{sorter:'procent'},
        8:{sorter:false},
        9:{sorter:false}
    },
    sortList:[[10,1],[7,0]],     
    widgets: ["stickyHeaders","zebra"],
    widgetOptions : {
        stickyHeaders : "tablesorter-stickyHeader"
    }
};
```

I update the table data via Ajax where I append the data, and then I do : 

```js
jq_table.get()[0].tBodies[0].innerHTML = buffer;
jq_table.trigger("update"); 
```

the table structure looks like this : 

```html
<table>
	<thead>
		<tr>
			<th rowspan="2">...</th>
			<th rowspan="2">...</th>
			<th rowspan="2">...</th>
			<th rowspan="2">...</th>
			<th colspan="3" rowspan="2">...</th>
			<th colspan="3">...</th>
			<th>...</th>
		</tr>
		<tr>
			<th>...</th>
			<th>...</th>
			<th>...</th>
		</tr>
	</thead>
	<tbody>
		<tr class="odd">
			<td>...</td>
			<td>...</td>
			<td>...</td>
			<td>...</td>
			<td>...</td>
			<td colspan="2">...</td>
			<td>...</td>
			<td>...</td>
			<td>...</td>
			<td>...</td>
		</tr>
	</tbody>
	<tfoot>
	</tfoot>
</table>
```

**Comment by Mottie** [comment]
Well, I added very basic support for a table when an **entire column** is set with `colspan`... I have not thoroughly tested it with all widgets, but so far it is working well with the filter widget ([demo](http://jsfiddle.net/Mottie/856bzzeL/681/)).

It *should* work with `colspan`s in the `tbody`, but again, this has not been thoroughly tested. I added it to the master branch to hopefully get some help with that :)

Any `rowspan` in the `tbody` will not work as expected... yet.

**Comment by debonil** [comment]
Hi,
I have a td with colspan in tfoot, but tablesorter is adding "filtered " class in that. How to get rid of this?

**Comment by Mottie** [comment]
Hi @debonil!

It sounds like the HTML might be malformed. Please check it. If that isn't the problem, then please modify [this demo](https://jsfiddle.net/Mottie/bbxxomhx/424/) to show the problem.

**Comment by Mottie** [comment]
Hi @chandreshd!

How are you using the `colspan`? An example of the HTML structure would help.

This fork of tablesorter will work with `colspan`s in the `thead`, `tbody` and `tfoot` as long as you're consistently maintaining the column structure, as seen in https://github.com/Mottie/tablesorter/issues/746#issuecomment-61564337. Or, as long as the number of columns match *everywhere*.

It won't support `rowspan`s in the `tbody`. If you need to do this, then add a [child row class name](https://mottie.github.io/tablesorter/docs/) to the attached rows, but these child rows won't sort within their block.

**Comment by chandreshd** [comment]
<table class="table table-bordered data-table dataTable tablesorter" id="tableId" cellspacing="0" cellpadding="0">
    <thead>
        <tr>
            <th class="country_heading" rowspan="2" colspan="2">A</th>
            <th class="tablet_hide phone_hide" rowspan="2">B</th>
            <th class="phone_hide" rowspan="2">C</th>
            <th class="shrink" colspan="3" data-sorter="false">D</th>
            <th class="shrink" colspan="3" data-sorter="false">E</th>
            <th class="phone_hide" rowspan="2">F</th>
            <th class="phone_hide" rowspan="2">G</th>
            <th class="tablet_hide phone_hide" rowspan="2">H</th>
            <th rowspan="2" class="phone_hide">I</th>
        </tr>
        <tr>
        	<th class="phone_hide">D1</th>
            <th class="col5">D2 %</th>
            <th class="col6">D3 %</th>
            <th class="phone_hide">E1</th>
            <th class="col8">E2 %</th>
            <th class="col9">E3 %</th>
        	
        </tr>
    </thead>
    <tbody>
        <tr>
            <td title="Aus"><img src="" alt=""></td>
            <td class="phone_hide country_col">Aus</td>
            <td class="tablet_hide phone_hide">1</td>
            <td class="phone_hide">BBBB</td>
            <td class="phone_hide">
            	<div style="cursor:pointer;" onclick="">1</div>
            </td>
            <td class="error">0%</td>
            <td class="good">97.14%</td>
            <td class="phone_hide">
            	<div style="cursor:pointer;" onclick="">0</div>
            </td>
            <td class="good">100%</td>
            <td class="good">100%</td>
            <td class="phone_hide">
            	<div style="cursor:pointer;" onclick="">0</div>
            </td>
            <td class="phone_hide">1</td>
            <td class="tablet_hide phone_hide">2</td>
            <td class="phone_hide">22</td>
        </tr>
                                    
    </tbody>
    <tfoot class="tablesorter-ignoreRow">
      <tr class="total_row">
            <td class="total_heading" colspan="2">Total</td>
            <td class="tablet_hide phone_hide"></td>
            <td class="phone_hide"></td>
            <td class="phone_hide">1</td>
            <td class="error">0%</td>
            <td class="good">99.88%</td>
            <td class="phone_hide">0</td>
            <td class="good">100%</td>
            <td class="good">99.94%</td>
            <td class="phone_hide">0</td>
            <td class="phone_hide">1</td>
            <td class="tablet_hide phone_hide">2</td>
            <td class="phone_hide">22</td>
        </tr>
    </tfoot>
</table>

**Comment by Mottie** [comment]
I added the HTML to [this demo](https://jsfiddle.net/bbxxomhx/1406/); please describe the issue you're seeing. It seems to be working.

**Comment by chandreshd** [comment]
Column with percentage sign not sorted properly 
And where i have to do what modifications kindly let me know

**Comment by Mottie** [comment]
Can you describe in detail what you're seeing... in the demo, all columns with a percentage sign are sorting properly for me.

**Comment by chandreshd** [comment]
Ok your demo looks ok now

But can you once say what was problem in my html and what I have to change to make it work, I don't want to use any theme or widget

**Comment by Mottie** [comment]
I didn't change the basic html, I only duplicated and modified the content of the rows in the `tbody`.

**Comment by chandreshd** [comment]
Hi @Mottie 

I have triggered out solution actually all was well, just at the top country th, colspan was not attaching through class, so i did that manually there and all sorting working perfect everywhere

Thanks a lot for your support
