### ISSUE TITLE
User selected columns to filter

### ISSUE THREAD

**Issue by Mottie** [Mottie/tablesorter#747]
I need some ideas, or maybe some best practices on how I should implement this feature.

Basically, if there is an external filter which is set to `data-column="all"` ([demo](http://jsfiddle.net/abkNM/4367/)), I want the user to be able to specify which column(s) they want to search.

These are some ideas on how a user could specify the desired column when searching for "abc" in the first column AND "10" in the second:

* `0:abc && 1:10`
* `AlphaNumeric:abc && Numeric:10` (column titles will likely be case insensitive)
* `{AlphaNumeric}abc && {Numeric}10`
* `abc{0} && 10{1}`
* `0+abc && 1+10` (trying to use selectors that don't match any of the filter flags; so don't use `=` or `-`)

Currently if you search for "abc && 10" in the demo, you get 3 results, one of which includes "ABC 10" in the first column with "87" in the second.

**Comment by MaksimProgr** [comment]
You haven't implemented yet. If you are not working on this feature right now, can I try to implement this?

**Comment by Mottie** [comment]
Hi @MaksimProgr!

Sure, I just haven't figured out the best way to implement it.

**Comment by Mottie** [comment]
Completed thanks to @MaksimProgr!

See a [working demo here](http://mottie.github.io/tablesorter/docs/example-widget-filter-any-match.html#anymatch_searches)
