### ISSUE TITLE
Rowclick is fired twice?

### ISSUE THREAD

**Issue by briankitt** [Mottie/tablesorter#750]
I snagged this sample code form the internet as a widget for 'rowclick'.  However, I notice it is always getting fired twice.  I've looked through the code, but I can't seem to find out why?  I have modified it to deal with the double click, but it would be really nice if It only fired one time.

    $.tablesorter.addWidget({
        id: "rowClick",
        format:
        function (table) {
            $('tr:visible', table).click(function () {
                if (!$(this).hasClass("tablesorter-filter-row") && !$(this).hasClass("tablesorter-headerRow"))  // for some reason when you type in a filter, it drives the 'on click'
                {
                    var MemberId = $(this).children("td").first().html();
                    if (MemberId != lastMember) {  // For some reason this clicks twice
                        lastMember = MemberId;
                       document.location = '/Member/MSIHSD/' + MemberId;
                        setInterval(function () { lastMember = '' }, 1000);  // this resets the 'last member'
                    }
                }
            });
        }
    });

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
