### ISSUE TITLE
Cannot read property '1' of undefined

### ISSUE THREAD

**Issue by binhwpo** [Mottie/tablesorter#751]
Please have a look at this issue when a table has only heading but no rows. Thanks :)

![screen-shot-2014-10-23-at-5 43 08-pm](https://cloud.githubusercontent.com/assets/7647566/4751725/ac32f1c0-5aa1-11e4-97bc-f3868e19a166.jpg)

**Comment by vashisth00** [comment]
jquery.tablesorter.min.js:4 Uncaught TypeError: Cannot read property '1' of undefined
    at multisort (jquery.tablesorter.min.js:4)
    at jquery.tablesorter.min.js:4

In the elfsight-instagram-feed#/widgets/
