### ISSUE TITLE
Caching not working for chrome

### ISSUE THREAD

**Issue by gogreenit** [Mottie/tablesorter#761]
Hi, I have been using Mottie's tablesorter for a while now for a web app. One of my users just just brought it to my attention that it does not save the cached query on Google Chrome. Does anyone else have this issue?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by gogreenit** [comment]
Yes it is. So sorry I didn't reply
