### ISSUE TITLE
Update event triggers sort events when serverSideSorting == true

### ISSUE THREAD

**Issue by dheim** [Mottie/tablesorter#764]
In a table with server side sorting, the click on a table header has to trigger a table update. This can be done by binding the sortEnd event.

After the data is updated, the sort events are triggered again even if serverSideSorting is set to true. This leads to an endless loop, because the sortEnd event triggers an update again.

Suggestion: checkResort(Line 812) should set the resort flag to false if serverSideSorting == true.

Workaround:
dataTable.trigger('update', !dataTable[0].config.serverSideSorting);

**Comment by Mottie** [comment]
Thanks again for reporting this. Sorry for taking so long to fix it.

This fix is available within the working branch at this time. Whenever the next update is ready, it will be included.
