### ISSUE TITLE
Processing formatting not working on sort with ajax

### ISSUE THREAD

**Issue by lindonb** [Mottie/tablesorter#769]
The `table-processing` formatting isn't applied when sorting with ajax. It works when filtering is applied.

**Comment by lindonb** [comment]
Hi @Mottie!

I'm still having problems with this. Could you tell me where it is in the code - perhaps I can troubleshoot.

**Comment by Mottie** [comment]
Hmm, oh... the delay in adding the processing class name to the headers is only used when  the `sortBegin` event is fired ([line 1155](https://github.com/Mottie/tablesorter/blob/master/js/jquery.tablesorter.js#L1155)).

The code you are interested in is in the pager. At the top of the `getAjax` function ([line 714 of the pager widget](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-pager.js#L714)) - it checks the `config.showProcessing` option setting, then calls the code to add the icons.

```js
if (c.showProcessing) {
	ts.isProcessing(table, true); // show loading icon
}
```

Then in the `renderAjax` function ([line 680 of the pager widget](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-pager.js#L680)) is the check to remove the processing class names:

```js
if (c.showProcessing) {
	ts.isProcessing(table); // remove loading icon
}
```

**Comment by lindonb** [comment]
Thanks @Mottie!

When I step through with the debugger it looks like it's working, but in real time it doesn't. The formatting works fine when I filter, but not when I sort. I'm using the processing class to apply an opacity of .25 to `table.processing-class body tr td`, rather than loading an icon. Can't figure out what the problem is but I have an easy workaround so will move on for now!
Thanks for your help.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
