### ISSUE TITLE
Improvement: add alternate value to sort a column by

### ISSUE THREAD

**Issue by jvetyska** [Mottie/tablesorter#77]
The idea:
I have a lot of text in a table cell (or doe to space issues need to cram multiple values into one cell, or the data format is strange and don't want to figure out a parser, or the data is dynamic, etc), and I want to sort the column based on a easily parsed and predictable value.

The solution:
Easy solution, only two lines of code:
function getElementText(table, node, cellIndex) {
    var text = "", t = table.config.textExtraction;
    if (!node) { return ""; }
    // NEW: check for data-sort-value attribute for alternate sort value
       var altText = $(node).data("sortValue");
       if (typeof altText != "undefined" && altText != "") {return altText;}
       ....

And in my table I just add the property to the row with the tricky data:

<tr>
<td data-sort-value="135"><span>ID: </span>FQ54TRV<br><span>Name:</span>Somebody</td>
...

This simple addition has many uses and it's optional so no changes are needed.
This also enables the users to separate sortable values from displayable content.

I've had to add this to every new version of tablesorter, because it is so powerful, yet so simple.
Please add it in so I don't have to keep changing the source every time I want to upgrade to the latest version.

Thanks.

**Comment by baszero** [comment]
I think as of v2.16 it is supported, right? I only mention this here, as Google finds this issue first when asking for sorting by attribute ;-)

`<td data-text="1">First repository</td>`
This option only works when the `textExtraction` option is set to `"basic"`.

See https://mottie.github.io/tablesorter/docs/#Configuration for full documentation
