### ISSUE TITLE
Custom parser doesn't work properly after tablesorter updateAll event

### ISSUE THREAD

**Issue by billonas** [Mottie/tablesorter#772]
Hello mottie. Thanks for the great plugin.

I am facing a problem not with your tablesorter but with the parser i add on it. When i update table (because i delete the old rows and add other rows depending on a filter), then the parser i have added doesn't work properly. It seems to have a problem (after updateAll) on updateCell event.
I saw your post here: 
http://stackoverflow.com/questions/17653473/tablesorter-does-not-work-when-i-add-more-columns
Your are saying that a problem is caused with the parser and the updateCell event. Is there any way that you know of to fix it. I will give you a sample of  my code.
After the user chooses a filter (outside the table) then an ajax call is made to server and a new set of rows is returned to be shown on the table. Here is my code: 

**Function that runs on successfull response:**

     function(response){
						var table = $('.dataTable');
						var numRows = response.rows.length; 
						//empty table with old data
						table.empty();

						//add header Row to newTable
						addEquipmentHeaderRow(table);

						//add body Rows to new
						for(var i = 0 ; i<numRows ; i++)
						{
							addBodyRows(table, response.rows[i]);	
						}
						
						//remove CheckboxParser
						table.removeClass('hasCheckbox')
						//update Tablesorter for table with newdata

						var resort = true;

						table.trigger('updateAll', [resort]);
    },
**addHeaderRow function:**
		
     function addHeaderRow(table, row) {
			table.append(
				$('<thead />').append(
				'<tr>\n\
				<th class="sorter-checkbox" data-placeholder="Επιλογή">Επιλογή εμφανιζόμενων  <input type="checkbox"></th>\n\
				<th data-placeholder="Τίτλος" >Τίτλος</th>\n\
				<th data-placeholder="Όνομα κατόχου">Κάτοχος</th>\n\
				</tr>'
				)
			);	
		}

**addBodyRows function:**

        function addBodyRows(table, row) {
		
			var holderValue;
			if(row["Equipment"]["holder"] === null)
			{
				holderValue = "Διαχείριση";
			}
			else
			{
				holderValue = '<a href="/users/show/'+row["User"]["id"]+'">'+row["User"]["name"]+' '+row["User"]["surname"]+'</a>'; 
			}
			table.append(
				'<tr role="row">\n\
				<td><input type="checkbox"><div class="coloringCategory" style="background-color:#'+row["Category"]["coloring"]+'"></div><input type="hidden" id="id" value='+row["Equipment"]["id"]+'></></td>\n\
				<td>'+row["Equipment"]["title"]+'</td>\n\
				<td>'+holderValue+'</td>\n\
				</tr>'
			);	
		};

**My custom Parser:**

       var myCustomParser = {
		    	    	id: 'myCustomParser',
		    	    	is: function(s) {
		    	    	    return false;
		    	    	},
		    	    	format: function(s, table, cell, cellIndex) {
		    	    	    var $t = $(table), $c = $(cell), c,
		
		    	    	    // column containing all of the checkboxes (zero-based index)
		    	    	    columnWithCheckboxes = 0,
		    	    	    // resort the table after the checkbox status has changed
		    	    	    resort = false;
		
		    	    	    if (!$t.hasClass('hasCheckbox')) {
		    	    	        $t
		    	    	        .addClass('hasCheckbox')

		    	    	        // make checkbox in header set all others
		    	    	        .find('thead th:eq(' + columnWithCheckboxes + ') input[type=checkbox]')
		    	    	        .bind('change', function(){
		    	    	                 c = this.checked;
		    	    	                $t.find('tbody tr:visible td:nth-child(' + (columnWithCheckboxes + 1) + ') input').each(function(){
		    	    	                 this.checked = c;
		    	    	                $(this).trigger('change');
		    	    	            });
		    	    	        })
		    	    	        .bind('mouseup', function(){
		    	    	            return false;
		    	    	        });

		    	    		//if a checkbox is checked add the checked class to it
		    	    	        $t.find('tbody tr').each(function(){
		    	    	            $(this).find('td:eq(' + columnWithCheckboxes + ')').find('input[type=checkbox]').bind('change', function(){
		    	    	                	$t.trigger('updateCell', [$(this).closest('td')[0], resort]);
						    }
		    	    	            });
		    	    	        });

		    	    		//if a row is checked then check the checkbox
		    	    		$t.on('click', 'tr', function(){
						alert("row clicked");
		    	    			 $(this).children('td:first').find('input[type=checkbox]')
                    	    	    		.prop('checked', function(i, val) {
                    	    				return !val;
                    	    	    	         })
                    	    	    		// trigger a change so tablesorter will update the value
                    	    	    		.trigger('change');
		    	    		});

		    	    		//if any checkbox is unchecked, uncheck the checkAll box
		    	    	        $t.on('change', 'input', function(){
		    	    			if(!this.checked){  //if any checkbox is unchecked
		    	    	        		$t.find('thead th:eq(' + columnWithCheckboxes + ') input[type=checkbox]').prop('checked', false);

		    	    			}
		    	    	        });
		    	    	  };
		    	    	  // return 1 for true, 2 for false, so true sorts before false
		    	    	  c = ($c.find('input[type=checkbox]')[0].checked) ? 1 : 2;
		    	    	  $c.closest('tr')[ c === 1 ? 'addClass' : 'removeClass' ]('checked');
		    	    	  return c;
		    	    	},
		    	    	type: 'numeric'
		};

**And last my tablesorter settings:**
          
         $.tablesorter.addParser(myCustomParser);
 
         $(".dataTable")
		    	.tablesorter({
		    	    	theme:'blue',
		    	    	widthFixed: true,
		    	    	widgets: ['zebra', 'filter'],
    		    	    	headerTemplate : '{content}{icon}',
		
		    	    	headers: {
		    	    	    	0: {
		    	    	    	    	sorter: 'myCustomParser',
						filter: false
		    	    	    	},
		    	    	}
		    	})

A problematic senario is when i click on a row. In the original tablesorter (before the update) when i click a row then the class 'checked' is added to the row and the checkbox of the first column is checked (this is correct). But in the updated tablesorter for some reason that i can't understand, when i click a row the event is triggered twice. So it is like i am clicking and next un-clicking. So the rows can't be clicked! I would fully appreciate your help... Thank you in advance.
Bill from greece!

**Comment by Mottie** [comment]
There have been changes to the "updateAll" method. Please try the latest version and see if your problem persists.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by billonas** [comment]
Mottie hello.
Sorry for the veeeety late answear but i was working with some other parts of my project. Thank you anyway. I've upgraded to the last version of tablesorter (2.21.4) but there is no change. The problem now is that when i append new rows to the table the parser that is added to it doesn't seem to parsing the new added rows. For example the rows of the table are clickable. So when a row is clicked a class "checked" is added to it through the parser. When the new rows are apended to the table and i click on them class checked is not added as should be..
Thanks in advance for your help
Still Bill and still from Greece...

**Comment by Mottie** [comment]
Hmm, ok I think I see now... I'll see what I can do.

**Comment by Mottie** [comment]
Hmm, ok I may not need to change anything internally if a simple change to that code is made. Essentially, don't remove the `thead` and `tbody` from the table.

In this ([updated demo](http://jsfiddle.net/xg6ysrpk/3/)), I've included the [`parser-input-select.js`](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js) file to add the checkbox parser and extra code to highlight the row when checked. It does not include code for a checkbox in the thead.

```js
$(function () {

	// column containing all of the checkboxes (zero-based index)
	var checkboxColumn = 0,
	// resort the table after the checkbox status has changed
	resort = true,

	$t = $('table');

	$t.on('change.tisc mouseup.tisc', 'thead input[type=checkbox]', function () {
		c = this.checked;
		$t.find('tbody tr:visible td:nth-child(' + (checkboxColumn + 1) + ') input').each(function () {
			this.checked = c;
		});
		// update all checkboxes at once
		$t.trigger('update');
	});

	//if any checkbox is unchecked, uncheck the checkAll box
	$t.on('change.tisc', 'input[type=checkbox]', function () {
		if (!this.checked) { //if any checkbox is unchecked
			$t.find('thead th:eq(' + checkboxColumn + ') input[type=checkbox]').prop('checked', false);
		}
	});



	$('table').tablesorter({
		theme: 'blue',
		widgets: ['zebra', 'stickyHeaders', 'filter'],
		headers: {
			0: {
				sorter: 'checkbox'
			}
		}
	});

	function addHeaderRow(table) {
		table.append('<tr><th><input type="checkbox"></th>' +
			'<th>AlpaNumeric</th><th>Numeric</th><th>Animals</th>' +
			'<th>Sites</th></tr>');
	}

	function addBodyRows(table, row) {
		table.append('<tr role="row"><td><input type="checkbox"></td>' +
			'<td>abc 123</td><td>10</td><td>Koala</td><td>http://www.google.com</td>' +
			'</tr>');
		table.append('<tr role="row"><td><input type="checkbox"></td>' +
			'<td>abc 1</td><td>10</td><td>Koala</td><td>http://www.google.com</td>' +
			'</tr>');
	}

	$('#updateTable').click(function () {
		var table = $('table');
		// empty thead (preserves thead/tbody elements)
		table.find('thead, tbody').empty();
		// remove all tbodies
		table.find('tbody:gt(0)').remove();

		addHeaderRow(table.find('thead'));
		addBodyRows(table.find('tbody'));

		// updateAll because the thead content has changed
		table.trigger('updateAll', [resort]);

	});

});
```

**Comment by billonas** [comment]
Hello Motie. Everything works great now. The case is closed... Thanks a bunch
Keep up the good work !
:)
