### ISSUE TITLE
External Table

### ISSUE THREAD

**Issue by BlackNeo** [Mottie/tablesorter#775]
Hi,

I'm trying to use tablesorter, with a special html structure.

In fact I've one table containig my thead, and another contanaig my tbody. I had to to this because of a scroll option on my tbody, who applied a load more.

I'd like to sort this table. I can not really touch the structure of my table.

Any ideas?

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
