### ISSUE TITLE
column reorder after filter

### ISSUE THREAD

**Issue by Username83** [Mottie/tablesorter#781]
Hi,

after a filter in a column, if I try to move a column that is stored before the filtered column in a position after the filtered column, the filter is not updated correctly. Infact, the text used to filter remains in the same filter input, but the column with the filtered value is now shifted and the filter is also cancelled.
In this case the filter should be not cancelled and should be shifted with the column (best solution) or the input field should be cleaned (worst solution).

Thanks

**Comment by Mottie** [comment]
Can you try [this demo](http://jsfiddle.net/Mottie/abkNM/4870/), which uses the [jQuery UI dragtable widget](http://akottr.github.io/dragtable/) (requires sortable), to see if it solves the issues you are having.

**Comment by Username83** [comment]
Hi Mottie,

thanks for your answers!

with this [demo](http://jsfiddle.net/Mottie/abkNM/4870/) my problem is partially solved, because the filter is cleaned. However, the best solution would be to reorder the column and keep the filter.

**Comment by Mottie** [comment]
Oh, oops! Try [this demo](http://jsfiddle.net/abkNM/4950/)

It's not very pretty because refreshing the widgets causes all rows to become visible, then the filter needs to be applied again after dropping the column. I'll see what I can do about that when I get some time.

```js
$(function () {
	var lastSearch,
	$table = $('table:first')
	.dragtable({
		dragHandle: '.handle',
		excludeFooter: true,
		beforeStart: function(){
			lastSearch = $table.data('lastSearch');
		},
		persistState: function (table) {
			var columnOrder = $table.children('thead').children('.tablesorter-headerRow').children().map(function(){
				return $(this).attr('data-column');
			}).get(),
			// update moved filters
			filters = [];
			$.each( lastSearch, function(i){
				filters[i] = lastSearch[ columnOrder[i] ];
			});
			// remove div wrapper, or swapped header
			// contents will be replaced
			$table.find('thead .tablesorter-header-inner').contents().unwrap();
			$table.trigger('updateAll', [ false, function(){
				setTimeout(function(){
					$table[0].config.lastCombinedFilter = null;
					// $table.trigger('search', [ filters ]);
					$.tablesorter.setFilters( $table, filters, true );
				}, 200);
			}]);
		}
	})
	.tablesorter({
		theme: 'blue',
		selectorSort: '.sort',
		widthFixed: true,
		widgets: ['zebra', 'filter']
	});

});
```

**Comment by Username83** [comment]
Perfect!!! now it works as expected!

I will wait your next releases for an optimization :)

Thanks a lot!

**Comment by Mottie** [comment]
Hey @Username83!

Try this [updated demo](http://jsfiddle.net/abkNM/4998/) - it is using tablesorter core & widget files from the working branch and a highly modified version of dragtable in the demo javascript window.

The only issue I have is that a resized column width isn't retained after moving because there are no set widths (setting `widthFixed` prevents the resizable widget from working) and setting the `resizable_widths` option would not work properly because the settings aren't being changed... I guess I could add that into the dragtable plugin.

Otherwise, please test it out and tell me if you run into any other issues. Thanks!

```js
$(function () {
	var last = {},
		getOrder = function(){
			return $table.children('thead').children('.tablesorter-headerRow').children().map(function(){
				return $(this).attr('data-column');
			}).get();
		},
		$table = $('table:first')
			.dragtable({
				dragHandle: '.table-handle',
				excludeFooter: true,
				beforeStart: function(){
					last.search = $table.data('lastSearch');
					last.order = getOrder();
				},
				persistState: function (table) {
					var columnOrder = getOrder(),
						hasFilters = $.tablesorter.hasWidget($table, 'filter'),
						// update moved filters
						filters = [];
					if (hasFilters) {
						$.each( last.search || [], function(i){
							filters[i] = last.search[ columnOrder[i] ];
						});
					}
					// only trigger updateAll if column order changed
					if (last.order.join('') !== columnOrder.join('')) {
						// remove div wrapper, or swapped header
						// contents will be replaced
						$table.find('thead .tablesorter-header-inner').contents().unwrap();
						$table.trigger('updateAll', [ false, function(){
							if (hasFilters) {
								setTimeout(function(){
									$table[0].config.lastCombinedFilter = null;
									// $table.trigger('search', [ filters ]);
									$.tablesorter.setFilters( $table, filters, true );
								}, 200);
							}
						}]);
					}
				}
			})
			.tablesorter({
				theme: 'blue',
				selectorSort: '.sort',
				widgets: ['zebra', 'filter', 'resizable']
			});

});
```

**Comment by Username83** [comment]
Hi,

it seems there aren't other issues, excepted the resized columns. It works as expected.

Thanks,
Fabio

**Comment by Mottie** [comment]
Check out the new [dragtable](http://mottie.github.io/tablesorter/docs/example-dragtable.html) demo!

**Comment by Username83** [comment]
Very good!

Thanks!
