### ISSUE TITLE
Multiple Tables on one page - unique IDs

### ISSUE THREAD

**Issue by Sepppl** [Mottie/tablesorter#790]
Dear Mottie,

Maybe I oversaw an alredy exiting entry to the subject multiple tables.
How is it possible to get/have/generate/assigne unique IDs to multiple tables?
I have a page with 10 tables. I have difficulties to define the function with it's paramenters.

Is there a way to work with jQuery: .uniqueId() ?
Since my skills are limited, I have no idea how to alter the code in order to get it work.

Simple Example:

```html
<table id="uniqueID">....</table>
<table id="uniqueID">....</table>
<table id="uniqueID">....</table>
<table id="uniqueID">....</table>
```

Help is very welcomed ;-)

Did I told you that you have done a great job. Realy great!

Thanks!
Sepppl

**Comment by Mottie** [comment]
Hi @Sepppl 

Unique ID shouldn't be that difficult. If you can't think of anything fancy, just use something like `table` plus an index:

```html
<table id="table01">....</table>
<table id="table02">....</table>
<table id="table03">....</table>
<table id="table04">....</table>
```

Or, if you want to use javascript to generate IDs, do something like this:

```js
$('table').each(function(i){
    // only add an id if one doesn't exist
    if (!this.id) {
        this.id = 'planets_to_conquer_' + i;
    }
});
```

**Comment by Sepppl** [comment]
Hi @Mottie,

Thank you for answering that fast.
That's great, thanks for your suggestion.

Do you know, what I have to adjust in order to get the following code working?

`<script>
jQuery(document).ready(function($) {
     $("#divers").tablesorter({`
     widthFixed : false,
     showProcessing: true,
     headerTemplate : '{content} {icon}', // Add icon for various themes
     widgets: [ 'zebra', 'stickyHeaders' ],

    widgetOptions: {

      // extra class name added to the sticky header row
      stickyHeaders : '',
      // number or jquery selector targeting the position:fixed element
      stickyHeaders_offset : 0,
      // added to table ID, if it exists
      stickyHeaders_cloneId : '-sticky',
      // trigger "resize" event on headers
      stickyHeaders_addResizeEvent : true,
      // if false and a caption exist, it won't be included in the sticky header
      stickyHeaders_includeCaption : true,
      // The zIndex of the stickyHeaders, allows the user to adjust this to their needs
      stickyHeaders_zIndex : 2,
      // jQuery selector or object to attach sticky header to
      stickyHeaders_attachTo : null,
      // jQuery selector or object to monitor horizontal scroll position (defaults: xScroll > attachTo > window)
      stickyHeaders_xScroll : null,
      // jQuery selector or object to monitor vertical scroll position (defaults: yScroll > attachTo > window)
      stickyHeaders_yScroll : null,

      // scroll table top into view after filtering
      stickyHeaders_filteredToTop: true

      // *** REMOVED jQuery UI theme due to adding an accordion on this demo page ***
      // adding zebra striping, using content and default styles - the ui css removes the background from default
      // even and odd class names included for this demo to allow switching themes
      , zebra   : ["ui-widget-content even", "ui-state-default odd"]
      // use uitheme widget to apply defauly jquery ui (jui) class names
      // see the uitheme demo for more details on how to change the class names
      , uitheme : 'jui'
    }
  });

  $("#divers").tablesorter(options);

  /* make second table scroll within its wrapper */
  options.widgetOptions.stickyHeaders_attachTo = '.wrapper'; // or $('.wrapper')
  $("#divers").tablesorter(options);

});
</script>`

**Comment by Mottie** [comment]
That code does not have an `options` variable defined. So it is likely causing a javascript error.

Also, there is no reason to initialize tablesorter three times; **delete** of this part of the code and it should start working:

```js
  $("#divers").tablesorter(options);

  /* make second table scroll within its wrapper */
  options.widgetOptions.stickyHeaders_attachTo = '.wrapper'; // or $('.wrapper')
  $("#divers").tablesorter(options);
```

**Comment by Sepppl** [comment]
Thank you so much!
I try to be more accurate next time.

Now my question is:
Giving the tables the IDs is enough, that the function can relate to them?
At the moment I relate to them through the "#divers" ID.
In my case in order to get the relation I'm supposed to have to? :

`$("#table01").tablesorter({...`

`$("#table02").tablesorter({...`

`$("#table03").tablesorter({...`

`$("#table04").tablesorter({...`

**Comment by Mottie** [comment]
If all of the tables use the same settings, you can use something like this:

```js
$('#table01, #table02, #table03, ...').tablesorter({...
```

or, if all of the tables on the page are getting tablesorter applied, then just use:

```js
$('table').tablesorter({...
```

**Comment by Sepppl** [comment]
Thank you very much for your helpful advice!
Now I know what to do.

Do you have a donation-form/button where I can give you something?

Best,
Sepppl

**Comment by Mottie** [comment]
I'm glad you figured it all out... The only donation button I have is on [my blog](http://wowmotty.blogspot.com/); and thank you.

**Comment by BillRamos** [comment]
I can't seem to get tablesorter working on two tables on my page.  I'm using all default tablesorter values and specifying both tables by id...

jQuery('#boxscore-away, #boxscore-home').tablesorter();

Only the first table becomes sortable.  Any idea why?

**Comment by Mottie** [comment]
Hi @BillRamos!

I set up [this demo](http://jsfiddle.net/Mottie/abkNM/4972/) to show that it works.

Possible problems include:
* The second table does not have a `<thead>` or `<tbody>` or the HTML is broken.
* The `boxscore-home` id:
  * doesn't exist
  * exists more than once on the page, and the first instance is not the table.
  * is not added to a table element

**Comment by BillRamos** [comment]
Thanks for the speedy followup!

I'm using a javascript function to build out those tables after grabbing data from an external json source... Had an extra "<tbody>" in the boxscore-home builder function that was throwing everything off.  Don't you hate when it's something stupid/simple you kept overlooking?

Thanks again for the help!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
