### ISSUE TITLE
Sort Restart Not Working

### ISSUE THREAD

**Issue by BillRamos** [Mottie/tablesorter#791]
Hey there,

Having some issues with the sortRestart option...  I've set sortRestart to true and sortInitialOrder to desc, but my columns still flip back and forth between ascending and descending depending on the last state of that column regardless of another column head being used to sort (if that makes sense).  I'd like, if a column is unsorted, to always default to sorting from largest to smallest when clicked on again.

My code is:

> jQuery('#boxscore-away, #boxscore-home').tablesorter({
> 	sortRestart : true,
> 	sortInitialOrder : 'desc'
>});

What am I doing wrong?  Thanks in advance!

**Comment by Mottie** [comment]
It is working for me ([demo](http://jsfiddle.net/Mottie/abkNM/4975/)).

Basically when you click on an UNSORTED header, it will always restart from the `sortInitialOrder` option setting. You can see it works if you click once on all 4 headers one at-a-time, then click again on all 4 headers again one at-a-time; the initial sort from an unsorted column will always start with a descending sort (in that demo).

If you have questions about making tablesorter work, please use the IRC channel or Stackoverflow (see [the readme file](https://github.com/Mottie/tablesorter#questions)). I would appreciate it if you didn't open a new issue as I would like to keep issues for actual problems with the code or an enhancement request. Thank you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
