### ISSUE TITLE
Tablesorter on generated content

### ISSUE THREAD

**Issue by emaldonadov** [Mottie/tablesorter#793]
I'm trying to apply the plugin to a table that is generated dinamically (via ajax), after the entire page has loaded. But it doesn't work.

Any ideas?

TIA,

Ernesto

**Comment by Mottie** [comment]
Hi Ernesto!

Interestingly, I just answered a [question on Stackoverflow](http://stackoverflow.com/questions/27906452/tablesorter-in-dynamic-jquery-ui-doesnt-work) about making tablesorter work inside of a jQuery UI Dialog box. Maybe the example there will help get you started. If it doesn't, it would be easier for me to help if some basic code was provided.

**Comment by emaldonadov** [comment]
Thank you for your quick answer, Mottie. I couldn't solve the problem viewing the example you provided. The problem is that I don't have the table in the page, I generate it in another page. (I'm providing some code: principal1.png and principal2.png form the html file and the other file generates the table).
I'm using Laravel with twig. The table is generating and displaying data, the only issue is that it doesn't have style and can't be ordered.

Hope you can help me.

Regards,

Ernesto
![listadoccuentascontables](https://cloud.githubusercontent.com/assets/9448197/5728692/7d67b8c6-9b42-11e4-8965-0505ebb87ce1.png)
![principal2](https://cloud.githubusercontent.com/assets/9448197/5728693/7d6884f4-9b42-11e4-816e-4f37765bd3e4.png)
![principal1](https://cloud.githubusercontent.com/assets/9448197/5728691/7d6686e0-9b42-11e4-8701-26085130fa5d.png)

**Comment by Mottie** [comment]
I've never used Laravel, nor twig, but it is essentially the same concept.

In this case, tablesorter will need to be initialized within the ajax `success` callback:

```js
$(document.body).on('click', '#enlace', function(){
    $.ajax({
        type: 'GET',
        url: '....',
        success: function(data){
            $('#datos')
                .html(data)
                .find('table').tablesorter({
                    /* tablesorter options here */
                });
        }
    });
});
```

**Comment by emaldonadov** [comment]
Thank you very much, Mottie! It worked!

Nice job with this plugin.

Regards,

Ernesto
