### ISSUE TITLE
Old Tablesorter conversion to New Tablesorter

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#794]
I've been using (successfully) the original tablesorter plugin, and just discovered this fork. I did not realize it was a fork, at first, and just updated the .js file with the one on this site. Unfortunately, that broke my initial tablesorter table -- it never initiates at all.

Consequently, I learned this was a fork and so would necessarily be different in implementation. In short: do you have any recommended way I can move over to YOUR plugin with existing code for the original plugin? (I'm looking for a simple solution so I don't have to completely rebuild from scratch.)

**Comment by aetna-wsa** [comment]
I need to clarify... I thought it was not instantiating since the styles applied to the orginal tablesorter table were not coming into view. However, I was wrong -- it IS working, only the styles have been changed quite a bit. I apologize for throwing this out there without looking more carefully at what was going on. 

Do you happen to have any CSS mapping from the old styles to the new, so that this can be easily resolved?

Thanks!!

**Comment by TheSin-** [comment]
for the most part it should be a drop in.  Jus take sure you update ALL FILES, not just the main js.  Widgets, add ons, css everything.

**Comment by Mottie** [comment]
Hi @aetna-wsa!

If you run into any issues, please share some code and we would be happy to help.

**Comment by craighoskin** [comment]
Hi, Ive had similar.

Have a working instance of tablesorter using V 1.0.3 where everything is working perfectly with selected columns only, a custom image showing and an initial sort (with CSS formatting) on a single column.

The only trouble is with its handling of empty ells and hence wanted to use the Mottie fork. Got this working OK as well, however nothing I could find would allow me to get my images working again.

The CSS I had was:

/* tables sorting
----------------------------------------------------------*/
table.tablesorter {
    margin:10px 0pt 5px;
    font-size: 1.0EM;
    width: 100%;
    border: 1px solid #FFF;
}
table.tablesorter thead tr th, table.tablesorter tfoot tr th {
    font-size:1.0EM;
    padding: 4px;
}
table.tablesorter thead tr .header {
    background-image: url(/Images/bg.gif);
    background-repeat: no-repeat;
    background-position: center right;
    cursor: pointer;
}
table.tablesorter tbody td {
    color: #3D3D3D;
    padding: 4px;
    vertical-align: top;
}
table.tablesorter tbody tr.odd td {
    background-color:#F0F0F6;
}
table.tablesorter thead tr .headerSortUp {
    background-image: url(/Images/asc.gif);
}
table.tablesorter thead tr .headerSortDown {
    background-image: url(/Images/desc.gif);
}
table.tablesorter thead tr .headerSortDown, table.tablesorter thead tr .headerSortUp {
    background-color: #8dbdd8;
}

and the script portion was pretty basic
 $(document).ready(function () {
        $("#raceresults").tablesorter({
            sortList: [
                    [0, 0]
                ],
            // pass the headers argument 
            headers: {
                // assign the secound column 
                1: {sorter: false},
                2: {sorter: false},
                3: {sorter: false},
                7: {sorter: false},
                8: {sorter: false},
                9: {sorter: false}
            }
        });
    });

and my HTML table started with:

<table id="raceresults" class="tablesorter">
@if (raceresults.Any())
{
    <thead>
        <tr style="background-color:lightgray">
            <th>Place</th>
            <th>ID</th>
            <th>Name</th>
            <th nowrap>Finish Time</th>
            <th>Handicap    </th>
            <th nowrap>Corrected Time   </th>
            <th>Avg Speed   </th>
            <th>Points</th>
            <th nowrap>Time Diff</th>
            <th nowrap>Cumm Diff</th>
        </tr>
    </thead>
    <tbody>

So really just a basic tablesorter implementation.
I got it working nicely with the emptyTo directive, but nothing I could do would get the table formatting (change colour on table heading, or the custom image).

Cheers

Craig

**Comment by Mottie** [comment]
If you want to use this css:

```css
table.tablesorter thead tr .header {
    background-image: url(/Images/bg.gif);
    background-repeat: no-repeat;
    background-position: center right;
    cursor: pointer;
}

/* ... */

table.tablesorter thead tr .headerSortUp {
    background-image: url(/Images/asc.gif);
}
table.tablesorter thead tr .headerSortDown {
    background-image: url(/Images/desc.gif);
}
table.tablesorter thead tr .headerSortDown, table.tablesorter thead tr .headerSortUp {
    background-color: #8dbdd8;
}
```

you'd need to change some of the default settings ([cssHeader](http://mottie.github.io/tablesorter/docs/#cssheader), [cssAsc](http://mottie.github.io/tablesorter/docs/#cssasc) &amp; [cssDesc](http://mottie.github.io/tablesorter/docs/#cssdesc)):

```js
$(function () {
    $('table').tablesorter({
        cssAsc    : 'headerSortUp',
        cssDesc   : 'headerSortDown',
        cssHeader : 'header',
    });
});
```

**Comment by craighoskin** [comment]
Ahhh perfect, thanks for that!
Cheers

Craig

**Comment by craighoskin** [comment]
Sorry one more thing.
WIth the new .js in place sorting works OK, and the sorting images display, however every column shows the bg.gif even if sorting is disabled for that column?

**Comment by Mottie** [comment]
Ahh yes, that is another issue with the css... Now, when a column has it's sort disabled, a class name of "sorter-false" is added. If you look at the "theme.blue.css" file you'll find this line:

```css
.tablesorter-blue thead .sorter-false {
	background-image: none;
	cursor: default;
	padding: 4px;
}
```

Which removes the background image from the header and changes the cursor back to an arrow.

In the next iteration of tablesorter, which is named [Abelt](https://github.com/tablesort/Abelt) to avoid confusing this fork with the original tablesorter, the icons will only target the `<i>` element within the header.

**Comment by craighoskin** [comment]
Great.
Actually ended up using the default theme css and then modifying to get the look back again :)

**Comment by aetna-wsa** [comment]
Thank you all -- CSS was the issue. I replaced mine with the new styles and all is well.

When is the Abelt anticipated release?

**Comment by Mottie** [comment]
I don't have a definite timeline... I've been busy with other things lately and haven't had time to work on Abelt.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
