### ISSUE TITLE
Displaying the count in the header

### ISSUE THREAD

**Issue by getvivekv** [Mottie/tablesorter#795]
Hi
I searched the documentation but couldn't find it. I am using Tablesorter with the Filter widget. I want to know how to display the total number of occurrence of a column item in the column header.

For example,
http://easycaptures.com/fs/uploaded/714/3897489290.png

There are 3 rows with the same name "Boston". When we click on the filter drop down, it should show "Boston (3)" where 3 is the total number of occurrence of "Boston" in the table. The column however may not contain "(3)". How do I achieve this ?

**Comment by Mottie** [comment]
Hi @getvivekv!

Hmm, issue #575 has pretty much covered this issue... I did not merge the code there into the widget because, if I remember correctly, there were still some issues with it not counting "filter-onlyAvail" rows properly.

Let me know if that works for you.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
