### ISSUE TITLE
by default second column gets focused (first column i'm keeping disable)

### ISSUE THREAD

**Issue by gurditta** [Mottie/tablesorter#797]
i tried so many tweaks and hacks but couldn't make it. I've so many filterFormatter and by default i'm disabling the first column and i don't know why the second column is being focused on loading the page. Kindly refer the attachment for more detail 

![image](https://cloud.githubusercontent.com/assets/3133431/5785171/1fa41852-9d99-11e4-96b3-ef4ce6235142.png)

**Comment by Mottie** [comment]
Hi @gurditta!

I don't know why the second input is getting focused either. Share some code and maybe I can help you figure it out.

**Comment by gurditta** [comment]
<script language="javascript" type="text/javascript">
        $(function(){
            $("table").tablesorter({
                widthFixed: true,
                widgets: ['uitheme', 'stickyHeaders', 'filter','zebra','pager'],
                theme : "bootstrap",
                headers: {
                    0: { sorter: false }
                },
                headerTemplate : '{content} {icon}',
                widgetOptions: {
                    zebra : ["even", "odd"],
                    filter_formatter : {
                        1 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        2 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        3 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        4 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        5 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        6 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        7 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        8 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        9 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        },
                        10 : function($cell, indx){
                            return $.tablesorter.filterFormatter.select2( $cell, indx, {
                                match : false,
                                placeholder: 'search...'
                            });
                        }                        
                    }
                }
            });
            $('table').trigger('pageSize', 20);
            $('.tablesorter-filter-row td:first').find('input').attr('disabled', 'disabled');
            //$('.tablesorter-filter-row td:gt(1)').remove();
            $('#checkAllBox').click(function () {
                $(':checkbox.checkItem:visible').prop('checked', this.checked);
            });
        });
        </script>

**Comment by Mottie** [comment]
Instead of disabling the filter using jQuery, add a `filter-false` class to the header ([ref](http://mottie.github.io/tablesorter/docs/example-widget-filter.html#classes)):

```html
<th class="filter-false"><input type="checkbox"/></th>
```

And instead of triggering a `pageSize` method, use the [`pager_size` option](http://mottie.github.io/tablesorter/docs/index.html#pager-size)

```js
widgetOptions: {
    pager_size: 20,
    ....
}
```

As for the second input getting focus, that might be somewhere else in the code. Search through the code for a `.focus()` to hopefully find the culprit.

**Comment by gurditta** [comment]
Thanks @Mottie  for the tip :)
But this focus issue can be considered as a nice to have a feature as user will anyhow start searching :P

**Comment by Mottie** [comment]
Oh, I misunderstood... *you want* the second select2 input to get focus.

In that case, add an `initialized` callback option and the following code ([demo](http://jsfiddle.net/Mottie/abkNM/5045/)):

```js
initialized: function(table){
    table.config.$filters.eq(1).find('.select2').select2('open');;
}
```

**Comment by gurditta** [comment]
NO you understood right the issue is there that the first column get focused automatically.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
