### ISSUE TITLE
refreshColumnSelector

### ISSUE THREAD

**Issue by Kepro** [Mottie/tablesorter#798]
i try to update collumn selector but not working i try many ways to set new widgetOptions but nothging working... 
last i tried table[0].config.widgetOptions.columnSelector_columns = { 	2: true,3: false }; but nothing changes....

**Comment by Mottie** [comment]
Hi @Kepro!

Hmm, it's been a while since I looked at the widget code... I don't remember why I saved the states of each column in an internal set of checkboxes when no external checkboxes are added - I probably just wanted to patch it and get it to work. So anyway, you'll need to update the internal checkboxes using the following code ([demo](http://jsfiddle.net/Mottie/abkNM/5057/)):

HTML

```html
<select class="col-picker" multiple>
    <option value="2">Sex</option>
    <option value="3">English</option>
    <option value="4">Japanese</option>
    <option value="5">Calculus</option>
    <option value="6">Geometry</option>
</select>
```

Script

```js
$(function () {
    var $table = $('.custom')
        $picker = $('.col-picker');
    
    $picker.change(function(){
        var c = $table[0].config,
            wo = c.widgetOptions,
            // total # of columns
            cols = c.columns,
            // active columns
            val = $(this).val(),
            // internal columnSelector container
            $c = c.selector.$container;
        // turn off auto breakpoints
        c.selector.auto = false;
        // first 2 columns not included (priority critcal & disabled)
        // using TH attribute and class name settings
        for ( i = 2; i < cols; i++ ) {
            $c
                // set internal checkbox values
                .find('input[data-column=' + i + ']')
                .prop('checked', $.inArray( '' + i, val ) >= 0 );
        }
        $table.trigger('refreshColumnSelector');
    });

	$table.tablesorter({
		theme: 'blue',
		widgets: ['zebra', 'columnSelector', 'stickyHeaders'],
		widgetOptions : {
			columnSelector_container : null,
			columnSelector_saveColumns: true,
			columnSelector_mediaquery: true,
			columnSelector_mediaqueryState: true,
		},
        initialized: function(){
            // make all columns visible on init
            $picker.val([2,3,4,5,6]).change();
        }
	});
});
```

**Comment by Kepro** [comment]
that will be cool :) thanks

**Comment by Mottie** [comment]
This update is now available in the working branch.

I did make an error in the example above (corrected now) in that when triggering a method, the array needs to be inside of another array:

```js
// pass the refresh method an array of column indexes to show
$table.trigger( 'refreshColumnSelector', [ [2,3,4,5] ] );
```

If a column index in the array is targeting a column that has "critical" priority or set as "disable", that column will never get toggled off using this method.

**Comment by Kepro** [comment]
and @Mottie is there some way to disable/enable auto with config? i using both of select box + search bar 
and i want still to use auto, but if i use auto and i can't deselect "auto"

**Comment by Mottie** [comment]
Ok, I updated the same method... if you pass anything other then an array, "auto" mode will be enabled:

```js
$('table').trigger('refreshColumnSelector', true);
```
