### ISSUE TITLE
dummy row in table sorter pager

### ISSUE THREAD

**Issue by karthickkumarganesh** [Mottie/tablesorter#800]
is there a way to exclude row in table sorter with pager widget .
for example the row with class "inforow" 
these row are visible in table ,but not included in pager and total rows, how to do this ,please help

**Comment by Mottie** [comment]
Hi @karthickkumarganesh!

All you need to do is include a tbody with the class name "tablesorter-infoOnly" - set by the [`cssInfoBlock` option](http://mottie.github.io/tablesorter/docs/#cssinfoblock) ([demo](http://jsfiddle.net/Mottie/4mVfu/4178/)) - either before or after the pager block; the pager knows to ignore these tbodies.

```html
<tbody class="tablesorter-infoOnly">
    <tr>
        <td colspan="7">Extra Information Row</td>
    </tr>
    <!-- add more than one row, if desired -->
</tbody>
```

**Comment by karthickkumarganesh** [comment]
thanks for your reply , this work only with one row ,please look at my case here [link] (jsfiddle.net/4mVfu/4181), i have multiple info block say 1 to 15 in my table

**Comment by Mottie** [comment]
Well the pager will only add content to the first non-info-only tbody, so in that case, you can use child rows ([demo](http://jsfiddle.net/Mottie/4mVfu/4208/)):

```html
<tr class="tablesorter-childRow">
    <td colspan="7">Info row attach to above row</td>
</tr>
```

Please note that a child row is associated with the row above it:
* If a parent row ends up being the last row on a page, the child row will also be shown.
* Zebra striping of the child row will match the parent unless you use custom css to change the style.
* Hovering the parent row will also highlight the child row - it's defined in the css.
* The "tablesorter-childRow" class will be ignored if it is added to the first row in the tbody.
* To include the child rows in the pager row count, set the pager [`countChildRows` option](http://mottie.github.io/tablesorter/docs/#pager-countchildrows) to `true`; I know you don't want to count them, but I included this information here for completeness.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
