### ISSUE TITLE
tablesorter with pager - force update when table is empty

### ISSUE THREAD

**Issue by panickos** [Mottie/tablesorter#801]
I am using `tablesorter` with the `pager` plugin. All of the paging is done server-side so I am using the `ajaxUrl`, `ajaxObject` and `customUrl` options of the pager to handle all the ajax calls needed whenever the user is flipping pages.

Inside the `customUrl` option I have a function that retrieves a timerange that the user defines in an external field, and add it into the url, in order to filter only entries within that range.

When the user changes that timerange I remove all of the rows from the table using `$("tr", tableElement).remove();` and then `$(tableElement).trigger("update");` to trigger the ajax call by the pager plugin.

This works when the table has entries in it: The entries get removed, then the update trigger issues a new ajax request, and gets the rows within the selected timerange inside the table with proper pagination.

**Problem:** When the currently selected range is empty (i.e. no entries were found), and the user selects a new range, the update trigger doesn't see any change in the data/entries (within the table's structure), thus the ajax request doesn't get issued.

*Is there a way to force the table to update itself and run the ajax query procedure?*

Question cross-listed here: http://stackoverflow.com/questions/28054625/tablesorter-with-pager-force-update-when-table-is-empty

**Comment by Mottie** [comment]
Hi @panickos!

The pager does look for changes to the url, so you could try adding a random number to the end of the `customAjaxUrl` when the time range is blank.

```js
customAjaxUrl: function(table, url) {
    var range = $('.range').val();
    return url += range ? '&rand=' + ( '' + Math.random() ).slice(2) : '&range=' + range;
}
```

**Comment by panickos** [comment]
The URL is always different, since I augment the to and from timestamps:

```javascript
customAjaxUrl: function(table, url) {
                var windowSizeInMinutes = timeWindowSelector.getWindowSizeSelected();

                var to = new Date().getTime();
                var from = to - windowSizeInMinutes * 60 * 1000;
                url += "&from="+from+"&to="+to;

                // manipulate the url string as you desire
                // url += '&cPage=' + window.location.pathname;
                // trigger my custom event
                $(table).trigger('changingUrl', url);
                // send the server the current page
                return url;
            },
```

**Comment by Mottie** [comment]
Are you using the most up-to-date pager version? I added the url check just recently in [v2.18.0](https://github.com/Mottie/tablesorter/wiki/Changes#version-2180-10262014).

**Comment by panickos** [comment]
I have:
```javascript
/*!
* TableSorter (FORK) 2.18.4 min - Client-side table sorting with ease!
* Copyright (c) 2007 Christian Bach; fork maintained by Rob Garrison
*/
```

**Comment by panickos** [comment]
Actually, what I've noticed while trying to debug this is that if the table is empty, and then try to call update, to refill it from ajax, the `customAjaxUrl` function is not being ran.

**Comment by Mottie** [comment]
Actually instead of emptying the table and triggering an update, try this code:

```js
$('table')[0].config.pager.last.ajaxUrl = '';
$('table').trigger('pageSet');
```

I think I'll add a method to force a pager update instead of making people do stuff like the above....

**Comment by Mottie** [comment]
I added a new method named "pagerUpdate" which will force a pager update. It is available within the working branch of this repository. Use it as follows:

```js
$('table').trigger('pagerUpdate');
```

**Comment by panickos** [comment]
Thank you for the quick response and for solving this issue. I tried your first solution with the current released version and it works perfectly. I haven't tried the new "pagerUpdate" function since I would have to switch libraries to a non-released version and I don't want to do that at the moment.
