### ISSUE TITLE
Using trigger("updateCell") w/Filters+stickyHeader combo causes unwanted scrolling

### ISSUE THREAD

**Issue by JamoCA** [Mottie/tablesorter#802]
If you increase the amount of rows in the "Updating a table cell" demo, add stickyHeader & filter widgets and then scroll down and click on any cell.  The cell is updated, but the window is immediately scrolled to the top of the page.
http://mottie.github.io/tablesorter/docs/example-update-cell.html

It won't hijack the current scroll position if either stickyHeaders or filter are disabled.  If both are enabled, the unwanted scrolling occurs.

    $("table").tablesorter({
        theme: 'blue',
        stickyHeaders : 'tablesorter-stickyHeader',
        sortList: [[3,1],[0,0]],
        widgets: [ 'zebra', 'stickyHeaders', 'filter' ]
    });

**Comment by Mottie** [comment]
Hi @JamoCA!

It might be the [`stickyHeaders_filteredToTop` option](http://mottie.github.io/tablesorter/docs/#widget-sticky-headers-filtered-to-top), which is `true` by default, causing the behavior that you are seeing.

**Comment by JamoCA** [comment]
ok.  Thanks. That worked with the demo.

I'm having an issue regarding stolen focus.  My table cells have INPUT fields with on('change') that perform ajax updates followed by a trigger('updateCell').  If I modify a field value & press TAB to go to the next field, the update trigger causes the field focus to be lost.

This is the function I am using to update qty field w/ subtotals in an updated row:

    function updateTablesorter(theTable, theRow){
        theTable.trigger('updateCell', [theRow.find('td:nth-of-type(5)'), false]); /* Update qty cached data in Tablesorter */
        theTable.trigger('updateCell', [theRow.find('td:nth-of-type(6)'), false]); /* Update subtotal cached data in Tablesorter */
    }

I want to update the sortable value associated with the cell *using textExtraction) so that clicking the table header will sort based on the updated values, but triggering updateCell causes the focus to be lost on the next focused/tabbed field.  Is there an attribute to prevent this?  Thanks.

**Comment by Mottie** [comment]
I've encountered a similar problem with the editable widget. The way I solved it was to add a class to the input when focused, then in the updateCell callback you can remove the class and trigger a focus. Something like this:

```js
function updateTablesorter(theTable, theRow){
	// get the last focused element
	var $focused = $(document.activeElement);
	// make sure it's an input inside the table before adding a class name
	if ($focused[0].tagName === "INPUT" && $focused.closest('table').is(theTable)) {
		$focused.addClass('lastFocusedInput');
	}
	/* Update qty cached data in Tablesorter */
	theTable.trigger('updateCell', [theRow.find('td:nth-of-type(5)'), false]);
	theTable.trigger('updateCell', [theRow.find('td:nth-of-type(6)'), false, function(){
		// find element, remove class name, then focus on it
		theTable.find('.lastFocusedCell').removeClass('lastFocusedCell').focus();
	}]);
}
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by JamoCA** [comment]
I ended up using the following code based on your recommendations:

    $('.lastFocusedInput').removeClass('lastFocusedInput');
    $focused = $(document.activeElement);
    if ($focused[0].tagName === "INPUT") {
        $focused.addClass('lastFocusedInput');
    }
    cartTable.trigger('updateAll', [false, function(){
        $('.lastFocusedInput').focus().removeClass('lastFocusedInput');
    }]);

**Comment by Mottie** [comment]
Great! Thanks for the update... I still wouldn't recommend using "updateAll", but if it works, I won't sweat it.

**Comment by JamoCA** [comment]
Is there a method to update a single column of cell values instead of "all"?

I'm using -/+ buttons to update a qty & sub-total in 2 separate columns. (The function also updates hidden metadata in another column for flagging discounts due to quantity.)  It would be optimal to only update the affected columns, but I'm updating all since it may not be possible.

**Comment by Mottie** [comment]
You can use "update" to refresh the cache on the tbody. But if you mean you need to include the header cell, then you'll need to use ["updateAll"](http://mottie.github.io/tablesorter/docs/#updateall) to get everything...

Or use a combination of ["update"](http://mottie.github.io/tablesorter/docs/#update) and ["updateHeaders"](http://mottie.github.io/tablesorter/docs/#updateheaders) separately; this alternative doesn't "expect" a newly inserted or removed column though.
