### ISSUE TITLE
Use cssStickyHeader

### ISSUE THREAD

**Issue by nna37** [Mottie/tablesorter#803]
I use tablesorter with cssStickyHeader widget. When a page is scrolled the page header is sticked to the top of a screen. But when a page is sctolled fastly by the mouse scroller the header begin to flash

**Comment by Mottie** [comment]
Hi @nna37!

I'm not sure what to tell you.

It's not pure css being used to position the header during scrolling as some javascript is needed to calculate the page scroll position and where to position the header, including nested table headers.

It is really smooth if you scroll using the keyboard (arrows or pageUp/Down) and if you scroll the page by dragging the scroll bar. The only time it isn't smooth is when using the mousewheel.

If you know, or can help figure out how to solve this issue, I'm open to ideas.

**Comment by Mottie** [comment]
I don't think there is a solution, so I'm going to go ahead and close this issue.
