### ISSUE TITLE
can i take the existing filter outside of table as it is?? need extra one for server side filtering

### ISSUE THREAD

**Issue by gurditta** [Mottie/tablesorter#805]
![image](https://cloud.githubusercontent.com/assets/3133431/5886031/f821c7f6-a348-11e4-83e9-21d6ed059839.png)

**Comment by TheSin-** [comment]
you mean like http://codepen.io/TheSin/pen/xkgKj ?

**Comment by gurditta** [comment]
@TheSin- thanks much for replying
That's really cool but i don't need that fancy, my requirement is to just copy the drop down as it is without copying each element.

**Comment by TheSin-** [comment]
right but the idea is the same, all the code you need to do it is in that example, just use how I clone it and re bind it and you are set.  I made it fancy to show how far you can go with it but it doesn't need to be that far.

**Comment by Mottie** [comment]
Hi @gurditta!

As @TheSin- said, it is possible. But if you are using the select2 plugin it might be a bit more complicated than just duplicating the HTML and binding a search to it.

If you are using select2, you would need to use the filter formatter code for the select2 plugin. You'll also need to set up some code to initialize select2 outside of the table, then copy any changes between the two initializations; this part may be tricky because you don't want to cause an infinite loop of updating between the two.

If you're asking for help, please share the code you have thus far, I would be happy to help troubleshoot the problem.

**Comment by gurditta** [comment]
Hii @Mottie , @TheSin- 
can i pre-populate a select2 drop down with some values and should be able to send the selected values to the server

**Comment by Mottie** [comment]
If you already have the select2 set up using the filterFormatter, then use the initialization and filter end event to update the external select2 data.

```js
$(function(){

	$('.external-select2').select2({
		/* whatever options */
	});

	// zero-based index of select2 column
	var select2Column = 2,
		// only get available (filter-onlyAvail) rows
		onlyAvail = false;

	$('table')
		.tablesorter({
			/* whatever options */
		})
		.on('tablesorter-initialized filterEnd', function(){
			var	data = [],
			arry = $.tablesorter.filter.getOptionSource( this, select2Column, onlyAvail) || [];
			// build select2 data option
			$.each(arry, function(i,v){
				data.push({id: v, text: v});
			});
			// update select2 with new data
			$('.external-select2').select2('data', data, true);
		});

});
```

**Comment by gurditta** [comment]
@Mottie thanks for replying
I've data like following in an array 
[{"Name":"A", "Id":"123"},{"Name":"B","Id":"456"}}]

Can i pre-populate this data to select2 drop down without table formatter, i just want the drop down and then i would like to send the selected value to server

**Comment by gurditta** [comment]
@Mottie 
Hi,
I need to update the tableformatter select2 plugin after the ajax request has been completed, below is the code i'm using for it.

            function(result, event){
                var row = "";
                $.each(result, function(index, item){
                    //whatever with result
                });
                $("#updatedUc").html(row);
                $("table").trigger("update"); 
                $('table').trigger('pageSize', 10);
            }

**Comment by Mottie** [comment]
> Can i pre-populate this data to select2 drop down without table formatter

I'm not sure what this means. The code I shared should update the external select2 to match the internal one on table initialization. Why would you not want to use the table formatter (which I assume means you don't want to use the `$.tablesorter.filter.getOptionSource()` function.

Which of these are you asking for help with?

1. "can i pre-populate a select2 drop down with some values and should be able to send the selected values to the server"
2. "my requirement is to just copy the drop down as it is without copying each element."
3. "I need to update the tableformatter select2 plugin after the ajax request has been completed"

(1) Has been partially answered, but you'll need to add code in your select2 options to post the values back to your server.
(2) I believe I have  answered above in the code I shared. Did you try to integrate that code?
(3) What ajax request? Are you using the pager ajax, or is it a custom ajax call? Are you adding content to the table? What is `$('#updateUc`)` pointing to? Is the internal select2 not updating as expected?

I am not getting enough information to work with here.

And I don't want to sound rude, but I am just here really just here to listen to enhancement requests and bug reports. I try to assist people with finding problems in their code, mostly because I enjoy helping; but really I don't have the free time to provide a coding service (free or otherwise) - what I mean is don't expect me to do all the work for you.

**Comment by gurditta** [comment]
Hey @Mottie 
That's not rude at all.I really appreciate your efforts and the time you devote for all such bugs and issues. 
I got that select2 thing done (that was my silly mistake sorry bout that), but facing a new issue in tablesorter. If i don't have any records in column then it always gives me a default blank value. See the screenshots

![image](https://cloud.githubusercontent.com/assets/3133431/5949503/eac3b51e-a713-11e4-8cdd-c11cd384c957.png)

![image](https://cloud.githubusercontent.com/assets/3133431/5949509/f980c376-a713-11e4-8637-8b3689178d69.png)

**Comment by Mottie** [comment]
That appears to be an issue with select2 ([see this demo](http://jsfiddle.net/eGXPe/382/)):

If the data includes an empty string, then you'll get blank entries. So I would add a check to see if the (trimmed) string is not empty before adding it as an option:

```js
$.each(arry, function(i,v){
  if ( $.trim(v) !== '' ) {
    data.push({id: v, text: v});
  }
});
```

**Comment by gurditta** [comment]
@Mottie 
Thanks much for your help. But i came across a new error, though this error is not impacting i think but it's still a error

TypeError: parsed.push is not a function
jQueryTableSortFilter/js/jquery.tablesorter.widgets.js
Line 1406

**Comment by gurditta** [comment]
@Mottie 

there is one more thing i just figured out 

![image](https://cloud.githubusercontent.com/assets/3133431/5962581/7fffbfa6-a7aa-11e4-8d0b-b0eeb7ae78ec.png)
-------------------------------------------------------------------------------------------
this is my code for this 

            $('input[name="accountNameFromDB"]').select2({
                data: remotedata,
                multiple: true,
                maximumSelectionSize: 3,
                placeholder: 'search for Accounts',
                tags: true,
                separator: "|",
                placeholder: 'search...',
                match: false
            });

**Comment by Mottie** [comment]
> TypeError: parsed.push is not a function

How are you calling the `$.tablesorter.filter.getOptionSource` function?

> there is one more thing i just figured out

That looks like a select2 issue. It has probably been resolved in a new version of select2, but sadly I haven't had time to update the filter formatter for select2 to work with the newest version. Anyway, you might be able to fix that by taking the results of the `getOptionSource` function and string replacing `&amp;` with `&`.

**Comment by gurditta** [comment]
@Mottie No i'm not calling getOptionSource. Below is the whole structure of code that i've.

OnLoad-------
            $("table").tablesorter({
                widthFixed: true,
                widgets: ['uitheme', 'stickyHeaders', 'filter','zebra','pager'],
                theme : "bootstrap",
                headers: {
                    0: { sorter: false }
                },
                headerTemplate : '{content} {icon}',
                widgetOptions: {
                    zebra : ["even", "odd"],
                    pager_size: 10,
                    filter_reset: 'button.reset',
                    filter_formatter: {
                        '.select2' : function ($cell, indx) {
                            return $.tablesorter.filterFormatter.select2($cell, indx, {
                                tags: true,
                                separator: "|",
                                placeholder: 'search...',
                                match: false // adds "filter-match" to header
                            });
                        }
                    }
                }
            });

Table Body----
tbody has the id #updatedUc

after AJAX call ------

function(result, event){
var row = "";
$.each(result, function(index, item){
	row+="<tr><td><input class='checkItem' type='checkbox' Id='"+item.Id+"'/></td>"+
	"<td>"+((!item.Customer__r) ? '' : item.Customer__r.AccountNumber)
	+"</td><td>"+item.User__r.Name+"</td>"
	+"<td>"+(item.Customer__r.Name || '')+"</td><td>"+(item.Partner_Position__c || '')+"</td>"
	+"<td>"+((!item.User__r.Partner_Supervisor__r) ? '' :      item.User__r.Partner_Supervisor__r.Name)
	+"</td><td>"+(item.Manual_source__c || '')+"</td>"
	+"<td>"+(item.Supervisor_source__c || '')+"</td><td>"+(item.Agrimine_Source__c || '')+"</td>"
	+"<td>"+(item.Agrimine_Sales_Management__c || '')+"</td><td>"+(item.Segmentation_source__c || '')+"</td></tr>";
	//console.log(item);
});
$("#updatedUc").html(row);
$('table').trigger('update'); -- updates my pager but not select2

Is there any way we to refresh all select2 that i have when the tbody will be updated :

![image](https://cloud.githubusercontent.com/assets/3133431/5966497/961790a0-a7ca-11e4-807e-9b7bc06a9a60.png)

**Comment by Mottie** [comment]
You could just update the external select2 elements from inside that function:

```js
function(result, event){
	var v,
		row = "",
		select2User = [],
		select2Customer = [];
	$.each(result, function(index, item){
		row+="<tr><td><input class='checkItem' type='checkbox' Id='"+item.Id+"'/></td>"+
			"<td>"+((!item.Customer__r) ? '' : item.Customer__r.AccountNumber)
			+"</td><td>"+item.User__r.Name+"</td>"
			+"<td>"+(item.Customer__r.Name || '')+"</td><td>"+(item.Partner_Position__c || '')+"</td>"
			+"<td>"+((!item.User__r.Partner_Supervisor__r) ? '' : item.User__r.Partner_Supervisor__r.Name)
			+"</td><td>"+(item.Manual_source__c || '')+"</td>"
			+"<td>"+(item.Supervisor_source__c || '')+"</td><td>"+(item.Agrimine_Source__c || '')+"</td>"
			+"<td>"+(item.Agrimine_Sales_Management__c || '')+"</td><td>"+(item.Segmentation_source__c || '')+"</td></tr>";

		// save user name
		v = item.User__r.Name;
		if (v) { select2User.push( { id: v, text: v } ); }
		// save customer name
		v = item.Customer__r.Name || '';
		if (v) { select2Customer.push( { id: v, text: v } ); }
	});
	$('#updatedUc').html(row);
	$('#select2User').select2({ data: select2User });
	$('#select2Customer').select2({ data: select2Customer });
	$('table').trigger('update');
}
```

**Comment by gurditta** [comment]
@Mottie 

as i'm creating select2 filter on all the headers in one go :

-------filter formatter setup-----
                    filter_formatter: {
                        '.select2' : function ($cell, indx) {
                            return $.tablesorter.filterFormatter.select2($cell, indx, {
                                tags: true,
                                separator: "|",
                                placeholder: 'search...',
                                match: false // adds "filter-match" to header
                            });
                        }
                    }

----------table header ------------

                        <tr>
                            <th class="filter-false"><input type="checkbox" id="checkAllBox"/></th>
                            <th class="select2" onchange="accountnumchange()">Account Number</th>
                            <th class="select2">User</th>
                            <th class="select2">Customer</th> 
                            <th class="select2">Position</th>
                            <th class="select2">Manager</th>
                            <th class="select2">Manual</th>
                            <th class="select2">Supervisor</th>
                            <th class="select2">AgriMine</th>
                            <th class="select2">AgriMine Sales</th>
                            <th class="select2">Segmentation</th>
                        </tr>

----------- after implementing the above code, it created a new select2

![image](https://cloud.githubusercontent.com/assets/3133431/5967430/7adc046c-a7d2-11e4-9e6f-21b139346cdb.png)

**Comment by Mottie** [comment]
I'm not sure what to tell you. Can you share a demo if this problem.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by gurditta** [comment]
@Mottie 
Yeah It's fixed. Sorry for not updating
