### ISSUE TITLE
How to , Do not filter on <tbody>

### ISSUE THREAD

**Issue by getvivekv** [Mottie/tablesorter#807]
Hi
I have a table which has two `<tbody>`

I am using the first `<tbody>` to populate the table with the data and second `<tbody>` with the class "avoid-sort" so that it doesn't get sorted.

I want to know is there any trick to avoid that tbody from filtering, something like if I put "avoid-filter" class then that `<tbody>` won't get filtered if filter on the first tbody

**Comment by Mottie** [comment]
Hi @getvivekv!

If you change the [`cssInfoBlock` option](http://mottie.github.io/tablesorter/docs/#cssinfoblock) (default is `"tablesorter-infoOnly"`) to `"avoid-sort"`, then no sort will be applied and the filter widget will ignore the contents of that tbody.

```js
$('table').tablesorter({
    cssInfoBlock: 'avoid-sort'
});
```

\* Please note that this will only work with the code from this fork of tablesorter - the original tablesorter does not have this option.

**Comment by getvivekv** [comment]
Thanks! It worked. I have also tested this with the original tablesorter and it works there too.
