### ISSUE TITLE
Output widget ignoreColumns not working 

### ISSUE THREAD

**Issue by Kezz101** [Mottie/tablesorter#809]
Hello again!

I'm using the output widget to download a csv file of my table and I'm using the `ignoreColumns` setting to remove the last row of the table. However, my table is of variable length so I have to use a bit of jQuery trickery to get the zero-based number of the last column but this doesn't seem to be working.

Here is the code I'm using to set up the table:

```javascript
$(".tablesorter").tablesorter({
	theme: "bootstrap",
	widthFixed: false,
	headerTemplate: "{content} {icon}",
	sortList: [[0,0]],
	widgets: ["filter", "zebra", "print", "columnSelector", "output"],
	widgetOptions: {
		zebra: ["even", "odd"],
		filter_reset: ".reset",
		columnSelector_mediaquery: false,
		columnSelector_saveColumns: false,
		output_saveFileName: "responses.csv",
		output_delivery: "download",
		output_ignoreColumns: [columnsInTable(".tablesorter") - 1],
		print_callback: function(config, $table, printStyle) {
			config.print_columns = "selected";

			$table.find(".tablesorter-infoOnly").remove();
			$table.find(".print-remove, .tablesorter-pager").remove();
			$table.find(".tablesorter-childRow").remove();
			$.tablesorter.printTable.printOutput(config, $table.html(), printStyle);
		}
	}
});
```

Here is the `columnsInTable` function:
```javascript
function columnsInTable(table) {
    var colCount = 0;
    $(table).find('tr:nth-child(1) td').each(function() {
        if ($(this).attr('colspan')) {
            colCount += +$(this).attr('colspan');
        } else {
            colCount++;
        }
    });

    return colCount;
}
```

The whole HTML of the page can be viewed here: http://pastebin.com/zGf85LBQ

**Comment by Mottie** [comment]
Hi @Kezz101!

You can use the [`table.config.columns` variable](http://mottie.github.io/tablesorter/docs/#variable-columns) to get the total number of columns in the table.

If you have questions, I would appreciate it if you would join us in the `#tablesorter` channel on Freenode.net instead of opening an issue. Thanks!

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
