### ISSUE TITLE
tfoot totals row disappears when using scrolling

### ISSUE THREAD

**Issue by rogerskk** [Mottie/tablesorter#825]
I have my table totals in a tfoot tag outside of the tbody.  However, when I use the tablesorter scroller widget, it disappears.  I would like it to stay underneath the scrolling like the headers stay on top.  I need something like a stickyFooters widget.  Do you have any suggestions?

**Comment by Mottie** [comment]
Hi @rogerskk!

You're right, the scroller widget is totally ignore the tfoot. I'll look into adding this soon.

**Comment by Mottie** [comment]
The fix is currently available in the master branch. I haven't updated the gh-pages, so the documents are not showing these changes yet.

**Comment by rogerskk** [comment]
Thanks!  My totals tfoot row now shows, however it isn't showing my totals.  My code seems solid because I added an alert to make sure it was putting the data in the boxes and added a text box outside of the table and it would show the correct totals in that box, but not the ones inside the tfoot.  Any idea why that might be the case?  Using the following to put the data in: $("#ptotal").val(value.toFixed(2)); 
ptotal is the id of the text box.  Thank you!

**Comment by Mottie** [comment]
The `tfoot` you see is not the original, it is a copy. So instead of targeted it with an ID (IDs must be unique), use a class name instead.

```js
$(".ptotal").val(value.toFixed(2));
```

**Comment by rogerskk** [comment]
Sweet! That did the trick! You rock!
