### ISSUE TITLE
"Homemade" theme

### ISSUE THREAD

**Issue by johnnymex** [Mottie/tablesorter#828]
First of all, my praise to the Tablesorter plugin. It works like a charm !!

My wish is to add a different theme, let’s call  it  “theme.lightgray.css”,  - so 
What I did was to copy from theme.default.css  and rename it afterwards.
Hereafter set the tablesorter field “theme” to “lightgray”.
Then I could adjust the containing CSS until its view suited me.
Unfortunately this method did not work. 
What will you suggest I should do ?

Thanks in advance.

**Comment by Mottie** [comment]
Hi @johnnymex!

Within the theme file, every definition starts out with `.tablesorter-default` so as to target only the chosen class name. Make sure to rename all of these css selectors as well.

Might I also suggest an alternative. Although it may seem daunting, test out one of the LESS themes. 

* [Basic Tablesorter theme](http://codepen.io/Mottie/pen/eqBbn)
* [Bootstrap Tablesorter theme](http://codepen.io/Mottie/pen/Ltzpi/)
* [Metro Tablesorter theme](http://codepen.io/Mottie/details/gCslk/)

Rename the theme in two places:

* LESS: `@theme : tablesorter-custom;`
* HTML: `<table class="tablesorter-custom">`

Then tweak the colors until you get a design you like then click on the little eye in the upper right corner to show the compiled css.

![2015-02-24 07_32_41-tablesorter less theme](https://cloud.githubusercontent.com/assets/136959/6350250/b584886c-bbf7-11e4-9f57-664c6348936d.png)

Once you copy that css to your editor, you'll need to strip out a few css definitions that don't apply - the first 60 or so lines of the css; the comments and the selectors that don't start with `.tablesoter-{theme}`.

**Comment by johnnymex** [comment]
Thanks,
I think I will dig into LESS themes

**Comment by johnnymex** [comment]
This will do it for now !
