### ISSUE TITLE
Tablesorter not setting the default selection value with multiple search inputs

### ISSUE THREAD

**Issue by JohnBloom** [Mottie/tablesorter#831]
Here is an example of a setup we have. We have a search box and a filter dropdown box. When trying to set the default for the drop down the fact that the input box exists is breaking the code. 

Here is an example http://jsfiddle.net/johnbloom/f8kz4ec7/

**Comment by Mottie** [comment]
Hi @JohnBloom!

Hmm, yeah, it looks like the any-match input is trying to find "less-than-50" in the table instead of using the `filter_formatter` function... that will need to be fixed.

**Comment by TheSin-** [comment]
here is a not so pretty work around till it's fixed

http://jsfiddle.net/f8kz4ec7/3/

**Comment by Mottie** [comment]
Here is a "slightly uglier" work around ([demo](http://jsfiddle.net/f8kz4ec7/4/)):

```js
initialized: function(){
    setTimeout(function(){
        $('input.search').val('lang && fe');
        $('select.search').val('less-than-50').change();
    }, 100);
}
```

Ugly because the table shows all rows, then applies the filter... use one of these workarounds until I can get the filter initial value setting to behave properly with the any-match.

**Comment by Mottie** [comment]
Ok, all fixed!

The update is available in the master branch. I also added code to allow setting a default filter value in external filters, so if you look in this [updated demo](http://jsfiddle.net/f8kz4ec7/5/), the `data-value` in the `data-column="all"` input is set.

**Comment by JohnBloom** [comment]
Wow great job guys! Best turn around time I have seen on an open source project. Thanks!
