### ISSUE TITLE
Tbody sort

### ISSUE THREAD

**Issue by serheyShmyg** [Mottie/tablesorter#833]
Hi.
Is there any solution for tbody sorting?
Not tr, but get information about sorting from tr and sort tbody?
Thank's.

**Comment by Mottie** [comment]
Hi @serheyShmyg!

Are you referring to pull #195 ?

Or, do you mean there is an issue with the built-in [sorting of rows within tbodies](http://mottie.github.io/tablesorter/docs/example-multiple-tbodies.html)?

**Comment by Mottie** [comment]
Closing this duplicate issue... Please refer to the update in [issue #195](https://github.com/Mottie/tablesorter/pull/195#issuecomment-109818770).
