### ISSUE TITLE
Want to use JUI theme on tablesorter

### ISSUE THREAD

**Issue by johnnymex** [Mottie/tablesorter#835]
I want to use JUI theme on tablesorter.
I have seen the demo on http://mottie.github.io/tablesorter/docs/example-widget-ui-theme.html.
When a new theme is selected in the dropdownlist, the theme changes as expected.
My problem is I can't trace what happens with the selected theme. - Where is it stored or what  is done with it ?
will you please provide an example where to f.ex setting the theme to let's say "redmond" ?

Best regards,
Johnnymex

**Comment by Mottie** [comment]
Hi @johnnymex!

To make tablesorter work with a jQuery UI theme, you need the minimum following setup:

```js
$("table").tablesorter({
  theme : 'jui',
  headerTemplate : '{content} {icon}', // needed to add icon for jui theme
  widgets : ['uitheme'],
});
```

The `uitheme` widget adds the class names used by jQuery UI to the selected elements:

```js
// Extend the themes to change any of the default class names
// this example modifies the jQuery UI theme class names
$.extend($.tablesorter.themes.jui, {
	/* change default jQuery uitheme icons - find the full list of icons
	here: http://jqueryui.com/themeroller/
	(hover over them for their name)
	*/
	// table classes
	table: 'ui-widget ui-widget-content ui-corner-all',
	caption: 'ui-widget-content',
	// *** header class names ***
	// header classes
	header: 'ui-widget-header ui-corner-all ui-state-default',
	sortNone: '',
	sortAsc: '',
	sortDesc: '',
	// applied when column is sorted
	active: 'ui-state-active',
	// hover class
	hover: 'ui-state-hover',
	// *** icon class names ***
	// icon class added to the <i> in the header
	icons: 'ui-icon',
	// class name added to icon when column is not sorted
	iconSortNone: 'ui-icon-carat-2-n-s',
	// class name added to icon when column has ascending sort
	iconSortAsc: 'ui-icon-carat-1-n',
	// class name added to icon when column has descending sort
	iconSortDesc: 'ui-icon-carat-1-s',
	filterRow: '',
	footerRow: '',
	footerCells: '',
	// even row zebra striping
	even: 'ui-widget-content',
	// odd row zebra striping
	odd: 'ui-state-default'
});
```

These class names *do not change* between jQuery UI themes. So whether you choose "ui-lightness" or "redmond" the class names stay the same. The only thing that changes is the active "jquery-ui.min.css" file.

If you want to switch between jQuery UI themes, try out the [`jui_theme_switch` plugin](https://github.com/pontikis/jui_theme_switch/); but you might want to use the updated [theme_switched.json](https://github.com/Mottie/tablesorter/blob/master/docs/assets/theme_switcher.json) file from my documentation since the urls have been updated.

**Comment by johnnymex** [comment]
Hi Rob,
Thanks for your help ! 
By adding the code as you suggested, it was as simple as can be.
by switching between jquery.ui css references, f.ex:
//code.jquery.com/ui/1.11.2/themes/redmond/jquery-ui.css  
and 
//code.jquery.com/ui/1.11.2/themes/sunny/jquery-ui.css
I could either see it "redmond" theme or "sunny" theme.

So far so good !  But one thing that is not possible when using "jui" theme, is to
have several tablesorters with different themes  (layout) !

Am I right ?

Best regards,
@Johnnymex

**Comment by Mottie** [comment]
Well anything is possible, it just depends on how much work you want to put into it. The easiest method would be to add the tables into separate iframes each of which has a different ui theme loaded. The second method would require a lot of css editing, which is less desirable.

**Comment by johnnymex** [comment]
What I meant was,  just  two tablesorters on the same webpage, so no iframes or anything  :-)

**Comment by Mottie** [comment]
Lots of css editing then :tired_face:
