### ISSUE TITLE
Scroller widget, width issue

### ISSUE THREAD

**Issue by cristianocoelho** [Mottie/tablesorter#836]
Hello,

On tables with many columns, header width and body width do not align. See screen capture below.
Is there a way to handle this properly?

![scroller_issue](https://cloud.githubusercontent.com/assets/8058669/6548128/9decbb54-c5cd-11e4-984d-f8a0d5669d93.PNG)

**Comment by Mottie** [comment]
Hi @cristianocoelho!

Hmm, ok I'll see what I can do.

**Comment by Mottie** [comment]
Ok, it should work a lot better now... it's not 100% pixel perfect, but it's pretty darn close.
