### ISSUE TITLE
Filter missing in last column

### ISSUE THREAD

**Issue by clod986** [Mottie/tablesorter#840]
Hi @Mottie ,
The filter widget will build one column left if the last `<th>` cas a colspan of 2. It works fine for all the previous headers with the same colspan, but for some reason not for the last one.

Here's a screenshot.
http://awesomescreenshot.com/0f14lhy3db

**Comment by Mottie** [comment]
Hi @clod986!

It works for me - http://jsfiddle.net/Mottie/856bzzeL/68/

Can you update that demo to show the issue? It will help me troubleshoot the problem.

**Comment by clod986** [comment]
I replicated the error removing the <code>tfoot</code> from the fiddle.

Here's the link - http://jsfiddle.net/clod986/856bzzeL/71/

Thanks @Mottie!

**Comment by clod986** [comment]
I was now wondering if <code>tfoot</code> is mandatory to comply with W3C standards. From what I've read, it is wrong to include it and leave it empty...

**Comment by Mottie** [comment]
Ahh, ok I see the problem now, it's not calculating the number of columns correctly by not taking into account the colspan in the last cell...

I forgot I left the `tfoot` in the original demo; and no the `tfoot` is not mandatory, but maybe in this special case it would be better to add a hidden `tfoot` so the column number is correctly calculated.

Either way, I'll look into modifying the code to look for this special case.

**Comment by Mottie** [comment]
Ok, all fixed. Get the updated `jquery.tablesorter.js` file from the master branch.

**Comment by clod986** [comment]
Awesome job @Mottie!
Thanks a lot for this package
