### ISSUE TITLE
Resizable widget: resizer div has height 0 if <th> is empty

### ISSUE THREAD

**Issue by gigib82** [Mottie/tablesorter#844]
This can be easily be fixed by inserting a `&nbsp;` inside the `<th>` instead of leaving it empty. I think it's worth mentioning this in the documentation :)

**Comment by Mottie** [comment]
Hi @gigib82!

Thanks! I'm thinking about rewriting the resizable widget to not add the resize element inside the header cell anyway ;)

**Comment by Mottie** [comment]
Added an "Important" note on the [resizable demo page](http://mottie.github.io/tablesorter/docs/example-widget-resizable.html). Thanks again!
