### ISSUE TITLE
editable_selectAll and (sorry) IE8

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#848]
Yes, I'm stuck with IE8.  Firefox does the selectAll upon starting to edit a cell in the table just fine.  But IE8 doesn't do it.  (Right?)  Maybe this is just a limitation I gotta deal with.

Are there any workarounds I can do like maybe on editable_focused function do a .select on the element?

2nd thing is when I hover outside the table, the hilight is killed and the cursor hops to the leftmost spot in firefox, rightmost spot in IE8.

Below is my javascript if it helps...

Thank you for this TOTALLY AWESOME code, though !!

```js
   $("table thead th").data ("sorter", false);
   $(".tablesorter").each (function () {
     var ce = [], t = Number ($(this).attr ('id').substr (2));
      for (var i = 0;  i < ta [t][1];  i++)  ce [i] = i;
      $(this).tablesorter ({
         theme  : 'blue',
         widgets: ['editable'],/*, 'resizable'],*/
         widgetOptions: {
            editable_columns      : ce,
            editable_enterToAccept: false,
            editable_autoAccept   : true,
            editable_autoResort   : false,
            editable_validate     : null,
            editable_focused      : function (txt, colInd, el) {
               el.addClass    ('focused');
            },
            editable_blur         : function (txt, colInd, el) {
               el.removeClass ('focused');
            },
            editable_selectAll    : function (txt, colInd, el) {return true;},
            editable_wrapContent  : '<div>',
            editable_noEdit       : 'no-edit',
            editable_editComplete : 'editComplete'
         }
      })
      .children ('tbody').on ('editComplete', 'td', function (ev, cfg) {
        var $th = $(this),
            tn = Number ($th.closest ('table').attr ('id').substr (2)),
            tr =         $th.closest ('tr'),
            co = this.cellIndex,
            ro = tr.index ();
           //.............etc etc etc (field validation, formatting, etc
```

**Comment by Mottie** [comment]
Hi @Stephen-Hazel!

Maybe the modification (from [this Stackoverflow answer](http://stackoverflow.com/a/13641884/145346)) will work better...

Add the following code outside of the document ready function, and after the editable widget is loaded:

```js
$.tablesorter.editable.selectAll = function( cell ) {
	setTimeout( function() {
		// select all text in contenteditable
		// see http://stackoverflow.com/a/13641884/145346
		var range, selection;
		if ( document.body.createTextRange ) {
			range = document.body.createTextRange();
			range.moveToElementText( cell );
			range.select();
		} else if ( window.getSelection ) {
			selection = window.getSelection();
			range = document.createRange();
			range.selectNodeContents( cell );
			selection.removeAllRanges();
			selection.addRange( range );
		}
	}, 100 );
};
```

If it works in IE8, then I'll update the editable widget.

**Comment by Stephen-Hazel** [comment]
BLESS YOU !!

That did the trick alright.

There's still the annoyance of if you scoot your mouse out of the way for editing and it happens to be beyond the table, in firefox it'll scoot the cursor all the way to the left.
After this change, the cursor completely disappears in IE8.

But this'll get my boss off my back :)  So thanks !!

**Comment by Mottie** [comment]
Well, I made it so when you move the mouse out of the tbody, it blurs the contenteditabe... the reason is if you have a contenteditable un-saved, and you move the mouse to click the header to sort. A problem occurs where the table gets sorted, then the "updateCell" method gets triggered to update the cell contents, but the row indexing is all messed up because it was just sorted.

You can try to disable this, and see if this is turns out to be a non-issue for you.... in the `initialized` callback, add this:

```js
initialized: function(table){
  table.config.$tbodies.off('mouseleave.tseditable');
}

**Comment by Stephen-Hazel** [comment]
BLESs YOU AGAIN !!

I don't need the tablesorter to actually sort.  So you just solved everything in tarnation for me.

(Do I close this thing out or somethin?  Hopefully you can help a github newb out)

THANKS AGAIN.

**Comment by Mottie** [comment]
LOL no worries... close this issue if you are happy :wink:

**Comment by Stephen-Hazel** [comment]
do nothin?  sure, that i can do !
