### ISSUE TITLE
Resize column issue (Avoid pressing Shift key)

### ISSUE THREAD

**Issue by ShovanDhara** [Mottie/tablesorter#850]
I have used tablesorter for resizing column and freeze header, the whole things working fine & it is awesome. I have only one issue in resize column through header. When I'm resizing one column, the very next column is getting automatically resized. To prevent this, you have suggested to press Shift key and then resize in issue. #215. My client does not like this and want to avoid pressing Shift key every time for resizing. So I was wondering if there is any other way to resize column perfectly without pressing any key. Please reply fast..................It is urgent

Your earlier reply will appreciated

**Comment by Mottie** [comment]
Hi @ShovanDhara!

The widget is written to require the shift key... if this behavior isn't to your liking, you can modify line 115, which looks like this:

```js
$next = event.shiftKey ? $target.parent().find('th').not('.resizable-false').filter(':last') : $target.nextAll(':not(.resizable-false)').eq(0);
```

and change it to this:

```js
$next = $target.parent().find('th').not('.resizable-false').filter(':last');
```

I actually plan on rewriting the resizable widget in the near future, and I'll add an option to lock that mode in place.

**Comment by Mottie** [comment]
Hey!

I totally forgot to mention this change in the readme... but I added a new [`resizable_targetLast`](http://mottie.github.io/tablesorter/docs/example-widget-resizable.html#resizable-target-last) widget option in https://github.com/Mottie/tablesorter/commit/673d7cbbb517c7c7e849aa7288776ea915e8cbd9.

Thanks for the suggestion!

**Comment by ShovanDhara** [comment]
I have done the code changes as you said. But there is one problem I'm facing in IE9 - Whenever I'm resizing any column, the very last column is getting affected. Is there any way to prevent this. I do have horizontal scroll in the table container div. I also want to increase and decrease the horizontal scroll based on table width after resizing column.

Your earlier reply will appreciated

**Comment by Mottie** [comment]
Are you using the updated resizable widget? - I just modified it with the new option and a new method to add resizable handles less than 2 weeks ago.

**Comment by ShovanDhara** [comment]
You have done some changes in table classes which ruining my design.

**Comment by Mottie** [comment]
Which classes?

The biggest change to the resizable widget was adding a div container outside the table; also while dragging the resizable handle, the body is given a no select class/attributes to prevent text highlighting.

No changes to the table class were made.
