### ISSUE TITLE
filter_saveFilters for sessionStorage?

### ISSUE THREAD

**Issue by ZeddV** [Mottie/tablesorter#851]
Hello!

It is possible with the function filter_saveFilters to save the data in the sessionStorage instead of  the localStorage?

thanks!

**Comment by Mottie** [comment]
Hi @ZeddV!

Sure, it would be possible with some minor code changes... 

I wonder though, do you want only only the saveFilters to be saved to session storage or all saved variables to be toggled between local and session storage. If it is specific to  some variables, I'll need to figure out how to change where data is saved based on that preference - more widget options, fun fun!

**Comment by TheSin-** [comment]
I plan to add this option as a TS wide setting, I thought this was a great suggestion and I'd like to use it as well.

I guess it could have a TS wide default and per widget override?

**Comment by Mottie** [comment]
![keep-calm-and-do-what-you-want-27](https://cloud.githubusercontent.com/assets/136959/6791318/0e232a98-d17c-11e4-89f3-2dce9c559170.png)

**Comment by ZeddV** [comment]
For my purpose, it would be great that all saved variables  to be toggled between local and session storage. 

It would be pretty pretty good! Thx! :)

**Comment by Mottie** [comment]
Ok, I added a new widget option `storage_useSessionStorage`, and a few other options that might be useful.

Check out the [documentation](http://mottie.github.io/tablesorter/docs/#widget-storage-fixed-url) for `widgetOptions` that start with `storage_`.
