### ISSUE TITLE
Use background-color instead of background for hovered rows

### ISSUE THREAD

**Issue by sgjohnston** [Mottie/tablesorter#853]
In the css for hovered rows (eg theme.blue.css lines 107 and 113, or I guess .evenHovered and .oddHovered in theme.less), the background color of the row is set using "background". An unfortunate side-effect of this is other background properties (eg background-image, background-repeat, etc) are set to none. This makes it very difficult to use a background image in a table cell via css, as the selector used in the theme is quite specific, and so normally wins (using !important does work to set the background image, but I would rather not if possible).

I can't see any reason not to use just background-color in the theme file, rather than background. Any change of making that change?

thanks,
Stuart

**Comment by Mottie** [comment]
Hi @sgjohnston!

Oh, yeah that is an oversight on my part. I'll have it fixed in the master branch ASAP.

I plan on pushing out a new version some time today.
