### ISSUE TITLE
Missing Events in PageEvents list

### ISSUE THREAD

**Issue by omnilord** [Mottie/tablesorter#854]
There is a list of events here: [TableSorter Pager Events](http://mottie.github.io/tablesorter/docs/index.html#events-pager)

That are not included in the pager events list here: [Line 117 - jquery.tablesorter.pager.js](https://github.com/Mottie/tablesorter/blob/v2.21.2/addons/pager/jquery.tablesorter.pager.js#L117)

And this causes problems when destroying tablesorter or the pager plugin because these events are not included in the cleanup activities/unbind calls internal to tablesorter.

Is this a defect or an omission by design?  If by design, I'd like to understand why.

**Comment by Mottie** [comment]
Hi @omnilord!

Everything in that list is removed in the destroy method (see [line 797](https://github.com/Mottie/tablesorter/blob/v2.21.2/addons/pager/jquery.tablesorter.pager.js#L797)); and again upon initialization.

```js
$(table).unbind( pagerEvents.split(' ').join('.pager ').replace(/\s+/g, ' ') );
```

I just reviewed all the binds in the pager plugin and noticed that "refreshComplete" wasn't included in the list - I'll fix that ASAP.

I just created [this demo](http://jsfiddle.net/Mottie/1a5yu8yq/2/) and:
* When I destroy the pager, no events starting with "pager" are in the events list (look at the console).
* When I destroy everything, only "refreshComplete" remains - which I'll have fixed soon.

So, what specifically is the problem that is occurring?

**Comment by omnilord** [comment]
pagerComplete is also missing.

**Comment by Mottie** [comment]
Huh?

The `pagerInitialized` (with a "d" on the end) and `pagerComplete` are events that are triggered on the table. No where in the pager plugin/widget is there a bind to those events.

The only widgets that do bind to "pagerComplete" are:
* editable
* formatter
* stickyHeaders

And those widgets namespace the event bindings to the widget name, so that shouldn't be the problem.

I wonder if after triggering a destroy in the pager, any event bindings within the code on that page also need to be removed.

I might be able to better help troubleshoot the problem if some of the code from that page were shared.

**Comment by omnilord** [comment]
I updated [Your example](http://jsfiddle.net/1a5yu8yq/4/) with a third button (Lines 24 to 33) and a callback for ```pagerInitalized pagerComplete``` (on line 40).  Click the destroy 'All' button, then click the 'Restart' button to re-initialize tablesorter and pager without the callback.  Then page through the data, you should get an alert every page change even though the tablesorter with the pagerComplete event was "destroyed" previously.

Also, I may have made a typo with the pagerInitialized because I don't see an alert when the example initializes.

I also create a [Two Modes Toggle Example](http://jsfiddle.net/1a5yu8yq/5/) where one state has ```pagerInitialized pagerComplete``` events a little more in line with what I have.  Just click back and forth between the two mode buttons a couple of times and you should see the compounding effect of calls to the callback function (pagerInitialized seems to be working here even though I didn't change that code from the previous iteration).

**Comment by Mottie** [comment]
Maybe I have the wrong idea, but I don't think the plugin is "responsible" for bindings that are made outside of the plugin. 

There is no way for it to determine when a binding should or shouldn't be removed, or reason out why and prevent an event from being bound multiple times. What I mean is, if a developer binds to an event, then they should remove that bind when they think it should be removed.

In the case of those demos, what  is likely missing is an unbind to the "pagerInitialized" and "pagerComplete" events:

```js
$('table').trigger('destroy').off('pagerInitialized pagerComplete');
```

Updated:
* [demo 1](http://jsfiddle.net/Mottie/1a5yu8yq/6/)
* [demo 2](http://jsfiddle.net/Mottie/1a5yu8yq/7/)

**Comment by omnilord** [comment]
Any drawbacks to doing the .off() call in a callback attached to the destroy event like [This](http://jsfiddle.net/1a5yu8yq/8/)?

**Comment by Mottie** [comment]
None that I can see.

**Comment by omnilord** [comment]
I'll pass this along to my team.  Thanks for the patience, I know these kinds of "not-a-bug" investigations can be bothersome, but they can be educational for everyone else.

**Comment by Mottie** [comment]
Not a problem :)
