### ISSUE TITLE
Table headers resist alignment in IE9

### ISSUE THREAD

**Issue by unkani** [Mottie/tablesorter#856]
Sorry if this issue has already been brought up, but I couldn't find it when I searched for it.

In IE9, the table headers resist alignment via CSS, while it works fine in Chrome and Firefox. I took a screenshot of one of the default tables in IE9, which has this problem as well.

http://i.imgur.com/wkPnVHM.png
Original URL: http://mottie.github.io/tablesorter/docs/example-multiple-tbodies.html
In the css, the table headers have left-align, but they show up as center aligned regardless of what is done with the stylesheet. 

Thanks!

**Comment by Mottie** [comment]
Hi @unkani!

I think all that is missing is a text-align definition on the header ([demo](http://jsfiddle.net/856bzzeL/97/)):

```css
th {
    text-align: left;
}
```

**Comment by unkani** [comment]
Oh gosh.
I've been using 
#tableID thead {
}

I don't know how I didn't try this... Thank you for your speedy reply!
