### ISSUE TITLE
filtering and pager in a dialog

### ISSUE THREAD

**Issue by lernerc** [Mottie/tablesorter#857]
I have the table I am filtering in a dialog and the problem I am coming across is when I try to filter a table it applies the filtered class to all the right rows, but the filtered rows that were initially visible are still displayed even though they should not be shown. The pager will also add more rows to the page that are filtered properly. And as you flip through the pages the ones shown that shouldn't be are still shown on every page. 

I am using the 2.21.3 file for jquery.tablesorter.js and have tried it with the 2.21.3 files jquery.tablesorter.js and jquery.tablesorter.widgets.js and also subbed those with the 2.21.4 file jquery.tablesorter.combined.js. I get the same problem in both.

![example](https://cloud.githubusercontent.com/assets/4111301/6923812/51e1afb4-d791-11e4-8c7f-c7027e0ed5c7.png)

So originally the pager shows 2 rows and then after adding the filter it shows 3 rows. One row not containing the filter information. And then as you flip through the pages there are always 3 rows shown with 1 of the rows being the one that doesn't match the filtering criteria.

**Comment by Mottie** [comment]
Hi @lernerc!

In a recent change to the filter widget, it no longer adds a `display` style to the rows (neither `none` nor `table-row`), so to ensure the filtered rows are hidden, make sure to include this css definition:

```css
.filtered { display: none; }
```

It [has been included](https://github.com/Mottie/tablesorter/blob/master/css/theme.blue.css#L219-L221) with all of the provided themes for a while now. It appears you're using a custom theme, so this definition may be missing.

**Comment by lernerc** [comment]
Thanks, that fixes the problem. I will try looking at the themes more carefully from now on.

**Comment by Mottie** [comment]
No worries! I'm glad that was the issue and not something bigger :wink:
