### ISSUE TITLE
When Filter Cleared using the "X" icon in the filter input 

### ISSUE THREAD

**Issue by ramjeekabra** [Mottie/tablesorter#858]
In the image below if you click on the "X" icon to clear the filter criteria, the table is not rendered without that criteria. User has to click into the filter and hit backspace to refresh the table.

![tablesorter_filter](https://cloud.githubusercontent.com/assets/11760543/6950197/cbbf4ea2-d87e-11e4-9eef-5ed767af6792.png)

**Comment by Mottie** [comment]
Hi @ramjeekabra!

I'm not exactly sure what you mean by "the table is not rendered without that criteria".

It "x" inside the filter is added by the browser. Tablesorter has nothing to do with that "x". The filter widget does listen for a "search" event which "should" be triggered by clicking it, but it is not consistent across all browsers.

Please see issue #356 for details on how to completely remove it, or add functionality to all browsers using jQuery.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
