### ISSUE TITLE
No display table header/filter/sorter when used columns selector

### ISSUE THREAD

**Issue by sportok** [Mottie/tablesorter#859]
Hi,

after update v2.20.1 to v2.21.4, i have an issue.
Indeed, my table have not header/filter/sorter...

For me, it is only when use plugin column selector.

Example : 
![issue](https://cloud.githubusercontent.com/assets/7646373/6964476/c7086242-d949-11e4-83fe-c08199451e2d.PNG)

Google chrome console : (on jquery.tablesorter.widgets.min.js)
![issue2](https://cloud.githubusercontent.com/assets/7646373/6964477/c70be476-d949-11e4-9f87-873f70da820b.PNG)

Thanks,
Sportok

**Comment by Mottie** [comment]
Hi @sportok!

Can you tell me the line number of that error from the un-minified version?

**Comment by sportok** [comment]
Hi @Mottie :-).

Yes, error is line 2089

![issue3](https://cloud.githubusercontent.com/assets/7646373/6965545/ae326c00-d952-11e4-9c03-87ca678eb062.PNG)

Thank you

**Comment by Mottie** [comment]
Ok, thanks... that's definitely a bug with the resizable widget since I changed around how it works, it doesn't ignore hidden columns.

I'll try to get this fixed ASAP.

**Comment by Mottie** [comment]
Actually, I can't duplicate the error. Can you please share your initialization code for the column selector and resizable widgets.

**Comment by sportok** [comment]
Indeed when i disable resizable widget, tablesoter work.
Our code is not very clean, perhaps we should do it again..

    function initTableSorter() {
    $(".tablesorter").each(function(index) {
        var widgets = ['uitheme', 'filter', 'zebra', 'resizable'];
        var isSticky = false;
        if ($(this).hasClass('tablefixheader')) {
            isSticky = true;
            widgets.push("stickyHeaders");
        }
        if ($(this).hasClass('tablecolumnfilter')) {
            $(this).addClass('bootstrap-popup');
            widgets.push("columnSelector");
            $(this).before('<button id="popover_' + $(this).attr('id') + '" type="button" class="btn btn-default"><i class="fa fa-filter"></i> Filter</button>');
            $('#popover_' + $(this).attr('id')).popover({
                placement: 'right',
                html: true,
                content: '<div id="popover-target"></div>'
            }).on('shown.bs.popover', function() {
                $.tablesorter.columnSelector.attachTo($('.bootstrap-popup'), '#popover-target');
            });
        }

        var saveFilters = init($(this).data('saveFilter'), true);
        if (saveFilters == "false") {
            saveFilters = false;
        }

        var filter_liveSearch = init($(this).data('livesearch'), true);
        if (filter_liveSearch == "false") {
            filter_liveSearch = false;
        }

        var options = {
            index: index,
            theme: "bootstrap",
            widthFixed: true,
            headerTemplate: '{content} {icon}',
            widgets: widgets,
            widgetOptions: {
                filter_ignoreCase: true,
                filter_saveFilters: saveFilters,
                filter_liveSearch: filter_liveSearch,
                filter_reset: '.resetFilters-' + index,
                resizable: true,
                stickyHeaders_offset: $('header.navbar-fixed-top').height(),
                zebra: ["ui-widget-content even", "ui-state-default odd"]
            }
        };
        
        $(this).bind('filterInit', function() {
            setResetFilterButton($(this));
        });

        // handle sticky sorter
        if (isSticky && !this.alreadyInit) {
            $(this).bind('stickyHeadersInit', function() {
                setResetFilterButton($('#' + $(this).attr('id') + '-sticky'), index);
            });
        }

        // init
        $(this).tablesorter(options);

        // static
        this.alreadyInit = true;
    });

**Comment by Mottie** [comment]
Please try the fix I just committed to the master branch... I don't know if it'll fix the error you're seeing, but it work with the column selector widget now.

I'll try to look at this again later when I get some more time.

**Comment by sportok** [comment]
Thank, 

on master branch or only when i change jquery.tablesorter.widget file with your fix, i have following issues : 
(so, it is the same of before, problem with $header)

![issue5](https://cloud.githubusercontent.com/assets/7646373/6967153/e1cfcd5e-d95d-11e4-885a-b6e682f13a59.PNG)
![issue4](https://cloud.githubusercontent.com/assets/7646373/6967152/e1cdf9fc-d95d-11e4-8d40-0bc65e8327a0.PNG)

**Comment by Mottie** [comment]
Hmm, ok I still can't duplicate it... 

It might have something to do with the HTML. Is the HTML valid? I mean like the number of columns and colspans in the header all match up?

Anyway, try adding this line in the widget code. If it works, then I'll commit it.

```js
	$header = $this.data( 'header' );
if ( !$header ) { return; }  // <--- ********** ADD THIS LINE **********
if ( !$header.is(':visible') ) {
```

**Comment by sportok** [comment]
Hi,
i haven't colspan and the number of cols is correct. So i think Html is good.
The bug is corrected by adding your recommended line. Column Filter, sorter and filter function correctly.

**Comment by Mottie** [comment]
Oh, that's good to hear! I'll push a new release soon.

**Comment by hynese** [comment]
I also have a problem with no sort icons:

![screen shot 2015-04-04 at 13 30 21](https://cloud.githubusercontent.com/assets/315697/6992591/27fd1ad0-dacf-11e4-9318-e5d8dfed41e3.png)

I'm using clean HTML. I have the bootstrap theme. widgets.js enabled.

Here's what I use to sort:

```$('#eoh_table').tablesorter({
              theme: 'bootstrap',
              widthFixed: false,
              dateFormat: "ddmmyyyy",
              widgets: ['zebra', 'columns']
});```

**Comment by Mottie** [comment]
Hi @hynese!

It looks like the header template is missing the icon definition:

```js
headerTemplate: '{content} {icon}',
```

**Comment by hynese** [comment]
Hello, I just did that and it didn't work...

I can see a `<i class="tablesorter-icon"></i>` where there should be a sort icon in Firebug.

**Comment by Mottie** [comment]
What about the `theme.bootstrap.css` file, is that being included?

**Comment by hynese** [comment]
Hi, I don't have a file called "bootstrap.min.css"

I'm using bower.io

I can see the following .min.css files:

./dist/css/dragtable.mod.min.css
./dist/css/filter.formatter.min.css
./dist/css/jquery.tablesorter.pager.min.css
./dist/css/theme.blackice.min.css
./dist/css/theme.blue.min.css
./dist/css/theme.bootstrap.min.css
./dist/css/theme.bootstrap_2.min.css
./dist/css/theme.dark.min.css
./dist/css/theme.default.min.css
./dist/css/theme.dropbox.min.css
./dist/css/theme.green.min.css
./dist/css/theme.grey.min.css
./dist/css/theme.ice.min.css
./dist/css/theme.jui.min.css
./dist/css/theme.metro-dark.min.css


Do I need to install jquery-ui?

**Comment by Mottie** [comment]
bootstrap.min.css is the main Bootstrap style... link to it or get it from here: http://www.bootstrapcdn.com/

**Comment by hynese** [comment]
Hello,

I had that included already. I appreciate you helping me with this.

Here are the includes I'm using:

```
<!--global dependencies-->
<link href="./lib/bower_components/bootstrap/dist/css/bootstrap.css" rel="stylesheet">
<link href="./lib/bower_components/font-awesome/css/font-awesome.min.css" rel="stylesheet">

<script src="./lib/bower_components/jquery/dist/jquery.min.js"></script>
<script src="./lib/bower_components/bootstrap/dist/js/bootstrap.js"></script>

<script src="./lib/bower_components/json2/json2.js"></script>

<script src="./lib/bower_components/fancybox/source/jquery.fancybox.js"></script>
<link href= "./lib/bower_components/fancybox/source/jquery.fancybox.css" rel="stylesheet" />

<script src="./lib/bower_components/tooltipster/js/jquery.tooltipster.min.js"></script>
<link href="./lib/bower_components/tooltipster/css/tooltipster.css" rel="stylesheet" />

<script src="./lib/bower_components/jquery-cookie/jquery.cookie.js"></script>



<!--dependencies specific to the page with the tablesorter:-->
<link  href="./lib/bower_components/jquery.tablesorter/dist/css/theme.bootstrap.min.css" type="text/css" rel="stylesheet">
<script src="./lib/bower_components/jquery.tablesorter/dist/js/jquery.tablesorter.combined.min.js" type="text/javascript"></script>

<script src="./lib/bower_components/phpjs/functions/datetime/date.js" type="text/javascript"></script>
```

**Comment by Mottie** [comment]
If the initialization script includes the code mentioned before, then I'm not sure where the problem exists.

Please use the browser development tools to see if the table is getting a "tablesorter-bootstrap" class added to it and the css from the theme file is being applied. Also the "tablesorter-icon" inside the sortable header cells should also be getting a "bootstrap-icon-unsorted" class added to it.

**Comment by hynese** [comment]
Hi Mottie,

I can't see how I can fix this.

I tried an isolated:

```
<i class="tablesorter-bootstrap bootstrap-icon-unsorted">hello</i><br>
```

All I see is "hello" - no icons anywhere.

I can see the following CSS in Firebug:

```
.tablesorter-bootstrap .bootstrap-icon-unsorted {
    background-image: url("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAAOCAMAAADOvxanAAAAVFBMVEUAAABCQkJZWVkZGRnJyckgICAZGRkZGRn8/PweHh4dHR0aGhoaGhpUVFQbGxvQ0NDc3NxMTExSUlIbGxvr6+s4ODhKSkogICAtLS00NDQzMzMnJydSEPrQAAAAGHRSTlMA1ssZRLgdAQbDyisqsZo8QdXUq0r9xPepSRwiAAAAX0lEQVQI13XHSQKAIAwEwQAKxn13Ev7/T2Pu9qmarJKPXIicI4PH4hxaKNrhm2S8bJK5h4YzKHrzJNtK6yYT/TdXzpS5zuYg4MSQYF6i4IHExdw1UVRi05HPrrvT53a+qyMFC9t04gcAAAAASUVORK5CYII=");
}
```
When I mouse over it, I can see an up-down icon rendered.

**Comment by Mottie** [comment]
The unsorted icon symbol is not included in Bootstrap, so it is included in the "theme.bootstrap.css" file.

It appears that the style is being applied. Maybe there is some other css on the page that is interfering.

I set up [this demo](http://jsbin.com/neyowu/2/edit?html,output) so you can compare the differences. Other than that, I'm not sure what to tell you without seeing the page myself.

**Comment by Mottie** [comment]
v2.21.5 is now available, so I'm closing this issue.

@hynese we can continue our discussion in this thread.

**Comment by hynese** [comment]
Hi Mottie, thank you for the push. I'm doing so much in parallel at the moment. I will test and report back.
