### ISSUE TITLE
Freezing initial columns doesn't seem to work when filter widget is not included

### ISSUE THREAD

**Issue by phildin** [Mottie/tablesorter#860]
I've created a minimal example in which freezing of the initial columns works based on the example at http://mottie.github.io/tablesorter/docs/example-widget-scroller.htm

This cut down version is here:
http://www.mobius.ie/tablesorter/index2.html

The problem is that the entire table scrolls horizontally without the initial 2 columns being frozen. If I add in the 'filter' widget then it correctly freezes the first 2 columns as per the link below:
http://www.mobius.ie/tablesorter/index.html

Note that occasionally the non-working example will show the expected behaviour but following a reload, will revert to the erroneous behaviour with the whole table scrolling.

**Comment by Mottie** [comment]
Hi @phildin!

Hmm, you're right... but if I resize the window it starts working. I'll take a look at this later when I get some more time.
