### ISSUE TITLE
Tablesorter column selector not showing.

### ISSUE THREAD

**Issue by aeryn21** [Mottie/tablesorter#861]
I've got a bootstrap site template that I'm using for a dynamic redesign of my work's website, and am trying to use the filter function in tablesorter 2.21.4 and jquery 1.11.1.

[Beta Site] (http://beta.apogeerockets.com/index.php?main_page=product_rocket_info&cPath=1_2&products_id=6)

--I've got the filter to show, it's responding to select/false/etc filters I give the headers, and I can input text or select a drop-down, but it's not actually filtering anything.-- ** *See comment* ** Sort works fine. I'm still a jquery n00b, so I'm wondering if there's a conflict somewhere? Or I'm missing something?  It might possibly be with the widgets.js, because I cannot get the column selector widget to activate either.

We have an older version (2.10.8) working just fine on our [current site] (https://www.apogeerockets.com/Rocket_Kits/Skill_Level_1_Kits/Apprentice_Rocket_Kit) using a dynamically generated table. On the beta, the dynamic table wasn't sorting, so I copied the code directly from Mottie and it is still not working. :/

**Comment by aeryn21** [comment]
Well, at least for the filtering part, looks like my css template wasn't loading correctly.  Tweaked css so that the .filtered class is in another css file, and now it's filtering correctly.

Now to figure out why the check boxes on the column selector isn't working.

**Comment by aeryn21** [comment]
Alright, figured out both issues.

1. .filtered class is not included in theme.default.css.  Added there.
2. Column selector js is a separate file (not in default widget.js, as I thought), so added file.  Works OK now.  :)

**Comment by Mottie** [comment]
Hi @aeryn21!

I'm glad you figured out the issues! I've had a busy day so I haven't had a chance to followup until now.

The `filtered` class is defined in the [default theme file](https://github.com/Mottie/tablesorter/blob/master/css/theme.default.css#L185-L187), so maybe you were using an older version?

And yes, the columnSelector widget is separate, but if you make a [custom build](https://github.com/Mottie/tablesorter/wiki/Customize) using grunt, you can include the columnSelector along with any other widgets you plan to use.
