### ISSUE TITLE
How to for textArea field in tablesorter?

### ISSUE THREAD

**Issue by ramjeekabra** [Mottie/tablesorter#863]
When tablesorter has a text area field to display, the field tends to take up lot of space or increase the height of the row causing vertical scrolling to be more. I would like to know if there is a way to implement kind of ellipsis with "Show More" link at the end of the shortened text and display the complete content of text area in a pop up on click of "Show More"?

**Comment by Mottie** [comment]
Hi @ramjeekabra!

Are the textareas readonly? Why even use them if you want to limit the view?

Anyway, textareas can be styled using css to limit its height and width; but a user can resize it as desired, so why not use a div with a tooltip containing all the contents?

**Comment by ramjeekabra** [comment]
Hi Mottie,

The textarea data is readonly, not editable. The textarea is a product description which the users want to see only when needed.Displaying the complete content takes up lot of real estate on the UI thus cluttering it. Thats why just showing a part and allowing them to view the content when they clik on a link in the text area makes sense. Also that will allow to look into more rows on the table becasue right now the decription takes up lot of height thus showing only 4 - 5 product details on the UI. Reducing that would show about 15+ products.

**Comment by Mottie** [comment]
I would urge you to reconsider using a textarea. Maybe use you can include additional information in a hidden child row which is revealed on clicking a link... something like this: http://jsfiddle.net/Mottie/856bzzeL/113/

HTML

```html
<tbody>
    <tr>
        <td>Widget 01</td>
        <td>W124535</td>
        <td>$20.00</td>
        <td><a href="#">Show more&hellip;</a></td>
    </tr>
    <tr class="tablesorter-childRow hidden">
        <td colspan="4">
            <img src="http://lorempixel.com/100/100/technics/"/>
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Morbi at nisi enim. Aenean et molestie odio, at auctor felis. Etiam a arcu vitae orci luctus sagittis. Ut suscipit justo metus, sit amet blandit sapien ultrices a. Vivamus eu venenatis nulla, ac euismod ante. In non diam quis erat congue maximus in et purus. Nulla consequat tristique enim ac scelerisque. Nulla volutpat interdum eros a mollis.</td>
    </tr>
    ...
</tbody>
```

Script

```js
$(function () {
	$('table').tablesorter({
		theme: 'blue'
	});
    
    $('table').on('click', 'a', function(){
        $(this).closest('tr').next().toggleClass('hidden');
    });
    
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
