### ISSUE TITLE
Resizing columns issue with cursor location

### ISSUE THREAD

**Issue by garciaan** [Mottie/tablesorter#864]
The location of the cursor to resize the columns is not on the edge of the columns, but to the left of the sorting button in the header. Then, when I resize the window, the cursor the resizing of the columns is about 4 columns to the right in the middle of one of the headers. I am not sure what I am doing wrong. This is implemented in my own theme in wordpress as a wordpress plugin that I made with the table sorter plugin. The resizing works but the cursors are just completely in the wrong position.

**Comment by Mottie** [comment]
Hi @garciaan!

Are you using the columnSelector widget? If so, use the [resizable widget from the master branch](https://github.com/Mottie/tablesorter/blob/master/js/widgets/widget-resizable.js), it's got a patch to make it work with that other widget.

If that isn't the issue, then is there a way you can provide a demo replicating the problem? Or some way I can see the issue?

**Comment by garciaan** [comment]
I am not using that widget. You can see the issue here. I will only lift the password restriction for a day or so so let me know if you havent seen it yet and I can send you the password. I just don't want my students registering on the uncomplete website yet. 

Here is the link. It doesn't work in IE for some reason (no surprise)

http://campuslifeohs.com/test/

**Comment by Mottie** [comment]
Hmm, ok I've seen it... I made a local copy of the page for further testing, so you can restore the password.

**Comment by garciaan** [comment]
OK thank you.

**Comment by Mottie** [comment]
Ok, it should be all fixed now! :smiley_cat:

**Comment by garciaan** [comment]
Awesome. Thank you so much!
