### ISSUE TITLE
Cannot sort plain text 

### ISSUE THREAD

**Issue by johnnymex** [Mottie/tablesorter#865]
Hi,
For no apparent reason, I can't sort on a column containing plain text.
Sorting on the leftmost column "jobname" is not a problem, but the column "description" can not be sorted. When using the F12 debugger I can see when I try to sort on the column. many attributes are changing , like class atribute and aria-sort from ascending to descending, but reaction the tablecontent itself . 
I hope you can read the 2 PNG images I have attached, otherwise let me know how I can send these images to you

Best regards,
JohnnyMex

![tablesorter_p1](https://cloud.githubusercontent.com/assets/11174564/7045303/4d7edf4c-ddfd-11e4-9c05-bd9bb17c5aba.PNG)
![tablesorter_p2](https://cloud.githubusercontent.com/assets/11174564/7045302/4d7d0bc2-ddfd-11e4-9f90-3d9604887c7a.PNG)

**Comment by Mottie** [comment]
Hi @johnnymex!

What are the "showtime" and "testgroup" rows? Are they in "info-only" tbodies? Or a row with a `colspan`?

Tablesorter doesn't not currently support `colspan` or `rowspan` within the `tbody`. 

Also, the pager doesn't "officially" support multiple tbodies, but you can modify the [`ajaxProcessing` function](http://mottie.github.io/tablesorter/docs/#pager-ajaxprocessing) to get around that (see [issue #458](https://github.com/Mottie/tablesorter/issues/458#issuecomment-77555715)).

Are you seeing any errors in the console?

It would really help if you could modify [this demo](http://jsfiddle.net/yfwwzvL8/) (using the pager widget) to duplicate the reported issue. If you're using the pager addon, then modify [this demo](http://jsfiddle.net/1a5yu8yq/).

Thanks!

**Comment by johnnymex** [comment]
Hi Rob,
The table is with multiple tbodies, just like your example on "example-multiple-tbodies.html". And in this example, sorting works fine. (The pager is developed by me and is not a part of the tablesorter extensions).
The first column "Jobname" contains a bunch of anchors and sorting on this columns works perfectly well. And I what I don't understand is why sorting on the next column "description" does not work.
If you study the second attachment, you will notice that both TH tags looks pretty much the same.
When I click ASC/DESC on the header field, I can see action in the  F12 debugger -window, class name changes back and forth between "tablesorter-headerAsc" to "tablesorter-headerDesc" and attribute aria-sort between "ascending" and "descending". the column must "see" that I am changing sort-order, but change in the columns them selves

**Comment by johnnymex** [comment]
, but NO change in the columns them selves
(I forgot a NO !, sorry )    :-)

**Comment by Mottie** [comment]
I'm pretty sure this has to do with how the cache is being populated.

As I said, tablesorter does not currently support `colspan` and `rowspan` in the tbody, unless it is inside of a info only tbody (class name set by the [`cssInfoBlock` option](http://mottie.github.io/tablesorter/docs/#cssinfoblock))

So the HTML should look like this to make it work properly:

```html
<tbody>
	<tr>
		...
</tbody>
<tbody class="tablesorter-infoOnly">
	<tr>
		<td colspan="5">showtime</td>
	</tr>
</tbody>
<tbody>
	...
</tbody>
<tbody class="tablesorter-infoOnly">
	<tr>
		<td colspan="5">testgroup/td>
	</tr>
</tbody>
<tbody>
	...
</tbody>
```

You can check the cache by opening the browser console and typing in the following:

```js
$('table')[0].config.cache
```

And check the `normalized` portion of the cache to see if it is being populated properly.

**Comment by johnnymex** [comment]
Hi Rob,

I managed to create a couple of HTML-pages that boiled  it down  to the table-sorting problem in question.
I have made one page using the multiple tbodies and one page that does not.
Anyway, the problem is the same. Here you can try it yourself, and I hope you will come up with a solution to the problem.

Med venlig hilsen / Best Regards

Johnny Olsen
Developer

[Accobat final1]<http://www.accobat.com/>

Accobat A/S | København | Aarhus
T  +45 3211 1090 | M +45 3138 2922
joo@accobat.com<mailto:joo@accobat.com> | www.accobat.com<http://www.accobat.com/>

Følg os på [cid:image003.jpg@01CF7FEB.11EBEC70] <https://www.linkedin.com/company/accobat-as?trk=biz-companies-cym>

**Comment by johnnymex** [comment]
Hi Rob,
I managed to create a couple of HTML-pages that boiled  it down  to the table-sorting problem in question.
 I have made one page using the multiple tbodies and one page that does not. 
Anyway, the problem is the same. Here you can try it yourself, and I hope you will come up with a solution to the problem.

However, I tried to attach a zip file - but zip files are not supported in this system.
So I have sent the zip file via e-mail and I hope it will reach you successfully

**Comment by Mottie** [comment]
I did not get the file. My gmail name is `wowmotty`.

**Comment by Mottie** [comment]
Ok, the problem is with the parser settings.

* In the "HtmlPage1" file:
  * The "Result" column is being set to "digit" (it's a bug in the `isDigit` function) instead of "text" because it was only looking in the first tbody which only has an empty string.
  * To fix this add a `sorter-text` class name to the "Result" header

      ```html
      <th class="sorter-text">Result</th>
      ```

* The "HtmlPage2" file:
  * The `sorter: `"shortDate"` is set on the wrong column. Actually, setting the sorter in the second file is not even necessary as "shortDate" is auto-detected
  * There are no completely empty columns in the first tbody so the "Result" column is properly detected as needing a "text" parser.

* Overall
  * I would not recommend using attributes like `cat`;

      ```html
      <td cat="starttime"></td>
      ```

     instead use HTML5 data attributes, so the above would become `data-cat="starttime"`

**Comment by johnnymex** [comment]
Hi Rob,

That did the trick !  Thank you !
