### ISSUE TITLE
requirejs error when initializing tablesorter outside of requirejs

### ISSUE THREAD

**Issue by nikolas** [Mottie/tablesorter#867]
I'm using require.js 2.1.15, and I'm including tablesorter on the page outside of my requirejs app, I get this error because tablesorter is registering itself as an AMD module:
`Uncaught Error: Mismatched anonymous define() module: function (a){return function(a){"`

django-debug-toolbar has also struggled with this problem: https://github.com/django-debug-toolbar/django-debug-toolbar/pull/591

My temporary solution is just to remove the equivalent of this code from the minified tablesorter file that I'm using:
```js
(function(factory) {
	if (typeof define === 'function' && define.amd) {
		define(['jquery'], factory);
	} else if (typeof module === 'object' && typeof module.exports === 'object') {
		module.exports = factory(require('jquery'));
	} else {
		factory(jQuery);
	}
}
```

**Comment by nikolas** [comment]
Actually, the issue resolved itself and I don't know why. Currently, the pre-build tablesorter.min file is working fine for me.

**Comment by Mottie** [comment]
Very odd, but I'm glad I didn't have to include a work around like they did...
