### ISSUE TITLE
Hidden columns + Output widget

### ISSUE THREAD

**Issue by umbertix** [Mottie/tablesorter#869]
Hi there I did find out a problem with the Output widget and the hidden columns.

If I do set a `display: none;` to the columns that I want to hide they do not appear on the visual table but neither on the output result file.

If I do set `visibility: hidden;` to the columns that I want to hide the data and the header of the columns do not appear but the table keeps the space for the columns but and on the output result file everything is there as expected.

Thanks.

**Comment by Mottie** [comment]
Hi @umbertix!

When `display:none` is set, that is the expected behavior.

I have no idea why anyone would set `visibility: hidden` on a table, the empty space does not look good. The output widget is not looking for visibly hidden cells, so it includes them in the output.... I'm not sure why that would be "as expected".

So what exactly is the issue being reported here?

**Comment by umbertix** [comment]
Hi @Mottie,

Since I did saw the option:
output_saveRows: 'a'; (a)ll, (f)iltered or (v)isible

I did expected to be able to hide a column or a row, and using the 'a' option getting as output the full table. I guess that those options only apply for the filtered results but even tho, I think that would be a good think. Probably I'm not the first one to encounter this 'problem'. I know that outputting different data than the one that you are displaying is a nonsense thing to do in most cases but...

**Comment by umbertix** [comment]
Hi @Mottie,

I did find out the solution to my problem, I just did created a class for the hidden columns with font-size to 0. So now they are not displayed but they appear correctly in the export file.

Regards and thx for your time.

.tablesorter_hidden{
	font-size: 0px;
}

**Comment by Mottie** [comment]
The [`output_saveRows` option](http://mottie.github.io/tablesorter/docs/example-widget-output.html#output_saverows) allows selects which **rows** to output. It has nothing to do with columns.

The [`output_ignoreColumns` option](http://mottie.github.io/tablesorter/docs/example-widget-output.html#output_ignorecolumns) allows you to hide columns in the output.

I didn't understand what it was you were reporting until now... I see there isn't an option to allow the output of hidden columns. It would not be difficult to add an option to allow it.
