### ISSUE TITLE
Tablesorter not working properly on Google Chrome

### ISSUE THREAD

**Issue by briantjuhh007** [Mottie/tablesorter#870]
I tried my tablesorter on firefox and it worked perfectly, when I try using it on google chrome, he only sorts the strings but not the datetimes?

thanks in advice.
Brian

**Comment by briantjuhh007** [comment]
SOLVED

Google Chrome couldn't parse the amsterdam time d-m-Y H:i
maybe one for a fix?

**Comment by Mottie** [comment]
Hi @briantjuhh007!

Are you setting the [`dateFormat` option](http://mottie.github.io/tablesorter/docs/#dateformat) to `"ddmmyyyy"`?

If you are setting that option, can you please share some examples of that date format.

**Comment by briantjuhh007** [comment]
I tried that but it didn't work. I got it fixed already, i'll check it out when im back at home if I put 'ddmmyyyy'.
Im at work now and I don't want to mess up my application now.
