### ISSUE TITLE
Column totals at top of table

### ISSUE THREAD

**Issue by lbstoller** [Mottie/tablesorter#872]
Hi. I have a table with column totals at the bottom of the table (using the math widget), defined
in a tfoot. But I'd like to have them at the top of the table, and if I put the same html inside the
thead, it does not do it. Is this expected to work, if so I will send along more details. 

Thanks!

**Comment by Mottie** [comment]
Hi @lbstoller!

The math widget does not target the `thead` when calculating or displaying results. Although, you could use the [`match_complete` callback](http://mottie.github.io/tablesorter/docs/example-widget-math.html#math_complete) to target any HTML in the `thead`.

```js
// complete executed after each function
math_complete : function($cell, wo, result, value, arry){
    $cell.closest('table').find('thead .totals').html( result );
    return result;
}
```

**Comment by lbstoller** [comment]
Thanks! A slightly easier fix was to edit the math widget source code and add a line to look inside the thead.

diff --git a/www/aptui/js/lib/jquery.tablesorter.widget-math.js b/www/aptui/js/lib/jquery.tablesorter.widget-math.js
index 54962d5..20c460b 100644
--- a/www/aptui/js/lib/jquery.tablesorter.widget-math.js
+++ b/www/aptui/js/lib/jquery.tablesorter.widget-math.js
@@ -129,6 +129,9 @@
 				math.mathType( table, wo, $mathCells, wo.math_priority, dataAttrib );
 
 				// only info tbody cells
+				$mathCells = c.$table.find('.' + c.cssInfoBlock + ', thead').find('[' + dataAttrib + ']');
+				math.mathType( table, wo, $mathCells, wo.math_priority, dataAttrib );
+				// only info tbody cells
 				$mathCells = c.$table.find('.' + c.cssInfoBlock + ', tfoot').find('[' + dataAttrib + ']');
 				math.mathType( table, wo, $mathCells, wo.math_priority, dataAttrib );

**Comment by Mottie** [comment]
Honestly, I would not recommend doing that... every time you update this plugin and there is a change to the math widget (like the one I just pushed this morning), you have to remember to go back and make the change.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by osterhase90** [comment]
How can I use it for more columns with math-widget?
