### ISSUE TITLE
tablesorter  not suport IE7 and input input type="text"

### ISSUE THREAD

**Issue by AviHafner** [Mottie/tablesorter#876]
Thanks you  for the best plugin I know,
 I have 2 issues 
 1. Unfortunately tablesorter does not work in internet-explorer Compatibility-mode to 7, in The University that I work, lot of people working in this mode.
 2. I develop my project with Visual-Studio and the td I have input field with value,
 tablesorter not seems to recognize this situation and the workaround is to build hidden field with value in the same td

Thank you
 Hafner Avi

**Comment by TheSin-** [comment]
for problem 2 use the input parser

http://mottie.github.io/tablesorter/docs/example-widget-grouping.html

**Comment by AviHafner** [comment]
תודה על התשובה המהירה
האם תוכל לכתוב לי דוגמא ,
לצערי אני חדש בתחום

**Comment by AviHafner** [comment]
Thanks for the quick reply
Can you write me an example,
Unfortunately I am a newcomer

**Comment by TheSin-** [comment]
The example is what I posted ;)

I'll see if I can make an other one but honestly I'd just copy that example to jsfiddle if I did.  I have to run to work now but i'll check in on this in a bit.

**Comment by Mottie** [comment]
Hi @AviHafner!

Are you seeing any error in the console when running in IE7 compatibility mode? I have no idea why you would want to downgrade the version of IE... :disappointed: 

Anyway, [this is the input-select parser](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js). It is a separate file from the main plugin and needs to be loaded, and the parser for that column needs to be set. The easiest ways to set the parser are by class name:

```html
<th class="sorter-inputs">Foo</th>
```

or in the [`headers` option](http://mottie.github.io/tablesorter/docs/#headers):

```js
headers : {
    0 : { sorter: 'inputs' }
}
```

The demo @TheSin- linked is to show how it works - you can look at the page source.

**Comment by AviHafner** [comment]
**Lot of thanks**, I have adopted the solution and it does work nicely,

Is there a solution that has a Solution for **form-input-field** and mixing **regular text**, in the same Column?

**Another problem** I have encountered, typing on the search-field causes opening a autocomplete window,     how I solved this undesirable trait

**Comment by AviHafner** [comment]
You can read how to use ie7 computable mode 
[Microsoft instructions Work with to Work in E7 compatibility mode](http://windows.microsoft.com/en-us/internet-explorer/use-compatibility-view#ie=ie-11)
[Picture how to configure the Ie11 Work Website mottie.github.io in computablemode](http://www.admin.technion.ac.il/avi/ComptableMode.PNG)

*I get an error*
c.$headers
	.removeClass(css.join(' '))
					.addClass(none).attr('aria-sort', 'none')
					.find('.' + ts.css.icon)
					.removeClass(cssIcon.join(' '))
					.addClass(cssIcon[2]);
**Member not found.**

**Comment by AviHafner** [comment]
Hi **Friends**
I found in the product documentation all I needed
A big thank

**Comment by Mottie** [comment]
Oh? What was the problem? Would you please post it here to help others in case they run into the same problem and search through these issues. Thanks!

**Comment by AviHafner** [comment]
**Computable display problem with IE7**,
I think that my organization should work with advanced standards,
And not to work with old and not supported standards.
**All the other problems**  your documentation is excellent and served me a lot of help to finding  solution

**Thanks for the great Work**
Yours
Avi Hafner
