### ISSUE TITLE
Sorting order is not saved

### ISSUE THREAD

**Issue by kotmatpockuh** [Mottie/tablesorter#877]
For example:

http://jsfiddle.net/abkNM/5611/

after `f5` - order is not saved... how to fix it?

**Comment by Mottie** [comment]
Hi @kotmatpockuh!

There is a ["saveSort" widget](http://mottie.github.io/tablesorter/docs/example-widget-savesort.html) you can use.

**Comment by kotmatpockuh** [comment]
thank you
also: does this plugin support sorting via multiple fields?

**Comment by Mottie** [comment]
Yes, hold <kbd>shift</kbd> + left click to include multiple columns.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
