### ISSUE TITLE
scroller / contenteditable

### ISSUE THREAD

**Issue by kevintc** [Mottie/tablesorter#878]
Hello,

I'm using the scroller widget which works pretty well but it disables the contenteditable ability of the fixed columns.

I define my contenteditable columns using : `<td contenteditable='true'>`
I tried to use the Content editable widget without any success either.

Is there any work around ? I need my first three columns to be fixed AND content editable :)

Can you help me ?
Best regards

**Comment by Mottie** [comment]
Hi @kevintc!

Yeah, I need to make the frozen column have selectable text, working links (see #135) and work with the editable widget. I'll try to get to it this weekend when I have some free time.

**Comment by dqduc** [comment]
A temporary solution that worked on my side:
.tablesorter-scroller-fixed th, .tablesorter-scroller-fixed td {
     pointer-events: all;
}

**Comment by kevintc** [comment]
Well, thanks @dqduc , it works. Now I just have to fix the separate hover behavior :) and wait for an official fix for contenteditable & scroller widget :)

**Comment by Mottie** [comment]
The scroller is currently incompatible with the editable widget. I've centralized all of the scroller widget incompatibilities into one issue (#1487). Please follow any progress there.
