### ISSUE TITLE
Custom columns selector using a link ?

### ISSUE THREAD

**Issue by kevintc** [Mottie/tablesorter#879]
Hi! :)

I looked up the "Column Selector Widget", seems to work pretty well...
Is there a way to use a link to select specific predefined columns to show/hide ?
I could use the selector dropdown menu but is there an easier way ?

I would like to have some fixed columns, and a link that I could use to show, say... columns 5 to 10, then another link to toggle columns 11 to 20, ...

![image](https://cloud.githubusercontent.com/assets/7962247/7253358/6f7cab26-e83c-11e4-8846-519d913614ba.png)

Here is an example using Slickgrid :

    $("#coverage").click(function () {
        var columns = [];
        columns = columns.concat(TVC.all, TVC.coverage);
        TVC.grid.setColumns(columns);
        $("#coltabs").find("li").removeClass("active");
        $(this).parent().addClass("active");
        setCheckAll();
    });

where TVC.all are the fixed columns and TVC.coverage the view specific ones.

Did I miss something in the documentation ?

**Comment by Mottie** [comment]
Hi @kevintc!

Check out the [methods](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#methods) section in the columnSelector documentation:

> In v2.19.0, this method will now accept a parameter.
> * The parameter can be either an array of zero-based column indexes to toggle columns on and off:
>
>   ```js
>   $('table').trigger('refreshColumnSelector', [ [2,3,4] ]);
>   ```
>   Note
>   * Passing an array will turn "auto" mode off.
>   * Make sure to wrap the array inside another array.
>   * Columns marked as "critical" or "disable" will never get toggled off using this method.
> * Or, set the parameter to any non-array value to turn the "auto" mode on - this only works if the `columnSelector_mediaquery` is set to `true`:
>
>  ```js
>   $('table').trigger('refreshColumnSelector', true);
>  ```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
