### ISSUE TITLE
npm is without widgets

### ISSUE THREAD

**Issue by Kepro** [Mottie/tablesorter#881]
Hi @Mottie  can you please add widgets to package.json ? my project only use npm to install dependencies not using copy from files (missing cssStickyHeader) 

Thanks!

**Comment by Mottie** [comment]
Hi @Kepro!

Hmm, the documentation for package.json isn't that great. I'll make this change

```js
  "files": [
    "dist/"
  ],
```

but I'm not sure if it'll apply after I use `npm publish` or when I bump the version.

I won't have a lot of time to work on bugs and push the next update until this weekend.

**Comment by Mottie** [comment]
Yeah, I can't publish until I bump the version. Sorry!

**Comment by Kepro** [comment]
@Mottie thanks for fast response ;) i wait for new version no problem
