### ISSUE TITLE
Input field with numeric values 

### ISSUE THREAD

**Issue by AviHafner** [Mottie/tablesorter#888]
I got from you an example of the input field
I would like an example when values are numeric

**Comment by Mottie** [comment]
What specifically are you asking about?

The default [`inputs` parser](https://github.com/Mottie/tablesorter/blob/master/js/parsers/parser-input-select.js#L18-L28) only handles text. I guess I could include an additional parser in the "parser-input-select.js" file for numeric only inputs (maybe of type number?).

```js
$.tablesorter.addParser({
	id: "inputs-numeric",
	is: function(){
		return false;
	},
	format: function(s, table, cell) {
		var v = $(cell).find('input').val() || s,
			n = $.tablesorter.formatFloat((v || '').replace(/[^\w,. \-()]/g, ''), table);
		return n && typeof n === 'number' ? n : n ? $.trim( s && table.config.ignoreCase ? s.toLocaleLowerCase() : s ) : s;
	},
	parsed : true, // filter widget flag
	type: "numeric"
});
```

You can add the above widget, *and* load the "parser-input-select.js" file for the extra code to make this work.

**Comment by AviHafner** [comment]
Rob ,
A huge thank, it works
Yours
Hafner Avi

Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>

**Comment by thezoggy** [comment]
just to note you also could just use html5's input type number... but you should still do some validation on your back end just in case they are using a browser that doesnt do html5 (then it'd just be a normal text input).
 
http://html5doctor.com/html5-forms-input-types/#input-number
