### ISSUE TITLE
Math widget with dynamically added content.

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#889]
Maybe this isn't as much an issue of the widget as of the documentation but how exactly can one get it to work with dynamically added content? Apparently running "update" isn't enough and the setting "math_event" isn't documentation very well. When I set it that setting to "update" then the summing works correctly but filtering/sorting stops working.

See http://jsfiddle.net/Herst/pcmsL943/
(Also note that the table can't be empty at init time otherwise it fails in the init code that runs the computeColumnIndex function.)

BTW, thanks for the great plugin!

**Comment by Mottie** [comment]
Hi @Herst!

Thanks for reporting this... the fix I just pushed should take care of it :)

I hope to have a new release out by this weekend.

**Comment by Herst** [comment]
Great, works indeed: http://jsfiddle.net/Herst/pcmsL943/9/
Thank you!

**Comment by Herst** [comment]
But starting with an empty table doesn't appear to work: http://jsfiddle.net/Herst/pcmsL943/10/
>    Uncaught TypeError: Cannot set property 'formatMask' of undefined

**Comment by Mottie** [comment]
Yes, sorry, a tablesorter core update (`computeColumnIndex` function) is also part of this fix.
