### ISSUE TITLE
Exact match with boolean operations

### ISSUE THREAD

**Issue by omnilord** [Mottie/tablesorter#891]
I am trying to do a search for `"option 1" OR "option 2"` in a field, but I get nothing.  I used the example from the documentation to create a fiddle for this.  In the fiddle, I am trying to find either `"Bruce"` **or** `"Aaron"` but **not** `"Bruce Lee"` or `"Philip Aaron Wong"`.

[Example based from http://mottie.github.io/tablesorter/docs/example-widget-filter.html](http://jsfiddle.net/Omnilord/3c00b9ss/)

I think this is actually a feature request since the documentation does not specify that you can use `"` in conjuncture with `AND` or `OR` operations.

**Comment by TheSin-** [comment]
you can not combine search elements.  You are using " = literal + or, use one or the other, so use

bruce or aaron, or use "Bruce" you can not do both at once.

**Comment by thezoggy** [comment]
can use regex?

**Comment by Mottie** [comment]
I actually answered this question on [stackoverflow](http://stackoverflow.com/questions/29873053/how-to-filter-jquery-tablesorter-by-multiple-columns-using-or-logic) ([demo](http://jsfiddle.net/Mottie/4mVfu/4701/))...

```js
$(function () {
    var $table = $('table'),
        // get 'filter-OR' column indexes
        orColumns = $('.filter-OR').map(function (i) {
            return this.cellIndex;
        }).get(),
        filterfxn = function (e, n, f, i, $r, c) {
            var col, v,
                showRow = false,
                content = [];
            $r.children().filter(function (indx) {
                if (orColumns.indexOf(indx) > -1) {
                    v = (c.$filters.eq(indx).find('.tablesorter-filter').val() || '').toLowerCase();
                    showRow = showRow || $(this).text().toLowerCase() === v;
                }
            });
            return showRow;
        };

    $table.tablesorter({
        theme: 'green',
        widgets: ['uitheme', 'zebra', 'columns', 'filter'],
        sortReset: true,
        sortRestart: true,
        widthFixed: true,
        widgetOptions: {
            filter_functions: {
                '.filter-OR': {
                    'Yes': filterfxn,
                    'No' : filterfxn
                }
            }
        }
    });
});
```

I've been working on the filter widget to make it more straight-forward, by adding a `data` parameter to the `filter_functions`. The same `data` passed to the [filter type functions](http://mottie.github.io/tablesorter/docs/example-widget-filter-custom-search.html#how_to_add_custom_filter_types).

I know this looks messy, so I'm thinking about removing the extra parameters in a later update.

```js
filter_functions : {
  0 : function(e, n, f, i, $r, c, data) {} // <- parameters in the next update
  // 0 : function(c, data) {} // planned change (version undetermined)
}
```

**Comment by omnilord** [comment]
This was actually a different issue where I was trying to do an OR on multiple *exact* match entries in one column using the existing filter semantics.

Having a data parameter accessible would make multiple column sorts a lot easier.

**Comment by Mottie** [comment]
Oh, and @thezoggy, yes regex would work too... it's just that the average user won't know how to use it.

So `"option 1" OR "option 2"` should be equivalent to `/^option (1|2)$/` (untested).

**Comment by Mottie** [comment]
Oh and @omnilord! Yeah, I realize now that this issue is different from the Stackoverflow question... I've been so busy lately that I didn't intently read this issue text. I assumed it was the same because they were both posted by you around the same time. Sorry!

So, as @TheSin- stated, combining an exact search with "AND" or "OR" searches isn't possible at the moment. I would have done it long ago, but because I think this functionality should work with multiple operators (e.g. `"bruce" OR "Aaron" or "Brenda"), I would need to do a bunch of internal code changes to loop through the filter types. Making it work with only two operators is just too easy :wink:

**Comment by Mottie** [comment]
I've started working on this feature... see #918 for updated information. The other issue is very similar to this one, but I left it open because it requested including other filter types with the "OR".

**Comment by Mottie** [comment]
I just updated the filter widget. You can use filter queries like:
* `<10 or >40`
* `>20 && <40`
* `a && !o`
* etc.

Only the "AND" and "OR" filter queries allow nesting.. so you can't do something like `!(20 - 30)`.
