### ISSUE TITLE
table inside a table?

### ISSUE THREAD

**Issue by southmeadows** [Mottie/tablesorter#892]
Is there a way to have a table inside a table? I know how to do this in C or .NET but not in PHP and tablesorter. 

In other words have a parent row and under the parent row child records

Is that possible? If so is there any documentation on this?

**Comment by Mottie** [comment]
Hi @southmeadows!

I think what you are referring to is a child row... just add the class defined in the [`cssChildRow` option](http://mottie.github.io/tablesorter/docs/#csschildrow) , which is `"tablesorter-childRow"` by default, to attach the child row to the parent and keep those rows together. The documentation has some example HTML and even that row in the documentation is a child row.

There are two examples included in the documentation as well:
* [basic child rows](http://mottie.github.io/tablesorter/docs/example-child-rows.html).
* [child rows with filter widget](http://mottie.github.io/tablesorter/docs/example-child-rows-filtered.html).

If you are referring to nesting tables, then I would recommend using a custom parser to set which part of the nested table data to use for sorting.

**Comment by southmeadows** [comment]
For a simple example suppose the first row was a person info name, address city.  And suppose the person had 1 to x phone numbers.  the child rows would each have a phone number. 

so question is can I use the child-row with multiple rows?

**Comment by Mottie** [comment]
Yes. Did you look at the examples?

**Comment by southmeadows** [comment]
Is there a way to have the column headers be part of the child rows rather than placing the headers at the top?




From: South Meadows <mark@southmeadows.net>
Reply: South Meadows <mark@southmeadows.net>>
Date: May 2, 2015 at 10:02:13 PM
To: Mottie/tablesorter <reply@reply.github.com>>
Subject:  Re: [tablesorter] table inside a table? (#892)  

For a simple example suppose the first row was a person info name, address city.  And suppose the person had 1 to x phone numbers.  the child rows would each have a phone number. 

so question is can I use the child-row with multiple rows?

**Comment by Mottie** [comment]
You have a few choices:

* Add the HTML yourself
* Add some code to duplicate the headers using a custom widget or in the [`initialized` callback function](http://mottie.github.io/tablesorter/docs/#initialized).
* If the child row headers are the same as the main table, use the [stickyHeaders widget](http://mottie.github.io/tablesorter/docs/example-widget-sticky-header.html) or [css3StickyHeaders widget](http://mottie.github.io/tablesorter/docs/example-widget-css-sticky-header.html).

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
