### ISSUE TITLE
Empty Format String in MAC Address Parser

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#895]
I have a bug I unfortunately didn't manage to create a test case for yet but I have currently a tab open where I am paused at a exception. It happens when I refresh the contents of a table by emptying it and filling it up with new data and then triggering an "update" event.

It basically has to do with the function "format" in the following code being called with an empty string as an argument:

```javascript
/*! Parser: MAC address */
ts.addParser({
    id: 'MAC',
    is: function(s) {
        return ts.regex.ipv6Validate.test(s);
    },
    format: function(s) {
        var t = '',
            val = s.replace(/[:.-]/g, '').match(/\w{2}/g);
        $.each(val, function(i, v){
            t += ( '000' + parseInt(v, 16) ).slice(-3);
        });
        return t;
    },
    // uses natural sort hex compare
    type: 'numeric'
});
```
If I make it return early for when the "s" argument is empty it appears to work fine. Tested in current revision on the master branch.

Call stack:
```
jQuery.extend.each (jquery2.js?1430758962:348)
ts.addParser.format (parser-network.…1430758962:119)
buildCache (jquery.tablesor…1430758962:387)
commonUpdate (jquery.tablesor…1430758962:542)
(anonymous function) (jquery.tablesor…1430758962:913)
jQuery.event.dispatch (jquery2.js?1430758962:4435)
jQuery.event.add.elemData.handle (jquery2.js?1430758962:4121)
jQuery.event.trigger (jquery2.js?1430758962:4350)
(anonymous function) (jquery2.js?1430758962:4901)
jQuery.extend.each (jquery2.js?1430758962:374)
jQuery.fn.jQuery.each (jquery2.js?1430758962:139)
jQuery.fn.extend.trigger (jquery2.js?1430758962:4900)
```

**Comment by Mottie** [comment]
Hi @Herst!

Thanks for reporting this issue! It looks like if the `match` returns `null` a javascript error will pop up. I'll have that fixed (in the master branch) here shortly.
