### ISSUE TITLE
Line 577 'undefined' is null or not an object

### ISSUE THREAD

**Issue by hoppities** [Mottie/tablesorter#897]
I am forced to support IE8 with tablesorter, and it's currently not sorting, but the demo works in IE8.

`o.count = s[1];` This is the line. Any thoughts why this could be happening?

    <thead>
	<tr class="warning">
	  <th class="sortable">Name <i class="fa"></i></th>
	  <th class="sortable">NS <i class="fa"></i></th>
	  <th class="sortable">Hosp. <i class="fa"></i></th>
	  <th class="sortable">Loc. <i class="fa"></i></th>
	  <th class="sortable">Service <i class="fa"></i></th>
	  <th class="sortable">Age <i class="fa"></i></th>
	  <th class="sortable">Admitted <i class="fa"></i></th>
	  <th>Injuries</th>
	  <th class="sortable">Surgery <i class="fa"></i></th>
	  <th>Plan</th>
	</tr>
    </thead>

I'm using bootstrap as well. Any help would be greatly appreciated.

**Comment by Mottie** [comment]
Hi @hoppities!

The code mentioned `o.count = s[1]` is part of the original tablesorter. This fork of tablesorter does not have anything similar. Please try updating tablesorter to this version. Here is an [outdated summary](https://github.com/Mottie/tablesorter/wiki/Summary) of differences between the versions; but updating should not require any significant changes.

**Comment by hoppities** [comment]
Hm...I updated and am still getting an error. Am I initializing correclty?

    $( document ).ready(function() {
    $("#trauma-table").tablesorter({
	        		sortList: [[6,1], [10,0]],
	        		cancelSelection: true,
	        		headers: {
	        			7: {
	        				sorter: false
	        			},
	        			9: {
	        				sorter: false
	        			},
	        			11: {
	        				sorter: false
	        			}
	        		}
	        });
    });

**Comment by hoppities** [comment]
The bug has moved to line 629.

`header = c.$headerIndexed[col][0];`

Error: Uncaught TypeError: Cannot read property '0' of undefined

**Comment by hoppities** [comment]
@Mottie , in debug mode, IE8 is throwing

`extractor:undefined; parser:text; string:max; empty:bottom`
That seems wrong to me.

**Comment by hoppities** [comment]
It works in IE8 if I have a pre populated table, but the PHP built table doesn't work.

**Comment by Mottie** [comment]
That is an odd error. Is the HTML valid? I mean, does it have the same number of columns throughout the table?

What version of jQuery is being used?

If you're using Bootstrap, you can include the "uitheme" widget and a few adjustments to the options to make it work smoothly together. Here is a [demo with a bunch of options](http://jsfiddle.net/njj5b5vc/); and a [demo with the bare minimum settings](http://jsfiddle.net/Mottie/njj5b5vc/24/).

**Comment by hoppities** [comment]
HTML is valid, same number of columns. I'm using Jquery 1.11.2. I don't think it is seeing that anything is in the table.
