### ISSUE TITLE
How refresh tablsorter in a modal

### ISSUE THREAD

**Issue by Patatou** [Mottie/tablesorter#899]
Hi,

First, ty for the incredible work !

My tablesort is in a modal windows populate by Ajax request (to a PHP file which do SQL Resquest).

Well, for refresh my table, i do this :+1:

```js
function rerend_tablesort()
{
  return $.ajax({
    type: "POST",
    url: "./plage-exist.php",

    success: function(data) {
      resort = true;
      $('#plagehorairetab')
      .find('tbody').remove();
      $('#plagehorairetab')
      .find('thead').replaceWith(data);

      $('#plagehorairetab').trigger('updateAll', [resort]);
      $('#plagehorairetab').find('.tablesorter-childRow td').hide();

    },
    error: function(XMLHttpRequest, textStatus, errorThrown) {
      alert("Status: " + textStatus); alert("Error: " + errorThrown);
    }
  });
}
```

This work perfectly but, there's another solution ? More traditionnal ?

Ty

**Comment by Mottie** [comment]
Hi @Patatou!

It all really depends on what is in the data.

If the `tbody` is completely removed/updated, then all that is needed is an "update" , but if the `thead` is modified, then an "updateAll" is needed.

Programmically, modals are very similar to tabs and if the table already exists, then all you would need to do is initialize the table first, then just use "applyWidgets" after the table becomes visible. There are several demos under ["misc"](https://github.com/Mottie/tablesorter/wiki#misc) on the Home wiki page that show the code needed for tabs.

**Comment by Patatou** [comment]
Ok, ok, i'm a jerk...

I did this "tips" because update method doesn't work... but it was because I update befaore ajax done... -_-'

Ty ;)

**Comment by Patatou** [comment]
Data are HTML table with thead, tbody, and the entire tablesorter.

I do this "tips" because  $( $('#plagehorairetab').trigger('updateAll', [resort]);).trigger('update', [resort]); doesn't work....

In fact, only tbody change but plage-exist rewrite the entire of table.

I just try this doe :    
 success: function(data) {
      resort = true;
      $('#plagehorairetab').trigger('updateAll', [resort]);
      $('#plagehorairetab').find('.tablesorter-childRow td').hide();
    },

But it doesn't refresh table in the modal.

**Comment by Mottie** [comment]
If you are adding an entire table, then *initialize* tablesorter.

```js
success: function(data) {
    $('#plagehorairetab')
        .tablesorter()
        .find('.tablesorter-childRow td').hide();
},
```

**Comment by Patatou** [comment]
Ty for answer.

Doesn't work...

When i delete or add a row, with your solution, I need to refresh the page to see the new row...

I don't understand why only the remove and remplace solution work dynamicly... :'(

**Comment by Mottie** [comment]
Why would you need to refresh the page when using ajax?

**Comment by Patatou** [comment]
No, I don't want to refresh the page, only the tab

**Comment by Patatou** [comment]
I've a table in the modal, and user can add or delete row. Then, i rerender the tab in a modal and user can see dynamicly the modification.

**Comment by Mottie** [comment]
Please share that code.

**Comment by Patatou** [comment]
function remove()
{
	$.ajax({
			type: "POST",
			url: "./script/delete.php",	
	
			success: function() {
				rerend_tablesort()
			},
			error: function(XMLHttpRequest, textStatus, errorThrown) { 
				alert("Status: " + textStatus); alert("Error: " + errorThrown); 
		}
	}); 			
} 

Script delete.php only do SQL request for deleting event in the table.

Plage-exist.php : 
       
    /*SOME SQL STUFF for connection*/

   	$events 		= array();
	$eventArray = array();
	$rows 			= $stmt->fetchAll();
		
	$result = '
	<thead>
	    <tr>
	      <th filter-select>Namz</th>
	      <th>Cal</th>
	      <th>Hd</th>
	      <th>Hf</th>
	      <th>Date D</th>
	      <th>Date F</th>
	      <th>P&eacute;riodicit&eacute;</th>
	      <th>Co</th>
	      <th class="remove sorter-false"></th>
      </tr>
  	</thead>
  	<tfoot>
  	</tfoot>';
	$result .='<tbody>';
	
	foreach ($rows as $row){
		$start_time = split(" ", $row['start_time']);
		$end_time = split(" ", $row['end_time']);
		

		$stmt = $dbh->prepare("SELECT * FROM events_plage 										WHERE parent_id =\"".$row['parent_id']."\"										
ORDER BY event_id, start_time");

		$stmt->execute();
		$child_rows	= $stmt->fetchAll();		

		$result	.= "<tr>";
		$result	.= "<td><a href=\"#\" class=\"toggle\">".$row['title']."</a></td>";	
		$result	.= "<td>".$row['calendar']."</td>";
		$result	.= "<td></td>";
		$result	.= "<td></td>";
		$result	.= "<td></td>";
		$result	.= "<td></td>";
		$result	.= "<td>".$row['Periodicity']."</td>";
		$result	.= '<td style="background-color:'.$row['color'].'"></td>';  
		$result	.= '<td><span class="deletePlage ui-icon ui-icon-circle-close" title="Supprimer">   </span>
     			</td>';
			$result	.= "</tr>";		
	  
   		
		foreach ($child_rows as $child_row){
			$child_start_time = split(" ", $child_row['start_time']);
			$child_end_time = split(" ", $child_row['end_time']);
			
			$child_number 				= $child_row['child'];
			$child_start_time_tmp = $child_start_time[1];	
			$child_end_time_tmp 	= $child_end_time[1];				
			$date_tmp						 	= $child_start_time[0];
			
			$result	.= "<tr class=\"tablesorter-childRow ".$childRow_class."\">";
			$result	.= "<td></td>";
			$result	.= "<td>".$child_row['calendar']."</td>";
			$result	.= "<td>".$child_start_time[1]."</td>";
			$result	.= "<td>".$child_end_time[1]."</td>";
			$result	.= "<td>".date("d/m/Y", strtotime($child_start_time[0]))."</td>";
			$result	.= "<td>".date("d/m/Y", strtotime($child_row['end_date']))."</td>";
			$result	.= "<td></td>";
			$result	.= "<td></td>"; 
			$result	.= '<td></span>
			</td>';
			$result	.= "</tr>";
		}	
	}
	$result.='</tbody>';
	print_r($result); 
?>
  
I erase some SQL line volontary.

**Comment by Mottie** [comment]
Does the content in the `thead` change? If not, then I think it would make things so much easier to just replace the `tbody` content and trigger an "update".

If that isn't the case, then instead of replacing the content of the `table`, replace the entire table and initialize tablesorter.

**Comment by Patatou** [comment]
Thead not change, then gonna try immediatly and report.

**Comment by Patatou** [comment]
I do this : 
function rerend_tablesort()
{
			return $.ajax({
			type: "POST",
			url: "./table-update.php",
			     		
			success: function(data) {				
				resort = true;
				/*$('#plagehorairetab')
				  .find('tbody').remove();*/
				$('#plagehorairetab')
				   .find('tbody').replaceWith(data);
				   
				$('#plagehorairetab').trigger('updateAll', [resort]);
				$('#plagehorairetab').find('.tablesorter-childRow td').hide();
				
			},
			error: function(XMLHttpRequest, textStatus, errorThrown) { 
				alert("Status: " + textStatus); alert("Error: " + errorThrown); 
			}
		});
}

table-update.php only send tbody... and this is work ;)

Thanks a lot. <3

**Comment by Mottie** [comment]
That's great to hear! :smile_cat:

**Comment by Patatou** [comment]
*cry*

When close modal and reopen it, table dissapear... :'(

**Comment by Patatou** [comment]
Ok, I'm gonna open a new issue because i find the guilty !!! ... but havn't any idea of the solution...
