### ISSUE TITLE
contenteditable and addClass ('no-edit') and trigger ('updateAll') problems with td still editable

### ISSUE THREAD

**Issue by Stephen-Hazel** [Mottie/tablesorter#900]
Yes, it's me needing some hand holding again...

I see that when I start off with a contenteditable table with a td that has class no-edit there's no div with contenteditable attribute of true, just straight td text end td.

Then I td.removeClass('no-edit') and trigger ('updateAll') and as if by magic, there's the td's div with attribute contenteditable='true' and everything's great.  It looks great, I can edit, perfect.

But when I go back to readonly with addClass ('no-edit'), (and trigger ('updateAll'))  things go bad:
- the div is still there (That's ok by me, still looks fine - hilited readonly)
- BUT the td is still editable (at least in firefox 37.0.2)...  That part ain't really ok...:(
    It's hilited readonly color, but you can click on it and start editing away...

And, as always, thanks for a FAN-freakin-TASTIC table editor thingy

**Comment by Stephen-Hazel** [comment]
oh, also, when I have a td with some <br>s in there that's class no-edit, and removeClass ('no-edit') and trigger ('updateAll'), there's no div added, but the <br> all get an attribute contenteditable='true'...  (and consequently editing is messed up)

rats.

**Comment by Mottie** [comment]
Hi @Stephen-Hazel!

Hmm, so you are wanting to make cell editing dynamic?

I was just looking at the code, and apparently I didn't add code to remove the editable widget, so calling "updateAll" will not remove the contenteditable divs - I'll have to fix that.

I'll also take a look at the `<br>` issue.

Thanks for reporting it!

**Comment by Stephen-Hazel** [comment]
Actually, for the short term I can live without it bein' dynamic like that.  We have a form that has records per team (one inputter per team) and wanted it to be read only when you're looking at all teams and according to permissions when you slim down the form to one team with a select.  I can just use the real permissions in the "view all" select pick, too, though.

It'd be kind of cool eventually tho.  Thanks for bein so responsive and for your great plugin thing.  I think I'm back to good again.

**Comment by Stephen-Hazel** [comment]
For my multiline fields, I need to put my own divs in.  If I don't, the <br>s get an added contenteditable='true' attribute, but I get no "automagical" divs. like I do when it's just straight text without <br>s.  I'll have to test this on IE to make sure line breaks turn into <br>.  I think ya mentioned line breaks showing up for YOU as a div per line break...  Well, I'm almost done at least.

**Comment by Mottie** [comment]
Ok, that last update should fix just the `<br>` issue... I'll look at the dynamic thing later when I get another break ;)

**Comment by Stephen-Hazel** [comment]
cool.  yeah, i won't need it after all.  somebody else someday miiiiight, but ya could wait till they do.

thanks again.

**Comment by Mottie** [comment]
Reopening so I can keep track ;)
