### ISSUE TITLE
Lost Key Inputs in Filter Field When Triggering Update at Same Time

### ISSUE THREAD

**Issue by Herst** [Mottie/tablesorter#903]
1. Go to http://jsfiddle.net/Herst/q7pq7cw5/ /edit: new testcase: https://jsfiddle.net/Herst/pcmsL943/
2. Enter and delete stuff from the filter text box while it is updating (every second in this case).
3. Notice that some of the key inputs are lost or rather the input is apparently every now and then reverting to a state before the update started.

**Comment by Mottie** [comment]
Hi @Herst!

This issue is likely related to #733. I'll have to dig into the code to see where the input is getting updated. It should not update the filter that is actively being interacted with, but it will update filters set to the same column.

**Comment by Herst** [comment]
Maybe, but it happens with unlike what is said there it happens with `filter_liveSearch: false` as well: http://jsfiddle.net/Herst/q7pq7cw5/4/

**Comment by Mottie** [comment]
Thanks for the update, I'll definitely find time this weekend to dig into this issue.

**Comment by Herst** [comment]
I can confirm that it works in my project. Thank you, you rule!
(The summation refresh bug / widget update order bug is the only one remaining issue that causes me headaches.)

**Comment by Mottie** [comment]
Oh, you mean issue #898?

**Comment by Herst** [comment]
Apparently the issue is back, see: https://jsfiddle.net/Herst/pcmsL943/

**Comment by Herst** [comment]
And funny enough an issue with the zebra plugin shows but issue #898 does not.

**Comment by Mottie** [comment]
So, this time it looks like my optimizations to the math widget - detaching and reattaching the table - are the cause of the input losing focus.
