### ISSUE TITLE
jQuery UI Datepicker Range Selector and Scroller widget

### ISSUE THREAD

**Issue by Patatou** [Mottie/tablesorter#904]
Hi,

I've one issue with : 
- jQuery UI Datepicker Range Selector ("Date (two inputs)" column)
- Scroller widget,

When I use this 2 widget in the same time, datepicker don't popup when i click on the filter, and filter don't work at all (same if i put a date manually in the case "to from").

Any idea ?

**Comment by Mottie** [comment]
The scroller widget still needs a lot of work to make it work with other widgets. For now I would tell you not to use the scroller widget unless the filters are external to the table. I'll put this on my to-do list, but I don't know when I'll have time to get to it.

**Comment by Mottie** [comment]
The scroller is only partially compatible with the filter widget. I've centralized all of the scroller widget issues into #1487. Please follow any progress there.
