### ISSUE TITLE
Scroller + Column selector

### ISSUE THREAD

**Issue by kevintc** [Mottie/tablesorter#905]
Hi :)

When I use both of the widgets at the same time, removing a column causes a bug on the table header.

Here is an example :
- All columns are shown
![image](https://cloud.githubusercontent.com/assets/7962247/7587025/4ba4988a-f8b3-11e4-8d32-b8fde306c51b.png)

- Removing "Exon"
![image](https://cloud.githubusercontent.com/assets/7962247/7587038/68410ff0-f8b3-11e4-8be5-2cce0c863bce.png)

If I check the column back, then i get a correct layout again.

I also face another bug when I scroll the page, at some point, the header disappears and reappears weirdly :
![image](https://cloud.githubusercontent.com/assets/7962247/7587121/1ddb62a2-f8b4-11e4-97cc-bbd218da53ac.png)

![image](https://cloud.githubusercontent.com/assets/7962247/7587062/98b82862-f8b3-11e4-9a8e-139e39bb0481.png)

Any idea on how to fix it ?

**Comment by Mottie** [comment]
Hi @kevintc!

I apologize for the inconvience, the scroller widget still needs *a lot of work*... it works great on it's own, but when combined with other widgets, it is being naughty.

There are a bunch of open tickets which need attention:

* #495: Scroller + reorder (this would also include the dragtable plugin)
* #866: Scroller + resizable
* #878: Scroller + contenteditable
* #884: Scroller + pager
* #901: Scroller in a modal window (alignment issues)
* #904: Scroller + filter (when using `filter_formatter`)
* #905: Scroller + columnSelector.... and now this one.

It's taken a lot of work to get the widget where it is now, and it'll take a lot more to make it compatible with all the other widgets. I wish I had the time... I'll try to make some time this weekend.

**Comment by kevintc** [comment]
No problem :) I totally understand that :)
Good luck ^^ I'll wait and find a way around
