### ISSUE TITLE
Scroller full height

### ISSUE THREAD

**Issue by Mottie** [Mottie/tablesorter#907]
Enhancement request: leave `scroller_height` undefined (`null`) to leave table at full height (fixed columns needed) - see [Stackoverflow](http://stackoverflow.com/q/30193729/145346).

**Comment by jasongabel** [comment]
It could be as simple as adding this around line 250 of the scroller widget, which then if you put in anything 0 or less, the scroller widget does not set a max-height to the outer div
`		    // use max-height, so the height resizes dynamically while filtering
if (maxHt > 0) {
$table.wrap('<div class="' + tscss.scrollerTable + '" style="max-height:' + maxHt + 'px;" />');
}
else {
$table.wrap('<div class="' + tscss.scrollerTable + '"  />');
}`

**Comment by Mottie** [comment]
Hi @jasongabel!

Did you test that change? I'll try to look into it this weekend, but it would be awesome if you would send me a PR! :grin:

**Comment by jasongabel** [comment]
Tested in code I am running, not necessarily in jshint or grunt.
Works as expected, meaning that the scroll bar maybe far away, but scroll mouse and arrows allow you to scroll left and right before going all the way to the bottom.
