### ISSUE TITLE
resizable: window trigger resize

### ISSUE THREAD

**Issue by Kepro** [Mottie/tablesorter#912]
I have problem with 

$(window).trigger('resize'); // will update stickyHeaders, just in case

why you do this? you fire resize event and other libraries watchs resize event is fired...
this cause problem in my applications... i have charts on second tab and then always is deformated if i show results in your table, due to that is not visible... 

try to use your own event name? :) thanks...

**Comment by Mottie** [comment]
Hi @Kepro!

Yeah, I'll change it to something sticky header specific.

**Comment by Kepro** [comment]
@Mottie  thanks! 
i have widgets : [ 'uitheme', 'resizable', 'cssStickyHeaders', 'columnSelector', 'filter', 'zebra'],
if graph library throw exception due to resize of not visible chart, then tablesorter crash loading plugins, after resizable, workaround is resizable put on end of plugins list meh..

**Comment by Mottie** [comment]
Ok, you'll find the changes in the master branch :D
