### ISSUE TITLE
Combine filters operator

### ISSUE THREAD

**Issue by eMerzh** [Mottie/tablesorter#918]
Hi, 

I wanted to be able to combine filters together, 
but it seems to be impossible ... right?

i wanted to do things like : 
> <80 or >100

or

> !( 80 - 100)

btw, thanks for this awesome tool :)

**Comment by Mottie** [comment]
Hi @eMerzh!

It is not currently possible to combine the "or" or "not" operator in that manner.

I'll look into it again when I have some free time this weekend.

**Comment by eMerzh** [comment]
sorry , i know you must have a lot to do, but any news on this, 
i need to remove specific rows in the table... so i was thinking about a column with ids, and a serie of "!id1 and !id2 ..." 
do you see any other possibility than that?

**Comment by Mottie** [comment]
I did start working on this feature, the `OR`  operator is integrated in with the wild card multiple (`*`) and  single (`?`) non-space character matcher, using regular expressions. After separating it out, I found that the updated method changes how "filter-match" works. So now I need to find a way to work around this problem. Hopefully it won't take too much more time to fix it.

**Comment by eMerzh** [comment]
awesome! big thanks for this, and for your reactivity!! keep on the awesome work!

**Comment by Mottie** [comment]
I don't think I'll have time to work on the `!( 80 - 100)` request... it is nesting filter types and if you want to include parentheses, I would also have to prioritize operations, which would require even more coding.

**Comment by Mottie** [comment]
Whew, ok, try out the updated filter widget available in the master branch!
