### ISSUE TITLE
ts.css issue in jquery.tablesorter.widets.js

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#919]
I found an error around line 2216, where ts.css was not defined before an attempt to extend.  Resolved by inserting:

if ( ts['css'] == undefined ) {
  ts['css'] = {};
}

before:

$.extend(ts.css ...

**Comment by Mottie** [comment]
Hi @SPlatten!

Hmm, is the widgets file being loaded before the tablesorter core? I couldn't imagine that being a problem otherwise.

**Comment by SPlatten** [comment]
No, I installed is as per the directions on the web-site.

**Comment by TheSin-** [comment]
please provide a jsfiddle of the issue so we can reproduce it and fix it since we can not reproduce it.

**Comment by SPlatten** [comment]
Thank you I will do this went I get to my system tomorrow.

I'm starting to think I missed something.

**Comment by Mottie** [comment]
Can you please check what version of tablesorter is being used? The widgets from this branch *do not* work with the original tablesorter (v2.0.5) from tablesorter.com.

**Comment by SPlatten** [comment]
The versions are:

jquery.tablesorter.js, version 2.0.5b
jquery.tablesorter.widgets.js, version 2.22.1
jquery-2.02.min.js, version 2.0.2
jquery-ui, version 1.11.3

I've put a try/catch wrapper around the initialisation code for the tablesorter, I get an exception raised:

file: jquery.tablesorter.widget.js
line: 308
column: 3
message: c is undefined

**Comment by SPlatten** [comment]
I've traced the call to jquery.tablesorter.js line 511, where it calls this format function with just 1 parameter.

Obviously I've missed something, but what is it?

**Comment by SPlatten** [comment]
Having searched around I have now found later versions of the scripts:

jquery.tablesorter.js, v2.22.1
jquery.tablesorter.widgets.js, v2.22.1

This has solved the problem I was having, the original scripts I was using were downloaded from:

http://tablesorter.com/

**Comment by Mottie** [comment]
Ok, I'm glad this has been resolved. I maintained compatibility with the original tablesorter for quite some time, but I had to break away from it around v2.16.0 to make widgets more robust.

I plan on renaming this fork to [Abelt](https://github.com/tablesort/Abelt), once I have more free time to avoid further confusion.
