### ISSUE TITLE
Sort  tbodys in a table with several separately

### ISSUE THREAD

**Issue by flathat** [Mottie/tablesorter#921]
I have a table of data for departments, each department with its own `<thead>` and `<tbody>`. There are several columns in each pair that can be sorted meaningfully and it makes sense to sort some departments differently than others.  The single table maintains uniform column widths for all of the pairs (sub-tables).

 I would like the sorting to apply only to the `<tbody>` under the given `<thead>` when one of its `<th>s` is clicked. Currently all `<tbody>s` are sorted, each in its own sequence, as desired, when the `<th>` in the top `<thead>` is clicked.

The sorting is controlled by the up/down arrows in the `<th>`'s of the first `<thead>`.  The arrows appear in the 2nd+ `<thead>s` but their effect is only to restore the whole table to its original sequence.

It would be no problem to give HTML `id='s` to each element to help identify which `<tbody>` to sort.

`tablesorter v2.14.5-0` Thank you for supporting it.

**Comment by Mottie** [comment]
Hi @flathat!

My understanding of the [W3C specifications](http://www.w3.org/TR/html-markup/table.html) on `<thead>` elements is that only one is allowed per table. From the description above, is seems that all departments are listed in one table and each has its own `<thead>` and `<tbody>`; maybe each department should have a separate table?

If I am misunderstanding, would you please provide an example. Make sure to remove any sensitive information and include only two (or so) departments, with a few rows. Also please include the javascript used to initialize tablesorter.

**Comment by flathat** [comment]
Your understanding is correct, and no disagreement about the spec.  The way I'm using the multiple tables is a convenience for getting identical column widths for data that should have a uniform appearance; past attempts to do this with column `width=` in separate tables have not been successful.  I hoped what I described was how `tablesorter` would work. (I'm upgrading to 2.14 from 2.05 to get over an error that was reported when clicking a 2nd+ level heading.  The error is gone and the 2nd+ `<tbody>s` are sorted now which they weren't before.)  So I guess what I'm asking for is non-standard, but `tablesorter` is already half way there by sorting each `<tbody>` separately, and it would be convenient if it did work this way. I used the extra `<thead>s` because I thought `tablesorter` needed them (it does for the re-sort arrows but not for sorting the 2nd+ `<tbody>s` separately), but just using rows of `<th>s`, possibly with `id=` or `class=`, would be fine and perhaps less in conflict with the spec.

**Comment by Mottie** [comment]
Ok, I think the easiest solution would be to separate the departments into separate tables, then add a class name to each header & set a width for that column - [here is an example](http://jsfiddle.net/abkNM/5895/)

HTML (class name added to each `<th>`)

```html
<thead>
    <tr>
        <th class="anumeric">AlphaNumeric</th>
        <th class="numeric">Numeric</th>
        <th class="animals">Animals</th>
        <th class="url">Sites</th>
    </tr>
</thead>
```

CSS

```css
.anumeric { width: 30%; }
.numeric { width: 10%; }
.animals { width: 20%; }
.url { width: 40%; }
```

When initializing tablesorter, it would be optional to include the `widthFixed` option. 

```js
$(function () {
    $('table').tablesorter({
        theme: 'blue',
        widthFixed: true // optional
    });
});
```

What this option does is adds a `<col>` for each column with a set percentage width, so if you happen to skip a few columns widths with the HTML/CSS, this will lock in the initial proportional column width and keep all the tables in alignment (unless they start out with different column widths).

**Comment by flathat** [comment]
OK, thank you. My use of this is embedded in a general reporting tool. It's going take a while to change approach.
