### ISSUE TITLE
tablesorter with fixed columns and pager plugin

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#922]
Are they're any known issues with the fixed columns and the pager plugin?

I've added the pager plugin to the table I'm working on and it seems doesn't seem to work.  Is there a working example of this already?

The widgets I'm using are: 'uitheme', 'zebra', 'pager', 'filter', 'scroller'

**Comment by Mottie** [comment]
Please search older issues if you have questions; issue #884 was just closed, so there are no known issues with the pager ([demo](http://jsfiddle.net/1a5yu8yq/21/)), if you are using the scroller widget available *in the master branch*.

**I would appreciate it if you would only open issues here on GitHub for enhancement requests and issues.**

For questions, please use the `#tablesorter` IRC channel on freenode.net or [Stackoverflow](http://stackoverflow.com/questions/tagged/tablesorter). I may not answer questions at 5:30 in the morning (like I am right now), but I always try to respond.

**Comment by SPlatten** [comment]
Thank you, will do.

On 1 June 2015 at 11:42, Rob G <notifications@github.com> wrote:

> Please search older issues if you have questions; issue #884
> <https://github.com/Mottie/tablesorter/issues/884> was just closed, so
> there are no known issues with the pager (demo
> <http://jsfiddle.net/1a5yu8yq/21/>), if you are using the scroller widget
> available *in the master branch*.
>
> *I would appreciate it if you would only open issues here on GitHub for
> enhancement requests and issues.*
>
> For questions, please use the #tablesorter IRC channel on freenode.net or
> Stackoverflow <http://stackoverflow.com/questions/tagged/tablesorter>. I
> may not answer questions at 5:30 in the morning (like I am right now), but
> I always try to respond.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Mottie/tablesorter/issues/922#issuecomment-107395420>.
>



-- 
 <http://about.me/SPlatten>
[image: Simon Platten on about.me]

Simon Platten
about.me/SPlatten
    <http://about.me/SPlatten>
