### ISSUE TITLE
Unable to change column width in DataTables

### ISSUE THREAD

**Issue by Cr3z** [Mottie/tablesorter#925]
Hi! I actually use Datatables plugin on my website with inputs-research area in each column header.
It works well but the column width is fixed at 169px (probably due to the search inputs) and I don't know how to resize it to fit to my data width.

Can you help me please?

Here's my .js:
 
```
$(document).ready(function() {

    // Setup - add a text input to each header cell
    $('#maTable thead .search').each( function () {
        var title = $('#maTable thead .header_title').eq( $(this).index() ).text();
        $(this).html( '<input type="text" placeholder="Search '+title+'"/>' );
    } );
  
    // DataTable
    var table = $('#maTable').DataTable();
     
    // Apply the search
    table.columns().every( function () {
        var that = this;
        $( 'input', this.header() ).on( 'keyup change', function () {
            that
                .search( this.value )
                .draw();
        } );
    } );
});
```

**Comment by Cr3z** [comment]
Here's a view of the result:
![capture](https://cloud.githubusercontent.com/assets/12269381/7930843/3484d52a-090c-11e5-878a-c3fe616ecf09.PNG)

**Comment by Francks11** [comment]
Hi @Cr3z,

I think, it is not the good project to report your issue.

Here it is tablesorter.

:-)

**Comment by Cr3z** [comment]
Yes sorry i'm new on Git and I didn't found where to post my issue :/

**Comment by Francks11** [comment]
You can post your issue here https://github.com/DataTables/DataTables

**Comment by Cr3z** [comment]
Ok thanks ^^'
