### ISSUE TITLE
Scroller Widget - Options scroller_jumpToHeader or scroller_upAfterSort don't work when fixed columns are used

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#926]
Options scroller_jumpToHeader or scroller_upAfterSort don't work when fixed columns are used.

You can see a demo here : http://jsfiddle.net/856bzzeL/465/

**Comment by Francks11** [comment]
A solution for this? I update table data with javascript and when I refresh header, the vertical scrollbar go to top and it's a bit annoying...

Thanks

**Comment by Francks11** [comment]
Good job @Mottie, but on window resize, the scrollbar position is not restore...

**Comment by Mottie** [comment]
Please elaborate... what do you mean "not restore"? What browser?

**Comment by Francks11** [comment]
Sorry...

In my demo : http://jsfiddle.net/856bzzeL/465/

Scroll to bottom :

![1](https://cloud.githubusercontent.com/assets/3995851/8281837/1e44e85a-18ec-11e5-9097-0ccbc2695111.png)

Resize the window. You can see that the scrollbar go to top.

![2](https://cloud.githubusercontent.com/assets/3995851/8281928/d74ec5a0-18ec-11e5-9161-487124324246.png)

This issue appears with all browser.

I think that you restore not the scroller position when the browser is resizing in resizing method.

Thanks

**Comment by Mottie** [comment]
Ok, try it now! :P

**Comment by Francks11** [comment]
Thanks @Mottie, its works :D
