### ISSUE TITLE
Scroller Widget - Line doesn't line up with Internet Explorer 9, 10, 11

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#928]
When we use colspan in table body like this :

```
<tbody class="tablesorter-infoOnly">
    <tr>
        <td colspan="2">COLSPAN</td>
        <!-- add extra hidden td because the fixed column set to 2
             will hide 2 cells; this hidden cell is a placeholder -->
        <td style="display: none"></td>
        <!-- this cell will show up on the right -->
        <td colspan="8">&nbsp;</td>
    </tr>
</tbody>
```

Line doesn't line up with Internet Explorer but works good with other browser.

You can see a demo here : http://jsfiddle.net/1a5yu8yq/42/

![capture](https://cloud.githubusercontent.com/assets/3995851/7947521/f436ab8e-097d-11e5-863c-6ccdbbbf9e8e.png)

To better see, go on the bottom of table.

**Comment by Mottie** [comment]
This issue also occurs without info-only tbodies and colspans

**Comment by Francks11** [comment]
Yes, indeed, I just saw. Why? A idea?

**Comment by Mottie** [comment]
If I knew that, it would be fixed by now.

**Comment by Herst** [comment]
Ugly hack idea: Do "overflow: scroll", i.e. always display a scroll bar on IE?

**Comment by Mottie** [comment]
@Herst: It is possible to add a `direction: rtl` on the fixed column and have the scrollbar appear on the left, then you'd see two outer scrollbars. That still definitely sounds ugly :wink: 

I haven't touched the scroller widget in a week, or so - mostly to get away from it and finish up other work - I'll look at it again this weekend.

**Comment by Mottie** [comment]
I wanted to add a note here, the rows line up better now while scrolling due to throttling of the scroll event. There are times when the two sides don't line up - for example, the fixed column is scrolled to the bottom using the mouse wheel and the scrolling columns ends up about 5px from the bottom. There is no easy method to fix this since no scroll event is fired.
