### ISSUE TITLE
Scroller Widget - Colspan in header work only if is not the first row which contains colspan.

### ISSUE THREAD

**Issue by Francks11** [Mottie/tablesorter#929]
TheSin, last ticket I speak of colspan :-p.

Colspan in header work only if is not the first row which contains colspan.

Demo here : http://jsfiddle.net/1a5yu8yq/43/

![capture](https://cloud.githubusercontent.com/assets/3995851/7947814/c6a5b848-097f-11e5-866e-897e42a9e962.png)

If I set colspan in first row, it doesn't work.

Demo here : http://jsfiddle.net/1a5yu8yq/44/

![capture2](https://cloud.githubusercontent.com/assets/3995851/7947851/07f581c0-0980-11e5-867f-58206c6c2c58.png)

Thanks

**Comment by Mottie** [comment]
Fixed columns in the scroller + colspans do not work.

It would be too work to make colspans work in every situation. So, for now, *Don't use `colspan`s when using the scroller widget with fixed columns.

If you want to tackle the coding, you are more than welcome, but for now this will be unsupported.

**Comment by Francks11** [comment]
Okay, I will take a look when I have time :-). The problem is always time :-p.

For now, I have just reported this bug, this lack :-).

**Comment by TheSin-** [comment]
oh it's more then time it has to work for everything not just your use of it.  Since col width and count is based on the first row it'll be very hard to do anything else.

I know you are thinking use first row of tbody, but that will break on blank tables or if filter results are none, etc etc etc.  Not really something that can be coded around, easier to not use it.

**Comment by Mottie** [comment]
Anything is possible... I just don't want, nor do I have time, to add maybe a hundred lines of code just to support colspans in fixed columns.

**Comment by Francks11** [comment]
I will take a look when I have time, to see if it is possible to do this without too much line and what are the possible solutions.
