### ISSUE TITLE
Headers and Data rows not lining up, bottom header row missing

### ISSUE THREAD

**Issue by SPlatten** [Mottie/tablesorter#931]
As discussed before this jsfiddle shows the problem I'm experiencing.

http://jsfiddle.net/SimonPlatten/qt1xx7s6/3/

Not all the data rows are shown in this example and they do not line up with the headers, bottom header row is missing.

This is a cut and paste from firebug, so it may not be entirely accurate, but it does show a lot of the issues.

Versions:
jquery.tablesorter.combined.js, v2.22.1, 2015-05-31
jquery.tablesorter.pager.js, v2.22.0, 2015-05-17
widget-scroller.js, v2.22.0, 2015-05-17
Firefox, v38.0.1
Firebug v2.0.10

Comparing the above output with another table that does render correctly I've noticed that there is no 'tablesorter-scroller-footer' div in the document.

**Comment by SPlatten** [comment]
I fixed the bottom row header now showing, that was my fault, I was rending the table from a data stream received from a socket.  I was creating the thead content but not the tfoot.  

However the issue with the data row columns not lining up with the headers is still an issue, the fixed columns line up perfectly.

**Comment by SPlatten** [comment]
Have now fixed the issue with the data rows and column widths being different, in the data table I had a style='width:90%' , removing this resolved the issue.  Almost there now, just need to figure out why horizontal scroll bar bar doesn't appear when brower is resized.

**Comment by SPlatten** [comment]
There are two div wrappers around the tables, both of these get modified with the styles:

element.style {
  display: block;
  height: 455px;
  left: 8px;
  position: absolute;
  top: 84px;
  width: 1503px;
}

I'm not sure why this is done as it doesn't seem to do anything except move the table down abit...and removing them from the DOM doesn't nothing except shift the table up a bit.

**Comment by SPlatten** [comment]
I have two examples, one that is created by hand which works perfectly, everything now works with no issues.

The other, which is created dynamically using the data from the feed....this has issues, the one that works has an additional div wrapper with the class 'tablesorter-scroller tablesorter-scroller-has-fixed-columns'

The one that doesn't work doesn't have this wrapper.

**Comment by Mottie** [comment]
Why is tablesorter being initialized on an already rendered HTML?

I mean, the HTML was copied from a table already set up using the filter & scroller widget, and then the widgets are applied to it a second time... if I [remove the initialization code](http://jsfiddle.net/qt1xx7s6/4/), the table looks "better", but you can't interact with it..

**Comment by SPlatten** [comment]
I think that was just the jsfiddle cut and paste.

**Comment by SPlatten** [comment]
Glad to say all issues now resolved and table working correctly.  Hold my hand up, assign one one issue most of the problems were my own.
