### ISSUE TITLE
Grouping columns for show/hide

### ISSUE THREAD

**Issue by Guppy49** [Mottie/tablesorter#939]
The column selector widget works fine, but it is necessary to select/deselect column by column. If I could group columns in the manner of Excel, it would make switching between views much faster.

**Comment by Mottie** [comment]
Hi @Guppy49!

You could create a custom popup (leave the [`columnSelector_container` option](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-container) as `null`) with your own groups and use the [`refreshColumnSelector` method](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#methods) to hide multiple columns:

```js
$('table').trigger('refreshColumnSelector', [ [2,3,4] ]);
```

This method will only hide the columns in the parameter, already hidden columns will become visible, so you'll need to add/remove columns groups from that array.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
