### ISSUE TITLE
Header fails to allow for scroller width after calling the 'update' method

### ISSUE THREAD

**Issue by gws0000** [Mottie/tablesorter#940]
I'm sorry if I've missed something simple in the documentation but this has been troubling me for a while now, it's the last issue left for me to solve before a release.

I have a table which uses the 'filter' and 'scroller' plugins.  The table data is changed dynamically.  If the user removes rows until the scroller becomes deactivated and the 'update' method is called on the table the header fails to leave space for the scroller.  Adding rows back into the table does not correct the problem.

In the below fiddle, click "Remove row" until the scroller is no longer active, then click "Update".

http://jsfiddle.net/gws000/7trdwo9e/

**Comment by Mottie** [comment]
Hi @gws0000!

Try the scroller widget updates available in the master branch. You can use this url to replace the scroller widget in the resource section of jsFiddle:

https://rawgit.com/Mottie/tablesorter/master/js/widgets/widget-scroller.js

I don't see a "Remove row" button in that demo.

**Comment by gws0000** [comment]
Sorry, I mucked up the jsfiddle version.  Using the master version looks better.
