### ISSUE TITLE
default listing 

### ISSUE THREAD

**Issue by nicksergio** [Mottie/tablesorter#942]
I am trying to list my data in tablesorter using the last published custom Posts in wordpress in descending order starting with the latest. Tablesorter seems to have a Default which is in alphabetical order. How do i get it to lists with this custom order. Thank you

**Comment by Mottie** [comment]
Hi @nicksergio!

You can sort the listings by posted date in descending order. If you provide an example of the HTML and javascript, I could better help determine if a custom parser is needed.

**Comment by nicksergio** [comment]
Thanks for the Response,

This a link to the table Sorter initialization in js
http://pastie.org/10244889#22

Html Markup for table Sorter can be referenced on the line 259 on here
http://pastie.org/10245115#22

This is a link to html page:
http://test.unternehmensverkauf.de/unternehmensboerse/

2015-06-17 14:09 GMT+02:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
Hmm, I think you might need to add another column for the posted date, make it hidden if you want, then set the `sortList` to apply a descending sort to that column.

**Comment by nicksergio** [comment]
Thanks Rob for the Response. Would appreciate a code snippet of how that
will look like.

2015-06-17 15:50 GMT+02:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
[Here is an example](http://jsfiddle.net/Mottie/abkNM/6129/). You can hide the date column by un-commenting out the css definition.

**Comment by nicksergio** [comment]
Thanks very much will try with the dynamic data i am getting from wordpress
and get back to you. appreciate it.

2015-06-17 16:40 GMT+02:00 Rob G <notifications@github.com>:

**Comment by nicksergio** [comment]
Hello Rob,

I have implemented the date sort based on your example. Also used get date
to pull published Dates dynamically. but now i have another concern. The
first columns dont seem to hide after i did insert a column for publised
which is rerefeenced to the hidden 'date' property exactly as you did. What
could be wrong? How do i get it hidden.

Here is the html page :
http://test.unternehmensverkauf.de/unternehmensboerse/

http://pastebin.com/R5MGzL0s ... The get date code can be referenced on
line 579 of this snippet Thanks in advance

2015-06-17 16:40 GMT+02:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
I'm not that good with php, but since the column will be hidden, it would be better to use [`strtotime`](http://php.net/manual/en/function.strtotime.php) to add the time in seconds since the epoch date; this makes it so you don't need to parse or worry about the date format.

```php
 <td class="date"> <?php echo strtotime( get_the_date( ) ); ?> </td>
```

**Comment by nicksergio** [comment]
Thanks very much. Got it to work..

2015-06-25 13:57 GMT+02:00 Rob G <notifications@github.com>:

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.

**Comment by nicksergio** [comment]
Sure its been resolved . thanks loads appreciate it.

2015-06-30 17:14 GMT+02:00 Rob G <notifications@github.com>:
