### ISSUE TITLE
Group by entire text value

### ISSUE THREAD

**Issue by afmab** [Mottie/tablesorter#943]
Hi,

Looking at the header class names for grouping I can't see that there is any way to group by the column's entire text value. You can group by nth word, but not by all words.

Please can you let me know if there's a way to achieve this?

Thanks.

**Comment by Mottie** [comment]
Hi @afmab!

You can use the `"group-separator"` class on that column. It includes all text from the start to the first separator (use `"group-separator-n"` for the n-th separated block of text). The default separator is set by the [`group_separator` option](http://mottie.github.io/tablesorter/docs/example-widget-grouping.html#group_separator).

Sort the inputs column in [this demo](http://jsfiddle.net/Mottie/4ac5kr3o/1/) to see that it works.

**Comment by afmab** [comment]
Ah, brilliant - thanks, that's sorted it.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
