### ISSUE TITLE
Output table in table

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#944]
Hello,
I just try your fantastic plugin and I'm really happy to use it ! Thanks for your great job.

I encounter a strange behaviour with output widget : I have a table with some child rows. Inside these child rows I have another table. I can now correctly output my parent table without children (issue #923) but when I try to export my second table, in child row, I have to files which are downloaded which corresponding to my parent table and my child. 

So my questoin is how can I export, maybe set correctly another "instance" of tablesorter in a parent and a child table inside this parent.

Thank you for your help !

**Comment by ciadch** [comment]
Maybe an information : I try to trigger table with id : like that (simplified)

$('#parent-table').tablesorter()
$('#child-table').tablesorter()

$('#parent-table').trigger('outputTable');
$('#child-table').trigger('outputTable'); --> when I call that, the outpuTable exports the parent-table too

**Comment by Mottie** [comment]
Hi @ciadch!

Hmm, that sounds like a bug... I need to stop the event propagation of 'outputTable'. I'll have a fix available in the master branch shortly.

**Comment by ciadch** [comment]
Thanks for promptness !

Sorry but same behaviour despite your update...

**Comment by ciadch** [comment]
Sorry, I spoke too soon. Clear cash problem !

Thanks a lot, everything work perfectly now !!!

**Comment by Mottie** [comment]
Awesome! :smile_cat:
