### ISSUE TITLE
Why tablesorter is not sticky when using with JSF datatable?

### ISSUE THREAD

**Issue by tonyxs** [Mottie/tablesorter#945]
I am a kind of new to jQuery tablesorter. I am using it with JSF datatable. It seems working, except it is not sticky when scrolling. Why?

Thanks in advance.

```html
<div id="tableview_containerdiv" role="content" class="ui-content df-tablescroll" 
        style="overflow-y: auto; position:absolute; top: 50px; bottom: 40px;">
        <h:dataTable 
         class="table-stripe ui-responsive df-table" 
          id="tableview" value="#{sfsMB.model}" var="item"  
                        columnClasses="column1Data
                                      ,column2Data
                                      ,column2Data
                                      ,column2Data
                                      ,column2Data
                                      ,column2Data
                                      ,column7Data
                                      ,column7Data
                                      ,column7Data
                                      ,column7Data
                                      ,column7Data
                                      ,column12Data
                                      ,column12Data">
            <h:column headerClass="column1">                    
                <f:facet name="header">#</f:facet>   
                <h:outputText value="#{item.fileItemNumber}"/>                    
            </h:column>
            <h:column headerClass="column2">

            </h:column>
            <h:column headerClass="column3">
                <f:facet name="header">Author</f:facet>
                <h:outputText value="#{item.author}" />   
            </h:column>
            <h:column headerClass="column4">
                <f:facet name="header">Floor Manager</f:facet>
                <h:outputText value="#{item.floorManager}" />    
            </h:column>
        </h:dataTable>     
</div>
```

```js
$(document).ready(function () {
 $("#tableview").tablesorter({
    widgets: ['stickyHeaders'],
    widgetOptions: {
        stickyHeaders_attachTo: $('.df-tablescroll'),
        stickyHeaders_yScroll: $(window)
    }
 });
});
```

**Comment by Mottie** [comment]
Hi @tonyxs!

Since the div wrapping the table has a fixed position, the `stickyHeaders_yScroll` option should monitor the scroll position of the wrapper (default behavior) instead of the window. Try this instead ([demo](http://jsfiddle.net/Mottie/yfwwzvL8/228/)):

```js
$(function () {
  $("#tableview").tablesorter({
    widgets: ['stickyHeaders'],
    widgetOptions: {
      stickyHeaders_attachTo: $('.df-tablescroll')
    }
  });
});
```

**Comment by tonyxs** [comment]
Hi Mottie,

Thanks for a quick help! 

But it is still not working after taking 'stickyHeaders_yScroll' off. It has another parent div outside of the div in my code which I didn't put it in my question (trying to make the case simple). Is that going to affect the sticky tablesorter status? I saw your demo which is working fine. thanks.

**Comment by Mottie** [comment]
It shouldn't matter as long as the wrapping div has a `position: absolute` definition.

**Comment by tonyxs** [comment]
Hi Mottie,

Why it is still not sticky? I am frustrated of it..... I have take out all unnecessary code (including .css files and other xhtml files) and put them in a single file for you to look. Can you take a look to tell me what's wrong there? Thanks.


<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:f="http://java.sun.com/jsf/core">
    <h:head>
        
        <link rel="stylesheet" href="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.css"/>
        <script src="http://code.jquery.com/jquery-2.1.3.min.js"/>
        <script src="http://code.jquery.com/mobile/1.4.5/jquery.mobile-1.4.5.min.js"/> 
        <script src="resources/js/common.js"/>
        <script src="resources/js/tablesorter.min.js"/>
        <link rel="stylesheet" href="resources/css/tablesorter.css"/>
    </h:head>
    <h:body style="overflow:hidden;">
    <div data-role="page"  id="tableViewPage" style="overflow:hidden; position:absolute;">
        <div id="tableview_containerdiv" role="content" class="ui-content df-tablescroll" style="overflow-y: auto; position:absolute; top: 50px; bottom: 40px;">
            <h:dataTable class="table-stripe ui-responsive df-table" id="tableview"  value="#{sfsMB.model}" var="item" columnClasses="column1Data,column2Data,column2Data,column2Data,column2Data,column2Data,column7Data,column7Data,column7Data,column7Data,column7Data,column12Data,column12Data">
                <h:column headerClass="column1">    				
                    <f:facet name="header">#</f:facet>   
                    <h:outputText value="#{item.fileItemNumber}"/>                    
                </h:column>
                <h:column headerClass="column2">

                    <f:facet name="header">Item</f:facet>
                    <h:form prependId="false">
                        <h:commandLink  onclick="showTableViewDocs()"> 
                            <f:setPropertyActionListener target="#{sfsMB.itemDocToDisplay}" value="#{null}"/>
                            <f:setPropertyActionListener target="#{sfsMB.itemBrowseMode}" value='true'/>
                            <h:outputText value="#{item.billTypeNumber}"/>

                        </h:commandLink>
                    </h:form>
                </h:column>
                <h:column headerClass="column3">
                    <f:facet name="header">Author</f:facet>
                    <h:outputText value="#{item.author}" />   
                </h:column>
                <h:column headerClass="column4">
                    <f:facet name="header">Floor Manager</f:facet>
                    <h:outputText value="#{item.floorManager}" />    
                </h:column>
                <h:column headerClass="column5">
                    <f:facet name="header">Topic</f:facet>
                    <h:outputText value="#{item.topic}" />    
                </h:column>                
                <h:column headerClass="column6">
                    <f:facet name="header">Location</f:facet>
                    <h:outputText value="#{item.location}" />     
                </h:column>
                <h:column headerClass="column7">
                    <f:facet name="header">Vote</f:facet>
                    <h:outputText value="#{item.voteRequired}" />     
                </h:column>                
                <h:column headerClass="column8">
                    <f:facet name="header">OC</f:facet>
                    <h:outputText value="#{item.onCall}" />     
                </h:column>
                <h:column headerClass="column9">
                    <f:facet name="header">P</f:facet>
                    <h:outputText value="#{item.pass}" />         
                </h:column>                
                <h:column headerClass="column10">
                    <f:facet name="header">F</f:facet>
                    <h:outputText value="#{item.fail}" />         
                </h:column>                
                <h:column headerClass="column11">
                    <f:facet name="header">Staff&nbsp;Notes</f:facet>
                    <h:outputText value="#{item.staffNotesIndicator}" />         
                </h:column>     
                <h:column headerClass="column12">
                    <f:facet name="header">Amend</f:facet>
                    <h:outputText value="#{item.amendIndicator}" />         
                </h:column> 
                <h:column headerClass="column13">
                    <f:facet name="header">All</f:facet>
                    <h:outputText value="#{item.allIndicator}" />         
                </h:column>                 
            </h:dataTable>
            <h:panelGroup rendered="#{empty sfsMB.currentDailyFile.guiDFItemsList}">
                <p>No daily file items available!</p>
            </h:panelGroup>  
            <a href="#" id="btnTableGoToCurrent" class="ui-btn ui-btn-b tableGoToCurrent" data-mini="true">Current</a>
            <h:form id="setItemBrowsingForm" style="display: none">
                <p style="display: none">
                    <h:commandLink id="setItemBrowsingLink">

                    </h:commandLink>
                </p>
            </h:form>   
        </div>       
    </div>         
    </h:body>
</html>


    $("#tableview").tablesorter({
        widgets: ['stickyHeaders'],
        widgetOptions: {
            stickyHeaders_attachTo: $('.df-tablescroll')
          }
    });

**Comment by Mottie** [comment]
Does tablesorter even work? Since jQuery Mobile is involved, you'll need to wrap the  javascript code like this instead of using the document ready function:

```js
$(document).on('pageinit', function() {
    $("#tableview").tablesorter({
        widgets: ['stickyHeaders'],
        widgetOptions: {
            stickyHeaders_attachTo: $('.df-tablescroll')
        }
    });
});
```

**Comment by tonyxs** [comment]
Yeah, the tablesorter seems working with jQuery Mobile. I think I know the reason, cause I missed <script src="resources/js/tablesorter.widgets.min.js"/> 

I'll keep in mind for your recommendation for jQuery Mobile with tablesorter.

Thanks.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue this discussion.
