### ISSUE TITLE
editable_enterToAccept  bug

### ISSUE THREAD

**Issue by Patatou** [Mottie/tablesorter#947]
Hi there,

In this demo, on chrome, editable_enterToAccept option bug :
https://mottie.github.io/tablesorter/docs/example-widget-editable.html

Any solution for workable this option ?

Ty

**Comment by Patatou** [comment]
Edit : for information, scroller widget + editable widget make some strange bug on display...

**Comment by Mottie** [comment]
Hi @Patatou!

It appears to work for me.

Go to that demo page and open the development tools (press F12), then enter the following into the console:

```js
$('table').eq(2).on('editComplete', 'td', function(){ console.log( $(this).text() ); });
```

Now edit the content of any cell, and press <kbd>Enter</kbd>, you'll see the changed content in the console after pressing return.

In that demo, the `editable_autoResort` is set to `false`, so the table won't auto-resort after editing.

You can use [this jsFiddle](http://jsfiddle.net/xxmha2Ly/) to try the different options.

**Comment by Patatou** [comment]
Ok you're right.

I thinked it was a bug because cursor stay in the cell after ENTER pressed, and cell still active.

Ty, u're faster than speedy gonzales ;)

**Comment by Mottie** [comment]
I feel more like ["Slow Poke Rodriguez"](https://www.youtube.com/watch?v=wYi_hq2p1Ac).

**Comment by Patatou** [comment]
Complementary question : Is it normal that Content Editable widget doesn't work in modal windows ?

**Comment by Patatou** [comment]
Gonna make a jsfiddle... brb

**Comment by Patatou** [comment]
http://jsfiddle.net/njt1nth5/12/

If you disable scroller option, modal and Content edit work perfectly.

**Comment by Mottie** [comment]
The editable widget does not yet work with the scroller widget... please watch #878 for updates.

**Comment by Patatou** [comment]
Ok.

Ty again.

**Comment by Patatou** [comment]
But look : http://jsfiddle.net/g7jcfjoo/

If i desactive class="modal" it work... 

Don't really understand why doesn't work in modal.

**Comment by Mottie** [comment]
Can you make the modal work in that demo... some modal scripts clone the contents into a new popup, which won't work with tablesorter; in this case you need to initialize tablesorter *after* the modal window is visible.... So really it depends on the modal plugin.

**Comment by Patatou** [comment]
Modal work when i disable scroller : http://jsfiddle.net/6xfxgvsq/

But scroller + content edit work if i disable modal : http://jsfiddle.net/g7jcfjoo/

Strange...

**Comment by Patatou** [comment]
Nevermind, I found an alternative solution :)

Ty ;)

**Comment by Herst** [comment]
Mind to share it with us?

**Comment by Patatou** [comment]
Well, since today my "hotfix" doesn't work anymore.... :'(

When I update table dynamically for rerend it, edit Content doesn't... (I can edit, but all option is down...)

Work on it.

**Comment by Patatou** [comment]
Same problem as last month, empty table except when i resize window and $(window).resize(); doesn't work on trigger.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
