### ISSUE TITLE
DateFormat with hours

### ISSUE THREAD

**Issue by ciadch** [Mottie/tablesorter#951]
Hi, 

Is it possible to set default date format for tablesorter with hours like this : dd.mm.yyyy H:i:s (19.06.2015 15:49:49). I want to do that for all my tables without adding a "personal" parser. I try a lot of combinations but impossible to order this format ! 

Thanks !

**Comment by Mottie** [comment]
Hi @ciadch!

The built-in short date format already supports including the time - see the [changing the date format demo](http://mottie.github.io/tablesorter/docs/example-option-date-format.html).

**Comment by ciadch** [comment]
Ok perfect, thank  you !
