### ISSUE TITLE
Resizable widget in div with overflow scrolling

### ISSUE THREAD

**Issue by ryancoakley** [Mottie/tablesorter#953]
Hi, 

Thanks for your tool it is great. I am having some issues with using resizable in a div with an overflow scroll.

I read this issue here where you guys fixed it:

https://github.com/Mottie/tablesorter/issues/737

It works great with his "resizable2" widget he provided in this jsfiddle: 

http://jsfiddle.net/Kermit_the_frog/4oc8bpzm/

Now that you have made it so that you can resize from the entire table instead of just the header, it seems that the functionality is not as the same.. 

In this jsfiddle all of my columns are resizing at the same time when I try and resize one:

http://jsfiddle.net/1417jjbt/5/

In this one using the "resizable2" widget it behaves much better (note seems you have to click a header first to be able to resize):

http://jsfiddle.net/o3zp275x/5/

(sorry if my jsfiddles are awful they are my first).

Anyways, any suggestions on what I could do to get the behavior of the resizing from the entire table and have the div in overflow as well?

Thanks!

**Comment by Mottie** [comment]
Hi @ryancoakley!

So the second demo has the behavior you want, right? You just want to make it resize without needing to click on the header first? Or am I missing something?

**Comment by ryancoakley** [comment]
Hi, Thanks for the reply, but that isn't quite what I meant. 

You  are correct that I have to click the header to get the proper resizing, so I would like to not have to do that.  

However, the main issue is that it can only be resized by dragging the header, and I am using sticky headers, so once I scroll I lose that ability when I scroll the table on the Y overflow. 

So I would like for it to be also resizable by dragging the elements of the table. In my first example it allows you to resize on the table elements, but doing so makes all the columns scale at once, not just the one I am trying to resize. 

So I basically think what you did in, might have broken the extra tweaking to make the resizable work well with tables with an x overflow:

 In New v2.21.3
      Performed a major overhaul on the resizable widget to add resizable handles outside of the table, so now the resizable handles can be used over the entire height of the table!
    This change allows the resizable widget to work seemlessly with the stickyHeaders widget (included in this demo); sadly, to make it work with the scroller widget will require more work.

I hope that makes more sense!

Thanks again.

**Comment by Mottie** [comment]
Ok, the update is available in the master branch. Here is an [updated demo](http://jsfiddle.net/Mottie/4oc8bpzm/3/).

**Comment by ryancoakley** [comment]
You are amazing thank you so much!
