### ISSUE TITLE
Empty "Placeholder"

### ISSUE THREAD

**Issue by randdusing** [Mottie/tablesorter#954]
Is it possible to have an empty cell placeholder like "n/a" that doesn't affect sorting? Do I just need to create a custom sorting function that ignores a value like "n/a" or "none"?

**Comment by Mottie** [comment]
Hi @randdusing!

I think the easiest method would be to create a parser that replaces the "n/a" or "none" with an empty string ([demo](http://jsfiddle.net/abkNM/6160/))

```js
$.tablesorter.addParser({
    id: 'replace-na',
    is: function () {
        return false;
    },
    format: function (s) {
        return (s || '').replace('n/a', '');
    },
    type: 'text'
});
    
$(function () {
    $('table').tablesorter({
        theme: 'blue'
    });
});
```

I was going to suggest using the `data-text` attribute (data-attribute name set by the [`textAttribute` option](http://mottie.github.io/tablesorter/docs/#textattribute), but if you set it to an empty string, it will fallback to the text inside the cell. I'll fix it so you can set it to an empty string.

**Comment by Mottie** [comment]
Oops, I forgot to include that with empty strings, you can then use the `emptyTo` option setting to place the empty cells at the:

* `'top'`
* `'bottom'`
* `'none'` or `'zero'` (sort as if the cell has the value equal to zero)
* `'emptyMax'` (sort as if the value is greater than the max value), or
* `'emptyMin'` (sort as if the value is less than the minimum value)

You can also define this option per column - see [this demo](http://mottie.github.io/tablesorter/docs/example-option-sort-empty.html).

**Comment by randdusing** [comment]
Thank you very much! That's exactly what I needed.

**Comment by Mottie** [comment]
Ok, in the master branch is a change which will allow setting empty data-attributes for text extraction ([demo](http://jsfiddle.net/abkNM/6161/)):

```html
<td data-text="">n/a</td>
```

**Comment by randdusing** [comment]
Thanks again!
