### ISSUE TITLE
tablesorter resizing not work

### ISSUE THREAD

**Issue by masasih** [Mottie/tablesorter#958]
Hi Mottie,

I have problem on resizing feature, resize icon works but no column can be resizable could you please take a look? 

now I found the problem, it is because I have column with data  ( ).
Anyone can resolve this issue?

Thanks in advance.
Masa Sih

**Comment by Mottie** [comment]
Hi @masasih!

Please modify [this demo](http://jsfiddle.net/Mottie/em87cupL/) to duplicate the issue as I don't understand what you mean by having a "column with data( )".

**Comment by masasih** [comment]
Hi Mottie,

thanks for your kindness replying my issue, it is very strange your code worked properly when I use data something like (Mathematics.) (Student01 )  etc.
it my be something prevented resizing feature,   the other tables without ' ()  ' data worked properly.
by the way my widget is ver. v2.22.2.

**Comment by masasih** [comment]
Latest test,
It is not about data contain null, empty or (), but It think about memory or something, it worked for total rows below 298 rows and 4 columns  but greater than or equal to 298 rows resize didn't work.

**Comment by Herst** [comment]
So, just to iterate, the mouse cursor is changing correctly into the one for resizing? Because there is another open issue which might cause the area where resizing is possible to be at the wrong position.

**Comment by masasih** [comment]
mouse icon changed ti resize icon but the column did not resize at all, I think this about memory I have tried with another tables have same problems too.

**Comment by Mottie** [comment]
Ok, [here is a table demo with 500 rows](http://jsfiddle.net/Mottie/em87cupL/6/), please modify it to show me the problem. It would make it easier for me to fix it if I can see it.

And, I still don't understand what you mean by data... do you mean the content of the table cell? I tried [adding an empty column](http://jsfiddle.net/Mottie/em87cupL/7/), but the widget still works.

**Comment by masasih** [comment]
Thanks, Very strange, your 4 samples work properly. but mine not, I replaced mine with all your 3js and theme.blue.css. Do you want me to close this issue or not? because I don't know this is memory or conflicted scripts.

Now my suspect pointing to bundle.config. below my Files and config:

Here my config:
       bundles.Add(new StyleBundle("~/Content/css").Include(
                      "~/Content/bootstrap.css",
                      "~/Content/site.css",
                      "~/Content/theme.ice.css",
                      "~/Content/theme.gac.css",
                      "~/Content/theme.blue.css"
                      ));
					  
					              bundles.Add(new ScriptBundle("~/bundles/additional").Include(
             "~/Scripts/jquery.tablesorter.js",
              "~/Scripts/widget-storage.js",
              "~/Scripts/widget-resizable.js",
              //"~/Scripts/jquery.tablesorter.widgets.js",
              "~/Scripts/custom.js"
                   ));
/*-------------------------------------------------------------------------------------------------------- */



my _layout.cshtml:

<html>
<head>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/jqueryui")
</head>
<body>
    @Scripts.Render("~/bundles/jqueryval")
    <script src="@Url.Content("~/Scripts/mvcfoolproof.unobtrusive.min.js")" type="text/javascript"></script>
    <script src="../../Scripts/MvcFoolproofValidation.min.js" type="text/javascript"></script>
    @Scripts.Render("~/bundles/bootstrap")
    
    @RenderSection("scripts", required: false)
    @Scripts.Render("~/bundles/additional")
</body>
</html>

**Comment by Mottie** [comment]
I would still like to help you find a solution.

I wonder if the `widthFixed` tablesorter option is set to `true`... this option adds a `<col>` for each column with a set percentage width. It would need to be set to `false` for resizing to properly work.

If that isn't the issue,  I would suspect that another script is interfering. It might still help if you would please share the tablesorter initialization code and explain what it is you mean by `data ( )`.

**Comment by masasih** [comment]
Latest  test now resizable function works ( added widthFixed:false and many parameters, sorter,filter,pager and so on)  ,  data means data in cell ( such as:  ", ', (,)  many special characters. i  but sometime the resize cursor was at wrong position, for this case i agree with @Herst.

@Mottie, you can close this case if you want to.  
@Herst., could you give me the previous issue no so we can merge the issue.

**Comment by Mottie** [comment]
@masasih Could you provide a demo showing the resize cursor in the wrong positions. It would really help me troubleshoot the problem, otherwise I would just be guessing at the problem.

**Comment by masasih** [comment]
maybe later, because i'm not using jsfiddle but my own program and cannot just copy and paste into jsfiddle.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
