### ISSUE TITLE
Feature Request: Use <td data-order=" "> to set sort order

### ISSUE THREAD

**Issue by saturdaywalkers** [Mottie/tablesorter#959]
Rather that use the various parsers, I just use something much simpler like
`<td><span class="hide">2015-07-03 12:23</span> Sat, 03-Jul-15 ` i.e. alphanumeric sort on the hidden text
`<td><span class="hide">3 003</span> SWC Walk 3`
`<td><span class="hide">5 010</span> Short Walk 10`

A nice generic solution might be
`<td data-order="2015-07-03 12:23">this text not used for sorting`

**Comment by Mottie** [comment]
Hi @saturdaywalkers!

Actually, that's already built into this forked version.

If the [`textExtraction` option](http://mottie.github.io/tablesorter/docs/#textextraction) is left at its default setting of `'basic'`, then the data-attribute set by the [`textAttribute` option](http://mottie.github.io/tablesorter/docs/#textattribute) (default is `data-text`) is used:

```html
<td data-text="2015-07-03 12:23">this text not used for sorting
```

**Comment by saturdaywalkers** [comment]
Brilliant. I hadn't noticed it the doco. Thanks for the prompt reply, and all your work. Its really appreciated.
