### ISSUE TITLE
Export not working

### ISSUE THREAD

**Issue by DavidAnderson684** [Mottie/tablesorter#960]
I have been trying to get the 'output' widget to work, with no joy.

Eventually, I found Mottie's simple StackExchange demo and JSFiddle; these don't work either - tested in current Chrome and Firefox. Presumably something has broken?

JSFiddle: Pressing "Get CSV" does nothing: https://jsfiddle.net/Mottie/abkNM/2617/
StackExchange answer, containing code implemented in the Fiddle: https://stackoverflow.com/questions/23295723/tablesorter-how-to-export-results-to-csv

**Comment by Mottie** [comment]
Hi @DavidAnderson684!

That fiddle isn't working because it is using https, try this link: http://jsfiddle.net/Mottie/abkNM/2617/

**Comment by DavidAnderson684** [comment]
And... my own code wasn't working because I hadn't loaded the individual output widget JS file. I'll close this now. Thank you!

**Comment by Mottie** [comment]
No problem :smile_cat:

**Comment by DavidAnderson684** [comment]
Final note for anyone reading this in future - if you've got "HTTPS Everywhere" installed (which I had, in both browsers), then Mottie's direct link above will still result in a not-working Fiddle.

**Comment by Mottie** [comment]
I had to replace all the resources with an HTTPS protocol to make it work - it appears that completely removing the protocol didn't work.

https://jsfiddle.net/Mottie/abkNM/6418/
