### ISSUE TITLE
Multiple Tbody paging and sorting

### ISSUE THREAD

**Issue by dileephb** [Mottie/tablesorter#961]
Hi Motie,

I am still unable to find a solution for multiple tbody paging. I have three groups in my grid. Under each group I have 10 to 15 records. When I sort, the records in each group should be sorted. This works great. 
Also I want to achieve pagination across all 3 groups. This does not work correctly because I have each group as a tbody and paging works for the first tbody only.I have looked into many examples and I could not achieve it. You had mentioned that this should be eacsy to achieve, can yu please help.

I am not doing any ajaz operation meaning, I am fetching my records from server and adding it to my view and then calling table sorter plugin. Please let me know if you need more information from me.

**Comment by Mottie** [comment]
Hi @dileephb!

Are you saying you're not doing any ajax operations? So all the rows exist within the table and you want to add pagination to all tbodies?

**Comment by dileephb** [comment]
Mottie,

Thats right. I have a basic mvc view populated with all the rows. I would like to display these rows among 4 different groups. So I used multiple Tbody to display each group. The sorting works fine across all the groups but pagination doesn't work.

**Comment by dileephb** [comment]
Mottie,

Can you please let me know if there is any solution to this. I started usinf table sorter for my grid purpose and now I am not able to meet this requirement. Your help will be greatly appreciated.

**Comment by Mottie** [comment]
I started working on a demo for you this morning, then I found some issues:

* In a table with the pager applied to multiple tbodies:
  * How do you count total rows? I think counting by page would be the solution, but just in case the output were to include a row count, it wouldn't make sense, or would only make sense for the last tbody.
  * How do you count filtered rows?
  * What if each tbody has a different number of rows, what do you do when the page is beyond that tbody? Show nothing? Stay on the last page? Everything would get unsynchronized if you use that approach.
  * How would you differentiate each row count? Would each tbody need a spacer with a custom output?

Then I thought, maybe I could just add multiple tables, all controlled by one pager:

* First off, the pager is not set up to allow multiple bindings to the same set of controls. So, I added event namespace bindings to fix that.
* The same problem with counting rows shows up again.
* Again, what if each table had a different number of rows? Would you show an empty tbody? If the [`fixedHeight` option](http://mottie.github.io/tablesorter/docs/#pager-fixedheight) were set, a nice big empty gap would show up in that empty table.

So, I'm starting to think that maybe the best solution would be to have multiple tables, each with their own pager.

I am open to feedback on how to implement your idea. What are you expecting as a result?

**Comment by Mottie** [comment]
Since I don't see how this change would be useful or really even usable. I'm going to close this issue.

You should be able to use one set of pager controls to work on multiple tables. I just don't think it's a good idea unless all tables have the same number or rows.
