### ISSUE TITLE
destroy or refeshWidgets break with Scroller-Widget source

### ISSUE THREAD

**Issue by CiTRO33** [Mottie/tablesorter#965]
Hello,

i use different  Tables with Tablesorter on my page, since today i would like to include the scroller widget ( It Works  if the scroller widget is used in the Table ).
But if the scroller widget is not used on a table  the destroy or refeshWidgets function break with an error 
you can see a javascript error in e.g. Firebug:
TypeError: f is undefined
..."+d.filterDisabled).prop("disabled",!1),f.remove(),a(b).off(g),c.isScrolling=!1}...

here is a fiddle for the problem:
http://jsfiddle.net/cp9tct3a/2/

If you click on the destroy button the error occur.

**Comment by Mottie** [comment]
Hi @CiTRO33!

Thanks for reporting this issue & the demo, it really helped!

I'll have this fixed shortly.

**Comment by Mottie** [comment]
This fix is now available in v2.22.4!
