### ISSUE TITLE
Default Page size and page number are incorrect

### ISSUE THREAD

**Issue by aetna-wsa** [Mottie/tablesorter#969]
I have been going over this for hours, and it is not making any sense to me. I have page set to 0 and size set to 20, but no matter what I set them to, IE is bringing up "Page 2 of 9" with 10 items displayed. I've reset my code to the defaults, deleted and started over -- nothing fixes this. I'm hoping someone out there has seen this issue before and maybe knows how to fix it?

**Comment by aetna-wsa** [comment]
I'm sorry, this was a browser issue, not an issue with tablesorter. How do you delete an issue?

**Comment by Mottie** [comment]
Hi @aetna-wsa!

Actually the problem you're having might be due to the [`savePages` option](http://mottie.github.io/tablesorter/docs/#save-pages) which prioritizes the user saved set page and size over the initialization setting. Set this option to `false` (default is `true`) and see if that resolves the issues you are having.

**Comment by aetna-wsa** [comment]
It does appear to be some sort of caching issue, that's for sure. In IE I have to logout of my application, open a new 'Private browsing' window and login again to view any updates I make (such as page or size.) I'll try this out since it sounds like it may just be the culprit! Thank you.

**Comment by aetna-wsa** [comment]
It worked, except now it will not go to the next page (1 of 3 pages, click next and it stays on 1)

**Comment by Mottie** [comment]
Are you seeing any errors in the development console? Try setting the `debug` option to `true` and see what messages show up in the console.

**Comment by aetna-wsa** [comment]
I just tried, and got no messages in the console.

**Comment by aetna-wsa** [comment]
Actually, I put the debug in the pagerOptions... I just redid it putting it into .tablesorter and got:

jquery.tablesorter.min.js:2 Overall initialization time (194ms)
2015-07-21 13:24:51.803 jquery.tablesorter.min.js:2 Pager initializing
2015-07-21 13:24:51.853 jquery.tablesorter.min.js:2 Rebuilt table (42ms)
2015-07-21 13:24:51.858 jquery.tablesorter.min.js:2 Pager changing to page 0

**Comment by Mottie** [comment]
And what do you see in the console when you try to change pages?

**Comment by aetna-wsa** [comment]
That's what it says... it applies the widgets, rebuilds the table, then changes to page 0

**Comment by Mottie** [comment]
So, nothing new shows up in the console when you try to change the page?

Hmm, can you modify a demo to duplicate this issue?

* [pager addon](http://jsfiddle.net/1a5yu8yq/)
* [pager widget](http://jsfiddle.net/yfwwzvL8/)

**Comment by aetna-wsa** [comment]
I'll do that and get it back to you. I'm using the addon, I didn't even know there was a widget. Is one preferred over the other (one may be newer or actively developed, for example?)

**Comment by Mottie** [comment]
The widget and the addon basically have the exact same functionality.

I plan on phasing out the addon someday. So the widget would be preferred over the addon.

Also, the [custom build process](https://github.com/Mottie/tablesorter/wiki/Customize#custom-build), which can combine the tablesorter core with selected parsers & widgets, does not allow including the pager addon.

**Comment by aetna-wsa** [comment]
Styling is wiped out, but you should get the picture. That being said, it works in the fiddle, just not on my site. :(

https://jsfiddle.net/1a5yu8yq/

**Comment by Mottie** [comment]
The link you shared is the same link I shared above... make sure to use http:// and not https:// or the demo breaks.

**Comment by aetna-wsa** [comment]
I'm sorry, here you go: http://jsfiddle.net/1a5yu8yq/67/

**Comment by Mottie** [comment]
Ok, so if I had to think about why it would work in the fiddle and not on your site, this is what I am thinking about:

* Is there more than one table on the page? If so, does it also use a pager? You might need to set the container option to target the id:

    ```js
    container : $('#pager')
    ```

    or make sure the "pager" class for each table is unique.
*  If supporting IE, make sure to include a `type` attribute in buttons - just trust me on this.

    ```html
    <button class="prev" type="button">Prev</button>
    ```

* Code from somewhere else on the page is interfering. If you open the console and type the following into the console:

    ```js
    $._data( $('#pager .next')[0] ).events
    ```

    This is how to access jQuery's internal data for each element. And, it should only return an object with one `click` function.

**Comment by aetna-wsa** [comment]
Adding  type="button" to the buttons did the trick! Thank you, I would have never thought of that in a million years. (BTW, your support is *amazing*.)
