### ISSUE TITLE
Unable to get Math Ignore Working on Column Totals

### ISSUE THREAD

**Issue by invisiblekid** [Mottie/tablesorter#976]
Hi Mottie,

It's very likely I'm doing something incorrect, however I don't appear to be able to get data-math="ignore" working on either rows or cells.

I've done a super simple JS Fiddle version of my example. I'm looking to 'ignore' the rows of Maria and Matt either by tr or by td. 

http://jsfiddle.net/8fwc675z/4/ 

Could you provide me with a working fiddle if I'm doing something wrong, or indeed advise if this is a bug.

Many Thanks. Keep up the awesome work!

**Comment by Mottie** [comment]
Hi @invisiblekid!

Hmm, that looks like a bug. I'll have it fixed momentarily.

**Comment by Mottie** [comment]
Here is an [updated demo](http://jsfiddle.net/Mottie/8fwc675z/5/) using the math widget from the master branch.
