### ISSUE TITLE
Build table widget - JSON - headers - translation error

### ISSUE THREAD

**Issue by jonnogibbo** [Mottie/tablesorter#978]
When using the build table widget for JSON, the headers are translated into HTML cells incorrectly - each letter of each word is translated into a th 

example:

"headers":["URL","Grade","Price","Features","Count","status"] 

converts to:

<img width="1306" alt="ford_comparison_tool_and__build_static_data_ford_json__comparison_project__ _brackets" src="https://cloud.githubusercontent.com/assets/10895922/8890845/23b89e86-3308-11e5-8e5c-6abe2acc27d5.png">

**Comment by Mottie** [comment]
Hi @jonnogibbo!

Actually the `headers` option is expected to be an array of arrays since it can be set up to add multiple header rows ([demo](http://jsfiddle.net/hnzph5us/2/)):

```js
headers : [ ["First Name","Last Name","Age","Total","Discount","Date"] ]
```

Or multiple rows:

```js
headers : [
  ["First Name","Last Name","Age","Total","Discount","Date"],
  ["First Name","Last Name","Age","Total","Discount","Date"]
]
```

**Comment by jonnogibbo** [comment]
Mottie - you hero! Apologies, my mistake.

**Comment by Mottie** [comment]
I got your email about not having control over the JSON. In that case, you can use the `build_processing` callback function to modify the raw data how ever you need to make it compatible ([demo](http://jsfiddle.net/hnzph5us/4/)):

JSON

```js
headers : ["First Name","Last Name","Age","Total","Discount","Date"],
```

Tablesorter [Build widgetOption](http://mottie.github.io/tablesorter/docs/example-widget-build-table.html#options) `build_processing`:

```js
build_processing : function(data, wo){
    data.headers = [ data.headers ];
    return data;
}
```
