### ISSUE TITLE
Adding a row in an editable table

### ISSUE THREAD

**Issue by davehayes** [Mottie/tablesorter#979]
I'm trying to add an empty row in an editable table. The JS I'm using to do this is

```javascript
var j = $('#mytable');
j.find("tbody")
  .append(rowhtml)
  .trigger('addRows',[rowhtml, false]);
```
This throws an error in the console:
```
 TypeError: c.cache[tbdy] is undefined
    order: c.cache[tbdy].normalized.length

jquery....ined.js (line 1007, col 8)
```
Of course, the added rows are not editable at all. 

I'm including the following files:
```html
<script src="/js/jquery-1.11.2.js">
<script src="/js/jquery.cookie.js">
<script src="/js/jssha256.js">
<script src="/js/semantic.min.js">
<script src="/js/jquery.tablesorter.combined.js">
<script src="/js/widget-editable.js">
```

Is there something I am missing or is this possibly a bug? Is there a demo of addRows with an editable table somewhere?

**Comment by Mottie** [comment]
Hi @davehayes!

When the [`addRows` method](http://mottie.github.io/tablesorter/docs/#addrows) is used, a reference to the newly added rows needs to be passed, not the html ([demo](http://jsfiddle.net/Mottie/xxmha2Ly/10/)).

```js
var $row = $('<tr><td>Marky</td><td>Mark</td><td>35</td><td>$24.95</td>' +
    '<td>10%</td><td>Mar 22, 2005 10:33 AM</td></tr>');
$('#table tbody')
    .append( $row )
    .trigger('addRows', [ $row, false ]);
```

**Comment by davehayes** [comment]
Thank you very much. That got rid of the issue and my confusion.

However now the new row is not editable. Do I have to call addWidgets too?

**Comment by Mottie** [comment]
I'm still going  to add some code to prevent that js error. So thanks for letting me know about it!

**Comment by davehayes** [comment]
Not a problem. 

Your js demo works to add an editable row, but my js does not set up a new editable row. Any ideas? I know this is probably my issue but just in case you might know... :)

**Comment by Mottie** [comment]
I couldn't only guess... 

* What's different between the js code to trigger the `addRows` method?
* Are there any errors in the console?
* If you are still stuck, please modify the demo I shared to demonstrate the reported problem.

**Comment by davehayes** [comment]
* No effective difference that I can see. I'm comparing a new jsfiddle with what I've got to make sure. 
* Nope
* That's proving difficult to do. I'm working on it! lol

I do notice that the rows are not being rewritten with <div contenteditable="true" class> in my applicaton...this is what appears to be going on in the jsfiddle example.

**Comment by Mottie** [comment]
Is the HTML valid? There should not be any `colspan` or `rowspan` in the newly added rows as it messes with the indexing.

Other than that, I'm not sure why there continues to be an issue... maybe there is another script on the page interfering? Try disabling them one-by-one.

**Comment by davehayes** [comment]
Ok after extensive console logging I've tracked the issue down this far:

In widget-editable.js near line 47 I inserted this:

```javascript
		getColumns : function( c, wo ) {
                  console.log("getColumns called");
                  console.log(wo.editable_columns);
                  console.log(wo.editable_columnsArray);
                  console.log($.type(wo.editable_columns));
                  console.log(wo.editable_columns.indexOf( '-' ));
                  console.log($.isArray( wo.editable_columns) );
```
The console output is
```
getColumns called
0-2
[0, 1, 2]
string
1
false
```
If you'll note the conditionals after that, you can see that if you have `wo.editable_columnsArray` defined as an array and `wo.editable_columns` defined as a string...neither conditional will fire. 

I'm pretty sure you'll consider that a bug. :smile: Now how these variables got that way, I don't have time to track down at the moment (I will eventually though). When I define editable columns, it looks like this:

```javascript
jq.tablesorter({
    widgets: widlist,
    widgetOptions: {
      sortList : [[0,0], [1,0]],
      scroller_height : 300,
      editable_columns : "0-" + maxcol,
      editable_autoAccept : true,
...
```
Let me know if you find anything else from this data. Thanks very much for your attention.

**Comment by davehayes** [comment]
Sorry about closing it, I'm too fast for my mouse.

**Comment by Mottie** [comment]
Ok, the error should no longer be thrown. I added a `debug` message as well.

Also, I've updated the `addRows` method so that if the table only contains one `tbody` then the method will accept a row string. If there are multiple tbodies, not counting information-only tbodies, then it wouldn't know where you want the row(s) added.

Additionally, I made it so you can call all the update methods directly. In this case you can call the `addRows` method function:

```js
// table with only one tbody
var config = $('table')[0].config,
  row = '<tr><td>1</td><td>2</td></tr>',
  resort = [ [0,0] ],
  callback = function( table ) {
    // do something exciting here
  };
$.tablesorter.addRows( config, row, resort, callback );
```

These changes are currently only available within the master branch.

**Comment by davehayes** [comment]
Thank you very much. I'm really not sure why I'd ever want more than one tbody in a table so I should be ok with your caveat there. I'll grab master (probably unwise to just cherry pick that commit).

**Comment by davehayes** [comment]
This patch did not solve my issue. The issue appears to me to be that the `update` function in `widget-editable.js` is asking for this:

```javascript
update: function( c, wo ) {
      ....
     cols = tse.getColumns( c, wo ).join( ',' );
````

The first time this runs (when I initialize the table), cols is something like this

```
td:nth-child(1),td:nth-child(2),td:nth-child(3)
```

but when it runs after that, cols is empty. This is because `getColumns` only works once. It only works once because the logic in it sets `wo.editable_columnsArray` the first time and this prevents it from doing anything ever again. 

The following patch to widget-editable.js fixes my issue, please pardon the lack of proper whitespace preservation:

```patch
--- a/js/widgets/widget-editable.js
+++ b/public/js/widget-editable.js
@@ -10,7 +10,8 @@
 	var tse = $.tablesorter.editable = {
 		namespace : '.tseditable',
 		// last edited class name
-		lastEdited: 'tseditable-last-edited-cell',
+	        lastEdited: 'tseditable-last-edited-cell',
+                myCols: [],
 
 		editComplete: function( c, wo, $cell, refocus ) {
 			c.$table
@@ -48,7 +49,7 @@
 			var indx, tmp,
 				colIndex = [],
 				cols = [];
-			if ( !wo.editable_columnsArray && $.type( wo.editable_columns ) === 'string' && wo.editable_columns.indexOf( '-' ) >= 0 ) {
+                        if ( !wo.editable_columnsArray && $.type( wo.editable_columns ) === 'string' && wo.editable_columns.indexOf( '-' ) >= 0 ) {
 				// editable_columns can contain a range string ( i.e. '2-4' )
 				tmp = wo.editable_columns.split( /\s*-\s*/ );
 				indx = parseInt( tmp[ 0 ], 10 ) || 0;
@@ -60,6 +61,7 @@
 					colIndex.push( indx );
 					cols.push( 'td:nth-child(' + ( indx + 1 ) + ')' );
 				}
+                                tse.myCols = cols;
 			} else if ( $.isArray( wo.editable_columns ) ) {
 				$.each( wo.editable_columnsArray || wo.editable_columns, function( i, col ) {
 					if ( col < c.columns ) {
@@ -67,12 +69,14 @@
 						cols.push( 'td:nth-child(' + ( col + 1 ) + ')' );
 					}
 				});
+                                tse.myCols = cols;
 			}
 			if ( !wo.editable_columnsArray ) {
 				wo.editable_columnsArray = colIndex;
 				wo.editable_columnsArray.sort(function(a, b){ return a - b; });
 			}
-			return cols;
+
+  		        return tse.myCols;
 		},
 
 		update: function( c, wo ) {

```

**Comment by Mottie** [comment]
Why don't you send me a pull request? :smile_cat:

**Comment by davehayes** [comment]
Mostly because I use an editor that messes up your whitespace. I will go that route if you want.

**Comment by Mottie** [comment]
Oh ok, I see what you're doing now... the reason `editable_columnsArray` can't be changed is because it is really an internal variable to store the columns set by the `editable_columns` option. It's easier and faster to reference the array when `editable_columns` is set as a string, like `'0-3'`.

I would prefer not to add a variable to `tse.myCols` for general use because some users may have more than one editable table on the page.

I think what I'll do update the code to not use `editable_columnsArray` at all.

**Comment by davehayes** [comment]
I actually have more than one editable table on the page I'm working on, and this appears to work. It may be that my tables are behind tabs. 

At any rate, since I don't fully grok your codebase yet so I can't comment on the right way to do that. I just know that the code I saw wasn't working for me. I generally write code so I use one and only one data source for the same data (editable_columns and editable_columnsArray are two sources of the same data). It seems to me once you've done getColumns() once, you could cache the result somewhere...but then maybe a user adds a column and it breaks? I dunno.

**Comment by Mottie** [comment]
Ok, please try the updated editable widget in the master branch and let me know if the issue persists.

Also in this update, the `editable_columns` option will now accept a string with both a range and single column values, e.g. `1,3-5,7`.

I updated [this demo](http://jsfiddle.net/Mottie/xxmha2Ly/15/), but you won't notice much difference.

**Comment by davehayes** [comment]
Awesome! The issue is gone with this patch. Thank you.
