### ISSUE TITLE
destroy.pager appears broken

### ISSUE THREAD

**Issue by meatheadmike** [Mottie/tablesorter#980]
Maybe I'm doing something wrong here, but no matter how I call destroy pager it seems to "keep on trucking" regardless. The example show here doesn't seem to work either:

https://mottie.github.io/tablesorter/docs/example-pager.html

If I click on "destroy" I can click next page, add rows, etc. It all works still.

**Comment by Mottie** [comment]
Hi @meatheadmike!

Ahh, it looks like broke it when I added unique pager namespaces in https://github.com/Mottie/tablesorter/commit/dd80e3c88fcc6834589272f2711fa76b6ed8bb46.

For now, you can still enable, disable and destroy the pager, but you'll need to get and use the namespace first ([demo](http://jsfiddle.net/Mottie/1a5yu8yq/68/)).

```js
var pagerOptions = {},
    $table = $('table');

$('.enable').click(function () {
    var $this = $(this),
        namespace = $table[0].config.namespace + 'pager',
        state = $this.text(),
        newState = state === 'Enable' ? 'Disable' : 'Enable';
    $table.trigger(state.toLowerCase() + namespace);
    $this.text(newState);
});

$('.destroy').click(function () {
    var $this = $(this),
        namespace = $table[0].config.namespace + 'pager';
    if (/Destroy/.test($this.text())) {
        $table.trigger('destroy' + namespace);
        $this.text('Restore Pager');
    } else {
        $table.tablesorterPager(pagerOptions);
        $this.text('Destroy Pager');
    }
    return false;
});
```

**Comment by meatheadmike** [comment]
Now that's what I call efficiency! Thank you sir!
