### ISSUE TITLE
Adding/removing rows = pager troubles

### ISSUE THREAD

**Issue by meatheadmike** [Mottie/tablesorter#981]
So here's my scenario... I have a table. I go to do a search via ajax. When it comes back I update the header and the rows. So in other words I'm completely rebuilding the table on each search. My problem is that the pagination acts pretty funky. Basically after the search is done everything *looks* ok. But click on the "last" button and you'll see that the pagination resets to the previous size. What gives? Is this a closure somewhere in my code that I'm not seeing? Is there a better way to kill/rebuild the tablesorter+pager?

Here's a demo that I conjured up:
http://jsfiddle.net/1avd9pu3/2/

**Comment by Mottie** [comment]
Hey @meatheadmike!

It looks like the destroy method isn't unbinding the pager controls. I'll get to work on that fix.

**Comment by Mottie** [comment]
Don & verified - the demo you shared above works perfectly now :smile_cat:

**Comment by meatheadmike** [comment]
Thank you again. You are definitely a JQ master!
