### ISSUE TITLE
Table inside a hidden div does not size.

### ISSUE THREAD

**Issue by bindrid** [Mottie/tablesorter#984]
I use Ajax Tool kit tab controller on my pages. I have discovered that if the scroller widget is turned on for a back tab, or for that matter, just a plain hidden div (`<div style='display:none'>`), the scroller div width gets set to zero and stays that way even after the tab or div becomes visible.

How do I tell the table to resize itself once the tab is brought into view?

**Comment by Mottie** [comment]
Hi @bindrid!

Try the `setFixedColumnSize` method, but don't pass a `size` value.

```js
$( 'table' ).trigger( 'setFixedColumnSize', size );
```

If that doesn't work, try triggering a window resize

```js
$( window ).resize();
```

And if neither of those methods work, please modify [this demo](http://jsfiddle.net/Mottie/mqv16pd4/) to show the problem. It'll help me troubleshoot the issue more easily.

**Comment by bindrid** [comment]
I changed the demo to demonstrate the problem that I am having. 

I set up the table on the second tab using jquery ui tabs. 

You will see that after you click on the second tab to see the table that it will not appear until the browser is resized. 

Using the debugger, I saw that the container for the scroller had its width set to zero. 

Thanks for your interest in this, 
Scott 


----- Original Message -----

**Comment by Mottie** [comment]
If you look at the [home wiki page](https://github.com/Mottie/tablesorter/wiki#misc), there is a demo showing how to deal with the table when inside of jQuery UI tabs. Basically, the table needs to be updated because hidden elements have a zero-width ([demo](http://jsfiddle.net/Mottie/abkNM/6633/)):

```js
$("#tabs").tabs({
    activate: function (event, ui) {
        var $t = ui.newPanel.find('table');
        if ($t.length) {
            if ($t[0].config) {
                $t.trigger('applyWidgets');
            } else {
                $t.tablesorter({
                    theme: 'blue',
                    widgets: ["zebra", 'scroller'],
                    widgetOptions: {
                        scroller_fixedColumns: 1,
                        scroller_height: 300,
                        // scroll tbody to top after sorting
                        scroller_upAfterSort: true,
                        // pop table header into view while scrolling up the page
                        scroller_jumpToHeader: true
                    }
                });
            }
        }
    }
});
```

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.

**Comment by bindrid** [comment]
yes, it has. I did implement the logic using your suggestion. 
  
Sorry, I did not respond sooner, vacation, etc. 
  
Thank you, 
Scott 

----- Original Message -----
