### ISSUE TITLE
Tablesorter append data with dynamic column from AJAX ,but column select  not work

### ISSUE THREAD

**Issue by don750421** [Mottie/tablesorter#985]
Tablesorter version: 2.22.3

Because Query DB result is not fixable,so I create the tablesorter after Query DB. 
But the column select function is not work.
The "columnSelector_container: '#TableColSel' " always display "Auto" Item.

![image](https://cloud.githubusercontent.com/assets/13444821/9130544/5459a9d2-3d16-11e5-96c2-5567766a25f3.png)

![image](https://cloud.githubusercontent.com/assets/13444821/9130592/c156d6f4-3d16-11e5-9470-ec09ce4e9f4e.png)

ashx return message like
![image](https://cloud.githubusercontent.com/assets/13444821/9130580/a1a37fce-3d16-11e5-89e9-3196ff953e3e.png)

**Comment by Mottie** [comment]
Hi @don750421!

With that code, if ajax is used more than once, tablesorter won't reinitialize correctly. The contents of the table are being cleared, but not the parameters saved to the `table`  element. Try moving the `id="info" to the wrapper div, then append the response with a table wrap:

```html
<div id="info" style="overflow:auto; width:500px; height:150px"></div> 
```

```js
success: function( response ) {
    $('#info').html( '<table>' + response + '</table>' );

    $('#info table').tablesorter({
        ...
    })
    .tablesorterPager({
        ...
    });
}
```

If you don't want to use the `auto` feature, you can set the [`columnSelector_mediaquery` option](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-mediaquery) to `false`.

If you want the column selector to start out with the `auto` feature unchecked, then set the [`columnSelector_mediaqueryState` option](http://mottie.github.io/tablesorter/docs/example-widget-column-selector.html#column-selector-mediaquery-state) to `false`.

**Comment by don750421** [comment]
Thanks Mottie Reply,
I try to modify my code .
Only use the <div></div>
<div id="info" style="overflow:auto;height:150px"></div>

**Comment by Mottie** [comment]
Hmm, ok... I'm not 100% sure what the problem is, but maybe if you used the pager ajax functions things would work better.

[Here is a demo](http://jsfiddle.net/uwZc2/48/) of the column selector & pager working together.

**Comment by don750421** [comment]
I modify my code again and follow your ajax function of sample code.

My .ashx return json format is following information is returned.
like 
[1,[["3781478","1882472","V","2013/4/3 下午 03:22:06","2013/4/3 下午 03:22:06","998D510DD","CRT"]],["PACKAGE_ID","ID_NUMBER","PACKAGE_TYPE","CREATION_DATE","LAST_UPDATE_DATE","TEST_PACKAGE","STATUS"]]

but I can't use "hasOwnproperty('rows')" to get the row count 
![image](https://cloud.githubusercontent.com/assets/13444821/9240810/7dcaef52-419d-11e5-880a-6940b3f2227c.png)

**Comment by Mottie** [comment]
Yeah, it looks like it's returned an array of arrays.

Would you share your `ajaxProcessing` code (as text & not a screenshot) please? It might help me narrow down the problem.

**Comment by don750421** [comment]
Hi Mottie ,
I modify my code ajax and return json to again.but 
my ajaxProcessing code is 
ajaxProcessing: function (data) {
                            if (data && data.hasOwnProperty('rows')) {

                                var indx, r, row, c, d = data.rows,
                                // total number of rows (required)
                                total = data.total_rows,
                                // array of header names (optional)
                                headers = data.headers,
                                // cross-reference to match JSON key within data (no spaces)
                                headerXref = headers.join(',').replace(/\s+/g, '').split(','),
                                // all rows: array of arrays; each internal array has the table cell data for that row
                                rows = [],
                                // len should match pager set size (c.size)
                                len = d.length;
                                // this will depend on how the json is set up - see City0.json
                                // rows
                                for (r = 0; r < len; r++) {
                                    row = []; // new row array
                                    // cells
                                    for (c in d[r]) {
                                        if (typeof (c) === "string") {
                                            // match the key with the header to get the proper column index
                                            indx = $.inArray(c, headerXref);
                                            // add each table cell data to row array
                                            if (indx >= 0) {
                                                row[indx] = d[r][c];
                                            }
                                        }
                                    }
                                    rows.push(row); // add new row array to rows array
                                }

                                return [total, rows, headers];
                            }
                    },

and .ashx return json string is .
{"total_rows":1,"headers":["PACKAGE_ID","ID_NUMBER","PACKAGE_TYPE","CREATION_DATE","LAST_UPDATE_DATE","TEST_PACKAGE","STATUS"],"rows":[{"PACKAGE_ID":3781478.0,"ID_NUMBER":1882472.0,"PACKAGE_TYPE":"S","CREATION_DATE":"2013-04-03T15:22:06","LAST_UPDATE_DATE":"2013-04-03T15:22:06","TEST_PACKAGE":"998D510DD","STATUS":"CRT"}]}

and HTML is ..
![image](https://cloud.githubusercontent.com/assets/13444821/9269044/c57157f6-4297-11e5-96d2-40f0276bfcb5.png)

and Column Select function 
![image](https://cloud.githubusercontent.com/assets/13444821/9269051/def4dcca-4297-11e5-9379-aed4a1888984.png)

**Comment by Mottie** [comment]
It appears that the issue is that the `thead` row is empty. Tablesorter won't initialize if there are no headers, so I think the easiest solution would be to add that HTML:

```html
<div style="overflow: auto; height: 150px;">
    <table class="tablesorter">
        <thead>
            <tr>
                <th>Package ID</th>
                <th>ID Number</th>
                <th>Package Type</th>
                <th>Creation Date</th>
                <th>Last Update</th>
                <th>Test Package</th>
                <th>Status</th>
            </tr>
        </thead>
        <tbody></tbody>
    </table>
</div>
```

With that change, everything should work - [demo](http://jsfiddle.net/Mottie/1a5yu8yq/73/)

Oh, and to keep the nicely formatted header cell text, don't return the `headers` value from the `ajaxProcessing` function:

```js
ajaxProcessing: function (data, table) {
    // ...
    return [total, rows]; // don't include `headers` here
}
```

**Comment by don750421** [comment]
Hmm, maybe you don't know my problem.Sorry~
I want to used a page let user key in the SQL Command.and the tablesorter will show query result.
but user SQL command and query column is non-fixed.
so... I want to set the tablesorter column by query result header.
If I used your solution ,the tablesorter header will be fixed...

![image](https://cloud.githubusercontent.com/assets/13444821/9296167/0436476c-44b9-11e5-90d2-0b6e1448fb4b.png)

**Comment by Mottie** [comment]
Hmm, ok. It sounds like you need some way to update the contents of the column Selector. There isn't an easy method right now. I'll update the column selector widget to make this easier.

**Comment by Mottie** [comment]
Ok, here is an [updated demo](http://jsfiddle.net/Mottie/1a5yu8yq/76/).

All you need to do is include the following code to refresh the Column Selector container contents:

```js
$('table').on('pagerComplete', function(){
  $(this).trigger('refreshColumnSelector', 'selectors');
});
```

This method will also update using any changed `data-priority` or `data-selector-name` attributes.

Use this updated method as follows (showing examples added to the documentation):

| Method | Description |
|-----|-----|
| `$('table').trigger('refreshColumnSelector');` | Refresh current settings; mainly used to update the css used to hide/show columns |
| `$('table').trigger('refreshColumnSelector', [ [2,3,4] ]);` | Set visible columns; turn off "auto" mode (original method). |
| `$('table').trigger('refreshColumnSelector', [ 'columns', [5,6] ]);` | Set visible columns; turn off "auto" mode (alternative method). |
| `$('table').trigger('refreshColumnSelector', true);` | Turn on "auto" mode (original method). |
| `$('table').trigger('refreshColumnSelector', [ 'auto', true ]);` | Turn on "auto" mode (alternate method). |
| `$('table').trigger('refreshColumnSelector', [ 'auto', false ]);` | Turn off "auto" mode (alternate method). |
| `$('table').trigger('refreshColumnSelector', [ 'auto', [2,3,4] ]);` | Turn on "auto" mode & set visible columns when "auto" is off. |
| `$('table').trigger('refreshColumnSelector', 'selectors');` | Refresh selector popup contents & maintain "auto" mode; this allows updating column priorities, column names & widget options. |
| `$('table').trigger('refreshColumnSelector', [ 'selectors', [5,6] ]);` | Refresh selector popup contents; Set visible columns & turn off "auto" mode. |
| `$('table').trigger('refreshColumnSelector', [ 'selectors', true ]);` | Refresh selector popup contents; Turn on "auto" mode. |

**Comment by don750421** [comment]
Thanks Mottie.
I will look forward to your next update
