### ISSUE TITLE
Bind an onChange function to the filter fields - how?!

### ISSUE THREAD

**Issue by crazyserb** [Mottie/tablesorter#986]
how do I bind an onChange function to the filter fields? I've tried this: 

$('.tablesorter-filter,.select2-input').on('change',function(){
	console.log("it's working...");
	myfunction();
});

But I get nothing... what am I missing?!

**Comment by Mottie** [comment]
Hi @crazyserb!

Try using either of these methods ([demo](http://jsfiddle.net/856bzzeL/592/)):

```js
$table
    .on('filterEnd', function () {
        console.log('filterEnd');
    })
    .on('search','.tablesorter-filter', function(e){
        console.log( e.type );
    });
```

\* Note the `search` method is binding to a [delegated event](http://api.jquery.com/on/#direct-and-delegated-events).

**Comment by crazyserb** [comment]
That worked!

Thank you so much! I was dying here looking for the hook to latch onto...

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
