### ISSUE TITLE
current version scroller&headerSort not support? ie8 mode run

### ISSUE THREAD

**Issue by GoGillDong** [Mottie/tablesorter#987]
![1](https://cloud.githubusercontent.com/assets/5512509/9190348/19fa1b7a-402f-11e5-9ebe-db2de0964544.png)
![2](https://cloud.githubusercontent.com/assets/5512509/9190388/a1349d9a-402f-11e5-8853-00661eed0078.png)

hi, thank you

current version use scroller&headerSort, tablesorter.js error and table header click 
(ie8 mode run) 

ie9 mode run is ok

I want to ie8 mode run is scroller&sort run

please..

**Comment by Mottie** [comment]
Hi @GoGillDong!

Thanks for reporting this issue. It is now fixed in the master branch, and will be available in the next update.

**Comment by GoGillDong** [comment]
thank you!!

**Comment by Mottie** [comment]
Hi @GoGillDong!

Can you please make sure that commit https://github.com/Mottie/tablesorter/commit/91a76eae45dd4cdf9c13a4ab895d95037250de57 doesn't break IE8 again? Thanks!

**Comment by GoGillDong** [comment]
Hi @Mottie 

update version is scroller&headerSort ie8 test No problem!

 so good!

Thanks!
