### ISSUE TITLE
Pager ts.showError shows undefined(0)

### ISSUE THREAD

**Issue by Federico-G** [Mottie/tablesorter#988]
I'm having a problem when ajax fails in the tablesorter pager. The function renderAjax calls ts.showError with
```javascript
ts.showError(table, exception.message + ' (' + xhr.status + ')');
```

Where exception is a string and .message is undefined.
In my code exception contains the string "timeout"

**Comment by Mottie** [comment]
Hi @Federico-G!

You're right! I have the [correct code in the pager addon](https://github.com/Mottie/tablesorter/blob/master/addons/pager/jquery.tablesorter.pager.js#L395-L402):

```js
ts.showError(table,
	xhr.status === 0 ? 'Not connected, verify Network' :
	xhr.status === 404 ? 'Requested page not found [404]' :
	xhr.status === 500 ? 'Internal Server Error [500]' :
	exception === 'parsererror' ? 'Requested JSON parse failed' :
	exception === 'timeout' ? 'Time out error' :
	exception === 'abort' ? 'Ajax Request aborted' :
	'Uncaught error: ' + xhr.statusText + ' [' + xhr.status + ']' );
```

I guess I forgot to copy it over to the pager widget. I'll get right on that!
