### ISSUE TITLE
Tablesorter add update table method

### ISSUE THREAD

**Issue by Federico-G** [Mottie/tablesorter#989]
One of the tablesorter methods is updateAll which description based on the docs is 'Update a column of cells (thead and tbody)'.
But it also refreshes the widgets:
```javascript
ts.refreshWidgets(table, true, true);
```
Although I need to refresh the thead because I get the columns names after init, I don't want to refresh the pager widget.
I made a similar function without that line and it worked.

Could you add that function to the tablesorter methods? Something like 'updateTable'? It might be useful to other people too

**Comment by Mottie** [comment]
Hi @Federico-G!

Ideally, I would prefer to use delegated event bindings on the header so it wouldn't ever need to be updated; but `delegate` wasn't added to jQuery until v1.4.2... and for some odd reason, I'm trying to maintain compatibility with jQuery v1.2.6.

Until I can stop support for older jQuery & older IE, I might look into adding a "updateHeader" method to just refresh the header cells and not touch the tbody or widgets. I'll look into it this weekend.

**Comment by Mottie** [comment]
Added in v2.23.0.
