### ISSUE TITLE
Enhancement Request: Pager ajax errors

### ISSUE THREAD

**Issue by Federico-G** [Mottie/tablesorter#992]
Hi @Mottie 

I saw this issue #486 about ts.showError in Pager

It's a very good idea, but how about making that more useful? For example if the ajax request fails, now I'll get only a message and not any xhr object or a way to ask for it again, or handle it in any other way rather than only show an error. Even `exception` is inside the xhr object (`xhr.statusText`)

I can redeclare the ts.showError method, but without any xhr object I can't do anything but handling the error string on another way.

It would also work to show the error message in any language, not only english (I speak Spanish by the way)

Thanks!

**Comment by Mottie** [comment]
Hi @Federico-G!

Hmm, I guess I could add a pager error callback that can be used to change the message. I'll work on it this weekend.

**Comment by Mottie** [comment]
I added an `ajaxError` callback function, use it as follows:

```js
$('table').tablesorterPager({
  ajaxError: function( config, xhr, exception ) {
    // returning false will abort the error message
    // the code below is the default behavior when this callback is set to `null`
    return
      xhr.status === 0 ? 'Not connected, verify Network' :
      xhr.status === 404 ? 'Requested page not found [404]' :
      xhr.status === 500 ? 'Internal Server Error [500]' :
      exception === 'parsererror' ? 'Requested JSON parse failed' :
      exception === 'timeout' ? 'Time out error' :
      exception === 'abort' ? 'Ajax Request aborted' :
      'Uncaught error: ' + xhr.statusText + ' [' + xhr.status + ']' );
  },
  // other options
});
    
```
