### ISSUE TITLE
How to use the Tablesorter master detail (child row) with ajax ?

### ISSUE THREAD

**Issue by don750421** [Mottie/tablesorter#993]
I want to used tablesorter to do master detail table.and I follow the demo to do.
https://mottie.github.io/tablesorter/docs/example-child-rows.html

my ajax return json is 
![image](https://cloud.githubusercontent.com/assets/13444821/9269262/6894538c-429a-11e5-8f0d-2686047db89d.png)

but ajax return json string always " data = null "
![image](https://cloud.githubusercontent.com/assets/13444821/9269247/3a8ec83c-429a-11e5-8400-34a5ccac55da.png)

then table showing
![image](https://cloud.githubusercontent.com/assets/13444821/9269252/45b0c9ae-429a-11e5-8496-a5ceab62607d.png)

why ?

**Comment by Mottie** [comment]
Hi @don750421!

It appears that the JSON is not valid. The HTML in the rows array is not wrapped in quotes. jQuery won't parse invalid JSON, so make sure it is valid first by using http://jsonlint.com/

**Comment by don750421** [comment]
Sorry,because I see the method in tablesorter 's docs 
https://mottie.github.io/tablesorter/docs/index.html#api
![image](https://cloud.githubusercontent.com/assets/13444821/9296575/82228ede-44c2-11e5-9036-5c3b3b5f0e1a.png)

So,it is seems infeasible. 
Well,what is the valid Json that used to child row??

Thanks.

**Comment by Mottie** [comment]
I think you misunderstood me... the JSON results in the screenshot (please stop posting screenshots of code) that was shared above did not have quotes.

I saw:

```js
<tr><td>r0c0</td><td>r0c1</td></tr><tr><td>r1c0</td><td>r1c1</td></tr>
```

when I should see

```js
"<tr><td>r0c0</td><td>r0c1</td></tr><tr><td>r1c0</td><td>r1c1</td></tr>"
```

as a JSON result.

Anyway, if you want to add a child row, the `<tr>` just needs the child row class name (set by the [`cssChildRow` option](https://mottie.github.io/tablesorter/docs/index.html#csschildrow).

```js
"<tr class="tablesorter-childRow"><td>r0c0</td><td>r0c1</td></tr><tr><td>r1c0</td><td>r1c1</td></tr>"
```

**Comment by don750421** [comment]
Sorry , I really misunderstood you,so I modify return json string.

```javascript
{"total_rows":1,"headers":["Detail","NUMBER","REQUEST","CUST","NO","CLOSE","CREATEDATE","LASTUPDATEDATE","Edit","Delete"],"rows":["<tr><td rowspan='2'><a href='#' class='toggle'><img src='/images/Details16.png'/></a></td><td>AAC150204-01-01</td><td>efefef</td><td>AAC</td><td>svsvsv</td><td>N</td><td>2015/02/04 16:32:31</td><td></td><td></td><td></td></tr>","<tr class='tablesorter-childRow'><td colspan='4'><div class='bold'>testchildrow</div></td></tr>"]}
```
and my javascript is following..
```javascript
    var gv_HandoverTable;
        var gv_row;
        $(function () {
            $("#divDisplayTable").resizable();
            $('.tablesorter-childRow td').hide();
            gv_HandoverTable.find('.tablesorter-childRow td').addClass('hidden');
        });

        gv_HandoverTable = $("#tJobHandover").tablesorter({
            theme: 'blue',
            sortList: [[0, 0]],
            cssChildRow: "tablesorter-childRow",
            widthFixed: true,
            widgets: ['zebra', 'stickyHeaders', 'filter','pager'],//'columnSelector',
            widgetOptions: {
                //columnSelector_container: '#QueryDBColSel',
                //columnSelector_columns: {
                //},
                //columnSelector_mediaquery: true,
                //columnSelector_mediaqueryState: false
            }
        })
        .tablesorterPager({
            // target the pager markup - see the HTML block below
            //?page=0&size=25&filter&sort[0]=1
            //?page=0&size=25&filter[0]=1373781600&filter[1]=800&sort[0]=1
            container: $(".pager"),
            ajaxUrl: "/Handler/Handler.ashx?WorkType=JOBHANDOVERLIST&page=0&size=20&filter[7]=N",
            page:0,
            size: 20,
            savePages: false,
            cssGoto: '.gotoPage',
            countChildRows: false,
            customAjaxUrl: function (table, url) {
                // need to dynamically update page size
                // since adding 'rows : size' in ajaxObject.data doesn't
                // dynamically update the size
                table.config.pager.ajaxObject.data.rows = table.config.pager.size;
                //$(table).trigger('changingUrl', url);
                return url;
            },
            ajaxObject: {
                dataType: 'json',
                type: 'POST',
                data: {
                    //SevName: $("#QuerySevName").val().trim(),
                    //SQLComm: $("#QuerySQLComm").val().trim()
                },
            },
            ajaxProcessing: function (data) {
                if (data && data.hasOwnProperty('rows')) {
                    return [data.total_rows, $(data.rows), data.headers];
                }
            },
            // css class names of pager arrows
            cssNext        : '.next',  // next page arrow
            cssPrev        : '.prev',  // previous page arrow
            cssFirst       : '.first', // go to first page arrow
            cssLast        : '.last',  // go to last page arrow
            cssGoto        : '.gotoPage', // page select dropdown - select dropdown that set the "page" option
            cssPageDisplay : '.pagedisplay', // location of where the "output" is displayed
            cssPageSize    : '.pagesize', // page size selector - select dropdown that sets the "size" option
            // class added to arrows when at the extremes; see the "updateArrows" option
            // (i.e. prev/first arrows are "disabled" when on the first page)
            cssDisabled    : 'disabled', // Note there is no period "." in front of this class name
            cssErrorRow: 'tablesorter-errorRow', // error information row

            output: 'Showing: {startRow} to {endRow} (Total:{totalRows})'
        });
```

There is an error in tablesorter.pager
![image](https://cloud.githubusercontent.com/assets/13444821/9302093/651431d2-4506-11e5-902a-a76cbb0c1878.png)

And I also post my code on the fiddle http://jsfiddle.net/3hruotu5/

Have I missed something?

**Comment by Mottie** [comment]
Ok, I see a few issues:

* The JSON *should not* have multiple rows separated by commas

    ```js
    { "rows" : [ "<tr>...</tr>","<tr class='tablesorter-childRow'>...</tr>" ] }
    ```

    unless your `ajaxProcessing` function does this:

    ```js
    ajaxProcessing: function (data) {
        if (data && data.hasOwnProperty('rows')) {
            return [data.total_rows, $( data.rows.join('') ), data.headers];
        }
    },
    ```

    or actually, you can keep the current `ajaxProcessing` function if you combine the rows and remove the wrapping array:

    ```js
    { "rows" : "<tr>...</tr><tr class='tablesorter-childRow'>...</tr>" }
    ```

* Don't use a `rowspan` or `colspan` in *non-child rows*. Using spans within multiple child rows is okay. Including a span in a non-child row shouldn't cause an error, but the row may not sort as you expect.

* The [`ajaxUrl` option](http://mottie.github.io/tablesorter/docs/#pager-ajaxurl) setting should contain placeholders for `{page}`, `{size}` & `{filter:filter}`.

    ```js
    ajaxUrl: "/Handler/Handler.ashx?WorkType=JOBHANDOVERLIST&page={page}&size={size}&{sortList:sort}&{filterList:filter}",
    ```

**Comment by don750421** [comment]
Thanks Mottie,
I follow your suggest and modify my code.
JSON return string.
````
{"total_rows":1,"headers":["Detail","NUMBER","REQUEST","CUST","NO","CLOSE","CREATEDATE","LASTUPDATEDATE","Edit","Delete"],"rows":["<tr><td><a href='#' class='toggle'><img src='/images/Details16.png'/></a></td><td>AAC150204-01-01</td><td>efefef</td><td>AAC</td><td>svsvsv</td><td>N</td><td>2015/02/04 16:32:31</td><td></td><td></td><td></td></tr><tr class='tablesorter-childRow'><td><div class='bold'>rvervreverververv</div></td></tr>"]}
````
and modify ajax 's  ajaxUrl  option 
````
ajaxUrl: "/Handler/Handler.ashx?WorkType=JOBHANDOVERLIST&page={page}&size={size}",
````
but the same error message at line #430 
![image](https://cloud.githubusercontent.com/assets/13444821/9320367/acbd2266-458b-11e5-90e8-c9a019db00a4.png)
![image](https://cloud.githubusercontent.com/assets/13444821/9320370/be840f3c-458b-11e5-8a6c-5f311193c24d.png)

Why is there an error happen?

**Comment by Mottie** [comment]
Remove the array wrapping (`[ ]`) the `"rows" value:

Change this

```js
"rows": [ "<tr>...</tr>" ], ...
```

to this:

```js
"rows": "<tr>...</tr>", ...
```

**Comment by don750421** [comment]
Oh no, I forget to remove  wrapping array.sorry.
but I have another question that the child row can't hide after ajax return.

I think it is because set the hide before ajax return.
````
$('.tablesorter-childRow td').hide();
````
Have I any method or api  to hide child row after ajax return ?

**Comment by Mottie** [comment]
Try css:

```css
.tablesorter-childRow td { display: none; }
```

**Comment by don750421** [comment]
Thanks @Mottie ,it is work for me.
I have some questions about tablesorter.
If I used the ajax to get data from database,
so .. all of filter, sort,paging is need to do on the server side ?
or I just query all the data by database and  tablesorter plugin will to do this ?

Because I used the child row and ajax,but the paging,sort,filter is not work..
I don't know what happened? 
![image](https://cloud.githubusercontent.com/assets/13444821/9325374/628d60a0-45c4-11e5-9808-587dd62fcb5a.png)
![image](https://cloud.githubusercontent.com/assets/13444821/9325376/68250bd0-45c4-11e5-8e0f-17ecfe0f9e58.png)

**Comment by Mottie** [comment]
Yes, you will have to sort, filter and provide the correct number of selected rows, total rows & filtered rows to the pager when you use ajax. The pager doesn't have access to your database to get all of these values, nor can tablesorter sort a small part of a larger database without access to the entire database.

I think the best example of what you want is in the documentation under [`ajaxProcessing` of objects](http://mottie.github.io/tablesorter/docs/#object) returned from the server. The JSON contains the `totalRows` contained in teh database, the current `filteredRows` count, the set number of rows to be displayed (in the data HTML) and other various bits of information you might want to display in the pager output.

The pager also has a [`countChildRows` option](http://mottie.github.io/tablesorter/docs/#pager-countchildrows) which is set to `false` by default which keeps the child row with it's parent. But really this option is for non-ajax tables.

**Comment by don750421** [comment]
Thanks for your patient explanation; it's all now clear as crystal.
but I am still curious about it's work that used another ajax method.
````
            $.ajax({
                url: "/Handler/SrcHandler.ashx?TableName=Ticket",
                type: 'POST',
                async: false,
                data: {
                    DataSrc: iDataSrc,
                    Datakey: iDataKey
                },
                success: function (response) {
                    if (response.Result)
                    {
                        $('#Ticket tbody').empty().append(response.ReturnText);
                        $('#Ticket').trigger('update');
                    }
                }
            });
```
When I click the column to sort. it's really can work.
![image](https://cloud.githubusercontent.com/assets/13444821/9346759/6c8aae7a-4653-11e5-9713-293522124e31.png)

**Comment by Mottie** [comment]
It's because within the pager addon/widget, I turn off tablesorter's sorting ability.

If you load in a table by a different method, then sorting will still be enabled. The reason it is disabled on the client side is because when a user clicks on the header to sort a column, they *expect* the sort to apply to the entire database, not just what is visible on the page.

If there was some way to differentiate the sort so the *user knows exactly* what they are sorting, then I don't see a problem with re-enabling client-side sorting.

**Comment by don750421** [comment]
OK, Thanks @Mottie .

If I using the child row and filter in my page,and it's multi sort key and multi filter column.
like this...
````
.../Handler/Handler.ashx?WorkType=OVERLIST&page=0&size=10&sort[1]=0&sort[2]=1&fcol[3]=AAA&fcol[5]=N"
````

How do I Parse the sort and fcol array on the server-side ?
Is this the only-way that parse the array ?
````
foreach (String key in Request.QueryString.AllKeys)
{
    Response.Write("Key: " + key + " Value: " + Request.QueryString[key]);
}
````

**Comment by Mottie** [comment]
I'm sorry, I don't know very much about server-side languages.

You will find a better answer if you asked that question over on [Stackoverflow](http://stackoverflow.com/). But, make sure to search for the answer before asking, or your question will get closed without any response.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
