### ISSUE TITLE
index.html table not sorting

### ISSUE THREAD

**Issue by richardgmcmahon** [Mottie/tablesorter#995]
the example table in index.html does not sort for me. I changed the jquery from 1.2.6 to latest and
it worked. i.e. changed

```
<script src="docs/js/jquery-1.2.6.min.js"></script>
 
to:     
  
 <script src="docs/js/jquery-latest.min.js"></script>
        
```

**Comment by Mottie** [comment]
Hi @richardgmcmahon!

Thanks for reporting this issue! I don't have the unit tests set up to check the core against different versions of jQuery. It sounds like something I need to work on, either that or drop v1.2.6 support :wink:
