### ISSUE TITLE
pager showError error

### ISSUE THREAD

**Issue by Federico-G** [Mottie/tablesorter#997]
Hi @Mottie!

In v2.23.0 when showError is called and xhr is undefined the browser throws:
Uncaught TypeError: Cannot read property 'status' of undefined

So I read the code and noticed this:
```javascript
if ( typ !== 'string' ) //typ = "undefined"   eval:true
	message = xhr.status // !! undefined.status !!
	//(...)
```

I think typ must be equals to 'object'

**Comment by acidnine** [comment]
Same here, rolled back to v2.22.5 until fixed.

**Comment by Mottie** [comment]
Hi @Federico-G & @acidnine!

Thanks for reporting this problem, I'll have it fixed shortly.

**Comment by Mottie** [comment]
Ok, so I ended up making a few internal changes.

* The `ajaxError` callback now includes a `settings` parameter, which previously was not included from the jQuery [`.ajaxError()` method](http://api.jquery.com/ajaxError/)

    ```js
    ajaxError: function( config, xhr, settings, exception ){ return exception; };
    ```

    I entered it between the `xhr` and `exception` parameter to keep the same order as the parameters returned by jQuery.

* The `ajaxError` callback is now *always* called, including times when the `$.tablesorter.showError()` function is not called by the internal ajax error method.
* If the `ajaxError` callback returns an empty string, it will be essentially the same as `return false` in that all error rows will be removed.
* I guess I didn't explicitly mention this in the docs, but the message returned by the `ajaxError` function can include HTML, or even the HTML for the entire row to be added as an error row to the `thead`.
