### ISSUE TITLE
Sort accordance based on image

### ISSUE THREAD

**Issue by AviHafner** [Mottie/tablesorter#999]
Hello
I will be happy if you can provide me 2  examples
1) If there is IMG in TD
2) If there HREF in TD

Thank you
I love what you are doing

**Comment by Mottie** [comment]
Hi @AviHafner!

## Image

There is an image parser built into tablesorter (only in my fork), where you set the column header class with "sorter-image". By default, the parser extracts out the `alt` attribute content for sorting. If there is no `alt` attribute, then it falls back to the table cell text. You can change the targeted attribute by setting the [`imgAttr` option](http://mottie.github.io/tablesorter/docs/#imgattr).

This example uses the [`headers` option](http://mottie.github.io/tablesorter/docs/#headers) to set the parser:

```js
$(function(){
  $('table').tablesorter({
    // parse image title (value to be used while sorting & filtering)
    imgAttr : 'title',
    headers : {
      // this parser is auto-detected, but will only work if there is an
      // image in the cell in the first row
      0 : { sorter: 'image' }
    }
  });
});
```

## Link

If you want to sort by an `href`, then you'll need to set the [`textExtraction` option](http://mottie.github.io/tablesorter/docs/#textextraction) for that column to get the attribute from the link.

This example finds the `href` attribute from the first column (zero-based index):

```js
$(function(){
  $('table').tablesorter({
    textExtraction : {
      // the "url" parser is auto-detected so if your url starts with
      // "http", "https", "ftp" or "file" then it'll work
      0 : function(node, table, cellIndex) {
        return $(node).find('a').attr('href');
      }
    }
  });
});
```

If your url doesn't contain "http", "https", "ftp" or "file", then you can set the parser by adding "sorter-url" to the header, or setting the `headers` option.

**Comment by AviHafner** [comment]
Hey Rob
I put a change to the algorithm that you sent me,
I will be happy if you check it and Approve it,
Or send me right algorithm



    // Custom parser for parsing Href values
       $.tablesorter.addParser({
           id: "href",
           is: function () {
               return false;
           },
           format: function (s, table, cell) {
               var href = $(cell).find('a').attr('href')
            var result=0
            if (typeof  href === "undefined")
               {
                   href = "";
                   result = "";
               }
            else
               {
                   result = 1;
               }


            console.log('href='+href+'\r\nRresult='+result)
            return (result || s );
           },
           parsed: true, // filter widget flag
           type: "numeric"
       })



Hafner Avi
        •    (w): 972-4-829-5728
        • hafner@technion.ac.il<mailto:hafner@tx.technion.ac.il>

**Comment by Mottie** [comment]
Sadly that parser won't work because if an `href` is defined, it saves the cache value as `1`, so the sort will look like it gets stuck. Also, it's set to "numeric" so even if a string was returned, string values become zero (i.e. `parseFloat('foo') // 0`)

Try this parser instead ([demo](http://jsfiddle.net/Mottie/856bzzeL/601/)):

```js
// Custom parser for parsing Href values
$.tablesorter.addParser({
    id: "href",
    is: function () {
        return false;
    },
    format: function (s, table, cell) {
        var href = $(cell).find('a').attr('href') || '',
            // replace protocol
            result = $.trim( href.replace(/(https?|ftp|file):\/\//, '' ) );
        return result || s;
    },
    parsed: true, // filter widget flag
    type: "text"
});
```

I copied the `replace` function from the "url" parser because "http" and "https" should be ignored while sorting.

**Comment by Mottie** [comment]
I'm guessing this issue has been resolved, so I'm going to close it. If you continue to have problems, please feel free to continue the discussion in this thread.
